### ISSUE TITLE
Responsive Line - Is there a way to enable Points only when hovering above the specific point?

### ISSUE THREAD

**Issue by wamiquem** [plouc/nivo#1002]
**Is your feature request related to a problem? Please describe.**
I only found the option of enablePoints by passing the props enablePoints={false} or enablePoints={true} to the whole chart in general. 
Is there a way where I can enable point only when hovering over the specific point?

**Describe the solution you'd like**
Enable points only when the mouse is over the specific point on the Line chart.

**Describe alternatives you've considered**
I did not find any option on the story book.

**Comment by wyze** [comment]
You will need to use a custom layer to achieve this. Here, this should get you started, but might need a little more work to meed your specific needs: https://codesandbox.io/s/upbeat-panini-wobtv
