### ISSUE TITLE
onClick event on radar chart

### ISSUE THREAD

**Issue by AndreiZoitanu** [plouc/nivo#1003]
Hi, is it possible to add onClick event on the Radar chart? Or if that is too complicated, maybe on the lables? Thx.
Andrew

**Comment by brunosantanarj** [comment]
Hi, any update?

**Comment by AndreiZoitanu** [comment]
Hi @brunosantanarj ,  I have a NIVO RADAR build with click event support. You can download it [here](http://d1x7r8pyf695o6.cloudfront.net/nivo_radar_with_click_event.rar). You can use this until they add it to the actual library.

**Comment by brunosantanarj** [comment]
Thanks, @AndreiZoitanu ! Maybe you can open a pull request

**Comment by AndreiZoitanu** [comment]
I was too lazy to work on the source files, I just modified the builded files. Sry :D
