### ISSUE TITLE
Labels overflowing rectangles in treemap

### ISSUE THREAD

**Issue by DigitalNomad1001** [plouc/nivo#1005]
![Screen Shot 2020-06-18 at 3 04 30 PM](https://user-images.githubusercontent.com/22581328/85076525-22b81200-b175-11ea-897c-4f6401667cf3.png)

How do you fit label strings properly? There are no options here.

**Comment by plouc** [comment]
@DigitalNomad1001, there are several options depending on what you're trying to achieve, you can choose to enable `orientLabel`, which will try to orient the label depending on the rect proportion, or use `labelSkipSize` to hide labels which cannot fit in the available space. SVG/canvas do not support text wrap.

**Comment by DigitalNomad1001** [comment]
@plouc --what I am trying to achieve is having the label only display if it fits inside the rectangle space no matter what type of data is being used. If it doesn't fit then it doesn't need to appear. So I guess to achieve this would be using the labelSkipSize to hide the labels which cannot fit in the available space. But it is not working in the tree map I have created for myself. It only lets me adjust up to labelSkipsize 53, any higher number and all labels are hidden. Even though there are larger spaces that should be displaying the labels.
