### ISSUE TITLE
Specifying a numeric `tickValues` updates the ticks, but not the grid lines

### ISSUE THREAD

**Issue by kaiyoma** [plouc/nivo#1008]
**Describe/explain the bug**
Specifying a numeric `tickValues` updates the ticks, but not the grid lines.

**To Reproduce**
https://codesandbox.io/s/nivo-bar-chart-ovly3

**Expected behavior**
The grid lines should update to match the ticks. Instead, there are phantom grid lines without tick labels.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 83
 - Version: 0.62.0

**Comment by plouc** [comment]
@kaiyoma that's the expected behavior, you don't necessarily want the same tick divisions and grid divisions, ticks have labels, while the grid can act as a sub-divider, if you want to update both, please use `gridX|YValues`.

**Comment by plouc** [comment]
For your example, please add `gridYValues={5}`, this will achieve what you want.

**Comment by kaiyoma** [comment]
Got it. Thanks!
