### ISSUE TITLE
x/yFormat Documentation 

### ISSUE THREAD

**Issue by joshzeldin** [plouc/nivo#1018]
Thank you so much for the amazing product!

I'm wondering how I can use the xFormat attribute to leverage d3-formatting. I think this should probably be added to the documentation if you have some time.

![image](https://user-images.githubusercontent.com/20430305/85237288-b39c2100-b3f3-11ea-8b34-33e7b73daae4.png)

 For example, I want to format to two significant digit so I'm using the following line. However, it seems to not pick it up.

`yFormat=".2s"`

Thanks a lot!

**Comment by plouc** [comment]
Hi @joshzeldin, thank you!

I've created a new widget for the demo website which could help understanding how it can be used:

<img width="480" alt="Capture d’écran 2020-06-22 à 08 23 20" src="https://user-images.githubusercontent.com/501642/85237417-ad448e00-b461-11ea-97d4-9a1fa32ea995.png">

It's gonna be deployed when I release the next version.

**Comment by joshzeldin** [comment]
Wow. That's incredible! Is there anywhere to play around with it early before it's released? Thanks so much!

**Comment by plouc** [comment]
@joshzeldin, yes, you can clone this repo, and then run:

```
make init # be patient :)
make website
```

Then you'll have the website running locally on port 8000, for now it's only used for the new funnel package, so please go to http://localhost:8000/funnel/

**Comment by plouc** [comment]
Please use Node.js 12 to run this.

**Comment by joshzeldin** [comment]
Sorry if I misunderstood. Is the x/yFormat on Line graphs not currently in place? I've copied my formatting from the demo site, but still doesn't seem to work. Many thanks!

`yFormat=" <-0,.2s"`

![image](https://user-images.githubusercontent.com/20430305/85238111-b39f1f80-b3f9-11ea-89fd-df398854d6c9.png)

**Comment by plouc** [comment]
Hum, I see, yFormat only format the values, I think you're trying to format the tick labels here, to do so you can add a format property to the `axisLeft` object.
