### ISSUE TITLE
Change background to something other than transparent

### ISSUE THREAD

**Issue by GoetheProductions** [plouc/nivo#1020]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to make the background color of ResponsiveRadar something other than transparrent.

**Describe the solution you'd like**
I would like something like a style prop or a way to change the color scheme of the chart. Another solution could be a simple background prop to the chart

**Describe alternatives you've considered**
I tried giving a parent div a border radius and a background color, but that did not work 

**Additional context**
I am making a component where the ResponsiveRadar component overlabs a table a little bit and this is why i need the radar to not be transparent

**Comment by wyze** [comment]
You can set the `background` property of `theme` prop. See here: https://codesandbox.io/s/patient-butterfly-dq53o

**Comment by GoetheProductions** [comment]
Hello.

There is an error in your example on the prop ``theme``, and when looking in the type definition, i do not see a prop called theme?

Here is the interface:

```
interface CommonRadarProps<Datum = any> {
        data: object[]
        keys: Array<string | number>
        indexBy: number | string | IndexByCustomFunctiono<Datum>
        maxValue?: 'auto' | number

        margin?: Box

        curve?: string

        borderWidth?: number
        borderColor?: InheritedColorProp

        gridLevels?: number
        gridShape?: 'circular' | 'linear'
        gridLabel?: GridLabelCustomFunction
        gridLabelOffset?: number

        enableDots?: boolean
        dotSymbol?: CustomDotSymbol
        dotSize?: number
        dotColor?: InheritedColorProp
        dotBorderWidth?: number
        dotBorderColor?: InheritedColorProp
        enableDotLabel?: boolean
        dotLabel?: string | CustomDotLabel
        dotLabelFormat?: string | CustomFormatter
        dotLabelYOffset?: number

        colors?: OrdinalColorsInstruction
        fillOpacity?: number
        blendMode?: CssMixBlendMode

        isInteractive?: boolean
        tooltipFormat?: string | CustomFormatter

        legends: LegendProps[]
    }
```

**Comment by GoetheProductions** [comment]
I have added: `theme?: any` to the interface, however this should dissapear when modules are updated. Will you add something similar to the code? It compiles without errors when adding this, so it should be a small thing :)
