### ISSUE TITLE
Documentation about Theming?

### ISSUE THREAD

**Issue by altrang** [plouc/nivo#1022]
Hello everyone,
I m new to this librairy and it seems amazing thanks for your work !
I was wondering how to customize GridY and it seems that using theme props i could do so. ITs working but is there a doc concerning this theme object? what kind of thing can i customize using this? 

Thank you !

**Comment by wyze** [comment]
No official documentation, but you can see what is used by looking at the default theme: https://github.com/plouc/nivo/blob/master/packages/core/src/theming/defaultTheme.js

**Comment by altrang** [comment]
Thanks a lot !
