### ISSUE TITLE
Custom patterns (patternomaly support?)

### ISSUE THREAD

**Issue by mkpietrzyk** [plouc/nivo#1025]
Hi! First of all, thank you so much for such great library, we have a blast using it! 

Our team currently face a problem of displaying multiple layers of lithology formations for different depth stacks. Your stacked Bar component seems excellent for this task, especially looking at the extra fill patterns we can provide to the data. However, it's not enough for us in a current state by looking at [Nivo patterns guide](https://nivo.rocks/guides/patterns/)

**Describe the solution you'd like**

We would like to use multiple custom patterns to define our stacked bars. Below is the example image of such patterns:

http://publications.iodp.org/proceedings/367_368/102/figures/367368_102_F04.png
![image](https://user-images.githubusercontent.com/23457146/85705489-8d230200-b6e1-11ea-83dd-8b1bab17cbf2.png)

However, we understand that it could be a little too complex, so we tried looking for alternatives.

**Describe alternatives you've considered**

We have found that `chart.js` library can be used with `patternomaly` : https://github.com/ashiguruma/patternomaly 

I think this is the closest to what we would like to achieve. If such thing would be available in Nivo, that would allow us to stay with Nivo-only usage 😃 

![image](https://user-images.githubusercontent.com/23457146/85706207-4386e700-b6e2-11ea-8e93-316c4ece2419.png)

**Comment by wyze** [comment]
You might be able to build some with our current pattern support. https://nivo.rocks/guides/patterns

It is just very simple and not able to support custom patterns currently, but it might be something we can look into in the future.

**Comment by mkpietrzyk** [comment]
Thank you for the response. 

Eventually, we have discussed with project owner and decided to followup using basic pattern customisation you guys provide by default (as you linked towards you pattern customization) turns out, colors will mostly matter so in terms of patterns we will be using diagonal lines and dots 🙂

Nontheless, I will bookmark this issue if you guys decide to include custom pattern support eventually.
