### ISSUE TITLE
continue line over holes in data

### ISSUE THREAD

**Issue by pietervanwijk** [plouc/nivo#1026]
**Is your feature request related to a problem? Please describe.**
For a client i need to make a line chart where the data on the x-axis has holes but the line needs to be continuous. Going straight from the last non-null data point to the next.

**Describe the solution you'd like**
A boolean parameter that makes the line continue over holes or disappear over holes

**Describe alternatives you've considered**
I could calculate the values in between the known data points myself to artificially make such a line but it gets hard with curved lines

**Comment by arkatriymfalnaya** [comment]
bump

**Comment by tkonopka** [comment]
The original question is a few years old, so it may be referring to an early version. In any case, it is now possible to draw lines with and without gaps (see example below). To continue a line over holes in the data, just filter the data to remove null values.

![2022-07-11-gaps](https://user-images.githubusercontent.com/7260190/178265311-c543b5b9-5a2d-4560-9997-a5d32f111dcf.png)

https://codesandbox.io/s/trusting-river-2r89dm?file=/src/App.js

**Comment by arkatriymfalnaya** [comment]
@tkonopka thanks a lot for your answer!
but i've tried to explain a bit different solution, for example:
![Screenshot 2022-07-11 at 15 41 26](https://user-images.githubusercontent.com/32422684/178266615-71c2cf5a-393e-4fd7-a508-ff7d2da70ff7.png)
the point is not to filter nullish x'es but to 'highlight' it and not to lose a gradient, like in your example.

**Comment by madhuraman-nauto** [comment]
> highlight

@arkatriymfalnaya : could you provide me with a sample of how you achieved the dotted lines between two non-null data points when it has a null data point in between? I have a situation in my line graph where i will need to connect the missing data between two points with a dotted line.

**Comment by manchaary** [comment]
I ended up adding extra points to connect holes in data

**Comment by madhuraman-nauto** [comment]
@manchaary can you provide a snippet of your LineGraphComponent. Did you mean by using two data sets, you achieved the connection?

**Comment by manchaary** [comment]
@madhuraman-nauto yes, I have created two data sets of Datum to connect them.

`const data1 = [
  { x: 1, y: 2.5 },
  { x: 2, y: 2.4 },
  { x: 3, y: null },
  { x: 4, y: null },
];
const data2 = [
  { x: 1, y: null },
  { x: 2, y: 2.4 }, <- connecting point
  { x: 3, y: 2.3 },
  { x: 4, y: 2.2 },
];`

**Comment by madhuraman-nauto** [comment]
adn is there a way to have the connecting line alone in a different line format like dotted lines or dashed lines? can we define separate line format for each data set?

**Comment by manchaary** [comment]
@madhuraman-nauto yes absolutely, just define an id for each Datum and add custom Layer to have custom styling for each chart line, you even can achieve different gradient styling too. I think you can find how to style Line in a storybook of the nivo/line
