### ISSUE TITLE
LineChart: Slices disappear with standard layers defined

### ISSUE THREAD

**Issue by headfox23** [plouc/nivo#1027]
The linear layer type is the following:
```
    export type LineLayerType =
        | 'grid'
        | 'markers'
        | 'axes'
        | 'areas'
        | 'lines'
        | 'slices'
        | 'points'
        | 'mesh'
        | 'legends'
```

The proptypes of the code expects the following :
`['grid', 'markers', 'axes', 'areas', 'crosshair', 'lines', 'slices', 'points', 'mesh', 'legends']`

If the crosshair is missing, slices and other crosshairs are missing.

To get it to work with typescript the following works:
`layers={['grid', 'markers', 'axes', 'areas', 'crosshair' as any, DashedLine, 'slices', 'points', 'mesh', 'legends']}`

**Comment by wyze** [comment]
This was fixed in #917 and is released in the latest version.
