### ISSUE TITLE
border line on x and y axis

### ISSUE THREAD

**Issue by jerryjcchang** [plouc/nivo#1030]
Is there a property available for setting a line on the X and Y axis of a Responsive Bar Chart (example: https://wcs.smartdraw.com/bar-graph/img/simplebarchart.jpg?bn=1510011165) without having to toggle enableGridY to 'true'?

**Comment by plouc** [comment]
Yes, the next release will include documentation for it, you can use a theme object for this, something like this:

```javascript
const theme = {
    axis: {
        domain: {
            line: {
                stroke: '#777777',
                strokeWidth: 1
            }
        }
    }
}
```

then you can pass this to the `theme` property.

**Comment by ssbarbee** [comment]
Hey @plouc is it possible to have the line appear on the right side of graph as well? Using the theme makes it appear on left and bottom.
