### ISSUE TITLE
Legends Disappear

### ISSUE THREAD

**Issue by HadiKhai** [plouc/nivo#1031]
Hello, is there a way to show the legends despite the data being 0, for example, if I have the following data for the bar chart: `[{
date: ...,
key1: 0,
key2: 2,
key3: 10
}]
`
Only the legends for keys 2 and 3 will appear while I need all the keys to be shown. Thank you

**Comment by diegosps** [comment]
This might be a duplicate.

**Comment by sibelius** [comment]
is there a workaround for this?
