### ISSUE TITLE
Bar Chart - Tooltip isn't being rendered when using custom layers

### ISSUE THREAD

**Issue by thisizkp** [plouc/nivo#1033]
Hey, Thanks for the amazing project. I need some help with the `Bar` chart component.

I've customized the `Bar` chart component using layers.

```js
<ResponsiveBar
   layers={['grid', 'axes', Bars, 'markers', 'legends', 'annotations']}
   ...
/>
```

Bars are being rendered fine, but tooltips are not working anymore. How do I make tooltips work with the custom layers?

I tried searching for the existing issues & storybook examples, but couldn't find anything with custom layers & tooltips. Please point me out in the right direction.

**Comment by plouc** [comment]
@thisizkp, if you want to use a custom layer for bars, you also need to attach the proper event handlers to the bar items, you can have a look at the default [BarItem](https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.js) for guidance.
