### ISSUE TITLE
Question: is there a way to center bars?

### ISSUE THREAD

**Issue by onionhammer** [plouc/nivo#1034]
Is there a way to center bars horizontally? I'm looking to make a sort of 'funnel' shape

![image](https://user-images.githubusercontent.com/969938/85865332-56a1c180-b78b-11ea-9543-b848f91ffee5.png)

**Comment by wyze** [comment]
There is actually a funnel chart that will be released in the next version: https://github.com/plouc/nivo/tree/master/packages/funnel

But to answer the question, you might be able to achieve what you want by trying a custom layer and replace the `bars` layer.
