### ISSUE TITLE
Treat zero as empty in Calendar component 

### ISSUE THREAD

**Issue by iamchathu** [plouc/nivo#1036]
**Is your feature request related to a problem? Please describe.**

Api endpoint sends 0 for no data dates for the give range. For that data it displays lowest color rather than empty color.

**Describe the solution you'd like**
Option to treat zero as empty or the values less than min value to be treated as empty.

**Describe alternatives you've considered**
I tried setting min value to 1 but it doesn't work.

**Comment by plouc** [comment]
HI @iamchathu, I'm not sure treating 0 as a null/undefined value would be a good API, 0 is perfectly fine as a value, and setting some kind of threshold for null values doesn't seem ideal either as the min/max values are used to clamp and segment the values reaching those limits in the proper cluster, I think you could transform the data you get from your API instead. something like this maybe:

```javascript
const normalizedData = rawApiData.filter(datum => datum.value !== 0)

# or using memoization to improve performance
const normalizedData = useMemo(() => rawApiData.filter(datum => datum.value !== 0), [rawApiData])
```
