### ISSUE TITLE
Interactivity Mouse Hover Options for Stream Chart

### ISSUE THREAD

**Issue by DigitalNomad1001** [plouc/nivo#1038]
I would like the option to have the hover details to be consistent and just display the full data like when it's hovering over the vertical line.

When the mouse hovers over the data in between the vertical lines it just displays the name detail. I would like to remove the name detail that appears on the hover. 

I have tried:
```
isInteractive={false}
enableStackTooltip={false}
```
and adding:

```
onMouseEnter={(_data, event) => {
    event.target.style.opacity = ".5";
}}
onMouseLeave={(_data, event) => {
    event.target.style.opacity = 1;
}}
tooltip={({ indexValue, value, color }) => (
    <div>
        <span style={{ backgroundColor: color }}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
         <strong className="ml-2">
              Prediction Score {indexValue}: {value}
         </strong>
    </div>
)}

```

But it doesn't work.

**Comment by DanWttvn** [comment]
Try "event.currentTarget.style...."
It worked for me
