### ISSUE TITLE
Donut legend symbol 

### ISSUE THREAD

**Issue by jdeanquin-dg** [plouc/nivo#1041]
I had the need to implement a donut instead of a circle for a project im working on. Are you interested that i commit a donut symbolShape? Currently im using a custom symbol but wondering if it wouldn't make sense to have it within the lib
Thanks for all the hard work, the charts are amazing 
![image](https://user-images.githubusercontent.com/15792006/86276425-39199100-bbab-11ea-89be-34f3d9970d25.png)

**Comment by ModiteCrisRojas** [comment]
@jdeanquin-dg that's really cool! Would you mind just sharing your code here, I'm looking into how to create custom legend symbols and a real-life example would be awesome!
