### ISSUE TITLE
Hiding or removing non-tick axis lines

### ISSUE THREAD

**Issue by kaeland** [plouc/nivo#1044]
Hi, 

Thank you all for the work you're doing on Nivo. It really is a great library to use. 

I'm wondering if there's a way to hide/remove "non-tick" axis lines for the `ResponsiveBar` component. Currently, I'm implementing a horizontal bar chart, and I'm attempting to display tick values (w/ axis lines) along the x-axis for the chart. At the moment, the chart is also rendering additional vertical lines between the `axisBottom`'s `tickValues` I've specified to be displayed.  

Is there a way to remove the additional vertical axis lines drawn between the tick axis lines?

Here is a codesandbox of the chart I'm working on: [link](https://codesandbox.io/s/distracted-cache-1r5zf?file=/src/App.js)

**Comment by wyze** [comment]
You can use `gridXValues={[0, 50, 100]}` that will match your tickValues on the x-axis.

**Comment by kaeland** [comment]
I love a simple solution. Thank you so much!
