### ISSUE TITLE
Adding events to ResponsiveCalendar

### ISSUE THREAD

**Issue by gabrieldespindula** [plouc/nivo#1046]
**Is your feature request related to a problem? Please describe.**

I wish to add some special color when something happen. For example tag a day as raining if the calendar shows how much I ran or tag important events to consider in specific days. I believe they all could have same color as "eventColor".

**Describe the solution you'd like**

I already have coded to my needs, but think could be an interesting add on for other applications as well (if you want to add this).
What I did was adding a check to the value properties, if it was number it just works same way, if its a string it considers an event. This way it renders an "eventColor" and the tooltip show whatever I wrote in the value property.

Sumarizing: 
```
...
if (dayData.day === day.day) {
  day.value = dayData.value;
  day.color = Number.isInteger(dayData.value) ? colorScale(dayData.value) : eventColor;
  day.data = dayData;
}
...
```
Apart from this line of code is just necessary to add the event color and change some point where it estimates the color scale based on value. In this case is possible to just ignore non numeric values using Number.isInteger as well.

The only thing I didn't do was adding a legend to the event when it's used, but I don't think that's too complicated, considering is not necessary a different color to every different event but just an "event" color.

As the tooltip already shows value, when we set a string it works pretty well and the result is quite cool.

**Describe alternatives you've considered**

I tried to set all my events as a negative or lower value and create a custom tooltip (not so elegant), but the result wasn't so good because in this case I needed to set the minimum to avoid showing a very low value in the legend and as the color is a gradient was hard to set in a good way, it would depend a lot in my samples range.

**Additional context**

Well, if you have interest I can take a look in your code standards, complement my code to feature a legend box and contribute with a piece of code.

![image](https://user-images.githubusercontent.com/20251817/86485302-b59da280-bd58-11ea-9275-b68804901a9d.png)

**Comment by diegosps** [comment]
You can have this behavior using a custom color scale function.

https://github.com/plouc/nivo/pull/703

But I'm no sure if this is in the npm package

**Comment by wyze** [comment]
I think we will pass on this feature and keep it in userland. Thanks!
