### ISSUE TITLE
Include color in data for Bar chart tooltip

### ISSUE THREAD

**Issue by thomasthiebaud** [plouc/nivo#1049]
I would like to have access of the color of every series in the tooltip on a Bar chart. Today I only get the color of the value I'm hovering (https://github.com/plouc/nivo/blob/master/packages/bar/index.d.ts#L42).

Would it be possible to have something similar to the `sliceTooltip` on the Line chart (https://github.com/plouc/nivo/blob/master/packages/line/index.d.ts#L108)?

**Comment by diegosps** [comment]
Map all colors to your data or declare it outside:

```
const colors = [
        { key: "a", value: "red"},
        { key: "b", value: "blue" },        
    ]
const data = [
        { key: "a", value: 1 },
        { key: "b", value:2},        
    ]
const labels = [
        { key: "a", value: "Hamburguer" },
        { key: "b", value: "Salad" },
]
```
...
```
<ResponsiveBar
   keys={['a', 'b']}
   data={data}
   colors={['red','blue']}
   tooltip={d => {
                                        return (<ul style={{ listStyleType: "none", padding: 0 }}>
                                            {
                                                labels.map((item, index) =>
                                                    <li key={"lg" + index}>
                                                        <div className={classes.legendRow}>
                                                            <div className={classes.legendBox} style={{ background: colors[index].value }}>
                                                            </div>
                                                            <Typography variant={d.id === item.key ? "subtitle2" : "caption"} color={d.id === item.key ? "secondary" : "textPrimary"} >{labels[index].value + ": " + d.data[item.key]} </Typography>
                                                        </div>
                                                    </li>
                                                )}
                                        </ul>)
   }}
...
/>
```

**Comment by thomasthiebaud** [comment]
Yes sure, this is a valid workaround, but ultimatly what I want is a SliceTooltip for a bar chart.

**Comment by diegosps** [comment]
What is SliceTooltip?
![image](https://user-images.githubusercontent.com/1766388/87057552-65519500-c1dd-11ea-86f8-563b56241d35.png)
Something like this?

**Comment by thomasthiebaud** [comment]
yes, like that. I guess you do that by iterating over `data`?

**Comment by diegosps** [comment]
> yes, like that. I guess you do that by iterating over `data`?

The code that I posted does that.
In my case it iterates over label: "Até 1 ano", "12 a 18 meses", ...
and finds the respective keys in colors and data

**Comment by thomasthiebaud** [comment]
Check the `Line` component. It has that feature build in. What I'm asking in this issue is if it is possible to provide the same feature for the Bar component.
I have a workaround live for now, but having to do it makes it harder to reuse the component accross the app

**Comment by ClaireSheek** [comment]
Bump! 
I second this request!
