### ISSUE TITLE
Can't pass colors into ResponsiveHeatMapCanvas cells

### ISSUE THREAD

**Issue by ramikhalayleh** [plouc/nivo#1050]
I need to pass custom colors into  ResponsiveHeatMapCanvas cells, but facing an issue in that, the colors defined in data, have no effects.
Details how implemented:
        <ResponsiveHeatMapCanvas
            data={props.data}
            keys={keys}
            indexBy="site"
            margin={{ top: 20, right: 30, bottom: 20, left: 0 }}
            pixelRatio={1.25}
            minValue="auto"
            maxValue="auto"
            height={400}
            forceSquare={false}
            sizeVariation={0}
            padding={0}
            colors="RdYlBu"
            axisTop={null}
            axisLeft={null}
            axisRight={{
                orient: 'right',
                tickSize: 5,
                tickPadding: 3,
                tickRotation: 0,
                legend: '',
                legendPosition: 'middle',
                legendOffset: 0
            }}
            axisBottom={null}
            enableGridX={false}
            enableGridY={false}
            cellShape="rect"
            cellOpacity={1}
            cellBorderWidth={0}
            cellBorderColor={{ from: 'color', modifiers: [ [ 'brighter', 0.6 ] ] }}
            enableLabels={false}
            labelTextColor={null}
            animate={false}
            motionStiffness={120}
            motionDamping={0}
            isInteractive={true}
            hoverTarget="cell"
            cellHoverOpacity={0.5}
            cellHoverOthersOpacity={1}
        />

const data = [
  {
    "site": "AD",
    "1": 80,
    "1Color": "hsl(27, 70%, 50%)",
    "2": 36,
    "2Color": "hsl(205, 70%, 50%)"
}]

Tried to change colors from data 1Color and 2Color, didn't work.

Could you please advise why the colors passed in data have no effects?
Also tried to create custom shape, it didn't work on ResponsiveHeatMapCanvas. Doesn't it supported on this component?

Thanks in advance

**Comment by wyze** [comment]
It looks like the heatmap doesn't support custom colors in this way. Also, looks like the canvas implementation only supports rect or circle cells. I'd be willing to accept a PR to add custom cell function to bring it on par with the non-canvas implementation.
