### ISSUE TITLE
Misleading points displayed in stacked line chart if some values are zero

### ISSUE THREAD

**Issue by phacks** [plouc/nivo#1051]
**Describe/explain the bug**

In a stacked line graph with points, the top-most point will always be displayed on top (and covering entirely) points below it. This can be misleading if some intermediate values in that graph are 0, and can result in an incorrect reading of the graph, as illustrated in the screenshot below.

**To Reproduce**
I’ve set up a repro on this CodeSandBox: https://codesandbox.io/s/nivostacked-line-misleading-points-ublb7

**Expected behavior**

In a stacked line graph with points enabled, points with a value of 0 should not appear on top of (and covering entirely) points that have a value that is non-0.

I think that giving priority to the bottom-most point will solve this problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/2587348/87164913-ab842280-c2c9-11ea-9c5a-daf911028a9e.png)

In that screenshot, reading the graph makes me think that there was 1 PR merged and 0 PR opened, although the reality (as shown in the tooltip) is the other way around.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome latest
 - Version: 0.62.0

I’m willing to work on a PR if you think this is indeed an issue.

**Comment by wyze** [comment]
Indeed this is confusing, a PR would be great!

**Comment by phacks** [comment]
Sure thing, it’s over at #1060 😀

**Comment by plouc** [comment]
While I understand the problem, I'll probably have to revert the fix for a11y and supporting keyboard navigation, as the resulting order in the dom isn't very natural.
