### ISSUE TITLE
Add right click contextmenu functionality 

### ISSUE THREAD

**Issue by bhavyajeet** [plouc/nivo#1052]
**Is your feature request related to a problem? Please describe.**
I am unable to open a context menu when there is a right click on any one of the data elements of a chart

**Describe the solution you'd like**
an option to handle the right click in the same manner as the onClick handler

**Comment by damianr13** [comment]
This is my workaround for a context menu in nivo: 

We add another layer in the chart. That layer implements the mouse handling logic. 

Example for a bar chart: 

```typescript
const MyCustomLayer = (props: BarCustomLayerProps<any>) => {
  return (
    <>
      {props.bars.map((bar) => (
        <rect
          key={bar.key}
          x={bar.x}
          y={bar.y}
          width={bar.width}
          height={bar.height}
          onContextMenu={(e) => {
            e.preventDefault();
            e.stopPropagation();
          }}
          fillOpacity={0}
        />
      ))}
    </>
  );
};
```

And we use it like this: 
```typescript
<ResponsiveBar
        ...
        layers={[
          "grid",
          "axes",
          "bars",
          "markers",
          MyCustomLayer,
          "legends",
          "annotations",
        ]}
  />
```
