### ISSUE TITLE
Custom design to box with no data in Heatmap

### ISSUE THREAD

**Issue by Sakshisrivastava413** [plouc/nivo#1053]
Is their a way to have change the color of the no data box instead of **black box**. I want to show a white box with a cross in it to represent that the data for that box is not found. Please let me know how can I customise the heatmap boxes in this situation.
<img width="356" alt="Screenshot 2020-07-13 at 5 51 35 AM" src="https://user-images.githubusercontent.com/32509093/87260025-fe79f780-c4cc-11ea-87af-5abf19777fd4.png">

**Comment by wyze** [comment]
I'm not sure we provide the ability to add something inside a cell without data, but you can use `nanColor` prop to change the color. The cross could possibly be done with a custom cell component: https://nivo.rocks/storybook/?path=/story/heatmap--custom-cell-component
