### ISSUE TITLE
Show empty grid values in Y axis

### ISSUE THREAD

**Issue by Mujaddadi** [plouc/nivo#1056]
First, I would like to thank you for this awesome library. I appreciate the hard work on it. I have a small issue. I want to show empty Y scale values if there is no data for it. At the moment it just show only values in Y scale which have data. In my situation it can be empty chart also. I posted bellow the code which I am using just to give you better idea. As you can see from my code, I tried the solution mentioned in #349. It would be good to mention that the Y scale doesn't contain numeric values so min and max doesn't make much sense here. 

```
<ResponsiveLine
        data={data}
        margin={{ top: 50, right: 30, bottom: 50, left: 60 }}
        curve="cardinal"
        xScale={{ type: 'point' }}
        yScale={{
          type: 'point',
          min: `${gridYValues[0]}`,
          max: `${gridYValues[gridYValues.length - 1]}`,
          stacked: true,
          reverse: false,
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          orient: 'bottom',
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: `${categoryData.name} evaluation`,
          legendOffset: 36,
          legendPosition: 'middle',
        }}
        axisLeft={{
          orient: 'left',
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legendOffset: -40,
        }}
        gridYValues={gridYValues}
        colors={{ scheme: 'accent' }}
        pointSize={10}
        pointColor={{ theme: 'background' }}
        pointBorderWidth={2}
        pointBorderColor={{ from: 'serieColor' }}
        pointLabel="y"
        pointLabelYOffset={12}
        useMesh={true}
        legends={[]}
      />
```

**Comment by wyze** [comment]
Can you show a sample of the `data` and `gridYValues` variables so we can get a more complete picture?

**Comment by Mujaddadi** [comment]
Here is an example of  `data`

```
[
  {
    "data": [
      {
        "x": "18.06.2020",
        "y": "Some text"
      },
   {
        "x": "18.06.2020",
        "y": "Some text"
      },
    ]
  }
]
```

Here is example of `gridYValues `

```
["Yes",  "No",  "Not selected"]
```

**Comment by Mujaddadi** [comment]
Could you please tell me how to achieve what I asked in question?

**Comment by wyze** [comment]
I put together a codesandbox with your code, https://codesandbox.io/s/vigilant-easley-xq44e, but confused on what what exactly you are trying to achieve. I'm not sure the yScale can go off of text values like that, so what you could do is assign a value to `y` and do a lookup for your format function on `axisLeft`.

**Comment by Mujaddadi** [comment]
I understand. That what I will do with the YScale values.  My question is, how to show empty graph or all the YScale values even if there is no value for it in the data.

**Comment by Mujaddadi** [comment]
@wyze Any hint how to achieve the above?

**Comment by wyze** [comment]
I'm not sure it would be possible out of the box. Would likely need a custom layer to render the values you want when there is no data.

**Comment by Hari-0210** [comment]
const data = [
    {
      id: 'ECOM',
      color: '#F7B34D',
      data: [
        {
          x: '2023-07-21',
          y: -1448.3,
        },
        {
          x: '2023-07-22',
          y: -307.98,
        },
        {
          x: '2023-07-23',
          y: -1012.08,
        },
      ],
    },
    {
      id: 'UNSETTLE',
      color: '#3AD1C8',
      data: [
        {
          x: '2023-07-21',
          y: -448.3,
        },
        {
          x: '2023-07-22',
          y: -3946.98,
        },
        {
          x: '2023-07-23',
          y: -1896.08,
        },
      ],
    },
    {
      id: 'POS',
      color: '#4B25B6',
      data: [
        {
          x: '2023-07-21',
          y: -75,
        },
        {
          x: '2023-07-22',
          y: -3666,
        },
        {
          x: '2023-07-23',
          y: -884,
        },
      ],
    },
    {
      id: 'SETTLE',
      color: '#1EC5FA',
      data: [
        {
          x: '2023-07-21',
          y: -1075,
        },
        {
          x: '2023-07-22',
          y: 0,
        },
        {
          x: '2023-07-23',
          y: 0,
        },
      ],
    },
    {
      id: 'REFUND',
      color: '#347235',
      data: [
        {
          x: '2023-07-21',
          y: 0,
        },
        {
          x: '2023-07-22',
          y: 27,
        },
        {
          x: '2023-07-23',
          y: 0,
        },
      ],
    },
  ]
  This is my data
  <ResponsiveLine
                      data={data}
                      margin={{ top: 20, right: 200, bottom: 90, left: 100 }}
                      xScale={{ type: 'point' }}
                      yScale={{
                        type: 'linear',
                        min: 'auto',
                        max: 'auto',
                        stacked: true,
                        reverse: false,
                      }}
                      curve="basis"
                      axisTop={null}
                      axisRight={null}
                      axisBottom={{
                        tickSize: 5,
                        tickPadding: 5,
                        tickRotation: 0,
                        legend: 'File Date',
                        legendOffset: 36,
                        legendPosition: 'middle',
                      }}
                      axisLeft={{
                        tickSize: 5,
                        tickPadding: 5,
                        tickRotation: 0,
                        legend: 'Amount',
                        legendOffset: -90,
                        legendPosition: 'middle',
                      }}
                      enableGridX={false}
                      enablePoints={false}
                      pointSize={10}
                      pointColor={{ theme: 'background' }}
                      pointBorderWidth={2}
                      pointBorderColor={{ from: 'serieColor' }}
                      pointLabelYOffset={-12}
                      useMesh={true}
                      legends={[
                        {
                          anchor: 'bottom-right', // Position the legend at the bottom-right corner
                          direction: 'column', // Display the legend items in a row
                          justify: false,
                          translateX: 90, // Move the legend horizontally (adjust as needed)
                          translateY: 0, // Move the legend vertically (adjust as needed)
                          itemsSpacing: 0,
                          itemDirection: 'left-to-right',
                          itemWidth: 80,
                          itemHeight: 20,
                          itemOpacity: 0.75,
                          symbolSize: 12,
                          symbolShape: 'circle',
                          symbolBorderColor: 'rgba(0, 0, 0, .5)',
                          effects: [
                            {
                              on: 'hover',
                              style: {
                                itemBackground: 'rgba(0, 0, 0, .03)',
                                itemOpacity: 1,
                              },
                            },
                          ],
                        },
                      ]}
                    />
                    I cant able to see refund values
                    And refund also not in correct place
