### ISSUE TITLE
Better tree shake support

### ISSUE THREAD

**Issue by matthewkwong2** [plouc/nivo#1063]
**Is your feature request related to a problem? Please describe.**
I noticed when I import `ResponsiveRadar` from `@nivo/radar`, some of the packages are bundled despite I did not use them.

e.g. If I create a radar chart as follow:
```jsx
<ResponsiveRadar
    data={data.about.languages}
    indexBy='name'
    keys={keys}
    maxValue={100}
    colors={theme.palette.primary.main}
    isInteractive={false}
    enableDots={false}
    borderWidth={0}
    fillOpacity={1}
    margin={margin}
 />
```
The `legend`, `tooltip` and `colors` packages are bundled despite 
1. `legends` is not specified (legend will not render).
2. `isInteractive={false}` is specified (tooltip will not render).
3. Define my own colour(s) (in this case, colours defined in `material-ui` theme is used, so the "theme" of the Nivo charts will not be used).

![image](https://user-images.githubusercontent.com/32725014/87615583-a00b7e00-c745-11ea-998b-37b450835d77.png)

Similar situations apply to other options as well, like if I set `animate={false}`, `react-motion` is bundled regardless.

**Describe the solution you'd like**
I would like the Nivo charts to have better tree shake support, namely some packages are dynamically imported depending on the value of some options, since the bundle size of this library is quite large and bundling unnecessary packages have significant impact on the initial load performance.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by plouc** [comment]
I think this is different from tree-shaking, you can opt-in for features, but you still have those packages used, I'm not aware of an approach to dynamically import and include code or not depending on runtime options, tree shaking basically relies on a static structure.

**Comment by plouc** [comment]
Also note that even if you use your own color scheme, the `colors` package is used to compute inherited colors.
