### ISSUE TITLE
Question: Is it possible to make width of bar item proportional to some data property?

### ISSUE THREAD

**Issue by onionhammer** [plouc/nivo#1067]
I have bar height based on 1 property, is it possible to base the width on another property? I've tried creating my own BarItem but I run into obscure issues around the pure/compose around mouseenter/mouseleave tooltip functionality.

**Comment by wyze** [comment]
I was going to suggest using a custom BarItem to achieve this. What kind of issues are you having? Can you post a codesandbox with what you have?

**Comment by onionhammer** [comment]
I'll try to reproduce it tomorrow in a codesandbox

**Comment by onionhammer** [comment]
I was able to reproduce in a stripped down version on codesandbox. I'm sure I'm doing it wrong, but I wasnt able to find a sample of how to do it right; What would be handy is if this sample tooltip support; ideally without having to add in dependencies like recompose;
https://nivo.rocks/storybook/?path=/story/bar--custom-bar-item

Here's the sandbox with the error I mentioned, hover over the bar to reproduce.
https://codesandbox.io/s/heuristic-field-fde49?file=/src/App.js
