### ISSUE TITLE
Changing hover text for ResponsiveLine

### ISSUE THREAD

**Issue by ilirosmanaj** [plouc/nivo#1070]
Hi all,

I am using ResponsiveLines to visualize some of my data and I want to change the default text that is displayed on hover. As far as I know, this should be done using tooltips. Unfortunately, I did not find any working example of tooltips with ResponsiveLines (even though from [this issue](https://github.com/plouc/nivo/issues/192), it seems like its implemented.

Can someone help me by pointing out some docs or something relevant? Maybe I am just missing some important documentation somewhere.

Thank you in advance

**Comment by wyze** [comment]
You can see a storybook of custom tooltip here: https://nivo.rocks/storybook/?path=/story/line--custom-tooltip
