### ISSUE TITLE
Support for different time intervals on Line chart?

### ISSUE THREAD

**Issue by vpfaulkner** [plouc/nivo#1072]
Hey there!

I'm not sure if the library currently supports this or not so wanted to clarify.

I'm building a time-based Line chart with two series: one which has a data point every 10 minutes and another which has a data point every hour. Is that possible?

All of the examples show uniform intervals across series.

If not, I'm guessing I'll need to split-up the hour-interval series to actually have a point every 10 minutes so they are uniform, but use the layers feature to hide the "circle" on all but the hourly times. Or, perhaps I use stacking? Any suggestions about the best approach would be helpful.

Thanks for this great library!

Vance

**Comment by wyze** [comment]
You won't be able to have different xScale values per series. Your best bet would be to split the hour series into 10 minute equivalent. If you kept it at the hour mark, it would work but would be considered "holes in data" and would likely just put a point and not draw a line to connect the points.
