### ISSUE TITLE
Pie slices with zero size cause additional padding

### ISSUE THREAD

**Issue by vdh** [plouc/nivo#1077]
**Describe/explain the bug**

Pie slices with zero size cause "gaps" to appear when `padAngle` is greater than 0.

**To Reproduce**
https://codesandbox.io/s/nivo-pie-slice-zero-padding-issue-bw1ik?file=/src/App.js

1. Include data with zero value.
2. Set `padAngle` higher than 0.
Padding glitch becomes more apparent with more items with zero value.

**Expected behavior**

Ideally, a pie slice with zero value would not cause padding to generate. On static charts this can be avoided by removing zero-value items, but on dynamic charts where legends ideally shouldn't have items removed, sometimes zero-value slices will exist.

**Comment by vdh** [comment]
bump

**Comment by ossim** [comment]
bump. This issue is also happening with borders where 0-value slices still have their borders drawn. 

<img width="50" alt="image" src="https://user-images.githubusercontent.com/7756887/103821632-7744b100-5023-11eb-88e2-3b92a8afc276.png">

**Comment by mikejackowski** [comment]
any updates on this?

**Comment by HodayaGruz** [comment]
have that problem too, any solutions?
