### ISSUE TITLE
Allowing pagination for Legends?

### ISSUE THREAD

**Issue by fpezzola** [plouc/nivo#1078]
Is there a way to show the legends paginated? 
I am trying to show a huge dataset and the legends are being cut by the height of the parent div. 

It would be great if i can specify a limit of legends to be shown per page along with a list of `hiddenIds` to allowing the user to disable/enable a serie (I know this feature is already implemented in the Pie chart).

**Comment by Pato91** [comment]
This or trying to make legends scrollable for custom legends would improve interactivity

**Comment by plouc** [comment]
This is unfortunately not something we're willing to add to nivo, this would add a bunch of extra properties, when legends are getting really long/complex, I would suggest to build them in html outside of the charts, this is more flexible, especially for text handling which is definitely limited in SVG/canvas.
