### ISSUE TITLE
Any way to create population pyramid

### ISSUE THREAD

**Issue by mrpotato3** [plouc/nivo#1083]
Is there any way to create a population pyramid like this:

![image](https://user-images.githubusercontent.com/9481003/89327261-f0fafc00-d68b-11ea-8859-4d578f486aa1.png)

Now I have a bar chart like this:

![image](https://user-images.githubusercontent.com/9481003/89327354-1a1b8c80-d68c-11ea-88f3-05c1bddc654e.png)

Many thanks!

Good job!

**Comment by nnmrts** [comment]
I hate the stale bot so much, it's crazy. Alright then, lemme create a new issue with the exact same content, I guess...
