### ISSUE TITLE
Add legend item without drawing bar 

### ISSUE THREAD

**Issue by altrang** [plouc/nivo#1087]
Hello guys.
I m using a barGraph with a line layer in order to display bars and line on the same graph. I was wondering if there is a way to add a legendItem without drawing a bar linked to this legend. 
If i add in the keys array the key i want as legend then a bar will automatically be drawned. I would like just the legend Item (linked to my line) without bar graph

**Comment by wyze** [comment]
You should be able to use the `legends` prop and override data. 

```tsx
function Chart() {
  return <Bar {...otherProps} legends={[{ data: [] }]} />
}
```

You can look at the website for Bar and get the rest of the legend props.

**Comment by altrang** [comment]
Thanks ! i will try this :)
