### ISSUE TITLE
Calendar missing from NPM?

### ISSUE THREAD

**Issue by mvxt** [plouc/nivo#1090]
## Description
`@nivo/calendar` seems to be missing from NPM.

```bash
$ yarn add @nivo/calendar
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@nivo%2fcalendar: Not found".
```

I went directly to the NPM page and got this:
![image](https://user-images.githubusercontent.com/2441695/89512936-250c1500-d791-11ea-8f1c-8c4ddd874ac9.png)

## Steps to reproduce the behavior:
1. Try to do a `yarn add @nivo/calendar`. I've confirmed that other packages are installing without issues, so it's not likely a configuration problem on my end.
2. Head to https://www.npmjs.com/package/@nivo/calendar and also get `esockettimedout` error.

## Expected Behavior
I wanted to add the calendar to one of my projects but discovered I couldn't when I tried

## Tech Info
Not sure if this info matters, but:
 - **OS**: macOS Catalina 10.15.6
 - **Browser**: Chrome 84.0.4147.105
 - **yarn**: v1.22.4
- **node**: v13.9.0

Let me know if you need any additional info from me.

**Comment by plouc** [comment]
It's an npm issue, please see https://status.npmjs.org/.

Le jeu. 6 août 2020 à 18:06, Michael Thanh <notifications@github.com> a
écrit :
