### ISSUE TITLE
@nivo/radar Not Found in NPM

### ISSUE THREAD

**Issue by Nevation** [plouc/nivo#1092]
**Describe/explain the bug**
`npm install @nivo/radar ` returns Not Found Error

**Screenshots**
![image](https://user-images.githubusercontent.com/52541784/89518867-7c07fd80-d816-11ea-82ff-048c86491e5f.png)

**Desktop (please complete the following information):**
 - OS: macOs

**Comment by paulblqr** [comment]
I'm experiencing the same if @nivo/line

**Comment by plouc** [comment]
It's an npm issue, please see https://status.npmjs.org/

**Comment by Nevation** [comment]
@plouc thx for the answer!
