### ISSUE TITLE
Add metadata object for Serie and Datum and populate that to Slice and Point

### ISSUE THREAD

**Issue by mateusznowosielski** [plouc/nivo#1095]
**Is your feature request related to a problem? Please describe.**
I have a component that wraps a defined chart of my choice, let's say ResponsiveLine that I'm using in 2 similar use cases with small differences: 1st for displaying population number and 2nd one for displaying value in $. I would like to present data in tooltip differently (different format, additional suffix, prefix) based on a Serie or Datum.

1st chart displaying population data:
```
       <ChartWrapper
          data={populationData}
        />
```
Tooltip
```
Date: 03/23/2010
Population A: 243 // no special formatting, no prefix to value
Population B: 123
```

2nd chart displaying value data:
```
       <ChartWrapper
          data={valueData}
        />
```
Tooltip
```
Date: 03/23/2010
Value A: $23,000 // here and below I want to add the prefix to formatted value
Value B: $13,000
```

**Describe the solution you'd like**
Add attribute to the below object and populate this into Tooltip
```
export interface Serie {
        id: string | number
        data: Datum[]
        metadata: any // this is a new attribute that could hold information about attributes of my choice ie. above prefix 
        [key: string]: any
    }
```
...same thing could be done on Datum object type
```
    export interface Datum {
        x?: DatumValue | null
        y?: DatumValue | null
        metadata: any
        [key: string]: any
    }
```
...so then I could access that metadata back in `Slice` and `Point` objects in tooltip.

**Describe alternatives you've considered**
Right now I have to expose additional parameter in my `ChartWrapper` component and define the metadata, but it gets complicated if I want to have full control over displaying information in Tooltip based on just individual points.

**Comment by thomas07vt** [comment]
+1 for this feature... i currently need this feature
