### ISSUE TITLE
Missing data update example

### ISSUE THREAD

**Issue by laibulle** [plouc/nivo#110]
Hello,

I am looking for a way to update chart data but I can't find any example in documentation. I tried to update the state of my component but it does not seems to work.

**Comment by andreas-groos** [comment]
If the data props (or any other props) you pass to a nivo component change, the nivo component will update.

**Comment by plouc** [comment]
Hello @laibulle,

There's nothing specific in fact.
In order to update chart data, you can pass new data (as prop) to it, but please make sure to pass a new reference then because most components use `PureComponent`.

**Comment by laibulle** [comment]
Thanks, 

I have to update at max 30 graphs every seconds, so I fear that immutable data will introduce too much overhead. 

Let's try ! ^^
