### ISSUE TITLE
Log scale validation too strict againts null values

### ISSUE THREAD

**Issue by tflanitzer** [plouc/nivo#1100]
When using a line with a log scale on data that has null or undefined values, an exception is thrown ("a log scale domain must be strictly-positive or strictly-negative"). However, when the check is removed (packages/scales/src/logScale.js:19), the line displays fine with gaps, as expected. I have created PR #1099 with a possible fix. 

**To Reproduce**
To reproduce the validation error, just use a null value in a data set with a log scale. See [this codesandbox](https://codesandbox.io/s/nivoline-time-y-axis-forked-qyb2n?file=/src/index.js).

**Expected behavior**
Like with linear scales, data points without value (null or undefined) should just not be displayed and the line should be separated.

**Screenshots**
Here is a screenshot proving that it works with the validation disabled.
![logscalewnull](https://user-images.githubusercontent.com/10977536/90101768-96bf0280-dd3f-11ea-91a7-e8ac07eb1f6d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 84

**Comment by tflanitzer** [comment]
Still an issue and really easy to resolve, see mentioned pr

**Comment by tflanitzer** [comment]
Bump

**Comment by plouc** [comment]
Solved by #1099, thank you @tflanitzer for the PR!
