### ISSUE TITLE
Uneven grid lines

### ISSUE THREAD

**Issue by brandondurham** [plouc/nivo#1103]
X axis grid lines are uneven in my chart. There are two that appear closer together than the rest, resulting in the border on the right side being pushed off the chart.

**To Reproduce**
https://codesandbox.io/s/nivoline-time-y-axis-forked-694on?file=/src/index.js

1. Go to https://codesandbox.io/s/nivoline-time-y-axis-forked-694on?file=/src/index.js
2. See the uneven grid lines on the x axis.

**Expected behavior**
Grid lines would be divided equally across the chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/250210/90411742-d5232d00-e071-11ea-91e5-34cfd0f06655.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.125

**Comment by Incin** [comment]
I am seeing this issue as well, it seems to be a bug with the Y axis when there are 2 months and the previous month has an odd number of days.
