### ISSUE TITLE
Bullet chart with multiple measures

### ISSUE THREAD

**Issue by honohunter** [plouc/nivo#1104]
hello, I would like to know if there is a possibility to do a bullet chart with multiple measures like shown in the image below.
I appreciate any help.
thanks

[
![Screenshot_2020-08-19 Figma](https://user-images.githubusercontent.com/37155319/90636544-abf5ce80-e222-11ea-9a80-5a470b8bff6b.png)
](url)

**Comment by ppfm** [comment]
Would be great to have. Bump!
