### ISSUE TITLE
null/undefined color in Heatmap

### ISSUE THREAD

**Issue by javiermelendezc** [plouc/nivo#1105]
**Is your feature request related to a problem? Please describe.**
When feeding the Heatmap with null values it's taken as a 0
When feeding the Heatmap with undefined values it shows a black square/rectangle

**Describe the solution you'd like**
Is it possible to avoid or personalize the rendering of a square using null/undefined? 

**Describe alternatives you've considered**
I've also considered a custom cell renderer but I think data absence in Heatmap is a common use case
The null -> 0 similarity is understandable for general API consumption
But It'd be a great feature to have the ability to control how absent data is presented

**Describe additional context**
Example of use case:
-Showing percentages in Heatmap: It's not the same having 0% and not having a sample of that square at all

**Comment by javiermelendezc** [comment]
Will close this
It isn't anywhere in the docs but found out **nanColor** property on the source code

**Comment by mikerhyssmith** [comment]
Just thought I'd add I'd also really like this feature, for rendering a heat map where you don't have the data yet such that every row and column has data.

I also went down the custom cell renderer route but the HeatmapCellRect isn't exported for me to add a custom component that behaved like  - if there is a value use the HeatmapCellRect else render an empty space!

**Comment by azrul-aziz** [comment]
Just found out nanColor prop has been updated to emptyColor instead.

**Comment by plouc** [comment]
@azrul-aziz there are other changes which were made to the package when it was migrated to TypeScript, they're listed here: https://github.com/plouc/nivo/pull/1880 if you're curious.
