### ISSUE TITLE
Missing 'colorBy' type in BarSvgProps

### ISSUE THREAD

**Issue by eggei** [plouc/nivo#1106]
I created a `ResponsiveBarChart` and I added `colors` and `colorBy` props to adjust the colors of the bars. How every TypeScript compiler complains about `colorBy` prop being missed in the prop types. More specifically, `colorBy` prop is not in `BarProps`

I would love to open a PR for this but couldn't find a contribution guide so created this issue instead.

<img width="895" alt="Screen Shot 2020-08-20 at 1 22 00 PM" src="https://user-images.githubusercontent.com/52514315/90804398-2c323780-e2e8-11ea-8c3c-d54cc28d9843.png">

Funny that there are two workarounds in the screenshot for different Typescript issues.

**Comment by wyze** [comment]
This is deprecated, you should be using the `colors` prop. See https://github.com/plouc/nivo/pull/904#issuecomment-626407337

**Comment by eggei** [comment]
@wyze But if I take out `colorBy` from the below code `scheme` doesn't work. If I put it in and specify as `colorBy="index"` it works.

```
<ResponsiveBar
        margin={{ top: 32, right: 48, bottom: 56, left: 48 }}
        colors={{ scheme: 'orange_red' }}
        colorBy="index"
        layout="horizontal"
        keys={keys}
        padding={0.2}
        indexBy={indexBy}
        data={data.sort((a, b) => a.count - b.count)}
        animate={false}
        enableGridY={false}
        enableGridX
        labelFormat={labelValue =>
          ((
            <tspan x={-16}>{replaceThousandWithK(labelValue)}</tspan>
          ) as unknown) as string
        }
        borderRadius={2}
        tooltip={customTooltip}
        axisLeft={{
          renderTick,
        }}
        layers={['grid', 'bars', 'axes'] as BarLayerType[]} // This pushes axes in front of bars so tick labels stay over bars
      />
```
