### ISSUE TITLE
tickValues is not working in nivo Bar chart.

### ISSUE THREAD

**Issue by achillescs** [plouc/nivo#1109]
**Describe/explain the bug**
I want my Bar chart yAxis (axisLeft) to be maximum of 5 values i.e maximum (or maybe minimum too) should be 5 grids with only 5 values.
For this i am using tickValues as 5

      axisLeft={{
        tickSize: 2,
        tickPadding: 5,
        tickRotation: 0,
        tickValues: 5,
        legend: yAxisText,
        legendPosition: "middle",
        legendOffset: -45
      }}
     gridYValues={5}

But it is not working, If i am having values like 1000,2000,3000,4000,5000,6000......12000 then 7 ticks are coming as 0,2k,4k,6k,8k,10k,12k but i want only 5 ticks maximum. How to do it.

**Expected behavior**
As tickCount is deprecated , tickValues:5 should work ?

**Additional context**

**Comment by jdcaperon** [comment]
> a number which define the number of ticks to display, doesn't work with point scale, also note that when using this form it's not guaranteed that you'll have exactly the number of ticks you asked for as d3 will make an educated guess to define them

From: https://nivo.rocks/guides/axes/
