### ISSUE TITLE
Network Graph - labels for nodes and edges

### ISSUE THREAD

**Issue by vihardesu** [plouc/nivo#1110]
I would like to use Nivo's implementation of its Network Graph, but it does not have out of the box support for labeling the nodes and edges. It also doesn't seem like there is a Storybook for it. 

I would like to have a Storybook added for Network Graphs describing how to add labels for nodes and edges. I would like to have interactivity in the form of an onClick handler, onHover tooltip handler.

**Comment by Dhyaan1** [comment]
Did you find a way to add labels to the nodes and edges?
