### ISSUE TITLE
isInteractive heatmap prop cannot be false

### ISSUE THREAD

**Issue by tripp528** [plouc/nivo#1111]
**Describe/explain the bug**
Setting isInteractive={false} does not disable interactivity in a heatmap. 

**To Reproduce**
Easiest reproduction is using the example at https://nivo.rocks/heatmap/.

Scroll down and set isInteractive slider to false position. It clearly still reacts to mouse hovers. Happens for both canvas and svg.

- Browser: chrome, safari

**Comment by wyze** [comment]
It looks like this is an issue with just the website and has been fixed on master, we just need to deploy a new version of the website.
