### ISSUE TITLE
gridXValues, gridYValues not working with type="time"

### ISSUE THREAD

**Issue by jj0b** [plouc/nivo#1114]
I'm working on a ResponsiveLine graph that has an xScale type="time" and a yScale type="linear" and have just noticed that gridYValues works as expected but grdiXValues seems to have no effect, other than any value passed to it results in no vertical grid lines at all. 

After playing with a sample in codesandbox I believe gridYValues are also not working if yScale has type="time".

Here is my codesandbox based off of one by @plouc https://codesandbox.io/s/nivoline-time-y-axis-eoug4?file=/src/index.js 

Notice that the tickValues shown on the y axis are 0, 1, 2, 3, 4 but despite setting gridYValues={[0,1,2,3,4]} no y axis grid lines are displayed. The same happens for x axis grid lines in the case where time is on the x axis.

**Comment by jdcaperon** [comment]
Not sure if your sandbox is up to date?
