### ISSUE TITLE
bug: Legends text is hardcoded to black

### ISSUE THREAD

**Issue by knackjax** [plouc/nivo#112]
I'm trying to use this on a dark theme website. I believe you just want fill: fill ?

Thanks

https://github.com/plouc/nivo/blob/71e1c4b039feb6ef7cc9e4378a30f3a5018d6781/packages/nivo-legends/src/svg/LegendSvgItem.js#L61

**Comment by knackjax** [comment]
added pull request #113 for convenience

**Comment by knackjax** [comment]
actually, I rethought about this and it should be a different variable since we don't want the text to match legend color. Updated pull request.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/113 & https://github.com/plouc/nivo/pull/135.
@knackjax, thank you for your contribution!
