### ISSUE TITLE
ScatterPlot Canvas is causing "Invalid layer: annotations" Error in Website

### ISSUE THREAD

**Issue by priteshkeleven** [plouc/nivo#1122]
**Describe/explain the bug**
Whenever I visit ScatterPlots Canvas page, it displays nothing. A complete black page. After Opening Console, we can see the "Invalid layer: annotations" error. Screenshot is attached below.

**To Reproduce**

1. Go to [https://nivo.rocks/scatterplot/canvas/](https://nivo.rocks/scatterplot/canvas/)
2. See error in Console (F12)

**Expected behavior**
Expected behavior is to show website page displaying Canvas Implementation for ScatterPlot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37466934/92571525-e510e400-f2a0-11ea-84b0-9e4799f9860e.png)

**Desktop:**
 - OS: [Windows 10 Home 2004]
 - Browser:  Chrome 85.0.4183.83

**Comment by moftedal** [comment]
I'm getting the same issue of "Invalid layer: annotations" when trying to implement the ResponsiveScatterPlotCanvas in code. Are there any fixes to this?

**Comment by wyze** [comment]
This looks to be fixed now!
