### ISSUE TITLE
Controlling the padding around the line chart

### ISSUE THREAD

**Issue by mrkent** [plouc/nivo#1126]
I'm trying to make my charts mobile friendly. As you can see in this line chart, I've removed the left axis and located the legend on top-left. I'd like the chart to stretch horizontally to the entirety of the screen. How can I achieve this?

![image](https://user-images.githubusercontent.com/1649755/92797575-0b995280-f367-11ea-8ccf-208fd7ebe36c.png)

**Comment by plouc** [comment]
You can change the margin to do this (given the parent container has correct dimensions).
