### ISSUE TITLE
Add formatter to legend for Pie chart

### ISSUE THREAD

**Issue by VolodymyrKornetskyi** [plouc/nivo#1127]
I'm always frustrated when can't add formatting to the legend labels for Pie chart

It would be great to have a possibility to pass the function (formatter?) to the Legend Props or directly to the CommonPieProps which allows set new string to legend label or something like the `tooltip` field is in the CommonPieProps.

Maybe it can be done as [here](https://codesandbox.io/s/nivo-bar-example-nf86t?file=/index.js) in the ResponsiveBar component (with Layers functionality).

**Comment by maksym-plotnikov** [comment]
+1

**Comment by lordlpua** [comment]
+1

**Comment by plouc** [comment]
`valueFormat` is now available, you can try it in the demo website.
