### ISSUE TITLE
 Low severity vulnerability ||  node-fetch

### ISSUE THREAD

**Issue by atresca** [plouc/nivo#1129]
$ npm audit
=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Denial of Service

  Package         node-fetch

  Patched in      >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9

  Dependency of   nivo

  Path            nivo > recompose > fbjs > isomorphic-fetch > node-fetch

  More info       https://nodesecurity.io/advisories/1556

found 1 low severity vulnerability in 1750 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by kaleem-elahi** [comment]
I am getting this audit issue, how to solve it @atresca ?

**Comment by wyze** [comment]
This will be handled with #884 so you can track progress there.
