### ISSUE TITLE
BarCanvas does not show labels

### ISSUE THREAD

**Issue by Lynges** [plouc/nivo#1131]
Switched from `ResponsiveBar` to `ResponsiveBarCanvas` for performance and my label disappeared.

I have created a sandbox here that show the problem. Code is copied from the showcase and it shows labels working only for the non-canvas barchart.

https://codesandbox.io/s/romantic-sanne-96kqu

Everything else seems to work just fine. I have tried providing a function for the label names and it is only called by the non-canvas version.

**Comment by jdcaperon** [comment]
`BarCanvas` doesn't support labels right now afaict, this needs to be added or corrected in the documentation

**Comment by plouc** [comment]
@Lynges, @jdcaperon is right, the canvas implementation is not completely similar to the SVG one, and labels aren't supported.
