### ISSUE TITLE
ResponsiveLine tool tip y axis goes out of the layout.(how to auto adjust the position)

### ISSUE THREAD

**Issue by ajaiswal595** [plouc/nivo#1133]
Is there any way i can reposition the tooltip in ResponsiveLine chart.
Here it is 
![image](https://user-images.githubusercontent.com/8745632/93886102-a51b1980-fd02-11ea-8d55-5fc9abdb5f9e.png)

And if i do 
enableSlices="x" then tooltip automatically adjusting the position.

![image](https://user-images.githubusercontent.com/8745632/93886278-d85da880-fd02-11ea-9621-7a1491f95192.png)

Similar way how it auto adjust for enableSlices="x"  can we do something like this for the above snapshot?

My dependencies versions are 

"@nivo/bar": "0.62.0",
    "@nivo/line": "0.62.0",
    "@nivo/pie": "0.62.0",

**Comment by Pato91** [comment]
I think we can make sure the `x, y` values don't go beyond the bounds of the container(while accounting for tooltip dimensions) here https://github.com/plouc/nivo/blob/master/packages/tooltip/src/components/TooltipWrapper.js#L57. Just a quick thought. Sometimes the transform values are negative and in that case the cutoff at the start of the graph bounadries like in the screenshot below;
![TooltipCutOff](https://user-images.githubusercontent.com/29727441/98107890-322dc280-1eac-11eb-9183-207f358321e0.jpg)
