### ISSUE TITLE
Editing the Axis Title 

### ISSUE THREAD

**Issue by QamarFarooq** [plouc/nivo#1138]
I want to change the font and size, does the Nivo library allow me to do that?
![image](https://user-images.githubusercontent.com/19571983/94324394-b87aee80-ff67-11ea-86e9-c6d6e7d5a361.png)

**Comment by jdcaperon** [comment]
Probably, by creating a layer using the Layers nivo feature

**Comment by plouc** [comment]
@QamarFarooq, yes, you can change the theme to do this, which is unfortunately not documented, you can have a look at the [default theme](https://github.com/plouc/nivo/blob/master/packages/core/src/theming/defaultTheme.js) to see how it's structured, in your case, you'll have to pass a custom theme object to your chart and overriding `axis.legend.text` styles.
