### ISSUE TITLE
Changing/editing information in the pop-up box

### ISSUE THREAD

**Issue by QamarFarooq** [plouc/nivo#1139]
Whenever i hover over the graph, a popup box appears which shows me stats about the data lines. I want to add some more information into the popup box. Can the pop up box be edited to have some more information?

![image](https://user-images.githubusercontent.com/19571983/94324524-3b03ae00-ff68-11ea-916f-11d723eedec6.png)

**Comment by jdcaperon** [comment]
See https://github.com/plouc/nivo/issues/192

**Comment by plouc** [comment]
@QamarFarooq seems like a duplicate of https://github.com/plouc/nivo/issues/1142.
