### ISSUE TITLE
What is the documentation for tooltip?

### ISSUE THREAD

**Issue by QamarFarooq** [plouc/nivo#1142]
I want to know what the documentation is for inputting my own custom tooltip? do i just do tooltip={myFuncThatRenderTooltip}? i have looked at https://github.com/plouc/nivo/issues/192 but i am at a loss

**Comment by wyze** [comment]
Yes, that is correct. Some charts have stories showing custom tooltips, so you can get an idea of what you can do there.

https://nivo.rocks/storybook

**Comment by QamarFarooq** [comment]
I have looked at the story book and i just wanted some clarification. You said i could do tooltip={myCustomFuncThatRenderTooltip}, but when i am looking at the code, it only allows me to change certain things. What i wanted was literally my own custom toolkit, where i wanted to show a custom graph that i have made from scratch which corresponds to each value that i hover over. Can that be done? or should i migrate to another library?
![image](https://user-images.githubusercontent.com/19571983/94606025-e57d1900-0267-11eb-8328-d051a5c1237a.png)

**Comment by plouc** [comment]
@QamarFarooq, you can only customize the tooltip content, if you want to completely change the way the tooltip works, interactions, provided data... then it cannot be easily done.

**Comment by solcomgit** [comment]
Exist some method when tooltip close?

**Comment by kamilio** [comment]
Hello @plouc amazing library, works great. Thanks for building it.

I would like to add a link with data breakdown to the tooltip on the Line chart. However, the tooltip would close when hovered over. Do you have any ideas on how to do it? I read through the docs and source code and there doesn't seem to be any solution. You might have some more insights...

**Comment by azhard4int** [comment]
@kamilio Were you able to do that? I'm looking to do the same.
