### ISSUE TITLE
New Nivo release

### ISSUE THREAD

**Issue by aleksey1lipkin** [plouc/nivo#1149]
Hey, thank you for the great data-vis library. 👍 
  Can you shed a light when will be the next Nivo release? In our project, we want to use canvas charts for a line chart. While v0.62 doesn't have a way to provide a custom layer into canvas, the latest version has it (https://github.com/plouc/nivo/pull/987)

**Comment by wyze** [comment]
We are waiting until @plouc has some time to cut a new release. No idea on an ETA.

**Comment by ignatvilesov** [comment]
@plouc Could you please share a kind of approximated ETA when we should expect a new version to come out?
