### ISSUE TITLE
@nivo/core ResponsiveWrapper is not rendering children

### ISSUE THREAD

**Issue by szymonmal** [plouc/nivo#115]
Hello,

I've tried to use ReponsiveBar from the documentation and it seems that something might be broken in the ResponsiveWrapper.

[Here is reproduction repo](https://github.com/szymonmal/nivo-responsive-bar)

I've monkey patched ResponsiveWrapper code to give me logs of height and width and it seems that height is 0 after first recalculation from initial -1.

![image](https://user-images.githubusercontent.com/961649/33939076-0d5bce40-e00a-11e7-826c-0addf0acb2ac.png)

![image](https://user-images.githubusercontent.com/961649/33939100-2397b76e-e00a-11e7-9450-27f0c5b4c3d3.png)

**Comment by plouc** [comment]
@szymonmal, I use negative values as default, it's *normal* that the height is 0, because it has no way to compute any in your case, you need to have a defined height at some point in the parent tree.

**Comment by szymonmal** [comment]
@plouc, Thanks for explanation. I've added height for the container and indeed that fixed it! I'm closing this one.
