### ISSUE TITLE
Calendar legend labels are not visible in dark theme

### ISSUE THREAD

**Issue by kumarunster** [plouc/nivo#1153]
Calendar legend labels are not visible in dark theme

**To Reproduce**

1. Go to https://nivo.rocks/calendar/
2. Click on 'light/dark' switch and enable dark mode
3. See legend texts

**Expected behavior**
legend texts should have same fill color as year/month labels and be at least visible

**Screenshots**

<img width="1163" alt="Bildschirmfoto 2020-10-09 um 15 35 53" src="https://user-images.githubusercontent.com/2104820/95591197-461a0c00-0a47-11eb-8157-ddfc25429ecb.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser [chroe, safari, firefox]

**Comment by wyze** [comment]
Thanks, a PR would be welcomed. If anyone would like to tackle it!

**Comment by diegosps** [comment]
As a workaround:

```javascript
<ResponsiveCalendar
    theme={{
            ///...
            labels: { text: { fill: theme.palette.text.primary } }
    }}
/>
```
Im my case, theme is material ui and the value for primary changes according to dark/light theme.

But I agree this should be fixed in the component.

**Comment by kumarunster** [comment]
I'm trying to prepare a PR for this. I saw, that the same issue occurs on other legends too. More, with last release the legends disappear at all.
