### ISSUE TITLE
Axis y direction reversed for some datasets when using logarithmic line chart

### ISSUE THREAD

**Issue by barnapisti1994** [plouc/nivo#1154]
**Describe/explain the bug**
When using "log" type yScale with base 10 the axis y direction is reversed along the chart itself for some datasets. The values are increasing from top to bottom instead of bottom to top and the chart is chart is displayed according to this. For example axis y starts with 100000 and ends with 10000 at the top.

**To Reproduce**
To reproduce the issue, open the Codesandbox below. It uses the newest stable version of React and Nivo line chart.
https://codesandbox.io/s/nivo-line-graph-component-forked-kucfd?file=/src/components/line.js

**Expected behavior**
The direction of the y axis stays the same for all datasets when the type in yScale is "log".

**Comment by immanuelfodor** [comment]
bump

**Comment by libeks** [comment]
It appears that the fault is with the following code, where for `"log"` it arbitrarily picks the first and last entries of the (unsorted) unique set as min and max, respectively. This seems like a bug to me: https://github.com/plouc/nivo/blame/99b520e9621e77472b8c922d85a0fcd7bc5e00cc/packages/scales/src/compute.js#L125-L142

**Comment by anwfr** [comment]
Same problem here.

**Comment by FrancoPaez** [comment]
were you able to solve the problem?

> **Describa / explique el error**
> Cuando se usa el tipo "log" yScale con base 10, la dirección del eje y se invierte a lo largo del gráfico para algunos conjuntos de datos. Los valores aumentan de arriba hacia abajo en lugar de de abajo hacia arriba y el gráfico se muestra de acuerdo con esto. Por ejemplo, el eje y comienza con 100000 y termina con 10000 en la parte superior.
> 
> **Para reproducir**
> Para reproducir el problema, abra el cuadro Códigos a continuación. Utiliza la versión estable más reciente del gráfico de líneas React y Nivo.
> https://codesandbox.io/s/nivo-line-graph-component-forked-kucfd?file=/src/components/line.js
> 
> **Comportamiento esperado**
> La dirección del eje y permanece igual para todos los conjuntos de datos cuando el tipo en yScale es "log".

**Comment by wyze** [comment]
Should the log scale be sorted like we do for linear? Would be a simple enough change if that is the case.

**Comment by sidkoth1996** [comment]
Facing the same issue. Any help will be greatly appreciated, thank you!

**Comment by sidkoth1996** [comment]
Hello @plouc, could you please help with this? Thank you!

**Comment by francescocretti** [comment]
I have the same problem for a scatterplot, where both axes are reversed if I use logarithmic scale

**Comment by plotka** [comment]
I encountered the same problem with logarithmic scales on the y axis in line charts. My workaround was to sort the data by ascending y values: `data.sort((a, b) => a.y - b.y);`

**Comment by holtzy** [comment]
Same problem here 😞
