### ISSUE TITLE
Animation doesn't work with custom line (Responsive Line)

### ISSUE THREAD

**Issue by CharlieGoodson** [plouc/nivo#1157]
Hi, everyone! In your Storybook there's an example how to create custom lines https://nivo.rocks/storybook/?path=/story/line--custom-line-style.
But, in this case, lines animation not working. The points are animated, but the lines are not. How to fix it? Thanks a lot.

**Comment by aschey** [comment]
I was able to get this to work by using the `useAnimatedPath` hook from `@nivo/core` just like the actual implementation does: https://github.com/plouc/nivo/blob/master/packages/line/src/LinesItem.js.

**Comment by zerokol** [comment]
bump

**Comment by Neuro8** [comment]
Any solutions?

**Comment by Neuro8** [comment]
> I was able to get this to work by using the `useAnimatedPath` hook from `@nivo/core` just like the actual implementation does: https://github.com/plouc/nivo/blob/master/packages/line/src/LinesItem.js.

Hi, could you please give more detail about how to go about using the hook to solve the problem?

**Comment by egdiala** [comment]
I was able to animate the line (`path`) drawn from `@nivo/line` using `useAnimate` hook from framer-motion. Here's my implementation.


```import React, { useEffect } from "react"
import { ResponsiveLine, type LineSvgProps } from "@nivo/line"
import { useAnimate, useInView } from "framer-motion"

export const LineChart: React.FC<LineSvgProps & { className: string }> = ({ className, ...props }) => {
    const [scope, animate] = useAnimate()
    const isInView = useInView(scope, { once: true })
    
    useEffect(() => {
        if (isInView) {
            const enterAnimation = async () => {
                await animate("path", { pathLength: [0, 1] }, { duration: 2, ease: "easeOut" });
            }
            enterAnimation()
        }
    },[animate, isInView, scope])
    return (
        <div ref={scope} className="w-full h-full">
            <ResponsiveLine {...props} />
        </div>
    )
}
