### ISSUE TITLE
Support logarithm and zero values

### ISSUE THREAD

**Issue by codler** [plouc/nivo#1159]
Can we support logarithm and also to have the value 0

**Comment by plouc** [comment]
Log is supported on the line chart, however log 0 is invalid.

**Comment by codler** [comment]
okey, can we make 0 valid in log?

**Comment by plouc** [comment]
@codler, no, nivo uses d3 internally, and that's the expected behavior of log, you can have a look at [this](https://github.com/d3/d3/issues/1420#issuecomment-21500319) for more information.

**Comment by codler** [comment]
It doesn’t make sense, all other library can have 0 log. You can make so when value is 0 don’t use d3

**Comment by plouc** [comment]
@codler, sorry but I think it actually makes a lot of sense as log 0 is not valid, if I start to add exceptions like this, I'll have to do so for the whole code base, when handling the values, when generating ticks, axis... and also maintain extra tests for those exceptions, in the end, it would add a lot of maintenance costs I think.

If you feel this is something which could be easily implemented, or you would like to add it to nivo, please go ahead, I would be more than happy to review it.

> It doesn’t make sense, all other library can have 0 log.

That's clearly not the case as most of them use d3 and some just expose d3 scales directly such as `airbnb/visx`, `victory`...
