### ISSUE TITLE
Creating a marker in line chart when the x axis is based on a time scale 

### ISSUE THREAD

**Issue by rahul-sharma-nyz** [plouc/nivo#1162]
I am trying to create a x-axis marker (red line shown in the image) at the **12 PM** point.

<img width="740" alt="Screen Shot 2020-10-15 at 11 11 03 PM" src="https://user-images.githubusercontent.com/64561320/96208525-b8a15500-0f3b-11eb-91b3-6b178d31c3c2.png">

```js
<ResponsiveLine
      ...
      xScale={{
        type: 'time',
        format: '%H:%M',
        precision: 'minute',
        useUTC: false,
      }}
      xFormat="time:%H:%M"
      yScale={{
        min: 0,
        max: 80,
        type: 'linear',
      }}
      axisLeft={{
        ...
        format: (e) => e + '%',
      }}
      axisBottom={{
        ...
        format: '%I %p',
        tickValues: `every 3 hours`,
      }}
     markers={[
        {
          axis: 'y',
          value: 50,
          lineStyle: { stroke: '#fff', strokeWidth: 2 },
          legend: 'y marker',
          textStyle: {
            fill: '#fff',
            fontSize: 15,
          },
        },
        {
          axis: 'x',
          value: '12:00', // Here is the error, unable to translate on x-axis
          lineStyle: {
            stroke: '#ff0000',
            strokeWidth: 2,
            opacity: 1,
          },
          legend: 'x marker',
          textStyle: {
            fill: '#fff',
            fontSize: 15,
          },
        },
      ]}
     ...
/>
```

As you can see, the red marker is being rendered at 0 position rather than 12 PM. I feel the error is at `value: '12:00'` because the xScale cannot transform the string to a correct pixel value that would have rendered the red line at the right location.

I have tried passing the time in all possible formats but the red line still gets rendered at the 0 point. When inspecting the red line, I get the following error.

```
Error: <g> attribute transform: Expected number, "translate(undefined, 0)".

<g transform="translate(undefined, 0)">
<line x1="0" x2="0" y1="0" y2="220" stroke="#000000" stroke-width="1" style="stroke: rgb(255, 78, 94); stroke-width: 2; opacity: 1;">
</line>
<text transform="translate(14, 14) rotate(0)" text-anchor="start" dominant-baseline="central" style="fill: rgb(255, 255, 255); font-size: 15px;">x marker</text>
</g>
```

Any suggestion is appreciated! @plouc @wyze

**Comment by wyze** [comment]
What else have you tried? What does your data look like? It is passing the value you specify into the xScale function, and it can't find it so it is returning undefined and rendering it.

**Comment by rahul-rxr** [comment]
Hi @wyze, here's my data
```

const data = [
  {
    id: 'Today',
    data: [
      {
        x: '08:00',
        y: 40,
      },
      {
        x: '11:00',
        y: 25,
      },
      {
        x: '14:00',
        y: 59,
      },
      {
        x: '17:00',
        y: 15,
      },
    ],
  },
  {
    id: 'Avg Historical',
    data: [
      {
        x: '08:00',
        y: 25,
      },
      {
        x: '11:00',
        y: 30,
      },
      {
        x: '14:00',
        y: 3,
      },
      {
        x: '17:00',
        y: 27,
      },
    ],
  },
];
```

I understand the problem is `xScale` cannot take in `08:00` and produce a corresponding pixel value. I have tried passing in `08:00` in various date formats like `2020-01-01T08:00:00` and epoch time `1602852170657000`.

**Comment by arthuryeti** [comment]
I have the same issue :/

**Comment by arthuryeti** [comment]
@rahul-rxr I think you should use `new Date()`

**Comment by rbp-seasony** [comment]
That's sad that this issue was not solved or anyone commented about the solution... I am facing this issue right now 😢

**Comment by faycal-dev** [comment]
I am having the same issue and using the javascript Date didn't fix it

**Comment by SzymonRDuda** [comment]
> @rbp-seasony the `new Date(whateverMyDateIs)` worked for me

Worked for me as well :D
