### ISSUE TITLE
can i show image on bubble chart ?

### ISSUE THREAD

**Issue by samslow** [plouc/nivo#1164]
![image](https://user-images.githubusercontent.com/26738367/96415119-04e4e180-1229-11eb-9a21-7d816d4061ea.png)

for now, every bubble show only color by grouping their data.

but i want show image instead of color group like below.

![image](https://user-images.githubusercontent.com/26738367/96415019-e848a980-1228-11eb-85d2-3f9741ae86c8.png)

can i show this from now version? or it's future feature already??

**Comment by coooraph** [comment]
@samslow, you can do it by using a custom `nodeComponent`.

**Comment by samslow** [comment]
@coooraph Thanks for your answer. but i can't find nodeComponent props's docs. can i get some tip or docu about nodeComponent??

**Comment by wyze** [comment]
While there is no documentation, here is the default implementation, so you can see the props it receives: https://github.com/plouc/nivo/blob/master/packages/circle-packing/src/BubbleNode.js

**Comment by samslow** [comment]
Thanks for your help!!
