### ISSUE TITLE
feature request: custom tooltips

### ISSUE THREAD

**Issue by alexraginskiy** [plouc/nivo#117]
Allowing the user to provide a component of their choosing for the tooltip would be great.

**Comment by blakeperdue** [comment]
Giant +1. Custom tooltips would allow us to greatly enhance the user experience. For example, if I have a stacked bar chart, you have to move your mouse over each section within a single bar to see the value. A custom tooltip would allow me to show all values for a stacked bar when you hover over any of its components. That's just an obvious thing to do. In fact, not having that – while nearly every other good charts lib does – is surprising. This is a must have.

Here's  the pain point (see how I have to hover over each to get a value!):
![screen recording 2018-02-25 at 04 38 pm](https://user-images.githubusercontent.com/1642071/36646791-5ee2d392-1a4a-11e8-9949-77411d8fde92.gif)

**Comment by plouc** [comment]
I've created a generic issue to be able to track down progress on this, https://github.com/plouc/nivo/issues/192

**Comment by malzaeem** [comment]
Can we add a custom tooltip for stacked bar where it shows all values for the bar we hover on like in https://codepen.io/plotly/pen/bdZbWy ?
