### ISSUE TITLE
Line chart documentation breaks when choosing non-linear curve style on SVG

### ISSUE THREAD

**Issue by AntBush** [plouc/nivo#1171]
When selecting a value for the curve parameter in the [Line Documentation](https://nivo.rocks/line/) the page fails to render. 

Console shows: TypeError: n[t] is undefied

1. Go to https://nivo.rocks/line/
2. Click on linear under Style for the curve interpolation
3. Select any other curve style

Desktop
 - OS: WIndows 10
 - Browser Firefox
 - Version 81.0.2

**Comment by wyze** [comment]
It looks like this is related to #1170 and is an issue with react-spring.
