### ISSUE TITLE
[v0.63.1] [Radar] Circular grid misplaced

### ISSUE THREAD

**Issue by matthewkwong2** [plouc/nivo#1178]
**Describe/explain the bug**
The circular grid of `@nivo/radar@0.63.1` is misplaced. The most outer level of the grid should at least align with the max value of the data.

Bugged:
![image](https://user-images.githubusercontent.com/32725014/96944263-f5a5b280-150c-11eb-8b7c-d67ac3e7164b.png)
As supposed to:
![image](https://user-images.githubusercontent.com/32725014/96944341-2a196e80-150d-11eb-8761-dbf8f20da0cc.png)

**To Reproduce**
The online document should be enough to reproduce the issue.

1. Build the same radar chart with circular grid (which is the default) using version `0.62.0` and `0.63.1` respectively and observe the difference(s)

**Edit:**
**Workaround**
Option 1: Downgrade to version `0.62.0`.
Option 2: Crank up the `maxValue`.

**Comment by matthewkwong2** [comment]
@wyze Any ETA on when will this be fixed?

**Comment by wyze** [comment]
Hey Matthew, I just pushed a fix for it now. Sorry about that!
