### ISSUE TITLE
Install CodeSandbox CI to run with PRs

### ISSUE THREAD

**Issue by wyze** [plouc/nivo#1180]
Install CodeSandbox CI app to run on PRs. I think this would be great to check changes as they are submitted. I don't have access to install the GitHub app for this repo.

https://codesandbox.io/docs/ci

@plouc If you agree and have a few minutes to spare, it would be cool if you could install the app and link it to the repo. I can take care of the configuration after that!

**Comment by plouc** [comment]
@wyze, that's a really good idea, I've installed the app and added the necessary config, you can test it [here](https://github.com/plouc/nivo/pull/1193).

**Comment by wyze** [comment]
I'm going to close this since it is done and working good. Website covers a lot, but might add separate sandboxes for individual charts at a later date.
