### ISSUE TITLE
Support for tool tip on custom bar component

### ISSUE THREAD

**Issue by paulgodfrey** [plouc/nivo#1182]
**Is your feature request related to a problem? Please describe.**

I'd like to have the ability to add tooltips (custom would be great) to a custom bar component. I've looked through the documentation and although it doesn't explicitly say they aren't supported they don't seem to work.

**Describe the solution you'd like**
It'd be great to have the flexibility to use the existing tooltip support when passing in a custom bar component (might require additional hooks on the bar component)

**Describe alternatives you've considered**
It looks like the only way to have tooltips is to no use custom charts but unfortunately for our use case we've heavily customized the bar component and can't use the standard bar component.

Thanks for building such an amazing charting library!

**Comment by nigellima** [comment]
Hey @paulgodfrey could you try this? That works for me:

```
export const BarItem: FC<BarItemProps> = (props) => {
  const {
    x, y, width, height, color, data, showTooltip, hideTooltip,
  } = props;

  return (
    <g
      transform={`translate(${x}, ${y})`}
      onMouseMove={(event): void => {
        showTooltip(<Tooltip currentBar={data} />, event);
      }}
      onMouseLeave={(event): void => {
        hideTooltip();
      }}
    >
      <rect
        width={width}
        height={height}
        fill={color}
        strokeWidth="1"
        stroke={data.data[`${data.id}Color_Border`]}
      />
    </g>
  );
};
```

Then you pass this custom component to the Bar/ResponsiveBar component as `barComponent={CustomBarComponent}`

**Comment by paulgodfrey** [comment]
This works great, thank you @nigellima !!!

**Comment by wyze** [comment]
Going to close this as it looks like a working solution was posted. Feel free to comment if we need to reopen the issue.

**Comment by garretteklof** [comment]
Is this still relevant? I'm trying to figure out how to refactor my app that previously relied on `BarDefaultProps` (which seems to no longer exist). I do not have `showTooltip` or `hideTooltip` in props passed to `barComponent`. Any help is greatly appreciated!

**Comment by plouc** [comment]
@garretteklof you can use the dedicated hook for that, `useTooltip()`, this is now using a React context, you can [see how it's used in the default bar component](https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.tsx).

**Comment by garretteklof** [comment]
Awesome — cheers!

**Comment by SebasQuirogaUCP** [comment]
> Hey @paulgodfrey maybe you would try this? That works for me:
> 
> ```
> export const CustomBarComponent: FC<BarItemProps> = (props) => {
>   const {
>     x, y, width, height, color, data, showTooltip, hideTooltip,
>   } = props;
> 
>   return (
>     <g
>       transform={`translate(${x}, ${y})`}
>       onMouseMove={(event): void => {
>         showTooltip(<Tooltip currentBar={data} />, event);
>       }}
>       onMouseLeave={(event): void => {
>         hideTooltip();
>       }}
>     >
>       <rect
>         width={width}
>         height={height}
>         fill={color}
>         strokeWidth="1"
>         stroke={data.data[`${data.id}Color_Border`]}
>       />
>     </g>
>   );
> };
> ```
> 
> Then you pass this custom component to the Bar/ResponsiveBar component as `barComponent={CustomBarComponent}`

Update

```TS
  const CustomBarComponent: FunctionComponent<
    BarItemProps<Record<string, string | number>>
  > = (props) => {
    const { bar } = props;
    return (
      <g>
        <rect
          width={"10px"}
          strokeWidth="1"
        />
      </g>
    );
  };

```
