### ISSUE TITLE
Bar Y Axis Ticks can overlap the bars

### ISSUE THREAD

**Issue by ollwenjones** [plouc/nivo#1187]
**Describe/explain the bug**
If Y axis label rotation is more than +/- 90, they can 

**To Reproduce**
1. Create a bar chart, and set the label rotation to -136
2. Observe the labels overlap the bars.

**Expected behavior**
If the end of the label which is oriented to the tic can flip for X axis, it makes sense that the Y axis should do the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/1319208/97244129-32540100-17ce-11eb-9de4-36f704f09383.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 86

**Additional context**
Understand this is probably lower priority as going past 90 on the Y axis doesn't have much value, but I thought it might be worth tracking.

**Comment by nigellima** [comment]
@ollwenjones you probably need to increase the margin left of your chart. Something like:

```

<ResponsiveBar
          data={data}
          keys={keys}
          indexBy="x"
          margin={{
            bottom: 0,
            left: 120,
          }}
.
.
.
.
```

**Comment by ollwenjones** [comment]
@nigellima I'm actually already calculating the margin based on character length of longest label, so there's actually plenty of room there. These aren't pushed by the edge of the container, they just rotated on the tick anchor point.

**Comment by nigellima** [comment]
@ollwenjones oh, I see, indeed you have space there. Have you tried changing the `legend` position prop in the `axisLeft`?
If that does not work, you could bring your own tick component and set your svg properties

```
axisLeft={{
            orient: 'left',
            renderTick: axisTick,
            tickSize: 0,
            tickPadding: 15,
            tickRotation: 0,
            legend: '',
            legendOffset: -40,
            legendPosition: 'middle',
          }}
```

**Comment by ollwenjones** [comment]
I don't think legend will affect this, and you are correct about own svg properties. The X axis marks already have the behavior I was describing, so it doesn't seem like a huge lift on the surface. In our product, I'll probably limit the rotation to +/- 90, anyway.

**Comment by jcvegan** [comment]
@ollwenjones how do you rotate the labels?

**Comment by ollwenjones** [comment]
@jcvegan we have another part of our UI where the user can configure that rotation prop. We just decided to limit it there to avoid this scenario.
