### ISSUE TITLE
Bars Overlap axis When minValue is greater than 0.

### ISSUE THREAD

**Issue by ollwenjones** [plouc/nivo#1188]
**Describe/explain the bug**
If bar axis minimum is set much above 0, the bars extend off the edge of the chart and obscure the axis & its labels

**To Reproduce**
https://codesandbox.io/s/nivobar-chart-overlapping-axis-mod21?file=/src/index.js

1. Create a bar chart with either orientation.
2. Set `minValue` to be > 0. 20% or so of smallest entry works best to reproduce.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1319208/97244935-4dc00b80-17d0-11eb-9b85-1da6d294c39a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86

**Additional context**
I might be able to work around this in my app by adjusting the stack order...

**Comment by ollwenjones** [comment]
@plouc mentioned on discord we could [clamp](https://github.com/d3/d3-scale#continuous_clamp) this except it's very complex given how flexible the bar behavior is (grouped vs stacked), (bars vs columns,) etc. It seems like it would be straightforward for grouped bars based on orientation. I can see how stacked values would make this more complex, though.

**Comment by wyze** [comment]
Adding logic in the scales package for `clamp` on the linearScale seems straight forward. Then you can pass `valueProp={{ type: 'linear', clamp: true }}` and get desired results. Minor tick overlapping on the right axis, but that's because you specified a 0 tick value so it is getting clamped to the 1 position.

![image](https://user-images.githubusercontent.com/186971/98577539-b6ec5800-2281-11eb-81e0-a07cda15f4b9.png)

**Comment by ollwenjones** [comment]
@wyze super cool. The specified tickValues were just something from the example I grabbed; nothing important. Is that something you did just there in codesandbox, or were there additional changes to the way Bar exposes its scales to do it?

**Comment by wyze** [comment]
Just a couple changes to scales package. Here https://github.com/plouc/nivo/blob/8451c279099d3931afc35950ae52aa22b84ee7f6/packages/scales/src/linearScale.js#L13 add something like `, clamp = false` to the first parameter.

Then somewhere down here https://github.com/plouc/nivo/blob/8451c279099d3931afc35950ae52aa22b84ee7f6/packages/scales/src/linearScale.js#L34 add `if (clamp) { scale.clamp(true) }`.

Update PropTypes in that `linearScales` file.

Update typings for scales package here https://github.com/plouc/nivo/blob/8451c279099d3931afc35950ae52aa22b84ee7f6/packages/scales/index.d.ts#L16 with `clamp?: boolean`. 

That should do it.

**Comment by ollwenjones** [comment]
That is about the friendliest indirect invitation to PR that I have ever received 😄

**Comment by wyze** [comment]
I wasn't sure if you wanted to contribute or not, don't feel pressured to do so. :)

**Comment by ollwenjones** [comment]
would love to. just racing towards a deadline at present. This is linked in our backlog, so it's not unlikely someone will circle back and contribute :D

**Comment by ollwenjones** [comment]
Hoping to have some time to contribute here, soon.
