### ISSUE TITLE
onMouseEnter, onMouseLeave or onHover event for HeatMap

### ISSUE THREAD

**Issue by emlchan** [plouc/nivo#1190]
I am trying to implement a click effect in HeatMap so that the clicked cell remains highlighted. A way I think I can achieve that is to manipulate the SVG element during the onClick event. However, the hover effect will reset that almost immediately.

I think the quickest solution that you can do is to allow onMouseEnter and onMouseLeave event just like ScatterPlot. If there is an onHover event for me to use, even better.

**Comment by NicoleA505** [comment]
Is there now an existing way to do what was asked in the original question?
 I'm also trying to figure out how to keep a clicked cell "highlighted". Essentially I'm trying to keep the current hover style on a Cell to remain active if a user clicks that cell.
