### ISSUE TITLE
Grid Component

### ISSUE THREAD

**Issue by dmagill89** [plouc/nivo#1191]
**Is your feature request related to a problem? Please describe.**
I need to be able to display a large grid, each block being one item in that grid. Tool tip for each square should pass the data object in.

**Describe the solution you'd like**
A grid component with custom columns/rows and total, similar to waffle component but I need each square to always be exactly one entry of the data input. Imagine the waffle component but instead of having only three data entries but having hundreds or thousands of data points and each square being one of them.

**Describe alternatives you've considered**
Currently my solution is to use the waffle canvas element, and then doing value of 1 and calculating using the total number of items. Often we'll display different grids or filter them on the fly and then they won't always match up to the columns/rows ratio making 2 or more squares represent one data object. 

**Additional context**

**Comment by plouc** [comment]
@dmagill89, I think that for this use case (as I understand it at least), you could use a simple CSS grid for example with `auto-fill` or `auto-fit`.

**Comment by dmagill89** [comment]
@plouc, hopefully to provide a little bit more insight I'd like to use nivo reasons being already using it throughout my app and additionally been utilizing the canvas components a lot e.g. this grid could be in the tens of thousands so a pure html/css solution doesn't have the performance. I've successfully been able to use the canvas waffle component to temporarily achieve what I want but it'll make my life a lot easier if there was a simple grid component.
