### ISSUE TITLE
@nivo/bar custom color

### ISSUE THREAD

**Issue by potatoengineer** [plouc/nivo#1192]
For some reason when I am trying to apply custom color to my bar graph, it is giving me shades of a single color instead of taking the color from data and using it.  I have a simplified dataset in codesandbox with just 3 objects and simple colors (red, green, blue) and it works perfectly but in my app I have this strange output:
![image](https://user-images.githubusercontent.com/62916212/97537049-63bdff80-197b-11eb-9abc-6c7ffd3b9c0a.png)

It seems to be applying color from a different index instead of the appropriate color?

CodeSandbox: https://codesandbox.io/s/dawn-violet-174k1?file=/src/App.js

My sample data:
const data = [{Game: 'Among Us', Percent: 55, color: 'red'},{Game: 'Phasmophobia', Percent: 36, color: 'green'},{Game: 'WarZone', Percent: 90, color: 'green'}

My code:
```
export const Bar = ({ data }) => (
	<ResponsiveBar
		data={data}
		keys={['Percent']}
		indexBy="Game"
		margin={{
			top: 50,
			right: 130,
			bottom: 50,
			left: 60,
		}}
		padding={0.3}
		maxValue={100}
		groupMode="grouped"
		layout="horizontal"
		colors={datasets.map((d) => d.color)}
		colorBy="index"
		borderColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
		axisTop={null}
		axisRight={null}
		axisBottom={{
			tickSize: 5,
			tickPadding: 5,
			tickRotation: 0,
			legend: 'Percent (%)',
			legendPosition: 'middle',
			legendOffset: 35,
		}}
		enableGridX="true"
		labelSkipWidth={12}
		labelSkipHeight={12}
		labelTextColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
		legends={[]}
		animate={false}
		motionStiffness={90}
		motionDamping={15}
	/>
);
```

**Comment by plouc** [comment]
@potatoengineer, it's harder to tell without knowing your exact environment, you could try to replace `colors={datasets.map((d) => d.color)}` with `colors={(d) => d.data.color}`, this way you bypass the nivo mapping to directly use the color defined in your data.

**Comment by potatoengineer** [comment]
That fixed the issue. Thank you!
