### ISSUE TITLE
Error: When installed @nivo/bump, it breaks my react app showing error of unresolved dependency

### ISSUE THREAD

**Issue by meetzaveri** [plouc/nivo#1198]
**Describe/explain the bug**
I installed scoped package of `@nivo/bump`.  When I integrated it into my app, it crashes my webpack dev server(create-react-app) showing "**Module not found: Can't resolve '@nivo/axes'** "

As expected the scoped package should work without throwing any dependency error. Thanks

**To Reproduce**
My app is scaffolded with create-react-app. Install `@nivo/bump`  and render the example of it in your app

1. Scaffold any app with create-react-app
2. Install `@nivo/bump` 
3. Render example from example in docs
4. See the crash report/log in console

**Expected behavior**
As expected when I install any scoped package, it should work without breaking the app. The chart should get rendered if integrated in app.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Browser Chrome
 - Version 86.0.4240.75

**Comment by wyze** [comment]
You can install that package manually, but it looks like it is missing from the dependencies, so we need to get that fixed.

**Comment by plouc** [comment]
@meetzaveri, thank you for reporting this issue, I've created a [PR to fix this](https://github.com/plouc/nivo/pull/1200), making it an explicit dependency.

**Comment by meetzaveri** [comment]
Thank you guys for the prompt response :raised_hands:
