### ISSUE TITLE
Format dot hover label in line chart

### ISSUE THREAD

**Issue by jonathaningram** [plouc/nivo#120]
When you have a line chart, is it possible to format the label that is shown in the box that appears when you hover over a dot/point?

The use case can be seen in this image. We want to know what date is being shown.

![image](https://user-images.githubusercontent.com/626664/34286917-e63536fa-e737-11e7-91b5-ceee0196c91e.png)

**Comment by spredemann** [comment]
@jonathaningram may I ask what setting is used to not show every tick on the xAxis? And +1 for label customization.

**Comment by plouc** [comment]
@spredemann, you can use the `tickValues` property on each axis definition.

**Comment by plouc** [comment]
Duplicate of https://github.com/plouc/nivo/issues/117

**Comment by plouc** [comment]
see https://github.com/plouc/nivo/issues/192 for progress
