### ISSUE TITLE
only show final point on a line chart?

### ISSUE THREAD

**Issue by ianstormtaylor** [plouc/nivo#1201]
Thanks for this great library!

Right now I can render line charts either with all the points visible or with no points visible. Is there a way to make it so that only the last datum as a point rendered? Or even a way to add a custom point to the plot that is easy to position exactly where the last data point would be?

**Comment by plouc** [comment]
You could use a custom layer, layers receive all computed data and can be used to augment or completely replace part of a chart. You can see an example [here](https://nivo.rocks/storybook/?path=/story/line--custom-layers).

**Comment by wyze** [comment]
I don't think this will be added as an option for out of the box, but like @plouc said you can use a custom layer. I have a codesandbox that shows exactly that right here: https://codesandbox.io/s/fancy-line-chart-3quqe
