### ISSUE TITLE
Calendar Demo Crash after 10sec on nivo.rocks/calendar

### ISSUE THREAD

**Issue by froger** [plouc/nivo#1203]
Hello, 
Visiting the nivo.rocks website, I encounter an error with the calendar demo, here my report, hope it can help.
 
**Describe/explain the bug**
[the demo of the calendar component](https://nivo.rocks/calendar/) crash after few seconds on the nivo.rocks website.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to [https://nivo.rocks/calendar/](https://nivo.rocks/calendar/), don't do any interactions. 
2. Wait more or less 10sec 
3. See error: the screen becomes white

**Expected behaviour**
The component should stay mounted, and I should be able to interact with the component

**Console.log**
```log
23:09:13.666 VM268:1 XHR finished loading: GET "https://nivo.rocks/page-data/bubble/page-data.json".
23:09:15.112 react-dom.production.min.js:4454 Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

**Desktop:**
 - OS: Mac Mojave
 - Browser Chrome
 - Version 86.0

Thank you, and congrats for this great job! Just starting, already in love.

**Comment by wyze** [comment]
I wasn't able to reproduce this. Any other information you can provide? What about in an incognito window?
