### ISSUE TITLE
Question: Change language

### ISSUE THREAD

**Issue by florianbepunkt** [plouc/nivo#1205]
I checked the docs and wonder: How can you change the language? Using some of the format options, for example format: `"%b %d"` as date format, use English as default language.

**Comment by wyze** [comment]
This is currently not supported, but it definitely should be!

**Comment by lnazarit** [comment]
any solution?

**Comment by periakteon** [comment]
Hi, if anyone has the same problem, I will share my solution below.

```js
monthLegend={(_year, month) => {
          return format(new Date(new Date().getMonth(), month, 1), "LLL", {
            locale: tr,
          });
        }}
```

I use `format` function in the library `date-fns/format` and import the language I want from `date-fns/locale`

(I just use the package `@nivo/calendar` and this solution works for that package.)

**Comment by JosePoma11** [comment]
> Hola, si alguien tiene el mismo problema, compartiré mi solución a continuación.
> 
> ```js
> monthLegend={(_year, month) => {
>           return format(new Date(new Date().getMonth(), month, 1), "LLL", {
>             locale: tr,
>           });
>         }}
> ```
> 
> Utilizo `format`la función en la biblioteca `date-fns/format`e importo el idioma que quiero`date-fns/locale`
> 
> (Solo uso el paquete `@nivo/calendar`y esta solución funciona para ese paquete).

Hola este codigo funciona perfecto para los meses pero para los dias de semana tiene una opcion ?
