### ISSUE TITLE
Error: Bump chart throwing error while supplying array data of length '5'

### ISSUE THREAD

**Issue by meetzaveri** [plouc/nivo#1206]
**Describe/explain the bug**
It might not be exactly a bug, but I face this issue when I reduce array size to 5 from the example data in documentation(initially arr size is 13). Referenced it in codesandbox

**To Reproduce**
As per bump example in documentation, I supplied same array in data but with length of 5 instead of 13.

**Expected behavior**
As it was working with example data of array of length 12. it should work with array of length 5 

**Codesandbox**
https://codesandbox.io/s/long-browser-g1hi3

**Screenshots**
This screenshot is when I am using it in my project(create-react-app bootstrapped)
![chrome-capture - 2020-11-02T140552 518](https://user-images.githubusercontent.com/21293048/97846846-9e75be00-1d14-11eb-89d5-d831c4fd56b4.jpg)

**Comment by plouc** [comment]
Fixed in https://github.com/plouc/nivo/pull/1869.
