### ISSUE TITLE
error: "TypeError: (this.options.measures || []).map is not a function"

### ISSUE THREAD

**Issue by manikasharma70** [plouc/nivo#1207]
The following error is coming in the /v1/sql API call.
Can you please let me know what can be the issue.
The Query i have used is this:

{
  "measures": [
    "Application.PercentUtilization"
  ],
  "timeDimensions": [
    {
      "dimension": "Application.servertime",
      "granularity": "day"
    }
  ],
  "order": {},
  "dimensions": [],
  "filters": []
}

**Comment by wyze** [comment]
@manikasharma70 Are you sure you opened this issue on the right repo? I searched the codebase for `sql` and only received hits in yarn.lock file.
