### ISSUE TITLE
Markers at the same position

### ISSUE THREAD

**Issue by guilhermemiua** [plouc/nivo#1213]
Hi!

I'm currently facing a problem which I can have two markers with the same value, but when I render the chart, the second marker label overrides the first. Is there a way to resolve this?

![chart](https://user-images.githubusercontent.com/30276013/98157100-9609b880-1eb7-11eb-9e4b-39af1b534936.png)

**Comment by wyze** [comment]
You can use `textStyle` property of the markers to supply some kind of offset. We don't have any intelligent positioning for markers.

**Comment by guilhermemiua** [comment]
Ok! I'll try it! Thank you! :)
