### ISSUE TITLE
Migrate @nivo/bar to TypeScript

### ISSUE THREAD

**Issue by plouc** [plouc/nivo#1223]

**Comment by keonik** [comment]
This might be unrelated and if so I'll make a new issue.

In the docs, you can use `colorBy` as a prop but in TypeScript it doesn't recognize the prop

Example
```ts
 <ResponsiveBar
                data={data}
                groupMode="grouped"
                reverse={reverse}
                maxValue={3}
                enableGridY={false}
                // @ts-ignore
                colorBy="indexValue"
                indexBy="id"
                colors={{ scheme: 'pastel1' }}
                role="figure"
            />
```

**Comment by wyze** [comment]
It should be just `colors`. `colorBy` was the old way so the docs will need updated.

**Comment by keonik** [comment]
Okay. Heads up the `colorBy` prop works. 

I tried using colors like so
```
colors="indexValue"
```
and it turned everything black. 

Gonna dig around in the type declarations/bar source code to see how to properly set it up. If you all want help rewriting some components to TypeScript I might be able to contribute

**Comment by wyze** [comment]
Not sure 100% what you are trying to achieve, but I think this is the same behavior. https://codesandbox.io/s/summer-cache-7f4bl

**Comment by keonik** [comment]
I was looking for that datum usage. Thank you @wyze

**Comment by FurkanToprak** [comment]
The solution that @wyze gave was good, but I couldn't find any documentation to point to this. The TypeScript def file isn't much help either.
