### ISSUE TITLE
maxValue for radar chart

### ISSUE THREAD

**Issue by archatas** [plouc/nivo#124]
Currently radar chart calculates the maxValue from all the data inputs. That works well if you have all data compared within the same radar chart.

However, if you want to compare data from different elements side-by-side, by drawing multiple radars next to each other, the scale gets inconsistent and the support for custom maxValue is necessary. Can a custom maxValue be added to the radars?

**Comment by ddresch** [comment]
@plouc any hints about where to get started? I also need this kind of feature and at the moment I always overwrite one datapoint to fix it to a maxValue which is just wrong :( and all the other values are the right ones.

**Comment by emanuelebrivio** [comment]
@plouc we need this feature too, we are having issues while comparing different charts but without a maxValue props it's really difficult...

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/209, available in `@nivo/bar@0.40.0`

**Comment by plouc** [comment]
You can see it in action on http://nivo.rocks/radar.
