### ISSUE TITLE
Calendar example in latest docs is breaking on mouseover

### ISSUE THREAD

**Issue by solo474** [plouc/nivo#1246]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

- Open nivo docs here https://nivo.rocks/
- Select calendar example
- mouseover on the calendar visualization
- webpage breaks 

**Expected behavior**

 - OS: MacOs Catelina 
 - Browser Chrome Latest

**Comment by plouc** [comment]
This has been fixed by https://github.com/plouc/nivo/pull/1214 and will be deployed in the next release.
