### ISSUE TITLE
[Pie] Defs patterns doesn't work with custom colors

### ISSUE THREAD

**Issue by Deliaz** [plouc/nivo#1248]
I am trying to add a dots pattern on slice hovering, which uses custom color.
But looks like `background: "inherit"` doesn't work in this case, using black color. Am I missing something? 

<img src="https://user-images.githubusercontent.com/4865430/98232038-d6c00b00-1f65-11eb-82ac-8ddf5c941254.png" alt="issue screenshot" width="340">

Link to sandbox: https://codesandbox.io/s/nivopie-typescript-forked-sqhlo?file=/src/index.tsx
Pie version: 0.63.1

Code: 
```jsx
<Pie
  colors={{ datum: "color" }}
  width={400}
  height={400}
  data={data}
  margin={{
    top: 40,
    right: 80,
    bottom: 80,
    left: 80
  }}
  defs={[
    {
      id: "dots",
      type: "patternDots",
      size: 8,
      background: "inherit",
      color: "rgba(255, 255, 255, 0.5)"
    }
  ]}
  fill={id ? [{ match: { id: id }, id: "dots" }] : []}
  onMouseEnter={({ id }) => setId(id)}
  onMouseLeave={() => setId(null)}
/>
```

**Comment by plouc** [comment]
@Deliaz the problem is with specifying color in `hsl`, which isn't supported (and used in the doc which is quite misleading).

**Comment by plouc** [comment]
I've recreated a working example https://codesandbox.io/s/nivopie-typescript-forked-d0i37.

**Comment by Deliaz** [comment]
@plouc It is clear for me now. Thank you for the fast response!
