### ISSUE TITLE
Support annotations

### ISSUE THREAD

**Issue by jeznag** [plouc/nivo#125]
Is there an easy way to annotate charts along the lines of d3-annotation.susielu.com?

**Comment by plouc** [comment]
You can add an extra layer if the chart you use supports it and use https://react-annotation.susielu.com/

**Comment by plouc** [comment]
Otherwise, I've started to add support for annotations on newer packages, https://nivo.rocks/storybook/?path=/story/swarmplot--using-annotations

**Comment by plouc** [comment]
Note that the provided nivo implementation doesn't use react-annotation to be able to use transitions and to support canvas implementations.

**Comment by mcintyre94** [comment]
@plouc Are line charts supported with annotations? The annotations doc page https://nivo.rocks/guides/annotations is 404ing

**Comment by carlsagan21** [comment]
Hope annotation be implemented in Line or other charts too. Any update?

**Comment by sattuchin** [comment]
This feature would be very useful. Please prioritize when possible. Thank you!

**Comment by BATESTPYTHON** [comment]
I am looking forward for this feature too! For line charts, all I need is a straight vertical line to specify certain events on certain dates on x axis.

**Comment by loganfuller** [comment]
I am also very interested in this feature.
