### ISSUE TITLE
Storyboard mismatch

### ISSUE THREAD

**Issue by sattuchin** [plouc/nivo#1251]
Thank you for creating Nivo! Such a fantastic library!!

The storyboard appears to be broken. I want to get the code for grouped bar chart - and I cant see it correctly

**Steps to reproduce the behavior:**
Go to the following link. The code shown in the story appears to be for another example.
https://nivo.rocks/storybook/?path=/story/bar--grouped

**Screenshots**
Attached screenshot. See how layout="horizontal" shows in the story for the chart, which is vertical

**Desktop:**
 - OS: macOS (High Sierra)
 - Browser: Chrome 86 

![Screen Shot 2020-11-06 at 7 51 04 AM](https://user-images.githubusercontent.com/57167563/98318833-72ed1f00-2005-11eb-81b7-9a1ea79874ec.png)

**Comment by plouc** [comment]
@sattuchin, it seems like there's an issue with the way the story source is collected, this is the code for the race chart, in the meantime, you can find the source here => https://github.com/plouc/nivo/blob/master/packages/bar/stories/bar.stories.js#L35
