### ISSUE TITLE
window is not defined, when using @nivo/pie in Next.JS

### ISSUE THREAD

**Issue by SimplyBallistic** [plouc/nivo#1253]
**Describe/explain the bug**
It doesn't seem like the pie chart `@nivo/pie` supports server side rendering. Others however such as line do.

**To Reproduce**
1. Create a new next app `yarn create next-app`
2. Add pie charts `yarn add @nivo/pie`
3. Go inside `pages` and edit the `index.js` to import `Pie` and try using it with `<Pie/>`

**Expected behavior**
The Pie chart renders server side and all is good.

**Screenshots**
![image](https://user-images.githubusercontent.com/25571542/98328014-ed8b5e00-2048-11eb-9371-f047da344735.png)
![image](https://user-images.githubusercontent.com/25571542/98328070-098eff80-2049-11eb-9635-fbf90acb38c9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: `@nivo/pie: ^0.64.0`

Thank you!

**Comment by plouc** [comment]
@SimplyBallistic, sorry for this, it has been fixed in https://github.com/plouc/nivo/pull/1250 and should be available in the next release.

**Comment by SimplyBallistic** [comment]
no worries, thanks for the quick reply :)

**Comment by gomorizsolt** [comment]
I'm facing with the same issue. As per the releases, #1250 hasn't been made available. When do you plan the next release?

**Comment by plouc** [comment]
@gomorizsolt, I'm gonna try to release tomorrow.

**Comment by gomorizsolt** [comment]
That was quick, thanks, much appreciate it.
