### ISSUE TITLE
Bar chart x-axis not responsive and label for value exceeding 10 is not showing

### ISSUE THREAD

**Issue by potatoengineer** [plouc/nivo#1254]
Using @nivo/bar 0.63.1 and the bottom axes is not responsive to the largest value and the label is not showing for values exceeding 10 even though it's on the tooltip. Labels will show for the top two bars if I set maxValue={50} (both values are below 50) but axes should be auto.

```
<ResponsiveBar
		data={datasets}
		keys={['percentage']}
		indexBy="emotion"
		margin={{
			top: 50,
			right: 60,
			bottom: 50,
			left: 80,
		}}
		padding={0.3}
		enableGridY={false}
		groupMode="grouped"
		layout="horizontal"
		colors={(d) => d.data.color}
		colorBy="index"
		borderColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
		axisBottom={{
			tickSize: 5,
			tickPadding: 4,
			tickRotation: 0,
			legend: 'Percent (%)',
			legendPosition: 'middle',
			legendOffset: 40,
		}}
		labelSkipWidth={12}
		labelSkipHeight={12}
		labelTextColor={{ from: 'color', modifiers: [['brighter', 2]] }}
		animate={false}
		motionStiffness={90}
		motionDamping={15}
	/>
```
![image](https://user-images.githubusercontent.com/62916212/98343095-2b936e00-1fc6-11eb-8602-8e959a4774c2.png)

**Comment by plouc** [comment]
@potatoengineer could you please reproduce this in codesanbdox? It's hard to tell without the data.

**Comment by potatoengineer** [comment]
https://codesandbox.io/s/nivo-basic-demo-forked-os0bo

**Comment by plouc** [comment]
@potatoengineer values should be numbers, please see https://codesandbox.io/s/nivo-basic-demo-forked-xddsk.
