### ISSUE TITLE
Nivo bar bug introduced in 0.64

### ISSUE THREAD

**Issue by codler** [plouc/nivo#1255]
**Describe/explain the bug**
The bar crashed in new v0.64, it worked in previous version 0.63.1

**To Reproduce**
Here is an example, you can switch dependency between versions to see difference.
https://codesandbox.io/s/bar-custom-color-forked-zm065?file=/src/index.js

**Expected behavior**
It should not crash

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by wyze** [comment]
Hi @codler, thank you for opening an issue and including a CodeSandbox. The issue is with your data, specifically the last item in the array, it is missing the `compareCount` key. For now, you can add it with a zero value, but I have a fix incoming.

**Comment by codler** [comment]
@wyze It is intentionally "missing"/undefined on the last compareCount key, I dont want the bar to show 0 on that item

**Comment by wyze** [comment]
Okay, no worries, it is something I didn't account for in my refactor.

**Comment by stahlmanDesign** [comment]
@codler, thank you for creating the [CodeSandbox](https://codesandbox.io/s/bar-custom-color-forked-n7re4) I have this exact same problem. When I generate my data, I only add the data that is pertinent so this failed starting with 0.64.0 for the exact reason you showed in your example.

**Comment by stahlmanDesign** [comment]
@wyze This is this a bug if you remove `groupMode: 'grouped'`. Here's an example with 0.65.1 where you can uncomment the `groupMode: 'grouped'` to see it fail https://codesandbox.io/s/bar-custom-color-forked-n7re4?file=/src/index.js

**Comment by wyze** [comment]
Correct, I opened #1291 to fix it. I tested it out in grouped/stacked, horizontal/vertical, and it matches output of 0.63, before I introduced valueScale prop. I am going to add a couple tests to prevent regression again.
