### ISSUE TITLE
Responsive bar - empty data show nothing

### ISSUE THREAD

**Issue by ariel-upstream** [plouc/nivo#1260]
Hi,
I'm using the Nivo responsive bar component.
My issue: when the data is empty the bar chart is completely disappeared and I want the user will see a little thin line when the chart data is empty.
I tried to set the default values to 0 or 1, 
but I think because the chart is responsive it will show full chart (1) or nothing (0)

```
  <ResponsiveBar
          data={data}
          keys={...}
          indexBy={getIndex}
          colors={getChartsColor}
          enableLabel={false}
          enableGridX={false}
          enableGridY={false}
          isInteractive={false}
          labelFormat=".0s"
          axisTop={null}
          axisRight={null}
          axisLeft={null}
          animate={true}
          motionStiffness={90}
          motionDamping={15}
        />
```

**Comment by wyze** [comment]
If all the data is empty, I'm not sure there is much we can do about that. You could try using a custom layer to present something.

**Comment by ariel-upstream** [comment]
> If all the data is empty, I'm not sure there is much we can do about that. You could try using a custom layer to present something.

Does Nivo support a custom layer?

**Comment by wyze** [comment]
Yes, you can see here the `markerLayer` component is a custom layer provided to the chart: https://codesandbox.io/s/dreamy-robinson-x3ktp
