### ISSUE TITLE
Pie tooltip is child of other divs

### ISSUE THREAD

**Issue by ebernerd** [plouc/nivo#1263]
**Describe/explain the bug**
When using the `<ResponsivePie />`'s `tooltip` prop to render a custom tooltip, the rendered HTML is inside of a few divs that make it really hard to style, unlike the way I can a `<ResponsiveLine />`'s tooltip.

**To Reproduce**
[Code Sandbox](https://codesandbox.io/s/summer-flower-0hd7m?file=/src/App.tsx)

1. Hover over any point on the Line graph. You'll see that the div returned from the `tooltip` function is all on its own, and the result is a tooltip whose background is entirely red.
2. Hover over any point on the Pie graph. You'll see that the div returned from the `tooltip` is inside of other divs, so the result is a red div inside of some white padded divs.

**Expected behavior**
I think that the Pie tooltip should behave like the Line tooltip, where the tooltip is completely controlled by the `tooltip` prop.

**Screenshots**
Line graph (correct, as expected):
![image](https://user-images.githubusercontent.com/8388562/98582290-c4f5a500-2290-11eb-9889-782a445f6738.png)

Pie graph (unexpected, renders with extra padding):
![image](https://user-images.githubusercontent.com/8388562/98582306-cde67680-2290-11eb-817f-051e590cd9ef.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version 0.62+

**Comment by plouc** [comment]
Hi @ebernerd, the `pie` package was migrated to TypeScript recently along with a few updates and improvements, including making the tooltip consistent with other chart types, please upgrade @nivo packages to their latest version, also note that the API changed a little bit, some props have been renamed.
