### ISSUE TITLE
LineCanvas: Slices support.

### ISSUE THREAD

**Issue by OlegKosarev502** [plouc/nivo#1266]
Hey, thanks for great data visualization library :+1: :1st_place_medal: 
In our project we would like to migrate to `LineCanvas` from `Line`. But I've found that `LineCanvas` doesn't support slices. We actively use slices for our line charts and it will be great to have it in `LineCanvas`. 
Could you please add this functionality to `LineCanvas`? :raised_hands: 
Do you have any plans about this?
Thanks a lot :raised_hands:

**Comment by plouc** [comment]
@OlegKosarev502, no plan for this specific feature right now, we're working on the TypeScript/React hooks/react-spring migration of all packages currently, and it's gonna take a while...
