### ISSUE TITLE
Responsive bar chart height and position

### ISSUE THREAD

**Issue by ariel-upstream** [plouc/nivo#1269]
Hi,
I'm using the responsiveBar component and I did wrap it with a div with specific width and height,
My issue is that the chart adjacent to the top of the div container and doesn't stretch to all of the container.

I tried to change the position with styles on the div parent (flex and justify-content) but it doesn't help.

```
  chartContainer: {
    height: "4rem",
    width: "5rem",
    margin: "0 auto",
    padding: "0.5rem 0",
    textAlign: "center",
  }
```

```
      <div className={classes.chartContainer}>
        <ResponsiveBar
          data={data}
          keys={keys}
          indexBy={getIndex}
          colors={colors}
          margin={{ top: 0, right: 0, bottom: 20, left: 0 }}
          enableLabel={false}
          enableGridX={false}
          enableGridY={true}
          gridYValues={0.5}
          isInteractive={false}
          padding={0.1}
          labelFormat=".0s"
          minValue={0}
          axisBottom={{
            tickValues: [`f1`, `f2`],
          }}
          axisTop={null}
          axisRight={null}
          axisLeft={null}
          animate={true}
        />
      </div>
```

![chart-top](https://user-images.githubusercontent.com/69746819/98798412-87bb1f80-2416-11eb-8da9-4de6249e1ba2.png)

**Comment by plouc** [comment]
@ariel-upstream, as you have `padding: 0.5rem` + `margin.bottom: 20`, it seems normal, just looking at the code.

**Comment by ariel-upstream** [comment]
> @ariel-upstream, as you have `padding: 0.5rem 0` + `margin.bottom: 20`, it seems normal, just looking at the code.

If I remove it I will get the same result as now

**Comment by plouc** [comment]
@ariel-upstream could you recreate this in codesandbox?

**Comment by ariel-upstream** [comment]
Thanks.
but if I change the margin to margin={{ top: 0, right: 0, bottom: 0, left: 0 }} the x axisBottom tickvalues are disappears

**Comment by plouc** [comment]
Yes, as there was no axis in your screenshot I assumed you weren't using them.

**Comment by ariel-upstream** [comment]
How can I solve it?

**Comment by plouc** [comment]
@ariel-upstream it's gonna be difficult unless you provide a running example using codesandbox, I don't know what the issue is and I'm not sure about what you're trying to achieve.

**Comment by plouc** [comment]
I've tried to reproduce it and I don't get this issue https://codesandbox.io/s/nivo-basic-demo-forked-x7ptv

**Comment by ariel-upstream** [comment]
> I've tried to reproduce it and I don't get this issue https://codesandbox.io/s/nivo-basic-demo-forked-x7ptv

I upgraded the version from 0.62 to 0.63 and it fixed.
Thanks!
