### ISSUE TITLE
In Pie Chart 

### ISSUE THREAD

**Issue by AkashMishraMS** [plouc/nivo#127]
In pie chart how to increse font size of value shown by in graph.
how to increase slice lable font size.

please reply with solution on my mail:-akashmishra989ha@gmail.com

**Comment by plouc** [comment]
You can give your chart a theme object and increase the `theme.axis.fontSize` property.

**Comment by FrankBrullo** [comment]
Hi,
I tried with the theme but it doesn't work.
Looking at your code it seems that you are taking the font size from `theme.labels.text.fontSize` and not from `theme.axis.fontSize`.
Also, your TypeScript definition of labels is specifying only textColor.
I tried a hacky way to overcome TypeScript and it correctly changed the font size of the pie chart
Here is the code:
`theme.labels = Object.assign(theme.labels, {text: {fontSize: '35px'}});`

Could you please fix the TypeScript definition to include fontSize and perhaps fill within labels.text?

Thanks

**Comment by plouc** [comment]
Hi @FrankBrullo,

It wasn't the case when this issue was opened :) but you're right now it's `theme.labels.text.fontSize`.
Regarding the TypeScript definition, could you submit a Merge Request?
I'm pretty busy and won't have the time to fix this at the moment.

**Comment by FrankBrullo** [comment]
Sure.
While I am changing the definitions do you mind if I fix also SVG defs?
Right now they are defined to have only an id while they should have more optional attributes like: type, background, color, etc.

This time I did a Typescript trick to overcome this issue (see below. I used your example code and modified it) but it will be nice to have it fixed in the main component library.

`interface SVGDef {
    id: string;
    type: string;
    background: string;
    color: string;
    size: number;
    padding: number;
    stagger: boolean;
};

type SVGDefs = SVGDef[];
const defs: SVGDefs = [
                        {
                            id: "dots",
                            type: "patternDots",
                            background: "inherit",
                            color: "rgba(255, 255, 255, 0.3)",
                            size: 4,
                            padding: 1,
                            stagger: true
                        },
                        {
                            id: "lines",
                            type: "patternLines",
                            background: "inherit",
                            color: "rgba(255, 255, 255, 0.3)",
                            rotation: -45,
                            lineWidth: 6,
                            spacing: 10
                        }
                    ];
return (
                <ResponsivePie
                               data={data}
                               defs={defs}
                  />
`

**Comment by plouc** [comment]
Of course :)

**Comment by FrankBrullo** [comment]
I forked the project but it seems that the module present in NPM is quite old compared the code in GIT. I think that if you spin a new build in NPM it will fix all the problems.
It seems also that a build failed 3 days ago on NPM.
Any chance you can spin a new build there?

Thanks,
Frank

**Comment by plouc** [comment]
@FrankBrullo the package is 4 days old

<img width="339" alt="screenshot 2018-11-05 at 23 48 42" src="https://user-images.githubusercontent.com/501642/48004856-62271b80-e155-11e8-9aec-880864adcf0f.png">

**Comment by plouc** [comment]
Where did you saw that the build failed 3 days ago on NPM?

**Comment by FrankBrullo** [comment]
Sorry I didn't realize I was looking at the main Nivo page on NPM.
Nivo Pie is updated and it fixed the issue.
Thank you very much!! :)

BTW on the main screen of the Nivo page on NPM (https://www.npmjs.com/package/nivo) below the Nivo logo there is a marked that says "build: failing"
![screen shot 2018-11-05 at 10 39 39 am](https://user-images.githubusercontent.com/43351788/48008415-a4197880-e0e7-11e8-860e-9f61673414eb.png)

which links to travis and you can read the details there:

https://travis-ci.org/plouc/nivo
Not sure if this is important or not.
