### ISSUE TITLE
Make it possible to control each node label position individually

### ISSUE THREAD

**Issue by vinibanaco** [plouc/nivo#1270]
**Is your feature request related to a problem? Please describe.**
Long Sankey labels ends up overlapping when using `labelPosition="inside"`, and using `labelPosition="outside"`, some content may be off the screen.

**Describe the solution you'd like**
Each node would have its own `labelPosition` attribute that overrides the `labelPosition` prop.

**Additional context**
[CodeSandbox example](https://codesandbox.io/s/nivo-sankey-label-overlapping-fc9iu?file=/src/index.js)

![image](https://user-images.githubusercontent.com/44006807/98816291-335c7380-2407-11eb-963e-742f4f080c3c.png)

**Comment by plouc** [comment]
@vinibanaco, it would have to be defined on the nodes themselves, or defined as a mapping in another prop, I think this would make a complex API, I think the best to get full control over label position is to use a custom layer and disable the default one for labels.

**Comment by plouc** [comment]
@vinibanaco, you can have a look at this example: https://codesandbox.io/s/nivo-sankey-label-overlapping-forked-34lhc?file=/src/index.js, I've just create an extra layer where it returns null for now, you can use it as a base to implement custom positioning.

**Comment by vinibanaco** [comment]
The way I'm suggesting I don't think this would make a complex API. Each node object would have a `labelPosition` that may receive 'inside' or 'outside' (just like the prop):
```js
nodes: [
  { id: 'Some text' },
  { id: 'Another text', labelPosition: 'outside' },
  { id: 'Some really long text', labelPosition: 'outside' },
  { id: 'Another really long text' },
  { id: 'Last text' },
],
```
The expected result would be something like:
![image](https://user-images.githubusercontent.com/44006807/98823596-12008500-2411-11eb-8520-3d5173c777fd.png)

I don't know if I made myself clear before, but I don't see the need of a full control over the label positioning. I know that my approach doesn't solve all the cases (e.g. the first node could also have a long text, so it would be overlaid by some label from the second column), but I think it's cool to have this possibility.

**Comment by dorin-moldoveanu-assist** [comment]
Hey there,
Have you managed to find a solution for your issue ? I'm finding myself in your shoes :)
Any advice is well received.
Thanks.

**Comment by vinibanaco** [comment]
@dorin-moldoveanu-assist Hello! I did what @plouc suggested in [this comment](https://github.com/plouc/nivo/issues/1270#issuecomment-725432881) and it worked perfectly. For the use case I've mentioned in this post this was kind of an overkill solution, but soon after I felt the need to make some other modifications, like rotating the first label 90deg and adding descriptions to some of the labels, so at the end this "boilerplate" really paid off.

**Comment by dorin-moldoveanu-assist** [comment]
@vinibanaco many thanks for the quick response. I've managed to make it work based on the same comment.
Thanks @plouc & @vinibanaco .

**Comment by mnkcoder** [comment]
on a related label positioning topic, is it possible to set position to the top?

**Comment by emrerdem1** [comment]
> @vinibanaco, you can have a look at this example: https://codesandbox.io/s/nivo-sankey-label-overlapping-forked-34lhc?file=/src/index.js, I've just created an extra layer where it returns null for now, you can use it as a base to implement custom positioning.

The CodeSandbox link is not working anymore, can you share Stackblitz code or just a code snippet, if possible? @vinibanaco

**Comment by vinibanaco** [comment]
> > @vinibanaco, you can have a look at this example: https://codesandbox.io/s/nivo-sankey-label-overlapping-forked-34lhc?file=/src/index.js, I've just created an extra layer where it returns null for now, you can use it as a base to implement custom positioning.
> 
> The CodeSandbox link is not working anymore, can you share Stackblitz link or just a code snippet, if possible? @vinibanaco

[Here you go!](https://stackblitz.com/edit/vitejs-vite-x62pts?file=src%2FApp.jsx) I don't quite remember what everything does because I wrote this code a long time ago, but the most important bit is the `layers` prop. It which allows you to pass a function to customize how the layer is rendered.

Positioning the SVG elements was kind of tricky, but unless your use case is way different than mine I guess you can just tweak some numbers (mainly the `margin` prop and the `LABEL_MARGIN` constant in LabelsLayer.jsx) to position your labels accordingly.

As I said I don't remember most of the code, but if something wasn't clear feel free to ask and I'll see if I can help.
