### ISSUE TITLE
All release dates in CHANGELOG are the same

### ISSUE THREAD

**Issue by EpicEric** [plouc/nivo#1277]
**Describe/explain the bug**
The dates for all releases in [CHANGELOG.md](https://github.com/plouc/nivo/blob/ea1ff453e30d9890a858b39e90026d7cf1d80b8a/CHANGELOG.md) appear as "2020-11-06" instead of the actual dates.

**Comment by wyze** [comment]
Interesting find! Looks like it is caused by this here in the library we use: https://github.com/clog-tool/clog-lib/blob/b8a4f5be6b22153b45dd69144557f77768b86ccc/src/fmt/md_writer.rs#L76-L94
