### ISSUE TITLE
Accept itemWidth as function for dynamic legend label text width

### ISSUE THREAD

**Issue by furedal** [plouc/nivo#1280]
Legends doesn't look very nice when having legends in a horizontal direction and the texts is in different lengths.
I am aware that SVG doesn't support wrapping texts but there is some logical solutions that could be made.

I have been looking in to the code a bit and I think a viable solution would be to accept a function for itemWidth.
This function accepts the legends label as a parameter and returns a number.

I have been trying to make this work by myself but there is some anchor problems with my current solution so i'm not making any PRs atm. I just want to share the direction I have been looking in to and see if anyone has a deep knowledge of the codebase that wants to fix this correctly 😊

What I can see [LegendSvg.js](https://github.com/plouc/nivo/blob/master/packages/legends/src/svg/LegendSvg.js#L49) needs a few changes.
```
 const { padding } = computeDimensions({
        itemCount: data.length,
        itemWidth: 0, // <- Since this code only makes use of the resulting padding, we can pass 0 here
        itemHeight: 0, // <- Same here
        itemsSpacing,
        direction,
        padding: _padding,
    })

    let currentX = padding.left
    let currentY = padding.top
    return (
        <g transform={`translate(${x},${y})`}>
            {data.map((data, i) => {
                const calcItemWidth = typeof itemWidth == 'function' ? itemWidth(data.label) : itemWidth
                const calcItemHeight = typeof itemHeight == 'function' ? itemHeight(data.label) : itemHeight

                const result = <LegendSvgItem
                    key={i}
                    data={data}
                    x={currentX}
                    y={currentY}
                    width={calcItemWidth}
                    height={calcItemHeight}
                    direction={itemDirection}
                    justify={justify}
                    effects={effects}
                    textColor={itemTextColor}
                    background={itemBackground}
                    opacity={itemOpacity}
                    symbolShape={symbolShape}
                    symbolSize={symbolSize}
                    symbolSpacing={symbolSpacing}
                    symbolBorderWidth={symbolBorderWidth}
                    symbolBorderColor={symbolBorderColor}
                    onClick={onClick}
                    onMouseEnter={onMouseEnter}
                    onMouseLeave={onMouseLeave}
                />

                if (direction === 'row') {
                    currentX += calcItemWidth + itemsSpacing
                } else if (direction === 'column') {
                    currentY += calcItemHeight + itemsSpacing
                }

                return result
                }
            )}
        </g>
    )
}
```

And then there are some other places that `itemWidth` is being used that needs a proper look at, for example:
[BoxLegendSvg.js](https://github.com/plouc/nivo/blob/master/packages/legends/src/svg/BoxLegendSvg.js#L67)

**Comment by chrise86** [comment]
This (or something that achieves the same end result) would be very useful 👍
