### ISSUE TITLE
Reverse bar chart legend

### ISSUE THREAD

**Issue by onionhammer** [plouc/nivo#1285]
Bar charts underwent some changes and the somewhat hacky way I was getting the legends and bars to order correctly before no longer works, so now I'm trying to just follow the examples and get the legends in the same order as the bars and I'm having issues.

![image](https://user-images.githubusercontent.com/969938/99277127-118e3280-27f3-11eb-8f4f-f550d966ff85.png)

Long story short, I can't seem to get the legend to go the same way as the bars.

**Comment by wyze** [comment]
What was the old code you were using?

**Comment by onionhammer** [comment]
@wyze I was setting the 'keys' attribute to an array with the values in the right order, but after upgrading to 0.65 every item in the legend was the same color and the chart was empty.

So it *was* a chart where keys was in the opposite order as the data

**Comment by onionhammer** [comment]
Here's a repro

Vertical chart has the legend in the right order, horizontal is reversed

https://codesandbox.io/s/nivo-basic-demo-forked-2wz95?file=/src/index.js:866-867

**Comment by wyze** [comment]
Thanks for that sandbox, it is very helpful. Looks to be 2 different issues going on here. I've updated the sandbox to at least get your data displaying in 0.64, or 0.65 now. https://codesandbox.io/s/nivo-basic-demo-forked-uyxko?file=/src/index2.js

I had to add null values for all the keys, definitely a bug and I'll look into a PR shortly. The legend colors should receive the same value from the bar, but that doesn't seem to be happening, so I will need to look at that as well.

**Comment by onionhammer** [comment]
Another nice to have might be to add some more layout options. Horizontal goes from left to right, but vertical goes from bottom to top. This could be resolved with a "vertical-reverse" option, and a "horizontal-reverse" option (for consistency) to flip the order of bars

**Comment by plouc** [comment]
@onionhammer, there's already a `reverse` option on the chart, I think this could be a bit confusing. I think it would be nice to add a way to sort the legends the way we want.

**Comment by onionhammer** [comment]
Any update on this issue? I'm holding off upgrading to the latest version of nivo due to this order issue. Would switch to a funnel if it supported legends

**Comment by wyze** [comment]
You can implement in a custom layer and have full control over the legend: https://codesandbox.io/s/nivo-basic-demo-forked-nptio?file=/src/index.js

**Comment by taniarascia** [comment]
It's a pretty complex workaround to use the proposed sandbox in order to get the legend to match the chart. I also notice the colors are reversed on the horizontal bar chart.

For example, if I do:

```
colors=['red', 'blue', 'yellow']
```

My horizontal bar chart will be "yellow, blue, red", from top to bottom, but the legend will be "red, blue, yellow", so there is some fundamental mismatch going on. By default the legend and chart do not match.

**Comment by wyze** [comment]
> Any update on this issue? I'm holding off upgrading to the latest version of nivo due to this order issue. Would switch to a funnel if it supported legends

@onionhammer It will be fixed in the next release. I have updated the logic in the typescript migration PR. Here is your sandbox using that code: https://codesandbox.io/s/nivo-basic-demo-forked-30vct?file=/src/index.js

**Comment by onionhammer** [comment]
@wyze Awesome, that looks great!
