### ISSUE TITLE
Bar keys need to be identical

### ISSUE THREAD

**Issue by mnifakram** [plouc/nivo#1289]
**Describe/explain the bug**
Bars will not render unless keys are identical across all data members.

**To Reproduce**
https://codesandbox.io/s/nivo-basic-demo-forked-445rf?file=/src/index.js

Steps to fix the behavior:
1. change "donut" to "kebab" on US
2. remove "donut" from keys array
4. Voila, now it does render

**Expected behavior**
Chart should render whether or not the keys are identical, there's too many real use cases (a country where donuts are prohibited 🤣). Also I don't think that the answer will be to normalize the data by setting that missing key to 0, Sometime you want to select top 3 menu by country(so we need to trim the data).

Thanks

**Comment by wyze** [comment]
Correct, I broke this recently, I will get a fix out shortly.
