### ISSUE TITLE
Treemap Custom Tooltip question

### ISSUE THREAD

**Issue by samyoungnyc** [plouc/nivo#1296]
Hi - I am considering switching from Recharts to Nivo, and am trying to understand how to add custom values to a tooltip for a Treemap.

My current tooltip accepts a number of key-value pairs:

<img width="189" alt="Screen Shot 2020-11-17 at 2 51 20 PM" src="https://user-images.githubusercontent.com/4691011/99440306-5e056b00-28e4-11eb-9002-d8c050576cd1.png">

It appears from the Storybook in the documentation that the following code is pertinent to achieving this:

```
<TreeMap
        {...commonProperties}
       // node appears to be where the data for a tooltip is derived from
        tooltip={({ node }) => (
            <strong style={{ color: node.color }}>
                {node.pathComponents.join(' / ')}: {node.formattedValue}
            </strong>
        )}
...
```

As sample data, I've set up the following: 

```
{
        id: 'GME',
        color: 'hsl(154, 70%, 50%)',
        loc: 121.11,
        quantity: 11
}
```

It seems that `id`, `loc`, and `color` are recognized by the `node` - however any additional key-value pairs are not (like `quantity` in the example).

I tried looking at documentation for the `node` from the link listed on the Treemap component documentation, but it gives a 404 error [link](https://github.com/plouc/nivo/blob/master/src/components/charts/treemap/TreeMapNode.js)

This is a great library, hoping I can be pointed in the right direction so I can use it!

**Comment by wyze** [comment]
Hi! It should be available on `node.data` property. See here, if you mouse over `nivo`: https://codesandbox.io/s/sad-buck-7bhk7

**Comment by samyoungnyc** [comment]
> Hi! It should be available on `node.data` property. See here, if you mouse over `nivo`: https://codesandbox.io/s/sad-buck-7bhk7

Thank you - this clarified!
