### ISSUE TITLE
Color Customization

### ISSUE THREAD

**Issue by samyoungnyc** [plouc/nivo#1298]
I am building a Treemap and I want to replicate the UI seen here:

<img width="421" alt="Screen Shot 2020-11-18 at 10 07 26 AM" src="https://user-images.githubusercontent.com/4691011/99547724-de2fdd00-2985-11eb-9e0f-e0320e5ba7e2.png">

My `value` is an integer, and I would like to assign a color to a square on the Treemap, based on the integer (i.e `if (value > 5) { return 'darkGreenHex' }` )

Is it possible to do without adding a `color: #xxxxxxx` value to my nodes?

Thanks for any pointers in the right direction.

**Comment by sfiorotti** [comment]
Hi @samyoungnyc,
In the colors property, you can pass a function and take the id of the item and return the hexadecimal of the color

`colors: props => yourFunction(props.id)`

**Comment by samyoungnyc** [comment]
Thank you for this advice - however I'm a bit confused about adding `colors: props => yourFunction(props.id)` to the `Treemap` because the `data` I'm providing has multiple children. Thus, adding something like 

`colors: data => yourFunction(data.id)` 

doesn't work because the `id` needs to correspond to the singular child - typically would do this in a `.map(d => ...)` but in this case I can't use .map for just one `Treemap` component. 

Am I thinking of this incorrectly?

**Comment by samyoungnyc** [comment]
To further illustrate the issue I have the following:

```
<ResponsiveTreeMap
                  data={data}
                  identity="value"
                  value="value"
                  labelSkipSize={12}
                  labelTextColor={{ from: 'color', modifiers: [['darker', 1.2]] }}
                  parentLabelTextColor={{ from: 'color', modifiers: [['darker', 2]] }}
                  borderColor={{ from: 'color', modifiers: [['darker', 0.1]] }}
                  // colors={{ scheme: 'blues' }}
                  onClick={({ node }) => setColor(node)}
                  tooltip={({ node }) => <Tooltip node={node} />}
                />
```

In this case, the individual `node` has the data I need that would enable me to return a color however, if I click on one of the individual TreeMapNodes, the `console.log` returns `undefined`.

This is confusing me, because the `<Tooltip />` correctly contains and renders the data within `node`

**Comment by samyoungnyc** [comment]
I'm not sure if this is the 'proper' way to do it, but I got it working by adding the following as the `colors` prop:

```
colors={function (e) {
     return setColor(e.data.yourValueHere);
}}
```
ESLint is angry about `JSX props should not use functionseslintreact/jsx-no-bind` but it works nicely.
