### ISSUE TITLE
How to draw continuous lines with incomplete or unwanted data

### ISSUE THREAD

**Issue by daho-turner** [plouc/nivo#1299]
**Is your feature request related to a problem? Please describe.**
I have a set of a data for a period of a month.  However the data is only collected during weekdays.  I'd like to plot the data and omit the weekend gaps so the data appears continuous

**Describe the solution you'd like**
Perhaps something similar to some d3 modules that help with this.
see: discontinuitySkipWeekends
https://www.npmjs.com/package/@d3fc/d3fc-discontinuous-scale 

**Describe alternatives you've considered**
Perhaps this is already implemented and in that case can you help point me in the right direction?

**Comment by wyze** [comment]
Will this story work for you? https://nivo.rocks/storybook/?path=/story/line--holes-in-data

**Comment by daho-turner** [comment]
> Will this story work for you? https://nivo.rocks/storybook/?path=/story/line--holes-in-data

@wyze 
Not a bad option though I'm hoping to connect the gaps so it's one continuous line.
