### ISSUE TITLE
Documentation on how animate when you click roll the dice on bubble chart

### ISSUE THREAD

**Issue by BhavyaLight** [plouc/nivo#130]
When the data changes in my Bubble chart it kind if morphs in and out, however on nivo website on clicking  roll the dice, it animates like a shuffling dice. I would like to find out if there is any documentation to achieve that behaviour.

**Comment by plouc** [comment]
@BhavyaLight it depends on data consistency, on website, I juste shuffle the values of each node, but I do not change nodes nesting/ids…
You can have a look at the function I use to generate the data => https://github.com/plouc/nivo/blob/master/packages/nivo-generators/src/index.js#L214
