### ISSUE TITLE
Treemap Labels

### ISSUE THREAD

**Issue by samyoungnyc** [plouc/nivo#1300]
From the documentation I can see that it's possible to change the `parentLabelSize`, but no such prop/option for `label` - is it possible to style the label text within a given node (size, color, font)?

**Comment by wyze** [comment]
You might have to pass a custom `nodeComponent` prop to replicate this: https://github.com/plouc/nivo/blob/master/packages/treemap/src/TreeMapNode.js

You can also do custom `colors` function to determine color per node. The size I think would require the custom node component. Font you should be able to control by the `theme`, `theme={{ labels: { text: 
 { fontSize: 20 } } }}`

**Comment by samyoungnyc** [comment]
Thanks - this worked!
