### ISSUE TITLE
Area bump styles not updating - trapped in React.memo

### ISSUE THREAD

**Issue by LFDM** [plouc/nivo#1301]
### Observed problem

- Go to https://nivo.rocks/area-bump/
- Try to hover over an area. You will see that the legend labels change their style, but the areas themselves do not.
- When you click one of the areas, you see active and inactive styles. (as outlined below, this is a red herring)
- Once clicked, you can never go back to a state, where no area is selected

### Expected behavior

- According to https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/hooks.js#L179 hovering over an area should trigger active/inactive styles. Clicking is unrelated to these style changes.

### What's going on

- This is in essence a memoization issue.
- `onMouseEnter` the current series is set

https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/hooks.js#L191
```javascript
    const handleMouseEnter = useCallback(
        event => {
            showTooltipFromEvent(React.createElement(tooltip, { serie }), event)
            setCurrent(serie.id)
            onMouseEnter && onMouseEnter(serie, event)
        },
        [serie, onMouseEnter, showTooltipFromEvent, setCurrent]
    )
```
- The current series is used to compute new styles

https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/hooks.js#L145
```javascript
    const getSerieStyle = useSerieStyle({
        fillOpacity,
        activeFillOpacity,
        inactiveFillOpacity,
        borderWidth,
        activeBorderWidth,
        inactiveBorderWidth,
        borderColor,
        borderOpacity,
        activeBorderOpacity,
        inactiveBorderOpacity,
        isInteractive,
        current,
    })

    const series = useMemo(
        () =>
            rawSeries.map(serie => {
                serie.color = getColor(serie)
                serie.style = getSerieStyle(serie)

                return serie
            }),
        [rawSeries, getColor, getSerieStyle]
    )
```

- This is where the problem begins. Specifically here (comments added by me)

https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/hooks.js#L160
```javascript
    const series = useMemo(
        () =>
            rawSeries.map(serie => {
                serie.color = getColor(serie) // mutated in place!
                serie.style = getSerieStyle(serie) // mutated in place!
                
                // 
                return serie // returns the same referentially equal object, even if color or styles have changed
            }),
        [rawSeries, getColor, getSerieStyle]
    )
```
- The `serie` object is later consumed by `Area` (https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/Area.js#L15)
- Area is memoized (`export default memo(Area)`) and therefore compares through shallow equality whether is has to re-render - as the `serie` object never changes as it's only mutated, changes to its style will not trigger a re-render of the component.
- (the initially mentioned click behavior is explained by this as well: in the demo on the website, a click trigger another unrelated state update, which causes the component to re-render. As soon as it re-renders it sees the new styles.)

### Suggested solutions

- Return a new series object

```javascript
    const series = useMemo(
        () =>
            rawSeries.map(serie => {
                serie.color = getColor(serie)
                serie.style = getSerieStyle(serie)

                return { ...serie }
            }),
        [rawSeries, getColor, getSerieStyle]
    )
```
Immediately fixes the problem, but probably breaks all optimizations through `memo(Area)`. I didn't check this out closely. Is this `useMemo` only triggered at the right time or is one of its dependencies (especially getColor and getSerieStyle) unstable?
This would also be the cleanest fix - not changing the `serie` object when `style` changes is a breach of the contract `memo` expects.
One could also see that `const nextStyle = getSerieStyle(style); shallowEqual(serie.style, nextStyle ? serie : { ...serie, style: nextStyle }`, checking specifically whether styles in fact changed. This would be the technically most correct solution imo.

Mind that this problem also exists in the the normal `Bump` component (and potentially elsewhere in the library). It's a lurking bug there - it doesn't surface when hovering at the moment, as something else is causing a state update when you hover

- Workaround: Pass `currentSerie` to `Area` in https://github.com/plouc/nivo/blob/master/packages/bump/src/area-bump/AreaBump.js#L119

`Area` doesn't need the `currentSerie` - but by passing it in, the `memo` check will let a re-render happen whenever `currentSerie` changes.
Also immediately fixes the problem, but it's a hacky solution, which might lead to more problems in the future.

**Comment by wyze** [comment]
Thanks for the detailed issue! Looks like the color functions are stable and should probably be returning a new series object in `map` like your solution. If you want to put up a PR we can check it out!
