### ISSUE TITLE
Types issues after upgrading to 0.65.1

### ISSUE THREAD

**Issue by iamchathu** [plouc/nivo#1302]
**Describe/explain the bug**
Global types are not included to theme props as acceptable props.

**To Reproduce**
https://codesandbox.io/s/serverless-cookies-7zsw9?file=/src/App.tsx

**Expected behavior**
Compile Typescript without issues.

**Additional context**
Seems theme types missing global types.

**Comment by wyze** [comment]
This was fixed by #1292, it just hasn't been released yet.
