### ISSUE TITLE
JS error `TypeError: p is not a function` in production mode

### ISSUE THREAD

**Issue by plxel** [plouc/nivo#1306]
**Describe/explain the bug**
JS error `TypeError: p is not a function` in production mode when rendering Line chart

**To Reproduce**
I've used [time-scale line story](https://nivo.rocks/storybook/?path=/story/line--time-scale)
Pasted it to my app. Everything works fine in dev mode. After building for production I got an error:
![image](https://user-images.githubusercontent.com/1496959/100222427-1c4f7280-2f2b-11eb-9e07-af77a2fcd631.png)

Chart is rendered, but when data changes we see incorrect chart:
![image](https://user-images.githubusercontent.com/1496959/100222682-836d2700-2f2b-11eb-8f1f-b7eb427e50fa.png)
Axis and lines are mixed up. Data is correct and in dev mode is fine. This is only in prod mode. We use webpack 5 

**Expected behavior**
No js error occured after first render in prod mode

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 
 - Version 86

**Comment by wyze** [comment]
Do you use a framework like Create React App or NextJS? Do you do server side rendering? If you downgrade to 0.64 does the error still happen?

I'm curious if it is related to react-spring like in #1290.

**Comment by plouc** [comment]
Closing in favor of #1290

**Comment by plxel** [comment]
@wyze no, no create-react-app, no nextjs..

**Comment by plouc** [comment]
This error is the same as this the one mentioned in #1290  (`r.advance` in the stack trace), it might de-end on your build config, you can apply the temporary fix until they release a fix.
