### ISSUE TITLE
Compilation error without an explicit dependency on @nivo/core

### ISSUE THREAD

**Issue by benrhere** [plouc/nivo#1309]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**
According to the readme: "In order to use nivo, you just have to pick the scoped @nivo packages according to the charts you wish to use."

This used to be true. But starting recently (not sure of the exact version), I have had to take an explicit dependency on     "@nivo/core" in my package.json. If I do not, this package does not get installed and then when I run webpack I get:

```
ERROR in ./node_modules/@nivo/annotations/dist/nivo-annotations.es.js 6:0-149
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\annotations\dist'

ERROR in ./node_modules/@nivo/axes/dist/nivo-axes.es.js 3:0-74
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\axes\dist'

ERROR in ./node_modules/@nivo/bar/dist/nivo-bar.es.js 3:0-234
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\bar\dist'

ERROR in ./node_modules/@nivo/legends/dist/nivo-legends.es.js 3:0-38
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\legends\dist'

ERROR in ./node_modules/@nivo/pie/dist/nivo-pie.es.js 2:0-332
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\pie\dist'

ERROR in ./node_modules/@nivo/tooltip/dist/nivo-tooltip.es.js 3:0-86
Module not found: Error: Can't resolve '@nivo/core' in '[project_folder]\node_modules\@nivo\tooltip\dist'
```

Also interesting: when I point to the latest @nivo/core (0.66.0) I get several of these warnings on npm install:
npm WARN @nivo/bar@0.66.0 requires a peer of @nivo/core@0.65.0 but none is installed. You must install peer dependencies yourself.

**To Reproduce**
- Initialize a new react app with: `npm init react-app ./my-react-app`
- Edit the package.json file, adding `"@nivo/bar": "0.66.0",` to the dependencies
- Run `npm install`
- Open node_modules/@nivo
- Notice that the `core` folder is absent.

**Expected behavior**
A `core` folder should be present, I believe, without an explicit dependency on this package, or the documentation should be updated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: not applicable
 - Version: not applicable

**Additional context**

**Comment by plouc** [comment]
@benrhere, yes, `@nivo/core` is now a required dependency, and you should get warnings about it when installing, it's indicated in the generated code snippets on the website.

**Comment by plouc** [comment]
I also update the README, we overlooked this one, thank you!
