### ISSUE TITLE
Custom tooltip not working in demo

### ISSUE THREAD

**Issue by arifszn** [plouc/nivo#1310]
In [demo](https://nivo.rocks/storybook/?path=/story/pie--formatted-tooltip-values), where the tooltip should display in Russian format, I am not seeing any changes. 

![image](https://user-images.githubusercontent.com/45073703/100548115-d54bdf00-3294-11eb-9461-8c1440d3c935.png)

Also the code uses `tooltipFormat`, but I can not find anything related to it in the pie doc section. My best guess is `tooltipFormat` has been removed in the latest versions.

**Comment by wyze** [comment]
Correct, it should use the `valueFormat` prop now.

**Comment by plouc** [comment]
Fixed in https://github.com/plouc/nivo/pull/1331, `tooltipFormat` has been removed and `valueFormat` should now be used. This is gonna be part of the next release.
