### ISSUE TITLE
Customize @nivo/funnel

### ISSUE THREAD

**Issue by MeloncholyShiro** [plouc/nivo#1311]
How can I adjust the width of each data separately? Rummaged through all the documentation, but did not find links on how to do this.

**Comment by plouc** [comment]
The width of each part is driven by the corresponding data value.

**Comment by MeloncholyShiro** [comment]
@plouc Is it possible to somehow reduce the "compression ratio", or they gave me a curve diagram, but in any case I needed to somehow reduce the "compression ratio", thanks a lot for your answer :)
![изображение](https://user-images.githubusercontent.com/44039577/100583506-d6642700-32fb-11eb-987a-81320bca0060.png)
![изображение](https://user-images.githubusercontent.com/44039577/100583539-debc6200-32fb-11eb-9780-040529d310fa.png)

**Comment by plouc** [comment]
@MeloncholyShiro, I'm not sure to understand, you'd like to get linear lines on the sides, whatever the values are?

**Comment by plouc** [comment]
I'm not completely sure of what you're trying to achieve, but the second chart can be done like this https://codesandbox.io/s/loving-hooks-e8b63?file=/src/App.js.

**Comment by MeloncholyShiro** [comment]
@plouc Yes, it is! Thank you very much :)

**Comment by MeloncholyShiro** [comment]
@plouc Last question, can i replace displayed label (data.value) to (data.label) ? If it posible
