### ISSUE TITLE
Replace data.value to data.label in funnel

### ISSUE THREAD

**Issue by MeloncholyShiro** [plouc/nivo#1312]
Is it possible to replace data.value in funnel with data.label? I don't need to show data in numbers :)
If it's real

**Comment by wyze** [comment]
You can write a custom layer to replace the `layers` label.

**Comment by MeloncholyShiro** [comment]
> You can write a custom layer to replace the `layers` label.

Can I have example how I can do this?

**Comment by wyze** [comment]
Here you go: https://codesandbox.io/s/practical-haibt-6h8nf?file=/src/App.js

**Comment by MeloncholyShiro** [comment]
> 
> 
> Here you go: https://codesandbox.io/s/practical-haibt-6h8nf?file=/src/App.js

Thank you very match!
