### ISSUE TITLE
v0.66.0: npm/yarn package has wrong peerDependencies

### ISSUE THREAD

**Issue by KENNYSOFT** [plouc/nivo#1314]
**Describe/explain the bug**

v0.66.0: npm/yarn package has wrong `peerDependencies`

**To Reproduce**

1. Make an empty directory, and walk into the directory
2. Run command:
    ```shell
    npm install --save react@16.14.0 prop-types@15.7.2 @nivo/core@0.66.0 @nivo/line@0.66.0 @nivo/tooltip@0.66.0
    ```
    or
    ```shell
    yarn add react@16.14.0 prop-types@15.7.2 @nivo/line@0.66.0 @nivo/core@0.66.0 @nivo/tooltip@0.66.0
    ```
3. See warnings about peer dependencies like following:
    > warning " > @nivo/line@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/axes@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/annotations@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/colors@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/voronoi@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/legends@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning "@nivo/line > @nivo/tooltip@0.66.0" has incorrect peer dependency "@nivo/core@0.65.0".
    > warning " > @nivo/core@0.66.0" has unmet peer dependency "@nivo/tooltip@0.63.0".

**Expected behavior**

Not complaining about peer dependencies since it correctly set to 0.66.0 in 1f6cb2c933d1a319f223ea5509f12e17a952addc

**Screenshots**
npm:
![image](https://user-images.githubusercontent.com/6624567/100705169-19042d00-33ea-11eb-9647-b92301089b69.png)

yarn:
![image](https://user-images.githubusercontent.com/6624567/100705051-ebb77f00-33e9-11eb-8300-8ba402faeef2.png)

**Desktop:**
 - OS: Windows
 - Browser: -
 - Version: -

**Additional context**

As 1f6cb2c933d1a319f223ea5509f12e17a952addc, `peerDependencies` are correctly set to v0.66.0. But, if you check the published package, it says something different.

For example: `@nivo/line` package

* npm: https://registry.npmjs.org/@nivo/line/-/line-0.66.0.tgz
* yarn: https://registry.yarnpkg.com/@nivo/line/-/line-0.66.0.tgz#36d8bffcfbde872c54066f845cf3f69980a8c243

When you see package.json file in the package, it ends with following lines:

```json
  "peerDependencies": {
    "@nivo/core": "0.65.0",
    "prop-types": ">= 15.5.10 < 16.0.0",
    "react": ">= 16.8.4 < 18.0.0"
  },
  "publishConfig": {
    "access": "public"
  },
  "gitHead": "1f6cb2c933d1a319f223ea5509f12e17a952addc"
}
```

and it's different from https://github.com/plouc/nivo/commit/1f6cb2c933d1a319f223ea5509f12e17a952addc#diff-8907db74c10b8063551067aff4f70d63a219f7fc6142249ff288556cb05ab2adR45

**Comment by wyze** [comment]
Thanks for reporting, we thought we were bumping them in the correct lifecycle, but we will need to adjust the scripts.

**Comment by KENNYSOFT** [comment]
Oh PR merged, thanks for the fix. Looking forward the next release.

**Comment by KENNYSOFT** [comment]
Just checked https://github.com/plouc/nivo/pull/1317#issuecomment-742517603. Thanks for the fix!
