### ISSUE TITLE
Custom line chart

### ISSUE THREAD

**Issue by MeloncholyShiro** [plouc/nivo#1316]
Hello, thank you very much for your work, I rummaged through the documentation, but I still don't understand how you can make such an overlay of 2 lines on top of each other. I will be very glad to help.

![изображение](https://user-images.githubusercontent.com/44039577/100864019-752c8700-34a6-11eb-9a73-a0af9e58598d.png)

**Comment by plouc** [comment]
Hello, thank you, you can add `stacked: false` to the `yScale` property, you can try it on the website.
