### ISSUE TITLE
Line charts don't display tooltip

### ISSUE THREAD

**Issue by MeloncholyShiro** [plouc/nivo#1318]
**Describe/explain the bug**

A very interesting story, in any of my browsers the tooltip is not shown, but for some reason it is shown in the sandbox. I have no idea why it works this way. A screen of what it looks like for me, I attached it.

And 1 more think. Div with tooltip just not render.

**To Reproduce**
https://codesandbox.io/s/objective-paper-xlle0?file=/src/App.js

**Screenshots**
![изображение](https://user-images.githubusercontent.com/44039577/100877976-9d25e580-34ba-11eb-8a24-66a7f4b45ebb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Browser: Edge, Firefox
 - Version: Latest

**Additional context**
Package.json
![изображение](https://user-images.githubusercontent.com/44039577/100878102-c777a300-34ba-11eb-870f-3bd560402dbf.png)
Boostraped By Create-React-App

**Comment by plouc** [comment]
I think the issue comes from the different version of the nivo packages, all versions should be aligned, so probably `0.66.0` in your case.
