### ISSUE TITLE
Bullet props `rangeBorderWidth` and `rangeBorderColor` are not exposed

### ISSUE THREAD

**Issue by erheron** [plouc/nivo#1319]
**Bug report**

In `Bullet/ResponsiveBullet` components, `rangeBorderWidth` and `rangeBorderColor` props are given default values and never exposed to the user.
You can search for `rangeBorderWidth` in the `node_modules/@nivo/` and it will only occur in the file `@nivo/bullet/dist/nivo-bullet.cjs.js`

**To Reproduce**
This produces a TS error, and it shouldn't:
`
<ResponsiveBullet
   rangeBorderWidth={0.2}
   rangeBorderColor="green"
/>
`

**Comment by erheron** [comment]
@wyze I've been thinking about it and this seems to be a relatively simple issue. I will try to make a PR to close it. Just saying it to prevent us doing this on two different branches. Please tell if it's OK for me to go on and try

**Comment by wyze** [comment]
Go ahead @erheron.
