### ISSUE TITLE
Enable ticks customisation in the bullet

### ISSUE THREAD

**Issue by erheron** [plouc/nivo#1320]
**Is your feature request related to a problem? Please describe.**

When using a `Bullet/ResponsiveBullet` component, it's impossible to customize ticks on the main axis. For example, when `range=[0,200]` ticks generate automatically as `[0, 20, 40, ..., 200]` (see the picture below)
![image](https://user-images.githubusercontent.com/36896640/100904454-55598b00-34c7-11eb-9a18-e71c25aab4e6.png)

**Describe the solution you'd like**
I would like the ticks to be customisable through for example a `step` parameter, so when defining the data I could write
` const data = [
  { id: 'first element',
    range: [0,200],
    step:   10
  }]
`

**Describe alternatives you've considered**
Another customisation I see might be possible is with providing an array of ticks as in Python's matplotlib. I think this might be not the most optimal one in terms of data usage. In this approach I see it as something like:
` const data = [
  { id: 'first element',
    range: [0,200],
    ticks: [0, 10, 20, ..., 200]
  }]
`

**Comment by panggd-produktive** [comment]
+1. I have similar issue as it will be great to support something like axisBottom { format: <codes go here> }

**Comment by assadtony** [comment]
+1

**Comment by erheron** [comment]
@plouc can we re-open this? We had a few "+1"'s here

**Comment by khen-kovrr** [comment]
bump

**Comment by abhaiya26** [comment]
+1

**Comment by mgreenw** [comment]
+1

**Comment by ppfm** [comment]
+1
