### ISSUE TITLE
Import error when using Stream

### ISSUE THREAD

**Issue by mvdobrinin** [plouc/nivo#1324]
Trying to use ResponsiveSankey 0.66 and it leads to import errors. Maybe this is due to the typescript conversions?

> 
> Failed to compile
> ./node_modules/@nivo/core/dist/nivo-core.es.js
> Attempted import error: 'Tooltip' is not exported from '@nivo/tooltip'.

```
  "dependencies": {
    ...
    "@nivo/core": "^0.65.0",
    "@nivo/sankey": "^0.61.2",
    "@nivo/stream": "^0.66.0",
    "@nivo/tooltip": "^0.63.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@webcomponents/webcomponentsjs": "^2.4.3",
    "moment": "^2.27.0",
    "node-sass": "^4.14.1",
    "prop-types": "^15.7.2",
    "query-string": "^6.13.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-json-view": "^1.19.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.4",
    "vendor-copy": "^2.0.0"
  },
```

I tried to replicate the issue [in a code sandbox](https://codesandbox.io/s/nivostream-ticks-demo-forked-0sxuk?file=/src/index.js) but I am actually seeing a different issue there.

> TypeError
> (0 , $csb__react.memo) is not a function

**Comment by plouc** [comment]
@mvdobrinin, nivo versions have to be aligned as they share some common components, so in your case, all `@nivo/*` packages should be `^0.66.0`.

**Comment by mvdobrinin** [comment]
@plouc Thanks, I changed them all to ^0.66.0 and it seems to work.

```
    "@nivo/core": "^0.66.0",
    "@nivo/sankey": "^0.66.0",
    "@nivo/stream": "^0.66.0",
    "@nivo/tooltip": "^0.66.0",
```

There are some confusing warnings because of the way the peer dependencies are defined, but it seems they don't matter.

```
npm WARN @nivo/core@0.66.0 requires a peer of @nivo/tooltip@0.63.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/tooltip@0.66.0 requires a peer of @nivo/core@0.65.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by mvdobrinin** [comment]
@plouc by the way, setting versions the same doesn't work in the sandbox for some reason - https://codesandbox.io/s/nivostream-ticks-demo-forked-0sxuk?file=/src/index.js.

And locally my IDE is still complaining, though it happens to work in React development mode.

![image](https://user-images.githubusercontent.com/1854768/101219502-c0cb6600-3649-11eb-962a-e65b48b63294.png)

Could there still be an issue here somehow?

**Comment by wyze** [comment]
@mvdobrinin The sandbox is on React 16.5.x, and we need 16.8 to support the use of hooks.

**Comment by Syedateeq190** [comment]
It didn't worked, even after changing t

> @plouc Thanks, I changed them all to ^0.66.0 and it seems to work.
> 
> ```
>     "@nivo/core": "^0.66.0",
>     "@nivo/sankey": "^0.66.0",
>     "@nivo/stream": "^0.66.0",
>     "@nivo/tooltip": "^0.66.0",
> ```
> 
> There are some confusing warnings because of the way the peer dependencies are defined, but it seems they don't matter.
> 
> ```
> npm WARN @nivo/core@0.66.0 requires a peer of @nivo/tooltip@0.63.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @nivo/tooltip@0.66.0 requires a peer of @nivo/core@0.65.0 but none is installed. You must install peer dependencies yourself.
> ```

Didn't work for me :(
