### ISSUE TITLE
Zoom in Pie slice onMouseEnter (ResponsivePie)

### ISSUE THREAD

**Issue by Haaziq-Uvais** [plouc/nivo#1326]
**Is your feature request related to a problem? Please describe.**
Hi, first of all, great library! I'm still new to this so I'm not sure if I'm requesting an already existing feature. I've looked in several places but couldn't find a solution for the problem I'm having.

My goal is to slightly zoom in or pop out the slice when I'm either hovering over it or hovering over the relevant legend item. Like this,
![image](https://user-images.githubusercontent.com/18187747/101061708-c88dfa80-35b6-11eb-8607-536f4e5d5643.png)
![image](https://user-images.githubusercontent.com/18187747/101061742-d17ecc00-35b6-11eb-84ee-aa38347edcea.png)

**Describe the solution you'd like**
It'd be great to have an attribute to either increase the size of the slice of the pie onMouseEnter . Even though having the ability to specify the zoom level would be great, for now a fixed slight zoom would do the trick. and it should go back to the normal size onMouseLeave.

**Describe alternatives you've considered**
I'm not sure if I can achieve this via layers. If it is, can you direct me to a tutorial on how I can implement this?

**Comment by plouc** [comment]
It's been implemented in https://github.com/plouc/nivo/pull/1331 and is gonna be part of the next release (no ETA yet, sorry).

**Comment by plouc** [comment]
And it can be animated ;)

**Comment by Haaziq-Uvais** [comment]
That is fantastic!! thank you so much! <3

**Comment by Nikola-Andreev** [comment]
Any news, when will be the next release with this functionality in?

**Comment by Subzidion** [comment]
Is there any example on how to do this?

**Comment by wyze** [comment]
@Nikola-Andreev the functionality is released.

@Subzidion It is enabled by default.
