### ISSUE TITLE
@nivo/network - Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by peterampazzo** [plouc/nivo#1332]
**Describe/explain the bug**

Starting from a new create-react-app, when I use the @nivo/network (used the sample code - https://nivo.rocks/network/), I get this error:

```
Cannot read property 'map' of undefined
```

**To Reproduce**
I created a demo on CodeSandbox: https://codesandbox.io/s/epic-mcnulty-pj067?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 87

**Comment by peterampazzo** [comment]
The data should be passed to the `nodes` and `links` props.

More details here:
https://github.com/plouc/nivo/issues/654#issuecomment-594461157

**Comment by BHARANA4** [comment]
_instead_
 **data={data}** 
_use below_
**nodes={data.nodes}
 links={data.links}**
