### ISSUE TITLE
Flipping heatmap

### ISSUE THREAD

**Issue by abhishekpokhrel** [plouc/nivo#1336]
A user should be able to rotate/flip the axes of heatmap. This should be easily doable within the heatmap functionality. As of now, a user can only invert top axis to bottom axis and vice-versa or left axis to right axis and vice-versa but not the other way around which is flipping top axis to either left or right axis and vice-versa.

**Comment by plouc** [comment]
@abhishekpokhrel, sorry but I'm not sure to understand this, what's the use case? Axes are tied to the cells, so we cannot just use a top (x) axis for a right (y) axis for example.

**Comment by abhishekpokhrel** [comment]
@plouc I meant flipping the heatmap as similar to as we change layout in bullet chart as horizontal or vertical.
