### ISSUE TITLE
Customize Bump yScale

### ISSUE THREAD

**Issue by danilofuchs** [plouc/nivo#1337]
**Is your feature request related to a problem? Please describe.**
I'm building a chart of rankings over time.
This is an annual ranking spanning 7 years. Each year, 20 competitors are chosen by an organisation.
In total, 67 distinct people have won a place in any ranking.

The way I modelled the data was the following: Each person is assigned a serie. If in a specific year this person is not featured in the rankings, I assign `null` to the data point on that year. Otherwise, we position them accordingly.

When plugging this data into `Bump`, it creates a chart with a y axis from 1 to 67, even though only 1 to 20 is populated with information.

**Describe the solution you'd like**
I would like to be able to modify `yScale` to limit axis to go from 1 to 20

**Describe alternatives you've considered**
- I could limit myself into using only 20 series and mixing data from multiple people, but that would severely hinder dynamic interaction and tooltips.
- I could build `Bump` myself based on this code: https://github.com/plouc/nivo/blob/master/packages/bump/src/bump/Bump.js, but that would be a large undertake

**Additional context**
![image](https://user-images.githubusercontent.com/17657014/101705900-c0c2d000-3a66-11eb-81c5-51ebb05c1180.png)

**Comment by danilofuchs** [comment]
@wyze I currently have a deadline on finishing this project, and am able to contribute with Nivo on this issue. I just need some guidance.

What other charts/PRs have similar features?

**Comment by wyze** [comment]
Seems like we might be able to do xScale/yScale like we do for line charts.
