### ISSUE TITLE
Pie color and label not working properly after upgrade

### ISSUE THREAD

**Issue by drxcheng** [plouc/nivo#1339]
After upgrading from 0.62 to 0.67. Our current code is broken.

First, `PieDatum` is no longer exported. Fixed that by using `DefaultRawDatum`.

Then, found out the color and label are not working properly. I was using `colors={{ datum: 'color' }}`.

Color is showing black. Changing to `colors={{ datum: 'data.color' }}` doesn't work either. Workaround is changing to `colors={datum => datum.data.color}`, but I do prefer the old method as it is cleaner.

Labels are showing `id` instead of `label` value. Workaround is changing id to use label value.

The passed data is
```
[
  {
    color: '#1b3558',
    id: "0",
    label: "question 1",
    value: 28,
  },
  {
    color: '#07579e',
    id: "1",
    label: "question 2",
    value: 22,
  }
]
```
I'm following the example. Is there any breaking changes that I am not aware?

I'm on Mac, latest Chrome.

Thank you! Great project!

**Comment by wyze** [comment]
Seems to be working as expected in the sandbox here: https://codesandbox.io/s/heuristic-bird-ovso7?file=/src/App.tsx

**Comment by drxcheng** [comment]
Hi @wyze , thanks for the reply.

The label I was talking about is the tooltip label. Sorry I wasn't clear. In your sandbox, when you move to a part, it is showing "0: 28" or "1: 22".
![Screen Shot 2020-12-11 at 9 40 45 AM](https://user-images.githubusercontent.com/2762773/101936100-f82f9a80-3b94-11eb-846c-fc2bc4e92355.png)

I also put my code into the sandbox (https://codesandbox.io/s/admiring-cookies-637y3?file=/src/App.tsx). The color seems to be fine. However there is still issue on my side. When I use Chrome React component dev tool, I found the color on PieSlice component is `undefined`. I'm attaching some screenshots:

`ResponsivePie` props:
![Screen Shot 2020-12-11 at 9 38 41 AM](https://user-images.githubusercontent.com/2762773/101936000-c9b1bf80-3b94-11eb-8d55-922bebc0dd2c.png)

`PieSlice` props:
![Screen Shot 2020-12-11 at 9 38 56 AM](https://user-images.githubusercontent.com/2762773/101936010-ce767380-3b94-11eb-82ab-8bafe164e6ee.png)

Any idea?

**Comment by wyze** [comment]
I've updated my sandbox above to include a custom tooltip to use the label property instead of the id. As far as why `PieSlice` isn't receiving the `color` prop correctly, I am not sure. When I open both our sandboxes, and inspect them, color is passed to PieSlice correctly.

Is there more props you are passing in your project that could be causing `color` to be undefined?

**Comment by drxcheng** [comment]
Thanks. The tooltip works now, although the color in the tooltip is not right as well. 

I'll dig more into why the color is not working.

**Comment by drxcheng** [comment]
Couldn't figure out. Maybe it's because of some other dependencies. I will try in the future. Thanks for the support! Again, great project!

**Comment by drxcheng** [comment]
just add a note: could it be d3 dependency issue? I upgraded to 6.3.1

**Comment by wyze** [comment]
I'm not sure. Pie only depends on d3-shape, and the latest version is 2.0.0. I upgraded the sandbox to that version and it still worked without issue.

**Comment by lezan** [comment]
I am experience the same issue with Bar component. I am not able to change color according to color included in data.
`colors={{ datum: 'color' }}` is not working anymore, but as suggested by @drxcheng, `colors={{ datum: 'data.color' }}` works. With Scatterplot component I do not have this kind of issue, instead I can use `colors={{ datum: 'color' }}` as before.
If I inspect each BarItem with React Developer Tools I can see each one with `color: undefined`.
I am experience the same issue with `0.66.0` and `0.67.0`.
Is it a bug with Bar or something is changing but Scatterplot is not updated to the lastest API?

Thanks!
