### ISSUE TITLE
Network - error w/ annotations

### ISSUE THREAD

**Issue by outspokeio** [plouc/nivo#1343]
**Describe/explain the bug**
When adding a ResponsiveNetwork (or other Network) component, receiving error "TypeError: Cannot read property 'map' of undefined" at hooks.js - in useComputedAnnotation(). If I remove the Network component, all other nivo components render fine.

![image](https://user-images.githubusercontent.com/42721199/102003852-f0204980-3cbf-11eb-856f-667127bb991e.png)

![image](https://user-images.githubusercontent.com/42721199/102004054-07603680-3cc2-11eb-8dc1-65bdfe26b806.png)

![image](https://user-images.githubusercontent.com/42721199/102004059-147d2580-3cc2-11eb-82f2-6dbda20c94ba.png)

![image](https://user-images.githubusercontent.com/42721199/102004103-91100400-3cc2-11eb-86d1-0812aebe743b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Have tried updating and reverting version types btwn 0.66.0 and 0.67.0 along with peerDependencies, etc. All other charts work in same environment with same patterns.

**Comment by peterampazzo** [comment]
I experienced the same issue (#1332) - you should pass the data to `node` and `links` 😄

**Comment by wyze** [comment]
Duplicate #1332. You should spread `devData`, (`{...devData}`), into the component or pass `nodes` and `links` separately.

We need to update the website do display this properly.

**Comment by outspokeio** [comment]
@peterampazzo @wyze Thank you both. I appreciate the support & apologize for not seeing the duplicate. Really thought I did my diligence but it appears I did not! 

Again - thanks for your time.

- S
