### ISSUE TITLE
Grouped bar chart is not displayed correctly if each 'data' item is 0

### ISSUE THREAD

**Issue by logvy-22** [plouc/nivo#1344]
Thanks for your effort, nivo is really great :)

**Describe/explain the bug**

When I use 'grouped' mode and every data item have 0 as value the warning message's displayed in console and X axis disappears. Reproducible in 0.66.0 version.

Sandbox with the issue:
https://codesandbox.io/s/nivobar-chart-grid-customization-forked-nslvc?file=/src/index.js

**Screenshots**
![image](https://user-images.githubusercontent.com/30704265/102072942-3930e480-3e0b-11eb-9d43-4762a97e74d3.png)

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.198 (Official Build) (x86_64)

**Additional context**
If mode changes to 'stacked' everything looks fine.
This error was not relevant for version 0.61.0.

**Comment by wyze** [comment]
This was fixed with the latest release, v0.71.0. https://codesandbox.io/s/nivobar-chart-grid-customization-forked-yeh0n
