### ISSUE TITLE
Histogram with Continuous X-Axis Values

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [plouc/nivo#1345]
Thank you for this wonderful package!

Is there a way to create a histogram that has a continuous x axis? I want the x-values to start at 0, end at 100, and each bin has size 10 (i.e. 0-10, 10-20, ... 90-100).

Here's a picture of the desired format of the graph:
![image](https://user-images.githubusercontent.com/66634653/102131560-ffb2a600-3e17-11eb-82cc-01bba25002fc.png)

I have played around with it and this is what I get so far:
https://ibb.co/JxNz3rf

My code:
```
const bins = {"10":1, "20":3,"30":2,"40":3,"50":5,"60":8,"70":15,"80":22,"90":19,"100":23}
<ResponsiveBar 
            data={[
                {id:  1, value: bins["10"]},
                {id:  2, value: bins["20"]},
                {id:  3, value: bins["30"]},
                {id:  4, value: bins["40"]},
                {id:  5, value: bins["50"]},
                {id:  6, value: bins["60"]},
                {id:  7, value: bins["70"]},
                {id:  8, value: bins["80"]},
                {id:  9, value: bins["90"]},
                {id: 10, value: bins["100"]}
            ]}
            margin={{ top: 50, right: 130, bottom: 50, left: 60 }}
            padding={0}
            // valueScale={{"type":"linear"}}
            xScale={{
                type: "linear",
                min: 0,
                max: 100
            }}
            yScale={{
                type:"linear",
                max:'auto'
            }}
            colorBy="id"
            axisBottom={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legend: 'country',
                legendPosition: 'middle',
                legendOffset: 32
            }}
            axisLeft={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                tickValues:5
            }}
            enableGridX={true}
            enableGridY={true}
            gridXValues={10}

        />
```

**Comment by alexnault** [comment]
I am wondering the same.

Would [Line chart](https://nivo.rocks/line/) with `enableArea` and a `stepBefore` curve fit your need?

**Comment by Nathaniel-Fernandes** [comment]
I think that would work. 

In the meantime, I used [Data-UI Histogram](https://www.npmjs.com/package/@data-ui/histogram).

**Comment by ShuibCodes** [comment]
> I think that would work.
> 
> In the meantime, I used [Data-UI Histogram](https://www.npmjs.com/package/@data-ui/histogram).

HI, did you manage to find a solution using Nivo?

**Comment by Nathaniel-Fernandes** [comment]
No I didn't. I moved on to a different project so there still could be a way to do it with Nivo but I never found it.
