### ISSUE TITLE
Axis text impose on each other on dynamic data changes

### ISSUE THREAD

**Issue by seneka13** [plouc/nivo#1346]
Hi there!
I have been using Nivo plots with React and faces a problem. Working on development enviroment (localhost) nivo works well, but when I deploy to server rendering changes - Left and bottom axis text impose on each other because of dynamic changes of axis 
 data. The interesting thing is that main data, visualization, changes perfectly.
I wonder if there any changes in code for production.

![image](https://user-images.githubusercontent.com/62692646/102190551-63a1a100-3ee2-11eb-9ff8-00145bd8c006.png)
![image](https://user-images.githubusercontent.com/62692646/102190591-6dc39f80-3ee2-11eb-9fac-4e6cd192baab.png)
![image](https://user-images.githubusercontent.com/62692646/102190644-7caa5200-3ee2-11eb-933c-78ecd19316d7.png)

So you see that whenever I filter user my main plot changes, but Y-axis not working properly (The same for X-axis).

**Comment by plouc** [comment]
@seneka13 this is an issue in `react-spring`, please have a look at this issue: https://github.com/plouc/nivo/issues/1290, it also contains suggestions to fix it.
