### ISSUE TITLE
Swarmplot motion properties no longer working

### ISSUE THREAD

**Issue by janvarsa** [plouc/nivo#1348]
The swarmplot properties animate, motionStiffness, and motionDamping seem to have no effect, although they are still mentioned in the documentation at https://nivo.rocks/swarmplot/

Will these properties be unavailable until react-spring is implemented, and is there a way to disable animation in the meantime?

**Comment by plouc** [comment]
@janvarsa, they should work, that's definitely a bug 🐛

**Comment by wyze** [comment]
This issue has been resolved in the latest release. The package was converted to TypeScript and changed to use `react-spring`. The website documentation has been updated as well.
