### ISSUE TITLE
New Feature - Network Chart - onClick functionality

### ISSUE THREAD

**Issue by outspokeio** [plouc/nivo#1351]
**Is your feature request related to a problem? Please describe.**
A large client loves our Network visualization and wants to use it as a central piece of their UX - to make it truly impactful/useful they're requesting functionality that can only be performed with onClick (or, less so, a stationary/persistent tooltip). This is only a problem for us in that if we don't have it we may have to look for another visualization package or go custom d3 - we'd prefer to stick with Nivo and are willing to donate to get this functionality.

**Describe the solution you'd like**
We would like onClick interactive functionality added to NetworkChart (Responsive / SVG) - such that we can capture the series data (in this case, in nodes data) and display it in a persistent layout (does not disappear onMouseOut).

**Describe alternatives you've considered**
We've tried providing the "deeper interactive" related data in a list next to the chart but this in essence requires duplication of effort - the user can see the information in the tooltip and then has to go find the record in the list in order to interact with that information.

**Additional context**
I see this offered in other charts so I'm hoping it's possible to achieve here. While we are a startup and are on a skeleton budget we see this as having the potential to move the needle on an account that could close our round of funding... so we're willing to lay out some donation if it makes a difference in getting this added. Thank you!

**Comment by zbyju** [comment]
This would indeed be very useful!
