### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined (Treemap custom color)

### ISSUE THREAD

**Issue by samyoungnyc** [plouc/nivo#1356]
I am having trouble providing custom dynamic colors for the `<ResponsiveTreemap />` to render each item within. I am using the data that I fetch, and checking a specific value, then running a function and returning the proper RGBA code for the value to the `colors` prop of the Treemap. I was providing a HEX value before, however that seemed to trigger this very bug. What is strange is that this was working for weeks, with no changes, and is now triggering the bug again. 

**Describe/explain the bug**
The error message: 

`TypeError: Cannot read property 'replace' of undefined`

The stack trace:

```
 1849 | const createStringInterpolator = config => {
  1850 |   // Replace colors with rgba
> 1851 |   const outputRange = config.output.map(rangeValue => rangeValue.replace(colorRegex, colorToRgba)).map(rangeValue => rangeValue.replace(colorNamesRegex, colorToRgba));
  1852 |   const outputRanges = outputRange[0].match(stringShapeRegex).map(() => []);
  1853 |   outputRange.forEach(value => {
  1854 |     value.match(stringShapeRegex).forEach((number, i) => outputRanges[i].push(+number));
```

Furthermore: 

`index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

**To Reproduce**
I created a codesandbox with all my pertinent code and it works fine, however the data (`currentPositions`) is local, whereas in my app the data is coming from an API call, executed with `async/await`. I think that perhaps, this is a matter of data synchronization. What doesn't make sense is that I added a ternary to check that the data is present before the `ResponsiveTreeMap` is rendered. At this point, I am confused whether this is a problem with Nivo or the `async/await` being called in a `useEffect` hook. It may be the hook call, however this was working for weeks, and I have the ternary check, so I am just confused. I am making async calls all over with no issues.

**Desktop (please complete the following information):**
 - Mac OS Catalina 10.15.4
 - All major browsers

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0
 - Browser: All major browsers

**Comment by wyze** [comment]
Can you show the component with your data fetching and conditional render of treemap?

**Comment by samyoungnyc** [comment]
> Can you show the component with your data fetching and conditional render of treemap?

After looking into this some more I think it has to be a problem with the async/await calls - there's a bit of complex logic there - I'm going to close the issue because it's probably less a bug on Nivo's end than my own. It comes more as a surprised because it was working for weeks but it's clear I need to refactor.
