### ISSUE TITLE
Custom ToolTip goes off screen

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [plouc/nivo#1358]
Thank you for this great package!

My problem is that my tooltip is always directly above the cursor and goes off the screen when on the very left and right of the chart. I read in #631 that this issue was fixed (the tooltip would go to the left or right of the cursor) for versions 0.60+; however, I don't see that change.

I am probably missing something simple. Could you please point me in the right direction?

Here's a picture:
https://ibb.co/k4xCmMY

Here's my code:
```
const CustomTooltip = ({id, value, data}) => {
    // console.log(nameLookUp)
    return (
        <div style={{width: '300px',maxHeight:'200px'}}>
            <strong>ECO:</strong> {data.eco} <br />
            <strong>Name:</strong>
                {data.name[0]}
            <br />
            <strong>Won:</strong> {data.Won || 0}   <br />
            <strong>Lost:</strong> {data.Lost || 0}
        </div>
        
    )
}

           <Bar
                data={data}
                width={width}
                height={height}
                keys={[ 'Won', 'Lost']}
                indexBy="eco"
                margin={{ top: 50, right: (width > 600) ? 130 : 80, bottom: 50, left: 60 }}
                padding={0.3}
                valueScale={{ type: 'linear' }}
                indexScale={{ type: 'band', round: true }}
                colors={{ scheme: 'nivo' }}
                axisBottom={{
                    tickSize: 5,
                    // tickPadding: 5,
                    tickRotation: -30,
                    legend: 'Openings',
                    legendPosition: 'middle',
                    legendOffset: 40
                }}
                enableGridX
                axisLeft={{
                    tickValues:[...Array(max + 1).keys()],
                    legend: 'Count',
                    legendPosition: 'middle',
                    legendOffset: -30
                }}
                labelSkipHeight={12}
                labelTextColor={{ from: '#000000', modifiers: [ [ 'darker', 1.6 ] ] }}
                tooltip={CustomTooltip}
                legends={[
                    {
                        dataFrom: 'keys',
                        anchor: 'bottom-right',
                        direction: 'column',
                        justify: false,
                        translateX: 120,
                        translateY: 0,
                        itemsSpacing: 2,
                        itemWidth: 100,
                        itemHeight: 20,
                        itemDirection: 'left-to-right',
                        itemOpacity: 0.85,
                        symbolSize: 20,
                        effects: [
                            {
                                on: 'hover',
                                style: {
                                    itemOpacity: 1
                                }
                            }
                        ]
                    }
                ]}
                animate={false}
            />
```

**Comment by 8annoy** [comment]
Joining the praise, as well as the request.
I'm still seeing this at 0.67, would love to have this issue resolved soon :)

**Comment by ugrupp** [comment]
As far as I've understood and gathered from the source, the fix from #631 only kicks in when the tooltip anchor is initially positioned `"left"` or `"right"`:

https://github.com/plouc/nivo/blob/ce7c755b23cfc55ead9bac9920a55ef6e764bd99/packages/tooltip/src/hooks.ts#L32-L35

Unfortunately, the default anchor position is "top" and most components don't let you set your own position. So the fix would work (see the Sankey component for example), but unfortunately it's not really accessible in many cases.

In my case (Pie Chart), I narrowed this down to not having the option to pass the anchor position to tooltips generated on the Arcs component: https://github.com/plouc/nivo/blob/ce7c755b23cfc55ead9bac9920a55ef6e764bd99/packages/pie/src/Arcs.tsx#L51

Not sure how to solve/work around this yet..

**Comment by ugrupp** [comment]
bump

**Comment by luizjr92** [comment]
I was able to change the anchor by wrapping my custom component in a `TooltipWrapper`. Even though the position is set to `[0, 0]`, the tooltips do show at the right place. This does not solve this issue but might alleviate some of the pain.
```tsx
import { TooltipWrapper } from '@nivo/tooltip';

const CustomTooltip = (props?) => (
  <TooltipWrapper anchor="left" position={[0, 0]}>
    {/// your custom JSX here}
  </TooltipWrapper>
);
```

**Comment by DoubleEskimo** [comment]
bump

**Comment by siosio34** [comment]
bump

**Comment by svn1991** [comment]
bump

**Comment by mykhaliuk** [comment]
make this happen

**Comment by Elenalalala** [comment]
bump

**Comment by PrinceLoren** [comment]
bump

**Comment by scio-cypher** [comment]
bump

**Comment by zhikin2207** [comment]
bump

**Comment by Ziker22** [comment]
My answer in other thread might help someone https://github.com/plouc/nivo/issues/2403#issuecomment-2967019491

**Comment by Stijnboss12** [comment]
bump
