### ISSUE TITLE
Grid and axis in time series line charts doesn't appear on webpack production mode

### ISSUE THREAD

**Issue by alditiadika** [plouc/nivo#1361]
github repository: [https://github.com/alditiadika/power-meter-client](url)

**Describe/explain the bug**
I am using the @nivo/line version `0.67.0`,  brotli-webpack-plugin, and time series data on a scale of 30 to 50 seconds. In development mode everything is fine, but in production mode, the axis and grid on the line chart does'nt appear. I've tried downgrading @nivo/line to version `0.60.0` and still get the same thing.

![Screenshot from 2020-12-22 18-24-10](https://user-images.githubusercontent.com/18097853/102883651-f0b89d00-4482-11eb-8c2e-2b344e7811c6.png)

But when I switch routes, and a few moments later I return to the previous route, the axis and grid appear as in development mode.

![Screenshot from 2020-12-22 18-27-20](https://user-images.githubusercontent.com/18097853/102883937-5c026f00-4483-11eb-91a4-5e98f3616c8d.png).

and when my browser reloads, the axes and grids doesn't appear again.

**Additional**
There is an error:
`Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null"` and 
`TypeError: r.willAdvance is not a function` in the console which I think may be related to this.

**Browser**
Chrome

Thanks.

**Comment by Kichiyaki** [comment]
It's a problem with react-spring (https://github.com/pmndrs/react-spring/issues/1078). A temporary workaround is to downgrade @nivo/line and @nivo/core to version ``<=0.64.0``.

**Comment by alditiadika** [comment]
Thanks so much

**Comment by psyzz** [comment]
downgrading to 0.64.0 i still have this error : 
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null"

But the grid works now

**Comment by abbasegbeyemi** [comment]
Facing the same issue now. Did you find a fix?

**Comment by akigugale** [comment]
Same here @abbasegbeyemi

**Comment by wyze** [comment]
If you're experiencing the same issue. Please post a link to a repo or codesandbox that has the issue and I can take a look.

**Comment by adriangitvitz** [comment]
Did anyone found a solution related to this issue? I am using nivo 0.80.0, but still getting the same error

`Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null"`

My data is not empty or with null or negative values, I have tried downgrading, but still the same issue

Iam also using xScale as time

``
            xScale={{
                type: "time",
                format: "%m/%d/%Y",
                useUTC: false,
                precision: 'day'
            }}
``

**Comment by adriangitvitz** [comment]
I have found that if I set stacked option to false it solves the issue
