### ISSUE TITLE
chart legend in external container.

### ISSUE THREAD

**Issue by ashokkumarsand** [plouc/nivo#1362]
Currently, there is no way to put chart legends in any external container outside of the chart. 
Please provide support for external legends.

**Comment by plouc** [comment]
Hi, there's no plan to support such a feature, it would involve portals, forward refs and would be really difficult to implement for canvas.
Currently, you can build legends manually in plain HTML outside of the chart, which might even be preferable in situations where you want to have more control over styling/layout.

**Comment by ashokkumarsand** [comment]
ok, no issue but it is possible to provide a callback function when chart is updated with the chart/series object?
