### ISSUE TITLE
Allow to render custom symbol inside the legend

### ISSUE THREAD

**Issue by oleh-hutsalo-ks** [plouc/nivo#1366]
**Is your feature request related to a problem? Please describe.**
There is a `pointSymbol` prop on the Line component, but there is no way to pass the custom symbol into the Legend of the chart. 

**Describe the solution you'd like**
Add prop `symbolComponent` to the `LegendProps` with the same props as `pointSymbol` in the Line chart

**Describe alternatives you've considered**
The current alternative is to develop custom legend with custom symbols.

**Additional context**
I am making my charts more accessible by adding different shapes of the point for each line in the chart. But symbols in legends are not customizable.
![image](https://user-images.githubusercontent.com/67273539/103282696-3f17ef80-49df-11eb-96e3-90e422cda04f.png)

**Comment by oleh-hutsalo-ks** [comment]
I didn't realize that `legends[].symbolShape` can accept function. That solves my issue

**Comment by sebsouza** [comment]
Hi! I'd like to know if you could explain me how to render a different symbol point shape for each data series. Thanks in advance!

**Comment by wyze** [comment]
@sebsouza Something like this: https://codesandbox.io/s/sharp-ganguly-3m0rg?file=/src/App.tsx

**Comment by sebsouza** [comment]
@wyze thanks for your reply! I'd like to render a different symbol point shape for a determinate data series in the line plot besides inside the legend. Is it possible?

**Comment by wyze** [comment]
@sebsouza Okay, my bad, you commented in an issue about legends, so I assumed thats what you want. Here is one using a custom layer to replace the `points` layer. https://codesandbox.io/s/loving-hawking-uqx0g?file=/src/App.tsx

**Comment by sebsouza** [comment]
@wyze thank you very much! That's exactly what I was looking for.
