### ISSUE TITLE
Colors are muted/faded

### ISSUE THREAD

**Issue by ThinkSalat** [plouc/nivo#1374]
When I enter a color to be used in the `colors` prop, the  end results is a faded version of that color

Here's what the colors should look like:
![image](https://user-images.githubusercontent.com/31082405/103688211-55c1c780-4f46-11eb-91d7-77965a62dc1f.png)

and here's what they look like when rendered on the bar chart:

![image](https://user-images.githubusercontent.com/31082405/103688267-6d00b500-4f46-11eb-913a-06a1bd42dfb7.png)

The colors I'm passing in are: `['#6EC2B3', '#D7DDB0']`

The colors that are coming out are: #6dc2b2 and #d6ddb0

Anyone notice this? How do I fix this?

[Here's](https://codesandbox.io/s/nivobar-chart-grid-customization-forked-ht1wc) a code pen so you can see what I mean

**Comment by ThinkSalat** [comment]
Bumping this

**Comment by ThinkSalat** [comment]
bump

**Comment by wyze** [comment]
The provided sandbox didn't use those colors anywhere. I just added them as `colors={['#6EC2B3', '#D7DDB0']}` and inspected the DOM and it used that color straight to the `fill` prop of the rect element.

Would you mind providing an updated sandbox that shows this not working?
