### ISSUE TITLE
Line Chart Data Incorrect

### ISSUE THREAD

**Issue by p45mark** [plouc/nivo#1375]
**Describe/explain the bug**
The data points for the line chart are incorrect

**To Reproduce**
You can see the problem in this [codesandbox](https://codesandbox.io/s/async-cache-uwl4g?file=/src/App.js). I just copy/pasted the demo component and data. Notice that for the France, the "boat" value is set to 255 but on the graph the plot point somewhere around 475. 

It looks like all values for Japan (the first object in the data array) are correct but the more countries you add, the farther off their plot points on the graph. The last country in the array is Norway, and it's value for "moto" is 216 but the graph is showing somewhere around 1,100.

[Codesandbox](https://codesandbox.io/s/async-cache-uwl4g?file=/src/App.js)

**Screenshots**
![image](https://user-images.githubusercontent.com/48729903/103711888-3e4a0500-4f6d-11eb-95a5-b59a04f0cc99.png)

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser: Chrome
 - Version 87.0.4280.88

Let me know if you need any additional info
Thanks!

**Comment by plouc** [comment]
@p45mark, by default, the values are stacked, so this is the sum of all values, you can change the `yScale.stacked` property to `false` to disable this behaviour.

**Comment by p45mark** [comment]
Thanks for the clarification. I have to ask though... in general, is that the normal, expected behavior for a line graph? I don't use them often, but it seems really odd that if the point should be at 255, that depending on how many other countries are in the data beforehand, the point could be at 1,100.

**Comment by p45mark** [comment]
Never mind. Unstacked looks like spaghetti when you have a lot of lines. I can see now why stacking them is a better option. Thanks again
