### ISSUE TITLE
Mixed type chart

### ISSUE THREAD

**Issue by LuizMaestri** [plouc/nivo#1376]
I need a chart that mixed bar and lines to presents daily and monthly profit.
something like [this](https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/) .
I searched on docs but haven't anything like that.

**Comment by jamesdh** [comment]
The docs provide details for both bar and line charts, as well as how to mix them via custom layers. See https://nivo.rocks/storybook/?path=/story/line--custom-layers for an example. Look around the Storybook for numerous more examples. It took me all of about 30 seconds to find that.

**Comment by wyze** [comment]
Thanks James for the helpful answer!
