### ISSUE TITLE
markers are not taken into account for maxValue="auto" prop

### ISSUE THREAD

**Issue by Victorien-T** [plouc/nivo#1385]
**Describe/explain the bug**
When markers are defined, if some marker value is higher than the highest data value, it will not appear on the chart.

**To Reproduce**
See https://codesandbox.io/s/nivobar-markers-and-maxvalue-7548j?file=/src/index.js

Change value of marker to 4 > you will see it, change it back to 8 > it is not visible.

**Expected behavior**
I think that markers should be taken into account with maxValue at "auto"

**Comment by plouc** [comment]
Yes, for this you should use a max value, the markers don't define it, it should come from the data,

**Comment by Victorien-T** [comment]
Well, I don't know the max value... It would be too easy. 
I don't know if the marker value will be higher than the data highest one and I think that in most of cases when displaying data you don't know the values.
