### ISSUE TITLE
PieTooltip `id` not defaulting to `datum.label`

### ISSUE THREAD

**Issue by with-heart** [plouc/nivo#1387]
**Describe/explain the bug**
The conversion of `PieTooltip` to TypeScript included a breaking change to the tooltip's behavior. In `0.63.0`, the value of `id` was `datum.label || datum.id`, but as part of the conversion, this was changed to `datum.id` only. That change can be seen here: https://github.com/plouc/nivo/commit/9fd5cee1d6fe98fc10d497aaaac167afb44681f1#diff-e5420964f81416602e26bce4d51f7db64a90b61384f64cbe4ff9cfaf6bf74aa1L15-R16

**To Reproduce**

1. Go to https://codesandbox.io/s/nivopie-tooltip-example-0631-qhzoo (`0.63.1`)
2. Hover an item in the pie chart and notice that the tooltip displays the corresponding `label` value
3. Go to https://codesandbox.io/s/nivopie-tooltip-example-0640-kgzss?file=/src/index.tsx (`0.64.0`)
4. Hover an item in the pie chart and notice that the tooltip displays the `id` and ignores the `label` value

**Expected behavior**
`PieTooltip` should utilize the provided `label` for each item so that the tooltip can display a human-readable label (in cases where `id` is not human-readable) and so the tooltip matches the legend.

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1
 - Browser: Chrome 87.0.4280.141
 - Version: 0.64.0

**Additional context**
I'm unsure if this change was intentional or not. I looked through the PR for these changes and searched the issues but couldn't find anything documenting a move away from `label` in this case. If there is a better way to handle this situation, I'm totally fine with doing something else.

**Comment by wyze** [comment]
You can achieve the same functionality by using a custom tooltip. Here is the fork of your sandbox achieving the same functionality: https://codesandbox.io/s/nivopie-tooltip-example-0640-forked-4b9i8?file=/src/index.tsx
