### ISSUE TITLE
ResponsiveBar overlap on the X axis

### ISSUE THREAD

**Issue by GregdTd** [plouc/nivo#1389]
Hello @nivo users,
I have a very curious issue on the responsive bar that I want to show you.
Everything is working as expected locally  as you can see below: 

![image](https://user-images.githubusercontent.com/19348797/104608714-827e8900-5682-11eb-9589-242de445dbdf.png)

But when deploying on [Netlify](https://www.netlify.com/) the bars are overlapping on the X axis: 

![image](https://user-images.githubusercontent.com/19348797/104608845-ae017380-5682-11eb-8915-a9e72a4cf3e5.png)

Is there something I'm missing ? Does anyone of you have an idea of where it might come from ?
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Additional context**
Here are my npm version of the tools I'm using:
```
        "webpack": "^5.4.0",
        "@nivo/bar": "^0.66.0",
        "@nivo/core": "^0.66.0",
        "react": "^17.0.1",
        "typescript": "^4.1.3",
```

Here the component I'm using : 
```

export const BarChart = (props: Props) => {
    const { data, keys, indexBy, legendLeft, colors, labels, markers } = props;

    return (
        <ResponsiveBar
            data={data}
            keys={keys}
            margin={{ top: 50, right: 0, bottom: 50, left: 60 }}
            padding={0.3}
            indexBy={indexBy}
            valueScale={{ type: 'linear' }}
            indexScale={{ type: 'band', round: true }}
            colors={colors}
            label={labels}
            animate={false}
            axisBottom={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legendPosition: 'middle',
                legendOffset: 32
            }}
            axisLeft={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legend: legendLeft,
                legendPosition: 'middle',
                legendOffset: -40
            }}
            labelSkipWidth={12}
            labelSkipHeight={12}
            markers={markers}
        />
    );
};

export default BarChart;

```

**Comment by LucasEduardoRomero** [comment]
Same problem here! It happened with ResponsiveBar and ResponsiveLine.

When we put margin on bottom to show the tickValues and minValue is set, the bar just overflow.

With ResponsiveLine, we can see same effect if enableArea is True, and yScale.min is Set

### Info
* "@nivo/bar": "^0.67.0",
* "@nivo/core": "^0.67.0",
* "@nivo/line": "^0.67.0",
* "@nivo/pie": "^0.67.0",
* "react": "^16.13.1",
* "typescript": "^3.8.3"



[Example Here]( https://codesandbox.io/s/nivobar-minvalue-margin-bug-f8dgt?file=/src/index.js)

**Comment by GregdTd** [comment]
Hello @plouc, following some answer from the discord channel I was wondering if my issue could be solved by https://github.com/plouc/nivo/issues/1290#issuecomment-728630376
It seems to be the same thing but you didn't answer me so I'm wondering ..

**Comment by LucasEduardoRomero** [comment]
Hey @GregdTd I tested the Link above and it did not worked, so I developed a Quick Fix using the renderTick atribute from the axisBottom prop, that is a function called for every axis present on your graph. So the function verifies IF the axis is the first one in the iteration, it paints a white square to overhide the overflow of the bars.

The [Example](https://codesandbox.io/s/nivobar-minvalue-margin-bug-fix-oilyj?file=/src/index.js) is a fork from my previous CodeSandBox Link.
I Basically set the axisBottom Props with the custom function and changed de Layers order, to put the axis in front of the bars.

**Comment by GregdTd** [comment]
I was able to "somehow" fix the issue using the `ResponsiveBarCanvas` component instead of the `ResponsiveBar`.. You lose the label on column but at least it looks like something.. 
In another part of my app I used the Nivo API and it works perfectly so I strongly advise anyone encountering this kind of issue to give it a try !
