### ISSUE TITLE
Composed charts

### ISSUE THREAD

**Issue by ellipticaldoor** [plouc/nivo#139]
Can I compose two different charts into one?

Like for example drawing a line in a bar chart.

![image](https://user-images.githubusercontent.com/3449006/35624991-9ac858bc-0688-11e8-9776-0f6639769547.png)

**Comment by stahlmanDesign** [comment]
I recently asked the same thing and then answer is 'not right now' https://twitter.com/jstahlman/status/939260265618706435

**Comment by plouc** [comment]
I've started something on https://github.com/plouc/nivo/pull/116, but it involves far more work than I expected :/, I'm planning to re-introduce this in a more progressive way.

**Comment by wulucxy** [comment]
@plouc what is the progress now?

**Comment by wulucxy** [comment]
@stahlmanDesign @ellipticaldoor do you guys solve this problem？

**Comment by plouc** [comment]
Unfortunately, there is no proper guides on how to do it, but if you have a look at the code for each component, you could be able to build composed charts. 
Main chart components are build on smaller components, axes, containers, nodes…
I'm also adding *layout* components, which will also help.

**Comment by wulucxy** [comment]
@plouc so where I can find the *layout* Component?

**Comment by plouc** [comment]
I'm adding some, for example https://github.com/plouc/nivo/blob/master/packages/parallel-coordinates/src/ParallelCoordinatesLayout.js.

**Comment by plouc** [comment]
For now, the best you can do is having a look at the components and extract the relevant pieces, not really handy I admit :/

**Comment by plouc** [comment]
I've started to introduce a `layers` property which allows to pass extra layers and also to change the order of elements.

For now, it's supported on [`Bar`](https://github.com/plouc/nivo/blob/master/packages/bar/src/Bar.js) and [`ScatterPlot`](https://github.com/plouc/nivo/blob/master/packages/scatterplot/src/ScatterPlot.js) components. You can find a working example of it [here](https://codesandbox.io/s/kkqmx1rw17) using the `ScatterPlot` component.

If you're willing to contribute on other components, please do not hesitate :)

**Comment by ncknuna** [comment]
Oh, great! I'll try to take a look at adding `layers` to `Line` today, following this commit that added it to `Bar` (https://github.com/plouc/nivo/commit/8a817ec9b632740457546aca65fb3f09c8f9ffa3#diff-5799e61b0b5bfcb7468aee7a5406e61a). If there's a better thing for me to look at, let me know!

**Comment by plouc** [comment]
And now, thanks to @ncknuna we have `layers` support for Line component!

**Comment by pfreedmanJG** [comment]
Ok, [here](https://codesandbox.io/s/91l6kj5wop) is an example I've written that is vaguely similar to what OP wanted.

**Comment by plouc** [comment]
Thank you @pfreedmanJG! I've used it to reproduce what @ellipticaldoor wanted to achieve => https://codesandbox.io/s/m4ro13jjn8

**Comment by pfreedmanJG** [comment]
@plouc That's great, I was wondering how to get circles rendering on top of the points!

**Comment by yojeek** [comment]
@plouc sorry for the slight off-topic, but why your codepen example only works if x value contains series of integers "0", "1", etc. If I change it to anything but integers in breaks inside xScale(index).

**Comment by plouc** [comment]
@yojeek, because the bar chart only supports ordinal values for now, other charts (line, scatterplot) support other types like linear/time/log scales.

**Comment by plouc** [comment]
@yojeek, sorry I don't respond to emails, please use GitHub instead. I had a look at the example, and fixed it => https://codesandbox.io/s/zrk1o3j29p, the problem was the use of `bar.data.index` instead of `bar.data.indexValue`.

**Comment by EduardoAC** [comment]
@plouc are you giving supporting other `@nivo` components as Layers instead of D3?

**Comment by simoami** [comment]
@plouc Would it be best to support an entirely new Composite chart container instead of making Bar chart as the primary container? So it controls the layers and knows what layers to strip off from the inner charts. There might be other benefits.

**Comment by plouc** [comment]
@simoami, some charts supports the same layer ids, but contains different things, but not every chart share the same layers as others. Also nivo provides specific packages for each chart type, and this approach assumes that all chart types are installed.

**Comment by simoami** [comment]
Thanks @plouc. I was just throwing an idea in case it offers a predictable composition. To not be aware of charts, you could have an explicit declaration. `<CompositeChart><Chart1 /><Chart2 /></CompositeChart>`. Then the composite chart can share a layer service that the inner charts can choose to support. Something react contexts can help with.

**Comment by VolodymyrKornetskyi** [comment]
@plouc is it possible to add tooltip to Line chart in such approach?

**Comment by andreas-ateles** [comment]
@plouc same question as above, is there a way to make the tooltips show up for both the bar and line chart?
In my case preferably in a single tooltip box, with all graphed Y values for the current X value.

@VolodymyrKornetskyi did you have any luck solving that?

**Comment by plouc** [comment]
@andreas-ateles you could probably achieve this in your custom layer as you can do what you want, you could for example use the `useTooltip()` hook from `@nivo/tooltip` to display some extra tooltips.

**Comment by sarang12** [comment]
@plouc Is it possible to add a right axis corresponding to the line layer in this type of chart?https://codesandbox.io/s/zrk1o3j29p

**Comment by rosshoyt** [comment]
> @yojeek, because the bar chart only supports ordinal values for now, other charts (line, scatterplot) support other types like linear/time/log scales.

@plouc Scatterplot with `xScale={{ type: 'point', min: 0, max: 'auto' }}` works with custom D3 Line layer as described [above](https://github.com/plouc/nivo/issues/139#issuecomment-444846955)
![working example](https://user-images.githubusercontent.com/43669429/145761949-1118ea5c-d6e7-46cd-8155-f6de81c85e7b.PNG)
However, when changing the Scatterplot type to **_time_**, the xScale function **fails** in the _same_ LineGenerator function used above. 



The changed _ResponsiveScatterPlot_ settings:
```
xScale={{ 
    type: 'time',  
    useUTC: false,
    format: '%m-%d',
    precision: 'day'
}}
xFormat="time:%m-%d"`
axisBottom={{
  format: '%b %d',
  tickValues: 'every 4 days',
  // etc
}}
```
Custom Line layer excerpt:
```
function Line({ data, xScale, yScale}) { 
        const lineGenerator = line().curve(curveNatural)
            .x(d => xScale(d.x))
            .y(d => yScale(d.y));
       // etc
```

_Error produced:_
```
<path> attribute d: Expected number, "MNaN,289CNaN,282.…"
```

The x values are, in both cases, simply M-D date formats, e.g. 4-23

I'm working with Scatterplot version 0.72, and can provide a CodePen if needed.

**Comment by alissaVrk** [comment]
Hi, I made an [example](https://codesandbox.io/s/nivo-composed-bar-with-line-j6qce5?file=/src/index.js) of a combined bar with a line chart.
the bars and the line values have different scales - so there is an axis on the left for the bars and an axis on the right for the line.

I also added a tooltip - I made a combined tooltip for both values, but there are many different possibilities here...
Also if you already have some lib for tooltips in your project (like react-tooltip or floating-ui)  you can use the tooltip lib for the tooltips.

@plouc, thank you for making the code easy enough to navigate :)
I do think that this would have been easier if `useLine`, for example, would have been exposed
