### ISSUE TITLE
Display dates in Stream chart?

### ISSUE THREAD

**Issue by mvdobrinin** [plouc/nivo#1390]
I am using stream chart with time series data. Each data point not only has stream dimensions, but a timestamp. It is is then essentially a stacked line chart. I need some way to telling the user what timestamp he is looking at.

The options I considered are -
1. Display date in the tooltip. I tried adding the timestamp as to the `keys` prop, and the chart tries to put it in the tooltip then but this ends up breaking the chart. I tried using custom tooltip as a hack but AFAIK according to #182 this is not possible.
2. Make the X axis a scale for times to give the user at least a visual reference. Currently stream chart has a very simple scale for X axis. AFAIK according to #470 it cannot be swapped for a timescale.

I think being able to stick it in the tooltip would be great. Is there a way to do that?

**Comment by LuisThuillier** [comment]
+1 same here...bumping
PD: i guess there is no way to use this chart to display dates, i would love to display as a timeline and events count in each tick but looks like there is no way to do it.

**Comment by rap2hpoutre** [comment]
Also: https://github.com/plouc/nivo/issues/470

**Comment by TimWillebrands** [comment]
Bump

**Comment by jdddog** [comment]
Bump

**Comment by Gerald12344** [comment]
Bump

**Comment by ericdebelak** [comment]
Bump

**Comment by BigMrRob** [comment]
I was able to get this working fine utilizing textElements = document.querySelectorAll('text[dominant-baseline="text-before-edge"]') and then mapping over the keys and setting each textElement by index to the desired key

**Comment by BigMrRob** [comment]
` let textElements = document.querySelectorAll(
    'text[dominant-baseline="text-before-edge"]'
  );
  useEffect(() => {
    if (textElements.length) {
      groups.map((group, index) => {
        if (index === groups.length - 1) {
          textElements[index].innerHTML = `Now`;
        } else {
          textElements[index].innerHTML = group;
        }
      });
    }
  }, [textElements]);`
