### ISSUE TITLE
ResponsiveBar crashes if there's no data greater than 0

### ISSUE THREAD

**Issue by IrinaMityayeva** [plouc/nivo#1391]
With basic configuration `data`, `indexBy` and `keys` provided if there's no value by key from `keys` greater than 0 a bulk of errors appear in console:
`Error: <g> attribute transform: Trailing garbage, "….3996944712112, NaN)"`

Expected behavior: no console errors and `indexBy` axis maybe with some message that there's no data

**Comment by monzilnepali** [comment]
Nivo Responsive bar doesn't provide the empty state and this is how graphs are the plot. If want to avoid the error you need to check whether data contain 0 value or not and only render the bar if it not
