### ISSUE TITLE
Ability to disable Stream label hover

### ISSUE THREAD

**Issue by mvdobrinin** [plouc/nivo#1392]
Currently on Stream chart you can disable the tooltip hover popup which shows up when you are near a X axis tick line. 

This can be controlled with the **enableStackTooltip** property.

![image](https://user-images.githubusercontent.com/1854768/104827052-7b40b200-581f-11eb-9170-ff23d3febe67.png)

But you cannot disable the other hover popup which happens when hovering over a stream

![image](https://user-images.githubusercontent.com/1854768/104827039-69f7a580-581f-11eb-9a81-cf58800d6bf9.png)

Please add another config to enable/disable this one.

**Comment by mvdobrinin** [comment]
Bump

**Comment by wyze** [comment]
You can pass `isInteractive={false}` to the chart and it will disable the interactivity, which is currently only the tooltip.

**Comment by mvdobrinin** [comment]
@wyze This should still be open IMO.

`isInteractive={false}` actually disables both the (1) vertical line tooltip and the (2) stream hover tooltip at the same time.

`enableStackTooltip` controls the (1) vertical line tooltip. But there is no option that controls the (2) stream hover tooltip.

Users need to be able to enable only the vertical line tooltip while disabling the stream hover tooltip.

**Comment by wyze** [comment]
Sorry, I misread and thought you didn't want any tooltip.
