### ISSUE TITLE
Export plot items (and expose in TS definitions)

### ISSUE THREAD

**Issue by casperOne** [plouc/nivo#1393]
**Is your feature request related to a problem? Please describe.**

There are times I'd like to make modifications to the default plot items that are rendered.  In this particular case, I'd like to set the `cursor` property on a `BarItem` to `pointer`.

**Describe the solution you'd like**

I'd be more than happy to modify the JSX element of the item that's returned from rendering the `BarItem`.  For example, I could define the following component which would set the `cursor` property on the default `BarItem` to `pointer`:

```
function BarItemWithPointerCursor(
    props: BarItemProps
) {
    // Render the element.
    const element = <BarItem {...props}/>

    // Modify the cursor property.
    return React.cloneElement(
        element,
        { cursor: 'pointer' }
    )
}
```

And then render my `Bar` element like so:

```
return (
    <Bar
        // Other props...
        barComponent={BarItemWithPointerCursor}
    />
)

```

**Describe alternatives you've considered**

The only other ways I can think to do this are:

- Copy the code from `BarItem` to replicate the rendering
- Create a CSS class that relies on a nested element media query

Both of these are much more brittle than having direct access to the `BarItem` itself.

**Comment by casperOne** [comment]
Bump

**Comment by casperOne** [comment]
Dump

**Comment by wyze** [comment]
We now export `BarItem` as of https://github.com/plouc/nivo/releases/tag/v0.72.0.
