### ISSUE TITLE
Bar chart X-axis is typed as a 'BandScale' and as such does not support custom ticks

### ISSUE THREAD

**Issue by jamesdh** [plouc/nivo#1395]
**Describe/explain the bug**
Bar charts have the typing `indexScale: BandScale` and use `scaleBand()` for generating their X-axis scale. Scale bands do not support ticks and as such, every bar must have a tick. This falls down for scenarios where we'd like to use a large number of bars on a timeline of days, but only want to show a tick for each week or month. Otherwise it looks obnoxious. This also means that configuring the x-axis doesn't follow the guidelines as shown at https://nivo.rocks/guides/axes

<img width="700" alt="Screen Shot 2021-01-17 at 3 30 16 PM" src="https://user-images.githubusercontent.com/1085322/104856546-f6b26a00-58d8-11eb-8a6b-3e11723632b9.png">

**Comment by jamesdh** [comment]
It's also a bit confusing that the BandScale is whole implemented within the Bars package, but it's typings are within the Scales package. Meanwhile, all the other scale types are defined within the Scales package. It appears this could use a bit of cleanup.

**Comment by jamesdh** [comment]
For anyone interested, a workaround is to define your own timescale, and then use a custom axis format function to only print the tick label if the value is contained within the timescale ticks, e.g.

```javascript
const timeScaleTicks: string[] = useMemo(() => {
    const scale = scaleTime().domain([from, to])
    const ticks = scale.ticks(10)
    const formatter = timeFormat('%d %b')
    return ticks.map(tick => (
      formatter(tick)
    ))
  }
})
```

```javascript
axisBottom={{
  tickSize: 5,
  tickPadding: 5,
  tickRotation: 45,
  format: (val) => { 
      return timeScaleTicks.includes(formatter(new Date(val))) ? formatter(new Date(val)) : '' 
  } 
}}
```

It will still end up printing the tick lines, but it still looks much less cluttered: 
<img width="702" alt="Screen Shot 2021-01-18 at 9 47 15 AM" src="https://user-images.githubusercontent.com/1085322/104937072-fb2b6100-5972-11eb-8994-d6782879e8aa.png">

**Comment by sebastienbarre** [comment]
Thanks @jamesdh -- it's too bad the Bar chart still doesn't support time scale. Could you please clarify where `timeFormat` and `scaleTime` are coming/imported from?  Thank you.

**Comment by Nanak360** [comment]
`timeFormat` is being imported from `d3-time-format`, like `import { timeFormat } from 'd3-time-format'`
 and `scaleTime` like `import { scaleTime } from 'd3-scale'`
