### ISSUE TITLE
TypeScript error in nivo/line: Module '"@nivo/core"' has no exported member 'DataFormatter'

### ISSUE THREAD

**Issue by MartinCastellanos-at** [plouc/nivo#1399]
**Describe/explain the bug**
I'm getting the following Typescript error with version "0.67.0":
Error:
```
node_modules/@nivo/tooltip/dist/types/BasicTooltip.d.ts:2:10 - error TS2305: Module '"@nivo/core"' has no exported member 'DataFormatter'.

2 import { DataFormatter } from '@nivo/core';
           ~~~~~~~~~~~~~

node_modules/@nivo/line/index.d.ts:17:5 - error TS2305: Module '"@nivo/core"' has no exported member 'DataFormatter'.

17     DataFormatter,
       ~~~~~~~~~~~~~

```

It seems like this commit (https://github.com/plouc/nivo/commit/5b158797da79430260c1e75165dd1c0cd15264e1) missed the files referenced in the error above.

**To Reproduce**
```
"@nivo/bar": "^0.67.0",
"@nivo/core": "^0.67.0",
"@nivo/line": "^0.67.0",
"@nivo/pie": "^0.67.0 ",
"@nivo/tooltip": "^0.67.0",
```

**Expected behavior**
No TypeScript error.

**Screenshots**
N/A

**Additional context**
TypeScript version 4.0.5

**Comment by mickvangelderen** [comment]
On a related note, I'm missing `ThemeProvider`.

**Comment by timiles** [comment]
Looking at the js code, `ThemeProvider` _should_ still be exported, but is missing from Core's `index.d.ts`. @mickvangelderen did you find a solution?

**Comment by mickvangelderen** [comment]
Don't remember, probably declare everything as `any` as I was working on a quick tool and couldn't make time for a proper PR.

**Comment by wyze** [comment]
Looks like we need to update the usage in the Line types to use the `ValueFormat` type instead.
