### ISSUE TITLE
Nivo Line with custom bar layer (d3-shape)

### ISSUE THREAD

**Issue by sai-gurram** [plouc/nivo#1400]
I wanted to use { ResponsiveLine } from '@nivo/line' and have a Bar component as one of the layers to the ResponsiveLine?

**Comment by xessam** [comment]
any update on this, need help

**Comment by wyze** [comment]
Yes it is possible. The `BarItem` component is exported from the `@nivo/bar` package. Give it a shot and report back. Here is an example of a Line chart with a couple custom layers: https://codesandbox.io/s/fancy-line-chart-3quqe

**Comment by wyze** [comment]
Closing as answer was previously provided. Feel free to report back if there are any issues.
