### ISSUE TITLE
Allow onMouseMove and onMouseLeave Events For Line Charts when Slice Tooltip is Enabled

### ISSUE THREAD

**Issue by pnewhook** [plouc/nivo#1401]
**Is your feature request related to a problem? Please describe.**
I'm synchronizing multiple charts on the same page using the technique described here: https://nivo.rocks/storybook/?path=/story/scatterplot--synchronizing-charts However, adding custom onMouseMove and onMouseLeave handles precludes using the out of the box slice tooltip. Each chart has two series, one for current values and one for target values. It would be nice to see both values in the tooltip, as it behaves when `enableSlices = 'x'`

This scenario is similar requested in this comment, https://github.com/plouc/nivo/issues/47#issuecomment-656187650, but I felt it deserved it's own feature request given the number of upvotes that comment has.

**Describe the solution you'd like**
I would like to be able to supply `onMouseMove` and `onMouseLeave` handlers when `enableSlices="x"`

**Describe alternatives you've considered**
I'm exploring adding a custom tooltip but it is messier than the default  x slice tooltip.

**Additional context**

**Comment by MatissJanis** [comment]
bump

**Comment by Porqumn** [comment]
bump

**Comment by fspin** [comment]
bump

**Comment by p-abasian** [comment]
bump
