### ISSUE TITLE
Add axis to radar chart

### ISSUE THREAD

**Issue by malekhammou** [plouc/nivo#1402]
![RADAR](https://user-images.githubusercontent.com/46074100/106036986-5af1dc80-60d6-11eb-942b-ba322b352383.png)
**Is your feature request related to a problem? Please describe.**
Is there a way to add an axis on the Radar chart like the image?  dot labels overlap when the values are too close. 

**Describe the solution you'd like**
A good alternative would be to have an axis so the user can have an approximation of the values.

**Describe alternatives you've considered**
labeled grid lines with a scale (for example 0.2 0.4 0.6 0.8 1).

**Additional context**

**Comment by Ialimijoro** [comment]
Hello, did you find a solution for that @malekhammou ?

**Comment by YousraHa** [comment]
This could be the solution : 
https://medium.com/@Yousra.H/single-axis-label-for-radar-charts-c87d8ab18f27
