### ISSUE TITLE
Nivo Calendar, last 365 days

### ISSUE THREAD

**Issue by anton-johansson** [plouc/nivo#1405]
I'd love the possibility to show the last 365 days in the `@nivo/calendar` component. What I mean by that is something like the GitHub contributions calendar on your profile page.

If I currently set it to the last 365 days, I'm going to get two years, one for 2020 and one for 2021, and I really just want to show the 1. Mainly because of space issues, I don't want this to take up too much space.

Thoughts? Ideas?

**Comment by mamilov** [comment]
I believe this is what you want? https://github.com/plouc/nivo/pull/1173
Unfortunately not merged yet..

**Comment by anton-johansson** [comment]
@mamilov, thanks a lot. Looks like it's exactly what I want. :)
