### ISSUE TITLE
ResponsiveBar in production build - Y axis tick values not updating on setstate

### ISSUE THREAD

**Issue by Dnathan33** [plouc/nivo#1407]
**Describe/explain the bug**
I'm using ResponsiveBar to visualize simple grade percentage data. In development everything works as expected however, in production the tick values don't seem to update on setstate. 

**Code**
```
          <ResponsiveBar
            data={gradePrecentage}
            keys={["A", "B", "C", "D", "F", "O"]}
            indexBy="id"
            margin={{ top: 0, right: 60, bottom: 50, left: 50 }}
            padding={0.1}
            valueScale={{ type: "linear" }}
            indexScale={{ type: "band", round: true }}
            label={(d) => `${d.value}%`}
            colors={[
              "#41ab5d",
              "#7fc97f",
              "#f16913",
              "#ef3b2c",
              "#e41a1c",
              "#e41a1c",
            ]}
            itemHeight={"120px"}
            axisTop={null}
            axisRight={null}
            axisBottom={{
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "Grade",
              legendPosition: "middle",
              legendOffset: 32,
            }}
            axisLeft={{
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "% of Students",
              legendPosition: "middle",
              legendOffset: -40,
            }}
    />
```
data = [{id: key, data: value}]

**Expected behavior**
Y axis Tick values should update as data changes on setstate in production build.

**Screenshots**
<img width="110" alt="Screen Shot 2021-02-01 at 1 30 44 PM" src="https://user-images.githubusercontent.com/39175434/106501910-b2ef6100-6491-11eb-8030-b42e4d50b739.png">

**Desktop (please complete the following information):**
 - Browser chrome 88.0, safari 14.0.2

**Comment by mehulmshah** [comment]
I'm having this same issue - ResponsiveLine works perfectly in dev, but has following issues in production:
* Y axis legend & ticks are missing
* Data points are all over and graph is not animated or responsive.

**Comment by monzilnepali** [comment]
I have also faced a similar issue with the Line. Work perfectly on local but issue with tooltip animation on production build. And it turns out there is an issue with `react-spring` on a production build. Check this [issue](https://github.com/pmndrs/react-spring/issues/1078) for detailed info.

**Comment by arasovic** [comment]
I had same issue. It's interesting but I added **`animate={false}`** prop and I cleared data state when every data state change. It's costly but working now.

**Comment by mehulmshah** [comment]
I should have updated -- I was able to fix it using [this solution](https://github.com/pmndrs/react-spring/issues/1078#issuecomment-753032426)

Essentially due to an issue with `react-spring`, you have to set `sideEffects: false` in your config -- like @monzilnepali says above.

**Comment by Dnathan33** [comment]
@mehulmshah, I saw your linked solution. Thanks for sharing.
"Add a script to your root package.json, and run it on postinstall:" What exactly do they mean by `run it on postinstall`?

**Comment by mehulmshah** [comment]
> @mehulmshah, I saw your linked solution. Thanks for sharing.
> "Add a script to your root package.json, and run it on postinstall:" What exactly do they mean by `run it on postinstall`?

@Dnathan33 Essentially they want you to run that script after the main yarn install that will gather all the correct dependencies & build the application. As an example, see below my `scripts` object in my `package.json` -- note that I am deploying on Heroku so there may be some slight differences. Essentially on deployment, `yarn start` will run, which will run `node index.js`. Then after that is fully built, Heroku will run `yarn heroku-postbuild`, which is equivalent to `running on postinstall`. And inside the heroku postbuild I run the `react-spring-issue-1078` script.

"scripts": {   
    "start:dev": "nodemon",  
    "start": "node index.js",  
    "heroku-postbuild": "yarn run react-spring-issue-1078 && cd frontend && yarn && yarn run build",  
    "test": "yarn workspaces run test",
    "react-spring-issue-1078": "find node_modules -path \\*@react-spring/\\*/package.json -exec sed -i.bak 's/\"sideEffects\": false/\"sideEffects\": true/g' {} +"
  }

and my high-level directory structure is:
```
project
│   package.json (script JSON above is for this file)
|   yarn.lock
│   index.js    
│
└───frontend
│   │   package.json
│   │   yarn.lock
│   └───src (main frontend JS files)
│   └───build (folder created during `yarn build` command)
│   
└───node_modules
    │   ...
    │   ...
```
Hope that helps.

**Comment by Dnathan33** [comment]
> > @mehulmshah, I saw your linked solution. Thanks for sharing.
> > "Add a script to your root package.json, and run it on postinstall:" What exactly do they mean by `run it on postinstall`?
> 
> @Dnathan33 Essentially they want you to run that script after the main yarn install that will gather all the correct dependencies & build the application. As an example, see below my `scripts` object in my `package.json` -- note that I am deploying on Heroku so there may be some slight differences. Essentially on deployment, `yarn start` will run, which will run `node index.js`. Then after that is fully built, Heroku will run `yarn heroku-postbuild`, which is equivalent to `running on postinstall`. And inside the heroku postbuild I run the `react-spring-issue-1078` script.
> 
> "scripts": {
> "start:dev": "nodemon",
> "start": "node index.js",
> "heroku-postbuild": "yarn run react-spring-issue-1078 && cd frontend && yarn && yarn run build",
> "test": "yarn workspaces run test",
> "react-spring-issue-1078": "find node_modules -path \_@react-spring/\_/package.json -exec sed -i.bak 's/"sideEffects": false/"sideEffects": true/g' {} +"
> }
> 
> and my high-level directory structure is:
> 
> ```
> project
> │   package.json (script JSON above is for this file)
> |   yarn.lock
> │   index.js    
> │
> └───frontend
> │   │   package.json
> │   │   yarn.lock
> │   └───src (main frontend JS files)
> │   └───build (folder created during `yarn build` command)
> │   
> └───node_modules
>     │   ...
>     │   ...
> ```
> 
> Hope that helps.

@mehulmshah Thank you :)

**Comment by petrvecera** [comment]
I am having the same issue. For some reason in production build the axis are not re-rendered. Everything works fine in dev build.

**Comment by mehulmshah** [comment]
@petrvecera check my response two messages above -- my solution or any of the ones in [this thread](https://github.com/pmndrs/react-spring/issues/1078#issuecomment-753032426) will solve the issue.

**Comment by wyze** [comment]
We've update to the latest react-spring and this workaround won't be needed.
