### ISSUE TITLE
Lag when swapping between data sources after upgrading nivo/line from 0.61.0  ❯  0.67.0

### ISSUE THREAD

**Issue by JeffBeltran** [plouc/nivo#1409]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

No

**Describe/explain the bug**
There is lag when swapping between data sources after upgrading
```
@nivo/core  0.61.0  ❯  0.67.0
@nivo/line  0.61.1  ❯  0.67.0
```

**To Reproduce**
Before i fire up a full reproduction wanted to make sure i wasn't missing something first, but here are some gifs to show the lag, the only difference in the current repo is me running `npm install --save @nivo/core@0.67.0 @nivo/line@0.67.0`

**Before: 0.61.0**
![0 61 0](https://user-images.githubusercontent.com/22965241/106960255-a61c7880-66f0-11eb-9e27-13e8b28ca69f.gif)

**After: 0.67.0**
![0 67 0](https://user-images.githubusercontent.com/22965241/106960277-b0d70d80-66f0-11eb-903e-0bfa618485a7.gif)

1. Enjoy working chart
2. upgrade by running `npm install --save @nivo/core@0.67.0 @nivo/line@0.67.0`
3. troubleshoot for a week before narrowing down the issue

**Expected behavior**
Data loads as fast as previous version

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome (not as noticeable in firefox)
 - Version 11.1

**Additional context**
Each data set consists of 400 points. 

If i need to duplicate this in code, i'll work up a repo to help show this, but i just wanted to report this first and check to make sure i wasn't missing something that was in the docs. I inherited this project, so for now i'll just leave this at the older version and circle back to it.

**Comment by JeffBeltran** [comment]
so just took a look again at this and i get this when i go from 0.62.0 to 0.63.0, so 0.63.0+ seems to be having this issue, looking at the change log it appears to correspond to major change of `replace react-motion by react-spring (ca452490)`

**Comment by wyze** [comment]
@JeffBeltran Is this still an issue? I know we had merged a PR related to some performance issue, but don't quite remember. Can you check the latest version? If it is still an issue, please throw together a Codesandbox and we can take a look!
