### ISSUE TITLE
TickValues set to "every two days" but display both 01/31 and 02/01

### ISSUE THREAD

**Issue by cfecherolle** [plouc/nivo#1410]
**Describe/explain the bug**
I have a Line Chart set with a Date Bottom Axis, which has tickValues set to "every 2 days".
Even with this parameter, while most of the ticks on my chart are displayed accordingly (every two days) I still have two ticks for 01/31 and 02/01, which makes the tick labels look all garbled: they overlap each other. (see screenshot)

**Expected behavior**
I expected to have a tick every two day on the bottom axis.

**Screenshots**
<img width="701" alt="Capture d’écran 2021-02-05 à 11 49 41" src="https://user-images.githubusercontent.com/3169480/107024473-62854580-67a8-11eb-8983-3a50c9101482.png">

**Desktop**
 - OS: OSX
 - Browser: Chrome
 - Version: 88.0.4324.146

**Additional context**
I haven't added any code example, as this is a business case in the company I'm working at and I would have first to obfuscate the data and code. Hopefully, this gives enough information to reproduce and understand the issue. If not, I will take some time to add a sandbox, just ask! :)
Also, I'm French so labels are formatted using %d/%m format, this is expected and wanted ;)

**Comment by m1yon** [comment]
I have a very similar issue, it seems to occur during month transitions. I get the same behavior with any of the time based tickValues.

**Comment by cfecherolle** [comment]
Still an issue (bump!)

**Comment by cfecherolle** [comment]
Thanks a lot! :)

**Comment by MattB543** [comment]
@m1yon

I tried your method of supplying an array of dates like so:
```
axisBottom={{
format: "%b %d",
tickValues: ["2022-09-05", "2022-09-12", "2022-09-19", "2022-09-26", "2022-10-03", "2022-10-10"]
}}
```
And all of the dates overlap each other at the first tick:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/45475210/195699941-e9f3c642-a26f-4a8b-942e-2fceab8719c9.png">

and I get this error: `Failed prop type: The prop 'x' is marked as required in 'AxisTick', but its value is 'undefined'`


If instead, I put `tickValues: 6` it gives me 5 ticks all one day off of my data

<img width="768" alt="image" src="https://user-images.githubusercontent.com/45475210/195700491-12570904-b266-4d45-95b3-f476cbf2415c.png">

Do you still solve this issue in the way you showed above?

**Comment by m1yon** [comment]
> @m1yon
> 
> I tried your method of supplying an array of dates like so:
> 
> ```
> axisBottom={{
> format: "%b %d",
> tickValues: ["2022-09-05", "2022-09-12", "2022-09-19", "2022-09-26", "2022-10-03", "2022-10-10"]
> }}
> ```
> 
> And all of the dates overlap each other at the first tick: <img alt="image" width="777" src="https://user-images.githubusercontent.com/45475210/195699941-e9f3c642-a26f-4a8b-942e-2fceab8719c9.png">
> and I get this error: `Failed prop type: The prop 'x' is marked as required in 'AxisTick', but its value is 'undefined'`

In my example, I'm setting `tickValues` to an array of **Dates**, not strings. Have you tried that?

> If instead, I put `tickValues: 6` it gives me 5 ticks all one day off of my data
> 
> <img alt="image" width="768" src="https://user-images.githubusercontent.com/45475210/195700491-12570904-b266-4d45-95b3-f476cbf2415c.png">

I would look and see what type `tickValues` is expecting. The API may have changed since my solution was from a year and a half ago.

> Do you still solve this issue in the way you showed above?

I'm not sure, I've switched projects/companies since then :(

**Comment by MattB543** [comment]
@m1yon ah, thanks anyway! Would you still recommend Nivo or would you recommend a different simple React charting library for me to try?

**Comment by m1yon** [comment]
> @m1yon ah, thanks anyway! Would you still recommend Nivo or would you recommend a different simple React charting library for me to try?

I think Nivo's great! My old team still uses it, and they've gotten many compliments from customers on how great the charts are.
