### ISSUE TITLE
Apply zebra-striping style to Line chart

### ISSUE THREAD

**Issue by ytliuSVN** [plouc/nivo#1412]
**Is your feature request related to a problem? Please describe.**
Is there a way to add a striped style in Line chart. Ex. [bootstrap](https://getbootstrap.com/docs/4.1/content/tables/#striped-rows) table zebra stripe.

![Screenshot from 2021-02-07 10-10-32](https://user-images.githubusercontent.com/13102859/107134567-3a275380-692e-11eb-89bd-84a79ccb7aa3.png)

**Describe the solution you'd like**
A good alternative would be to have a striped property so the user can toggle it.

**Describe alternatives you've considered**
Support dark and light mode.

**Additional context**
Need to apply striped style on it.

![Screenshot from 2021-02-07 10-19-05](https://user-images.githubusercontent.com/13102859/107134572-46abac00-692e-11eb-91b1-da51c7ce6740.png)

**Comment by wyze** [comment]
Are you wanting to zebra stripe the background between each month?

**Comment by ytliuSVN** [comment]
Apply zebra-striped style, set another background color to all even (or odd) month intervals.

**Comment by wyze** [comment]
You can use a custom layer to achieve this as I have done previously in this sandbox: https://codesandbox.io/s/fancy-line-chart-3quqe?file=/src/App.tsx:365-416
