### ISSUE TITLE
Possible to use links as axis labels / legend labels?

### ISSUE THREAD

**Issue by ku3nsting** [plouc/nivo#1414]
Hello - I am using responsiveBar charts with the horizontal layout, and was wondering if it's possible to turn the labels on the y axis into hyperlinks. I've looked into the custom (legend) layers in examples like [this one](https://codesandbox.io/s/nivo-bar-example-nf86t), but when I've attempted to pass html to the custom label field it is always rendered as a string. 
Thanks!

**Comment by Zelphire** [comment]
Hi,

I don't know if this is the correct solution. but I tried it out on the example @ku3nsting  provided ([this one](https://codesandbox.io/s/nivo-bar-example-nf86t))

changed the code to something like this and looks to be working

`const BarLegend = ({ height, legends, width }) => (
  <React.Fragment>
    {legends.map((legend) => (
      <BoxLegendSvg
        onClick={() => {
          window.location.href = "https://mysampleurl.com"; // add your sample url here
        }}
        key={JSON.stringify(legend.data.map(({ id }) => id))}
        {...legend}
        containerHeight={height}
        containerWidth={width}
      />
    ))}
  </React.Fragment>
);
`

I know this isn't actually turning the legends into hyperlinks but they will navigate to your desired URL when clicked.. hope this helps

**Comment by Ali-Mahmood-Dentsu** [comment]
so the code sandbox link provided above seems to work on a limited amount of charts.

Would love to see this applied on all charts.

Is this possible @plouc @wyze ?

**Comment by wyze** [comment]
Any chart that supports legends supports onClick directly when passing to `legends={[{..}]}` prop to the chart. As far as the original question for the ticks, you can pass a custom `renderTick` function that wraps the text in a `a` tag. See https://alligator.io/svg/hyperlinks-svg/
