### ISSUE TITLE
Infinite rendering loop when using renderTick

### ISSUE THREAD

**Issue by rgazelot** [plouc/nivo#1415]
**Describe/explain the bug**
When data change and using renderTick, the ticks are indefinitely rendering.

**To Reproduce**

1. Go to 'https://codesandbox.io/s/spring-tree-fz4pp'
2. Click on 'Add Entry' button
3. Open the console
4. See that the console.log inside the CustomTick component re-render indefinitely 

**Expected behavior**
The ticks are re-rendered only once

Thanks a lot for your work and this lovely library 👍

**Comment by stephent** [comment]
Possibly related to #1379?

**Comment by wyze** [comment]
This was fixed via #1408.

**Comment by rgazelot** [comment]
Thanks a lot guys good job
