### ISSUE TITLE
Invariant Violation: Minified React error 

### ISSUE THREAD

**Issue by damianpm** [plouc/nivo#1418]
**Thanks for using nivo**

**Describe/explain the bug**
Website is crashing with following error:
```
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20color%2C%20children%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

**To Reproduce**
1. Go to https://nivo.rocks/bubble/
2. Click "roll the dice" several times
After some clicks, it will fail:

**Expected behavior**
Page doesn't crash

**Screenshots**
<img width="646" alt="Screenshot 2021-02-12 at 10 09 24" src="https://user-images.githubusercontent.com/13486237/107749177-72f26e80-6d1a-11eb-8162-cd19325abf34.png">

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - Browser: Firefox
 - Version: 85.0.1 (64-bit)

**Comment by wyze** [comment]
Is this still happening? I must have clicked roll the dice 100 times and had no issues.

**Comment by damianpm** [comment]
I have tried again and now it works fine. Closing issue
