### ISSUE TITLE
Support for custom names for x and y labels in the hover menu

### ISSUE THREAD

**Issue by Ali-Kiyan** [plouc/nivo#1422]

**Comment by Ali-Kiyan** [comment]
"bump"

**Comment by wyze** [comment]
This ticket didn't follow the issue template. I'm not 100% sure what you are requesting. Please add more detail.

**Comment by wyze** [comment]
Closing this as there hasn't been a response and the issue template wasn't followed. Feel free to open a new issue/discussion with more content.
