### ISSUE TITLE
Nivo Line tooltip issue in production build

### ISSUE THREAD

**Issue by monzilnepali** [plouc/nivo#1423]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**
No

**Describe/explain the bug**
Tooltip works fine in `development` but does not work as expected in the `production` build.

**To Reproduce**
[codesandbox](https://codesandbox.io/s/nivo-line-issue-8l3e8?file=/src/App.js)
[website](https://csb-8l3e8.netlify.app/)

1. Create production build
2. Serve production build and check the tooltip
3. This error is shown in the production build
![image](https://user-images.githubusercontent.com/28225895/108199566-55237000-7145-11eb-9ff4-3b7da3a071fc.png)

**Expected behavior**
the tooltip should behave the same in dev as well as in the production  build

**Screenshots**
Before:
![captured-1071df17d399e2aa70.gif](https://s2.gifyu.com/images/captured-1071df17d399e2aa70.gif)

After: 
![captured-11603443eb87f203dc.gif](https://s2.gifyu.com/images/captured-11603443eb87f203dc.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Version v88

**Additional context**
It seems like this is related to `react-spring v9.0.0-rc.3` . There is an [open issue](https://github.com/pmndrs/react-spring/issues/1078) regarding react-spring in the `production` build. This might be the reason for the tooltip issue.
Thank you

**Comment by Ali-Kiyan** [comment]
@monzilnepali I am experiencing the same issue. Did you find a fix?

**Comment by monzilnepali** [comment]
@Ali-Kiyan yeah, I able to fix this issue. There is a production build issue in react-spring but able to fix with minor patch mention in this [comment](https://github.com/pmndrs/react-spring/issues/1078#issuecomment-753032426)

**Comment by Ali-Kiyan** [comment]
@monzilnepali Thank you! Shortly after my comment I found a web pack fix for react-spring and I used react-rewrite to add the following while building or starting my code (just mentioning for future references)

```
module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /react-spring/,
      sideEffects: true,
    })

    return config
  },
}
```
