### ISSUE TITLE
HeatMap Label Formatting

### ISSUE THREAD

**Issue by arasovic** [plouc/nivo#1425]
I'm using svg heatmap component. I can edit tooltip values but I couldn't find any prop for edit label values.
Can I format label values, like in tooltip ? Do you have any solution?

![heatmap](https://user-images.githubusercontent.com/9802740/108261717-0d1c4180-7175-11eb-82be-cab142f3dc39.png)

second to H:M:S

**Comment by wyze** [comment]
This is solved via #1428.
