### ISSUE TITLE
The chart gets deformed on re-render

### ISSUE THREAD

**Issue by sk8Guerra** [plouc/nivo#1426]
I'm using **ResponsiveLine time-scale**, to show some data. I have a select with different options. As soon as I select another option (to fetch another type of data) the chart gets deformed; lines pointing to where they should not.

<img width="546" alt="Screen Shot 2021-02-18 at 12 50 22" src="https://user-images.githubusercontent.com/18681676/108527001-67152800-7297-11eb-95c7-3073aa6826b9.png">

**Expected behavior**
New data should print normal, with line pointing to where they should, not to other lost places.

**Desktop:**
 - Windows
 - chrome
 - 88

**Comment by maddy2894** [comment]
Hey @sk8Guerra I am facing similar issue, were you able to solve it?

**Comment by sk8Guerra** [comment]
Yes I solved it. I forgot to update this issue. 🤦🏽‍♂️

Instead of passing directly the new data to be displayed in the chart, I pass an empty array, to completely clean chart's internal at state; and then I pass the new data. 

Let me know if you can solve it that way.

**Comment by DaggLo** [comment]
> ...
> Instead of passing directly the new data to be displayed in the chart, I pass an empty array, to completely clean chart's internal state; and then I pass the new data.
> ...

Hi @maddy2894,
would you please attach kind a code snippet or smth of how did you do that?

I've tried something like below but got no luck :disappointed: 
```
if (/* Checks if data has actually changed */) {
    if (!state.wasCleared) { // <-- Checks if data has been already cleared before (via flag).
      setState({
        data: [],
        wasCleared: true,
      });
    } else {
      setState({
        data,
        wasCleared: false,
      });
    }
  }
```

**Comment by wyze** [comment]
If you can provide an example of the issue in a CodeSandbox, that would be helpful. See if there is a bug to fix instead of you having to do a workaround.

**Comment by devpms** [comment]
<img width="961" alt="Screenshot 2021-04-27 at 7 14 01 PM" src="https://user-images.githubusercontent.com/50977617/116251930-bd698000-a78c-11eb-823d-e5779c149033.png">


when chart gets render Y axis sorting is not getting applied due to that it seems deformed

**Comment by wyze** [comment]
@devpms We don't sort the data, you need to have it sorted correctly before passing it to the chart.

**Comment by sk8Guerra** [comment]
@devpms are you passing an empty array before you pass the new data? That is, cleaning the previous state inside nivo. Those weird lines are a remainder state from the previous passed data.

**Comment by devpms** [comment]
So, we have date filters implemented on the data and the issue we are facing is when we filter out the data by applying the dates its mixing up with the old data and that is causing this issue, what is the solution for the same.

**Comment by wyze** [comment]
@devpms I'd need to see the data, filtering, and chart to answer better. But ensure the data is sorted by the X value before passing it to the chart, even after filtering, you may have to sort it again. If it still looks off, instead of filtering data out, replace the "filtered" data's `y` value with null instead.

**Comment by muneeb706** [comment]
> So, we have date filters implemented on the data and the issue we are facing is when we filter out the data by applying the dates its mixing up with the old data and that is causing this issue, what is the solution for the same.

Facing the same issue when I upgraded to version 0.73.0

**Comment by wyze** [comment]
Still waiting on a CodeSandbox to reproduce this and we can see if there is a fix or workaround.
