### ISSUE TITLE
Can I pass props to a custom layer component?

### ISSUE THREAD

**Issue by luizamendes** [plouc/nivo#1427]
Hi everyone. 

I would like to pass a value to be rendered in the metric component just like this one in the storybook example:
https://nivo.rocks/storybook/?path=/story/pie--adding-a-metric-in-the-center-using-a-custom-layer

In the example, the component does the math, but I would like to have the component just render some value that comes from my API because I am filtering values when the user clicks a slice. 

I can't figure out how to do it. Is it possible?]

Thanks so much.

**Comment by olavoparno** [comment]
Hey, I think this is pretty much how you return the centered component using the props `layers`. I also think it must be a valid SVG valid tags https://developer.mozilla.org/en-US/docs/Web/SVG/Element

Check the sandbox below where there is a CustomPie component. 

https://codesandbox.io/s/kind-morning-z3ygm?file=/src/App.js

Is this how you wanted it to be?

**Comment by luizamendes** [comment]
@olavoparno Yes, this did the trick. Thanks!
