### ISSUE TITLE
 create a single level bubble chart

### ISSUE THREAD

**Issue by SimronMohapatra** [plouc/nivo#1429]
Hi, I was trying to create a single level bubble chart (like the bubble chart example in d3). However its not rendering anything. I manipulated the data to make it look something like this -
[
//     {
//                         "name": "cchart",
//                         "color": "hsl(111, 70%, 50%)",
//                         "loc": 35754
//                       },
//                       {
//                         "name": "xAxis",
//                         "color": "hsl(278, 70%, 50%)",
//                         "loc": 3926
//                       },
//                       {
//                         "name": "yAxis",
//                         "color": "hsl(312, 70%, 50%)",
//                         "loc": 191691
//                       },
//                       {
//                         "name": "layers",
//                         "color": "hsl(312, 70%, 50%)",
//                         "loc": 79490
//                       },
//                       {
//                                 "name": "outline",
//                                 "color": "hsl(307, 70%, 50%)",
//                                 "loc": 2070
//                               },
//                               {
//                                 "name": "slices",
//                                 "color": "hsl(10, 70%, 50%)",
//                                 "loc": 104839
//                               },
//                               {
//                                 "name": "bbox",
//                                 "color": "hsl(171, 70%, 50%)",
//                                 "loc": 55307
//                               },{
//                             "name": "donut",
//                             "color": "hsl(172, 70%, 50%)",
//                             "loc": 195971
//                           },
//                           {
//                             "name": "gauge",
//                             "color": "hsl(166, 70%, 50%)",
//                             "loc": 143594
//                           }, {
//                     "name": "randomize",
//                     "color": "hsl(340, 70%, 50%)",
//                     "loc": 163177
//                   },
//                   {
//                     "name": "resetClock",
//                     "color": "hsl(231, 70%, 50%)",
//                     "loc": 42841
//                   },
//                   {
//                     "name": "noop",
//                     "color": "hsl(315, 70%, 50%)",
//                     "loc": 45724
//                   },
//                   {
//                     "name": "tick",
//                     "color": "hsl(3, 70%, 50%)",
//                     "loc": 142157
//                   },
//                   {
//                     "name": "forceGC",
//                     "color": "hsl(104, 70%, 50%)",
//                     "loc": 163340
//                   },
//                   {
//                     "name": "stackTrace",
//                     "color": "hsl(217, 70%, 50%)",
//                     "loc": 99327
//                   },
//                   {
//                     "name": "dbg",
//                     "color": "hsl(202, 70%, 50%)",
//                     "loc": 140897
//                   },{
//                     "name": "address",
//                     "color": "hsl(207, 70%, 50%)",
//                     "loc": 35898
//                   },
//                   {
//                     "name": "city",
//                     "color": "hsl(302, 70%, 50%)",
//                     "loc": 28755
//                   },
//                   {
//                     "name": "animal",
//                     "color": "hsl(360, 70%, 50%)",
//                     "loc": 112101
//                   },
//                   {
//                     "name": "movie",
//                     "color": "hsl(60, 70%, 50%)",
//                     "loc": 118062
//                   },
//                   {
//                     "name": "user",
//                     "color": "hsl(7, 70%, 50%)",
//                     "loc": 60585
//                   },{
//                     "name": "clone",
//                     "color": "hsl(208, 70%, 50%)",
//                     "loc": 189804
//                   },
//                   {
//                     "name": "intersect",
//                     "color": "hsl(266, 70%, 50%)",
//                     "loc": 38862
//                   },
//                   {
//                     "name": "merge",
//                     "color": "hsl(93, 70%, 50%)",
//                     "loc": 15645
//                   }
//          
//     ]
Is this how its done?

**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nino3103** [comment]
Hi SimronMohapatra ! 

I think you have to add a "parent bubble", with a children field that is the array you gave : 

`let root = {
  name: 'parent',
  color: 'parentColor',
  children: [
    {
      name: 'cchart',
      color: 'hsl(111, 70%, 50%)',
      loc: 35754,
    },
    {
      name: 'xAxis',
      color: 'hsl(278, 70%, 50%)',
      loc: 3926,
    },
    {
      name: 'yAxis',
      color: 'hsl(312, 70%, 50%)',
      loc: 191691,
    },
    {
      name: 'layers',
      color: 'hsl(312, 70%, 50%)',
      loc: 79490,
    },
    {
      name: 'outline',
      color: 'hsl(307, 70%, 50%)',
      loc: 2070,
    },
    {
      name: 'slices',
      color: 'hsl(10, 70%, 50%)',
      loc: 104839,
    },
    {
      name: 'bbox',
      color: 'hsl(171, 70%, 50%)',
      loc: 55307,
    },
    {
      name: 'donut',
      color: 'hsl(172, 70%, 50%)',
      loc: 195971,
    },
    {
      name: 'gauge',
      color: 'hsl(166, 70%, 50%)',
      loc: 143594,
    },
    {
      name: 'randomize',
      color: 'hsl(340, 70%, 50%)',
      loc: 163177,
    },
    {
      name: 'resetClock',
      color: 'hsl(231, 70%, 50%)',
      loc: 42841,
    },
    {
      name: 'noop',
      color: 'hsl(315, 70%, 50%)',
      loc: 45724,
    },
    {
      name: 'tick',
      color: 'hsl(3, 70%, 50%)',
      loc: 142157,
    },
    {
      name: 'forceGC',
      color: 'hsl(104, 70%, 50%)',
      loc: 163340,
    },
    {
      name: 'stackTrace',
      color: 'hsl(217, 70%, 50%)',
      loc: 99327,
    },
    {
      name: 'dbg',
      color: 'hsl(202, 70%, 50%)',
      loc: 140897,
    },
    {
      name: 'address',
      color: 'hsl(207, 70%, 50%)',
      loc: 35898,
    },
    {
      name: 'city',
      color: 'hsl(302, 70%, 50%)',
      loc: 28755,
    },
    {
      name: 'animal',
      color: 'hsl(360, 70%, 50%)',
      loc: 112101,
    },
    {
      name: 'movie',
      color: 'hsl(60, 70%, 50%)',
      loc: 118062,
    },
    {
      name: 'user',
      color: 'hsl(7, 70%, 50%)',
      loc: 60585,
    },
    {
      name: 'clone',
      color: 'hsl(208, 70%, 50%)',
      loc: 189804,
    },
    {
      name: 'intersect',
      color: 'hsl(266, 70%, 50%)',
      loc: 38862,
    },
    {
      name: 'merge',
      color: 'hsl(93, 70%, 50%)',
      loc: 15645,
    },
  ],
};`

But, to answer your question, it is possible to have single level bubble chart (keeping the "parent bubble")

1) you can add a  leavesOnly={true} prop to the Bubble Chart Component. But you won't be able to zoom out once you have zoomed in on a bubble.

2) if you want to keep the "zoom out" functionality, you can have single level bubble chart with a little trick. You can make parent bubble color === the background color. It will 'hide' the parent bubble.

I try to explain better: let's say you want this (single level Bubble Chart) 
![Capture d’écran 2021-02-26 à 11 18 59](https://user-images.githubusercontent.com/48714971/109288107-b83b9380-7824-11eb-8278-58cf5b56ce58.png)

But if you add a parent bubble, you have this : 
![Capture d’écran 2021-02-26 à 11 20 35](https://user-images.githubusercontent.com/48714971/109288483-326c1800-7825-11eb-9e43-7a5ad8aaede0.png)

Let say the background color is #03193F (dark blue), and you want to 'hide' the parent bubble.
Well, the trick could be to add a def prop and a fill prop in the bubble chart component : 


```
def= {[
{
          id: 'hiddenBubble',
          type: 'linearGradient',
          colors: [
            { offset: 0, color: '#03193F' },
            { offset: 100, color: '#03193F' },
          ],
        }
]}
```

```
fill={[
         { match: (d: any) => d.data.color === 'parentColor', id: 'hiddenBubble' },
      ]}`

```
