### ISSUE TITLE
Problems Importing Charts

### ISSUE THREAD

**Issue by lisaWriteJava** [plouc/nivo#1433]
I've had to import my charts like so @nivo/bar/dist/nivo-bar.es. The same has happened with ScatterPlots. Is there something else I need to do to use this?

**Comment by wyze** [comment]
You should be able to import like `import { Bar } from '@nivo/bar'`. Are you still having this issue with the latest version?

**Comment by plouc** [comment]
I'm closing this issue due to lack of info, please feel free to add extra info if you still encounter the issue and can provide a reproductible example.
