### ISSUE TITLE
Text being truncated in Nivo ticks' axis text (Bar Chart)

### ISSUE THREAD

**Issue by lesagi** [plouc/nivo#1435]
My Y-Axis keys (or ticks) are pretty long, and they're being truncated
But it's not due to lack of sufficient width for the graph itself, using the inspect tool, I can see there's enough space allocated for it, but the frame that is allocated to the whole graph is not sufficient... and that's supposed to be the ResponsiveBar...

![image](https://user-images.githubusercontent.com/21172737/109217942-2baaba00-77bf-11eb-8984-ca453256ecac.png)

changing the "transform" value for the X-Axis makes the text appear in full (almost), but then the legends are being truncated:

![image](https://user-images.githubusercontent.com/21172737/109218714-71678280-77bf-11eb-8a78-4cce351e93f6.png)

How can I make them appear in full? Couldn't find my answer in the docs.

Here's a sandbox to reproduce the problem: https://codesandbox.io/s/missing-legends-text-pns6v

**IMPORTANT**: 'width' is not the problem, it is somehow covered with a sort of a white line... also, I tried many 'width' sizes

The problem I'm referring to is this:
![image](https://user-images.githubusercontent.com/21172737/109214257-4c244580-77ba-11eb-91e8-47bd5c1f0bd9.png)

**Comment by wyze** [comment]
According to the sandbox the labels are going outside the width of the svg. There isn't anything we can do that.

**Comment by lesagi** [comment]
@wyze 
as I mentioned, this is now a width issue, eventually, it was bearable for me to adjust the margin
but a wiser option would have been to break the text into multiple lines based on the width that's given to the labels area
