### ISSUE TITLE
How I can avoid float numbers on y axis?

### ISSUE THREAD

**Issue by ellipticaldoor** [plouc/nivo#144]
Right now I have this chart

![image](https://user-images.githubusercontent.com/3449006/35852284-64627944-0b22-11e8-9cd3-d9fe14308370.png)

But I know that I'm never going to have float values, can I only show integers?

**Comment by plouc** [comment]
Yes, you can set the `tickValues` property to `[0, 1]` for example.

**Comment by strahius** [comment]
@plouc  is there no other option? What if the y values are in the thousands?

**Comment by kkkrist** [comment]
Recently ran into the floats problem while visualising data with a narrow range of values (single digit; with a wide range of values this shouldn't happen anyway?). 

`tickValues` also takes a number which will then define the number of ticks to display ([docs](https://nivo.rocks/guides/axes/#ticks)). So if you use the number of unique values on the axis as argument, the floats should be gone:

```jsx
<Line
  axisLeft={{
    tickValues: [
      ...data.reduce((set, { y }) => set.add(y), new Set())
    ].length
  }}
/>
```

**Comment by timbrunette** [comment]
Had a similar problem where it didn't make sense to show these float intervals:
![image](https://user-images.githubusercontent.com/36954990/80463517-b3475280-897b-11ea-9d31-25835eced595.png)

Found a solution to this problem via [https://stackoverflow.com/a/12643613](https://stackoverflow.com/a/12643613)
can set `format` to:
```javascript
<Line
  axisLeft={{
    format: e => Math.floor(e) === e && e`
  }}
/>
```
Which will result in the tick values of any floats not showing:
![image](https://user-images.githubusercontent.com/36954990/80463226-416f0900-897b-11ea-8eb1-748ab97724c5.png)

This should work with a dynamic interval range (not limited by the data itself)

**Comment by honungsburk** [comment]
Seems like there was an update, this has the same effect though:

`   axisLeft={{
          format: (e) => (Math.floor(e) === e ? e : ""),
        }}`

**Comment by liamgbs** [comment]
I solved this using:

`format: e => (Number.isInteger(e) ? e : '')`
