### ISSUE TITLE
@nivo/pie Tooltip disappeared on version 0.67.0

### ISSUE THREAD

**Issue by Creaa** [plouc/nivo#1445]
**Describe/explain the bug**

Using default settings from nivo.rocks/pie/ causes missing default tooltip. 
Same as custom.
It happened when I use package in version 0.67.0
When I changed to 0.62.0 everything works fine.

**To Reproduce**

Install @nivo/pie package in version 0.67.0
Use default settings from docs.

**Expected behavior**

Tooltip should be visible.

**Comment by wyze** [comment]
Can you provide a Codesandbox replicating the issue? Also, make sure all nivo packages are on the same version.

**Comment by renan-schmitt** [comment]
I have the same problem with the 0.69.0 version.

**Comment by wyze** [comment]
I am going to close this. It is usually caused by mismatched dependency versions, when different `@nivo` packages have different versions. They all need to match in order for everything to work as expected.

**Comment by jbkuczma** [comment]
We are having this same issue with version 0.70.1, reinstalling does not appear to fix the issue.
