### ISSUE TITLE
bullet chart range other than zero 

### ISSUE THREAD

**Issue by awatson1978** [plouc/nivo#1447]
**Is your feature request related to a problem? Please describe.**
Hello.  Would it be possible to support ranges that start at something other than 0?  For example, with the Bullet graph, we might be trying to graph biomarker reference ranges, such as blood pressure or human body temperature.  Body temperature should typically be around 37 Cel, and in a bullet graph one would generally want to display a range from 34C to 42C, with a healthy values between 36C and 40C.  Currently, we would have to display 0C to 42C, which creates a narrow band and is wasteful of space in the user interface and skews the visualization.  

Also, this request has been raised before in #606

**Describe the solution you'd like**
Ideally include `rangeMin` and `rangeMax` props on the following components:
- Bullet
- Radar

There may be graphs that could benefit from custom ranges, but those are the two that are most relevant to bioinformatics and healthcare applications.

**Describe alternatives you've considered**
Using raw D3, or alternative D3 based charting libraries.  But Nivo is so much better than the alternatives, we'd love to see it included here.  We're trying to forward-port visualizations we've built with D3 to a React based approach using Nivo, and custo ranges are the one feature we're missing.

**Comment by awatson1978** [comment]
Digging through the source code, would you agree that the following line is where the minimum range gets set to 0?
https://github.com/plouc/nivo/blob/master/packages/bullet/src/hooks.ts#L21

My hunch is that setting that to `const min = Math.min(...all)` would have the Bullet graph behave in the manner that we’d like to see.   Although I suspect it might break behavior that other people are expecting, and would need some sort of prop introduced to control the behavior.

**Comment by awatson1978** [comment]
Hey.... I got storyboard working, and did a basic code reproduction and example:

![Screen Shot 2021-03-12 at 7 43 44 PM](https://user-images.githubusercontent.com/675910/111014841-51ad8e00-836b-11eb-97ee-f1bef48d7c6a.png)

**Comment by awatson1978** [comment]
Well, I feel a bit silly now, because I just got it to work.

![Screen Shot 2021-03-12 at 7 51 03 PM](https://user-images.githubusercontent.com/675910/111015023-5c1c5780-836c-11eb-977a-f69d405573c0.png)

For anybody else following up on #606, here is the code example:

```
const data = [{
    "id":"temperature",
    "ranges":[30,45],
    "measures":[34,36,40,42],
    "markers":[37]
}]

const commonProps = {
    width: 900,
    height: 360,
    margin: { top: 10, right: 30, bottom: 50, left: 110 },
    titleOffsetX: -80,
    data,
    spacing: 80,
    animate: false,
}

const stories = storiesOf('Bullet', module)

const CustomRange = ({ x, y, width, height, color, onMouseEnter, onMouseMove, onMouseLeave }) => (
    <rect
        x={x + 2}
        y={y + 2}
        rx={5}
        ry={5}
        width={width - 4}
        height={height - 4}
        fill={color}
        onMouseEnter={onMouseEnter}
        onMouseMove={onMouseMove}
        onMouseLeave={onMouseLeave}

    />
)

stories.add('temperature (C)', () => <Bullet {...commonProps} rangeComponent={CustomRange} height={100} measureColors={['none', 'orange', 'green', 'orange']} rangeColors={["none", "#cccccc"]} markerColors={["black"]}/>, {
    info: {
        text: `You can customize ranges using the \`rangeComponent\` property.`,
    },
})
```

Also, storyboard is a nice little tool.  Should have started using it earlier.

**Comment by makitom** [comment]
Hello, any updates on this? Is it possible to get this feature to bullet chart.
