### ISSUE TITLE
Is there way to hide tick labels on bottom axis on Bar Charts

### ISSUE THREAD

**Issue by joergd** [plouc/nivo#145]
I don't want to see my x-axis tick labels - it's too crowded down there, and am displaying the label on the bars themselves rather - so I have no need for the ticks.

Is there any way to get rid of it?

**Comment by joergd** [comment]
Found this way:

    axisBottom={{
      "orient": "bottom",
      "tickSize": 0,
      "tickPadding": 5,
      "tickRotation": 0,
      "format": () => null,
    }}

Feels like a hack - but it works :)

**Comment by plouc** [comment]
@joergd, you can just set `axisBottom={undefined}`

**Comment by joergd** [comment]
Tried it - but didn't work ... But it's ok - the hack above works well.

**Comment by shanky101** [comment]
This is exactly what I faced. Since after a certain number of entries, the tick labels overlap on each other. Hopefully there is a simple boolean toggle for this, which would simple show/hide for tick display.

**Comment by arturtakoev** [comment]
> @joergd, you can just set `axisBottom={undefined}`

the right way is axisBottom={false}

**Comment by bmmidei** [comment]
While `axisBottom={null}` works if you wish to hide the axis altogether, this workaround helps if you would like to hide the tick marks, but keep the axis label, which was my situation.
Thanks @joergd !

**Comment by Largonarco** [comment]
Idk why but it doesn't work for me.
Does this trick still work??

**Comment by omsteadily** [comment]
No, this didn't work for me.  A shame, as I want to hide the labels but keep the ticks and the legend, not just turn everything off!

**Comment by Ashish-vora** [comment]
Write margin={{ bottom: 0 }}, it's worked for me.

for ex: margin={{ top: 50, right: 0, bottom: 0, left: 0 }}

**Comment by Znoy108x** [comment]
> @joergd, you can just set `axisBottom={undefined}`

how can i hide the legends ?? ? 
![image](https://github.com/plouc/nivo/assets/75539409/b848dfb0-5707-47b7-a94f-ee685dafee11)
