### ISSUE TITLE
@nivo/swarmplot renderNode 'No overload matches this call'

### ISSUE THREAD

**Issue by BuguiBuguistica** [plouc/nivo#1451]
I am creating a graphic using @nivo/swarmplot. The problem is when I try to create a custom node using renderNode (basically I am trying to use a svg image instead the default node) but I have a typescript error (described below)

I am following the storybook example https://github.com/plouc/nivo/blob/master/packages/swarmplot/stories/SwarmPlotRenderNode.js

When I check in my project the module imported that specific prop does not exist. What I am missing?

### Typescript error
TS2769: No overload matches this call.   Overload 1 of 2, '(props: (CommonSwarmPlotProps<any> & Partial<{ animate: boolean; motionDamping: number; motionStiffness: number; }> & { role?: string | undefined; } & Dimensions) | Readonly<...>): SwarmPlot', gave the following error.     Type '{ width: number; height: number; margin: { top: number; right: number; bottom: number; left: number; }; data: any; groups: any; groupBy: string; identity: string; value: string; valueScale: { type: string; min: number; max: number; }; ... 8 more ...; layout: "horizontal"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<SwarmPlot> & Readonly<CommonSwarmPlotProps<any> & Partial<...> & { ...; } & Dimensions> & Readonly<...>'.       Property 'renderNode' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<SwarmPlot> & Readonly<CommonSwarmPlotProps<any> & Partial<...> & { ...; } & Dimensions> & Readonly<...>'.   Overload 2 of 2, '(props: CommonSwarmPlotProps<any> & Partial<{ animate: boolean; motionDamping: number; motionStiffness: number; }> & { role?: string | undefined; } & Dimensions, context: any): SwarmPlot', gave the following error.     Type '{ width: number; height: number; margin: { top: number; right: number; bottom: number; left: number; }; data: any; groups: any; groupBy: string; identity: string; value: string; valueScale: { type: string; min: number; max: number; }; ... 8 more ...; layout: "horizontal"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<SwarmPlot> & Readonly<CommonSwarmPlotProps<any> & Partial<...> & { ...; } & Dimensions> & Readonly<...>'.       Property 'renderNode' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<SwarmPlot> & Readonly<CommonSwarmPlotProps<any> & Partial<...> & { ...; } & Dimensions> & Readonly<...>'.

**Comment by wyze** [comment]
The property you were using has been renamed from `renderNode` to `circleComponent` in the latest release (v0.71.0). You can find an updated storybook here https://github.com/plouc/nivo/blob/master/packages/swarmplot/stories/SwarmPlotCustomCircle.tsx

**Comment by hatton** [comment]
Could you list breaking changes like this in the changelog please? Thanks!
