### ISSUE TITLE
Place labels above bars on bar charts

### ISSUE THREAD

**Issue by joergd** [plouc/nivo#146]
Instead of the label appearing over a bar on a bar chart, is there a way to adjust the label position so that it is above the bar?

**Comment by joergd** [comment]
This would also help when the bar columns are so short that they no longer get labelled. If the labels could be placed above the bar columns - then at least they can still be labelled and the label ends up in the chart areas as opposed to either not at all or on the x-axis.

**Comment by joergd** [comment]
![test](https://user-images.githubusercontent.com/5681/36042789-ac7e9554-0dd5-11e8-9808-3bbe26f63b6d.png)

The "missing" values are a fraction between 0 and 1 - But I do need them on the graph ...

**Comment by pvjones** [comment]
I also would like to do this.

**Comment by stahlmanDesign** [comment]
Here's how this can be done:
`labelFormat: d => <tspan y={ 0 }>{ d }</tspan>`
![capture d ecran 2018-02-12 a 18 50 14](https://user-images.githubusercontent.com/972804/36126245-b1462230-1025-11e8-9e54-b2bc52ade4bb.png)

**Comment by joergd** [comment]
Ah great - thank you - that worked for me!

Although I now get a warning in my browser:

Warning: Failed prop type: Invalid prop `label` supplied to `BarItem`.

**Comment by pvjones** [comment]
@stahlmanDesign Thanks this looks promising. From what I can tell, `labelFormat` just gets passed the numeric value of the current datum. Is there a way to get the entire datum (including both id and value) so that I can perform a lookup and modify the return based on other context? 

For example, `colorBy` gets an entire datum as its argument. (Personally I think it would be nice if all of the callback functions uniformly received the entire datum so that the user could do whatever they want with the information.)

I tried looking into the component, and it looks like there might be a `getLabel` prop, but it doesn't seem to be doing anything when I pass it a callback.

Thanks for your time!

**Comment by plouc** [comment]
The prop type warning has been fixed by https://github.com/plouc/nivo/commit/4152c0906849aa53ef4fa311aa2a66a16402e9d8

**Comment by plouc** [comment]
I close this issue and will consider https://github.com/plouc/nivo/issues/154 as it could be quite useful.

**Comment by arturtakoev** [comment]
How can I instead put labels to bottom of every bar?

**Comment by germanfleitas** [comment]
> Ah great - thank you - that worked for me!
> 
> Although I now get a warning in my browser:
> 
> ```
> Warning: Failed prop type: Invalid prop `label` supplied to `BarItem`.
> ```

HI, I have the same problem, because `label` expect  a string and not a function.

**Comment by monishagunalan** [comment]
How do you place the label on the right on a horizontal bar chart? how can I get the x value based on the bar width?

> labelFormat: d => <tspan y={ 0 }>{ d }</tspan>

**Comment by qasim-glidewell** [comment]
Also trying to get the labels to format to the right of a horizontal bar chart. Using x and y values but want them to be dynamic.

**Comment by ldmcdaniel** [comment]
Also trying to get a value to feed to x to get the horizontal bar chart values at the end of the bar. It worked brilliantly on the vertical bar chart.

**Comment by Eld0ud** [comment]
Did you try to add a new layer as explained here https://github.com/plouc/nivo/issues/582#issuecomment-499530645 ?

**Comment by trymbill** [comment]
> Here's how this can be done:
> `labelFormat: d => <tspan y={ 0 }>{ d }</tspan>`

Did the output of `labelFormat` not used to be `string | number`? Did this ever work for anyone? With this prop setup ...

```jsx
<BarChart data={chartData} labelFormat={d => <tspan y={0}>{d}</tspan>} />
```

... typescript complains about the output of the `labelFormat` function not being a `string` or `number`, which makes sense since the output of that function is a JSX `Element`. What method are people using to place labels on top of a chart today?

**Comment by stahlmanDesign** [comment]
> Just in case someone else ends up on this issue, this is how I placed the labels on top of each bar:

Very good idea. I don't think [custom bar items](https://nivo.rocks/storybook/?path=/story/bar--custom-bar-item) were supported when I originally answered this question with a tspan in labelFormat. Even if they were, I didn't think of using them this way.

**Comment by pietmichal** [comment]
FYI, @trymbill's solution doesn't support tooltips.

**Comment by bencohen2** [comment]
Did anybody ever manage to get it to work, placing labels at the right of horizontal bars?

**Comment by eggei** [comment]
> Here's how this can be done:
> labelFormat: d => <tspan y={ 0 }>{ d }</tspan>

^^ This **worked** for me but I had to fool the Typescript compiler with this :/
```
labelFormat={
    labelValue => (
        (<tspan y={-8}>{labelValue}</tspan>) as unknown
    ) as string
}
```

**Comment by nibble-4bits** [comment]
> Here's how this can be done:
> `labelFormat: d => <tspan y={ 0 }>{ d }</tspan>`
> ![capture d ecran 2018-02-12 a 18 50 14](https://user-images.githubusercontent.com/972804/36126245-b1462230-1025-11e8-9e54-b2bc52ade4bb.png)

This worked perfectly for me. Thanks!

**Comment by noisysky** [comment]
for horizontal bars:
labelFormat={d => <tspan x={ (d * (width-160) / 100) + ( 5 * (width-160) / 100) }>{ `${d}%` }</tspan>}
where 160 is marginLeft + marginRight,
5 is by how much label should be shifted from the bar
<img width="378" alt="Снимок экрана 2020-09-09 в 15 49 26" src="https://user-images.githubusercontent.com/33125830/92600484-5017e600-f2b4-11ea-952b-e2d31f2bd2bb.png">

**Comment by vgotsuliak** [comment]
@noisysky thanks for your example. How did you get width?

**Comment by tgirgin23** [comment]
`labelFormat` is not longer supported. See https://github.com/plouc/nivo/issues/1735

**Comment by plouc** [comment]
Now the bar chart supports custom layers, so the best way would be to add a custom layers for those labels, a custom layer receives the `bars` property (amongst others) and each bar has the following properties:

```
type ComputedBarDatum<RawDatum> = {
    key: string
    index: number
    data: ComputedDatum<RawDatum>
    x: number
    y: number
    absX: number
    absY: number
    width: number
    height: number
    color: string
    label: string
}
```
So you have the position and dimension of the bar, giving you complete freedom on where and how you want to render the labels.

**Comment by mkusold** [comment]
Here's a custom example for the new format. I'm using a layer to show a label outside of the bar when the bar is too small to contain the label itself. 

Here's the chart example:
![image](https://user-images.githubusercontent.com/5613706/148815592-379af48f-f128-4de1-81f8-244b81eafd4e.png)

Here's the code:
`...
labelSkipWidth={100} // labelSkipWidth = minimum bar size needed for a normal label
layers={[
                        'grid',
                        'axes',
                        'bars',
                        'markers',
                        'legends',
                        'annotations',
                        ({ bars, labelSkipWidth }) => {
                            return (
                                <g>
                                    {bars.map(({ width, height, y, data }) => {
                                        // only show this custom outer label on bars that are too small
                                        return width < labelSkipWidth ? (
                                            <text
                                                transform={`translate(${width + 10}, ${
                                                    y + height / 2
                                                })`}
                                                text-anchor="left"
                                                dominant-baseline="central">{`${
                                                data.id ?? ''
                                            }`}</text>
                                        ) : null;
                                    })}
                                </g>
                            );
                        },
                    ]}`

**Comment by abdulwahab13** [comment]
> for horizontal bars: labelFormat={d => <tspan x={ (d + 5) * ((width-160) / 100) }>{ `${d}%` }} where 160 is marginLeft + marginRight, 5 is by how much label should be shifted from the bar <img alt="Снимок экрана 2020-09-09 в 15 49 26" width="378" src="https://user-images.githubusercontent.com/33125830/92600484-5017e600-f2b4-11ea-952b-e2d31f2bd2bb.png">

@noisysky Hello, Please Can you tell us how you get the Width?

**Comment by wonsuc** [comment]
How is this possible with stacked bar chart? I need a special sum value of whole stacked values above each bars.

**Comment by hkellock** [comment]
Building on @trymbill's [comment](https://github.com/plouc/nivo/issues/146#issuecomment-576839073) and @mkusold's [comment](https://github.com/plouc/nivo/issues/146#issuecomment-1009184119) I came up with this solution to the original problem of placing the labels above bars on bar charts:

Bar component configuration:
```
<ResponsiveBar
  ...
  layers={['grid', 'axes', 'bars', BarLabels, ...]} // unlike @trymbill I just use the original bars and add the bar labels in a separate layer like @mkusold
  enableLabel={false} // disable labels in the original bars
/>
```
BarLabels.tsx:
```
import type { BarDatum, ComputedBarDatum } from '@nivo/bar';

const BAR_VALUE_PADDING = 5;

type Props = {
  bars: ComputedBarDatum<BarDatum>[];
};

export function BarLabels({ bars }: Props) {
  return (
    <g>
      {bars.map(({ width, x, y, data: { formattedValue } }) => (
        <text key={`${x}.${y}`} x={x + width / 2} y={y - BAR_VALUE_PADDING} textAnchor="middle">
          {formattedValue}
        </text>
      ))}
    </g>
  );
}

```

---

To answer @wonsuc's concern, I would add the sum values to the props when calling BarLabels and then just replace the formattedValue with the correct sum value from the component props. You would also need some logic to match the correct sum value with the correct bar. There are many ways to do that and they probably depend on the format you have your data in.
