### ISSUE TITLE
Bug in layers: series order changes during the rendering

### ISSUE THREAD

**Issue by Deliaz** [plouc/nivo#1463]
Issue Demo: https://codesandbox.io/s/nivo-line-graph-component-forked-nn322?file=/src/index.js
Version: 0.67.0

The example above shows a possible bug with the order of `series` items in custom layer props. 

The order in the sync phase is reversed from what we get at the end of rendering (next cycle of event loop). 

```js
...
layers={[
    "grid",
    "markers",
    "axes",
    "areas",
    (props) => {
      // Let's log first element from series
  
      // sync log
      console.log(props.series[0].id); // logs: japan
  
      // next loop log
      setTimeout(() => {
        console.log(props.series[0].id); // logs: norway
      }, 0);
  
      return null;
    },
    ...
]}
...
```

**Comment by Deliaz** [comment]
This bug also breaks the official custom layer example:
https://nivo.rocks/storybook/?path=/story/line--custom-layers
Hover over the chart to see how it changes.

**Comment by TomasB** [comment]
@wyze  while it fixes the official example and the provided sample, it seems that there is still some gap somewhere.. We are reproducing the issue in our code, and I'm still looking what exactly causes that behaviour
