### ISSUE TITLE
BoxLegendSvg throws "Cannot read property 'legends' of undefined"

### ISSUE THREAD

**Issue by timiles** [plouc/nivo#1464]
**Describe/explain the bug**
When rendering `<BoxLegendSvg>`, the `theme` returned from `useTheme()` in LegendSvgItem.js appears to be undefined.

**To Reproduce**
Demo here: https://codesandbox.io/s/material-demo-forked-h2g36?file=/Legends.js

(Apologies that there is superfluous code in this sandbox - I forked it from another demo where BoxLegendSvg was working with `@nivo/legends@0.52.0`. I have updated the packages to the latest, and the error is thrown. It is very possible that the code in the demo is wrong, I can't find any up to date examples or documentation of using Legends.)

The demo throws error on running.

**Expected behavior**
I believe `useTheme()` should be resorting to a default theme?

I wanted to wrap my component in a `<ThemeProvider>` but this is no longer exported from `@nivo/core@0.67.0` typings (this might have been removed in error, as it appears to be exported in the javascript still?). The `theme` property on `<BoxLegendSvg>` does appear to have been intentionally removed. Finally, I tried to play with `usePartialTheme`, but I'm not sure I was using this right as I can't find any documentation for this either.

UPDATE: Using `<ThemeProvider>` does fix this problem, if I add a workaround to add it to the typings. But from what I've read, I believe `useTheme()` should return a default theme if ThemeProvider is not used. Is this the case?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 89.0.774.63 (Official build) (64-bit)

**Comment by wyze** [comment]
Yes, you should use the `ThemeProvider` and pass a theme to it. I'll accept a PR that adds the component to the typings.
