### ISSUE TITLE
Add Radial Labels to Sunburst Charts

### ISSUE THREAD

**Issue by i-am-zach** [plouc/nivo#1465]
**Is your feature request related to a problem? Please describe.**
I'm graphing data on a project with a sunburst chart and I'd like to display the category title and percentage on a sunburst graph but there is no good way to accomplish this.

**Describe the solution you'd like**
I'd like to be able to use a `radialLabel` property on the sunburst chart to acheive something like this. There already seems to be functionality like this on the Nivo Pie Chart.
![sunburst-grades](https://user-images.githubusercontent.com/53406696/113497169-e7e65700-94c6-11eb-935b-62031989a3db.JPG)

**Describe alternatives you've considered**
I've tried adding my own custom labels using `text` and `tspan` but that feels much more tedious than it needs to be because the `radialLabel` prop on the pie chart would be nearly identical to that of the sunburst chart.

**Additional context**
Example of radial label on pie chart.
![pie-chart](https://user-images.githubusercontent.com/53406696/113497150-9d64da80-94c6-11eb-9721-3aebcd2070eb.JPG)

**Comment by wyze** [comment]
We have support for this now. You can use the `enableArcLabels` and `arcLabel*` properties to accomplish this. You can play with the properties on the website: https://nivo.rocks/sunburst/
