### ISSUE TITLE
Critical issue with Line/Responsive line causing major slowdown and crashes on rerender

### ISSUE THREAD

**Issue by mattoni** [plouc/nivo#1468]
**Thanks for using nivo**

**Describe/explain the bug**
There is a critical issue where rerendering line charts (at least, that's the one that I've tested) leads to some kind of memory leak with react-spring. In my larger project, this happens after one rerender, but I've managed to reproduce a state change every 5s in the sandbox. By the 24th-30th rerender, you start to notice some lag. By 50, it's pretty choppy. Eventually this crashes my browser tab on my main app.

**To Reproduce**
https://codesandbox.io/s/nivoline-chart-bottom-tick-values-forked-k9bt6?file=/src/index.js

1. Go to the code sandbox above
2. Open the console
3. Watch the rerenders happen, and move the tooltip around. Note: this happens with or without the tooltip, but it's easy to see the performance issues this way.
4. Notice lag around 30th rerender. 

**Expected behavior**
Performance should not be affected by reasonable rerenders. My app is affected by 1 rerender with 3 charts similar to the one in the sandbox present.

**Screenshots**
I say it's an issue with react-spring due to the sheer massive volume of promise callbacks referencing useTransition in the performance benchmarking.
![image](https://user-images.githubusercontent.com/5110855/113904637-1d20cc80-9787-11eb-8241-589918821c52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 
 - Version 87.0 (64-bit)

**Additional context**
There have been a few notable issues with the latest version of react-spring.

**Comment by wyze** [comment]
Fixed by #1408.
