### ISSUE TITLE
Skip labelling every few ticks on the x-axis

### ISSUE THREAD

**Issue by joergd** [plouc/nivo#147]
On a line chart - when I have a lot of x values, I don't want to show every tick on the x axis. I couldn't find a way to skip say every 2nd or 3rd one.

    axisBottom={{
      "orient": "bottom",
      "tickSize": 0,
      "tickPadding": 5,
      "tickRotation": -45,
      "format": (x, index) => { return x }
    }}

I tried the format field - but the function only gets the x value - it would be nice if it also got the index? Is there another way?

**Comment by pvjones** [comment]
I believe tickCount or tickValues may be what you're looking for? See these examples: 
```<Bar
      margin={{ top: 10, right: 10, bottom: 60, left: 60 }}
      maxValue={100}
      axisLeft={{ tickValues: [0, 25, 50, 100], format: v => 32 }}
      width={600}
      height={400}
      data={data}
      labelFormat=".2s"
    />
    <Bar
      margin={{ top: 10, right: 10, bottom: 60, left: 60 }}
      maxValue={100}
      axisLeft={{ tickCount: 2 }}
      axisBottom={{ tickCount: 1 }}
      width={600}
      height={400}
      data={data}
    />
```

**Comment by joergd** [comment]
Hmm no - that's not it - tried it on both the line and bar chart but made no difference ...

**Comment by joergd** [comment]
Correction: So the `tickCount` made no difference, but setting an array of `tickValues` does change the tick labels.

**Comment by plouc** [comment]
@joergd, is it OK now?

**Comment by joergd** [comment]
Yes thank you it's fine now. `tickCount` had no effect, so I had to write my own function to set `tickValues` instead to an array of values.

**Comment by BrunoQuaresma** [comment]
`tickCount` didn't work for me.

**Comment by stahlmanDesign** [comment]
@joergd @plouc Providing your own `tickValues` array where you intentionally use empty strings every other index causes a React render warning that two children have the same key (empty string).

Seems Nivo is using the x axis value as a unique key.

This is also a problem when the key happens to be the same, such as a date where you trim the time of day.

**Comment by ymenase** [comment]
> Yes thank you it's fine now. `tickCount` had no effect, so I had to write my own function to set `tickValues` instead to an array of values.

hey, i am trying to do this now. Any ideas? I know this is old.

**Comment by shubhamjagdale97** [comment]
Responsive bar chart showing only first value from tickValues array on x axis specified in axis bottom. I am using date in 1 month for example and specified four dates in array but its showing only first one on x axis

**Comment by smiksiukhpe** [comment]
same for me

**Comment by KTruong008** [comment]
Dynamically setting `tickValues` worked for me:

```
const xScaleTickValues =
    dateRange === DATE_RANGE.LAST_90_DAYS
      ? lineData.map(
          (datum: Record<string, number>, index: number) => {
            return index % 10 === 0 ? datum.x : ''";
          },
        )
      : 'auto';
      
 ...
 
 axisBottom={{
      tickValues: xScaleTickValues,
    }}
```

**Comment by jpamorgan** [comment]
This approach worked for me: https://github.com/plouc/nivo/issues/524#issuecomment-628296620
