### ISSUE TITLE
Update dependency of @nivo for react-spring to 9.1.0

### ISSUE THREAD

**Issue by prueker** [plouc/nivo#1472]
**Describe/explain the bug**
react-spring package 9.0.0-rc.3 is dead so npm install breaks on @nivo/core (and the other packages) as they hard depend on the now defunct RC package.

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.8.x" from react-konva@16.8.6
npm ERR! node_modules/@nivo/core/node_modules/react-konva
npm ERR!   peer react-konva@">=16.8" from @react-spring/konva@9.0.0-rc.3
npm ERR!   node_modules/@nivo/core/node_modules/@react-spring/konva
npm ERR!     @react-spring/konva@"9.0.0-rc.3" from react-spring@9.0.0-rc.3
npm ERR!     node_modules/@nivo/core/node_modules/react-spring
npm ERR!       react-spring@"9.0.0-rc.3" from @nivo/core@0.67.0
npm ERR!       node_modules/@nivo/core
```
**To Reproduce**
npm install @nivo/core

**Expected behavior**
A released package should not have a hard dependency on a RC package.
Update to https://www.npmjs.com/package/react-spring/v/9.1.0

**Comment by prueker** [comment]
Actually it might be related to this https://github.com/plouc/nivo/issues/1462

**Comment by arseniosiani** [comment]
+1

**Comment by TrevorMcDougald** [comment]
I think the issue is unrelated. I'm getting the error with npm version 6.14.10. I think upgrading to version 6 resolved the previous issue.

My company has a proxy around NPM that only releases stable packages. They won't release react-spring 9.0.0-rc.3.
