### ISSUE TITLE
Localisation support

### ISSUE THREAD

**Issue by bladerunner2020** [plouc/nivo#1474]
I believe many of us need better support for localisation:
- specify what should be the first day of the week: Sunday or Monday
- date format for tooltip
- name of months
- etc.

Some of these things could be done easily without any changes in Nivo. Thus the custom name of months could be implemented with adding **monthLegend**, but I didn't find how to specify first day of the week. There was a similar request #264 and even a PR #613, but they both were closed on inactivity...

Any way to set first day of week?

**Comment by AntoineArt** [comment]
bump
