### ISSUE TITLE
Progress circular bar chart

### ISSUE THREAD

**Issue by iurylippo** [plouc/nivo#1482]
It's possible to accomplish this with a nivo chart?

![image](https://user-images.githubusercontent.com/35785386/114927654-17bb2600-9e08-11eb-8469-02177792f152.png)

**Comment by plouc** [comment]
Yes, you can use a pie chart with 2 values, `[21, 79]` and adjust the colors accordingly, for the value in the center, the repo contains [an example on how to achieve it](https://github.com/plouc/nivo/blob/master/packages/pie/stories/pie.stories.tsx#L134), but will only be released in 1/2 weeks I think.

**Comment by coooraph** [comment]
Actually, thanks to @wyze, we have a new release, so you should be able to implement this now.

**Comment by Durga1973** [comment]
Can you provide any example for the above graph, if we give two values it shows the sum of those two values in the radial label. How to show the Pie chart with one value which is progress

**Comment by pbldmngz** [comment]
Not too fancy but I used this code for a project of mine. I just replaced some values to make it obvious.
It creates a circular bar chart (or donut, as I like to call it) with a percentage in the center.
```jsx
<PieChart
 height={"32vh"}
 data={[
 {
  order: 0,
  id: "bad",
  label: "bad",
  value: 226,
  },
 {
  order: 0,
  id: "ok",
  label: "ok",
  value: 474,
  },
 ]}
 innerText={100 - (percentage * 100).toFixed(1) + "%"}
 colors={{ bad: "#FF4E4E", ok: "#7BCAFF" }}
 radius={0.5}
 enableLabels={false}
/>
```
