### ISSUE TITLE
useMesh on ScatterPlotCanvas

### ISSUE THREAD

**Issue by chynamyerz** [plouc/nivo#1487]
Hi

I want to have a tooltip only appearing when hovering on the actual data point not any wherelse.

With ScatterPlot (SVG) works but I want the same behaivior when using Canvas. 

Passing "useMesh={false}" seems to have no effect.

Am I missing something here?

**Comment by jlaguma** [comment]
I have the same issue.
ScatterPlot - tooltip appears only on a data point with useMesh=false option.
ScatterPlotCanvas - useMesh has no effect and tooltip appears everywhere on the chart.
ResponsiveScatterPlotCanvas - useMesh has no effect and tooltip appears everywhere on the chart.

Really need tooltips to work correctly on Canvas charts as we have lots of data points.

Is it possible?

**Comment by m-podlesny** [comment]
I was facing this issue on the `<ResponsiveLineCanvas />` as well.
The workaround is on the parent/wrapper (e.g. `<div>`):
```tsx
style={{ userSelect: 'none', pointerEvents: 'none' }}
```
