### ISSUE TITLE
Component @nivo/circle-packing has issue with typescript

### ISSUE THREAD

**Issue by VitaliyN** [plouc/nivo#1491]
I have issue with  component @nivo/circle-packing in my solution.
Details:
 React with TypeScript
 dependencies: {
    "@nivo/circle-packing": "^0.68.0",
    "@nivo/core": "^0.68.0"
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.2",
      ...
  }

Error message: 
TypeScript error in /src/pages/demo/demo.tsx(3,34):
Could not find a declaration file for module '@nivo/circle-packing'. '`/node_modules/@nivo/circle-packing/dist/nivo-circle-packing.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nivo__circle-packing` if it exists or add a new declaration (.d.ts) file containing `declare module '@nivo/circle-packing';`  TS7016

Can you adding support of  typescript for @nivo/circle-packing component?

**Comment by wyze** [comment]
Duplicate #1228. There is a closed PR that I will try to revive that looks complete, #1360.
