### ISSUE TITLE
Custom Set of Colors inside style's color option

### ISSUE THREAD

**Issue by pranjalsuyal** [plouc/nivo#1498]
Hey I am trying to use nivo in my project but I wanted to use my own set of custom colors inside style's color option. But I am not able to do so. Does anyone has any idea as to how to achieve this ?
Any help would be highly appreciated.

I have tried appending the color object obtained from nivo/colors with my own set of custom colors but it generates many errors possibly because of it being used in other components also

**Comment by wyze** [comment]
It would be helpful to provide the code you tried, even more helpful if you were able to provide a CodeSandbox. Most charts, if not all, have a `colors` prop you can use. See the website for your specific chart's documentation. https://nivo.rocks/
