### ISSUE TITLE
Stacked line graphs with areaOpacity=1 do not show all colors

### ISSUE THREAD

**Issue by niharikasingh** [plouc/nivo#150]
When I create a `ResponsiveLine` graph with `stacked=true`, `enableArea=true`, and `areaOpacity=1`, the graph fills in with only one color instead of showing all colors (see below). 

![screen shot 2018-02-10 at 8 57 21 pm](https://user-images.githubusercontent.com/3387590/36068509-560dfdc4-0ea5-11e8-9bdd-ed8a9f5e4473.png)

I think a potential fix may be in `nivo-line/src/LineAreas.js`. When I change both occurrences of `lines.map(function ...` to `lines.slice(0).reverse().map(function ...`, I see the following:

![screen shot 2018-02-10 at 9 01 18 pm](https://user-images.githubusercontent.com/3387590/36068521-920fcd52-0ea5-11e8-9be5-80e3c55028a4.png)

If this is an acceptable way to solve this issue, I can submit a pull request with the fix.

**Comment by plouc** [comment]
@niharikasingh, your fix seems fine :)

**Comment by plouc** [comment]
fixed by https://github.com/plouc/nivo/pull/152
