### ISSUE TITLE
Missing peer dependencies from multi target react-spring

### ISSUE THREAD

**Issue by nikolaik** [plouc/nivo#1505]
**Describe/explain the bug**
After upgrading the `react-spring` dependency in https://github.com/plouc/nivo/pull/1480 we now get warnings on missing peer dependencies. Does nivo support any other target than web? If not, could we simple switch to `@react-spring/web` ?

```
npm WARN @react-spring/konva@9.1.2 requires a peer of konva@>=2.6 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/konva@9.1.2 requires a peer of react-konva@>=16.8 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/native@9.1.2 requires a peer of react-native@>=0.58 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/three@9.1.2 requires a peer of @react-three/fiber@>=6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/three@9.1.2 requires a peer of three@>=0.126 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/zdog@9.1.2 requires a peer of react-zdog@>=1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/zdog@9.1.2 requires a peer of zdog@>=1.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**

1.  `npm i @nivo/core@0.69.1`
2. Check terminal output

**Expected behavior**

No warnings about peer dependencies

**Comment by wyze** [comment]
> Does nivo support any other target than web?

No we don't.

> If not, could we simple switch to @react-spring/web ?

Possibly? If it gets rid of the peer dependencies warnings from react-spring and keeps the same functionality, it is worth a shot.

**Comment by nikolaik** [comment]
> > If not, could we simple switch to @react-spring/web ?
> 
> Possibly? If it gets rid of the peer dependencies warnings from react-spring and keeps the same functionality, it is worth a shot.

Gave it a shot 🤞

**Comment by carlosprietobarron** [comment]
Hello, do you think this problem will be solved any time soon?
