### ISSUE TITLE
Pie v0.69.0 Axes types are wrong

### ISSUE THREAD

**Issue by IronSean** [plouc/nivo#1506]
**Describe/explain the bug**
In @nivo/pie@v0.69.0 you get this error if you use the enableRadialLabels prop:
`Property 'enableRadialLabels' does not exist on type 'IntrinsicAttributes & Pick<PieSvgProps<{ id: string; label: string; value: number; }>, "data" | "animate" | "defs" | "arcLabel" | "arcLabelsRadiusOffset" | ... 44 more ... | "arcLinkLabelComponent">'`

I suspect that the axes type fixes in 0.69.1 haven't been released for the Pie library since it's still on 0.69.0.

**Expected behavior**
The prop should work and not cause typescript errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (but irrelevant, build time error)
 - Version v0.69.0

**Comment by wyze** [comment]
That prop no longer exists for Pie. You should use `enableArcLinkLabels` instead.

**Comment by IronSean** [comment]
I also just found that
 enableRadialLabels={false}
 enableSliceLabels={false}
 
were replaced with enableArcLinkLabels and enableArcLabels. Just couldn't find any reference to these changes in the release changelogs.

**Comment by wyze** [comment]
Yeah it was hidden under `use arcs package` commit. Something along those lines.
