### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by cedmax** [plouc/nivo#151]
Hello, 
I might be wrong, but it looks like Nivo is importing the whole lodash-es in the bundle to use only a tiny subset of it. 

According to WebPackBundleAnalyzerPlugin the size of lodash-es exceeds the one of Nivo itself.
Is there any chance you would consider optimising the imports to include only the needed parts?

This is the screenshot from the webpack plugin with the responsive line example from your website
<img width="1192" alt="screenshot 2018-02-13 17 13 13" src="https://user-images.githubusercontent.com/415593/36163643-de9334f0-10e1-11e8-8ed0-1fdbb109be6a.png">

**Comment by marcosfede** [comment]
Is there any update on this?  The size of the imported javascript is very large, and you also download it multiple times if you are going to use a different type of graph

![image](https://user-images.githubusercontent.com/16232610/38647106-00f7b4c4-3dc1-11e8-9c6b-1906f12c08f3.png)

those two bundles correspond to the @nivo/line and @nivo/bar modules, which are not sharing common code

**Comment by marcosfede** [comment]
I'd like to help solving this. Could you point me in a general direction of what needs to be done?

**Comment by plouc** [comment]
Moved to rollup & use now use scoped imports (`@nivo/<package>@0.35.2+`).

**Comment by cedmax** [comment]
Thanks, sir :)
