### ISSUE TITLE
New typedefinition for ResponsiveLine's Layers prop is not correct

### ISSUE THREAD

**Issue by jauco** [plouc/nivo#1515]
In #1499 the linegenerator property in the CustomLayerProps interface was changed from a function that accepts an array of `Datum` (i.e. `{x: number y: number}`) to a function that accepts an array of `[number, number]` However the implementation at  https://github.com/plouc/nivo/blob/ce7c755b23cfc55ead9bac9920a55ef6e764bd99/packages/line/src/hooks.js#L20-L22 still extracts the x and y property instead of the first and second item of an array.

I'm guessing this was an accidental change and linegenerator should be `D3Line<Datum>`? Or did I read the code wrong?

**Comment by wyze** [comment]
Yup looks like it. Should be a quick fix. Also we should add the @types/d3-shape as well.
