### ISSUE TITLE
Is it possible to render legends in Nivo SSR api?

### ISSUE THREAD

**Issue by kkcy** [plouc/nivo#1516]
Thanks for the great chart library!

I've been using Nivo API to generate charts to PDF via puppeteer, but adding legends doesn't seem to work. 
Are legends supported under Nivo API?

**Comment by plouc** [comment]
Legends should work with puppeteer as I guess you're taking screenshots of the charts, if you have a look at the screenshots generated for each package README (also using puppeteer), you can see that legends are there, for example https://github.com/plouc/nivo/blob/master/packages/bar/doc/bar.png.

**Comment by wyze** [comment]
Going to close this as plouc already answered the question and we are doing it in the project when adding a new chart as well.
