### ISSUE TITLE
Line Chart With XAxis Padding

### ISSUE THREAD

**Issue by levnikan** [plouc/nivo#1525]
**Is your feature request related to a problem? Please describe.**
Since my date ticks can be long, they go beyond the chart (grid) borders and make elements vertical alignment inconsistent.
![image](https://user-images.githubusercontent.com/41207896/118624843-cff23a80-b7c9-11eb-92b6-4ed79df7cb59.png)

**Describe the solution you'd like**
I would like to be able to squeeze the line element without squeezing the grid by setting XAxis padding like in [here](https://recharts.org/en-US/examples/LineChartWithXAxisPading). This would help me to have all my XAxis ticks be within the grid box.

**Describe alternatives you've considered**
Extend xScale functionality

Since I have a lot code dependent on Nivo, I would like to stick to it.

**Comment by Gungrave223** [comment]
I'd second this.

**Comment by TetianaMulenko** [comment]
bump

**Comment by levnikan** [comment]
bump

**Comment by reasley-com** [comment]
Has the problem been resolved?

**Comment by ASchwad** [comment]
I dont think so... bump

**Comment by abhishekdev2024** [comment]
bump
