### ISSUE TITLE
[Question] How to plot a more expressive middle line in the grid?

### ISSUE THREAD

**Issue by Streeterxs** [plouc/nivo#1526]
### Overview
Hello, I want to plot a more expressive middle line in my swarmplot graph.

Today our graph has a simple grid.

How do I customize a grid?

### Screenshots
In this pic I want to make the '5' middle line in the grid more expressive than the others
![image](https://user-images.githubusercontent.com/41974719/118666889-e6989180-b7c9-11eb-8d9d-5afe3584f12a.png)

**Comment by wyze** [comment]
@Streeterxs Swarmplot supports custom layers so you can use `layers` prop to add a new layer to do whatever you'd like.

**Comment by Streeterxs** [comment]
Thank you! I will try it
