### ISSUE TITLE
ResponsivePieCanvas accepts radialLabel in code, but in the docs the correct is arcLabel... Is it a version problem or an inconsistency on nivo?

### ISSUE THREAD

**Issue by Budelon** [plouc/nivo#1527]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wyze** [comment]
The website reflects the latest version. `radialLabel` was renamed to `arcLabel` in https://github.com/plouc/nivo/releases/tag/v0.68.0.

**Comment by Budelon** [comment]
> The website reflects the latest version. `radialLabel` was renamed to `arcLabel` in https://github.com/plouc/nivo/releases/tag/v0.68.0.

Thank you @wyze! What should be the best documentation option if i want to remain using and old version?

**Comment by wyze** [comment]
Here you go: https://kh4ex.sse.codesandbox.io/

What I did to get there was go to the tag on GitHub (https://github.com/plouc/nivo/tree/v0.67.0), then go into the website folder. Copy the URL and go to CodeSandbox, create a new sandbox, Choose `Import Project`, and paste the URL in there. Wait a few minutes and you should be up and running!

**Comment by Budelon** [comment]
Thank you! Amazing solution, i'll continue as outlined!
