### ISSUE TITLE
How to use useTooltip hook and showTooltipFromEvent ?

### ISSUE THREAD

**Issue by olgakozich** [plouc/nivo#1528]
Hi! Could provide some examples how to use a showTooltipFromEvent or showTooltipAt function?
Any ways how to show tooltip from CustomLayer event?

**Comment by wyze** [comment]
Here you go https://codesandbox.io/s/pedantic-faraday-0n7cg?file=/src/App.tsx. If you mouse over the center metric, you will see the tooltip.

**Comment by olgakozich** [comment]
> Here you go https://codesandbox.io/s/pedantic-faraday-0n7cg?file=/src/App.tsx. If you mouse over the center metric, you will see the tooltip.

@wyze Thank you for your help! I need to add tooltip to Bar chart. I added a bar chart similar to your code, but the tooltip is not displayed. Could you take a look?
https://codesandbox.io/s/amazing-nobel-blkx1?file=/src/App.tsx

**Comment by wyze** [comment]
They get passed to the layer as props. https://codesandbox.io/s/bold-jennings-1d6y3?file=/src/App.tsx

Bar is still on an older pattern and hasn't been migrated over yet.

**Comment by olgakozich** [comment]
> They get passed to the layer as props. https://codesandbox.io/s/bold-jennings-1d6y3?file=/src/App.tsx
> 
> Bar is still on an older pattern and hasn't been migrated over yet.

@wyze Thanks a lot! It works, you made my day 👍

**Comment by wyze** [comment]
Awesome, glad I was able to help!
