### ISSUE TITLE
Failed prop type warning for legends and labels when valid markup used

### ISSUE THREAD

**Issue by stahlmanDesign** [plouc/nivo#153]
I use styled text in my legends and labels like this:
```
axisBottom: {
        legend: <tspan>
          <tspan>{ 'Some text' } </tspan>
          <tspan style={{ fontWeight: 900, fill: 'red' }}>{ '  bold and red ' } </tspan>
          <tspan>{ ' more text' } </tspan>
        </tspan>
}
```
`tspan` is supported as a child of the svg `text` element, so this renders just fine.
However, Nivo throws an error:
```
Error: Invalid prop `bottom.legend` of type `object` supplied to `Axes`, expected `string`.
```

Adding `object` in additon to `string` would also remove the PropType warning here https://github.com/plouc/nivo/issues/146 when using `tspan` to change label position on a bar

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/commit/4152c0906849aa53ef4fa311aa2a66a16402e9d8
