### ISSUE TITLE
Tooltip not working in heatmap v0.70

### ISSUE THREAD

**Issue by Luiz-Fellipe** [plouc/nivo#1543]
Hello, I'm using the new version (0.70) and when copying the example of the implementation of the heatmap graph, I realized that the tooltips don't work. when I returned my version to 0.69.1 the error was corrected.

**Comment by wyze** [comment]
Did you ensure all @nivo packages were upgraded to the same version?

**Comment by Luiz-Fellipe** [comment]
@wyze I checked and my 'nivo / core' package was a version back. Maybe that's why it didn't work, but as I have other graphics already implemented I will keep version 0.69 Thanks!

**Comment by wyze** [comment]
Sounds good, thanks!
