### ISSUE TITLE
Candlestick Graph

### ISSUE THREAD

**Issue by psongpin** [plouc/nivo#155]
Hello I just wonder how can I make candlestick graphs with this library?

**Comment by suminb** [comment]
I was able to find an *aftermarket* candlestick chart made with [React-Vis](https://uber.github.io/react-vis/). Would something like this be possible with nivo? 

Candlestick chart example (React-Vis): https://codesandbox.io/s/zl8wqj6743?from-embed

**Comment by mishelen** [comment]
Hey! You guys are doing really cool stuff! 
I really want the same cool candlestick chart from you guys!
