### ISSUE TITLE
LegendProps type requires data prop

### ISSUE THREAD

**Issue by IronSean** [plouc/nivo#1553]
**Describe/explain the bug**
The LegendProps type in the new Nive 0.70.0 versions include a property for `data` which is required but not documented on either the Pie chart page or the legend docs page.

**To Reproduce**
https://codesandbox.io/s/nivopie-typescript-forked-xsrf6?file=/src/index.tsx

1. Import a Pie or ResponsivePie
2. Copy config from the nivo pages or elsewhere including Legend
3. See typeerror for missing data property on LegendProps

**Expected behavior**
If this property is optional, the type would make it optional

**Screenshots**
![image](https://user-images.githubusercontent.com/1960190/119868207-24e22f00-bef5-11eb-9ea8-65f754fc2570.png)

**Desktop (please complete the following information):**
N/A, build time

**Comment by wyze** [comment]
Thanks for the report! This was fixed via #1545.

**Comment by IronSean** [comment]
Sorry, I did a search but may have only searched open issues and not seen the closed issues relating to this. My bad!

**Comment by wyze** [comment]
> Sorry, I did a search but may have only searched open issues and not seen the closed issues relating to this. My bad!

Not a problem. It should have been filed as a bug, but was left as a review comment on a PR! Anyways, about to cut a release to release quite a few fixes.
