### ISSUE TITLE
Line tooltip dissapeared in the latest version

### ISSUE THREAD

**Issue by rogerfn** [plouc/nivo#1557]
Hi,

The tooltip has dissapeared in the latest version. I'm copying and pasting the code from https://nivo.rocks/line/. 

Version 0.70.0 works fine

Cheers,

**Comment by wyze** [comment]
@rogerfn please ensure all nivo packages are on the same version. You have to upgrade them all at the same time.

**Comment by rogerfn** [comment]
@wyze  I actually started with the latest version (first time using this package, excellent work btw). The tooltip only appeared when downgrading to the mentioned version

**Comment by wyze** [comment]
I've put together a codesandbox by coping and pasting the code from the website https://codesandbox.io/s/quizzical-noyce-q8vhd?file=/src/App.tsx, it is working for me.
