### ISSUE TITLE
Colors from data not being displayed in Nivo ResponsiveHeatMap

### ISSUE THREAD

**Issue by gpalrepo** [plouc/nivo#1559]
Suppose I am inputting the following data into my ResponsiveHeatMap
```
const data = [
    {
      resultID: 'shopping',
      accepted: 2,
      acceptedColor: 'hsl(130,72%,65%)',
      exception: 0,
      exceptionColor: 'hsl(72,72%,44%)'
    }
    .
    .
    .
  ]
```
I am currently passing the following into the colors prop and it's not working.

```
  colors={({mapData}) => {
       return mapData.data[`${mapData.id}Color`]
  }}
```
I have checked out the following issues but they appear ResponsiveBar specific and aren't useful for Responsive Heatmaps
#581 
#1417

**Comment by wyze** [comment]
You need to process your colors to an array first and then pass it to colors property. See https://codesandbox.io/s/long-cherry-prbfw?file=/src/charts/HeatMap.tsx

```ts
const keys = [ ... ]
const props = { keys, ... }

function MyHeatMap({ data }) {
  const colors = props.keys.map(key => data[0][`${key}Color`]) as string[]

  return <HeatMap colors={colors} data={data} {...props} />
}
```

**Comment by gpalrepo** [comment]
Thanks. This is useful. 

It appears that in the background, the package is calculating the colors to display. Suppose, instead, one has done the calculations and has specific colors in mind for each cell, how can they display these colors overriding the programs' calculations: 
```
    {
      resultID: 'result01',
      accepted: 2,
      acceptedColor: 'hsl(130,72%,65%)',
      exception: 1,
      exceptionColor: 'hsl(72,72%,44%)'
    },
    {
      resultID: 'result02',
      accepted: 1,
      acceptedColor: 'hsl(130,72%,55%)',
      exception: 1,
      exceptionColor: 'hsl(72,72%,60%)'
    },
```

**Comment by wyze** [comment]
Can you show a full example of the code you are trying and we should be able to get it to work?

**Comment by gpalrepo** [comment]
Awesome. Here's the Codesandbox link: https://codesandbox.io/s/custom-heatmap-color-for-each-cell-uee2p?file=/src/App.js

**Comment by wyze** [comment]
I see, the problem is we still run it through a quantizeScale function and just use the colors value as the range of colors. Here I provided a mock scale function to return the colors in the order they appear in the data.

https://codesandbox.io/s/custom-heatmap-color-for-each-cell-forked-jo163?file=/src/Heatmap.js
