### ISSUE TITLE
Legends (LegendPropShape) -- No Exported Member (error TS2694)

### ISSUE THREAD

**Issue by SProst** [plouc/nivo#1567]
**Describe/explain the bug**
The version used to produce this bug is 0.70.1. The NPM package csstype does not contain a member called AnimationIterationCountProperty. This causes issues when running the tsc. This is affecting the LegendPropShape type (props.d.ts)

`data: PropTypes.Requireable<(PropTypes.InferProps<{
        id: PropTypes.Validator<import("csstype").AnimationIterationCountProperty>;
        label: PropTypes.Validator<import("csstype").AnimationIterationCountProperty>;
        color: PropTypes.Requireable<string>;
        fill: PropTypes.Requireable<string>;
    }> | null)[]>;`

**To Reproduce**
Use the LegendPropShape type and attempt to run tsc --emitDeclarationOnly. This will result in a tsc error.
https://codesandbox.io/s/missing-cssimport-r1cxp?file=/package.json

1. Use legends in a plot, such as a bar plot
2. Execute tsc --emitDeclarationOnly

**Expected behavior**
Running tsc --emitDeclarationOnly does not cause this error.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A (this is a type bug, not runtime bug)
 - Version N/A (this is a type bug, not runtime bug)

**Additional context**
N/A

**Comment by wyze** [comment]
Can you reproduce this in a codesandbox? I am not 100% sure where the error is coming from. It is working fine here: https://codesandbox.io/s/blue-fog-51105?file=/src/App.tsx

**Comment by SProst** [comment]
![Image 6-2-21 at 3 19 PM](https://user-images.githubusercontent.com/771219/120559797-87847080-c3b6-11eb-8c36-cd757fb7ea6c.png)

Still working on reproducing this in a codesandbox.

**Comment by SProst** [comment]
It appears that as long as `"skipLibCheck": true` is set in the tsconfig, the issue doesn't surface.

**Comment by thomassuckow** [comment]
https://codesandbox.io/s/missing-cssimport-r1cxp?file=/package.json

codesandbox doesn't want to show the error itself so screenshot:
![image](https://user-images.githubusercontent.com/3100037/120562755-e7314a80-c3bb-11eb-8e93-1340f51a75e0.png)

**Comment by wyze** [comment]
I see that in the generated output. I'll see if there is something we can do to change it.
