### ISSUE TITLE
Sizing problems, getting TypeError: Cannot convert undefined or null to object with d3-shape

### ISSUE THREAD

**Issue by haywirez** [plouc/nivo#157]
Banging my head for a while here with trying to get the charts to work 😢
Whether I give the `<ResponsiveStream/>` a parent div with both a height and a width, my app doesn't render and I get `TypeError: Cannot convert undefined or null to object` with d3-shape  in `/d3-shape/src/stack.js:41`:
```
stack.keys = function(_) {
 return arguments.length ? (keys = typeof _ === "function" ? _ : constant(slice.call(_)), stack) : keys;
 };
```
 
The previous stack call is in nivo's `stream/es/enhance.js:67`
```
d3Stack().keys(keys).offset(stackOffsetFromProp(offsetType)).order(stackOrderFromProp(order))
```

I'm simply trying to render the `<ResponsiveStream/>` with the sample code and data as provided. When I don't try to give the surrounding div both a width and height, the rest of the app renders as expected but the chart stays at either 0 width/height and doesn't show. Might be worthwhile to mention that I'm using flexbox sizing in general. Any ideas?

My component that's embedded in the app:

```  
import React from 'react'
import { ResponsiveStream } from '@nivo/stream'

const sampleData = [{...}] // same as in the docs
const StreamChart = (props) => (
  <div style={{ height: 400 }}>
  <ResponsiveStream
    data={sampleData}
        margin={{
            "top": 50,
            "right": 110,
            "bottom": 50,
            "left": 60
        }}
       ...
      legends={[
            {
                "anchor": "bottom-right",
                "direction": "column",
                "translateX": 100,
                "itemWidth": 80,
                "itemHeight": 20,
                "symbolSize": 12,
                "symbolShape": "circle"
            }
        ]}
    />
  </div>
)

export default StreamChart

```

Then I insert it as `<StreamChart />` inside another `<div>` in the App. Any pointers?

   ```
 render() {
        return (
            <StyledDiv className="App">
            <Button primary onClick={this.handleClick}>Button</Button>
            <StreamChart />
            </StyledDiv>)
    }
```

**Comment by stahlmanDesign** [comment]
I'm not sure if this is your problem but I also had trouble getting a chart to render. I found it works to wrap it in a Bootstrap 'container' (which is just `width: 100%` if you're not using Bootstrap)
```javascript
    return <div className='container'>
      <ResponsiveBar
        data={ barData }
        { ...barSettings }
      />
    </div>
```

**Comment by cherylschaefer** [comment]
One of these issues might help you:
https://github.com/plouc/nivo/issues/178
https://github.com/plouc/nivo/issues/122

**Comment by plouc** [comment]
@haywirez, sorry for the late reply, the website's example was missing the `keys` property. It's fixed now.
