### ISSUE TITLE
Scatterplot doesn't seem to support id / keys

### ISSUE THREAD

**Issue by MilesParker** [plouc/nivo#1572]
Hi,

When using scatter plot data sources, I can't seem to find a way to pass through unique ids for SVG keys. That means that when I filter items, nivo animations loses track of items. e.g. if I'm plotting A, B, C, D and remove item B, rather than item B fading to transparant before removal, B appears to move to replace the item that was at location D. Not sure if this is because of a React or D3 keying issue but something isn't working under the hood.

I've tried providing both a unique 'id' and 'key' field in my data items, but that doesn't seem to be respected.

Perhaps there is a pattern I'm missing?

thanks!

**Comment by wyze** [comment]
Please provide a CodeSandbox replicating the issue so we can take a look.

**Comment by MilesParker** [comment]
Sure thing!
https://codesandbox.io/s/nivo-1572-iowrq?file=/package.json
