### ISSUE TITLE
ResponsiveBar (nivo/bar) not updating its graphics as it should.

### ISSUE THREAD

**Issue by DimitarTB** [plouc/nivo#1579]
**Describe/explain the bug**
I am using the ResponsiveBar react component from the Nivo/bar library. It used to work just fine for a long time, I just noticed that the past few weeks (or longer) it has not been working correctly. 

I have dynamic data which changes over time. I am obtaining this data from my server and saving it to my state, then I provide this data to my ResponsiveBar component. 

The way it should work is - when my state changes (and it does, it updates other components in this view, I have no reason to believe that the the components do not re-render on state change) it should also update the values on my ResponsiveBar component - namely the values on the Y axis.

I am not sure how to reproduce this error as it just stopped working, I hadn't changed anything in this component for a long time.

As I described above, the expected behavior is: state change => component updates value. 

 - OS: Arch Linux
 - Browser Firefox
 - Version both nivo bar and nivo core are 0.67.0

 - Device: Samsung A71
 - OS: Android 10
 - Browser Chrome
 - Version both nivo bar and nivo core are 0.67.0

CodeSandbox reproduction: https://codesandbox.io/s/stupefied-glade-z19hx?file=/src/App.tsx

**Comment by DimitarTB** [comment]
So after a bit of investigation, I figured out what steps cause this no-update behavior. 

I had the default values (before each update) set to 0, and after I set the value to 0, it will not update again, I still dont know why that is. I tried 1 solution which worked and that is to import the `ResponsiveBar` component from `"nivo"` instead of `"@nivo/bar"`.

This however raised a new issue - for one the legends are no longer there, they are gone, and the second issue is that if one value is 0, every consecutive value that comes after it will have an incorrect color - essentially the color array is shifted 1 index to left for every bar that comes after the 0 value bar, and that re-applies for every occurrence of a 0 value bar, so if I have 2 0 value bars, after the first occurrence the color array will be shifted by 1, and after the second occurrence the color array will be shifted by 2. 

Also my labels are now at the top left instead of the middle left.

Here are before and after images using the @nivo/bar and the nivo imported ResponsiveBar component:
[images](https://imgur.com/a/tOqa5tS)

**Comment by wyze** [comment]
The `nivo` package is a really old version, published 4 years ago, please don't use that version. If you can provide a reproduction in CodeSandbox I'd be happy to take a look. We have a storybook example of data changing over time and it is working as expected: https://nivo.rocks/storybook/?path=/story/bar--race-chart

**Comment by DimitarTB** [comment]
As I mentioned above, when using the @nivo/bar as import, I am getting the glitch of no data after any of the values is reduced to 0.

Basically, if my Allocated bar is reduced to 0 by my filter, it will be stuck on 0 no matter what until I refresh. I used the developer tools to make sure that the component is recieving new data and it does - I can see its props changing but it does not update.

Using the old nivo import, it solved my issue but introduced 2 new issues (legends are missing and colors are incorrect unless I have at least 1 in each bar).

**Comment by wyze** [comment]
Here is the CodeSandbox to reproduce the issue: https://codesandbox.io/s/stupefied-glade-z19hx?file=/src/App.tsx

Looks to be only an issue with grouped mode as stacked works fine.

**Comment by DimitarTB** [comment]
Thanks for the swift responses and quality support. This helped me.
