### ISSUE TITLE
Have only full numbers instead of decimals for Chart scale

### ISSUE THREAD

**Issue by mboutin-qohash** [plouc/nivo#1580]
**Is your feature request related to a problem? Please describe.**
How can I set the scale to full numbers, like if I have a chart with persons, I can't have 1.2 persons.

![Screen Shot 2021-06-09 at 9 09 39 AM](https://user-images.githubusercontent.com/66835336/121360849-c65c7e00-c902-11eb-9934-807d893185c2.png)

**Describe the solution you'd like**
Entire number scaling

**Comment by rafapetter** [comment]
@mboutin-qohash what was your solution here?
