### ISSUE TITLE
Cant install using npm - broken dependency tree (@nivo/pie v0.70.1)

### ISSUE THREAD

**Issue by wiztemple** [plouc/nivo#1584]
**Describe/explain the bug**
When I tried installing the nivo/pie package by running npm i @nivo/pie, npm fails with this errors:

`Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from react-motion@0.5.2
npm ERR! node_modules/@nivo/colors/node_modules/react-motion
npm ERR!   react-motion@"^0.5.2" from @nivo/colors@0.70.1
npm ERR!   node_modules/@nivo/colors
npm ERR!     @nivo/colors@"0.70.1" from @nivo/pie@0.70.1
npm ERR!     node_modules/@nivo/pie
npm ERR!       @nivo/pie@"*" from the root project
npm ERR!     1 more (@nivo/arcs)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**To Reproduce**
 1. Create a blank folder and cd into it
 2. Run npx create-react-app .
 3. Run npm i @nivo/pi
 

 **Expected behavior**
Should install successfully

 **Additional context**
  - I am running on MacOs (Big Sur), using nodeJS v12.19.0 and npm v7.5.3.
  
  Thanks.
  wiztemple

**Comment by wyze** [comment]
You'll need to use the `--legacy-peer-deps` flag to work around the error while we work on removing `react-motion` which is causing the error. You can track the removal in #667.
