### ISSUE TITLE
ctx is not included in layers function of ResponsiveLineCanvas 

### ISSUE THREAD

**Issue by hoi82** [plouc/nivo#1588]
https://nivo.rocks/storybook/?path=/story/responsivelinecanvas--custom-line-style

above sample works well in TypeScript. But in below codes, 

layers={['grid', 'markers', 'axes', 'areas', 'crosshair', ({ lineGenerator, series, ctx, lineWidth, innerWidth }) => {
                             lineGenerator.context(ctx)
                             series.forEach(serie => {
                                 const gradient = ctx.createLinearGradient(0, 0, innerWidth, 0)
                                 gradient.addColorStop('1.0', serie.color)
                                 ctx.strokeStyle = gradient;
                                 ctx.lineWidth = responsive.mobile ? 4.8 : 6.4;
                                 ctx.beginPath();
                                 lineGenerator(serie.data.map(d => d.position));
                                 ctx.stroke();
                             })
                         }, 'points', 'slices', 'mesh', 'legends']}

layers property can only acccept (props: CustomLayerProps) => React.ReactNode functions and ctx property is not in CustomLayerProps and above codes does not return any React components. So errors displayed in IDE.

**Comment by wyze** [comment]
Which version are you using? Looks like this was fixed in v0.69.1 via https://github.com/plouc/nivo/pull/1499.

**Comment by hoi82** [comment]
I used 0.67.0 and props is displayed well after upgrade to 0.70.1.
But upgraded to 0.70.1, linegenerator's parameter changed from Array<{x: number, y: number}> to Iterable<{x: number, y: number}[]>.
And if I pass a single array of data, linegenerator returns invalid path string.
How can I use linegenerator?

**Comment by hoi82** [comment]
linegenerator works well.
Maybe I had some wrong in libraries.
I'll close this issue.
