### ISSUE TITLE
Allow graphing off the chart

### ISSUE THREAD

**Issue by Gabxi** [plouc/nivo#1590]
**Is your feature request related to a problem? Please describe.**
I have a set of sparse points where some have values past the interval I provide. I would like to graph them off the chart, so I can have line extending to my points that are within the intervals.

**Describe the solution you'd like**
It would be nice to pass a set of points, and the responsive line automatically cuts the ones not within the interval, graphs the closest outliers off the graph so the lines can extend.

**Describe alternatives you've considered**
I thought about just making an interpolated point, but it seems tricky to figure out the formula for how what y value should be at the boundaries.

**Comment by ollwenjones** [comment]
This can happen in our product, because we allow the user to specify the min/max for the axis. I experimented with SVG masks and it had promise, but I haven't had time to actually contribute, yet.
