### ISSUE TITLE
Marimekko chart still animates when false is passed via the animate prop

### ISSUE THREAD

**Issue by danbull** [plouc/nivo#1603]
This started happening after upgrading to v17.01 from v0.67.0 and can be recreated on the [chart demo page](https://nivo.rocks/marimekko/). Simply switch `animate` to `false` and you'll see animations still occur when clicking "roll the dice".

**Comment by wyze** [comment]
Looks like this is a bug with react-spring. I filed an issue over there. https://github.com/pmndrs/react-spring/issues/1581
