### ISSUE TITLE
parameter type of lineGenerator is weird

### ISSUE THREAD

**Issue by hoi82** [plouc/nivo#1604]
When I make custom layer in ResponsiveLine, lineGenerator's parameter type is displayed,

 'Iterable<{x: number, y: number}> | {x: number, y: number}[][]'

But, like below codes, pass the data like documents works well.

const CustomLine = (props: CustomLayerProps) => {
        const { series, lineGenerator, xScale, yScale } = props;
        return series.map((s : ComputedSerie) => {
            const { id, data, color } = s;
            return (
                <path d={lineGenerator(data.map(d => ({ x: xScale(d.data.x), y: yScale(d.data.y) })))} 
                stroke={color} style={{strokeWidth: '1rem'}}/>
            )
        })
    }

I'm using 0.70.1 version nivo/line, nivo/core, nivo/bar, nivo/tooltip.
Is there any missing of declares?

**Comment by dardanos** [comment]
Here is what I'm doing in the meantime
```typescript
interface FixedCustomLayerProps
  extends Omit<CustomLayerProps, 'xScale' | 'yScale'> {
  xScale: (x: DatumValue) => DatumValue;
  yScale: (y: DatumValue) => DatumValue;
}
```

**Comment by hoi82** [comment]
> Here is what I'm doing in the meantime
> 
> ```ts
> interface FixedCustomLayerProps
>   extends Omit<CustomLayerProps, 'xScale' | 'yScale'> {
>   xScale: (x: DatumValue) => DatumValue;
>   yScale: (y: DatumValue) => DatumValue;
> }
> ```

My question is about lineGenerator. Not xScale or yScale.

**Comment by akassaei** [comment]
@hoi82 Any update on this issue I'm facing the same problem in my code ?
