### ISSUE TITLE
Can it be possible to specify and independent lineWidth, enableDots, dotSize and dotBorderWidth for each displayed line

### ISSUE THREAD

**Issue by ellipticaldoor** [plouc/nivo#162]
I need to differentiate visually some lines in the graph and been able to change the lineWidth, enableDots, dotSize and dotBorderWidth of each line would be very helpful.

**Comment by plouc** [comment]
No it's not possible, however you could customize entirely lines and points by replacing `layers` with custom ones, like for [the demo of custom line style](https://nivo.rocks/storybook/?path=/story/line--custom-line-style).
