### ISSUE TITLE
Incorrect tick values on cross axis

### ISSUE THREAD

**Issue by gustavomauricio** [plouc/nivo#1621]
**Describe/explain the bug**
Incorrect tick values on line chart, time formatted axis, when month changes and using "every x days" as tickValues property.

**To Reproduce**
https://codesandbox.io/s/qpb9j

**Expected behavior**
tick values properly spaced with a 3 days difference

**Screenshots**

![image](https://user-images.githubusercontent.com/28717118/123161646-93200000-d467-11eb-9ee3-a9e49c77202a.png)

**Comment by wyze** [comment]
This is fixed in the latest version if you upgrade your sandbox, you will see it working correctly.
