### ISSUE TITLE
Usage with Typescript. Declaration file

### ISSUE THREAD

**Issue by jansomers** [plouc/nivo#163]
Hello,

Is there a reason why there is no declaration file available on the web or in the project itself?
I would really love to use this in our project but the lack of types will make it hard for us to commit to this library.

Anything I'm missing?

Kind regards,
Jan

**Comment by leonkyr** [comment]
+1

**Comment by plouc** [comment]
@jansomers appart from lack of time, no particular reason :)
If someone is willing to contribute to TS definitions, I'll be really happy to review!

**Comment by plouc** [comment]
I've created a new issue for this https://github.com/plouc/nivo/issues/197
