### ISSUE TITLE
Synchronizing Charts with ScatterPlotCanvas

### ISSUE THREAD

**Issue by ethansaxenian** [plouc/nivo#1632]
Since version 0.71.0, the synchronized charts demo in the storybook does not appear to be working correctly. It seems to be synchronizing all nodes in both plots, rather than just one pair. See the [storybook](https://nivo.rocks/storybook/?path=/story/scatterplotcanvas--synchronizing-charts) and screenshots below.

![Screen Shot 2021-06-25 at 10 12 11 AM](https://user-images.githubusercontent.com/67524957/123437583-d2506d00-d59d-11eb-8696-ec569bcb2b4f.png)

![Screen Shot 2021-06-25 at 10 12 43 AM](https://user-images.githubusercontent.com/67524957/123437638-e4321000-d59d-11eb-9fc2-542193754f1e.png)

**Comment by plouc** [comment]
This has been fixed in https://github.com/plouc/nivo/pull/1726, but not yet published/deployed.
