### ISSUE TITLE
Bar Chart legend regression from 0.70.1 to 0.71.0 

### ISSUE THREAD

**Issue by onionhammer** [plouc/nivo#1633]
Previously
![image](https://user-images.githubusercontent.com/969938/123465860-44cc4780-d5b4-11eb-803d-34a84869e40a.png)

Now:
![image](https://user-images.githubusercontent.com/969938/123465782-2f571d80-d5b4-11eb-830c-8f712451ad61.png)

The numbers arent important, the legend is no longer displaying all the possible options,  possibly related to #1556 

Client code is unchanged, just the version bump;

```tsx
<ResponsiveBar
                    data={data}
                    legends={[
                        {
                            dataFrom: 'indexes',
                            anchor: 'bottom-right',
                            direction: 'column',
                            justify: false
                        }
                    ]}
                />
```

`data` is structured like: 
```js
[
   { id: "Matched", value: 123 },
   { id: "Reviewed", value: 123 },
   ...
]
```

**Comment by wyze** [comment]
Yes, sorry I broke it! I did catch it when I was doing the typescript migration so it is fixed in #1619. Just need to get it reviewed and merged.

**Comment by stahlmanDesign** [comment]
Not sure if this is related but I'm getting an error with stacked bars after update from 0.70 to 0.71

TypeError: hiddenIds is undefined
generateStackedBars/keys<
src/compute/stacked.js:154
<img width="1043" alt="Capture d’écran, le 2021-06-25 à 23 50 02" src="https://user-images.githubusercontent.com/972804/123501109-973b5180-d610-11eb-961c-eceb2a34502a.png">

**Comment by wyze** [comment]
@stahlmanDesign Related to the legends but not really the original issue. I've also fixed that in the typescript PR.
