### ISSUE TITLE
Stacked bars getIndexScale error Object(...)(...) is undefined

### ISSUE THREAD

**Issue by stahlmanDesign** [plouc/nivo#1642]
0.71 introduced a error rendering stacked bars which I mentioned here https://github.com/plouc/nivo/issues/1633
That was fixed with the release of 0.72 thanks @wyze 

In 0.72, there's different error with `getIndexScale`, again related to stacked bars

<img width="908" alt="Capture d’écran, le 2021-06-29 à 15 53 53" src="https://user-images.githubusercontent.com/972804/123859121-45394b00-d8f2-11eb-88d9-b8d539a8b4dc.png">

**Comment by wyze** [comment]
Hi, can you please provide a CodeSandbox with a reproduction of the issue. I can't reproduce it with the website and storybook examples.

**Comment by stahlmanDesign** [comment]
Yes, I will work on that

> Hi, can you please provide a CodeSandbox with a reproduction of the issue. I can't reproduce it with the website and storybook examples.

**Comment by stahlmanDesign** [comment]
I was unable to reproduce the error, which I no longer see in my project either. I think I did not restart my front-end after installing 0.72. With a fresh start it seems OK. Sorry for the false alarm.

**Comment by wyze** [comment]
Sounds good, thanks!
