### ISSUE TITLE
Negative numbers do not render in bar chart when there is only one key

### ISSUE THREAD

**Issue by barrylapthorn** [plouc/nivo#165]
Take the example here:

http://nivo.rocks/storybook/?selectedKind=Bar&selectedStory=stacked%20horizontal&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs

Change the data to have negative values, and have only one key field:

```
<Bar
  width={1000}
  height={600}
  margin={{top: {60}, right: {80}, bottom: {60}, left: {80}}}
  data={[{{country: "AD", hot dogs: {-55}}}, {{country: "AE", hot dogs: {7}}}]}
  indexBy="country"
  keys={["hot dogs"]}
  padding={0.2}
  labelTextColor="inherit:darker(1.4)"
  labelSkipWidth={16}
  labelSkipHeight={16}
  layout="horizontal"
  enableGridY={false}
  enableGridX
/>
```
and the negative value bars do not render.

But adding an extra key makes it work, i.e.

```
  keys={["hot dogs", "FOO"]}
```

or

```
  keys={["hot dogs", ""]}
```

**Comment by 20ali20** [comment]
margin={{top: 60, right: 80, bottom: 60, left: 80}}

**Comment by 20ali20** [comment]
data={[{{country: "AD", hot dogs: -55}}, {{country: "AE", hot dogs: 7}}]}

**Comment by 20ali20** [comment]
dont put values inside { }

**Comment by plouc** [comment]
Example for reference => https://codesandbox.io/s/k346rpz98v

**Comment by pfreedmanJG** [comment]
> Example for reference => https://codesandbox.io/s/k346rpz98v

Can someone share a version of this with the workaround please? I can't get the negative bar to render.

**Comment by zepplock** [comment]
So what is the right way to fix this?

**Comment by 20ali20** [comment]
@zepplock  did you actually look at the first 3 posts I made and try those codes?

**Comment by zepplock** [comment]
I did, if I add a new "foo" key like original poster suggested it works, but this looks like a hack, right?

**Comment by 20ali20** [comment]
@zepplock I was talking about my posts. The original poster suggestions is hacky.
What I suggested is what works because his code seems to have some syntax issue. 
Just Check the first two posts I made and replace them where its needed from the original code.

**Comment by zepplock** [comment]
I tried your suggestions but there's still an issue. Take a look at codesandbox link @pluoc posted. It has no negative value unless you add `"FOO"` to the list of keys.

**Comment by 20ali20** [comment]
Gotcha. That is definitely hacky but I think that empty key acts as a baseline so the negative values can be rendered.
But a hacky way that won't really affect anything is not really a deal breaker ;)

**Comment by brunovegreville** [comment]
This seems to be related to this d3-shape issue : https://github.com/d3/d3-shape/issues/114

**Comment by sdzaveri** [comment]
Experiencing this issue as well, looks like a simple fix was also created https://github.com/d3/d3-shape/pull/115

**Comment by wyze** [comment]
Going to close this as it appears to be fixed now.

**Comment by Jedi-Sid** [comment]
Hello,

Reviving this was I cannot get negative ticks to appear, even with extra key hack.

```
  const data = [
    {
      class: "Property",
      asset: 100,
    },
    {
      class: "Mortgage",
      liability: -100,
    },
  ];
```

Code:


  ```
  <ResponsiveBar 
              data={data}
              padding={0.1}
              innerPadding={2}
              indexBy={"class"}
              keys={["", "asset", "liability", ""]}
              margin={{ bottom: 400,   left: 100,  right: 100, top: 100,  }}
  />
```

My chart looks like this, with no negative ticks...

<img width="549" height="715" alt="Image" src="https://github.com/user-attachments/assets/d363e997-efde-4490-8940-34efddaa173b" />

Any ideas?
