### ISSUE TITLE
Sunburst: make the root node visible as the center circle

### ISSUE THREAD

**Issue by derrickbeining** [plouc/nivo#1650]
**Is your feature request related to a problem? Please describe.**
The root node in `props.data` in `Sunburst` gets thrown away. I would expect the root node to be displayed as the center circle of the sunburst. Is there already an API exposed for enabling this? Or could it be added fairly easily?

**Describe the solution you'd like**
Add a prop for enabling the display of the root node as a circle at the center of the Sunburst.

**Describe alternatives you've considered**
Trying to jury rig it using the `layers` prop.

**Additional context**
Here is the Sunburst widget from `highcharts` which behaves the way I would expect, showing the root node as the center of the sunburst:

https://user-images.githubusercontent.com/25019711/124046283-95daa200-d9df-11eb-9bfd-356c06de9b68.mov

**Comment by joshburgess** [comment]
@wyze As a temporary solution to make things more flexible, would you accept a PR that allows the user to configure whether or not they want to exclude the root node?

The root node gets excluded here: https://github.com/plouc/nivo/blob/919f213600a08609939198ea743f7dbde9a572e2/packages/sunburst/src/hooks.ts#L61

Maybe, we could add a prop to the Sunburst component, like a boolean called `excludeRootNode`, which we default to true to preserve the existing functionality, but can be set to false to change this behaviour. This prop would be a new param passed to the useSunburst hook here: https://github.com/plouc/nivo/blob/fe388ff3d081ae9f8ab37c5ac3172bd5154fe98e/packages/sunburst/src/Sunburst.tsx#L69-L80

And we would then conditionally decide whether or not to call `.slice(1)`.

Another thing that would give the user some flexibility is to preserve the root node (even when excludeRootNode is set to true) as a separate reference and providing it as one of the props given to custom layer components. This would allow the user to gain access to it and use that information to create their own custom center circle. Ideally, this data would be of the `ComputedDatum<A>` type.

**Comment by wyze** [comment]
Yeah we could do that. I would prefer to call it `renderRootNode` and default to `false`.

**Comment by joshburgess** [comment]
Ok, sounds good. If I get some free time soon, I'll see if I can make a PR for this change.

**Comment by jsw** [comment]
It doesn't look like this ever got implemented?
