### ISSUE TITLE
Animate no longer working on bar chart after updating to 0.72.0

### ISSUE THREAD

**Issue by taniarascia** [plouc/nivo#1652]
The animation no longer applies to a bar chart in version 0.72.0 in situations where it did on 0.71.0. I made a sandbox with the exact same code for both versions to show the issue.

Version 0.71.0: https://codesandbox.io/s/nivo-0710-vxzkg?file=/src/App.js
Version 0.72.0: https://codesandbox.io/s/nivo-0720-yugxs?file=/src/App.js

As demonstrated, the animate property does not apply to the bars for the 0.72.0 version when the `keys` property is changed, which is behavior that was previously supported. Are there plans to continue supporting this behavior? 

Thank you!

UPDATE: This also applies to regular data sets that have changed. If I update the dataset to a different amount of bars and the axis changes, the animation does not work. I updated both sandboxes to include both situations in which animations no longer work.

Note that both of these situations still work on line graphs.

**Comment by wyze** [comment]
Whoops! Something was lost in the Typescript migration. I'll take a look. Thanks for the CodeSandbox links!
