### ISSUE TITLE
Bump react to 17.0.2

### ISSUE THREAD

**Issue by MartinSkovsen** [plouc/nivo#1659]
**Is your feature request related to a problem? Please describe.**
It's not really a breaking issue, but Nivo isn't up-to-date with react 17.0.2.

**Describe the solution you'd like**
I'd like to start by saying what an amazing product you guys have built. We use Nivo in business critical applications, and we are so happy with it. It could be nice if Nivo was always up-to-date with the latest react verison

**Describe alternatives you've considered**
Left empty on purpose.

**Additional context**
Left empty on purpose.

**Comment by wyze** [comment]
I've already done that for our dev dependencies here, https://github.com/plouc/nivo/pull/1612. We don't have a dependency on react and specify it as a peer dependency which already allows react v17.0.2.
