### ISSUE TITLE
Pie HTTP API error: "sortByValue\" is not allowed (sortByValue)"

### ISSUE THREAD

**Issue by kmcaloon** [plouc/nivo#166]
When trying to generate a pie chart using the Pie HTTP API, no matter what I do I receive the following error whether or not the sortByValue is set to true within the options provided by the UI:

```
{
  "errors": [
    "\"sortByValue\" is not allowed (sortByValue)"
  ]
}
```

**Comment by plouc** [comment]
I've removed it from the API call, as it's not yet supported.
