### ISSUE TITLE
How can I add a title to a chart?

### ISSUE THREAD

**Issue by deadhandsignal** [plouc/nivo#167]
Firstly, thank you very much for the library, it's helping me learn React. Probably really straightforward, but how do I add a chart title? Thanks again! tk

**Comment by plouc** [comment]
Hello @deadhandsignal, you could add it as plain html before|after your component, I do not added this feature as text is really hard to keep consistent between various implementations (SVG/HTML/Canvas), you'll also be able to style it the way you want using standard CSS.

**Comment by hatton** [comment]
>  you could add it as plain html before|after your component, 

That was my first thought, but the problem is then how to get it included in the SVG that our users download.

**Comment by plouc** [comment]
@hatton, depending on the component you use, you might be able to add an extra layer for the title, this way it would be part of the SVG, please note that not all components support it and the documentation is pretty light.

**Comment by Nathaniel-Fernandes** [comment]
Adding onto what @plouc stated, I was able to add the title as an extra layer like this:
```
    const Title = ({ width, height }) => {
        // You can console.log(data) to see what other properties are available

        const style = {fontWeight: 'bold'}

        return (
            <text 
                x={width / 2}
                y={-10}
                style={style}
            >
                Hi there. Your Title here!
            </text>
        )
    } 
...
      <Bar
            data={  the_data  }
            layers={['grid', 'axes', 'bars', 'markers', 'legends', 'annotations',Title]} // put your title function here. The order of layers is their precedence
        />
```
