### ISSUE TITLE
Bar chart: The values are offset by one given their key

### ISSUE THREAD

**Issue by tomasonjo** [plouc/nivo#1670]
I have created a codesandbox that replicates this behaviour: https://codesandbox.io/s/bar-bug-u5r6v. I use nivo/bar and nivo/core version 0.72.0

The example is very simple, so I don't know if I can fix anything on my end.

![Screenshot from 2021-07-07 22-06-51](https://user-images.githubusercontent.com/19948365/124822364-16654980-df70-11eb-91ab-ce98ad8f938d.png)

Neo4j key should have the highest value, but it seems it is actually empty looking at the visualization. That is really weird. What is even stranger is that when I hover over the first visualized bar, it displays index Neo4j.

![Screenshot from 2021-07-07 22-08-42](https://user-images.githubusercontent.com/19948365/124822637-6f34e200-df70-11eb-8a0f-81b5243d8565.png)

The feeling I get is that the visualized bars are offset by 1 given their index key.

**Comment by plouc** [comment]
@tomasonjo, this is because of the duplicated value for `Data Science Central`, this doesn't play well with the chart, those names are used as an index, and it breaks the chart if they're duplicated. If you remove this duplicate, things behave normally.

**Comment by tomasonjo** [comment]
Thank you! The issue remains, but I'll create a workaround for now. Feel free to reopen for others.
