### ISSUE TITLE
Points layer missing on Scatterplot / ResponsiveScatterplot when specifying layers

### ISSUE THREAD

**Issue by cflynn3** [plouc/nivo#1675]
Using https://codesandbox.io/s/kkqmx1rw17?file=/src/index.js as an example, I get the runtime error 'Error: Unknown layer (points)' when run against the latest version of this library. If I remove the 'layers' parameter, the graph renders OK, albeit without the intended extra layer.

This code works as expected in the version in the example (0.51.3).

**Comment by wyze** [comment]
Looks like it was changed with https://github.com/plouc/nivo/commit/4397dab67850d13d74890fbb0dbf3d2e89c114fb and released in v0.59.0. It should work as expected if you change `points` to `nodes`.

**Comment by cflynn3** [comment]
Thanks, that fixed it.
