### ISSUE TITLE
@nivo/color still has dependency on react-motion.

### ISSUE THREAD

**Issue by scottandrew** [plouc/nivo#1676]
When installing @nivo/color 0.7.2 it still has a dependency on react-motion.. The package.json has:

`  "dependencies": {
    "d3-color": "^2.0.0",
    "d3-scale": "^3.2.3",
    "d3-scale-chromatic": "^2.0.0",
    "lodash": "^4.17.21",
    "react-motion": "^0.5.2"
  },`

This is causing issues when installing with npm and react 17.x installed.

**To Reproduce**

1. Add @npm/colors as a dependency.
2. run npm install

**Expected behavior**
Everything to load.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 11.4
 - Browser Chrome

**Comment by wyze** [comment]
Thanks! We are tracking this in #667.
