### ISSUE TITLE
Ability to "slide" line markers (onChange)

### ISSUE THREAD

**Issue by ChuckJonas** [plouc/nivo#1699]
**Is your feature request related to a problem? Please describe.**
I'm using the Line chart to display a time series.  In my dataset, there are key moments, which I am using marker to denote.

<img width="1233" alt="localhost_3000_createRoast" src="https://user-images.githubusercontent.com/5217568/127665795-754092f1-334c-44c7-9bd3-c5229b37e6d2.png">

It would be extremely slick if I could edit these markers via a "draggable" interface.

**Describe the solution you'd like**
Add an API for marker "onDrag"

Could be in the Marker dataset itself or on the component:

```ts
markers={[
            {
                axis: 'x',
                value: 30,
                legend: 'First Crack',
                onChange: (x) => console.log(x)  // new x value
            },
]}
```

OR 

```ts
<ResponsiveLine
   onChange = {(marker) => console.log(marker)} // full data w/ new x or y value
   ...
```

**Describe alternatives you've considered**
The only alternative would be to try and "superimpose" your own markers over the graph, but that's extremely hard to do

**Comment by wyze** [comment]
This is out of scope for the library. I'd recommend disabling the default `markers` layer and build a custom layer that implements dragging. Here is the default `markers` layer for reference. https://github.com/plouc/nivo/blob/75eafa185d1d1cceeaacad589288f82d5d724842/packages/line/src/Line.js#L152-L162
