### ISSUE TITLE
BarCanvas axis text does not respect theme fontweight

### ISSUE THREAD

**Issue by vanbujm** [plouc/nivo#1704]
I think the issue is here:
https://github.com/plouc/nivo/blob/75eafa185d1d1cceeaacad589288f82d5d724842/packages/axes/src/canvas.ts#L68
`ctx.font` should probably look like it does on line 149:

This should be the fix
```
ctx.font = `${
            ttheme.axis.ticks.text.fontWeight ? `${theme.axis.ticks.text.fontWeight} ` : ''
        }${theme.axis.ticks.text.fontSize}px ${theme.axis.ticks.text.fontFamily}`
```

**Comment by vanbujm** [comment]
Fixed in https://github.com/plouc/nivo/pull/1708

**Comment by wyze** [comment]
Thanks!
