### ISSUE TITLE
ResponsiveSwarmPlotCanvas does not work with valueScale type "time"

### ISSUE THREAD

**Issue by anam-dodhy** [plouc/nivo#1705]
**Describe/explain the bug**
I am unable to use `ResponsiveSwarmPlotCanvas` for plotting a dataset with `valueScale` type set to `time`. The Axis just shows some strange time stamps which are neither related to the timestamp in the dataset or anything else. 

**To Reproduce**
I have implemented a simple example with `ResponsiveSwarmPlotCanvas` where the X-Axis is picking up some random time stamps.
https://codesandbox.io/s/affectionate-mahavira-j5nx0?file=/src/App.js

However the same example works perfectly fine when I switch to `ResponsiveSwarmPlot`
https://codesandbox.io/s/frosty-williamson-5uhbe?file=/src/App.js

Both examples are exactly the same, the only difference is the component being used. 

1. Go to the sandbox: https://codesandbox.io/s/affectionate-mahavira-j5nx0?file=/src/App.js
2. The X-Axis has some random time stamp values

**Expected behavior**
`ResponsiveSwarmPlotCanvas` handles `valueScale` type `time` same as `ResponsiveSwarmPlot`.

**Screenshots**
X-Axis is using strange time stamp values in case of `ResponsiveSwarmPlotCanvas`
![image](https://user-images.githubusercontent.com/28350571/128150724-4d5394c6-20ae-4798-807e-d6a482061efd.png)

The same example works perfectly fine when we replace `ResponsiveSwarmPlotCanvas` with `ResponsiveSwarmPlot`
![image](https://user-images.githubusercontent.com/28350571/128150933-d1d46c75-d404-41ac-b10e-0740ab513cb9.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome Version 92.0.4515.107
 - "@nivo/core": "0.73.0",
    "@nivo/swarmplot": "0.73.0",

**Additional context**
I need to switch from `ResponsiveSwarmPlot` to `ResponsiveSwarmPlotCanvas` in order to get better performance when rendering a rather large number of nodes.

**Comment by wyze** [comment]
It looks like we don't accept the `valueScale` prop in the canvas flavor but just use the default scale. Should be a simple fix. https://github.com/plouc/nivo/blob/master/packages/swarmplot/src/SwarmPlotCanvas.tsx#L103

**Comment by Patil2099** [comment]
I would love to work on this
