### ISSUE TITLE
Bar: Highlight Bar on Hover

### ISSUE THREAD

**Issue by akratzel** [plouc/nivo#1720]
**Is your feature request related to a problem? Please describe.**
I am using `nivo/bar` to include a `<Bar />` component on my application. The tooltip on hover works nicely and without any issues, however it would be nice if we could somehow highlight the complete bar that is currently being hovered - the tooltip should still be visible ofc.

**Describe the solution you'd like**
The easiest functionality would be a new prop that would go like e.g. `highlightOnHover`. Another solution might be using the `defs` to add a `hover` option inside the `colors` property.

**Describe alternatives you've considered**
An alternative would be with weird state handling and working with `onMouseEnter` or something like that since pure CSS will not work here either.

Thank you and let me know what you think!

**Comment by Souvikray** [comment]
Same here. I need a functionality for (in my case) highlighting a circle on hover in packed circle chart.

**Comment by wastedev** [comment]
bump
