### ISSUE TITLE
Bump d3-color

### ISSUE THREAD

**Issue by foreseeti-adam** [plouc/nivo#1728]
Hi,

d3-color version<3.0.0 that is used in some of your packages is vulnerable to [ReDoS](https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592), hence it would be a good idea to bump this ([if possible](https://github.com/d3/d3-color/releases/tag/v3.0.0)) in your next release.

Thank you for providing a great visualization tool!

**Comment by plouc** [comment]
Hi @foreseeti-adam, thank you for reporting this issue, as it's a major version change, we would have to investigate a little bit before migrating. If the only change is the adoption of modules, shouldn't be an issue though as we already use ESM.

**Comment by huornlmj** [comment]
Bump,  d3-color@2.0.0 has a Regular Express Denial of Service vulnerability via the rgb() and hrc() functions since August 2020.  Popular composition analysis tools are thus flagging nivo as introducing a vulnerable 3rd party component.

**Comment by dnoji** [comment]
The d3-color package is still be flagged by [security tools](https://security.snyk.io/vuln/SNYK-JS-D3COLOR-1076592). Can this be upgraded to 3.1.0 in the next release?

**Comment by marcospassos** [comment]
Hey guys, any news on this?

**Comment by B0lemix** [comment]
still being flagged like vulnerable to ReDoS and no fix available

**Comment by IshfaqAhmedProg** [comment]
@plouc any fix for this?

**Comment by dnoji** [comment]
> The d3-color package is still being flagged by [security tools](https://security.snyk.io/vuln/SNYK-JS-D3COLOR-1076592). Can this be upgraded to 3.1.0 in the next release?

I think it might have been fixed in this [release](https://github.com/plouc/nivo/releases/tag/v0.82.0) by #2142

**Comment by jvu1** [comment]
The vulnerability still exists for me because two of nivo's dependencies: `d3-interpolate@2.0.1` and `d3-scale-chromatic@2.0.0` still use version 2.0.0 of `d3-color`.

Anybody still getting the flagged after updating to `v0.82.0` or greater?

**Comment by RikuRuokonen** [comment]
This seems still be issue?

It seems that  `/d3-scale-chromatic@2.0.0` still uses v.2.0.0 of `d3-color`.

Subsequently,  `/@nivo/core@0.83.0` (latest one) seems to use said version in `d3-scale-chromatic`.

**Comment by adrian-meditect** [comment]
Unfortunately, I confirm what @RikuRuokonen is saying. After upgrading to latest release 0.83, I still have this issue. 
Here is the yarn.lock dependencies proving the problem.

This issue should be re-opened please @plouc 🙏 

```
"@nivo/colors@0.83.0":
  version "0.83.0"
  resolved "https://registry.yarnpkg.com/@nivo/colors/-/colors-0.83.0.tgz#e8afb2ec10ceb2c0d2b2407f01e11c197c57f78d"
  integrity sha512-n34LWYtE2hbd1fdCDP7TCHNZdbiO1PwcvXLo0VsKK5lNPY/FA5SXA7Z9Ubl/ChSwBwbzAsaAhjTy8KzKzSjDcA==
  dependencies:
    "@nivo/core" "0.83.0"
    "@types/d3-color" "^2.0.0"
    "@types/d3-scale" "^3.2.3"
    "@types/d3-scale-chromatic" "^2.0.0"
    "@types/prop-types" "^15.7.2"
    d3-color "^3.1.0"
    d3-scale "^3.2.3"
    d3-scale-chromatic "^2.0.0"
    lodash "^4.17.21"
    prop-types "^15.7.2"

"d3-interpolate@1 - 2", "d3-interpolate@1.2.0 - 2", d3-interpolate@^2.0.1:
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/d3-interpolate/-/d3-interpolate-2.0.1.tgz#98be499cfb8a3b94d4ff616900501a64abc91163"
  integrity sha512-c5UhwwTs/yybcmTpAVqwSFl6vrQ8JZJoT5F7xNFK9pymv5C0Ymcc9/LIJHtYIggg/yS9YHw8i8O8tgb9pupjeQ==
  dependencies:
    d3-color "1 - 2"

d3-path@1:
  version "1.0.9"
  resolved "https://registry.yarnpkg.com/d3-path/-/d3-path-1.0.9.tgz#48c050bb1fe8c262493a8caf5524e3e9591701cf"
  integrity sha512-VLaYcn81dtHVTjEHd8B+pbe9yHWpXKZUC87PzoFmsFrJqgFwDe/qxfp5MlfsfM1V5E/iVt0MmEbWQ7FVIXh/bg==

d3-scale-chromatic@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/d3-scale-chromatic/-/d3-scale-chromatic-2.0.0.tgz#c13f3af86685ff91323dc2f0ebd2dabbd72d8bab"
  integrity sha512-LLqy7dJSL8yDy7NRmf6xSlsFZ6zYvJ4BcWFE4zBrOPnQERv9zj24ohnXKRbyi9YHnYV+HN1oEO3iFK971/gkzA==
  dependencies:
    d3-color "1 - 2"
    d3-interpolate "1 - 2"
```

**Comment by tomyste** [comment]
The same for me

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
No fix available
node_modules/d3-interpolate/node_modules/d3-color
node_modules/d3-scale-chromatic/node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    @nivo/core  *
    Depends on vulnerable versions of @nivo/tooltip
    Depends on vulnerable versions of d3-interpolate
    Depends on vulnerable versions of d3-scale
    Depends on vulnerable versions of d3-scale-chromatic
    node_modules/@nivo/core
      @nivo/annotations  *
      Depends on vulnerable versions of @nivo/colors
      Depends on vulnerable versions of @nivo/core
      node_modules/@nivo/annotations
        @nivo/line  *
        Depends on vulnerable versions of @nivo/annotations
        Depends on vulnerable versions of @nivo/axes
        Depends on vulnerable versions of @nivo/colors
        Depends on vulnerable versions of @nivo/core
        Depends on vulnerable versions of @nivo/legends
        Depends on vulnerable versions of @nivo/scales
        Depends on vulnerable versions of @nivo/tooltip
        Depends on vulnerable versions of @nivo/voronoi
        node_modules/@nivo/line
      @nivo/axes  *
      Depends on vulnerable versions of @nivo/core
      Depends on vulnerable versions of @nivo/scales
      node_modules/@nivo/axes
      @nivo/colors  *
      Depends on vulnerable versions of @nivo/core
      Depends on vulnerable versions of d3-scale
      Depends on vulnerable versions of d3-scale-chromatic
      node_modules/@nivo/colors
      @nivo/legends  0.56.0 - 0.62.0 || >=0.63.1
      Depends on vulnerable versions of @nivo/colors
      Depends on vulnerable versions of @nivo/core
      Depends on vulnerable versions of d3-scale
      node_modules/@nivo/legends
      @nivo/tooltip  *
      Depends on vulnerable versions of @nivo/core
      node_modules/@nivo/tooltip
      @nivo/voronoi  *
      Depends on vulnerable versions of @nivo/core
      Depends on vulnerable versions of d3-scale
      node_modules/@nivo/voronoi
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
      @nivo/scales  *
      Depends on vulnerable versions of d3-scale
      node_modules/@nivo/scales
    d3-scale-chromatic  0.1.0 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale-chromatic

And, now I use  
"@nivo/core": "^0.83.0",
   "@nivo/line": "^0.83.0",

**Comment by plouc** [comment]
This should be fixed in `0.83.1`.

**Comment by Dmo16** [comment]
Sunburst is still showing vulnerability, but maybe it needs a new issue for tracking?

```
# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install @nivo/sunburst@0.55.0, which is a breaking change
node_modules/d3-interpolate/node_modules/d3-color
node_modules/d3-scale-chromatic/node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
      @nivo/core  *
      Depends on vulnerable versions of @nivo/tooltip
      Depends on vulnerable versions of d3-scale
      node_modules/@nivo/core
        @nivo/colors  *
        Depends on vulnerable versions of @nivo/core
        Depends on vulnerable versions of d3-scale
        Depends on vulnerable versions of d3-scale-chromatic
        node_modules/@nivo/colors
          @nivo/arcs  *
          Depends on vulnerable versions of @nivo/colors
          Depends on vulnerable versions of @nivo/core
          node_modules/@nivo/arcs
            @nivo/sunburst  *
            Depends on vulnerable versions of @nivo/arcs
            Depends on vulnerable versions of @nivo/colors
            Depends on vulnerable versions of @nivo/core
            Depends on vulnerable versions of @nivo/tooltip
            node_modules/@nivo/sunburst
        @nivo/tooltip  *
        Depends on vulnerable versions of @nivo/core
        node_modules/@nivo/tooltip
    d3-scale-chromatic  0.1.0 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale-chromatic

```

**Comment by jvu1** [comment]
> This should be fixed in `0.83.1`.

@plouc Updating to `v0.84.0` (below) did not address the issue fully. 

```
"@nivo/bar": "^0.84.0",
"@nivo/core": "^0.84.0",
"@nivo/line": "^0.84.0",
"@nivo/pie": "^0.84.0",
"@nivo/radial-bar": "^0.84.0",
```

It looks like `@nivo/bar` has dependencies that still rely on `d3-color@2.0.0`. Dependency tree below:

```
├─┬ @nivo/bar@0.84.0 invalid: "^0.83.0" from the root project
│ ├─┬ @nivo/colors@0.84.0
│ │ ├── d3-color@3.1.0 deduped
│ │ └─┬ d3-scale-chromatic@2.0.0
│ │   └── d3-color@2.0.0
│ └─┬ d3-scale@3.3.0
│   └─┬ d3-interpolate@2.0.1
│     └── d3-color@2.0.0
```

**Comment by radikrisffnext** [comment]
@jvu1 +1 on this.
we have the same issue, any update on this?

**Comment by kevy-maz** [comment]
![image](https://github.com/plouc/nivo/assets/107672586/f3da8c59-32af-4c43-aba0-c7eb190553cf)
![image](https://github.com/plouc/nivo/assets/107672586/29700f4c-49ca-45a2-963b-5208537b1461)
I think that unless `d3-scale-chromatic` is updated to higher version, it won't be fixed.

**Comment by Nestyko** [comment]
I think this is still an active issue, what I did to solve it was to use `yarn` and set the `resolutions` to force the usage of a safe version of `d3-colors`

package.json
```json
{
  "resolutions": {
    "d3-color": "^3.1.0"
  },
}
```

```bash
npm ls d3-color
npm ERR! code ELSPROBLEMS
npm ERR! invalid: d3-color@3.1.0 /Users/nestortobon/labra/webapp/node_modules/d3-color
labrav-webapps@0.1.0 /Users/nestortobon/labra/webapp
├─┬ @nivo/core@0.84.0
│ ├── d3-color@3.1.0
│ ├─┬ d3-interpolate@3.0.1
│ │ └── d3-color@3.1.0 deduped
│ ├─┬ d3-scale-chromatic@3.0.0
│ │ └── d3-color@3.1.0 deduped
│ └─┬ d3-scale@3.3.0
│   └─┬ d3-interpolate@2.0.1
│     └── d3-color@3.1.0 deduped invalid: "1 - 2" from node_modules/d3-scale/node_modules/d3-interpolate
└─┬ @nivo/line@0.84.0
  └─┬ @nivo/colors@0.84.0
    ├── d3-color@3.1.0 deduped
    └─┬ d3-scale-chromatic@2.0.0
      ├── d3-color@3.1.0 deduped invalid: "1 - 2" from node_modules/d3-scale/node_modules/d3-interpolate, "1 - 2" from node_modules/@nivo/colors/node_modules/d3-scale-chromatic
      └─┬ d3-interpolate@2.0.1
        └── d3-color@3.1.0 deduped invalid: "1 - 2" from node_modules/d3-scale/node_modules/d3-interpolate, "1 - 2" from node_modules/@nivo/colors/node_modules/d3-scale-chromatic, "1 - 2" from node_modules/@nivo/colors/node_modules/d3-interpolate


npm ERR! A complete log of this run can be found in: /Users/nestortobon/.npm/_logs/2024-01-19T06_27_42_820Z-debug-0.log
```

And well, just hope it works.
My use case is very simple and is not breaking, but I cannot guarantee this will work 100%
