### ISSUE TITLE
enter animation

### ISSUE THREAD

**Issue by wulucxy** [plouc/nivo#173]
@plouc thanks this vis repo a lot.

when i met a demand of barChart，like this https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/basic-column.html,  the enter animation is smooth。
and in pure d3，It's easy to implement this transition in `d3-transition`。

but i did't find the way to create enter animation in nivo，can you give me any tips to create the enter animation together with this great library?

thanks for your attention。

**Comment by plouc** [comment]
Hello @wulucxy,

nivo makes use of [react-motion](https://github.com/chenglou/react-motion), which creates physics based transition, so it does not have that kind of concept, d3 transition means relying on d3 to handle DOM, and I only use it for layout computing, sorry :(

**Comment by plouc** [comment]
However, if you set values to some really low values and after that set real values, it could works.
