### ISSUE TITLE
Add confidence intervals to bar, line, and scatter charts

### ISSUE THREAD

**Issue by TheMatrixMaster** [plouc/nivo#1730]
**Is your feature request related to a problem? Please describe.**
We are using Nivo to display predicted data points and we would like an easy way to display the confidence intervals of our predictions. 

**Describe the solution you'd like**
Add two properties `upperConfidence` and `lowerConfidence` to the data payload of the relevant chart components that would accept a numerical value to be displayed as a vertical/horizontal confidence interval line on the relevant data points. 

**Describe alternatives you've considered**
There is a storybook [example](https://nivo.rocks/storybook/?path=/story/scatterplot--adding-extra-layers) where an area shape is overlaid on a scatter plot to simulate a confidence area. However this solutions does not scale to other types of graphs such as bar graphs.

**Additional context**
<img width="80%" src="https://techcommunity.microsoft.com/t5/image/serverpage/image-id/72849i542DBE4AF424F248/image-size/large?v=v2&px=999" alt="1">

**Comment by ThePerfectLink** [comment]
A confidence interval band that's added to the line graph would still be excellent
