### ISSUE TITLE
ResponsiveBar prop types don't align with documentation

### ISSUE THREAD

**Issue by Tbhesswebber** [plouc/nivo#1735]
**Describe/explain the bug**

When applying the `label` prop to ResponsiveBar Nivo will only allow functions that return strings, rather than functions that return SVG Elements.

**To Reproduce**

1. Create a function that accepts BarDatum and returns an SVG element
2. Pass it to `<ResponsiveBar />`

**Expected behavior**

TypeScript allows me to pass a function that returns an SVGAElement without me having to cast the return type with `as unknown as string`.

**TypeScript**
TS 4.3.5

**Additional context**

This issue seems to stem from the fact that `BarSvgProps` extends `BarCommonProps`, which uses the Nivo core `PropertyAccessor`.  The second type parameter is `string`, which is true for Canvas charts, but for SVG charts, it should also allow `SVGAElement` (`PropertyAccessor<Datum, string | SVGAElement>`)

**Comment by Ayush11139** [comment]
Can someone tell me How to keep label values above bars in bargraph?

**Comment by rahulm-optimus** [comment]
Can someone just show an example how to do in  ResponsiveBar component in React or JS.
