### ISSUE TITLE
Export charts as Base64 image

### ISSUE THREAD

**Issue by jb-thery** [plouc/nivo#1747]
Hello, 

I think it would be a feature to be able to export graphics as base 64 images.

**Comment by jbty** [comment]
is it possible to pass a react ref to the nivo graphics to be able to recover the canvas and export it to base64 images with the method toDataURL() ?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by wyze** [comment]
Some charts support `forwardRef`. Which ones are you trying to export?

**Comment by jbty** [comment]
hi, I need this on Piechart and bar chart (canvas version)
