### ISSUE TITLE
How to add custom legend in pie chart

### ISSUE THREAD

**Issue by jameelakowsar** [plouc/nivo#1749]
**Describe/explain the bug**
code sandbox: https://codesandbox.io/s/sad-rgb-yb5d0?file=/src/App.js

Here I want to custom legend like below image.
![CustomLegend](https://user-images.githubusercontent.com/20105532/131284853-25c56477-d76f-48bd-be4a-f8ff01798075.png)

I am able to add custom legend label(Covered features 85), But I want to create exact like image (number should come in next line). Can you please let me know how can I achieve this.

**Comment by jameelakowsar** [comment]
@plouc

**Comment by plouc** [comment]
Creating such legend in SVG might be a bit challenging, I'd recommend that you create the legend in HTML outside of the chart, or if you really want to have it part of the SVG, you should create an extra layer, but you'll have to create everything manually anyway.
