### ISSUE TITLE
Marimekko animations

### ISSUE THREAD

**Issue by kaayso** [plouc/nivo#1750]
Hello, 

I'm trying to disable animations on marimekko chart  by switching `animate=false` but it doesn't work... It seems this props is not taking into account.
You can see this  bug on  https://nivo.rocks/marimekko/  by changing layout value for example. 

Thank you

**Comment by tkonopka** [comment]
Hi @kaayso. Is this still a bug, or has it been fixed since? (On the documentation website, changing layout as you suggest, the boxes now bounce with animate=true and just switch positions with animate=false.)

**Comment by plouc** [comment]
This issue has been resolved.
