### ISSUE TITLE
ResponsiveCalendar shown twice on mobile

### ISSUE THREAD

**Issue by alexus37** [plouc/nivo#1758]
**Describe/explain the bug**
I am using the `import { ResponsiveCalendar } from "@nivo/calendar";` component trying to recreate the example from https://nivo.rocks/calendar/ 
If I look at the resulting rendering on my browser even with a mobile device spoofed the result looks like I would expect. 

![Selection_406](https://user-images.githubusercontent.com/7422767/131923241-24445110-0e6e-4623-a09b-a249d1573cd2.png)

However, then I look at the same view with my phone RedMi Note 8 and the chrome browser (92.0.4515.159)
there are 2 calendars shown, switch screws up my design :/

![bug](https://user-images.githubusercontent.com/7422767/131923365-f0848058-6cfa-44cc-8d2b-d978026fd718.jpg)

**To Reproduce**
Here is my code to create the component:
```jsx
<ResponsiveCalendar
            data={data}
            from={`${year}-01-01`}
            to={`${year}-12-31`}
            emptyColor="#eeeeee"
            colors={["#C1C6E7", "#9DA6D9", "#8490D0", "#6574C4", "#3f51b5"]}
            margin={{ top: 40, right: 40, bottom: 40, left: 40 }}
            direction="vertical"
            yearSpacing={40}
            monthBorderColor="#ffffff"
            dayBorderWidth={2}
            dayBorderColor="#ffffff"
          />
```

**Expected behaviour**
Behave consistently between mobile and desktop.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 89.0.4389.128 

**Smartphone (please complete the following information):**
 - Device: Redmi note 8
 - OS: Android
 - Browser chrome
 - Version 92.0.4515.159

**Comment by plouc** [comment]
@alexus37, might be due to a timezone issue, time/date management in JS is a bit challenging... You can try to pass dates instead:
```
from={new Date(year, 0, 1, 0, 0, 0, 0)}
to={new Date(year, 11, 31, 23, 59, 59, 999)}
```
Ideally, you should memoize those with `useMemo` for example, to avoid creating a new date instance on each render.

**Comment by alexus37** [comment]
yes, that worked! Thanks for the hint with the useMemo hook. You would mind explaining to me that was the issue here, so I don't run into this again?

**Comment by plouc** [comment]
The issue is that the partial date passed as a string to the date constructor was probably using the timezone, with fully qualified dates, you don't have this issue.

**Comment by plouc** [comment]
For example her is what I get here in Japan:
<img width="410" alt="Screen Shot 2021-09-07 at 21 18 03" src="https://user-images.githubusercontent.com/501642/132343212-93d6fde6-ab28-4022-acff-8378e3a2d61f.png">
