### ISSUE TITLE
renderTick doesn't work in ResponsiveBarCanvas

### ISSUE THREAD

**Issue by JuliaVyl** [plouc/nivo#1759]
**Describe/explain the bug**
I am using _ResponsiveBarCanvas_  and when I try to use renderTick on some axis it doesn't even enter the function. (But renderTick works in _ResponsiveBar_.)

**To Reproduce**
Here is my code:
Component:
```
<ResponsiveBarCanvas
   axisLeft={{
     renderTick: TickFormatter,
   }}
   {...props}
 />
```
Function:
```
export const TickFormatter = (tick: AxisTickProps<string>) => {
  console.log('test');
  return <></>;
};
```

**Expected behavior**
We should see console.log message, but there is not message as it doesn't enter the function. (There is no problem when you use _ResponsiveBar_.)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 92.0.4515.159
 - Browser Firefox
 - Version 91.0.2

**Comment by plouc** [comment]
@JuliaVyl, this only work for SVG.

**Comment by JuliaVyl** [comment]
> @JuliaVyl, this only works for SVG.

Is there some other cases to wrap the axis text on canvas?

**Comment by itryapitsin2** [comment]
@plouc the renderTick is part of AxisProps type what is a parent for Canvas and SVG component and available in CanvasAxisProp https://github.com/plouc/nivo/blob/883b10ad02e3a0410462cc7485433f78ad272b45/packages/axes/src/types.ts#L49
If this callback is not available in the Canvas component, it would be nice to omit it from CanvasAxisProp or add callback support to renderAxisToCanvas function https://github.com/plouc/nivo/blob/883b10ad02e3a0410462cc7485433f78ad272b45/packages/axes/src/canvas.ts#L113
Or is there another solution?

**Comment by yairEO** [comment]
Please re-open this issue. 
I really need a way to style the ticks so they will be multiline with specific color and font-size (in Canvas)
