### ISSUE TITLE
TypeScript interfaces SankeyDataLink and SankeyDataNode are missing properties

### ISSUE THREAD

**Issue by masch712** [plouc/nivo#1763]
@nivo/sankey TypeScript interface `SankeyDataLink` should have a `value` property, and `SankeyDataNode` should have a `color` property.

These properties exist in the sample data generated at https://nivo.rocks/sankey/, but they are not defined in @nivo/sankey/index.d.ts, so TypeScript complains when I try to pass objects of type Data to the ResponsiveSankey component as the data prop.  

For example, typescript complains about this:
```typescript
import React from 'react';
import { Data, ResponsiveSankey } from "@nivo/sankey";

export const SankeyTypeBugExample: React.FC<any> = (props) => {
  const data: Data['data'] = {
    nodes: [
      {
        id: "node 1",
        color: "hsl(289, 70%, 50%)",
      },
      {
        id: "node 2",
        color: "hsl(289, 70%, 50%)",
      },
    ],
    links: [
      {
        source: "node 1",
        target: "node 2",
        value: 100,
      }
    ],
  };
  return (<ResponsiveSankey
    data={data}
  />);
}
```

TypeScript compile errors:
![image](https://user-images.githubusercontent.com/17676379/132119923-d5b7d042-6b16-44b6-b07d-d3f9dd8fae08.png)

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/1748, not released yet.
