### ISSUE TITLE
TimeRange - Allow specifying arrayOfWeekdays

### ISSUE THREAD

**Issue by anton-johansson** [plouc/nivo#1764]
**Is your feature request related to a problem? Please describe.**
I want to Monday to be the first row instead of Sunday.

**Describe the solution you'd like**
Should be easy to allow passing in `arrayOfWeekdays` as a property to `TimeRange` that is passed down to `computeWeekdays`:  
https://github.com/plouc/nivo/blob/d49a79034ba4fe13ed53f2163a0e511953fc61c0/packages/calendar/src/TimeRange.tsx#L114

Or maybe more clean: A property to indicate which is the first day of the week.

**Describe alternatives you've considered**
None.

**Comment by plouc** [comment]
@anton-johansson, if you think the solution is easy, please do not hesitate to submit a PR ;)

**Comment by aried3r** [comment]
@plouc, what do you think about https://github.com/plouc/nivo/pull/613?

**Comment by anton-johansson** [comment]
I'll try to get the project set up locally and see what I can do. I'd guess "first day of the week" is the cleanest approach?

**Comment by anton-johansson** [comment]
Won't be as easy as I initially thought! I looked too fast, `arrayOfWeekdays` is just for the labels. But I need to be able to specify those as well (I want to translate them in the appropriate language), so I might attempt to fix both of those issues in the same PR.

**Comment by aried3r** [comment]
@anton-johansson, in case #613 solves the problem of the first-day-of-the-week problem (I haven't checked out and run the code in the PR), translation for the calendar component should be doable using `monthLegend` (see [docs](https://nivo.rocks/calendar/canvas/)). For example using the [`.toLocaleString()`](https://caniuse.com/mdn-javascript_builtins_date_tolocalestring) API or other `Intl` APIs, depending on which browsers you support.

I.e.:

```JS
const date = new Date()
const month = date.toLocaleString('it-IT', { month: 'long' });
console.debug(month) // Prints "settembre"
```
