### ISSUE TITLE
Number y value on ResponsiveLine

### ISSUE THREAD

**Issue by th0th** [plouc/nivo#177]
I have data like the following:

```
const data = [
    { x: 1, y: 10 },
    { x: 2, y: 20 },
    { x: 3, y: 30 },
];
```

And I am rendering chart:

```
<ResponsiveLine
    data={[
        { id: 'data', data },
    ]}
    curve="monotoneX"
/>
```

Chart renders OK, but I get a warning on the console:

> Warning: Failed prop type: Invalid prop `slices[0].id` of type `number` supplied to `LineSlices`, expected `string`.

Warning goes away when I use strings for x axis but the document says x can be a number, too.

In my case, x is unix timestamp and values should be handled accordingly.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/222
