### ISSUE TITLE
[ResponsiveLine] Chart with data not shown correctly

### ISSUE THREAD

**Issue by Paul6552** [plouc/nivo#1772]
**Describe/explain the bug**
When you look on the chart of ResponsiveLine on the [webpage](https://nivo.rocks/line/) you can see the lines "norway", "germany"etc.
![Bildschirmfoto vom 2021-09-09 10-11-46](https://user-images.githubusercontent.com/25934591/132648712-bf0e5a68-a559-4932-a5e1-421b66310d39.png)

When we now check the line "japan" we see "plane" with the following y data:  
```
"id": "japan",
    "color": "hsl(127, 70%, 50%)",
    "data": [
      {
        "x": "plane",
        "y": 17
      },
```
When we check this on the chart, it is correctly shown:
![2](https://user-images.githubusercontent.com/25934591/132649061-ad14f7bd-2aed-4515-99c3-45907fdac29f.png)

But when we check the other line, for example "us" with the following  y data:
```
  "id": "us",
    "color": "hsl(178, 70%, 50%)",
    "data": [
      {
        "x": "plane",
        "y": 146
      },
```
it is wrong. US has y 146 but is shown **ABOVE 300**:
![3](https://user-images.githubusercontent.com/25934591/132649554-1d383e77-a9a2-4f9b-99ba-464025089a2d.png)
The data is also wrong on the lines "Germany" and "norway".

**Expected behavior**
The data should be shown correctly for every line.

**Additional context**
"@nivo/core": "^0.73.0",
"@nivo/line": "^0.73.0",
Browser "Firefox and Chrome latest"

**Comment by plouc** [comment]
@Paul6552, this is correct, values are stacked:

<img width="298" alt="Screen Shot 2021-09-09 at 17 29 12" src="https://user-images.githubusercontent.com/501642/132651406-e568a69a-3343-420b-8c4f-d391cb852dd0.png">

Just change `stacked` to `false` if you don't want this behavior.

**Comment by Paul6552** [comment]
@plouc  My colleagues and me right now:
![Alt Text](https://thumbs.gfycat.com/DishonestLimpDanishswedishfarmdog-max-1mb.gif)

thank you

**Comment by plouc** [comment]
@Paul6552 you're not the first one :)
