### ISSUE TITLE
The scroll is not working in Custom Tooltip for nivo Line Charts . can anyone help me on this?

### ISSUE THREAD

**Issue by santhoshCharles** [plouc/nivo#1775]
Hi I have more events to render in the tooltip so I need the scrollbar but it's not working

sliceTooltip={({ slice }) => {
            console.log('slice', slice)
            return(<div className="stacked-line-tooltip">
              <div>Date</div>
              <div className="tooltip-event-wrapper">
              {slice.points.map( events => {
                return (
                  <div>{events.serieId}</div>
                )
              } )}
              </div>
            </div>)
          }}

stacked-line-tooltip {
  height: 350px;
  width: 230px;
  background-color: rgb(255, 255, 255);
  box-shadow: rgb(203 215 233) 0px 2px 4px 0px;
}

.tooltip-event-wrapper {
  height: 120px;
  overflow: auto;
}

**Comment by plouc** [comment]
@santhoshCharles, I don't understand what you're trying to achieve exactly, but tooltips being displayed only on hover, I'm not sure scroll would lead to good UX.

Could you please use the issue template to provide the necessary information, and provide a code sandbox with what you tried? Also you can format your code in GitHub, it's easier to read.
