### ISSUE TITLE
Getting NaN in Choropleth path from geoJSON file

### ISSUE THREAD

**Issue by mattandryc** [plouc/nivo#1777]
**Describe/explain the bug**
NaN values are pushed to the "d" attribute in path

**To Reproduce**
Use the states.json file → https://github.com/mattandryc/geojson-states with the MyResponsiveChoropleth  example from the [documentation](https://nivo.rocks/choropleth/)

import { ResponsiveChoropleth } from '@nivo/geo'
import states from ".states.json"

const MyResponsiveChoropleth = ({ data /* see data tab */ }) => (
    <ResponsiveChoropleth
        features={states.features} .../>

     
**Error message**
Error: <path> attribute d: Expected number, "…7.7845336326942,NaNL190.17653904…

**Comment by plouc** [comment]
@mattandryc could you please create a codesandbox reproducing the issue? It would help, thank you.

**Comment by mattandryc** [comment]
@plouc https://codesandbox.io/s/nivo-geo-demo-forked-rs4s2

**Comment by plouc** [comment]
Thank you @mattandryc, I'll try to have a look at this.

**Comment by mattandryc** [comment]
@plouc here's the source for the geoJson in case that's helpful.

https://observablehq.com/@d3/u-s-map

Converted topoJson to geoJson using the method below.
`topojson.feature(us, us.objects.nation)`

**Comment by mattandryc** [comment]
Has anyone implemented choropleth with anything other than the world map (world_countries.json)?

**Comment by mattandryc** [comment]
@plouc I put together a hacky workaround using [dirtyreprojectors](https://github.com/developmentseed/dirty-reprojectors) here.

https://codesandbox.io/s/nivo-geo-albersusa-demo-uyit8

This is more of a feature request, less of a bug → a more succinct solution would be adding a GeoProjectionType for [d3.geoAlbersUsa()](https://github.com/d3/d3-geo#geoAlbersUsa) on the GeoMap component.
