### ISSUE TITLE
PieChart possibility to "preselect/highlight" a slice

### ISSUE THREAD

**Issue by vincentaudebert** [plouc/nivo#1781]
**Is your feature request related to a problem? Please describe.**
I have a pie chart with a custom HTML legend. At the moment it is possible for me to hover a slice inside the pie chart and with the onMouseEnter it highlights the corresponding legend.

**Describe alternatives you've considered**
I would like to be able to do the opposite. Hovering the custom legend and it hightlights the corresponding pie chart slice.
Sadly there is no way to "force select" a slice. 
I reckon a prop `selected` using the `id` as a identifier could be nice? maybe an array of ids if user wants to select many? (in the case of a checkbox selection in the legend?)

**Additional context**
Screenshot example when I hover a pie chart slice
<img width="1038" alt="Screenshot 2021-09-22 at 12 09 07" src="https://user-images.githubusercontent.com/3360430/134325141-6feb5d69-22bb-48e9-89d9-eaafdae986fa.png">

What do you think?

**Comment by vincentaudebert** [comment]
bump if possible 👌

**Comment by ortonomy** [comment]
it's not stale :(

**Comment by antonmelbardis** [comment]
bump

**Comment by gornyyvladimir** [comment]
+1

**Comment by laura-gheorghe** [comment]
+1
