### ISSUE TITLE
Formatting Gridlines

### ISSUE THREAD

**Issue by gah112** [plouc/nivo#1784]
Gridlines are an important visual feature in charts that allow users to quickly compare values and assess differences. However, Gridlines with too much weight can distract from the data being displayed. One way to avoid this is to use dotted or dashed lines instead of solid lines.

Nivo does not support Gridline styling. I am proposing a `lineStyle` property in the `grid.line` object which can accept values like `'dotted'` or possibly even `'--'`,`'.'`, etc.

**Comment by plouc** [comment]
@gah112, nivo does support gridline styling, please see https://codesandbox.io/s/91498pz0wo?file=/src/index.js.
