### ISSUE TITLE
Error using legend label customizing in Radar

### ISSUE THREAD

**Issue by minemanemo** [plouc/nivo#1785]
**Describe/explain the bug**
- We can't customize legend label in Radar component ([go source](https://github.com/plouc/nivo/blob/master/packages/radar/src/hooks.ts#L80))
- Type document and issue said "you can customize legend label!!!" ([go type docs 1](https://github.com/plouc/nivo/blob/master/packages/radar/src/types.ts#L126), [go type docs 2](https://github.com/plouc/nivo/blob/master/packages/legends/src/types.ts#L67), [go type docs 3](https://github.com/plouc/nivo/blob/master/packages/legends/src/types.ts#L58), [go issue](https://github.com/plouc/nivo/issues/791#issuecomment-564522268))

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/s/nivo-radar-bug-report-ftrmw)
2. Open `src/App.tsx` and see 31 line
3. legends props's data property is not working...
4. See browser

**Expected behavior**
- expected results(Legends): `🟠 My consumption` `🔵 Average` `🟢 Top 11%`
- actual result(Legends): `🟠 myc` `🔵 avg` `🟢 top`

**Screenshots**
- Please check codesandbox

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Browser: chrome
 - Version: 93.0.4577.82

**Additional context**
I'll fork and pull request

**Comment by plouc** [comment]
@minemanemo it's just supported for a few chart types.
