### ISSUE TITLE
Use of nivo chart component in react project

### ISSUE THREAD

**Issue by riteshnus** [plouc/nivo#179]
Guys, i have check most the places to look the sample example to use the nivo line in my react project. Whenever i try to give the render 'ResponsiveLine' it render nothing on page. Could please suggest to see the examples of NIVO chart component.

**Comment by wyze** [comment]
Likely the container component will need either a fixed height or width for the responsive components to work.

**Comment by wyze** [comment]
You need something like this:

```js
class Container extends Component {
  render() {
    return (
      <div style={{ height: '10em', width: '10em' }}>
        <Chart1 />
      </div>
    )
  }
}
```

Where `Chart1` refers to the code you posted above.

**Comment by riteshnus** [comment]
Not rendering anything. What could be the problem?

class Chart1 extends Component {
    render(){
        return (
            <div>
                <ResponsiveStream
                    data={constant.stream}
                    margin={{
                        "top": 50,
                        "right": 110,
                        "bottom": 50,
                        "left": 60
                    }} 
                 />
            </div>
        )
    }
}

**Comment by JesperWe** [comment]
The requirement for a set width/height really should be include in the example and docs. I spend a lot of time scratching my head looking at emptyness for the same reason.

**Comment by riteshnus** [comment]
I found the workaround. Set width and height of the container, also include the key array when required. Thanks for wonderful library.

**Comment by abhijit-padhy** [comment]
> Whats wrong in the below code. I just copy the code of the example code.
> 
> ```
> class Chart1 extends Component {
>     render(){
>         return (
>             <div className="widget">
>                 <h1>First chart 1</h1>
>                 <ResponsiveStream
>                     data={constant.stream}
>                     margin={{
>                         "top": 50,
>                         "right": 110,
>                         "bottom": 50,
>                         "left": 60
>                     }}
>                     axisBottom={{
>                         "orient": "bottom",
>                         "tickSize": 5,
>                         "tickPadding": 5,
>                         "tickRotation": 0,
>                         "legend": "",
>                         "legendOffset": 36
>                     }}
>                     offsetType="none"
>                     fillOpacity={0.85}
>                     borderColor="#000"
>                     defs={[
>                         {
>                             "id": "dots",
>                             "type": "patternDots",
>                             "background": "inherit",
>                             "color": "#2c998f",
>                             "size": 4,
>                             "padding": 2,
>                             "stagger": true
>                         },
>                         {
>                             "id": "squares",
>                             "type": "patternSquares",
>                             "background": "inherit",
>                             "color": "#e4c912",
>                             "size": 6,
>                             "padding": 2,
>                             "stagger": true
>                         }
>                     ]}
>                     fill={[
>                         {
>                             "match": {
>                                 "id": "Paul"
>                             },
>                             "id": "dots"
>                         },
>                         {
>                             "match": {
>                                 "id": "Marcel"
>                             },
>                             "id": "squares"
>                         }
>                     ]}
>                     animate={true}
>                     motionStiffness={90}
>                     motionDamping={15}
>                     legends={[
>                         {
>                             "anchor": "bottom-right",
>                             "direction": "column",
>                             "translateX": 100,
>                             "itemWidth": 80,
>                             "itemHeight": 20,
>                             "symbolSize": 12,
>                             "symbolShape": "circle"
>                         }
>                     ]}
>                 />
>             </div>
>         )
>     }
> }
> ```

Check if height is provided to the parent div element inside .widget class.

**Comment by mckinleymedia** [comment]
Yeah. I figured min-height would do the trick. Nope. You need height specifically.

**Comment by snsheth55** [comment]
So after specifying height or width, the issue I am having is how to make the container responsive if width and height are fixed?
