### ISSUE TITLE
Tooltip performance of large dataset

### ISSUE THREAD

**Issue by hoi82** [plouc/nivo#1790]
**Is your feature request related to a problem? Please describe.**
 When using large dataset to a LineCanvas (over 1k points), the tooltip is not moving smoothly.

**Describe the solution you'd like**
Prevent unnecessary re-rendering of a whole component.

**Describe alternatives you've considered**
Looking to codes, a mouse hover event sets position state in LineCanvas and this cause re-rendering. 
My solutions are,

1. Wrapping tooltip to a seperated component and pass container ref & necessary properties. (like HeatMapCanvas)
2. Directly set tooltip's translate position using mouse position.

**Additional context**

**Comment by itsyoboieltr** [comment]
bump
