### ISSUE TITLE
Changing color of horizontal labels

### ISSUE THREAD

**Issue by cangoktas** [plouc/nivo#1795]
I'm trying to achieve the following layout:
![Screen Shot 2021-10-07 at 12 54 06](https://user-images.githubusercontent.com/4026342/136362395-485505db-6724-4783-a1ea-673b65b43c72.jpg)

So I have 2 y-axis labels, each represent a line, and the bottom labels should be another color (grey). Using previously created issues I was able to create 2 line charts on top of each other to achieve 2 different-colored y-axis labels but the bottom one gets the first chart's color obviously. Is there a way to recolor only the bottom (horizontal) labels?

**Comment by Speckope** [comment]
You can create a custom tick on each axis with renderTick propperty in relevant axis prop.
In Your example, it would be axisBottom prop.

Try inserting something like this:
```TSX
renderTick: ({ textAnchor, textX, textY, value, x, y }) => {
            return (
              <g
                transform={`translate(${x},${y})`}
                style={{
                  fill: 'grey',
                }}
              >
                <text
                  x='0'
                  y='0'
                  textAnchor={textAnchor}
                  transform={`translate(${textX},${textY})`}
                >
                  {value}
                </text>
              </g>
            );
          },
```
In this example, the fill property on g tag will determine the colour of Your tick.
Hope it helps!
