### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by redi-lernera** [plouc/nivo#180]
The full message is:   Warning: Encountered two children with the same key, `L1.87.83999837239584`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version

Whats causing this?  Is it possible that its looking for each point in the line graphs to have its own 'react key' ?  Is each data point a react element?

**Comment by riteshnus** [comment]
@redi-lernera the graph can not take the two same keys as input, Instead you can format your keys as `format: value => moment.unix(value * 60).format('HH:mm'),`

**Comment by plouc** [comment]
@redi-lernera which component are you using? what's the dataset? can you provide some running example using https://codesandbox.io/ for example?

**Comment by designjockey** [comment]
@plouc I am encountering the same issue and created a codesandbox - https://codesandbox.io/s/v892ozo0y7

Happy to help fix it in a PR if you can point me in the right direction.

**Comment by plouc** [comment]
@designjockey, that's because you use `Line` instead of `ResponsiveLine`, when using non responsive component, you must pass explicit `height` & `width`.

**Comment by DrunkenDuck** [comment]
Hi, I am facing the same issue using the ResponsiveLine component: https://codesandbox.io/s/laughing-joji-rxusqq
It seems that the y value is used as key in place of the x value. 

Would it be possible to specify a key for each data pair?

**Comment by StorytellerCZ** [comment]
Bump, in my case I have multiple charts on my page and sometimes the values repeat. Would be great if I could pass `key` in the data that would be applied over the default option.

**Comment by jagandecapri** [comment]
@StorytellerCZ Did you find any workaround for the warning? I'm using multiple ResponseHeatMap and getting the warning.

**Comment by gercog1** [comment]
yeah, same issue here @plouc 

Can I specify the key somehow?

**Comment by Joshua-hypt** [comment]
Why is this closed if @DrunkenDuck issue not resolved? 😫
