### ISSUE TITLE
Allow overlap in Donut

### ISSUE THREAD

**Issue by AviusX** [plouc/nivo#1801]
**Is your feature request related to a problem? Please describe.**
I've been trying to get my donut chart lines to overlap, but haven't been able to do so (in a good way anyway). Currently, I'm making the `borderWidth` so large that it overflows onto other lines and causes the overlap-
![image](https://user-images.githubusercontent.com/55204295/136799172-54d5b4f7-54ec-4691-9c1b-a78ed12b7d40.png)

This is an extremely hacky way to do this, but it works. However, the problem with this is that I can't use gradients because borders can't have gradients right now. I tried making the `padAngle` negative, but that doesn't work.

**Describe the solution you'd like**
Allow lines to overlap with a negative `padAngle`. Optionally, also allow borders to have gradients, because while it's not a good way to do what I'm trying to do, that'd also be a nice feature to have.

**Describe alternatives you've considered**
Add another overlap property specifically for this.

**Additional context**
I've already attached a screenshot of what I'm currently doing, but just for reference, this is what I'd actually like to do-
![image](https://user-images.githubusercontent.com/55204295/136800017-3253bc89-ea50-407b-958f-b71f1b629b61.png)

**Comment by plouc** [comment]
The layout of this chart is computed by D3 under the hood, which doesn't support such feature, so I think the best option is to use the borders unfortunately.
