### ISSUE TITLE
Cannot update draw order for svg. 

### ISSUE THREAD

**Issue by tomemmerson** [plouc/nivo#1810]
I would like to overlap my bars slightly so that I can have a custom bar with a top border radius without this horrible white gap. I can't seem to find any options for changing draw order though?

<img width="313" alt="Screenshot 2021-10-20 at 12 35 07" src="https://user-images.githubusercontent.com/8326732/138085358-76a463bd-9bd0-4983-b6f8-90621720cf35.png">

It seems the SVG order of the bars is random, which means sometimes if I extend the top bar over the bottom one, the bottom bar is hidden by the top one. 

It would be awesome to be able to set the draw order some how

Thanks
Tom

**Comment by nleapai** [comment]
I can't speak to the overlapping part, but in terms of ordering the bar segments, I'm using `ResponsiveBar` and it uses the `keys` property to determine the order.

For example, if my `data` looks like this:
```
[
    {
      "id": "bar1",
      "sample_1": 80,
      "sample_2": 50,
      "sample_3": 100
    },
    {
      "id": "bar2",
      "sample_1": 160,
      "sample_2": 80,
      "sample_3": 140
    },
    {
      "id": "bar3",
      "sample_1": 100,
      "sample_2": 70,
      "sample_3": 150
    }
]
```

the `keys` prop would be:
```
[
    "sample_1",
    "sample_2",
    "sample_3"
]
```

And in this case, the "sample_1" segment would be on the bottom of the stack. 

On a related note, it's similar mechanism for the ordering of the full bars themselves, but that's based on the order of the objects in the `data` array. So from my example, if the object with id: `bar3` were first in that array, it would be the leftmost bar in the chart.
