### ISSUE TITLE
How does calendar color responde to days' value?

### ISSUE THREAD

**Issue by primelyw** [plouc/nivo#1811]
There is a senario that I need.
Days' value in calendar data is dispersed, which is [1, 2, 3, 4, 5, 6]. Each value responde to one color. 
1 = 'red'
2 = 'yellow'
3 = 'green' 
4 = 'blue' 
5 = 'purple'
6 = 'orange'
How can I implement it in my react code?

No doc mentioned this situation.

**Comment by kevinlens** [comment]
bump

**Comment by kevinlens** [comment]
never mind I found the solution
