### ISSUE TITLE
Ability to pass a custom color scheme to render

### ISSUE THREAD

**Issue by Nikhilnair48** [plouc/nivo#1815]
First off, thanks for the library! It's been a great experience so far.

**Is your feature request related to a problem? Please describe.**

Yes. I'd like to pass down an array of colors to be used for the color scheme of any given chart (currently using Stream, Pie & Line)

**Describe the solution you'd like**

A prop on the chart level component that allows me to pass an array for the color scheme

**Describe alternatives you've considered**

I tried:
- using the existing schemes
- looking for any similar requests from the past. [Found this one](https://github.com/plouc/nivo/issues/1601), but the EDIT from the post doesn't work as the prop doesn't exist
- looking into the library to see if it's customizable, but was unable to find any relevant prop

**Additional context**

Any help would be greatly appreciated!

**Comment by plouc** [comment]
You can pass `colors={['#ff0000', '#ff00ff', ...])` to most charts, the way the colors are applied to the bar chart is by assigning a color to each key, if you want a different behavior, for example having each bar with a different color, then you can also pass a custom function: `colors={(datum) => '#ff0000'}`, where you can use the datum to implement some custom logic based on the data. The pie and stream charts should work just by passing an array.
