### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by christopherjbaker** [plouc/nivo#1818]
**Is your feature request related to a problem? Please describe.**
Not a specific problem so much as a lack of a good solution. It would be really cool if there was a gantt chart module that matched the same design as the rest of your platform. I'm faking one using a stacked bar chart right now, but the `keys` prop got weird and I have to override the `colors` prop in weird ways, not to mention coercing the data from time series into what a stacked bar chart needs was...

**Describe the solution you'd like**
I feel like "gantt chart" covers it pretty well =P. Given your approach to other graph types, I'm sure this would go well too.

**Describe alternatives you've considered**
There are a small handful of react gantt chart modules, but they're fairly ugly and hard to work with.

**Comment by dboursaud** [comment]
+1
It would be really great to have a Nivo Gantt chart!

**Comment by christopherjbaker** [comment]
Bump. Bot shouldn’t be closing feature requests.

**Comment by samjowen** [comment]
This would be a really great feature to have.

**Comment by samjowen** [comment]
@christopherjbaker - would it be possible for you to share your Gantt chart code?

**Comment by christopherjbaker** [comment]
@samjowen I don't even remember what project I was working on when I opened this ticket. Sorry.

**Comment by e-for-eshaan** [comment]
bump

**Comment by e-for-eshaan** [comment]
Could really use this feature!

**Comment by alexbadoi** [comment]
i also want it
