### ISSUE TITLE
Export setActiveId to custom Arc context

### ISSUE THREAD

**Issue by Rendfold** [plouc/nivo#1820]
**Is your feature request related to a problem? Please describe.**
Hello, I am currently trying to leave Arc active on Pie chart, when I am clicking on it, even if my mouse left it. So that small addition could really be helpful

**Describe the solution you'd like**
There is a small fix for this, basically add setActiveId to `usePieLayerContext`

**Comment by Mangor1no** [comment]
It would be nice if this feature is included in the library

**Comment by ortonomy** [comment]
Why was this closed!?!?! I totally need this. Is this lib abandoned?

**Comment by theomessin** [comment]
+1

**Comment by gornyyvladimir** [comment]
+1
