### ISSUE TITLE
Is there a way to remove arc link labels in Pie charts?

### ISSUE THREAD

**Issue by Deveshb15** [plouc/nivo#1821]
Was looking to remove the arc labels as I already added a custom tooltip, removed all the attributes related to arc link label but still it's visible, is there a way to remove them?

**Comment by plouc** [comment]
@Deveshb15, you can set `enableArcLabels=false` and `enableArcLinkLabels=false` if you wish to disable all labels.

**Comment by caffeine-overflow** [comment]
> @Deveshb15, you can set `enableArcLabels=false` and `enableArcLinkLabels=false` if you wish to disable all labels.

enableArcLabels=false and enableArcLinkLabels=false not doing anything, it is still visible

**Comment by Deveshb15** [comment]
@caffeine-overflow it worked for me, can you share the screenshot so that I can help you?

**Comment by shubuu97** [comment]
> 

You might not be using the latest version

**Comment by shubuu97** [comment]
> 

You might not be using the latest version
