### ISSUE TITLE
Question. Label of days in TimeRange calendar

### ISSUE THREAD

**Issue by csgomezg0** [plouc/nivo#1822]
...

**Comment by csgomezg0** [comment]
Hi in the graph timerange, I have in the vertical axis: monday, ...,sunday, but i want other text, in other language, the day of week (in spanish). Are there some solution for this?


This is my options for my graph, but i dont get change the label of the days.

Note: I also try in this link: https://codesandbox.io/s/b57qd?file=/src/components/TimeRangeChart/TimeRangeChart.js:274-283, I didn't get.

`
from:"2021-10-01",
      to:"2021-10-31",
emptyColor:'#f5f5dc',
      margin:{ top: 40, right: 40, bottom: 100, left: 40 },
      dayBorderWidth:2,
      dayBorderColor: '#f5f5dc',
//monthLegend:(year, month) => Months[month],
dayLegend:(month, day) => Days213[day],
      legends:[
          {
		label:["Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"],
              anchor: 'bottom-right',
              direction: 'row',
              justify: false,
              itemCount: 4,
              itemWidth: 42,
              itemHeight: 36,
              itemsSpacing: 14,
              itemDirection: 'bottom-to-top',
              translateX: -60,
              translateY: -60,
              symbolSize: 20
          }
      ],
weekdayTicks:[0,1,2,3,4,5,6],
`
Thanks.

**Comment by Oxunjon1029** [comment]
I need to change weekdays text in my own language like I changed month names , how can I do that?
