### ISSUE TITLE
Using data objects with keys

### ISSUE THREAD

**Issue by rweller59** [plouc/nivo#183]
I am trying to use the nivo library but really struggling with datasets that do not have keys which is my perception of what is required (at least for bubble charts). I always use keys which makes access and modification of object arrays so much easier. Is there any way to use nivo with keyed objects or do I really have to convert everything whenever I pass a data object to nivo?

**Comment by plouc** [comment]
Hello @rweller59, can you please provide an example of what you're trying to achieve?

**Comment by rweller59** [comment]
Using nivo example data model below, lets assume I want to dynamically change the name of the first child from "viz" to "viz1". In order to access, I need to iterate through to find because the "children" key is common. If "children" key was unique (say child1, child2...) I could access directly like array[child1].name
I realize that this is trivial here but I've got some deeply nested objects so thought I'd ask if this is possible or maybe I'm mis-understanding.
{
  "name": "nivo",
  "color": "hsl(42, 70%, 50%)",
  "children": [
    {
      "name": "viz",
      "color": "hsl(21, 70%, 50%)",
      "children": [
        {
          "name": "stack",
          "color": "hsl(185, 70%, 50%)",

**Comment by plouc** [comment]
@rweller59, you shouldn't access only a part of the data dynamically, otherwise the data ref will remains identical and React won't see the change, data manipulation should be managed outside of the component.

You can use something like `lodash` [set](https://lodash.com/docs/4.17.10#set) function which can be really handy:

```javascript
_.set(deepObject, '[0].children[0].children[0].name', 'whatever')
```

**Comment by plouc** [comment]
Otherwise, you can traverse the tree and create a map of all nodes, keyed by path:

```javascript
const flatRefs = {
    'nivo': { /*…*/ },
    'nivo.viz': { /*…*/ },
    'nivo.viz.utils': { /*…*/ },
    // …
}
```
