### ISSUE TITLE
Live data tooltip NPE when hovering over disappearing cell

### ISSUE THREAD

**Issue by michaelg9** [plouc/nivo#1834]
**Describe/explain the bug**
I am using nivo heatmap latest version with live data and there's a null pointer exception happening when I'm hovering over a cell / row that is about to be removed from the dataset.
I refer to live data as a dataset that is constantly updated and new rows are added while old ones are removed
When you hover over a cell, the cell focuses and its tooltip appears. Even if the row moves up because a new row was added below it, that cell will still be the active cell until I move the cursor
If I don't move the cursor and that row disappears, then the component crashes with this error:
`Cannot read properties of undefined (reading 'xKey')

    at cell (https://2k6uc.csb.app/node_modules/
    nivo/heatmap/dist/nivo-heatmap.es.js:260:35
    at eval (https://2k6uc.csb.app/node_modules/
    nivo/heatmap/dist/nivo-heatmap.es.js:395:21
    at eval (https://2k6uc.csb.app/node_modules/
    nivo/heatmap/dist/nivo-heatmap.es.js:394:18`
 

**To Reproduce**
1. Go to https://codesandbox.io/s/nivo-playground-forked-2k6uc?file=/src/index.js
2. Hover your cursor over one of the top row cells and leave it there
3. The row will move up every 5 seconds and the first row is removed from the data set. When your row is removed, the component will crash

**Expected behavior**
I expect the selected cell state to reset and the component to not crash

**Screenshots**
![demo](https://user-images.githubusercontent.com/15193728/141119191-069e745a-e3b7-440d-95ab-fb240d88e8b8.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**
This is reproduced in the latest version of nivo on the codesandbox but also on 0.65.1 which is the version I use in my app
This library rocks btw, thank you for maintaining it!:D

**Comment by natBizitza** [comment]
This issue is still reproducible.
