### ISSUE TITLE
Add more configurability for line series styling

### ISSUE THREAD

**Issue by evantrimboli** [plouc/nivo#1837]
**Is your feature request related to a problem? Please describe.**
Trying to customize the display of the line series is more difficult than it needs to be. Specifically, the line width or style.

**Describe the solution you'd like**
`lineWidth` already has a numeric property, however to extend it:
- Allow it to be a function which would take a parameter (id, index etc) to allow customization per series
- Add a similar property to control the line style (dashed, dotted etc)

Maybe they could be combined into a single property:
```
lineStyle={(id) => {
  switch (id) {
    case 'foo':
      return {
        width: 1,
        style: 'dashed',
        opacity: 1,
      }
    case 'bar':
      return {
        width: 2,
      }
  }
}}
```

**Describe alternatives you've considered**
I have seen the `DashedLine` example, however it's not very discoverable and seems overly complex, especially since it's already dealing with line width.

**Additional context**

**Comment by evantrimboli** [comment]
Bump. While I realise the existing API allows for a fairly broad range of features, it's cumbersome if you want to modify something simple.

**Comment by ASchwad** [comment]
Agreed upon, looking for this enhancement too
