### ISSUE TITLE
Bar in grouped mode: Unwanted gaps for unused keys

### ISSUE THREAD

**Issue by strblr** [plouc/nivo#1840]
**Describe/explain the bug**

This issue explains it well but was not resolved: https://github.com/plouc/nivo/issues/950

In short, when rendering a bar chart in grouped mode, the keys that are not used result in weird gaps between the bars, when one would expect that space to be skipped entirely.

**To Reproduce**
[Link to sandbox](https://codesandbox.io/s/nivo-bar-callback-after-draw-forked-uuriv)

1. Created a grouped bar chart
2. Specify an array of keys
3. In some data items, leave some keys out
4. See the gaps

**Expected behavior**

No gap.

**Comment by plouc** [comment]
I guess the fact that white space is skipped might not necessarily what users necessarily want, personally I prefer to maintain those gaps so that the bars are always placed at the same position in each group. This could be an enhancement for the current API though, but it's not planned atm.

**Comment by strblr** [comment]
@plouc Alright I understand, will have to go with a custom layer for now then.

**Comment by strblr** [comment]
@plouc The gap skipping feature would really be nice to be added as an option. After playing a bit around, I'm really confused about how to add a custom bars layer that would also handle the tooltips and animations the way the default bars do.

**Comment by wwright216** [comment]
Bump

**Comment by damianr13** [comment]
In case anyone else finds this, I posted my proposed work around for a limited use case as a comment to #648
