### ISSUE TITLE
[Radar] More label and chart customization

### ISSUE THREAD

**Issue by SafaAlfulaij** [plouc/nivo#1842]
**Is your feature request related to a problem? Please describe.**
The radar chart currently has some customization options that are great, but isn't enough.
For example, there is no way for the label to access the full data (id and value) to represent more useful information.
In the "Custom Label Component" story for example, we are using `Math.random()` to display the percentage. How to display the actual percentage in the label?

Even the dot symbol. We don't have access to the data the dot is representing.

**Describe the solution you'd like**
Provide full access to the id and value in the different components we can customize in radar, _exactly as in the tooltip_.

**Describe alternatives you've considered**
Have the data as a global value and use that?
Sub-class?

**Comment by SafaAlfulaij** [comment]
This still needs feedback from developer :-)

**Comment by tkonopka** [comment]
Hi @SafaAlfulaij 

Customizing labels can be achieved via `gridLabel`, as in the story/example that you mentioned. Such labels don't typically depend on the values being plotted on the chart, and I guess that is why those values are not passed to the label-generating function.

Customizing labels on the dots can be achieved via `enableDotLabel` and `valueFormat`.

Other effects can be achieved via custom layers. Those receive a data object that is quite complete. Here is an example where the custom layer displays a circle on the data point with the max value. 

<img src="https://user-images.githubusercontent.com/7260190/168260996-22ebe400-f85d-4a71-9dbc-afd794a2bd2a.png" width=600 />

https://codesandbox.io/s/agitated-microservice-u2g4h5?file=/src/App.js

In principle, you could use such layers to create custom labels.

**Comment by SafaAlfulaij** [comment]
I ended up using a context passing the full data and `find`ing the slice the label is presenting.
The use case I had is that the color of the label would change depending on the value, perhaps only when hovered, or clicked, etc. I think it's more safe to just pass everything to the component, and let developers handle their edge cases, instead of limiting it.

**Comment by tkonopka** [comment]
Glad you found an approach that works for you :smile:
