### ISSUE TITLE
Unnecessary console logs are printed in ResponsiveRadialBar

### ISSUE THREAD

**Issue by hoi82** [plouc/nivo#1843]
**Describe/explain the bug**

Unnecessary console logs are printed in ResponsiveRadialBar.

**To Reproduce**
Check console logs in browser.

**Expected behavior**
Any console logs should not be displayed.

**Screenshots**

<img width="426" alt="Screen Shot 2021-12-02 at 5 33 54 PM" src="https://user-images.githubusercontent.com/13937539/144386480-a81db3b8-100b-4504-acc3-7d14a1546b92.png">

nivo-radial-bar.es.js -> 517 line

console.log(innerRadiusRatio);

It seems like this is the reason of the issue.

**Comment by benjamintd** [comment]
This was fixed in https://github.com/plouc/nivo/pull/1830, but unfortunately no new release was created since then.
