### ISSUE TITLE
Show value in label of sankey diagrams or make label customizable

### ISSUE THREAD

**Issue by hannesmanoe** [plouc/nivo#1848]
**Use Case:**
I would like to know if there is a way to display the value of a node inside the label. For example **`Raul: 100`,  `Marcel: 30`** and so on. Basically something like it is done in [this Sankey Builder here](https://sankeymatic.com/build/). 

**My Opinion:**
I haven't found an option in the documentation to add the value to the label. So another way I can think of to achieve this behavior is to be able to customize the label. But I haven't found an option for that in the documentation either.

**P.S.:**
If anyone has a workaround or other idea on how to do this, I would appreciate hearing from you 🙏

**Comment by plouc** [comment]
You should be able to pass a custom function to the `label` property, it'll receive the node data and should return a string, something like: 

```
label={node => `${node.id}: ${node.value}`}
```
