### ISSUE TITLE
Map constructor error

### ISSUE THREAD

**Issue by PhysioJay** [plouc/nivo#185]
Actually I ran the command "react-native run-android" in the project path and could execute the build, but error message is appeared with "Map constructor does not accept arguments."

Following the introduction, I installed victory-native, react-native-svg and also linked them but error was occurred.

What is the cause???

![screenshot_2018-05-05-03-53-49](https://user-images.githubusercontent.com/38989940/39647045-3f7f1ab0-4f92-11e8-9671-c2b24069f76e.png)

**Comment by plouc** [comment]
Sorry, but this has nothing to do with nivo apparently.
