### ISSUE TITLE
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null".

### ISSUE THREAD

**Issue by mihaibogdan** [plouc/nivo#1854]
Hi there,

I am trying to create a line chart with both negative and positive values and highlight the chart based on the value (exactly like here: https://nivo.rocks/storybook/?path=/story/line--highlighting-negative-values)
It's all good and it works perfectly fine but there is an annoying case: when i end up having no negative values, I get this error in console: `Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null"`
 

**To Reproduce**
I've created two sandboxes:

- one with the error: https://codesandbox.io/s/nivo-highlight-negative-colors-with-no-negative-values-wypw3?file=/src/index.js
- and one that works when having both negative and positive values: https://codesandbox.io/s/nivo-highlight-negative-values-638nz?file=/src/index.js 

The sandbox uses nivo@0.71.0 but it's also reproducible in v0.74.0. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6225068/145846012-6b0d5d28-9746-468e-b751-3ca9edca5895.png)

As I can see, this doesn't influence the behaviour of the chart, it just throws that annoying error in the console.

Thank you for this awesome library! 🙏🙏

**Comment by gre-dev** [comment]
Same problem !

**Comment by gre-dev** [comment]
Fixed by using this example:

```
const data = [
   {
      id: "hours",
      data: [
         { x: "A", y: "2019-05-29 04:00" },
         { x: "B", y: "2019-05-29 02:00" },
         { x: "C", y: "2019-05-29 07:00" },
         { x: "D", y: "2019-05-30 04:00" }
      ]
   }
];

return (
  <div className="Container" style={{height: 500}}>
     <ResponsiveLine
        data={data}
        margin={{ top: 50, right: 60, bottom: 50, left: 120 }}
        xScale={{ type: "point" }}
        yScale={{
           type: "time",
           format: "%Y-%m-%d %H:%M",
           precision: "hour"
        }}
        yFormat="time:%Hh"
        axisTop={null}
        axisRight={null}
        axisBottom={null}
        axisLeft={{
           orient: "left",
           format: "%Hh%M [%d]",
           legend: "day hour",
           legendOffset: -80,
           legendPosition: "middle"
        }}
        colors={{ scheme: 'yellow_orange_red' }}
        enableGridX={false}
        pointSize={5}
        pointColor="white"
        enableArea={true}
        areaOpacity={0.3}
        enableCrosshair={false}
        pointBorderWidth={2}
        pointBorderColor={{ from: "serieColor" }}
        useMesh={true}
        legends={[]}
        motionConfig="stiff"
     />
  </div>
)
```

I noticed that the `axisLeft` is the reason of this issue.

**Comment by TJHdev** [comment]
I'm getting the same error on using <ResponsiveLine /> on  version 0.78.0.

**Comment by scottsymm** [comment]
we saw this behavior when we passed a data array of *all* null values to one of the lines in a line chart.

note to self: don't do that.

**Comment by oncet** [comment]
Was having the same problem. I'm using Nivo alongside Cube JS, and it turns out that the `isLoading` flag from Cube's query starts as `false`, which caused to pass an empty data set to Nivo.

**Comment by DevGajjar28** [comment]
hey @scottsymm @mihaibogdan can you help me in this i have got same error message as you , it is working only showing lines of x and y but not inside data's.

import { Box, useTheme } from "@mui/material";
import { ResponsiveLine } from "@nivo/line";
import Header from "components/Header";
import { useMemo, useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { useGetSalesQuery } from "state/api";

const Daily = () => {
  const [startDate, setStartDate] = useState(new Date("2024-07-20"));
  const [endDate, setEndDate] = useState(new Date("2024-07-21"));
  const { data } = useGetSalesQuery();
  const theme = useTheme();

  const formattedData = useMemo(() => {
    if (!data) return [];

    const { dailyData } = data;

    const totalSalesLine = {
      id: "totalSales",
      color: theme.palette.secondary.main,
      data: [],
    };
    const totalUnitsLine = {
      id: "totalUnits",
      color: theme.palette.secondary[600],
      data: [],
    };

    Object.values(dailyData).forEach(({ date, totalSales, totalUnits }) => {
      const dateFormatted = new Date(date);
      if (dateFormatted >= startDate && dateFormatted <= endDate) {
        const formattedDate = dateFormatted.toISOString().split("T")[0];

        totalSalesLine.data.push({ x: formattedDate, y: totalSales });
        totalUnitsLine.data.push({ x: formattedDate, y: totalUnits });
      }
    });

    return [totalSalesLine, totalUnitsLine];
  }, [data, startDate, endDate, theme.palette.secondary]);

  return (
    <Box m="1.5rem 2.5rem">
      <Header title="DAILY SALES" subtitle="Chart of daily sales" />
      <Box height="75vh">
        <Box display="flex" justifyContent="flex-end">
          <Box mr={2}>
            <DatePicker
              selected={startDate}
              onChange={(date) => setStartDate(date || new Date())}
              selectsStart
              startDate={startDate}
              endDate={endDate}
            />
          </Box>
          <Box>
            <DatePicker
              selected={endDate}
              onChange={(date) => setEndDate(date || new Date())}
              selectsEnd
              startDate={startDate}
              endDate={endDate}
              minDate={startDate}
            />
          </Box>
        </Box>

        {data ? (
          <ResponsiveLine
            data={formattedData}
            theme={{
              axis: {
                domain: {
                  line: {
                    stroke: theme.palette.secondary[200],
                  },
                },
                legend: {
                  text: {
                    fill: theme.palette.secondary[200],
                  },
                },
                ticks: {
                  line: {
                    stroke: theme.palette.secondary[200],
                    strokeWidth: 1,
                  },
                  text: {
                    fill: theme.palette.secondary[200],
                  },
                },
              },
              legends: {
                text: {
                  fill: theme.palette.secondary[200],
                },
              },
              tooltip: {
                container: {
                  color: theme.palette.primary.main,
                },
              },
            }}
            colors={{ datum: "color" }}
            margin={{ top: 50, right: 50, bottom: 70, left: 60 }}
            xScale={{ type: "point" }}
            yScale={{
              type: "linear",
              min: "auto",
              max: "auto",
              stacked: false,
              reverse: false,
            }}
            yFormat=" >-.2f"
            curve="catmullRom"
            axisTop={null}
            axisRight={null}
            axisBottom={{
              orient: "bottom",
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 90,
              legend: "Date",
              legendOffset: 60,
              legendPosition: "middle",
            }}
            axisLeft={{
              orient: "left",
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "Total",
              legendOffset: -50,
              legendPosition: "middle",
            }}
            enableGridX={false}
            enableGridY={false}
            pointSize={10}
            pointColor={{ theme: "background" }}
            pointBorderWidth={2}
            pointBorderColor={{ from: "serieColor" }}
            pointLabelYOffset={-12}
            useMesh={true}
            legends={[
              {
                anchor: "top-right",
                direction: "column",
                justify: false,
                translateX: 50,
                translateY: 0,
                itemsSpacing: 0,
                itemDirection: "left-to-right",
                itemWidth: 80,
                itemHeight: 20,
                itemOpacity: 0.75,
                symbolSize: 12,
                symbolShape: "circle",
                symbolBorderColor: "rgba(0, 0, 0, .5)",
                effects: [
                  {
                    on: "hover",
                    style: {
                      itemBackground: "rgba(0, 0, 0, .03)",
                      itemOpacity: 1,
                    },
                  },
                ],
              },
            ]}
          />
        ) : (
          <>Loading...</>
        )}
      </Box>
    </Box>
  );
};

export default Daily;
