### ISSUE TITLE
Support Annotations in Line

### ISSUE THREAD

**Issue by Daveiano** [plouc/nivo#1857]
It would be great if the line diagram would also support annotations like for example the bar component. 

Here https://nivo.rocks/bar/ the bar layers property supports the "annotations" layer, whereas the line does not support the layer.

This is a follow up of #125 which was closed due to inactivity, but the request still exists!

**Comment by Daveiano** [comment]
bump

**Comment by KrauseFx** [comment]
Also in-need for this feature

**Comment by mswezey23** [comment]
+1 for annotations support across all/most practical chart implementations.

**Comment by loganfuller** [comment]
I'm also very interested in this feature
