### ISSUE TITLE
Is it possible to customize what data is displayed in the hover label in bubble chart

### ISSUE THREAD

**Issue by rweller59** [plouc/nivo#186]
I am trying to use the bubble chart as a method to make a selection - I'm trying this because I have deeply nested data and thought it might provide a good way to navigate through levels.

It's actually working quite nicely with the exception of the hover label data. Is there any way to modify what data is shown? I can probably work with the id but the value makes no sense in this scenario and it would be great if I could  define my own label info

**Comment by plouc** [comment]
For now, it's not possible, but it should be available soon enough. Also this issue is a duplicate of https://github.com/plouc/nivo/issues/117

**Comment by plouc** [comment]
see https://github.com/plouc/nivo/issues/192 for progress
