### ISSUE TITLE
Problem in tick values. Get error as '<g> attribute transform: Expected number, "translate(NaN,0)"'

### ISSUE THREAD

**Issue by riteshnus** [plouc/nivo#187]
Is anyone got this problem in tick values

> `Error: <g> attribute transform: Expected number, "translate(NaN,0)`".

**Comment by plouc** [comment]
@riteshnus can you provide more context please, used component, packages version, data set… A running example on application like https://codesandbox.io/ would be nice :)

**Comment by mhdhaj** [comment]
<Line
          {...commonProperties}
          enableDots={false}
          enableGridX={false}
          enableGridY={false}
          enableStackTooltip={false}
          curve="monotoneX"
          data={this.state.keys.length > 0 ? this.state.keys :[
            {
              id: 'fake corp. A',
              data: [1, 2, 3, 4, 5, 6, 7, 8, 9].map((y, i) => ({ x: `#${i}`, y })),
            },

          ]}
          axisBottom={{
            "orient": "bottom",
            "tickSize": 0,
            "tickPadding": 100,
            "tickRotation": 0,
            "tickValues": [1, 2, 3, 4, 5, 6, 7, 8, 9],
            "translate":v=> v * 10,
            "format": v =>`${v}`,
          }}
          axisLeft={{
            "orient": "left",
            "tickSize": 0,
            "tickPadding": 5,
            "tickRotation": 0,
            "format": v => {},
          }}
          dotSize={8}
          dotBorderColor="#fff"
          dotBorderWidth={2}
        />

**Comment by mhdhaj** [comment]
same problem here

**Comment by plouc** [comment]
@mhdhaj, thank you for the code snippet, I understand now.
Bottom axis uses a categorical scale, so you cannot use specific tickValues for it (same for topAxis).

**Comment by plouc** [comment]
Meaning you cannot pass arbitrary values, but you can use some which are part of x values, please have a look at [this example](https://codesandbox.io/s/jz3jq2l309)

**Comment by mhdhaj** [comment]
@plouc check this example https://codesandbox.io/s/v380vy9825

**Comment by plouc** [comment]
yes, it's the current behaviour, x scale is a categorical scale, meaning you have to use values from the defined x values, for your example 1.1, 2.1, 3.0 or 3.5.

**Comment by plouc** [comment]
Support for linear/time… based scales will be added, but I don't have much time for now :/
see https://github.com/plouc/nivo/issues/225
