### ISSUE TITLE
Npm Install

### ISSUE THREAD

**Issue by Gyekye** [plouc/nivo#1870]
I cant seem to find how to install nivo with Npm

**Comment by plouc** [comment]
@Gyekye, it depends on the chart you want to use, for example for the bar chart, you should install `@nivo/core` and `@nivo/bar`, you can see the package used for each chart type on the website, in the code tab, for example https://nivo.rocks/bar/, you might have to install some extra peer dependencies for certain charts, you will see them when installing.

**Comment by Gyekye** [comment]
@plouc, Thank You
