### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [plouc/nivo#1891]
Hey there!

I belong to an open source security research community, and a member (@r0hansh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by plouc** [comment]
Hi @JamieSlome,

Thank you for reaching out, I think GitHub issues could be used as for other issues, but I guess this could be specified in such file.

Between issues/PRs/Discord and sometimes people trying to contact me directly on twitter or via email, it's a bit difficult for me to keep track of everything, especially while being the solely maintainer and maintaining the project on my spare time, the more centralized it is, the better.

I'll have a look at the GitHub recommendation/workflow.

**Comment by JamieSlome** [comment]
@plouc - thank you for your response! ⚡ 

If it is easier, you can view the report directly here:
https://huntr.dev/bounties/986fb54a-9353-43c1-9433-9a54b3d31e6e/

It is private and only accessible by you 👍

**Comment by JamieSlome** [comment]
@plouc - any updates here?
