### ISSUE TITLE
Tooltip ^0.79.0 not getting rendered with Heatmap and probably with other charts

### ISSUE THREAD

**Issue by SainsateSonik** [plouc/nivo#1893]
**Steps Taken:**
Upgraded Heatmap from `0.75.0` to `0.79.1`.
Upgraded Tooltip from `0.75.0` to `0.79.0`.

The tooltip isn't visible anymore and the `tooltip` prop isn't rendering the custom tooltip if provided.

**Comment by plouc** [comment]
Closing this as it seems to be a duplicate of https://github.com/plouc/nivo/issues/1823.
