### ISSUE TITLE
Accept multiple data values per Funnel segment

### ISSUE THREAD

**Issue by skulden13** [plouc/nivo#1897]
Hi there,

**Seems, that it's unable to represent multiple data values in a Funnel section.**
I like Nivo lib very much, but it seems that it's not possible to pass an array of values to a Funnel section.
E.g. when data is classified into parts for segments. 
![image](https://user-images.githubusercontent.com/6533742/149914524-335eed19-1d33-458e-b650-ab57073ab546.png)
 
**Possible solution**
It would be nice to be able to pass array or object as data, e.g.:
```
export interface FunnelDatumObject {
    data: FunnelDatum[],
}
```

or smth like that.. And have it as an alternative to [the current FunnelDatum](https://github.com/plouc/nivo/blob/e3a4b7ba547e1fed4639606257a204592e0ef416/packages/funnel/src/types.ts#L8-L12).

[As an example](https://github.com/greghub/funnel-graph-js#two-dimensional-funnel-graph)

What do you think? Does it make sense?

Thanks,
Denis

**Comment by plouc** [comment]
Hi @skulden13, 

The current funnel behaves quite differently as the steps aren't continuous, you could use the stream chart to achieve this though, it's not exactly the same, but close enough, (here is a test I made)[https://codesandbox.io/s/stream-funnel-7sox1?
file=/src/App.js] which looks like this:

<img width="599" alt="Screen Shot 2022-01-28 at 15 35 09" src="https://user-images.githubusercontent.com/501642/151499243-c1b748bd-95b4-4d7c-a5db-f20a8d0a16c8.png">

The tooltips are a bit weird.

If that's not enough I'm afraid I don't have any other solution atm, this would involve re-implementing the current funnel package, which isn't something I'm planning to do in a near future 😅

**Comment by skulden13** [comment]
Hey @plouc , 

Thanks for spending some time on it!..
I see. I'll take a look at your example...

**Comment by skulden13** [comment]
Hey!
I can't use the solution you offered :(
The Funnel seems a bit awkward and not so smooth as a regular funnel.
I'm a fan of Nivo but stick with another lib for now to cover design needs 🤷‍♂️ 

Thanks,
Denis

**Comment by plouc** [comment]
No problem, good luck with your project!

**Comment by prashantkaw** [comment]
@skulden13 What other library did you end up using for comparing funnels? I'm looking for a similar solution (we're also using Nivo). Thanks!

**Comment by prashantkaw** [comment]
Many thanks! Will check it out.

**Comment by ryan-n-may** [comment]
I also had this problem.  After not finding an easy solution I edited the funnel chart source to allow for multiple sources & legends.  

Its a WIP and only exists as (messy) source, but I'll link it here if you want to replicate the results: https://github.com/ryan-n-may/nivo_responsivefunnelplus
