### ISSUE TITLE
Radar Chart Rotation

### ISSUE THREAD

**Issue by paluchs** [plouc/nivo#1898]
I have a Radar chart with 8 axes. I would like to change the orientation (rotation) of the axes such that I don't have one pointing north, but rather one point northnortheast and one northnorthwest. As far as I know, there is no propertiy to change this.

It would be super elegant if there was an axisRotation prop to define a custom angle from where to start drawing the first axis.
E.g.: axisRotation={22.5} to achieve what I am trying to do above.

Alternatively one could also define the angles between all the axis as a list starting from 0°. In the case explained above: [22.5, 45, 45, 45, 45, 45, 45, 22.5]
This:
<img width="168" alt="Bildschirmfoto 2022-01-20 um 10 59 44" src="https://user-images.githubusercontent.com/34346600/150316558-0b65f149-61f4-4f8d-a17a-6fc60308923b.png">

To this:
<img width="157" alt="Bildschirmfoto 2022-01-20 um 11 02 19" src="https://user-images.githubusercontent.com/34346600/150317004-eef0b0bf-0e8f-40e0-a585-dc8603c29f5f.png">

**Comment by plouc** [comment]
This is a good idea, would be nice to have this option! I'm quite busy atm though 😅 But if you want to/can implement this, that would be great!

**Comment by tkonopka** [comment]
I can have a look and submit a PR

**Comment by tkonopka** [comment]
Please see draft PR #1985.

It implements a prop called `angle`. Is that an acceptable name? It's shorter than 'axisRotation'. An alternative might be `startAngle` because that is already implemented in the Pie component.

Also, a similar feature would be relevant to other circle-based components, e.g. Chord. It would be nice to have a unified api. Would you like that in the same PR, or separately?

**Comment by plouc** [comment]
@tkonopka, sorry I reviewed the PR first, `startAngle` for the pie chart is a bit different as you also have an end, maybe simply `rotation`?

I agree this could be interesting for other charts, but I think `start/endAngle` would be good for _non closed_ charts while `rotation` could be used for _closed_ ones, chord could allow to define a start and end angle in fact.
