### ISSUE TITLE
is it possible move around on zoom state in circle packing chart ?

### ISSUE THREAD

**Issue by Yechu0217** [plouc/nivo#1903]
I set it up to zoom when i click the node and i wonder if it's possible to move around other circle with zoom state? 
now only way to see other circle is clicking other node 
Is there any other way around to do this?

**Comment by plouc** [comment]
Yes, it is possible, as long as you pass a zoomId to the chart, it's ok, if you have a look at the [demo](https://nivo.rocks/storybook/?path=/story/circlepacking--zoom-on-click) source, you can see that it's using a state:

```
const [zoomedId, setZoomedId] = useState<string | null>(null)
```

Meaning you can either change this on click or via other means if you want.

**Comment by Yechu0217** [comment]
I am using `setZoomedId ` whenever i click the node so that it zoom every nodes i click.
but how to move on zoom state? what I mean by that, for example when i see this chart (which is on the web) on my phone, i want to move whenever i pinch or touch the screen while zoomed state.
am i still able to do that with `setZoomedId`?

**Comment by plouc** [comment]
Yes, you can set the id depending on the interaction, but you'll have to define it by yourself and capture those interactions, as nivo doesn't support those, I'd say it's not a trivial task, but not impossible.
