### ISSUE TITLE
How do you create a percentage chart?

### ISSUE THREAD

**Issue by ariv797** [plouc/nivo#1909]
**Is your feature request related to a problem? Please describe.**
I am trying to create the following percentage chart:

![7410269_preview](https://user-images.githubusercontent.com/76804697/151317947-9650f685-c7c4-4ee5-b97d-4fa68706d8bc.png)

Normally I would simply use a pie chart with fake data (In the above example it would be 7 and 3) but I want my edges to be rounded. (Also how do you write text inside?) So if I use a normal pie chart I get something like this

![Screenshot (84)](https://user-images.githubusercontent.com/76804697/151318816-758775fe-d478-4483-b7a1-99a500963ef7.png)

There are visible gaps between the sections (understandably). How do you create the first chart without any gaps?

**Describe the solution you'd like**
An option in ResponsivePie to do something similar.

**Describe alternatives you've considered**
Maybe create a full circle and then add the 70% layer on top of it while not rendering the other 30%? But I don't know how to implement this.

**Comment by plouc** [comment]
You can use the [`@nivo/radial-bar`](https://nivo.rocks/radial-bar/) package which has tracks by default, for the percentage in the middle, you can use a layer, please see https://codesandbox.io/s/circular-progress-9gduz?file=/src/App.js.

**Comment by ariv797** [comment]
Thanks a lot!!!
