### ISSUE TITLE
Extra tick sometimes visible off the end of the datetime x-axis

### ISSUE THREAD

**Issue by rit-bit** [plouc/nivo#1910]
Raising in conjunction with my colleague @ewarosset

**Describe/explain the bug**
On the Line chart with a datetime x-axis, when using `tickValues: "every 1 day"`, an extra tick appears off the right end of the x axis some of the time. This bug only happens when using the `every X days` string and does not happen if you use `every X hours` or `every X weeks` etc. 
<img width="486" alt="x-axis tick error sandbox" src="https://user-images.githubusercontent.com/71881973/151345183-31cc6ff8-9758-4d76-bee8-0606513d3dad.png">
<img width="902" alt="x-axis tick error" src="https://user-images.githubusercontent.com/71881973/151345187-5a18f718-6544-4d16-b27f-6449cea37794.png">

**To Reproduce**
This bug is reproduced in [this sandbox](https://codesandbox.io/s/nivo-line-chart-bottom-tick-values-forked-5t6qi?file=/src/index.js). If you use `tickValues: "every 24 hours"` instead of `tickValues: "every 1 day"`, the extra tick disappears.

**Expected behavior**
I expect all the ticks to fall within the bounds of the chart x-axis.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 97.0.4692.99
 - (Also tested on Android and on browsers Edge and DuckDuckGo which all exhibit the bug.)

**Additional context**
After looking into the source code, this bug may be related to [this section of code](https://github.com/plouc/nivo/blob/master/packages/scales/src/ticks.ts#L106-L114).

**Comment by ewarosset** [comment]
Bump

**Comment by robin-leach** [comment]
Bump

**Comment by robin-leach** [comment]
bump
