### ISSUE TITLE
Custom Index Name/Label in Nivo Bar Charts

### ISSUE THREAD

**Issue by BalajiGaneshK** [plouc/nivo#1935]
Lets take the example given in nivo bar documentation

![image](https://user-images.githubusercontent.com/69104773/155398693-e08b8de6-3d92-44c3-a8ff-db533c60d4c4.png)

CodeSandBox link:https://codesandbox.io/s/000mv35lxn?file=/src/index.js

This bar chart is indexed by the "map" property inside each data object, i.e the various countries like RoL, DS,TA,NA,AF etc. So the index name is directly taken from the value of each "map" property and used.

I want to add a custom name to the index. For eg: instead of RoL , i want "Republic of Lemuria", instead of NA I want "North Atlantic" etc. 

Is this currently possible in nivo ? @plouc

**Comment by khen-kovrr** [comment]
bump

**Comment by lenaxus** [comment]
bump
