### ISSUE TITLE
Lines with different style/behaviour in the same plot

### ISSUE THREAD

**Issue by stur86** [plouc/nivo#1940]
I'd like to be able to style different lines within a single `Line` or `ResponsibeLine` plot individually. My use case in particular is I want to plot a signal containing several peaks by combining a whole line (with no markers) as well as markers only at the position of the peaks. Another possible application could be to show the results of a fitting (data = markers, fitting  = line).

**Describe the solution you'd like**
Ideally it should be possible to set values for parameters like `enablePoints` or even the `tooltip` function for each line. It could be done easily by allowing those parameters to be defined in the dataset dictionary, like this:

```
const data = [{
    name: 'myData',
    enablePoints: false,
    data: [...]
}];
```

**Describe alternatives you've considered**
I've considered finding ways to overlap two different `Line` elements, but it seems difficult and hackish to have the positioning be perfect. I think my suggested solution would be a lot cleaner.

**Comment by maxizhukov** [comment]
I have same issue here

**Comment by jackLIT** [comment]
bumo
