### ISSUE TITLE
Change devDependency to dependency

### ISSUE THREAD

**Issue by joshribakoff-sm** [plouc/nivo#1941]
You have `d3-scale` as a `devDependency` for nivo legends https://github.com/plouc/nivo/blob/master/packages/legends/package.json#L27

When we try to run your basic "hello world" examples we got:

```
Cannot find module 'd3-scale' from '../../node_modules/@nivo/legends/dist/nivo-legends.cjs.js'

    Require stack:
      /my-project/node_modules/@nivo/legends/dist/nivo-legends.cjs.js
      /my-project/node_modules/@nivo/line/dist/nivo-line.cjs.js
```

This should be moved to `dependency` or added as a `peerDependency` (preferably the former), otherwise it requires the user of Nivo to debug this. Naively one may try to install `d3-scale` in their `package.json` which will cause even more issues since the latest major version of said package is relying on *experimental* node features which will throw nonsensical errors taking the user further down the rabbit hole.

I believe this one small fix will greatly improve the DX for this library.

The code you publish in your `dist` for `legends` does a `require("d3-scale")` so this is not a `devDependency`.

**Comment by lillijo** [comment]
I guess this issue is related? 
I am getting this error trying to use @nivo/line
( I already have d3-scale installed for something else)

```
Error: require() of ES Module /project/node_modules/d3-scale/src/index.js from /project/node_modules/@nivo/legends/dist/nivo-legends.cjs.js not supported.
Instead change the require of index.js in /project/node_modules/@nivo/legends/dist/nivo-legends.cjs.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by joshribakoff-sm** [comment]
@lillijo Try to downgrade the major version of d3-scale, you're running into the same issue we hit.

**Comment by davidcalhoun** [comment]
I'm not so sure it's related to the major version of `d3-scale`, at least with the issue I'm seeing here.  I added more details to #1951, but in short as of 0.79 `@nivo/legends` is now using `d3-scale` and `@nivo/colors` [in this file](https://github.com/plouc/nivo/blob/v0.79.0/packages/legends/src/compute.ts#L1).  Both dependencies were added to legend's `devDependencies`, but since this code appears to run in prod it should be added to `dependencies` instead.

If using Yarn 2/3 berry you can add this temporary workaround to `.yarnrc.yml` with clears up the error:

```yml
# .yarnrc.yml

...

packageExtensions:
    '@nivo/legends@*':
        dependencies:
            'd3-scale': '*'
            '@nivo/colors': '*'
...

```

**Comment by davidcalhoun** [comment]
I think there's a slightly different issue mentioned by @joshribakoff-sm I'm seeing this issue with `d3-scale` v4 when trying to build the app with Next.js:

```
../../.yarn/__virtual__/@nivo-legends-virtual-c3468b9dca/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist/nivo-legends.cjs.js
Module not found: ESM packages (d3-scale) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```

**Comment by davidcalhoun** [comment]
Bump

**Comment by joshribakoff-sm** [comment]
Not stale.

**Comment by eholt201** [comment]
finding nivo unusable with create-t3-app due to this issue, any suggestions?

**Comment by plouc** [comment]
I'm trying to address this issue in https://github.com/plouc/nivo/pull/2313

**Comment by IshfaqAhmedProg** [comment]
Has this issue been fixed? I'm still getting this error while trying to use @nivo/funnel 

> Error: require() of ES Module node_modules\d3-color\src\index.js from node_modules\@nivo\colors\dist\nivo-colors.cjs.js not supported.Instead change the require of index.js in node_modules\@nivo\colors\dist\nivo-colors.cjs.js to a dynamic import() which is available in all CommonJS modules.

It gets fixed if I change my next js config to 

`const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@nivo"],
  experimental: {
    esmExternals: "loose",
  }
}`

But this hardly seems like a solution, and I'm kind of stuck using nivo, as I found only nivo to provide really good React-friendly docs and good-looking default styling. I've used react-chart-js-2 and material UI, as well on the project could those be causing conflicts?

**Comment by plouc** [comment]
@IshfaqAhmedProg why do you think it's not a solution? This is what [next recommends in such case](https://nextjs.org/docs/messages/import-esm-externals).

> I'm kind of stuck using nivo, as I found only nivo to provide really good React-friendly docs and good-looking default styling.

It seems like you're "stuck" for good reasons at least :)

Also the issue you're reporting is different from this one, it's more about https://github.com/plouc/nivo/issues/2310.

**Comment by plouc** [comment]
The issue has been solved in `0.82.0` via #2313.

**Comment by julienmunar** [comment]
@plouc hello, so what do we have to do to correct the issue ?

**Comment by plouc** [comment]
@julienmunar, to install the latest version, but please note that you might run into import issues depending on your setup due to esm only d3 packages (#2310).

**Comment by mt-hagen** [comment]
Hi @plouc - I am still experiencing this issue in 0.83.0, is this a common issue?

**Comment by Joeghanoe** [comment]
Experiencing this issue in 0.83.0 aswell here, how can we prevent this from happening?

**Comment by KupriyanovNikita** [comment]
Also bumped this issue in 0.83.0

**Comment by lucaslosi** [comment]
i got a similar error building my nextjs project. Heres the trace if it helps:

```
info  - Collecting page data ...Error [ERR_REQUIRE_ESM]: require() of ES Module [***]\node_modules\d3-color\src\index.js from [***]\node_modules\@nivo\colors\dist\nivo-colors.cjs.js not supported.
```

importing these as dependencies:
```
        "@nivo/bar": "^0.83.0",
        "@nivo/core": "^0.83.0",
        "@nivo/line": "^0.83.0",
        "@nivo/pie": "^0.83.0",
```

**Comment by plouc** [comment]
There are 2 different issues, which can be confusing I guess, dependencies weren't properly defined, it's especially an issue when using `pnpm` for example (this issue), this has been fixed, the other issue is: https://github.com/plouc/nivo/issues/2310

**Comment by TejasFresh** [comment]
I still get the same error in 0.83 when I use @nivo/line

**Comment by coderdix24** [comment]
same issue with @nivo/radial-bar

**Comment by coderdix24** [comment]
> @IshfaqAhmedProg why do you think it's not a solution? This is what [next recommends in such case](https://nextjs.org/docs/messages/import-esm-externals).
> 
> > I'm kind of stuck using nivo, as I found only nivo to provide really good React-friendly docs and good-looking default styling.
> 
> It seems like you're "stuck" for good reasons at least :)
> 
> Also the issue you're reporting is different from this one, it's more about #2310.

this didn't work for me, getting error 
/node_modules/@nivo/colors/dist/nivo-colors.cjs.js not supported.

Instead change the require of index.js in /srv/v2/browser/node_modules/@nivo/colors/dist/nivo-colors.cjs.js to a dynamic import() which is available in all CommonJS modules.

**Comment by IshfaqAhmedProg** [comment]
> 

Try updating using `npm i @nivo/core@0.83.0 @nivo/<modname>@0.83.0` replace modname with the module you're using like "funnel", "bar" etc. and then try changing the next js config. Thats what worked for me, you will still get the high risk vulnerabilities found when you run "npm audit". Without this package i get 5 moderate vulnerabilities, with the package i get 21 high risk and 5 moderate!

**Comment by IshfaqAhmedProg** [comment]
> > @IshfaqAhmedProg why do you think it's not a solution? This is what [next recommends in such case](https://nextjs.org/docs/messages/import-esm-externals).
> > > I'm kind of stuck using nivo, as I found only nivo to provide really good React-friendly docs and good-looking default styling.
> > 
> > 
> > It seems like you're "stuck" for good reasons at least :)
> > Also the issue you're reporting is different from this one, it's more about #2310.
> 
> this didn't work for me, getting error /node_modules/@nivo/colors/dist/nivo-colors.cjs.js not supported.
> 
> Instead change the require of index.js in /srv/v2/browser/node_modules/@nivo/colors/dist/nivo-colors.cjs.js to a dynamic import() which is available in all CommonJS modules.

Try updating using npm i @nivo/core@0.83.0 @nivo/<modname>@0.83.0 replace modname with the module you're using like "funnel", "bar" etc. and then try changing the next js config. Thats what worked for me, you will still get the high risk vulnerabilities found when you run "npm audit". Without this package i get 5 moderate vulnerabilities, with the package i get 21 high risk and 5 moderate!

**Comment by coderdix24** [comment]
> > 
> 
> Try updating using `npm i @nivo/core@0.83.0 @nivo/<modname>@0.83.0` replace modname with the module you're using like "funnel", "bar" etc. and then try changing the next js config. Thats what worked for me, you will still get the high risk vulnerabilities found when you run "npm audit". Without this package i get 5 moderate vulnerabilities, with the package i get 21 high risk and 5 moderate!

I appreciate your reply! 
I had it at that version and still getting the same error - I'm not sure what to do, really needed that radial bar chart

**Comment by IshfaqAhmedProg** [comment]
> > > 
> > 
> > Try updating using `npm i @nivo/core@0.83.0 @nivo/<modname>@0.83.0` replace modname with the module you're using like "funnel", "bar" etc. and then try changing the next js config. Thats what worked for me, you will still get the high risk vulnerabilities found when you run "npm audit". Without this package i get 5 moderate vulnerabilities, with the package i get 21 high risk and 5 moderate!
> 
> I appreciate your reply! 
> I had it at that version and still getting the same error - I'm not sure what to do, really needed that radial bar chart 

I forgot to say even i had it at 0.83.0 when i first installed the package, then after encountering the error i ran npm audit fix --force which downgraded the package version to, from what i remember, 0.81.0, then i manually updated it using the command stated above, that let me use it fine without any runtime error! Also if you're using next js in the #2310 issue, some people solved it using dynamic import although that didnt work for me as i needed it to be SSR!

**Comment by bruno-gurgel** [comment]
Still having this problem on 0.83.0. Any solution by now?

**Comment by mmaker** [comment]
same here

**Comment by codesjedi** [comment]
same here

**Comment by willemmulder** [comment]
> > @IshfaqAhmedProg why do you think it's not a solution? This is what [next recommends in such case](https://nextjs.org/docs/messages/import-esm-externals).
> > > I'm kind of stuck using nivo, as I found only nivo to provide really good React-friendly docs and good-looking default styling.
> > 
> > 
> > It seems like you're "stuck" for good reasons at least :)
> > Also the issue you're reporting is different from this one, it's more about #2310.
> 
> this didn't work for me, getting error /node_modules/@nivo/colors/dist/nivo-colors.cjs.js not supported.
> 
> Instead change the require of index.js in /srv/v2/browser/node_modules/@nivo/colors/dist/nivo-colors.cjs.js to a dynamic import() which is available in all CommonJS modules.

@plouc Could you implement this fix? Thanks!

**Comment by willemmulder** [comment]
For an ugly workaround in Next.js you could add the following to your `next.config.js`

    transpilePackages: ["@nivo"], 
    experimental: { esmExternals: "loose" }

**Comment by marekmaurizio** [comment]
So it's unusable in next.js?

**Comment by javierfuentesm** [comment]
im having this issue with remix too any dieas?

**Comment by DaveCole** [comment]
Same issue with @nivo/network - using the loose mode in next.config.js only seems to fix the issue every 2-3 reloads.

**Comment by DaveCole** [comment]
For what it's worth, a workaround is to wrap a container component around the offending Nivo chart (I have trouble with Network and Bullet at the moment, but I suspect it's all the charts), save it as it's own file so that's the file that imports directly from @nivo, and then use Next.js's dynamic import with `ssr: false` to import it during a client-side render:

```
import dynamic from 'next/dynamic';

...

const MyResponsiveNetwork = dynamic(() => import('./MyResponsiveNetwork'), { ssr: false } };
```

**Comment by Jon-Robb** [comment]
> For what it's worth, a workaround is to wrap a container component around the offending Nivo chart (I have trouble with Network and Bullet at the moment, but I suspect it's all the charts), save it as it's own file so that's the file that imports directly from @nivo, and then use Next.js's dynamic import with `ssr: false` to import it during a client-side render:
> 
> ```
> import dynamic from 'next/dynamic';
> 
> ...
> 
> const MyResponsiveNetwork = dynamic(() => import('./MyResponsiveNetwork'), { ssr: false } );
> ```

This fixed the issue for me thanks

**Comment by camiloux** [comment]
**TL;DR: The error occurs on the server side; try client-side loading instead.**

I encountered the same issue when using the Nivo library with Astro and React:

"require() of ES Module .../node_modules/d3-interpolate/src/index.js from .../node_modules/@nivo/core/dist/nivo-core.cjs.js not supported. Instead, change the require of index.js in .../node_modules/@nivo/core/dist/nivo-core.cjs.js to a dynamic import() which is available in all CommonJS modules."

This issue arises when trying to use nivo components on the server side. I resolved it by configuring my component to load client-side only. In Astro, you can do this by setting client:only="react". After making this change, everything worked smoothly, and my chart rendered as expected. For reference, I'm using Nivo version 0.87.0.

For developers facing similar issues with Next.js, you might need to set ssr: false to ensure the components load on the client side only.
