### ISSUE TITLE
Currency in euros

### ISSUE THREAD

**Issue by francescocretti** [plouc/nivo#1946]
**Is your feature request related to a problem? Please describe.**
I can't find a clean way to display currency in euros (€) in my Nivo Charts.

**Describe the solution you'd like**
A way to set the `d3.locale` functin for the chart, maybe through a property.
Something like:
```javascript
<Chart 
  {...props}
  locale={{
    currency: ["", "€"],
    decimal: ".",
    ...
  }}
/>
```

**Describe alternatives you've considered**
Writing a custom function to to that, but I wouldn't know where to put it.

**Additional context**
I'm using the format `valueFormat=">-$.4~s"`, which is fine, I just need the `€` symbol instead of `$`

Thanks a lot

**Comment by francescocretti** [comment]
UPDATE

I solved it using d3 `formatLocale` function.

I created custom hook that handles currency and other formatting options that I needed

`hooks/charts.js`
```javascript
import { useMemo } from "react";

import { format as d3Format, formatLocale } from 'd3-format';

export const useDataFormat = (dataType) => {
  return useMemo(() => {

    if (dataType === 'currency') {

      const euroLocale = formatLocale({
        currency: ["", " €"]
      });

      return euroLocale.format(">-$.5~s");
    }

    if (dataType === 'perc') {

      const percFormat = d3Format(">-.1~f");
      
      return datum => {
        const formattedDatum = percFormat(datum);
        return `${formattedDatum}%`;
      };
    }

    return datum => {
      if (datum <= 5) {
        // three decimals under value of 5
        return d3Format(".3~f")(datum);
      } else if (datum <= 10) {
        // two decimals under value of 10
        return d3Format(".2~f")(datum);
      } else if (datum <= 100) {
        // one decimal under value of 100
        return d3Format(".1~f")(datum);
      } else if (datum <= 10000) {
        // integer (with SI notation) with precision of 3 under value of 10.000
        return d3Format(">-.3~s")(datum);
      } else {
        // integer (with SI notation) with precision of 2 from 10.001 to Infinity (and beyond)
        return d3Format(">-.2~s")(datum);
      }
    }
  }, [dataType]);
};
```

Then in chart component just use it like that:

```javascript
import { ResponsiveBar } from '@nivo/bar';

import { useDataFormat } from '../hooks/charts';

const BarChart = ({ data, options }) => {

  const format = useDataFormat(options.dataType);

  return (
    <ResponsiveBar
      data={data}
      valueFormat={format}
      axisBottom={{
        format: options.layout === 'horizontal' ? format : undefined
      }}
      axisLeft={{
        format: options.layout === 'vertical' ? format : undefined
      }}
      {...otherProps}
    />
  );
};
```

**Comment by V-Mann-Nick** [comment]
I would like to see a feature like this implemented. Actually for me there's no way around having some way to configure the locale for `d3-format`.

## Our use case

We're using nivo on the front-end, but we're generating pdf-documents on the back-end. To render charts I use Nivo charts with server-side rendering. The properties for the nivo charts are passed over the network/JSON. This makes it impossible to use a format function.

For our purpose we need numbers formatted for German speakers. As I haven't found a way to configure the locale for `d3-format` used by `nivo` as it's described in the [docs of d3-format](https://github.com/d3/d3-format#installing) we're currently at an impasse.

## What have I tried

I suspected I should be able to install `d3-format@^1.4.4` and use `d3.formatDefaultLocale`, but for reasons I haven't investigated this doesn't work.

## Implementation

Personally I like the api-proposal of @francescocretti to add a property for localization although I would call it `d3Locale` to be more precise.

**I would offer myself to implement this**

But I would like to first have the way this should be implemented first agreed upon with @plouc.
