### ISSUE TITLE
Other plots like box/violin/pdf/kde plots

### ISSUE THREAD

**Issue by 12sam12** [plouc/nivo#1948]
**Is your feature request related to a problem? Please describe.**
I felt like it would be great if the charting designs like box/violin/PDF(Probability Density Function)/KDE(Kernel Density Estimation) be added to this already awesome library.

**Describe the solution you'd like**
Each of those plots helps in viewing the data in a slightly different manner such that it can highlight different aspects of the dataset.

**Describe alternatives you've considered**
I have seen many alternatives. But I find this library's design to be more appealing and attractive. So I felt that these additions would take this library to a whole new level. These are very common generic designs which are provided by many libraries out there. It would be great to see them here as well.

**Comment by maurochiozzi** [comment]
+1 (supporting #849 too)
