### ISSUE TITLE
Legends Data Override not functional

### ISSUE THREAD

**Issue by sofo1413** [plouc/nivo#1955]
When using Nivo Legends, I am trying to specify which data I want to use in the legend by using the data prop, however it cannot be overridden. I have troubleshooted this issue fairly extensively and am sure that it is an issue with the data override, as the data I am passing is valid. 

const beginningData = scatterPlotData
    .slice(0, Math.floor(scatterPlotData.length / 2));
const endingData = scatterPlotData
    .slice(Math.floor(scatterPlotData.length / 2));

legends={
          scatterPlotData && scatterPlotData.length <= 6
              ? [
                {
                  ...legendProps,
                  translateX: -225,
                  symbolSize: 18,
                  itemsSpacing: 0,
                },
              ]
              : [
                {
                    data: beginningData,
                    ...legendProps,
                  symbolSize: 10,
                  itemsSpacing: 0,
                  translateX: -250,
                },
                {
                    data: endingData[1],
                    ...legendProps,
                  symbolSize: 10,
                  itemsSpacing: 0,
                  translateX: 70,
                },
              ]
        }

**Comment by tkonopka** [comment]
Hi @sofo1413. I don't follow the technical details here, but the keywords (scatterplot, legend, data override) overlap with another issue #1962 and a tentative PR #2016. Does the PR address your question? Thanks
