### ISSUE TITLE
Legend Series Toggle

### ISSUE THREAD

**Issue by westonnh** [plouc/nivo#196]
Can we have the legend series toggle on and off the data in the chart?

**Comment by plouc** [comment]
@westonnh, unfortunately legends aren't interactives for now, but it can be implemented using your own legends, that's what I did on https://stateofjs.com/2017/connections/

**Comment by plouc** [comment]
@westonnh, there's a work in progress on https://github.com/plouc/nivo/pull/224 which will add the ability to implement this feature.

**Comment by serchavalos** [comment]
> [...] but it can be implemented using your own legends, that's what I did on https://stateofjs.com/2017/connections/

@plouc I guess you are referring to this part, right?

**Comment by plouc** [comment]
@serchavalos, yes, that's the approach I've used for state of js

**Comment by aiisahik** [comment]
I just figured out how to do this without having to build my own interactive legend component. The key is hidden inside of this storybook: https://nivo.rocks/storybook/?path=/story/waffle--legend-toggle




```
    <ResponsiveLine
                    data={ data }
                    colors={ this.state.colors || { scheme: 'red_yellow_green' } }
                    legends={[
                        {
                            onClick: (d) => {
                                const colors = data.map(series => (series.id === id ? '#ff3344' : '#DDD'));
                                this.setState({
                                    colors: colors,
                                });
                            },
                        },
                    ]}
    />
```

Once you have this, you can also implement a way for the user to deselect the series highlighting.

**Comment by onionhammer** [comment]
@aiisahik That kinda works as a poor-mans version of this feature, but it doesn't work for stacked `ResponsiveLine`s,

**Comment by fpezzola** [comment]
Is there a way to implements the `hiddenIds` in the ResponsiveLine chart?

**Comment by sattuchin** [comment]
This feature would be very useful. Please prioritize when possible. Thank you!

**Comment by shiftrtech** [comment]
Its this not possible yet? so much need it feature for multiple line charts

**Comment by yuyoux** [comment]
Is it supported now?

**Comment by fpezzola** [comment]
Can you add `hiddenIds` to Responsive Line?

**Comment by peersky** [comment]
Really essential feature. Bump!

**Comment by marcelojrfarias** [comment]
Bump! ;)

**Comment by rafacarrenho** [comment]
Bump!

**Comment by wyze** [comment]
I don't think we should build this in the library itself as most users might want different customizations and will lead to more changes. If we were to build this in, all the charts would need to change to support this. It was pretty straight forward to build this functionality given the current state of the library. You can see my example here: https://codesandbox.io/s/intelligent-neumann-if90n?file=/src/charts/Line.tsx

What is everyones thoughts on this? What more functionality are you looking for?

**Comment by onionhammer** [comment]
I think that this is a common enough feature in most interactive charting libraries that it should probably be built in. That said, your example is probably an effective workaround for most of your users

**Comment by wyze** [comment]
Well I put up a PR to see how it might work and this is a a forked sandbox using it, https://codesandbox.io/s/nivo-forked-e0jbo?file=/src/charts/Line.tsx. API is small, just pass `toggleSerie: true`, to the legends props. I guess it isn't terrible, we would just need to implement it for each chart.

Not sure if `serie` is applicable to all charts so not 100% on the name.

**Comment by Luc9802** [comment]
Great job so far, I'm approaching the library this days and I'm wondering if the same improvement could be done also for pie chart type?

@wyze do you think this is feasible? Do you already know when this improvement would be released? 
Thanks

**Comment by wyze** [comment]
I believe adding this to the Pie chart should be as straight forward as the Line chart. I don't have an ETA on when the next release will be.

**Comment by Luc9802** [comment]
Another functionality related to this could be the customization of the legend when a value is disabled, for example someone could want to mark the text with a line-through

![image](https://user-images.githubusercontent.com/71693205/121316706-e2175280-c909-11eb-9fae-338f7f2f55f5.png)

**Comment by wyze** [comment]
@Luc9802 You can customize the theme for hidden ids present on the legend: https://codesandbox.io/s/nivo-forked-e0jbo?file=/src/charts/Line.tsx

**Comment by mpoteriecy** [comment]
@wyze first of all thank you soooo much for adding this PR and creating this feature. It's working like a charm it's truly great!

What would you recommend me to do if I want so series to be hidden by default ? I am not sure to understand the API enough to find a workaround... I guess there is a way to do it, maybe in the `layers` prop but I am not sure how to achieve this without breaking the toggleSeries logic.

Thank you!

**Comment by wyze** [comment]
We would need to add a prop along the lines of `initialHiddenIds`.

**Comment by mpoteriecy** [comment]
Oh okay that would be truly amazing!  

I am still pretty junior so I am not sure how to proceed. Would be happy to help but I am afraid that it would take more time to review my work rather that doing it haha. What do you think ?

**Comment by wyze** [comment]
Here is how I did it for the Bar chart: [`344b5e1` (#1619)](https://github.com/plouc/nivo/pull/1619/commits/344b5e16e63436f4d643608c1936561a69a8ebc7)

**Comment by murenkot** [comment]
is it possible to implement the `hiddenIds` in the ResponsiveBar chart? In my use case, I need to unselect all IDs except the one that was clocked on.
