### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by benrhere** [plouc/nivo#1964]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use nivo with React 18 which was released on 3/29. Today, the nivo dependencies are such that React 18 causes errors like the following when running "npm update":

```
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16.14.0 < 18.0.0" from @nivo/core@0.79.0
npm ERR! node_modules/@nivo/core
npm ERR!   @nivo/core@"0.79.0" from the root project
npm ERR!   peer @nivo/core@"0.79.0" from @nivo/bar@0.79.1
npm ERR!   node_modules/@nivo/bar
npm ERR!     @nivo/bar@"0.79.1" from the root project
npm ERR!   1 more (@nivo/tooltip)
```

**Describe the solution you'd like**
I think bumping the React dependency should hopefully address this.

**Describe alternatives you've considered**
Running "npm update --force" seems to circumvent this problem for now.

**Additional context**
Thanks for all your work on this terrific library!

**Comment by sshquack** [comment]
Running into this problem too. Current workaround is to use `legacy-peer-deps`

https://github.com/plouc/nivo/blob/f83ad7bd26b0df489486771ac9ee28f99fff449f/package.json#L83-L87

@plouc Thank you for this amazing library 🙏

**Comment by flashdebugger** [comment]
How can I change the crosshair color? I only see it's black. It won't work for the dark mode sites. Thank you

**Comment by cameron-martin** [comment]
Is there anything preventing this over upgrading the dependency versions?

**Comment by singularitypress** [comment]
> Is there anything preventing this over upgrading the dependency versions?

Probably just some testing first to ensure that there aren't any breaking changes with 18.

**Comment by benrhere** [comment]
Appears React 18 support has since been added to react-spring: https://github.com/pmndrs/react-spring/pull/1875

Hopefully that gets us a bit closer

**Comment by benrhere** [comment]
I created https://github.com/plouc/nivo/pull/2008/files to bump peer dependencies, though I'm not sure if more work is needed to achieve React 18 compatibility but hopefully this moves things in the right direction.

**Comment by Gerald12344** [comment]
Has React 18 support arrived?

**Comment by netbizltd** [comment]
I just tried --force installing it but then got "Invalid hook call" errors in the browser :(
Very much looking forward to React 18 support 🙏

**Comment by aitorres** [comment]
I'm also looking forward to React 18 support over here 👍🏻

**Comment by Cpt-Falcon** [comment]
@netbizltd I tried --froce as well and it works fine. i don't see why there would be invalid hook call errors, that sounds like something unrelated to nivo. I mean react 18 only adds concurrent mode, don't see why there would be any breaking changes unless you're using the new react 18 concurrent features with the charts specifically.

**Comment by cameron-martin** [comment]
Upgrading the whole repo to use React 18 isn't trivial, because storybook needs upgrading to a version that supports React 18. However, this requires replacing the deprecated `@storybook/addon-info` and `@storybook/addon-knobs`. Both of these require upgrading to the component story format, which is quite a big change.

However, as a first step, we could upgrade the constraints on the packages, but still use React 17 in the repository for things such as testing.

**Comment by politsin** [comment]
have the same problem
subscribe

**Comment by Cpt-Falcon** [comment]
> Upgrading the whole repo to use React 18 isn't trivial, because storybook needs upgrading to a version that supports React 18. However, this requires replacing the deprecated `@storybook/addon-info` and `@storybook/addon-knobs`. Both of these require upgrading to the component story format, which is quite a big change.
> 
> However, as a first step, we could upgrade the constraints on the packages, but still use React 17 in the repository for things such as testing.

How about just creating a react 18 where you dump the storybooks? Then at a later time when upgrading becomes more manageable, you can bring addon info and knobs back in. Create a package called like nivo-react18-experimental

**Comment by hayyaun** [comment]
Is there any update? 
I have to use `--legacy-peer-deps` option on every npm install in my repo.

**Comment by luke9216** [comment]
@plouc would you be able to create a new release based on the merged changes in https://github.com/plouc/nivo/pull/2056

It is already in the master branch, I cannot see why a new release cannot be created from it.

**Comment by plouc** [comment]
A new release was created with the updated constraints.

**Comment by cameron-martin** [comment]
bump

**Comment by cameron-martin** [comment]
The stale bot is broken?

**Comment by politsin** [comment]
bump again?

**Comment by sethgw** [comment]
bump

**Comment by jedahan** [comment]
Still seeing this issue, please re-open

**Comment by lheinbokel** [comment]
same issue here

**Comment by tappyy** [comment]
Any update here? I'm getting an `Invalid Hook call` error thrown from `@nivo/tooltip/src/Tooltip.tsx:7` when using `ResponsivePie` with `react@18.2.0`.

Package versions are:
`@nivo/core@0.80.0`, 
`@nivo/pie@0.80.0`, 
`@nivo/pie@0.80.0`

**Comment by jwj777** [comment]
bump

**Comment by PerryRylance** [comment]
Same here

**Comment by onionhammer** [comment]
Is this resolved for real now or just marked stale?

**Comment by OsmelSynData** [comment]
any updates, for react18 support?

**Comment by OsmelSynData** [comment]
> any updates, for react18 support?

I managed to find work around the problem by `not upgrading to yarn berry (yarn 2)`. I don't know if you guys also had the same issue with yarn but react 18 was not a problem for me.  

Here are the version Im using if anyone wants to try it out. Also it would be nice to know why yarn seems to be the issue.
"@nivo/core": "0.83.0"
"react": "^18.2.0",
yarn --version => 1.22.19

**Comment by cameron-martin** [comment]
Not stale

**Comment by benrhere** [comment]
I'm now using this library with react 18 with no problems and no need to use "legacy-peer-deps". The original issue seems to be resolved, so I'm closing this.

**Comment by benrhere** [comment]
To add context, I'm using pie and bar charts. If this issue needs to remain open for other chart types, I can reopen.

**Comment by alinealvesvianna** [comment]
I updated my project to:  
``` 
"react": "^18.3.1",
 "react-dom": "^18.3.1",
```
I'm getting the following error when hovering over the ResponsiveLine graph:
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/8ff7f42c-3ba8-45d8-a7f2-b4f1ffdedd92">

When I click on the error in the console to see where it comes from, it points to an error in the tooltip script:
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/2fd1def3-6f4b-415d-923c-710f936dad7b">

Can you help me, please?

**Comment by sam-glass** [comment]
Not working for me either, failing on  @nivo/bar@0.79.1
