### ISSUE TITLE
X-Axis proportionally distributed

### ISSUE THREAD

**Issue by marcospassos** [plouc/nivo#1966]
It's pretty common for time-series data to have partial periods, e.g., selecting a period from June 15 to September 15. Nivo currently distributes the ticks equally, so you have no way to understand whether a period is partial or not visually.

![image](https://user-images.githubusercontent.com/943036/161263133-37e78248-617e-4bde-99b1-2f1ae0ceb44f.png)

**Describe the solution you'd like**

As most viz tools work (Google Analytics, for example), these ticks should be proportionally spread along the x-axis so that the distance from June to July and August to September should be half of the space from July to August.

Is there some way to implement that behavior currently?

**Comment by marcospassos** [comment]
bump

**Comment by marcospassos** [comment]
bump

**Comment by marcospassos** [comment]
bump

**Comment by MoulyT** [comment]
bump

**Comment by marcospassos** [comment]
bump
