### ISSUE TITLE
Can't install @nivo/line or any other components of nivo with REACT 18.0.0

### ISSUE THREAD

**Issue by sarath-gvnd** [plouc/nivo#1967]
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project   
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16.14.0 < 18.0.0" from @nivo/core@0.79.0
npm ERR! node_modules/@nivo/core
npm ERR!   peer @nivo/core@"0.79.0" from @nivo/line@0.79.1
npm ERR!   node_modules/@nivo/line
npm ERR!     @nivo/line@"*" from the root project
npm ERR!   peer @nivo/core@"0.79.0" from @nivo/tooltip@0.79.0
npm ERR!   node_modules/@nivo/tooltip
npm ERR!     @nivo/tooltip@"0.79.0" from @nivo/line@0.79.1
npm ERR!     node_modules/@nivo/line
npm ERR!       @nivo/line@"*" from the root project
npm ERR!     1 more (@nivo/core)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by joshribakoff-sm** [comment]
Try with `--legacy-peer-deps`, it is anecdotally working well in concurrent mode for us, but the author of Nivo has potentially a lot of work to verify things like `react-spring` rigorously before updating their peer deps.

**Comment by ycmjason** [comment]
@plouc any plan on upgrading nivo so it can use react 18?
