### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by plouc** [plouc/nivo#197]
This issue is used to track down the ongoing work on TypeScript definitions for nivo packages.

As nivo isn't built using TypeScript, it does not include definitions, if you're working in a TS environment and already created one for your use case, please do not hesitate to submit a PR!

- [x] `@nivo/bar` *Responsive***Bar** - https://github.com/plouc/nivo/pull/199
- [x] `@nivo/bar` *Responsive***BarCanvas** -  https://github.com/plouc/nivo/pull/199
- [x] `@nivo/calendar` *Responsive***Calendar** - https://github.com/plouc/nivo/pull/223
- [x] `@nivo/calendar` *Responsive***CalendarCanvas**
- [x] `@nivo/chord` *Responsive***Chord**
- [x] `@nivo/chord` *Responsive***ChordCanvas**
- [ ] `@nivo/circle-packing` *Responsive***Bubble**
- [ ] `@nivo/circle-packing` *Responsive***BubbleHtml**
- [ ] `@nivo/circle-packing` *Responsive***BubbleCanvas**
- [x] `@nivo/heatmap` *Responsive***HeatMap** - https://github.com/plouc/nivo/pull/198
- [x] `@nivo/heatmap` *Responsive***HeatMapCanvas** - https://github.com/plouc/nivo/pull/198
- [x] `@nivo/line` *Responsive***Line** - https://github.com/plouc/nivo/pull/316
- [x] `@nivo/line` *Responsive***LineCanvas**
- [x] `@nivo/pie` *Responsive***Pie** - https://github.com/plouc/nivo/pull/207
- [x] `@nivo/radar` *Responsive***Radar**
- [x] `@nivo/sankey` *Responsive***Sankey** - https://github.com/plouc/nivo/pull/211
- [x] `@nivo/scatterplot` *Responsive***ScatterPlot** - https://github.com/plouc/nivo/pull/319
- [x] `@nivo/scatterplot` *Responsive***ScatterPlotCanvas** - https://github.com/plouc/nivo/pull/319
- [x] `@nivo/stream` *Responsive***Stream**
- [x] `@nivo/sunburst` *Responsive***Sunburst**
- [x] `@nivo/treemap` *Responsive***TreeMap**
- [x] `@nivo/treemap` *Responsive***TreeMapHtml**
- [x] `@nivo/treemap` *Responsive***TreeMapCanvas**
- [x] `@nivo/waffle` *Responsive***Waffle** - https://github.com/plouc/nivo/pull/202
- [x] `@nivo/waffle` *Responsive***WaffleHtml** - https://github.com/plouc/nivo/pull/202
- [x] `@nivo/waffle` *Responsive***WaffleCanvas** - https://github.com/plouc/nivo/pull/202

**Comment by plouc** [comment]
@kodedevil, if you're willing to contribute with sankey definition, please link your PR to this issue :)

**Comment by wyze** [comment]
We use TypeScript in our project that contains nivo. A lot of the times we just use an empty `declare module '@nivo/bar` in a global setting and move on. I'll definitely take some of these and contribute them so we can remove those from our project.

**Comment by kallebornemark** [comment]
@plouc Are the definitions you have finished so far available on some dev branch? I'm only using `@nivo/bar` for now, and definitions would be great.

**Comment by plouc** [comment]
@kallebornemark, the doc says they're not required, but in fact they are required but defaultProps are defined, recent TypeScript version supports this, so the definitions should be updated :/

**Comment by kallebornemark** [comment]
@plouc I see. Do you think still will happen anytime soon? We're looking for a sophisticated graph lib for our project, and yours looks really promising. We're very reliant on TS at the moment though.

**Comment by plouc** [comment]
Not soon, I won't have much time to work on nivo in the upcoming weeks, but contributions are welcome :) All components have quite exhaustive prop types, it can help to write TS definitions.

**Comment by plouc** [comment]
Support added for `@nivo/line` package

**Comment by SaphuA** [comment]
As I don't have time right now to submit a pr (I might later) I'll use this place to sum up typescript issues I find as I go:

Bar v0.51
`Axis` is missing `renderTick`
`Axis` `legendPosition` contains `center` but should be `middle`

This one's a little weird and I'm not sure what the cause is, but I've added `colorBy={(datum) => {}}` to my Bar and it somehow thinks `datum.data` is of type `ReactText`.

Pie v0.51

Small issue, but doing something like this `colorBy={(datum) => datum.color}` won't work because `datum` is of a specific type even though it could contain anything.

**Comment by plouc** [comment]
@SaphuA, thank you

**Comment by plouc** [comment]
Definitions added for `@nivo/chord` => https://github.com/plouc/nivo/pull/526

**Comment by plouc** [comment]
`legendPosition` has been fixed

**Comment by plouc** [comment]
`@nivo/stream` & `@nivo/radar` now come with TypeScript definitions.

**Comment by sloanepetit** [comment]
Hi,

I seems that the `cellComponent` & `legends` props declarations are missing in the `Waffle` component.

**Comment by ralmo** [comment]
Great work! I'm starting with typescript and nivo and these definitions are a blessing.

I noticed two missing typings in `LineCustomLayerProps` though when attempting to do dashed lines by copying the `custom line style` example:
- [ ] `lineGenerator`
- [ ] `areaGenerator`

**Comment by latema** [comment]
The `pointSymbol` prop is missing from the LineProps interface in line typings. I created a PR for it: https://github.com/plouc/nivo/pull/681.

**Comment by felipap** [comment]
Hi there, has the Typescript issue with borderColor in @nivo/bar (#344) been fixed?

**Comment by londonbarrett** [comment]
renderTick is still missing ..

**Comment by joseantonomh** [comment]
First of anything, thanks for the awesome work. Keep it up! :)

I just realized, that the Types of the Axis' property `legend` are inconsistent between LineChart and BarChart.

`Axis.legend` is type `string` (Bar)
`AxisProps.legend` is type `React.ReactNode` (Line)

Since both seems to accept strings and components (at least `<tspan>`) I believe that legend should be of type `React.ReactNode` for both.

**Comment by maayanbar13** [comment]
Hi! just wanted to mention that there are some type definitions missing for the @nivo/core package, stumbled upon it while trying to use `linearGradientDef`. should probably add it to the list.

**Comment by seppu** [comment]
Hi, I am trying to add a total to the ResposiveBar stacked bars from @nivo/bars using the Layer option.
I am trying to follow a similar logic  to this codepen [https://codesandbox.io/s/nivo-basic-demo-forked-i1e6k?file=/src/index.js:1806-1863]

I have created my project with typescript so when I am adding the following line 
`layers={["grid", "axes", "bars", TotalLabels, "markers", "legends"]} `
I am getting a type error 

```
No overload matches this call.
  Overload 2 of 2, '(props: BarSvgProps, context?: any): ResponsiveBar', gave the following error.
    Type '"grid"' is not assignable to type 'Layer'.
  Overload 2 of 2, '(props: BarSvgProps, context?: any): ResponsiveBar', gave the following error.
    Type '"axes"' is not assignable to type 'Layer'.
  Overload 2 of 2, '(props: BarSvgProps, context?: any): ResponsiveBar', gave the following error.
    Type '"bars"' is not assignable to type 'Layer'.
  Overload 2 of 2, '(props: BarSvgProps, context?: any): ResponsiveBar', gave the following error.
```

Checking the type definitions for bars [https://codesandbox.io/s/nivo-basic-demo-forked-i1e6k?file=/src/index.js:1806-1863] I can see it has type for Layers. Any idea where I am going wrong
Following is my code 

```

import React from "react";
import { ResponsiveBar } from "@nivo/bar";
const TotalLabels = ({ bars , yScale }: any) => {
    // space between top of stacked bars and total label
    const labelMargin = 20;
  
    return bars.map(({ data: { data, indexValue }, x, width }: any, i: number) => {
      // sum of all the bar values in a stacked bar
      const total = data['Net Spend'];
  
      return (
        <g
          transform={`translate(${x}, ${yScale(total) - labelMargin})`}
          key={`${indexValue}-${i}`}
        >
          <text
            // add any class to the label here
            className="bar-total-label"
            x={width / 2}
            y={labelMargin / 2}
            textAnchor="middle"
            alignmentBaseline="central"
            // add any style to the label here
            style={{
              fill: "rgb(51, 51, 51)"
            }}
          >
            {total}
          </text>
        </g>
      );
    });
  };
const ResponsiveStackedBar: React.FunctionComponent<any> = ({ data, keys }) => { 
    return (
        <ResponsiveBar
            data={data}
            keys={keys}
            indexBy="scenario"
            margin={{ top: 50, right: 130, bottom: 50, left: 60 }}
            padding={0.5}
            // colors={{ scheme: 'nivo' }}
            colors={({ id, data }) => data[`${id}Color`]}
            
            borderColor={{ from: 'color', modifiers: [ [ 'darker', 1.6 ] ] }}
            axisTop={null}
            axisRight={null}
            axisBottom={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legend: 'Scenario',
                legendPosition: 'middle',
                legendOffset: 40
            }}
            axisLeft={{
                tickSize: 5,
                tickPadding: 5,
                tickRotation: 0,
                legend: 'Amount',
                legendPosition: 'middle',
                legendOffset: -55,
                format: '$.2s'
            }}
            labelSkipWidth={12}
            labelSkipHeight={12}
            labelTextColor={{ from: 'color', modifiers: [ [ 'darker', 1.6 ] ] }}
            labelFormat="$.2s"
            legends={[
                {
                    dataFrom: 'keys',
                    anchor: 'top-right',
                    direction: 'column',
                    justify: false,
                    translateX: 120,
                    translateY: 0,
                    itemWidth: 100,
                    itemHeight: 20,
                    itemsSpacing: 0,
                    symbolSize: 20,
                    itemDirection: 'left-to-right'
                }
            ]}
            animate={true}
            motionStiffness={90}
            motionDamping={15}
            layers={["grid", "axes", "bars", TotalLabels, "markers", "legends"]}
        />
    )
};
```

**Comment by wyze** [comment]
It is because the layers you are passing in are coming as `string` instead of `grid` or `axes`, etc. You might be able to do `layers={["grid", "axes", "bars", TotalLabels, "markers", "legends"] as const}`, but if that doesn't work, you will need to import `Layer` from `@nivo/bar` and do `layers={["grid", "axes", "bars", TotalLabels, "markers", "legends"] as Layer[]}`.

**Comment by stephanoshadjipetrou** [comment]
@plouc when trying to install `@nivo/treemap` package seems that the `index.d.ts` file is missing. Based on the initial comment list of yours treemap has ts types defined, isn't that right?

**Comment by wyze** [comment]
@stephanoshadjipetrou It is on master but hasn't been made to a release. It will be in the next release, whenever that might be.

**Comment by stephanoshadjipetrou** [comment]
@wyze thanks for the quick response! just another quick question: is this the same case for sunburst package?

**Comment by wyze** [comment]
Yup!

**Comment by maddy2894** [comment]
Thank you for the awesome effort. Any chance of adding Module `LineComputedSerieData` to `@nivo/line` in types? Because I am getting following error.
```
Module '"@nivo/line"' has no exported member 'LineComputedSerieData'.
```

**Comment by mikejackowski** [comment]
Seems like Treemap is missing tooltip. Any chance of adding it?

**Comment by wyze** [comment]
Hi @maddy2894 and @mikejackowski please open separate issues specific to your requests and we can handle it there. Thanks!

**Comment by lhguerra** [comment]
I see Pie is already checked as done, but I'm unable to import the type for data property (I expeted it to be PieDatum but it is not exported). Should I use some other type or is this a separate issue?
