### ISSUE TITLE
Nivo tooltip hover is broken on line chart

### ISSUE THREAD

**Issue by Cpt-Falcon** [plouc/nivo#1984]
**Describe/explain the bug**
Nivo tooltip hover is broken on line chart

**To Reproduce**
https://codesandbox.io/s/zealous-lamarr-jnzhyp?file=/src/App.js

Try to hover on graph, nothing happens

**Expected behavior**
Tooltip shows up

It doesn't appear tooltip hover has worked in a while, tried versions 0.7.0 to 0.7.9

Edit:

Legend in general doesn't work either. It seems like versions 0.7+, at least for line, are not yet stable. 0.69 seems to work

**Comment by tkonopka** [comment]
Try adding one of these to the `Line` component:

 - `useMesh={true}`
 - `enableSlices='x'`
 - `enableSlices='y'`

**Comment by Cpt-Falcon** [comment]
@plouc I actually forgot to post here that @tkonopka solution worked, adding useMesh enabled it to work, I simply forgot to post here thanks

**Comment by plouc** [comment]
@Cpt-Falcon, no worries, I'm glad it worked!
