### ISSUE TITLE
Render tooltip onClick

### ISSUE THREAD

**Issue by andtankian** [plouc/nivo#1986]
Hello guys,
Is it possible to render tooltip onClick?

Thank you.

**Comment by tkonopka** [comment]
(I'm not an author/maintainer of nivo, but hope this can help)

For a Bar chart, that can be achieved by creating a custom function for displaying the bars and handling their events, based on [BarItem](https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.tsx).

https://codesandbox.io/s/broken-leftpad-p0ji2k?file=/src/App.js

This approach may not apply to other chart types.

**Comment by andtankian** [comment]
Thank you for your time. This will be suitable for my usecase.
