### ISSUE TITLE
Custom color for single bar, but not stored in data

### ISSUE THREAD

**Issue by SteveAtKlover** [plouc/nivo#1989]
I'd like to be able to achieve this look. A color for each bar, but I don't want the color stored in the data object. I'd like to specify the colors in the config for the bar chart itself. It's like doable, but I just can't figure it out.

<img width="874" alt="Screen Shot 2022-05-04 at 12 20 00 PM" src="https://user-images.githubusercontent.com/101133964/166810313-24fa204e-30d6-42b1-afd6-0ff5548a6b52.png">

Right now i'm achieving it with `colors={(d) => d.data.color}`, and here's my data...

```[
  {
    "vendor": "Klover",
    "NPS": 45,
    "color": "red"
  },
  {
    "vendor": "Dave",
    "NPS": 27,
    "color": "pink"
  },
  {
    "vendor": "Varo",
    "NPS": 89,
    "color": "orange"
  },
  {
    "vendor": "Walmart",
    "NPS": 11,
    "color": "skyblue"
  }
]
```

but i wanna get the colors out of the data and into the bar config itself somehow. Thanks.

**Comment by tkonopka** [comment]
If the goal is to remove colors from the data object, perhaps like this:

```
// define custom colors as an object/dictionary
const myColors = {
  Klover: 'red',
  Dave: 'pink',
  Varo: 'orange',
  Walmart: 'skyblue'
}

// then use a function to assign colors to bars 
<Bar
  ...
  colors={(d) => myColors[d.data.vendor] }
  ...
/>
```

Alternatively:

```
<Bar
  ...
  colors={['red', 'pink', 'orange', 'skyblue']}
  colorBy={'indexValue'}    // or 'index' or 'data.vendor'
  ...
/>
```

**Comment by SteveAtKlover** [comment]
@tkonopka thank you!
