### ISSUE TITLE
Customize grid lines and ticks in BarChart

### ISSUE THREAD

**Issue by kaldebert** [plouc/nivo#1990]
Hi everyone!
I would like to render a bar chart with Nivo (see the example) but I can't find a good solution to custom the color of each grid line (Line 1, Line 2, Line 3).
[Theming](https://nivo.rocks/guides/theming/) allow us to change the color of all grid lines but not separately.
Is there a solution?
Otherwise, it would be great to be able to change the properties of each grid line, maybe by using a CSS classname on each grid line or by improving global theming or bar chart's properties.

Thanks!

Example:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/10433270/166888640-7ae82e44-0dd8-4444-b5ba-de3178bc4d6a.png">

**Comment by tkonopka** [comment]
One approach could be to use markers. See example story [here](https://nivo.rocks/storybook/?path=/story/bar--with-marker) and code [here](https://github.com/plouc/nivo/blob/master/packages/bar/stories/bar.stories.tsx#L52).

Another approach might be with layers, for example:

https://codesandbox.io/s/blue-grass-60vv67?file=/src/App.js

<img src="https://user-images.githubusercontent.com/7260190/167091912-7a7ebdc5-40c7-46fd-b593-e3a23c39f029.png" width=300 />

**Comment by plouc** [comment]
@kaldebert as @tkonopka suggested, you could use either markers or layers for this.

**Comment by kaldebert** [comment]
Thank you guys!
I will try that!
