### ISSUE TITLE
Responsive pie alignment/anchor

### ISSUE THREAD

**Issue by orenklein** [plouc/nivo#1996]
**Is your feature request related to a problem? Please describe.**
Responsiveness with Pie chart is frustrating - there is no way to control pie horizontal alignment, and it is always centered. 
When the container is small, the legends overlapping the pie. 

**Describe the solution you'd like**
1. A property to set the position of the pie similar to `legend.anchor` 
2. ability to set percentage margin specifically for pie chart (excluding legends)
3. pie and legends affects each other size - if legends starts overlapping the pie, it will shrink (like flexbox). I think this one can be a matter of another issue 

**Describe alternatives you've considered**
I've tried setting margin with percentages but it only accepts number. Nonetheless, the margin is on the whole chart including legends. If I'd want the chart docked to the left side and the legends docked to the right side, it couldn't be achieved even with percentage margin prop.

**Additional context**

https://user-images.githubusercontent.com/21295634/167816971-97c44da2-b44f-4f97-a2ef-be593567df7c.mov

example of shrinking due to legends overlapping
![image](https://user-images.githubusercontent.com/21295634/167819564-7cc4a9f1-6420-42cc-b037-d2c2dfb64177.png)

example with pie docked to the left, and legends docked to the right:
![Screen Shot 2022-05-11 at 12 26 45](https://user-images.githubusercontent.com/21295634/167818305-9fe6b258-cc02-4e66-9eaf-33a5feeae824.png)

**Comment by orenklein** [comment]
bump

**Comment by Shawry** [comment]
bump

**Comment by grant-davidson** [comment]
Margins work well with legends now. You can move the Pie chart to the left by increasing the right margin
