### ISSUE TITLE
[Feature request] legend itemPadding property

### ISSUE THREAD

**Issue by orenklein** [plouc/nivo#1997]
**Is your feature request related to a problem? Please describe.**
The current `padding` property of legend behaves as padding for the whole legends container.
In some cases, padding for each item is also necessary. for example when there's `itemBackground` set.

**Describe the solution you'd like**
legend's itemPadding property, or even better - item style's property to set whatever style you want
**Describe alternatives you've considered**

**Additional context**
example legends property of pie chart to reproduce
```
legends={[
            {
                anchor: 'right',
                direction: 'column',
                justify: false,
                translateX: 0,
                translateY: 0,
                itemsSpacing: 10,
                itemWidth: 51,
                itemHeight: 27,
                itemTextColor: '#999',
                itemDirection: 'left-to-right',
                itemOpacity: 1,
                symbolSize: 18,
                symbolShape: 'circle',
                effects: [
                    {
                        on: 'hover',
                        style: {
                            itemBackground: 'green'
                        }
                    }
                ]
            }
        ]}
```

![image](https://user-images.githubusercontent.com/21295634/167856180-aac67a34-dca3-49dc-a9cd-ff0ca2e73b47.png)

**Comment by ppfm** [comment]
Bump
