### ISSUE TITLE
Version on github doesn't match npm published versions

### ISSUE THREAD

**Issue by muffinresearch** [plouc/nivo#20]
Hi, I'm trying to debug some issues setting up a v2 Mozaik dashboard. The mozaik demo version I'm running has `^1.0.0-alpha.8` in the package.json as a dep but there's only `1.0.0-alpha.4` on github afaict.

FWIW: The rev of mozaik-demo I'm building from is https://github.com/plouc/mozaik-demo/commit/f29660969991414c7b7892871ee6deabfc72465f

**Comment by plouc** [comment]
Tags corresponding to versions now exist (not for the older one though, sorry).
