### ISSUE TITLE
NPM doesn't have @nivo/core 0.79.1

### ISSUE THREAD

**Issue by elliottpost** [plouc/nivo#2002]
https://www.npmjs.com/package/@nivo/core latest version shows `0.79.0` whereas the other packages are at `0.79.1`. The releases on GitHub show `@nivo/core 0.79.1` [is available as of Jan 12](https://github.com/plouc/nivo/releases/tag/v0.79.1), 2022. Because `0.79.1` [solves a few issues with SSG and SSR usage of Nivo](https://stackoverflow.com/a/71105088/1952517), we're using `0.78.0` still.

I'm not fully sure how NPM <> GitHub sync versions, but is this something that is an easy fix for NPM to recognize the latest version `0.79.1`?

![Screen Shot 2022-05-15 at 12 05 01 PM](https://user-images.githubusercontent.com/3232219/168482388-16821417-d759-4854-ac24-189fc3cbe44a.png)

**Comment by plouc** [comment]
Hi @elliottpost, this is because the `@nivo/core` didn't have any change for that release, so the latest version is `0.79.0` (if considering `0.79.1` for others. I agree it can be confusing, but I'm a bit reluctant about creating similar releases with different version ID.

**Comment by awareness481** [comment]
Would it be possible to cut a new release for the server rendering fix? (doesnt have to be 0.79.1)
