### ISSUE TITLE
How to set different "curves" by series in one ResponsiveLine

### ISSUE THREAD

**Issue by olha-s** [plouc/nivo#2003]
How I can to set different "curves" by series lines in one ResponsiveLine?
It is not possible to pass an array to a curve (eg curve={['natural', 'linear']}).
Are there any solutions for this?

**Comment by tkonopka** [comment]
Hi @olha-s. As far as I can tell this isn't possible by setting props, but it is possible to achieve the effect by drawing custom layers. 

The approach is similar to the example story [here](https://nivo.rocks/storybook/?path=/story/line--custom-layers) and code [here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L950-L985). Another example:

https://codesandbox.io/s/zealous-ride-zo8don?file=/src/App.js

<img src="https://user-images.githubusercontent.com/7260190/169139998-45b2fb7c-0ad8-4ebf-bc8e-fd8361b5df38.png" width=480 />
