### ISSUE TITLE
How to remove scale labels for radial bar

### ISSUE THREAD

**Issue by nappalm** [plouc/nivo#2006]
**Describe/explain the bug**
How to hide scale labels

**To Reproduce**
https://codesandbox.io/s/nivo-radia-bar-custom-color-usrbob

**Screenshots**
![image](https://user-images.githubusercontent.com/35016608/168668474-cc91d339-5fa7-47c5-af6c-6070a40b0ee2.png)

**Comment by sujan-s** [comment]
I have this question, too.

**Comment by sujan-s** [comment]
Ok, @nappalm this combo hides all text and other indicators on the bar—

```
enableLabels={false}
circularAxisOuter={null}
enableCircularGrid={false}
enableRadialGrid={false}
```
