### ISSUE TITLE
Bar char does not render correctly on nextjs

### ISSUE THREAD

**Issue by ari-motors-team** [plouc/nivo#2009]
**Describe/explain the bug**
Bar char does not render correctly before resizing window on nextjs.

First render:
![image](https://user-images.githubusercontent.com/95754840/169093012-9559d563-4437-4537-a9c7-9e2400fe5203.png)

After resizing:
![image](https://user-images.githubusercontent.com/95754840/169093072-37adcad3-83bd-4340-a76c-f9b5bf1022e3.png)

**To Reproduce**
Couldn't find a nextjs example. Hiere is the code:
```js
import dynamic from "next/dynamic";
import data from "./bar-data";

const CustomersDemographicsBar = dynamic(
  () => import("./CustomersDemographicsBar"),
  {
    ssr: false,
  }
);

export default function CustomersDemographics(props) {
  return (
    <div className="grid grid-rows-[min-content_min-content_1fr_min-content] p-4 bg-white shadow-outer">
      <p className="ml-2 text-lg font-bold">Alter</p>
      <div className="h-full">
        <CustomersDemographicsBar data={data} />
      </div>
    </div>
  )
};
```

bar-data.js
```js
export default [
  {
    country: "18 - 24",
    Alter: 34,
    "hot dogColor": "hsl(124, 70%, 50%)",
  },
  {
    country: "25 - 34",
    Alter: 28,
    "hot dogColor": "hsl(130, 70%, 50%)",
  },
  {
    country: "35 - 44",
    Alter: 19,
    "hot dogColor": "hsl(132, 70%, 50%)",
  },
  {
    country: "45 - 54",
    Alter: 11,
    "hot dogColor": "hsl(343, 70%, 50%)",
  },
  {
    country: "55 - 64",
    Alter: 5,
    "hot dogColor": "hsl(35, 70%, 50%)",
  },
  {
    country: "65+",
    Alter: 3,
    "hot dogColor": "hsl(67, 70%, 50%)",
  },
];
```

1. Create default nextjs app
2. Paste code

**Expected behavior**
Should render correctly without resizing window.

**Desktop (please complete the following information):**
 - Fedora 36
 - Chromium 100

**Comment by ari-motors-team** [comment]
The issue was solved after removing nextjs strict mode. However, it's strongly recommended to enable it. Therefor I will leave the ticket open.
https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode

**Comment by tony-cocco** [comment]
I've just been working through this same issue. I got it to work by setting `animate={false}` on the bar chart.

Worth noting, I've also downgraded to @nivo/core@0.78.0 to workaround the `ResizeObserver undefined` error to remove the need for the dynamic import turning off ssr.

**Comment by plouc** [comment]
Animations will cause this issue, also there was a bug with resize observer, which has been fixed.
