### ISSUE TITLE
ResponsiveHeatMap emptyColor Not Working

### ISSUE THREAD

**Issue by shoxter** [plouc/nivo#2013]
**Describe/explain the bug**
`emptyColor` does not work as a property on the `ResponsiveHeatMap` component.

**To Reproduce**
https://codesandbox.io/s/serene-bas-mw3bxp

1. Create a basic `ResponsiveHeatMap` with an empty data cross section.
2. See the cross section not respect the `emptyColor` property (as demonstrated by the white square in the sandbox)

**Expected behavior**
The empty square should be colored to the specified `emptyColor` prop -- the default also doesn't appear to be working either.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Chrome
 - Version 101.0.4951.64

**Comment by tkonopka** [comment]
Hi @shoxter. The example in the sandbox has 'missing data through omission', i.e. the data object does not contain any information about some row-column combinations.

```
[ 
  {
    id: "row label",
    data: [
      ... 
      // { x: "column label", y: 123 }   Commented out, i.e. omitted
      ...
    ]
}
```

To apply `emptyColor`, use 'missing data through nulls' instead:

```
[ 
  {
    id: "row label",
    data: [
      ... 
     { x: "column label", y: null }   // value is set null
      ...
    ]
}

```

The heatmap should then apply the chosen color to the cells with null values.

**Comment by shoxter** [comment]
> Hi @shoxter. The example in the sandbox has 'missing data through omission', i.e. the data object does not contain any information about some row-column combinations.
> 
> ```
> [ 
>   {
>     id: "row label",
>     data: [
>       ... 
>       // { x: "column label", y: 123 }   Commented out, i.e. omitted
>       ...
>     ]
>   }
> ]
> ```
> 
> To apply `emptyColor`, use 'missing data through nulls' instead:
> 
> ```
> [ 
>   {
>     id: "row label",
>     data: [
>       ... 
>      { x: "column label", y: null }   // value is set null
>       ...
>     ]
>   }
> ]
> ```
> 
> The heatmap should then apply the chosen color to the cells with null values.

Thank you for your reply! I also tried a `null` value and still could not get it to work. I've updated the sandbox to demonstrate this as well.

I know this is unsolicited, but to me, from a database query and format perspective, both omission and null should qualiify for `emptyColor` as they both qualify as empty in my mind. Again, I know that wasn't asked, but it seems to make more sense than having to artificially create data that isn't there just to have a `null` y value.

**Comment by shoxter** [comment]
> Hi @shoxter. I see the updated sandbox. It does work - just set `emptyColor` to something that clearly contrasts with the other cells.
> 
> > I know this is unsolicited, but to me, from a database query and format perspective, both omission and null should qualiify for emptyColor as they both are empty. This is how Calendar and TimeRange components both work -- omission qualifies for emptyColor -- you don't need a null value to trigger emptyColor there.
> 
> I agree that the two are often the same (also, I wasn't aware about the behavior in Calendar). This could be an idea for a feature request/suggestion, perhaps enabled by a prop 'missingAreNull' or 'setMissingToNull' or similar. I would give that +1

I see that now! Thanks for pointing out that to me.

I love that idea as it would benefit us greatly. I'm not comfortable enough in Typescript otherwise I'd look to submit the PR myself. I'll likely have to create the non-existent data structures so I can pass in null as a temporary workaround.

Thank you for all your feedback.
