### ISSUE TITLE
Sunburst section disappears on update and only comes back on additional re-render

### ISSUE THREAD

**Issue by mnai01** [plouc/nivo#2015]
CodeSandbox added, Responsive sunburst chart slice disappears when modifying slices value.

Basically when I modify the current state by changing one of the index's name/value the values are correctly calculated but that specific modified index on the slice disappears and is now seen as empty space unless a re-render is triggered after, example Resizing the page will make the newly modified slice appear 

 [See error and steps to reproduce here CodeSandBox](https://codesandbox.io/s/brave-hellman-yuuw82?file=/src/App.js&resolutionWidth=610&resolutionHeight=433)

**Expected behavior**
To update slice with correct values

**Comment by tkonopka** [comment]
Hi @mnai01. This could be related to React 18. The sandbox seems to work as expected if you can start the app with the old react syntax.

```js
// index.js
import App from "./App";
import { render } from 'react-dom';

const container = document.getElementById('root');
render(<App />, container);
```

**Comment by mnai01** [comment]
Hey @tkonopka, Thanks for the help that worked perfectly. I also tested it with 8.1.0 and that worked too. In my case its easier to upgrade the repo then downgrade so I went with that. Thanks again!
