### ISSUE TITLE
Line Layer over Grouped Bar Chart

### ISSUE THREAD

**Issue by sharaku17** [plouc/nivo#2017]
Hi Guys,

I am trying to achieve a Line Chart over a Grouped Bar Chart. I followed the example in an older issue that I found here,
which is shown in this [CodeSandbox](https://codesandbox.io/s/m4ro13jjn8) 
This is also working but I have a Problem when I use Grouped Bars and add a new entry in the "Keys" Array for the Bar. The Line gets manipulated and behaves incorrectly ( The first and last point of the Line get connected) as soon as the Bar chart is using the Grouped mode.

It looks like this:
![Screenshot 2022-05-26 160710](https://user-images.githubusercontent.com/32689131/170504317-7c53c096-9881-42b8-9d96-d648e138f0cd.png)

Any Idea how to solve this?

**Comment by plouc** [comment]
@sharaku17, it's hard to tell without seeing the code, Can you please share the  new sandbox?

**Comment by msolano00** [comment]
@plouc here is an example: https://codesandbox.io/s/nivo-bar-extra-layers-forked-xg3xkf
