### ISSUE TITLE
BarChart: Rendering issues with more than 220 bars in one chart

### ISSUE THREAD

**Issue by joseph-mccombs** [plouc/nivo#2019]
**Describe/explain the bug**
In using barChartResponsive and barChartCanvas, there is inconsistent renders of the actual barChart when the number of bars exceeds certain limits. Once there are roughly > 220 bars in one chart, the chart itself can have excess space in between the y axis on both the left and right side. Once there are roughly > 450 bars in one chart, absolutely nothing will render to the screen except the x-axis labels

**To Reproduce**
To reproduce see the following code sandboxes:

A. Excess padding on both right and left side of the chart (220 bars in one graph)
- Code Sandbox: https://codesandbox.io/s/nivo-bar-chart-220-bars-excess-padding-left-and-right-zjjz4m

To reproduce this in your own code:
1. Create a ResponsiveBar or ResponsiveBarCanvas component and have > 220 unique bars
2. This does not always happen, but more often than not with > 220 bars there will be excess padding in your chart

B. No chart render at all ( >450 bars on one chart)
- Code Sandbox: https://codesandbox.io/s/nivo-bar-chart-450-bars-no-bars-render-fje38j

To reproduce this in your own code:
1. Create a ResponsiveBar or ResponsiveBarCanvas component and have > 450 unique bars
2. This does not always happen, but more often than not with > 450 bars there will be no chart rendered to the screen

**Expected behavior**
In both cases, i would expect a bar chart to render to the screen with no excess padding between the y axis (left and right side) regardless of how small the bars may be.

**Screenshots**
Issue A (from code sandbox > 220 bars && < 450 bars):
<img width="200" alt="Screen Shot 2022-05-26 at 2 36 19 PM" src="https://user-images.githubusercontent.com/44590902/170554284-9c34d836-f434-48de-a33e-a1eb1d160aaf.png">

Issue B (from code sandbox > 450 bars):
<img width="200" alt="Screen Shot 2022-05-26 at 2 36 11 PM" src="https://user-images.githubusercontent.com/44590902/170554488-628825d6-a576-46ea-b325-aee6f7183cf5.png">

Expectected Behavior (in both circumstances):
<img width="200" alt="Screen Shot 2022-05-26 at 2 36 03 PM" src="https://user-images.githubusercontent.com/44590902/170554800-e95b6cdd-f036-47b7-87ad-7ec40df25c85.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome and FireFox (Only ones tested)
 - Version: 0.79.1

**Additional context**
I noticed that in Issue A (> 220 bars && < 450 bars) that the first bar was translated further than in a normal behaving barChart, believe this may have something to do with it. I tried to adjust my margin on the chart, but that did not remedy the situation. 

I believe that these two issues are connected as both have to do with too many bars in a bar chart, I can split them out into separate issues if that is required and desired.

**Comment by joseph-mccombs** [comment]
hi @plouc, thanks for responding. I updated the code sandboxes and both are exhibiting the behavior i mentioned in the issue. Any guidance would be greatly appreciated.

**Comment by cryptoTeq** [comment]
Hi. I'm having the same issue with the bars and columns. I have around 3000 data points and it gets the same result as [joseph-mccombs](https://github.com/joseph-mccombs).

Any help would be GREATLY appreciated.

**Comment by raktim-sg** [comment]
I am also facing the issue B as mentioned by @joseph-mccombs. I have 17000 bars, and as I cross 690 bars, I see that the last bar is simply not drawn at-all, any suggestions to fix this will help. @plouc please have a look as we use this chart a lot in our production code.

**Comment by joseph-mccombs** [comment]
Can we reopen this? It did not get solved and is still an issue. Multiple reports, would be great and seems like a core feature of a bar chart that should be investigated. Tagging @plouc, If you have any advice, I can try to make a pull request to address the issue as well.

**Comment by plouc** [comment]
Regarding the extra padding, as mentioned in https://github.com/plouc/nivo/issues/840#issuecomment-730014643, you can disable rounding, please see https://codesandbox.io/s/nivo-bar-chart-220-bars-excess-padding-left-and-right-forked-kmhe6q?file=/src/index.js.

Regarding the bars not rendering, same fix, please see https://codesandbox.io/s/nivo-bar-chart-450-bars-no-bars-render-forked-8n5xgk?file=/src/index.js.

But at any case, if the resulting bars width < 1px, they won't render.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/1282.

**Comment by plouc** [comment]
Also now bars <1px are also rendered.

**Comment by joseph-mccombs** [comment]
Thanks so much @plouc !
