### ISSUE TITLE
Change font size and style for arc label and arc link label separately

### ISSUE THREAD

**Issue by matt728** [plouc/nivo#2028]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set the font size, in addition to font styling (weight, style, etc.) for arc labels and arc links labels separately. Perhaps this is available through theme, however when I set theme.labels.text.fontSize, it changes for both the arc link label and the arc label.

**Describe the solution you'd like**
It would be nice if this was implemented in either the theme, as theme.arcLabel and theme.arcLinkLabel, or as a new set of props.

**Describe alternatives you've considered**
See above.

Apologies if this is already possible, and thank you for the help!

**Comment by jsonMartin** [comment]
I'm having this issue as well..any way to do this?

**Comment by archisman11** [comment]
is there any way to change the text style though?

**Comment by gramo37** [comment]
I am also facing the same issue. Is there any way to change the font style to "Arial" ?
