### ISSUE TITLE
custom legend text in BarChart

### ISSUE THREAD

**Issue by benzitohhh** [plouc/nivo#204]
Hi there,

Nivo is amazing! Thanks for all the great work.

Is there a way to set custom legend text in BarChart?

In https://github.com/plouc/nivo/blob/master/packages/nivo-bar/src/Bar.js 
it seems like text either comes directly from keys or indexes.

What we really need is a way to pass in some function
i.e.
```js
        legends={
          [
            {
              "dataFrom": () => {
                    // returns array of { label: xxx, fill: yyy } objects
              }
              "anchor": "bottom-right",
              "direction": "column",
            }
          ]
        }
```

Any ideas really appreciated!

**Comment by rascati** [comment]
Is there an example of how to set custom legend text? I can't find anything for it. Thanks!

**Comment by CallumHemsley** [comment]
@plouc is this possible now?

**Comment by oscargws** [comment]
Does this feature not exist? Or is it just not documented.

**Comment by wyze** [comment]
It's likely not documented, but you can manually set the `data` property of the legend item, and it has a `label` property you can use.

**Comment by 4-life** [comment]
@wyze Can you provide an example please?

**Comment by wyze** [comment]
It looks like it requires a custom layer to replicate the legend. Which is apparently what I have been doing in my project. See an example here: https://codesandbox.io/s/nivo-bar-example-nf86t

We could add a check for a label property where it computes the legend data (https://github.com/plouc/nivo/blob/441383999dad1c9697ef6f4bc89b1c19b4505153/packages/bar/src/compute/legends.js) and use that if it is present, that way you don't need a custom layer component.

**Comment by agustingabiola** [comment]
Hi @wyze I was trying to implement your example and found two issues with it (I'm using typescript)
1) `@nivo/legends` module definition is not complete you can bypass the compile error by adding something like:
```declare module '@nivo/legends' {
  import * as NivoLegends from '@nivo/legends';

  export class BoxLegendSvg extends React.Component<LegendProps> {}
}```
2) https://github.com/plouc/nivo/blob/master/packages/legends/src/svg/LegendSvgItem.js#L141 at that line it is trying to use what it retrieves from `@nivo/core` and in my case it is always undefined, like it cannot get it from anywhere and cannot find a solution.

**Comment by wyze** [comment]
1. I have a fix for that in #802.
2. Can you share an example on CodeSandbox of how it isn't working?

**Comment by agustingabiola** [comment]
@wyze Many thanks for the prompt reply. Unfortunately when I try to reproduce on sandbox it doesn't fail (https://codesandbox.io/embed/nivo-bar-example-jquhc?theme=dark). All I can track is that when it tries to get the theme from the `LegendSvgItem` it is always undefined.

**Comment by wyze** [comment]
I was going to suggest making sure you were on the latest versions of all the packages.

**Comment by agustingabiola** [comment]
I downgraded and worked but looking more closely I had some old dependencies for `@nivo/line` upgrading all the packages dependencies worked. Thanks a lot for your insight and help.

**Comment by HugoLiconV** [comment]
> It looks like it requires a custom layer to replicate the legend. Which is apparently what I have been doing in my project. See an example here: https://codesandbox.io/s/nivo-bar-example-nf86t
> 
> We could add a check for a label property where it computes the legend data (https://github.com/plouc/nivo/blob/441383999dad1c9697ef6f4bc89b1c19b4505153/packages/bar/src/compute/legends.js) and use that if it is present, that way you don't need a custom layer component.

this worked for me! I just have a question, in your example, you're setting the color to black, is there a way to use the default colors for the legends?

**Comment by RanjithNair** [comment]
Is there any way to do this yet?

**Comment by wyze** [comment]
@HugoLiconV It should use `legends.text.fill` from the theme prop.

**Comment by ariel-upstream** [comment]
Is that solution should work at v0.63? I'm doing as described in the example but the labels don't change

**Comment by wyze** [comment]
The types are not 100%. Depending on your TS version, you could try `layers={["grid", "axes", "bars", "markers", BarLegend] as const}`.

**Comment by vikrant-gembrill** [comment]
@wyze is it possible to use custom html to render legend

**Comment by wyze** [comment]
Yes, but it has to be outside of the chart.

**Comment by vikrant-gembrill** [comment]
@wyze @plouc  i have an issue where i am using the BarLegend in layers to render the legends but if the total no of legends are more, they are going out of the container:
![image](https://user-images.githubusercontent.com/75779649/116434075-b6637000-a867-11eb-871a-195f271dd5c4.png)
is there any way to wrap the legends to next line? or maybe add a scrollbar just for the legends?

**Comment by wyze** [comment]
You will have to manually wrap them by figuring out the limit and split into several legends. As far as I know, there is no way to add scrolling to an SVG.

**Comment by vikrant-gembrill** [comment]
I am usign this BarLegend component to render the legends:
```
const BarLegend = ({ height, legends, width }) =>
  legends.map((legend) => (
    <BoxLegendSvg
      key={JSON.stringify(
        legend.data.map(({ id }) => {
          return id;
        })
      )}
      {...legend}
      containerHeight={height}
      containerWidth={width}
    />
  ));
```
can you give an example of how to split in to multiple legends ,should i add multiple "BoxLengendSvg" components?

**Comment by wyze** [comment]
Yes, multiple BoxLegendSvgs like so:

```js
const BarLegend = ({ height, legends, width }) => (
  <>
    {legends.slice(0, 8).map((legend) => (
      <BoxLegendSvg
        key={JSON.stringify(
          legend.data.map(({ id }) => {
            return id;
          })
        )}
        {...legend}
        containerHeight={height}
        containerWidth={width}
      />
    ))}
    {legends.slice(8).map((legend) => (
      <BoxLegendSvg
        key={JSON.stringify(
          legend.data.map(({ id }) => {
            return id;
          })
        )}
        {...legend}
        containerHeight={height}
        containerWidth={width}
      />
    ))}
  <>
);
```

**Comment by vikrant-gembrill** [comment]
@wyze i tried doing this but the legends are still coming in a single line and going out of page:
do you have any idea how to resolve this?
```
const BarLegend = ({ height, legends, width }) => (
  <>
    {legends.slice(0, 7).map((legend) => (
      <BoxLegendSvg
        key={JSON.stringify(
          legend.data.map(({ id }) => {
            return id;
          })
        )}
        {...legend}
        containerHeight={height}
        containerWidth={width}
      />
    ))}
    {legends.slice(7).map((legend) => (
      <BoxLegendSvg
        key={JSON.stringify(
          legend.data.map(({ id }) => {
            return id;
          })
        )}
        {...legend}
        containerHeight={height}
        containerWidth={width}
      />
    ))}
  </>
);
```

**Comment by vikrant-gembrill** [comment]
@wyze even when i slice the first 7 items, it is still showing all the legends:
const BarLegend = ({ height, legends, width }) =>
  legends.slice(0, 7).map((legend) => (
    <BoxLegendSvg
      key={JSON.stringify(
        legend.data.map(({ id }) => {
          return id;
        })
      )}
      {...legend}
      containerHeight={height}
      containerWidth={width}
    />
  ));

**Comment by wyze** [comment]
It would be easier if you could put together a Codesandbox with your code, otherwise it is just me guessing. For the 2nd row of legends you will need to adjust the `translateY` prop passed into the BoxLegendSvg component.

**Comment by vikrant-gembrill** [comment]
@wyze i have created the sandbox, there are only 3 legends, but i am trying to split them, but still they are coming in a single line:
https://codesandbox.io/s/react-nivo-example-xqg2g?file=/src/App.js

**Comment by wyze** [comment]
@vikrant-gembrill Here you go: https://codesandbox.io/s/react-nivo-example-forked-hidxj

**Comment by vikrant-gembrill** [comment]
@wyze i have updated @nivo/bar and @nivo/legends to latest version, but now i am getting an error saying "TypeError: legends is not iterable"
after some debugging i found tha the 'legends' is undefined in the BarLegend function above, which means that 'legends' is not being passed to the function. Can you please help with this, what could be the cause of this. 
fyi, i have also updated react to v 18

**Comment by rodrix** [comment]
Hello, can you try this:

...
legendLabel={(e) => e.id === 'xpto' ? 'Crazy XPTO' : 'Madness Another One'}
legends={[...]}
...

Hope this help
