### ISSUE TITLE
Disabling tooltip without disabling interactivity

### ISSUE THREAD

**Issue by ilyabo** [plouc/nivo#2040]
**Is your feature request related to a problem? Please describe.**
I would like to have more control over how exactly the tooltips are rendered. For instance, I would like to render them in a portal so that they are not cut by the container or use custom positioning logic. Right now it doesn't seem to be possible without redefining item components e.g. `barItemComponent` which is quite a limitation. It is possible to disable interactivity but that also disables other interactive features e.g. the crosshair and the `onMouse…` event handlers are not called at all.

**Describe the solution you'd like**
There should be a property `isTooltipEnabled` which would disable the tooltip when passed `false` without disabling the `onMouse…` event handlers. Alternatively, passing `null` to the `tooltip` prop could also disable tooltip.

**Additional context**
Large tooltip in a small chart is cut because it's not rendered in a portal in a container which needs to use `overflow: hidden` or `overflow: scroll`

<img width=400 src=https://user-images.githubusercontent.com/351828/173221237-c6fecf94-189e-4977-8d77-db17465770b8.png>

**Comment by tkonopka** [comment]
Hi @ilyabo. You mentioned passing null to the tooltip to disable it. A similar approach could be to render an empty tooltip with `tooltip={() => (<></>)}`

**Comment by ilyabo** [comment]
Yes, thanks! I've actually discovered this approach too now and it works for me at least as a workaround. Does it still mean though that some resources are spent on rendering/positioning or can this be neglected? In any case, I think accepting `null` and documenting it would be more straightforward and helpful for the users of the API.

**Comment by ilyabo** [comment]
Also, offering an option to render the tooltip in a portal would be very helpful I think. Something like `tooltipUsePortal` which could take a DOM node to render to and default to `document.body` if just `true` is passed

**Comment by ilyabo** [comment]
Noticed that `onMouse…` events in the `Line` chart [only work when enableSlices is false](https://github.com/plouc/nivo/blob/ce7c755b23cfc55ead9bac9920a55ef6e764bd99/packages/line/src/Line.js#L272). That's unfortunate, because we need to use the slices mode and customize the tooltip. Is there a way to circumvent this limitation?

**Comment by tkonopka** [comment]
The line chart is due an update in #1932. This could be a topic to keep an eye on.

**Comment by ilyabo** [comment]
I started a related discussion here: https://github.com/plouc/nivo/discussions/2044

**Comment by vikrantsingh47** [comment]
@tkonopka not related to this topic, but there are no responses to opened issues recently, is this project actively maintained.

**Comment by plouc** [comment]
@vikrantsingh47, actively, not really lately, it depends on my other constraints (job, family, ...)

**Comment by criveratro** [comment]
Another way you could disable tooltips without disabling interactivity is by passing a custom bar to the `barComponent` prop.
