### ISSUE TITLE
Customize the Tick length on bar / line chart

### ISSUE THREAD

**Issue by chrisyeung1121** [plouc/nivo#2043]
**Is your feature request related to a problem? Please describe.**
Sometimes when the chart is small, I would like to customize the tick length. Currently the tick length is `x1=-10 x2=0`. and it cannot be customized

**Describe the solution you'd like**
A quick solution I can think of is to allow `stroke-dasharray` CSS property in `theme.axis.line.tick` object. It currently already supports stroke and strokeWidth. 

I can then quickly add `strokeDashArray: '7 3'` to hack a shorter tick length.

**Comment by tkonopka** [comment]
Hi @chrisyeung1121. Not sure what you mean by x1 and x2. If you are looking to make the tick lines shorter, there is `tickSize`. You can use that to configure any of the axes (axisTop, axisBottom, axisLeft, axisRight).

**Comment by chrisyeung1121** [comment]
![image](https://user-images.githubusercontent.com/3488583/174054135-555fd169-849c-45b5-b160-f69f3e81b795.png)

You can find the above, it is the length of the tick, from what I understand, it seems `tickSize` is more of the number of ticks?

**Comment by tkonopka** [comment]
Hi @chrisyeung1121. Please see the website [nivo.rocks](https://nivo.rocks/) - you can try out tweaking most chart features there, interactively, including the tick marks. The screenshots below are fragments from a bar chart, top with `tickSize: 5` (regular tick length) and bottom with `tickSize: 15` (longer tick length). The same technique works to increase/decrease length, and also works for other charts types.

<img src="https://user-images.githubusercontent.com/7260190/174148277-db8e5f7b-86c5-4d43-96b3-5acbcff50b4d.png" width="250" />

```
// pseudocode
<Chart
  ...
  axisBottom: {{
    tickSize: 5,
  }}
/>
```

**Comment by chrisyeung1121** [comment]
Oversight from my side! Thank you and closing
