### ISSUE TITLE
Sankey diagram - node position

### ISSUE THREAD

**Issue by ioanachi** [plouc/nivo#2047]
Hello, 
I am using sankey diagram and I was wondering if there is any possibility to control the position of a node in the diagram. So I want to put a node on the second level even if if doesn't have a link with the node from the first position or just skip a level - one node on the first position and the second one on the third level. 
In the documentation I saw nothing related to this.

Thank you!

**Comment by plouc** [comment]
Hello @ioanachi,

It is not possible, nivo uses `d3-sankey` which has an open issue about this feature: https://github.com/d3/d3-sankey/issues/3.
