### ISSUE TITLE
@nivo/treemap </code> </data> example not working

### ISSUE THREAD

**Issue by hjfarah** [plouc/nivo#205]
I just found nivo. It's just awesome!

I copied and paste the examples from nivo web site and all of them but treemap worked.

Tried to figure out what's was going wrong but I'm kind of new in react.

Congratulations for nivo!

I'm looking forward to learn more and see if I can help on something!

**Comment by tmewes** [comment]
@hjfarah Try to use the property "root" instead of "data" for treemap and bubble charts. It's just a small mistake on the website. :)

**Comment by hjfarah** [comment]
Worked!!
Thanks!!!

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/commit/b97c07b8c53e66f64265662e832dedc4446df067, thank you for reporting the problem.
