### ISSUE TITLE
Allow calandar heatmap to start on monday instead of sunday

### ISSUE THREAD

**Issue by alexus37** [plouc/nivo#2053]
**Is your feature request related to a problem? Please describe.**
A lot people are starting their week on Monday however, in the calendar heatmap the first column/row is Sunday.

**Describe the solution you'd like**
Add an option to start the calendar on Monday or any day of the week?

**Describe alternatives you've considered**
Could not find any

**Additional context**
![165492192-9f43e7da-a3c2-450a-be50-04c631379267](https://user-images.githubusercontent.com/7422767/175136356-766f0ed8-1ec0-4710-aa3e-c1a7c2b170df.png)

**Comment by tkonopka** [comment]
related to #1832

**Comment by MarcoMorik** [comment]
I think this requires a modification in compute/calender.ts where for both functions `cellPositionVertical`  and  `cellPositionHorizontal`   `d.getDay()`  should be replaced with ` (d.getDay() -StartDayIndex)%7 ` 

with `StartDayIndex = 1` for Mondays. 

However, I am not sure how to best pass this argument down.

**Comment by DobroslavR** [comment]
bump

**Comment by thomasbaronnet** [comment]
bump
