### ISSUE TITLE
Incorrect x tick value with month interval

### ISSUE THREAD

**Issue by hanbyul-here** [plouc/nivo#2054]
Hi, thanks for the great library.

**Describe/explain the bug**
The data gets shifted by one month when month interval is set for tick value. 

**To Reproduce**
This is Code Sandbox that you can see the problem https://codesandbox.io/s/tw6s8q?file=/src/chart/index.js
When you check `data.js`, you can see that the data starts from 09/2021, but the tooltip shows that the data for 09/2021 is for 08/2021, and this (incorrect) doesn't even match to the tick value. 

**Expected behavior**
The chart shows the right time. 

**Screenshots**

![Screen Shot 2022-06-22 at 5 25 56 PM](https://user-images.githubusercontent.com/4583806/175141662-551b3f06-2a1f-455b-8c07-b2fc6fb89fe6.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: both chrome and Firefox
 - Version: v102.0 (Chrome) , v101.0 (Firefox)

**Additional context**
in case this helps: I tested with several versions, this error doesn't happen v0.56.x.

**Comment by tkonopka** [comment]
Hi @hanbyul-here. I see the mismatch in the screenshot, but for me the sandbox is showing the correct result, i.e. the lines, labels, and tooltip start from 09/2021 and match the content in data.js. Have you by any chance resolved this already, or is this a strange OS/browser-dependent effect?

**Comment by tkonopka** [comment]
Thanks @danielfdsilva, learned something new here!
