### ISSUE TITLE
Ability to add tooltip to legend in pie chart.

### ISSUE THREAD

**Issue by willnolin** [plouc/nivo#2055]
**Is your feature request related to a problem? Please describe.**
We are using the pie chart with legend.  Sometimes customers use really long field option names and they get cut off.  I was wondering if you know of any easy way to add a tooltip to each option in the legend?  I can't seem to find a way to do this.  Thanks!

**Describe the solution you'd like**
When You hover over a legend item, the tooltip appears. (see amazing mockup below)
<img width="616" alt="Screen Shot 2022-06-23 at 11 35 06 AM" src="https://user-images.githubusercontent.com/49623535/175338556-fd39ae6f-61b4-441d-894b-f08305d9eb17.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by willnolin** [comment]
@plouc any idea if this is possible?

**Comment by plouc** [comment]
@willnolin, it is not currently supported
