### ISSUE TITLE
Ref is undefined in Pie/ResponsivePieCanvas charts

### ISSUE THREAD

**Issue by cryptoTeq** [plouc/nivo#2058]
**Describe/explain the bug**
`ref` to Canvas element is `undefined` in `Pie`/`ResponsivePieCanvas` charts.
But it works perfectly fine in the `ResponsiveBarCanvas` and returns a reference to the Canvas.

**To Reproduce**
Please check the CodeSandBox. [CodeSandBox](https://codesandbox.io/s/nivo-pie-typescript-forked-f48p40?file=/src/index.tsx)
1) Click on the button on the top
2) Check the value in the console

**Expected behavior**
`ref` contains a reference to the html canvas.

**Screenshots**
![image](https://user-images.githubusercontent.com/74078094/175989690-af985a80-84a5-4565-af2f-531450a27d74.png)

**Comment by Dlina1502** [comment]
I have the same problem, still not solved.

**Comment by YMMTech** [comment]
still not solved

**Comment by plouc** [comment]
There's no solution atm, it needs to be implemented, but you could use the workaround suggested by @YMMTech in the meantime.

**Comment by UdayKumar-Heeddata** [comment]
ok @plouc Thank you
