### ISSUE TITLE
`defaultActiveArcIndex` or `activeIndex`  and/or ref.selectArc for piechart/doughnut chart

### ISSUE THREAD

**Issue by ortonomy** [plouc/nivo#2059]
**Is your feature request related to a problem? Please describe.**
the piechart API has everything except selecting arc slices. They can be animated on hover, but not as a permanent state/prop

**Describe the solution you'd like**
I'd like to be able to provide a `defaultActiveArcIndex` or `activeIndex` which will force a segement/arc to be active, and then be able to change that, either by forwardRef to some kind of api interface or a a event callback with an API object so that I can `onClick` make it selected. 

**Describe alternatives you've considered**
I don't have any alternatives

**Additional context**

**Comment by ortonomy** [comment]
https://github.com/plouc/nivo/issues/1781 - this is basically a duplicate, but it was marked stale and closed :(

**Comment by ortonomy** [comment]
and was requested here, but also closed: https://github.com/plouc/nivo/issues/1820

**Comment by ortonomy** [comment]
It's not stale :(

**Comment by theomessin** [comment]
+1

**Comment by theomessin** [comment]
bump

**Comment by theomessin** [comment]
bump again

**Comment by gornyyvladimir** [comment]
+

**Comment by anoukinsyde** [comment]
+1

**Comment by YMMTech** [comment]
+1
