### ISSUE TITLE
`defs` and `fill` not working in Choropleth Map

### ISSUE THREAD

**Issue by francescocretti** [plouc/nivo#2068]
Thanks for creating and maintaining Nivo.

**Describe/explain the bug**
I can't use `defs` and `fill` properties on Choropleth map

**To Reproduce**
Such as described in #864, I followed the [guide](https://nivo.rocks/guides/patterns/) to add a `pattern` definition to my Map component, but when I define the `match` rule in the `fill`prop, this is never applied.

```javascript
<ResponsiveChoropleth
  data={data}
  features={features}
  margin={{ top: 0, right: 0, bottom: 0, left: 0 }}
  colors={chromaScale}
  domain={domain}
  unknownColor="#fff"
  label="id"
  projectionScale={scale}
  projectionTranslation={translate}
  borderWidth={1}
  borderColor="#152538"
  onClick={onFeatureClick}
  tooltip={({ feature }) => (
      <MapTooltip
        color={feature.color}
        label={feature.id}
        value={feature.formattedValue}
        aggregationType={aggregationType}
      /> 
  )}
  defs={[
    {
      id: "diagonal-stripes",
      background: "inherit",
      color: "#fecd64",
      lineWidth: 3,
      rotation: -45,
      spacing: 7,
      type: "patternLines"
    }
  ]}
  fill={[
    { match: { id: 'Lombardia' }, id: 'diagonal-stripes' }
  ]}
/>
)}
```

This is an example I tried. I'm sure the `feature` with `id = 'Lombardia` is present in my map.

I really don' know what I'm doing wrong.

Any thoughts? Thank you so much.

**Additional context**
```
"@nivo/core": "^0.79.0"
"@nivo/geo": "^0.79.1"
    ```

**Comment by plouc** [comment]
Implemented in https://github.com/plouc/nivo/pull/2072, and available in the latest release.
