### ISSUE TITLE
Graph overflow when min Value is anything above 0. 

### ISSUE THREAD

**Issue by MinBaeBae** [plouc/nivo#2073]
**Describe/explain the bug**
Hi!  My Bar Chart is overflowing and covering content when minValue is anything above 0. 
Shouldn't the graph start at the set min Value??

Additionally, I know you said not to ask questions here and ask on discord instead. But I got no response on discord so I thought I might as well ask you a question here as well.

I want to be able to bring the y value (inside the graph at the moment) and bring it on top of the bars within a circle. (please refer to 3rd screenshot)
Let me know if this is something that is possible using Nivo. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93083003/178409187-5d5efe85-2ace-447a-bf69-a51d006b81cb.png)
![image](https://user-images.githubusercontent.com/93083003/178409214-7558c609-d292-4572-a1a5-03d772f9dd9e.png)
![image](https://user-images.githubusercontent.com/93083003/178409443-d8aeca71-e703-4286-8dcb-936be32a4694.png)

` 
import React from "react";
import { ResponsiveLine } from "@nivo/line";
import { ResponsiveBar } from "@nivo/bar";

const InBodyGraphTest = ({ data, range }) => {
  if (data.length === 0) return;
  const styles = {
    fontFamily: "sans-serif",
    textAlign: "center"
  };

  const setColors = data.map((data, i) => {
    if (data.y > range.upper) {
      return "#a160fb";
    } else if (data.y < range.lower) {
      return "#363636";
    } else {
      return "#0e0aff";
    }
  });

  const refsLayer = props => {
    return (
      <g>
        <rect
          y={props.yScale(range.max)}
          width="100%"
          height={props.yScale(range.upper) - props.yScale(range.max)}
          fill="#FAEBFF"
        />
        <rect
          y={props.yScale(range.upper)}
          width="100%"
          height={props.yScale(range.lower) - props.yScale(range.upper)}
          fill="#EEF7FE"
        />
        <rect
          y={props.yScale(range.lower)}
          width="100%"
          height={props.yScale(0) - props.yScale(range.lower)}
          fill="#F7F7F8"
        />
      </g>
    );
  };

  return (
    <div
      style={{
        ...styles,
        height: 400, // this.getChartHeight(),
        width: "90%" // this.getChartWidth()
      }}
    >
      <ResponsiveBar
        margin={{
          top: 20,
          right: 20,
          bottom: 60,
          left: 80
        }}
        data={data}
        maxValue={range.max}
        minValue={range.min}
        keys={["y"]}
        indexBy="x"
        colorBy="indexValue"
        colors={setColors}
        padding={0.6}
        axisBottom={{
          tickSize: 0
        }}
        gridYValues={["20"]}
        layers={[
          "grid",
          refsLayer,
          "markers",
          "axes",
          "areas",
          "bars",
          "slices",
          "dots",
          "legends"
        ]}
      />
    </div>
  );
};
export default InBodyGraphTest;
`

**Comment by smurphy1111** [comment]
You have to set the clamp value to true in your valueScale property, ie:
```
<ResponsiveBar
  ...
  valueScale={{ 
    type: 'linear',
    min: minVal * 0.8,
    max: maxVal * 1.2,
    clamp: true
  }}
  ...
/>
```
