### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function     at e (nivo-bar.es.js:477:1)

### ISSUE THREAD

**Issue by basavarajum018** [plouc/nivo#2083]
nivo-bar.es.js:477 Uncaught TypeError: Object(...) is not a function
    at e (nivo-bar.es.js:477:1)
    at pe (nivo-bar.es.js:615:1)

**Comment by dev-jesser** [comment]
I'm running into this also after copying and pasting the `<MyResponsiveBar>` example from the home page, on React 16.4.0

**Comment by lylest** [comment]
Bump still facing this issue don't even know where to start fixing it
