### ISSUE TITLE
Axis custom tick values order

### ISSUE THREAD

**Issue by matteo1222** [plouc/nivo#2084]
Thank you for creating this amazing library.

I am passing a custom tickValues to a bar chart. The custom tickValues is an array of strings that is a range of months, e.g. Jan 2022, Feb 2022, May 2022. I am wondering if it is possible to determine the orders of the tick values that is shown on the bar chart?

**Comment by tkonopka** [comment]
Hi. A codesandbox would be helpful to understand precisely what you are trying to achieve. Just in case, some comments about ticks and re-ordering.

A `tickValues` array can specify what tick marks to display along an axis, but it doesn't control the layout or the content of the chart. To change how data are displayed, you'll have to adjust elsewhere, e.g. the input data.

As an example, consider a bar chart with bars ['A', 'B', 'C'], and heights in the domain [0, 100]. Setting `tickValues=[0, 50, 100]` on the vertical axis will tune the visible ticks. But setting `tickValues=[0, 100, 50]` with a different order will not change the chart. Indeed it isn't even clear what it would mean for a value axis to have 100 between 0 and 50. So the chart ignores the order in `tickValues` and just places ticks at the specified locations. Similarly, setting `tickValues=['A', 'B']` on the horizontal axis will label two of the bars (and omit a label for 'C'), but changing that to `tickValues=['B', 'A']` will not have further effects.

To change the arrangement of the bars, it is necessary to change the data object. Continuing the example above, to create a custom order such as ['B', 'A', 'C'], prepare the data like this:

```
const data = [
  { id: 'B', ... },
  { id: 'A', ... },
  { id: 'C', ... }
]
```

With this data (using `indexBy='id'` and all the other usual props), the chart will place the bars in the custom order and the tick marks will adjust accordingly.

**Comment by matteo1222** [comment]
Thank you for the detailed explanation, and it is what I am trying to achieve.
