### ISSUE TITLE
Slow focus performance on canvas heatmap

### ISSUE THREAD

**Issue by jhanggi** [plouc/nivo#2087]
**Describe/explain the bug**

If you have sufficient amount of data, the active row/column focus (active row/column are solid while others get some transparency/opacity) and the tooltip movement start to get pretty laggy.

It feels pretty ok on a 10x300 grid, but once we get to 10x1000 (all of our desired heatmaps are a small number wide by very tall) it starts to feel sluggish.

Does anyone have a workaround?

If we can't fix this performance, is there a way to disable the opacity focus? I can update `inActiveOpacity={1}`, but it still does the work and the tooltip is still sluggish. 

(We may want to disable the opacity and also change the tooltip to onClick for other reasons in which case it would be nice to separate the active hover behavior from the tooltip and onClick--`isInteractive` disables everything. Should that be a separate feature request?)

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-mft8dh?file=src%2FApp.tsx

Here is a sandbox with a 10x1000 grid. On my recent M1 mac, it feels super sluggish as you hover around compared to something in the say 10x300 range. It's downright painful on a slower windows machine I have to work with. You can adjust the size of the grid in the `generateXYSeries` call.

**Expected behavior**

I except the animation to continue to feel smooth up to a much higher size.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 103.0.5060.134

-OS: Windows 10 Pro
- Xeon CPU E5-2686 v4 @ 2.30GHz (is super slow)
- Browser: Chrome
- Version Version 102.0.5005.115

**Comment by plouc** [comment]
@jhanggi, did you experience the same with a production build?

What you can try for now is to add:

```
animate={false}
hoverTarget="cell"
```

You might also want to try to reduce the size of the canvas, in your example it's 786*50,000 (39,300,000), which is huge.

**Comment by jhanggi** [comment]
@plouc That definitely helps as well as shrinking the height of the canvas. 

It still gets a little laggy (we have a lot of data that we want to show in these heatmaps). Is it possible to completely turn off the hover target without turning off the tooltip as well? Or possibly switch the tooltip to reveal `onClick`? 

It looks like to turn the hover off we would need to use `isInteractive={false}` but it looks like that would also disable any click handling.

**Comment by Saroopashree** [comment]
Is there any updates in this regard?

**Comment by jhanggi** [comment]
It'll take me a bit to get the stackblitz working, but in the meantime what we discovered is that the browser can handle 1000s of `<canvas>`es much better than it can handle one giant canvas. Turned out the same was true of `<svg>`s. (I suspect because it's smart enough to not think about those elements not in the viewport.)

So what we ended up doing was creating a Nivo heatmap for each individual row. We conditionally turned off axisTop and margin top after the first row so they stack on top of each other. After that, adding virtualization via the `react-window` library was fairly easy.

This approach does have some downsides, but we were fine with these:

* It might not work if your heatmap is really wide: ours are only 10-20 cells wide, but thousands tall
* You can't do the vertical active/hover state, so you pretty much can only highlight the current cell.
* We had to do some hackery with the tooltip to use a React portal (`createPortal`) to prevent it from getting cut off by the virtualization's `overflow: hidden;`
* Due to the virtualization, there is sometimes a flash of white if you scroll too fast, but we've decided that's ok

**Comment by milliechan** [comment]
Hi there I'm also experiencing the same issue but with a different dimension (40 columns and 380 rows at a minimum since this is dynamic). I've tried all the solutions above related to changing the props and still notice the tooltip hovering lag issue. Any help would be appreciated! 

To Reproduce: (with 40x380 grid)
https://stackblitz.com/edit/vitejs-vite-orbc5p?file=src/App.tsx
