### ISSUE TITLE
0.79.1 of @nivo/core is not available via npm

### ISSUE THREAD

**Issue by nehalist** [plouc/nivo#2091]
https://github.com/plouc/nivo/releases/tag/v0.79.1 was released in Jan this year, but it's still not available via npm. Since it seems like it includes a fix to the `ResizeObserver is not defined` for ssr rendering it would be awesome to publish to npm.

**Comment by tkonopka** [comment]
Please see #2051 #2002

**Comment by plouc** [comment]
It is normal, it didn't have changes compared to other packages, please see https://github.com/plouc/nivo/issues/2051 and https://github.com/plouc/nivo/issues/2002. I've released a new version, `0.80.0` including this fix.
