### ISSUE TITLE
Optional property for Sankey diagrams for styling the cursor on mouse hover

### ISSUE THREAD

**Issue by nklswbr** [plouc/nivo#2093]
**Is your feature request related to a problem? Please describe.**
For sankey diagrams (`<ResponsiveSankey />` component), I want to be table to style the cursor when a node or link gets hoverd with the mouse

**Describe the solution you'd like**
I think a good solution would be if there would be properties like **_nodeHoverCursor_** and **_linkHoverCursor_** and then types for those properties like "pointer" for example. So basically the ones provided by the default [CSS cursor property](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor).

**Describe alternatives you've considered**
Perhaps it would be enough if there were properties like **_nodeHoverCursorPointer_** and **_linkHoverCursorPointer_** that take a boolean as value.

**Comment by ricky-cc** [comment]
any update for this?
