### ISSUE TITLE
Theme Inner Background color?

### ISSUE THREAD

**Issue by just-Bri** [plouc/nivo#2102]
**Is your feature request related to a problem? Please describe.**
Feature Request:
I would love the ability to change the background color of only the chart area.
For reference setting the background color changes the color for the entire area the chart is in:
![image](https://user-images.githubusercontent.com/4626724/183463152-1b28faa4-434c-4fb2-a1ab-265b2edb800f.png)

My ask: add a prop that allows setting a background color for only the chart area, as in it would not apply to anything outside the the line of the chart.
In the chart above the area I would like to change is this:
![image](https://user-images.githubusercontent.com/4626724/183463782-d2914bef-5738-417e-ab90-1e0c7d808866.png)

**Describe the solution you'd like**
Adding a prop that allows setting a background color for only the chart area

**Additional context**
This is the old chart I am working on replacing for context:
![image](https://user-images.githubusercontent.com/4626724/183463987-304b95b5-3170-4f66-903c-fdbffdd59f84.png)

**Comment by just-Bri** [comment]
While messing around in devtools I got to this point but I'm not sure how I would alter the 
![image](https://user-images.githubusercontent.com/4626724/183464554-3dbbb61b-9f80-462e-9672-caff4ab416ee.png)

I moved the `<rect />` components inside the root `<g>` to the top of the render, changed their fill color to 'blue', and changed their opacity to 100.

Will do some digging when I have more time.

**Comment by JamesTheBald** [comment]
I would also love to see this feature implemented. Please re-open this feature request.

**Comment by JamesTheBald** [comment]
BTW, this feature has been standard in MS Excel graphs since the 90s. I think it'll be easy to implement.
