### ISSUE TITLE
Bars in bar chart always animate horizontally

### ISSUE THREAD

**Issue by rbourdon** [plouc/nivo#2107]
**Describe/explain the bug**
The bars in a bar chart animate horizontally regardless of the orientation. 

**To Reproduce**
[Codesandbox](https://codesandbox.io/s/fancy-fire-4yet2k?file=/src/BarTest.js)

1. Open the codesandbox link
2. Observe the bars animating horizontally on component mount.
3. Change some piece of the data.
4. Observe the bars animating horizontally when data changes.

**Expected behavior**
I expect vertical bars to animate vertically and horizontal bars to animate horizontally.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 104.0.5112.79

**Additional context**
This appears to have been introduced with 0.74.0

**Comment by angusedwards64** [comment]
Hey! I was looking at addressing the same thing - is there now a way to animate them in vertically?

**Comment by valentinkostadinov** [comment]
Running into the same issue. This forces me to be stuck on version 0.74.0.

**Comment by valentinkostadinov** [comment]
Found a fix - just the direction explicitly instead of relying on the default and the animation is back to normal:
 `layout={'vertical'}`

**Comment by rbourdon** [comment]
> Found a fix - just specify the direction explicitly instead of relying on the default and the animation is back to normal: `layout={'vertical'}`

Confirming this is a workaround for this issue. Thanks!

**Comment by angusedwards64** [comment]
Brilliant thanks! Very simple. Gracias!
