### ISSUE TITLE
Bar/BarCanvas tooltip positioned incorrectly

### ISSUE THREAD

**Issue by mitoihs** [plouc/nivo#2113]
The image says more than a thousand words:
![tooLongTooltip](https://user-images.githubusercontent.com/61016672/186380549-1bf0aa2e-577a-45d1-ac6d-7ec05fcaf29a.gif)
The tooltip on Bar/BarCanvas charts (at least those) is always displayed above the cursor. If it's too long, it makes its container grow (horizontal scrollbar appears/gets wider).
The same behavior is observed for the vertical dimension, but it's less common for tooltips to "spill" in that way.

Could it please behave like for Line/LineCanvas charts? In those charts, the tooltip is positioned to the cursor's left or right.

Also, I would be able to fix it locally in my custom tooltip if I could control Tooltip's container (or at least its position), but now I have control only over its content.

**Comment by studiosciences** [comment]
Workarounds discussed in #580

**Comment by mitoihs** [comment]
bump
