### ISSUE TITLE
hightlight a grouped bar

### ISSUE THREAD

**Issue by Gabrieldsantos96** [plouc/nivo#2114]
Hi, I'm not fluent, so I apologize if I misspell something.
I searched for similar questions and didn't find anything about it.
but i would like to know if it is possible to highlight a grouped bar based on a prop?
Example: based on date picker value in the upper left corner, i want to highlight a grouped bar.
![image](https://user-images.githubusercontent.com/94016081/186425647-cd3d0338-d7c4-4d01-8a96-c5c89ed3a531.png)

**Comment by Gabrieldsantos96** [comment]
i created a custom bar and then i was able to modify the borders based on a prop.

**Comment by plouc** [comment]
@Gabrieldsantos96, I think that's a good approach, such feature is not supported by default, but yes, you can either customize the component or add an extra layer depending on the desired effect.
