### ISSUE TITLE
Placing Bar labels above bars in Nivo rocks Bar graph

### ISSUE THREAD

**Issue by Ayush11139** [plouc/nivo#2117]
Can someone please provide the working code for placing bar labels above bars in Nivo. I have read some comments about making custom bar or adding a new layer, but I am not able to achieve the UI I want. Any leads are welcome
<img width="844" alt="Screenshot 2022-08-30 at 1 06 10 PM" src="https://user-images.githubusercontent.com/62033517/187377945-3acd569c-742d-4f78-9cec-4ea774aa6d4d.png">

**Comment by plouc** [comment]
@Ayush11139 closing this in favor of the discussion you already created: https://github.com/plouc/nivo/discussions/2118, I got 4 notifications about this via 2 comments on other issues plus 1 issue, plus one discussion, please just report it once, thank you.
