### ISSUE TITLE
Skipping missing time scaled data in Line chart

### ISSUE THREAD

**Issue by ayushbisht2001** [plouc/nivo#2129]
![image](https://user-images.githubusercontent.com/61404154/191306293-7fbc9201-ffb8-4d2f-b2bf-f5b69c8eb25f.png)
I'm using Responsive Line Chart, for displaying a set of data with time field at x-axis. 
As seen in above image, there are various overlapping labels, because of missing X-axis value.
Is there a way to skip dates if the record isn't present... I want type : "time" to behave as type : "point" as in this case it works similar to linear type scaled value.

**Comment by shreyakupadhyay** [comment]
This should help you with displaying let number of x axis values.

```
import { useMemo } from 'react';
import { BarDatum } from '@nivo/bar';

# hook to filter every alternate value on x axis
const bottomAxisValues = useMemo(
   () =>
      data?.map((item, index) => {
        if (index % 2 === 0) {
          return { x: '', y: '' }
        } else {
          return { x: item.x, y: item.y }
        }
      }),
   [data]
);

# render chart
const LineChart = ({
    <LineChart
       axisBottom={{
          tickPadding: 15,
          format: (value: string) => bottomAxisValues.find((item) => item.x === value)) ? value : '';
       }}
     ...

```
