### ISSUE TITLE
Concider exposing the startAngle and endAngle api for dsShape.pie on the Pie component

### ISSUE THREAD

**Issue by Psvensso** [plouc/nivo#214]
It would be great if nivo/pie could support the underlying d3Shape.pie's startAngle and endAngle. 
This would allow us to write halv-pies, gauges etc. 

[https://github.com/d3/d3-shape#pie](https://github.com/d3/d3-shape#pie)
[https://github.com/plouc/nivo/blob/master/packages/nivo-pie/src/Pie.js#L114](https://github.com/plouc/nivo/blob/master/packages/nivo-pie/src/Pie.js#L114)

**Comment by plouc** [comment]
really like the idea :)

**Comment by plouc** [comment]
WIP on https://github.com/plouc/nivo/pull/220

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/220
