### ISSUE TITLE
NPM Install failing with latest ReatJS

### ISSUE THREAD

**Issue by DenysAshikhin** [plouc/nivo#2157]
**Describe/explain the bug**

It seems to stem from the fact that I am on a more latest version of react (reactjs) than what nivo 0.31 (latest nivo?) supports. Is there a way to make it nivo accept a newer react? I can locally fix force it to work by using npm install --force but I cannot use this solution for the automated build...

**To Reproduce**
I'm having issus with an automated npm install that I cannot modify. Here is the relevant issue:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: nivo@0.31.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@"^16.8.0 || ^17 || ^18" from @azure/msal-react@1.4.9
npm ERR!   node_modules/@azure/msal-react
npm ERR!     @azure/msal-react@"^1.4.9" from the root project
npm ERR!   48 more (@nivo/annotations, @nivo/axes, @nivo/bar, @nivo/colors, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.6.1 < 17.0.0" from nivo@0.31.0
npm ERR! node_modules/nivo
npm ERR!   nivo@"^0.31.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@">= 15.6.1 < 17.0.0" from nivo@0.31.0
npm ERR!   node_modules/nivo
npm ERR!     nivo@"^0.31.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Expected behavior**
The npm build should succeed with latest version of reactjs

**Desktop (please complete the following information):**
 - OS: Latest Win10
 - Browser [e.g. chrome, safari] N/A
 - Node: 18.10.0
 - NPM: 8.8.0

**Additional context**
The automated build cannot be changed/flags cannot be passed so solutions like adding `--force` will not work. However, for local purposes I tested and can confirm that --force will fix it, so the error should be more of a warning.

**Comment by DenysAshikhin** [comment]
Fixed by removing the legacy Nivo dependency in favour of the nivo/coew

**Comment by plouc** [comment]
@DenysAshikhin, `nivo` is the legacy package containing everything, you need to install the package you need, for example `@nivo/core`, `@nivo/line`... But I guess that's what you did.

**Comment by DenysAshikhin** [comment]
@plouc 

Thanks for the quick reply I haven't had a chance to return and close the issue. I got some help over on discord channel and essentially it came down to removing the lgacy `nivo` as you said. I'm not sure where it came from or why it was in the packgage.json ... but it wasn't needed and just breaking things.  After I removed it, reset my node modules everything worked fine!
