### ISSUE TITLE
Date tickValues aren't respected

### ISSUE THREAD

**Issue by MattB543** [plouc/nivo#2163]
**Describe/explain the bug**
When creating a line chart w/ 6 data points w/ dates the chart contains 5 ticks which are 1 day off from the data.

**To Reproduce**
[Sandbox link, but idk why it's not rendering here at all...](https://codesandbox.io/s/nivo-line-chart-time-bottom-tick-bug-42vt7y?file=/src/index.js)

1. Create this Responsive Line:
```
<ResponsiveLine
                      margin={{ top: 20, right: 20, bottom: 25, left: 20 }}
                      data={[
                        {
                          id: "Messages received",
                          data: posts,
                        },
                      ]}
                      axisLeft={{
                        format: (e) => Math.floor(e) === e && e,
                        tickValues: Math.max(...posts.map((o) => o.y)),
                      }}
                      xFormat="time:%Y-%m-%d"
                      yFormat=" >-.1d"
                      yScale={{
                        type: "linear",
                      }}
                      enableGridX={true}
                      enableGridY={true}
                      gridYValues={0}
                      gridXValues={0}
                      axisBottom={{
                        format: "%b %d",
                        tickValues: posts.length,
                      }}
                      xScale={{
                        type: "time",
                        format: "%Y-%m-%d",
                        useUTC: true,
                        precision: "day",
                      }}
                      enablePointLabel={true}
                      curve={"monotoneX"}
                      enableSlices={false}
                    />
```

With this data:
```
posts = [
    {
        "x": "2022-09-05",
        "y": 4
    },
    {
        "x": "2022-09-12",
        "y": 0
    },
    {
        "x": "2022-09-19",
        "y": 0
    },
    {
        "x": "2022-09-26",
        "y": 4
    },
    {
        "x": "2022-10-03",
        "y": 0
    },
    {
        "x": "2022-10-10",
        "y": 5
    }
]
```

**Expected behavior**
The exact same Line graph as below, but with 6 ticks, one for each data point w/ the correct date for each data point.

**Screenshots**
Currently, it looks like this:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/45475210/195729412-c76684e8-fdbe-4f86-b996-0a0aadda2acb.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 106.0.5249.119

**Comment by MattB543** [comment]
Bumping this thread. Still not sure if this is a configuration error or an actual bug.

**Comment by tkonopka** [comment]
Hi @MattB543. The placement of ticks is done on a best-guess basis, and it seems they are placed on the Sunday of each week. Your data has values for dates that are all Mondays, so that is why the points and labels are off by one day.

To align the labels with the data, specify the tick values explicity as an array of date objects, e.g.

```
const tickDates = [
  "2022-09-05",
  "2022-09-12",
  "2022-09-19",
  "2022-09-26",
  "2022-10-03",
  "2022-10-10"
].map(x => (new Date(x))) 
```

Then, use `tickValues: tickDates` inside `axisBottom`. 

This works with the current version of nivo (0.80), but am not sure about other versions.

**Comment by MattB543** [comment]
Thank you, @tkonopka, you're right! It's a Sunday/Monday issue. Supplying the tickValues at dates works great.
