### ISSUE TITLE
Bars with zero value are not able to render labels

### ISSUE THREAD

**Issue by RobertHosking** [plouc/nivo#2172]
It seems like the issue in #874 is back. I am unable to render a zero above the bar when it's value is 0. 
See this code sandbox:
https://codesandbox.io/s/nivo-basic-demo-forked-ut2b5j?file=/src/index.js

All bars should render their value above the bar. Should be able to render a zero above the x-axis to stand in place for a zero valued bar.

**Comment by plouc** [comment]
Please see https://github.com/plouc/nivo/issues/2646#issuecomment-2425305251.
