### ISSUE TITLE
Scatterplot: Wrong x/yScale prop type

### ISSUE THREAD

**Issue by cbix** [plouc/nivo#2173]
https://github.com/plouc/nivo/blob/3e639a28bc969ded57ad881a776ad973645ecdbf/packages/scatterplot/src/types.ts#L86-L88

I believe the `AnyScale` type here is wrong and it's supposed to be some d3 scale function

**Comment by tkonopka** [comment]
This is pointing to lines from one of my PRs. @cbix, could you elaborate on what you mean, please? 

`AnyScale` is a stand-in for a previous `Scale<any, any>` and it is meant to accept several d3 scale functions such as linear scales or log scales. (It requires the scale objects to also have a property 'type' to help distinguish between them).

The name 'AnyScale' is perhaps imperfect in capturing a more specific meaning [here](https://github.com/plouc/nivo/blob/3e639a28bc969ded57ad881a776ad973645ecdbf/packages/scales/src/types.ts#L124) and [here](https://github.com/plouc/nivo/blob/3e639a28bc969ded57ad881a776ad973645ecdbf/packages/scales/src/types.ts#L30-L42). But is this causing other kind of trouble?

**Comment by cbix** [comment]
I'm getting Typescript errors when using the scales:
```
error TS2349: This expression is not callable.
  Not all constituents of type 'AnyScale' are callable.
    Type 'ScaleLinear<any>' has no call signatures.
```
I'm using them inside a custom layer component like this:
```ts
export const MyCustomLayer: ScatterPlotCustomSvgLayer<MyDataType> = ({ nodes, xScale, yScale }) => {
  // [...]
  const xMin = xScale(0);
  const yMin = yScale(node.data.value - threshold);
```
`MyDataType` has `{ x: number; y: number }`, so in theory the scales could be inferred as `ScaleLinear<number, number>`, which would then be recognized as callable.

**Comment by tkonopka** [comment]
This could be related to #1947. In short, to develop advanced custom layers with typescript, additional dependencies might be needed. In this case, that could be `@types/d3-scale`.

**Comment by cbix** [comment]
Sorry, I must have missed that issue when searching for existing issues. This indeed solves the issue for me, however I'm wondering why the `@types/d3-scale` dev-dependency of nivo isn't enough here 🤔
