### ISSUE TITLE
Radial Bar Chart ticks value can't be modify

### ISSUE THREAD

**Issue by salihbahcekapili** [plouc/nivo#2177]
Hi,

i use radial bar chart. i can't modify chart tick values. For example i want to use "4 %".

Is there any way to format tick labels in radial bar chart?

![image](https://user-images.githubusercontent.com/37848815/200092730-e4bc3592-59bf-482d-b65d-0113328113a3.png)

**Comment by salihbahcekapili** [comment]
Bump

**Comment by salihbahcekapili** [comment]
Bunp

**Comment by clarkd** [comment]
Would be great to have this functionality

**Comment by lissagoforth** [comment]
Bump!

**Comment by akshaygdhole** [comment]
bump
