### ISSUE TITLE
Area shading on line charts flows outside of the chart when the yScale.min is 'auto'

### ISSUE THREAD

**Issue by danthul** [plouc/nivo#2181]
**Describe/explain the bug**
When you enable area shading on a line chart and allow the y axis min to be auto it cuts off the y axis minimum at the lowest data point. The area shading doesn't seem to recognize this and will shade down to where 0 should be covering up the x axis labels.

**To Reproduce**
https://codesandbox.io/s/festive-wildflower-yu7gmi?file=/src/App.js

1. Enable area shading and leave yScale.min at default 'auto'
2. All data needs to be above 0 to see problem

**Comment by plouc** [comment]
Yes, it doesn't use the min value, but you can pass it to `areaBaselineValue`.
