### ISSUE TITLE
Invalid dom-element with negative width while rendering Line elements and slices

### ISSUE THREAD

**Issue by Lillskogen** [plouc/nivo#2182]
**Describe/explain the bug**
An invalid dom-element is sometimes generated when data-points exist outside the configured xScale-range.

**To Reproduce**
Create a Line element with an xScale range with a max value set. Enable slices for the configured scale (e.g. enableSlices="x").
Render the line element with data that has data-points greater than the configured xScale range. An error message is generated in chrome. The error message is related to a slice element that is outside the visible area of the control.

```
react-dom.development.js:798 Error: <rect> attribute width: A negative value is not valid. ("-14.895833333333371")
setValueForProperty @ react-dom.development.js:798
setInitialDOMProperties @ react-dom.development.js:9720
setInitialProperties @ react-dom.development.js:9921
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

Reproduction sample: https://codesandbox.io/s/nivo-slicing-dom-error-with-value-range-dmtcsb?file=/src/index.js:404-420

**Expected behavior**
No error output in browser. No invalid dom-elements generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1154002/201990171-1172ed1f-0a4b-4081-a79f-41425a811e1b.png)

![image](https://user-images.githubusercontent.com/1154002/201991467-86db7b9a-b2c2-4faa-b592-6afbd0581cf0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 107.0.5304.107

**Additional context**
We want to be able to supply datapoint outside the visible range to create lines that connects to points before or after the visible timespan. 

The code in https://github.com/plouc/nivo/blob/master/packages/line/src/hooks.js: 
`if (!nextSlice) sliceWidth = width - x0`

Needs to consider that the datapoint position could be greater than the width of the control. Corresponding code for yScale needs to be fixed as well.

**Comment by robertsargent** [comment]
bump

**Comment by robertsargent** [comment]
bump

**Comment by YochayCO** [comment]
This still happens, though it does not have any visual effect.
