### ISSUE TITLE
Line chart showing incorrect trend

### ISSUE THREAD

**Issue by shahrukhitsme** [plouc/nivo#2190]
**Describe/explain the bug**
Line chart showing incorrect data for Line 2, Point 2 and Point 6

Use data below:
`[
  {
    "id": "Line 1",
    "data": [
      {
        "x": "Point 1",
        "y": "7"
      },
      {
        "x": "Point 2",
        "y": "9"
      },
      {
        "x": "Point 3",
        "y": "3"
      },
      {
        "x": "Point 4",
        "y": "3"
      },
      {
        "x": "Point 5",
        "y": "1"
      },
      {
        "x": "Point 6",
        "y": "1"
      },
      {
        "x": "Point 7",
        "y": 0
      }
    ]
  },
  {
    "id": "Line 2",
    "data": [
      {
        "x": "Point 1",
        "y": "11"
      },
      {
        "x": "Point 2",
        "y": "9"
      },
      {
        "x": "Point 3",
        "y": "4"
      },
      {
        "x": "Point 4",
        "y": "3"
      },
      {
        "x": "Point 5",
        "y": "1"
      },
      {
        "x": "Point 6",
        "y": 0
      },
      {
        "x": "Point 7",
        "y": "1"
      }
    ]
  }
]`

Checkout the sandbox here: https://codesandbox.io/s/nivo-line-graph-component-forked-f1kv2p?file=/src/data.json

Open the sandbox. And see that the chart is incorrectly rendered.

**Expected behavior**
Line chart should show correct data points

**Screenshots**
https://drive.google.com/file/d/1KKgv7KZO_fU7WLidY4YbP57JfS4NRpqw/view?usp=share_link

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 107.0.5304.110

**Comment by tkonopka** [comment]
Hi @shahrukhitsme. The chart looks correct to me. Line 2 is stacked on top of line 1, so the position of line 2 on the chart does not correspond exactly to the values in your json. To show line 2 in a more conventional way, i.e. without stacking, set `yScale={{ stacked: false }}`.
