### ISSUE TITLE
ResponsiveBar axis values "sticking" when swapping datasets with a custom renderTick

### ISSUE THREAD

**Issue by dakotaray571** [plouc/nivo#2198]
**Describe/explain the bug**
Using a custom renderTick with Nivo's <ResponsiveBar /> component breaks the transition animation that plays when swapping between datasets. The y-axis values will "stick" for a moment then dissappear. 

**To Reproduce**
https://codesandbox.io/s/lucid-stallman-mdsn67?file=/src/App.js:1026-1041
This is a sandbox of the issue described above. Click between "dataset 1" and "dataset 2" and you'll see the numbers on the y-axis erroneously "sticking". 
You may also disable the custom renderTick to see the correct animation by clicking "Tick is disabled: false". This will remove the custom renderTick and when swapping between the datasets you'll now see that the normal animation has returned. 

**Expected behavior**
I'd expect the default transitioning animation to play even when adding a custom renderTick. 

**Screenshots**
This is the chart transitioning between two datasets and the y-axis values "sticking". 
Note that these axis values aren't fading out like you'd expect, they are instead hanging around for a moment then vanishing. 
![image](https://user-images.githubusercontent.com/51932056/207122263-3bc54d81-8838-469b-896d-fb930a9c77cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 108.0.5359.99 (Official Build) (64-bit)

**Comment by ZayneLiu-ND** [comment]
Ran into the same issue, after investigation, turns out for all custom ticks defined, you'll have to pass down how to animate the custom tick element.

e.g., https://github.com/plouc/nivo/blob/master/packages/axes/src/components/AxisTick.tsx

construct `style` and pass it to tick component.

```tsx
const props = useMemo(() => {
        const style = { opacity: animatedProps.opacity }

        if (!onClick) {
            return { style }
        }

        return {
            style: { ...style, cursor: 'pointer' },
            onClick: (event: React.MouseEvent<SVGGElement, MouseEvent>) => onClick(event, value),
        }
    }, [animatedProps.opacity, onClick, value])

    return (
        <animated.g transform={animatedProps.transform} {...props}>
            <line x1={0} x2={lineX} y1={0} y2={lineY} style={theme.axis.ticks.line} />
            <animated.text
                dominantBaseline={textBaseline}
                textAnchor={textAnchor}
                transform={animatedProps.textTransform}
                style={theme.axis.ticks.text}
            >
                {value}
            </animated.text>
        </animated.g>
    )
```

**Comment by dakotaray571** [comment]
Thank you, @ZayneLiu-ND! 
I managed to get things working with your insight. 

Should anyone else stumble across this issue; I did have to add `react-spring` to my main project though as I wasn't able to easily utilize the `animatedProps` without it.
