### ISSUE TITLE
Add background color to bars

### ISSUE THREAD

**Issue by CoolTechYT** [plouc/nivo#2203]
I am trying to find a way to add a full-height background color to my bars. 

Here is an example of what I'd like to accomplish:

<img width="432" alt="Screenshot 2022-12-16 at 6 38 26 PM" src="https://user-images.githubusercontent.com/96965128/208219793-c14e6702-b125-4875-84ec-5b7c49c2065a.png">

Here is what I have currently:
<img width="376" alt="Screenshot 2022-12-16 at 6 38 40 PM" src="https://user-images.githubusercontent.com/96965128/208219803-bde5cd52-8a33-41e1-9995-0c688c9a0ff9.png">

As you can see, I don't have the grey background colors behind the bars... Is there anyway this can be accomplished?

(Also, if anyone knows how to have the curved borders that would be nice!)

**Comment by mohammadyahyaq** [comment]
I have same issue
