### ISSUE TITLE
Is there a way to interact with the legend?

### ISSUE THREAD

**Issue by Aphsai** [plouc/nivo#221]
Hi,

I was just wondering if there was a way to interact with the legend? 

I'm trying to make data toggle based on interaction with the legend, similar to something react charts has.

Any ideas on how to implement something like this would be welcome as well.

**Comment by plouc** [comment]
Hi @Aphsai, it's a work in progress on https://github.com/plouc/nivo/pull/224.

**Comment by plouc** [comment]
I close this issue in favor of https://github.com/plouc/nivo/issues/196 as it's a duplicate.
