### ISSUE TITLE
Pass all the ticks to the `renderTick` function

### ISSUE THREAD

**Issue by liqwid** [plouc/nivo#2211]
**Is your feature request related to a problem? Please describe.**
It's currently impossible to understand the magnitude of all the ticks when rendering a particular one.

E.g. depending on the whole ticks set we want to render:
500, 1000, 1500, 2000 as 0.5K, 1K, 1.5K, 2K
and
100, 200, 300, 400, 500 as 100, 200, 300, 400, 500

**Describe the solution you'd like**
Adding all the ticks to the `renderTick` callback will allow to easily understand the magnitude and also is a really simple change

**Describe alternatives you've considered**
We can understand ticks magnitude from the max data value but it's less of a universal solution, since data formats differ and results in extra calculations

**Comment by plouc** [comment]
It might seem like a simple change, but it's not, the default tick component is memoized, and ticks can be animated, passing all ticks could invalidate the a single tick even if only others changed.
