### ISSUE TITLE
Custom weekday labels for Time Range Chart.

### ISSUE THREAD

**Issue by imp-dance** [plouc/nivo#2213]
**Is your feature request related to a problem? Please describe.**
Yes. I'm implementing Nivo on a website that uses another language than English. 

**Describe the solution you'd like**
`ResponsiveTimeRange` already exposes a prop, `monthLegend` which lets the consumer customise the month labels. Ideally, a new prop would be introduced, `weekdayLegend`, with a similar interface and purpose.

**Describe alternatives you've considered**
I can't really see any other alternatives. I've tried doing some CSS hacks with `::after` but to no avail.

**Additional context**
This feature would ideally also be implemented in the `Calendar` chart.

**Comment by JosePoma11** [comment]
How do I add it to my library if I'm only using @nivo calendar
