### ISSUE TITLE
Custom tooltip render issue

### ISSUE THREAD

**Issue by Pierre-Citima** [plouc/nivo#2218]
**Describe/explain the bug**

I have a problem with the display of tooltips on some graphs while the code is the same.

Here is my custom tooltip code for my Waffle chart : 

```
tooltip={({ id, value, color }) => (
  <div
    style={{
      display: 'flex',
      background: 'white',
      alignItems: 'center',
      borderRadius: '2px',
      boxShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
      padding: '5px 9px',
    }}
  >
    <span
      style={{
        width: 12,
        minWidth: 12,
        height: 12,
        minHeight: 12,
        backgroundColor: color,
        display: 'block',
        marginRight: 7,
      }}
    />
    <span>
      {id} : <strong>{value.toFixed(2)}%</strong>
    </span>
  </div>
)}
```

And here is my custom tooltip code for my Calendar chart : 

```
tooltip={({ day, value, color }) => (
  <div
    style={{
      display: 'flex',
      background: 'white',
      alignItems: 'center',
      borderRadius: '2px',
      boxShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
      padding: '5px 9px',
    }}
  >
    <span
      style={{
        width: 12,
        minWidth: 12,
        height: 12,
        minHeight: 12,
        backgroundColor: color,
        display: 'block',
        marginRight: 7,
      }}
    />
    <span>
      {formatDate(new Date(day), 'dd/MM/yyyy')} : <strong>{value}</strong>
    </span>
  </div>
)}

```

**Screenshots**

And here is what is displayed in both cases :
 
![Capture d’écran 2023-01-13 à 16 57 29](https://user-images.githubusercontent.com/89920234/212364116-b6940666-4da3-4b01-89e1-28ea1dde3530.png)

![Capture d’écran 2023-01-13 à 16 57 45](https://user-images.githubusercontent.com/89920234/212364138-cebde4d5-2b54-4f9f-952f-3f62383e28b5.png)

By inspecting the tooltip DOM of the Waffle chart I realized that the div of the default tooltip is still present whereas it is no longer there in the case of the Calendar chart.

Any idea to solve this problem? Knowing that, as you can see above, the HTML/CSS code of the first div of my tooltips is the same in both cases.

**Desktop**
 - OS: macOS
 - Browsers: Brave / Chrome
 - Versions: 1.45.131 / 108.0.5359.124

**Comment by plouc** [comment]
This isn't really a bug, all nivo packages are independent, and `@nivo/waffle` is still using the _old_ tooltip, keeping the wrapper by default. I'll change this once I migrate the package to TypeScript.
