### ISSUE TITLE
line chart two colored line

### ISSUE THREAD

**Issue by ph98** [plouc/nivo#2228]
Hi, I'm going to implement something like this: 
![image](https://user-images.githubusercontent.com/6303786/215103914-9a357633-2699-403e-a255-141b13cc8de8.png)
the key is having a line with different color based on the value it's showing
I don't have any idea how to implement it in Nivo chart.I hope someone comes up with an idea, thanks in advance.

**Comment by Maverick17user** [comment]
@ph98, Hi there! I'm pretty new user of this library and I'm interested to develop same chart as you! 

To me it seems possible, trying to play with props values at https://nivo.rocks/line/ I've managed to make smith like this:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/30416868/217349760-660707b8-5c4a-4a11-bdd2-ceaa46086889.png">

I've played with `colors` `enableArea` `areaBaselineValuenumber` `areaOpacity` and `areaBlendMode`. To hide X & Y axis is eazy thing to do.

But still, no idea how to paint lines in red and green, when they reach particular value (like, 200, as it's on my chart above)

Me also would love to get any advices how does it possible to implement this kind of chart (probably, with extra D3.js usage, if it's required :) )

**Comment by plouc** [comment]
You can find an example of this kind of chart here: https://nivo.rocks/storybook/?path=/story/line--highlighting-negative-values, the key is to separate the data into 2 datasets.

**Comment by TaylorBruening** [comment]
@plouc 
I have seen give this response a couple of times now. There is an issue with the [highlighting negative values](https://nivo.rocks/storybook/?path=/story/line--highlighting-negative-values)
example though. The only way for it to work is to inject a data point into both the positiveData and negativeData dataset at 0,
Its major flaw is it does not work going just directly from a negative number to a positive, there has to be a waypoint of 0, which can be inaccurate and cause the graph to look quite ugly if you arbitrarily inject that 0 waypoint.

without the "zero" data point injected, there will be breaks in the line.

Do you have any suggestions on how to deal with this? 

ChartJS kind of has something like this, where it is just one line and dynamically changes the color of the line:
https://stackoverflow.com/questions/60190586/chart-js-plugin-to-change-line-color-depending-on-value

**Comment by mihaibogdan** [comment]
@ph98 @plouc  @Maverick17user  @TaylorBruening 

I managed to find a solution to change the color of the line using the same dataset. I think it still has some drawbacks but it might be better than having to add 0's between positive and negative values.

The idea is to use the original plotted line/area as a mask and two rectangles (one rectangle above the 0 line, filled with the color for the positive values, and one below the 0 line, filled with the color for the negative values) that have applied that mask. 

 Here's the implementation: https://codesandbox.io/p/sandbox/nivo-highlighing-negative-values-qv7xkq

**Comment by ph98** [comment]
nice solution @mihaibogdan, 
it looks nice to me, is there any known drawbacks?
