### ISSUE TITLE
Sunburst tooltip does not work v0.80

### ISSUE THREAD

**Issue by mfaradzheva-hubble** [plouc/nivo#2236]
Sunburst tooltip does not show up for v0.80
I used along with @nivo/core": ^0.79.0
Switching to sunburst v0.79.1 tooltip works

**Desktop (please complete the following information):**
 - OS: OS
 - Browser Chrome
 - Version 109.0.5414.119

**Comment by plouc** [comment]
@mfaradzheva-hubble, all nivo versions should be aligned, I think that's why.
