### ISSUE TITLE
Modify labels for axis along with svg icons

### ISSUE THREAD

**Issue by asifkabani** [plouc/nivo#2243]
Hello,

I am trying to see if it is possible to modify the axis on the left to render this view?
![image](https://user-images.githubusercontent.com/9083341/219884602-6d37edcc-4cb9-44f9-8d1f-60f1f0670ab1.png)

**Comment by asifkabani** [comment]
Anybody?

**Comment by plouc** [comment]
@asifkabani, you can play with:

```
axisLeft={{
    renderTick: CustomTick,
}}
```

Where `CustomTick` is a custom component (svg), you can see an example of this here: https://nivo.rocks/storybook/?path=/story/bar--custom-axis-ticks.
