### ISSUE TITLE
Point label color change

### ISSUE THREAD

**Issue by emalo6** [plouc/nivo#2245]
Hi, 

Is it possible to change the following element color?

![image](https://user-images.githubusercontent.com/55895846/220127486-3728eff9-4dfd-4a26-85ae-345cce05f6fb.png)

**Comment by tychtych** [comment]
Yes, you can try accessing via css

  svg {
    g {
      text {
        //try the property fill or color here
       }
     }
}

**Comment by P-Raphat** [comment]
Hi @emalo6, have you solved the problem yet? I have the same problem.

**Comment by plouc** [comment]
You can use `theme.dots.text`, please see https://codesandbox.io/s/nivo-line-label-text-color-fxm5w9?file=/src/index.js.

**Comment by emalo6** [comment]
Thank you so much!
