### ISSUE TITLE
Components should return SVG documents if it's wanted

### ISSUE THREAD

**Issue by sametcodes** [plouc/nivo#2257]
**Is your feature request related to a problem? Please describe.**
Components return SVGs in a relative div. I'm unsure if it was intended, but it causes issues when it's wanted to the returning value as an SVG document because it's wrapped with a div.

![image](https://user-images.githubusercontent.com/9467273/223718033-9acbeaae-3034-409c-9e85-f3e91ccf30a4.png)

**Describe the solution you'd like**
The components can return just the SVG without a div parent element if unnecessary.

**Describe alternatives you've considered**
Or we can have a `document` boolean attribute on the props of components and set it as `false` as default. If it's passed `true`, the returning value won't be wrapped in a relative div, and the SVG tag will have the proper `xmlns` and `xmlns:xlink` attributes to make it an SVG document.

**Additional context**

**Comment by plouc** [comment]
Sorry for the late reply, it is already possible to achieve this by passing `renderWrapper={false}`, but if you do, you'll loose some features, such as tooltips and interactivity in general. This is what I use for the HTTP api where I want to return SVG documents.
