### ISSUE TITLE
Exposing more of the internal implementations of packages to support custom layers

### ISSUE THREAD

**Issue by heath-freenome** [plouc/nivo#2259]
**Is your feature request related to a problem? Please describe.**
While creating custom layers for things like the `Line` chart from `@nivo/line` I have had to literally copy the implementation of `Mesh`, `Lines` and `LinesItem` simply to be able to use them. It would be awesome if all of these internals were exported so that users can build custom layers using them. I'm also wishing I could import  the `CrosshairsLine` implementation in `@nivo/crosshairs` for my custom `Crosshair` layer.

**Describe the solution you'd like**
I would love for each package to export all of the internal classes that help support the main implementation. If the idea of exposing them directly feels challenging, perhaps each package could expose an `unsafe_internals` "subdirectory" that exposes the internals with warnings about "use at own risk".

Here is what I imagine the `index.js` file for the `Line` package could look like:

```
/*
 * This file is part of the nivo project.
 *
 * Copyright 2016-present, Raphaël Benitte.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
import Areas from './Areas'
import Lines from './Lines'
import LinesItem from './LinesItem'
import LineCanvas from './LineCanvas'
import Mesh from './Mesh'
import Points from './Points'
import PointTooltip from './PointTooltip'
import ResponsiveLineCanvas from './ResponsiveLineCanvas'
import Slices from './Slices'
import SlicesItem from './SlicesItem'
import SliceTooltip from './SliceTooltip'

/*
 * Exported to assist in building custom layers, use at own risk as the interfaces and implementations may change
 */
const unsafe_internals = { Areas, Lines, LinesItem, LineCanvas, Mesh, Points, PointTooltip, ResponsiveLineCanvas, Slices, SlicesItems, SliceTooltip };
export unsafe_internals;

export { default as Line } from './Line'
export { default as ResponsiveLine } from './ResponsiveLine'
export { default as LineCanvas } from './LineCanvas'
export { default as ResponsiveLineCanvas } from './ResponsiveLineCanvas'
export * from './props'
export * from './hooks'
```

**Describe alternatives you've considered**
 Copying huge chunks of code directly from Nivo.

**Additional context**
I'm willing to make a PR to do this for as many packages as seem useful if this approach feels good to you @plouc

**Comment by plouc** [comment]
My main concern with this is documentation, which I wouldn't be able to provide for those, also most of them require contexts... That being said I like the idea of somehow flagging them, even if I'm pretty sure it'll lead to some issues/questions 😅. I think I could find the time to review such PR as there wouldn't be much logic.
