### ISSUE TITLE
Legend for nivo/ResponsiveWaffle

### ISSUE THREAD

**Issue by Amev** [plouc/nivo#226]
Hello,

First, you are doing a great job with this lib! :)

Are you planning to add a legend support to the Waffle graph soon?

Thank you

**Comment by plouc** [comment]
Hi @Amev. yes, it's part of https://github.com/plouc/nivo/pull/224 :)

**Comment by plouc** [comment]
as #224 was a little bit bloated, moved to #273

**Comment by plouc** [comment]
Fixed by #273
