### ISSUE TITLE
align ={'justify'} in Area Bump chart

### ISSUE THREAD

**Issue by meowmiyamoto** [plouc/nivo#2262]
Is there a way to justify the y-axis in the Area Bump chart? Basically to distribute items in the y-axis with even space so that the top and the bottom of the start and end would align.

**Comment by plouc** [comment]
There's no such feature for the bump chart, you can only use `start`, `middle` and `end`.

**Comment by meowmiyamoto** [comment]
Thank you. Any chance that justify could be added in the future?
