### ISSUE TITLE
Upgrade d3-color to >= 3.1.0 to avoid security vunerability

### ISSUE THREAD

**Issue by captainamerican** [plouc/nivo#2265]
**Describe/explain the bug**

`d3-color` < `v3.1.0` has a [high-level security vunerability](https://github.com/advisories/GHSA-36jr-mh4h-2g58). The solution is to upgrade the version to `3.1.0` or above.

**To Reproduce**

1. Run `npm audit` with nivo installed. 
4. See error (I'll post my logs in a comment)

**Expected behavior**
There should be no security error relating to nivo.

**Additional context**
Upgrading `d3-color` is the prescribed solution, but it might require upgrading other d3 libraries as well.

**Comment by BruceHubbard** [comment]
There was a PR merged recently that addresses this (https://github.com/plouc/nivo/pull/2142/files) but I don't think there has been a release yet that contains the fix (I'm waiting on it as well)

**Comment by francescocretti** [comment]
Hu @plouc. I'm waiting for the release with the d3-color upgrade too.

**Comment by Cellule** [comment]
That PR is not sufficient because version 2 is still being installed by `d3-scale-chromatic` and `d3-interpolate`
https://github.com/plouc/nivo/blob/4240e36ce5ffa556470e40d20ec57cc6ec243a23/yarn.lock#L9620-L9628

**Comment by sebasegura97** [comment]
Hi @plouc! I'm waiting for the release too

**Comment by StijnKlarenbeek** [comment]
Any update on this?

**Comment by plouc** [comment]
`d3-color` has been updated (in `@nivo/*@0.81.0`), but this can lead to [issues](https://github.com/plouc/nivo/issues/2310).
