### ISSUE TITLE
Sankey circular deconstructed

### ISSUE THREAD

**Issue by flaunder007** [plouc/nivo#2266]
Now there is no way to build sankey diagram with circular links. But this function can be realised. I have found some refs here: 
https://observablehq.com/@tomshanley/sankey-circular-deconstructed
https://observablehq.com/@tomshanley/sankey-circular-deconstructed-part-2-manual-scaling/2

Can you add this to sankey diagram please?

**Comment by SkylarWidman** [comment]
bump
