### ISSUE TITLE
Responsive Charts Legends Overflow

### ISSUE THREAD

**Issue by joaopedromatias** [plouc/nivo#2268]
**Describe/explain the bug**

It is not possible to see the chart legends when there are many items.

### Data:

<img width="324" alt="Captura de Tela 2023-03-16 às 11 23 48" src="https://user-images.githubusercontent.com/90068133/225647396-ead8c089-962f-4c96-8749-d30fe6889f46.png">

### Result:

<img width="1149" alt="Captura de Tela 2023-03-16 às 11 24 16" src="https://user-images.githubusercontent.com/90068133/225647571-61e3c8bf-6ce4-497b-88bc-cd85fb95ebe3.png">

**Expected behavior**

The legends could continue on the next line when it overflows the parent element width.

 - OS: MacOS
 - Browser: Chrome
 - Version: 111.0.5563.64

**Comment by joaopedromatias** [comment]
@plouc can you tell me if there is a duplicate or discussion around this kind of problem? 
I mean the chart keys legends and not the charts axis labels

**Comment by joaopedromatias** [comment]
@plouc can you please tell me if there is a duplicate or discussion around this kind of problem? 
I mean the chart keys legends and not the charts axis labels

**Comment by jasonamyers** [comment]
> I was able to solve by adding a custom legend bar, so I'm closing this

@joaopedromatias any chance you can share an example?

**Comment by joaopedromatias** [comment]
Sure @jasonamyers!

I use the fixed color theme `set2`, so the available colors are fixed on the array.
The component receives `keys` as props, which is an array of the available chart dimensions strings to be displayed.

```ts
const nivoColorSet2Order = [
  '#7ECBB3',
  '#FC8D62',
  '#8D9FCA',
  '#E789C3',
  '#A5D853',
  '#FFDF58',
  '#E5C494',
  '#B8B8B8'
]

interface Props {
  keys: string[]
}

export const CustomLegend = ({ keys }: Props) => {
  let colorCount = -1;
  return (
    <div
      style={{
        display: 'flex',
        gap: '10px',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: '30px',
        marginLeft: '50px',
        marginRight: '50px',
        overflowX: 'auto',
        overflowY: 'hidden',
        lineBreak: 'auto'
      }}
    >
      {keys.map((chartKey, index) => {
        colorCount++;
        if (colorCount === 8) {
          colorCount = 0;
        }
        return (
          <div
            key={index}
            style={{
              paddingBottom: '5px',
              flexShrink: 0,
              fontFamily: 'sans-serif',
              fontSize: '12px',
              fill: 'rgb(51, 51, 51)',
              '&:hover': {
                backgroundColor: 'rgba(0, 0, 0, .05)',
                cursor: 'pointer'
              }
            }}
          >
            <div
              style={{
                display: 'flex',
                flexWrap: 'nowrap',
                gap: '2px',
                justifyContent: 'flex-start',
                alignItems: 'center'
              }}
            >
              <div
                style={{
                  width: '3px',
                  height: '3px',
                  borderRadius: '50%',
                  backgroundColor: nivoColorSet2Order[colorCount]
                }}
              ></div>
              <span>{chartKey}</span>
            </div>
          </div>
        );
      })}
    </div>
  );
};

```

**Comment by jasonamyers** [comment]
> The component receives `keys` as props, which is an array of the available chart dimensions strings to be displayed.

ahh, so you're passing the data for the char components to both of them. Thank you so much for sharing this!!!

**Comment by hpecarlos** [comment]
> ```ts
> CustomLegend
> ```

How do you plug in `CustomLegend` into the line chart component?

**Comment by joaopedromatias** [comment]
For the bar chart I just sort the chart keys (not indexes) on the front end and pass it for both components, the `<CustomLegend />` and `<ResponsiveBar />` in the keys prop.

For the line chart it is trickier than for the bar chart, because it does not have the "keys" prop. So first I need to pre-order all the data of the line chart (it is done in the backend). After that, on the frontend, all of its dimensions (which are the `id` property of the data) are passed on the keys prop for the `<CustomLegend />`. This way it gets in sync with the line chart, even it does not allowing us to sort the data with a prop like the bar chart.

```
<CustomLegend
        orderType={orderType}
        dimensionsToFilter={dimensionsToFilter}
        setDimensionsToFilter={setDimensionsToFilter}
        chartType="line"
        chartOriginalData={chartOriginalData}
        worker={worker}
        keys={keys}
      />
      {chartOriginalData.length > 1 ? (
        <ChartPagination
          xAxisPage={xAxisPage}
          setXAxisPage={setXAxisPage}
          chartPages={chartPages}
        />
      ) : (
        <></>
      )}
      <ResponsiveLine
        data={chartData[xAxisPage]}
        {...lineChartCommonProps}
        colors={(d: { id: string }) => {
          const key = d.id
          const index = keysArr.findIndex((value) => value === key)
          const color = customColors[index]
          return color
        }}
        axisLeft={{
          tickSize: isMobile ? 0 : 5,
          tickPadding: isMobile ? 50 : 5,
          tickRotation: 0,
          tickValues: 10,
          legend: `Cost (${exchangeDisplay})`,
          legendPosition: 'end',
          legendOffset: -75
        }}
        margin={{ ...lineChartCommonProps.margin, bottom: bottomMargin }}
        sliceTooltip={(event: CustomTooltipEventLine) => (
          <CustomTooltipLine exchangeDisplay={exchangeDisplay} event={event} />
        )}
      />
```
