### ISSUE TITLE
Add gridYValues and gridXValues to Line chart

### ISSUE THREAD

**Issue by emanuelebrivio** [plouc/nivo#227]
I saw here https://github.com/plouc/nivo/pull/170/commits/420b96844a8dc31e57ada617ed0db02aacc36bca that there is support for gridYValues to the Bar component. I've tried it also with the Line component but with no luck.

**Comment by plouc** [comment]
Implemented via https://github.com/plouc/nivo/commit/b44c85437e8ccd204a266e830427f0527c5b77b5
