### ISSUE TITLE
Turn on Mouse Pointer when OnClick is used

### ISSUE THREAD

**Issue by Omzig** [plouc/nivo#2276]
**Is your feature request related to a problem? Please describe.**
My users do not know that you can click on the elements in the chart, because there is no "cursor: pointer;".

**Describe the solution you'd like**
Somehow it would be nice to turn on "cursor: pointer;" when i have added an OnClick to a chart element.

**Describe alternatives you've considered**
Hacking the DOM.

**Comment by ckesplin** [comment]
One workaround is to add a little JavaScript to the component.  e.g.
```
<ResponsiveBar
  { ... ResponsiveBarProps }
  onMouseEnter={(_datum, event) => {
  event.currentTarget.style.cursor = "pointer";
  }}
  isInteractive
/>
```

But, yes, it is still a little bit of "Hacking the DOM".

**Comment by chrischriscris** [comment]
bump

**Comment by LeopoldArkham** [comment]
Also interested in seeing a prop added for this

**Comment by Omzig** [comment]
stale but still valid /facepalm
