### ISSUE TITLE
Tooltip flickering on first render

### ISSUE THREAD

**Issue by federicocappellotto97** [plouc/nivo#2277]
Tooltip is flickering on first render
You can see the bug in this video:
https://user-images.githubusercontent.com/63153191/228231201-3830d437-a008-4a85-9d42-aa295dbda2b1.mov

Codesandbox [here](https://codesandbox.io/s/adoring-matan-9w2052?file=/src/App.js)

**Comment by jrnxf** [comment]
Also seeing this. Our tooltip is big too, so the flicker is really obnoxious. Any comment here @plouc?

**Comment by alex20044** [comment]
Experiencing the same issue, any workarounds found?

**Comment by plouc** [comment]
I'll need to have a look at this, I also noticed this issue.

**Comment by CyrusNG** [comment]
some hotfix here #2161 
also my hot fix: https://github.com/plouc/nivo/issues/2161#issuecomment-1545265602

**Comment by DimaAmega** [comment]
Hi guys! I fixed it in #2480
