### ISSUE TITLE
Website crashes when clicked on Add Legend button on the bar page

### ISSUE THREAD

**Issue by Nanak360** [plouc/nivo#2288]
# **BUG**
Website crashes when clicked on Add Legend button on the bar page

## Steps to reproduce the behavior:
1. Go to 'https://nivo.rocks/bar/'
2. Click on 'add legend' button. Can be found under legends section

**Expected behavior**
New legends should be added to the chart

**Actual behavior**
Screen goes white

**Screenshots**
on deployed website:
![Tab-1680499869883-website](https://user-images.githubusercontent.com/36790357/230063621-2dfd145d-63dd-493c-9bde-a3547fb84660.gif)

on local dev environment:
![Tab-1680499836483-with error](https://user-images.githubusercontent.com/36790357/230063870-af5d027d-f622-4223-8b46-4dd09e8a5d0f.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS 13.2
 - Browser: Chrome

**Additional context**

**Comment by Nanak360** [comment]
#2282 has a fix for it

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/2282.
