### ISSUE TITLE
color scheme modifiers for heatmaps

### ISSUE THREAD

**Issue by eddielee394** [plouc/nivo#2290]
Looking to apply some modifiers to the default color schemes within a heatmap.  Just looking to use the `brighter` modifier to lighten the scheme colors, but not seeing anything in the api or docs on how to handle that?

**Comment by plouc** [comment]
Color modifiers are not available in this context.

**Comment by eddielee394** [comment]
Thanks for the reply!  Just wanted to circle back to this in case someone else comes along looking to accomplish something similar.  The workaround I implemented was to pass in a `colors` property to the colorscale config in the chart `colors` prop.  Even though I was no longer able to utilize the built in color schemes, this allowed me to create a `[min, max]` color range where i could use a lighter `max` color than what was provided by the default schemes.  Implementation looked something like this:  

```
                <ResponsiveHeatMapCanvas
                    data={data}
                    colors={
                        {
                          type: 'sequential',
                          colors: ['#e6f4fd', '#3a98f8']
                         }
                    }
                />
```
