### ISSUE TITLE
Insufficient text contrast on Heatmap labels

### ISSUE THREAD

**Issue by drwpow** [plouc/nivo#2291]
**Describe/explain the bug**

When using labels with the Heatmap, they become hard to read over some cell colors, and disappear completely on others. This results in half the labels being difficult-to-impossible to read. This is due to there being no function to invert text color past a certain threshold.

<img width="912" alt="CleanShot 2023-04-19 at 11 56 01@2x" src="https://user-images.githubusercontent.com/1369770/233160542-f0d765f5-9014-487b-83e1-29fceb58fdee.png">

The solution can’t simply be “use another color scheme,” because most heatmaps require the use of both dark and light colors. In most implementations, a single label color isn’t sufficient.

**To Reproduce**

1. Select a color scheme like **Inferno** in the [example page](https://nivo.rocks/heatmap/)

**Expected behavior**

Nivo should invert the label color when the cell color comes too dark. Or at least provide an escape hatch for the implementer to handle this (even though including an implementation like [lightOrDark](https://github.com/drwpow/better-color-tools#light-or-dark) is trivial). An example of this being done in another heatmap library is [seaborn](https://seaborn.pydata.org/generated/seaborn.heatmap.html) (Python):

<img width="785" alt="CleanShot 2023-04-19 at 11 59 18@2x" src="https://user-images.githubusercontent.com/1369770/233161043-f593a2f1-aabe-4f29-ab22-e73382c7c8c8.png">

**Comment by drwpow** [comment]
Workaround: I was able to override the defaults by using the custom `cellComponent` renderer. But it would be nice without having to re-implement rendering just for a single color change:

```tsx
import { ResponsiveHeatMap } from '@nivo/heatmap';
import better from 'better-color-tools';

const TEXT_COLOR_DARK = '#222';
const TEXT_COLOR_LIGHT = '#fff';

export default function MyHeatMap() {
  return (
    <ResponsiveHeatMap
      data={data}
      cellComponent={({ borderWidth, cell, ...cellProps }) => {
        if (cell.value === null) return null;
        const textColor = better.lightOrDark(cell.color) === 'light' ? TEXT_COLOR_DARK : TEXT_COLOR_LIGHT;
        return (
          <g
            fillOpacity={cell.opacity}
            onClick={cellProps.onClick?.(cell)} 
            onMouseEnter={cellProps.onMouseEnter?.(cell)}
            onMouseLeave={cellProps.onMouseLeave?.(cell)}
            onMouseMove={cellProps.onMouseMove?.(cell)}
            transform={`translate(${cell.x} ${cell.y})`}
          >
            <rect
              fill={cell.color}
              height={cell.height}
              stroke={BORDER_COLOR}
              strokeWidth={borderWidth}
              transform={`translate(${-0.5 * cell.width} ${-0.5 * cell.height})`}
              width={cell.width}
            />
            <text dominantBaseline="central" fill={textColor} textAnchor="middle">
              {cell.value}
            </text>
          </g>
        );
      }}
    />
  );
}
```

**Comment by plouc** [comment]
@drwpow, I think you could try to use `labelTextColor`, it might allow you to change the color without having to redefine the whole component.

**Comment by drwpow** [comment]
>I think you could try to use `labelTextColor`, it might allow you to change the color without having to redefine the whole component.

Do you have an example of what you had in mind (even if pseudocode)?

I wasn’t able to think of a way to use that. Though `labelTextColor` does take a function, it only provides a single numeric value and no other information (it doesn’t pass back `cell` like other functions do, which would have the cell color, which is what I need). Wouldn’t I would have to somehow hoist up the logic that determines what color something is just from the raw value alone? Or maybe I’m missing something.

**Comment by plouc** [comment]
@drwpow, please see https://codesandbox.io/s/nivo-heatmap-automatic-label-contrast-cvs90s, I'm closing this issue as I think it's easily achievable using this approach.

**Comment by drwpow** [comment]
That works for me! Thank you!

**Comment by whaberek** [comment]
> @drwpow, please see https://codesandbox.io/s/nivo-heatmap-automatic-label-contrast-cvs90s, I'm closing this issue as I think it's easily achievable using this approach.

Looks like this link expired, do you remember how to achieve it?
