### ISSUE TITLE
Custom legend format

### ISSUE THREAD

**Issue by AlexandreVerhoye** [plouc/nivo#2294]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a custom renderer (or 'formatter') on legends like the 'format' one on axisBottom ? It seems currently impossible to truncate legends that are too lengthy on a ResponsivePie chart. 

**Describe the solution you'd like**
Add a format settings on legends.

**Describe alternatives you've considered**
I tried to truncate the text using data but i've lost automatic coloring using this method. I've also saw 'formatLegend' on StackOverflow but it doesn't seems existing, as it s not working and not on type definition.

**Additional context**
I'm trying to add tooltip using <tspan> and <title> on legends to prevent lenghty legend to overflow on others legends : 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/26713888/233333743-722a3336-b5c3-45e4-877e-25c54b6dad31.png">

Here is my chart settings : 
```
const defaultSettings = {
    innerRadius: 0.6,
    padAngle: 1,
    cornerRadius: 8,
    colors: [
      '#A6CAFC',
      '#FBE94E',
      '#ED782F',
      '#5EBB84',
      '#E1C2A4',
      '#BBDE93',
      '#559E3F',
      '#EE9E9C',
      '#F4C27B',
      '#EC8632',
      '#C6B3D4',
      '#AECDE1',
    ],
    radialLabelsLinkStrokeWidth: 0,
    radialLabelsLinkDiagonalLength: 5,
    radialLabelsLinkHorizontalLength: 5,
    radialLabelsTextXOffset: 3,
    enableSlicesLabels: false,
    radialLabelsSkipAngle: 10,
    enableArcLinkLabels: false,
    legends: [
      {
        anchor: 'center',
        direction: 'row',
        justify: false,
        translateX: 0,
        translateY: 140,
        itemsSpacing: 5,
        itemWidth: 80,
        itemHeight: 18,
        itemTextColor: isThing ? 'transparent' : '#999',
        symbolSize: isThing ? 0 : 10,
        symbolShape: 'circle',
        toggleSerie: !isThing,
        effects: [
          {
            on: 'hover',
            style: {
              itemTextColor: isThing ? 0 : '#000',
            },
          },
        ],
      },
    ],
  };
  ```

Thank you !

**Comment by joaopedromatias** [comment]
I was able to solve this by building a custom component to display the legends.

**Comment by hpecarlos** [comment]
> 

Can you please provide details/code of your solution ??  Others can use it.

**Comment by hpecarlos** [comment]
> I was able to solve this by building a custom component to display the legends.

Can you provide code/details of your solution ??  others can use it. :-)

**Comment by joaopedromatias** [comment]
@hpecarlos it's in this issue comments https://github.com/plouc/nivo/issues/2268
