### ISSUE TITLE
Line chart - How to show the hover point only?

### ISSUE THREAD

**Issue by Maverick17user** [plouc/nivo#2296]
Like it showed on the image bellow:

( I've tried to run example from #993, but for some reason it doesn't work 🧐 )

![image](https://user-images.githubusercontent.com/30416868/233807310-93b31020-e042-47d9-afb1-e8b4295e4512.png)

**Comment by van-for-days** [comment]
bump

**Comment by paolapog** [comment]
Hello everyone! I don't know if this is still an issue or someone else find a solution but I've created a custom layer for this (`enableSlices`needs to be enabled).
You can find above here 👆🏼

**Comment by DanilKasianenko** [comment]
Hello, I find solution use `React.useRef()`

```jsx
import {
  CustomLayerProps,
  Point,
  ResponsiveLine,
  SliceTooltip,
} from "@nivo/line";
// ........

export const LineChart = ({ data }: LineChartProps) => {
  const currentPoint = useRef<Point[] | null>();

  const CustomTooltip: SliceTooltip = ({ slice }) => {
    currentPoint.current = slice.points;
    return (
     // .... 
    );
  };

  const CustomPoints = () => {
    const { isVisible } = useTooltipState();

    if (currentPoint.current && isVisible) {
      return (
       // ......
      );
    }
  };

  return (
    <ResponsiveLine
      data={data}
     // .....

 />
  );
};
```
