### ISSUE TITLE
Bar Chart - renderToStaticMarkup not rendering properly

### ISSUE THREAD

**Issue by mrkirchner** [plouc/nivo#2297]
**Describe/explain the bug**
When rendering a barchart with renderToStaticMarkup the bars will not render.  At one point there was this bug but was closed https://github.com/plouc/nivo/issues/1778.

Even a pr was added but never merged due to package changes.
https://github.com/plouc/nivo/pull/1712

**To Reproduce**
https://codesandbox.io/s/bar-staticmarkup-x6vzv?file=/src/App.js

1. Render a Bar chart using renderToStaticMarkup to see no bars.

**Expected behavior**
Bars render properly

**Screenshots**
<img width="362" alt="Screenshot 2023-04-23 at 3 13 13 PM" src="https://user-images.githubusercontent.com/13805753/233866619-76f2266f-bc2e-4923-938a-f5802c5b05ff.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome/Firefox/Safari
 - Version 80

**Comment by mrkirchner** [comment]
@plouc does Nivo have anyone fixing issues?  This issue also seems related https://github.com/plouc/nivo/issues/2368

**Comment by mrkirchner** [comment]
Bump?

**Comment by mrkirchner** [comment]
@plouc or @shoito any word on this ? It prevents using bar on server side.  Original pr was one liner but package was moved.

**Comment by OleksandrRakovets** [comment]
Sorry it took so long 😮‍💨 

Been using a custom build with this change in production for over a year w/o any issues.

Hope it'll get merged this time 🤞

**Comment by plouc** [comment]
This issue should have been solved by https://github.com/plouc/nivo/pull/2464.

@OleksandrRakovets, thank you!
