### ISSUE TITLE
nivo.rocks website displays blank screen, requires manual cache clearing to fix.

### ISSUE THREAD

**Issue by davetransom** [plouc/nivo#2298]
**Website Bug**
First visit to the https://nivo.rocks/ website works fine (it's wonderfully designed btw), but then after a time, the site only displays a blank/white page.

A simple refresh of the browser tab _doesn't_ fix it.

It appears that when deploying a new version of the site, the old build is deleted, causing references to those _previously released files_ to return HTTP 404s which prevents the app loading and continuing gracefully.

**Workarounds**
1. "Empty cache and hard reload" from your browser, or
2. Unregister the Service Worker from the devtools Application tab, then reload the tab.

**To Reproduce**
Leave any https://nivo.rocks/ tab open in your browser, and then when the browser resumes that tab, it's often presented with a blank screen.

**Screenshots**
- **Blank Screen Snippet**
   ![image](https://user-images.githubusercontent.com/308188/233877509-5e23696f-8f90-45f0-8573-0106b04ba25e.png)
- **Network Requests Tab**
   ![image](https://user-images.githubusercontent.com/308188/233877532-e7a5a1e3-7d05-4814-88c6-898ab5628c71.png)
- **Console Errors**
   ![image](https://user-images.githubusercontent.com/308188/233877608-04e3e054-1ffd-43ca-8318-fa074db15ccb.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 112.0.5615.49 (64-bit)

**Comment by plouc** [comment]
This should now be fixed.
