### ISSUE TITLE
Help with importing NIVO library 

### ISSUE THREAD

**Issue by bluefig99** [plouc/nivo#230]
Hello , 

I am having issues importing the NIVO library in to my project. I am pretty sure there is an issue on my side but not able to figure that out. Can you please help? I have followed the following steps.

1. Install the nivo library using the following command
npm install --save @nivo/line

2. Imported the package as mentioned below. 
import React from "react"
import {ResponsiveLine} from "@nivo/line"
import "./Chart.css"

class Chart extends React.Component{
    constructor(props , context){
        super(props ,context);
        this.state = {

        }
    }

    render(){
        return(
            <div className="lineChart">
                <ResponsiveLine className="lineChart"
                    data={{
                                "id": "whisky",
                                "color": "hsl(1, 70%, 50%)",
                                "data": [
                                {
                                    "color": "hsl(286, 70%, 50%)",
                                    "x": "RE",
                                    "y": 16
                                },
                                {
                                    "color": "hsl(341, 70%, 50%)",
                                    "x": "TH",
                                    "y": 8
                                },
                                {
                                    "color": "hsl(228, 70%, 50%)",
                                    "x": "JP",
                                    "y": 31
                                },
                                {
                                    "color": "hsl(5, 70%, 50%)",
                                    "x": "SV",
                                    "y": 43
                                },
                                {
                                    "color": "hsl(66, 70%, 50%)",
                                    "x": "DK",
                                    "y": 29
                                },
                                {
                                    "color": "hsl(112, 70%, 50%)",
                                    "x": "GY",
                                    "y": 39
                                },
                                {
                                    "color": "hsl(34, 70%, 50%)",
                                    "x": "TN",
                                    "y": 28
                                },
                                {
                                    "color": "hsl(8, 70%, 50%)",
                                    "x": "PW",
                                    "y": 45
                                },
                                {
                                    "color": "hsl(180, 70%, 50%)",
                                    "x": "BV",
                                    "y": 59
                                }
                                ]
                            }}
                    margin={{
                        "top": 50,
                        "right": 110,
                        "bottom": 50,
                        "left": 60
                    }}
                    minY="auto"
                    stacked={true}
                    axisBottom={{
                        "orient": "bottom",
                        "tickSize": 5,
                        "tickPadding": 5,
                        "tickRotation": 0,
                        "legend": "country code",
                        "legendOffset": 36,
                        "legendPosition": "center"
                    }}
                    axisLeft={{
                        "orient": "left",
                        "tickSize": 5,
                        "tickPadding": 5,
                        "tickRotation": 0,
                        "legend": "count",
                        "legendOffset": -40,
                        "legendPosition": "center"
                    }}
                    dotSize={10}
                    dotColor="inherit:darker(0.3)"
                    dotBorderWidth={2}
                    dotBorderColor="#ffffff"
                    enableDotLabel={true}
                    dotLabel="y"
                    dotLabelYOffset={-12}
                    animate={true}
                    motionStiffness={90}
                    motionDamping={15}
                    legends={[
                        {
                            "anchor": "bottom-right",
                            "direction": "column",
                            "translateX": 100,
                            "itemWidth": 80,
                            "itemHeight": 20,
                            "symbolSize": 12,
                            "symbolShape": "circle"
                        }
                    ]}
                />
            </div>
        );
    }
}

export default Chart

**Comment by tmewes** [comment]
The value "from"-value for the import of ResponsiveLine is empty in your example.

Try this instead:
`import { ResponsiveLine } from "@nivo/line"`

Did you add the Nivo package in the package.json in the dependencies?
`"@nivo/line": "^0.42.1"`

After adding the package, run `npm install --save`.

If you still can not see the ResponsiveLine, give the CSS class "lineChart" a pixel-based height.

**Comment by bluefig99** [comment]
Thanks Tino for the response. I am not able to see the chart.Please find my code here:Can you please help reviewing it?

**************** .  Begining of NivoChart.jsx  *********************

```
import React from "react"
`import {ResponsiveLine} from "@nivo/line"`
import "./NivoChart.css"

const data = {
        "id": "whisky",
        "color": "hsl(193, 70%, 50%)",
        "data": [
          {
            "color": "hsl(246, 70%, 50%)",
            "x": "IR",
            "y": 32
          },
          {
            "color": "hsl(277, 70%, 50%)",
            "x": "GE",
            "y": 27
          },
          {
            "color": "hsl(340, 70%, 50%)",
            "x": "CL",
            "y": 33
          },
          {
            "color": "hsl(345, 70%, 50%)",
            "x": "GW",
            "y": 0
          },
          {
            "color": "hsl(201, 70%, 50%)",
            "x": "KY",
            "y": 12
          },
          {
            "color": "hsl(19, 70%, 50%)",
            "x": "CN",
            "y": 23
          },
          {
            "color": "hsl(64, 70%, 50%)",
            "x": "FJ",
            "y": 6
          },
          {
            "color": "hsl(348, 70%, 50%)",
            "x": "NO",
            "y": 30
          },
          {
            "color": "hsl(341, 70%, 50%)",
            "x": "TN",
            "y": 51
          }
        ]
  };

class NivoChart extends React.Component{
    constructor(props , context){
        super(props ,context);
        this.state = {

        }
    }

    render(){
        return(
            <div className="lineChart">
                <div>
                    <h2>Line Example (custom size)</h2>
                        <ResponsiveLine
                        data={data}
                        margin={{
                            "top": 50,
                            "right": 110,
                            "bottom": 50,
                            "left": 60
                        }}
                        minY="auto"
                        stacked={true}
                        axisBottom={{
                            "orient": "bottom",
                            "tickSize": 5,
                            "tickPadding": 5,
                            "tickRotation": 0,
                            "legend": "country code",
                            "legendOffset": 36,
                            "legendPosition": "center"
                        }}
                        axisLeft={{
                            "orient": "left",
                            "tickSize": 5,
                            "tickPadding": 5,
                            "tickRotation": 0,
                            "legend": "count",
                            "legendOffset": -40,
                            "legendPosition": "center"
                        }}
                        dotSize={10}
                        dotColor="inherit:darker(0.3)"
                        dotBorderWidth={2}
                        dotBorderColor="#ffffff"
                        enableDotLabel={true}
                        dotLabel="y"
                        dotLabelYOffset={-12}
                        animate={true}
                        motionStiffness={90}
                        motionDamping={15}
                        legends={[
                            {
                                "anchor": "bottom-right",
                                "direction": "column",
                                "translateX": 100,
                                "itemWidth": 80,
                                "itemHeight": 20,
                                "symbolSize": 12,
                                "symbolShape": "circle"
                            }
                        ]}
                    />
                </div>      
            </div>
        );
    }
}

export default NivoChart
```

/*****************************NivoChart.css*****************/

```
.lineChart {
    height: 500px;
    width:500px;
    background-color: #f7fcfa;
}
```


/*************************** Package.json*********************/

```
{
  "name": "charts",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@nivo/core": "^0.42.1",
    "@nivo/legends": "^0.42.0",
    "@nivo/line": "^0.42.1",
    "d3-format": "^1.3.0",
    "d3-scale": "^2.1.0",
    "d3-shape": "^1.2.0",
    "lodash": "^4.17.10",
    "nivo": "^0.31.0",
    "react": "^16.4.1",
    "react-chartjs-2": "^2.7.2",
    "react-dom": "^16.4.1",
    "react-motion": "^0.5.2",
    "react-scripts": "1.1.4",
    "recompose": "^0.27.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

/******************** App.jsx****************/

```
import './App.css';
import NivoChart from "./NivoChart";

class App extends Component {
  render() {
    return (
      <div className="lineChart">
        <NivoChart />
      </div>
    );
  }
}

export default App;
```

**Comment by riteshnus** [comment]
Check to these issues, might help you:
#178
#122

**Comment by bluefig99** [comment]
I think the problem is not with the height and width of the container. The problem seems to be related to importing the library in to my project. 

`import {ResponsiveLine} from "@nivo/line"` 

Above line seems to be a problem as mentioned below:

```
[ts]
Could not find a declaration file for module '@nivo/line'. '/Users/bluefig/Code/sandbox/charts/node_modules/@nivo/line/index.js' implicitly has an 'any' type.
  Try `npm install @types/nivo__line` if it exists or add a new declaration (.d.ts) file containing `declare module 'nivo__line';`
```

```
[ts]
Could not find a declaration file for module '@nivo/line'. '/Users/trueclap/Code/sandbox/charts/node_modules/@nivo/line/index.js' implicitly has an 'any' type.
  Try `npm install @types/nivo__line` if it exists or add a new declaration (.d.ts) file containing `declare module 'nivo__line';`
module "/Users/bluefig/Code/sandbox/charts/node_modules/@nivo/line/index"
```

Have you faced this kind of issue?

**Comment by plouc** [comment]
@bluefig99, you're using typescript and there's no available definitions for now

**Comment by plouc** [comment]
There's an opened issue https://github.com/plouc/nivo/issues/197

**Comment by bluefig99** [comment]
Thanks @plouc for the confirmation.  Do we have a workaround to use nivo with ReactJs library? Otherwise, when will be the support available for reactjs?

**Comment by plouc** [comment]
@bluefig99 nivo works with react :) but TypeScript support is just partially implemented.
I close this issue in favor of #197.
