### ISSUE TITLE
Website demo line chart y values are not inline with the y axis

### ISSUE THREAD

**Issue by doron-cohen** [plouc/nivo#2300]
**Describe/explain the bug**
In the nivo.rocks website in the [line chart demo](https://nivo.rocks/line/) the values are not inline with the y axis. Also, I find some big y values which are shown below some small y values. It's as if the y values are only taken into consideration in the label and not in the line graph itself.

**To Reproduce**
See https://nivo.rocks/line/

**Expected behavior**

**Screenshots**
<img width="1346" alt="Screenshot 2023-04-24 at 18 53 59" src="https://user-images.githubusercontent.com/4966182/234064292-01f11676-cede-4665-ac5e-8cb9797d908f.png">

**Comment by plouc** [comment]
This is expected, that's because the values are stacked, you can disable this behavior by changing `yScale.stacked` to `false`.
<img width="252" alt="Screenshot 2023-04-25 at 21 57 07" src="https://user-images.githubusercontent.com/501642/234283614-277c1686-a89e-4756-a3c0-eb1132ca989b.png">
