### ISSUE TITLE
How does it possible to implement such gradient?

### ISSUE THREAD

**Issue by Maverick17user** [plouc/nivo#2301]
I want area to look kind of fade out gradient, as bellow
But I didn't find workable solution 
![image](https://user-images.githubusercontent.com/30416868/234383033-7f75c307-b687-4c63-ad62-83e909382c97.png)

**Comment by plouc** [comment]
You can use [`defs` and `fill`](https://nivo.rocks/guides/gradients/), please see [this example](https://codesandbox.io/s/nivo-line-gradient-8wi1de?file=/src/index.js).
