### ISSUE TITLE
How can I draw such chart?

### ISSUE THREAD

**Issue by vireshshah** [plouc/nivo#2302]
Hi, How can I draw chart like below? Basically different background colors based on y axis ranges. Thanks in advance.

![chart-type](https://user-images.githubusercontent.com/1148796/234389293-09033677-ee4b-4683-85aa-40745a8fe7b2.png)

**Comment by plouc** [comment]
You can add a custom layer to achieve this, please see: https://codesandbox.io/s/nivo-line-custom-areas-btyzmz?file=/src/index.js.

**Comment by vireshshah** [comment]
Great. Thanks a lot @plouc!
