### ISSUE TITLE
Nextjs 13 nivo/core warning

### ISSUE THREAD

**Issue by DStavast** [plouc/nivo#2303]
**Describe/explain the bug**
Hydration Error in Nextjs 13 experimental app directory when using the client-side component. 
Below you will find a code sandbox as well as the 2 different error messages from Chrome and Firefox

**CodeSandbox**
[ codesandbox link ](https://codesandbox.io/p/sandbox/nivo-0hmyx8?file=%2Fapp%2Fcalendar-chart.tsx&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A29%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A29%7D%5D)

**To Reproduce**
1. Install Nextjs 13.2.4
2. Install nivo/core and nivo/calendar
`npm i @nivo/core@nivo/calendar,`
3. Create the client component: 

```typescript
"use client";
import React, { FC } from "react";
import { CalendarTooltipProps, ResponsiveCalendar } from "@nivo/calendar";

type CalendarChartPropsType = {
  data: {
    day: string; // format must be YYYY-MM-DD
    value: number;
  }[];
};

const CalendarChart: FC<CalendarChartPropsType> = ({ data }) => {
  if (data.length === 0) return <div>No data</div>;

  return (
    <ResponsiveCalendar
      data={data}
      theme={{ textColor: "rgb(200,200,200)" }}
      from="2015-01-01"
      to="2015-12-12"
      emptyColor="#ffff"
      colors={["#DCFCE7", "#A9EBCE", "#76DBB4", "#43CA9B", "#10B981"]}
      minValue="auto"
      margin={{ top: 40, right: 40, bottom: 40, left: 40 }}
      yearSpacing={45}
      yearLegendOffset={15}
      monthBorderWidth={2}
      monthBorderColor="rgb(220,220,220)"
      monthLegendPosition="after"
      monthLegendOffset={14}
      dayBorderWidth={2}
      dayBorderColor={"rgb(240,240,240)"}
      legends={[
        {
          anchor: "bottom-right",
          direction: "row",
          translateY: 36,
          itemCount: 4,
          itemWidth: 42,
          itemHeight: 36,
          itemsSpacing: 14,
          itemDirection: "right-to-left",
        },
      ]}
    />
  );
};

export default CalendarChart;


``` 
4. Import and add the component to our page:
```typescript
import CalendarChart from "./calendar-chart";
import { calendarData } from "./test-data";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main style={{ width: "100%", height: "500px" }}>
      <CalendarChart data={calendarData} />
    </main>
  );
}

``` 
5. See error

**Firefox Error Message**
![image](https://user-images.githubusercontent.com/112618528/234452973-488ab22b-66d7-46be-82ac-02a1a789ecaf.png)

**Chrome Error Message**
![image](https://user-images.githubusercontent.com/112618528/234462722-b529a979-dc71-49ea-ac60-4433578b2775.png)
![image](https://user-images.githubusercontent.com/112618528/234463053-7e14ed5e-b26d-4d0c-901f-f465f0c0b72f.png)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, firefox]

**Comment by plouc** [comment]
Just to clarify, this is a warning 😅, I won't be able to get rid of default props easily as I first need to [get rid of recompose](https://github.com/plouc/nivo/issues/884).

**Comment by plouc** [comment]
Closing this issue as I think we can wait before supporting the next major of React as we still have things to address for React 18.
