### ISSUE TITLE
Y-Axis as time causes values to be reverted 

### ISSUE THREAD

**Issue by nhtoby311** [plouc/nivo#2306]
## Issue
It seems like having time axis as Yaxis cause the display data to be reversed. I'm using a mock data like this to measure the elapse time data with its corresponding data. 
```ts
<ResponsiveLine
                enableSlices="x"
                curve="monotoneX"
                lineWidth={3}
                enableGridX={false}
                enableGridY={false}
                enablePoints={false}
                enableCrosshair={false}
                colors={{ scheme: 'blues' }}
                data={[
                    {
                        id: 'fake corp. A',
                        data: [
                            { x: 'Week 1', y: '3:00' },
                            { x: 'Week 2', y: '2:00' },
                            { x: 'Week 3', y: '14:20' },
                            { x: 'Week 4', y: '12:00' },
                            { x: 'Week 5', y: '22:00' },
                            { x: 'Week 6', y: '32:00' },
                            { x: 'Week 7', y: '5:00' },
                        ],
                    },
                ]}
                yScale={{
                    type: 'time',
                    format: '%M:%S',
                    precision: 'second',
                }}
                axisLeft={{
                    format: '%M:%S',
                }}
            />
```
![image](https://user-images.githubusercontent.com/52330522/234698436-e603c6e6-0329-4210-9fb9-ecb2694adb25.png)

Is there a way to fix this? Or a work around such as revert the Yaxis values, or having y as number represent seconds, then have a method to format it to "MM:SS" in order to display.

**Comment by plouc** [comment]
Unfortunately, a time scale cannot be reversed, using numbers representing seconds might work, but converting the value back would be tedious.

**Comment by nvminhhieu** [comment]
So is it a bug for type time on yAxis? 

Can I use yFormat or other attribute to display as minute value? Or it can only be done inside the code of the package?

**Comment by plouc** [comment]
> So is it a bug for type time on yAxis?

I would need to spend more time to properly investigate what's happening.

> Can I use yFormat or other attribute to display as minute value? Or it can only be done inside the code of the package?

Yes, but you still need to specify it separately for the axes config.

**Comment by nvminhhieu** [comment]
> Yes, but you still need to specify it separately for the axes config.

Is there an example on how can I do this?

**Comment by nvminhhieu** [comment]
I tried this workaround and it works for me! The data value is seconds, and I pass through a function to convert it to `minute:second` format. 

```ts
const formatTime = (time: number) => {
    return [
        Math.floor((time % 3600) / 60), // minutes
        ('00' + Math.floor(time % 60)).slice(-2), // seconds
    ].join(':')
}

<ResponsiveLine
    margin={{ top: 20, right: 40, bottom: 60, left: 60 }}
    animate={true}
    enableSlices="x"
    curve="monotoneX"
    lineWidth={3}
    theme={theme as any}
    enableGridX={false}
    enableGridY={false}
    enablePoints={false}
    enableCrosshair={false}
    colors={{ scheme: 'blues' }}
    data={[
        {
            id: 'fake corp. A',
            data: [
                { x: 'Week 1', y: 1 },
                { x: 'Week 2', y: 2 },
                { x: 'Week 3', y: 4 },
                { x: 'Week 4', y: 5 },
                { x: 'Week 5', y: 7 },
                { x: 'Week 6', y: 3 },
                { x: 'Week 7', y: 8 },
            ],
        },
    ]}
    axisLeft={{
        format: (value) => `${formatTime(Number(value))}`,
    }}
/>
```

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/52330522/234858710-dfc0d840-d48f-441d-98f5-c7e3839523c9.png">
