### ISSUE TITLE
@nivo/swarmplot breaking in 0.81.0

### ISSUE THREAD

**Issue by daniloab** [plouc/nivo#2309]
I have updated the Nivo to version 0.81.0 and start to break the code previously working

## code example
```tsx
import type { SwarmPlotProps } from '@nivo/swarmplot';
import { ResponsiveSwarmPlot } from '@nivo/swarmplot';

export type NivoBarProps = {
  data: Record<string, unknown>[];
  keys: string[];
  indexBy: string;
} & SwarmPlotProps;

const SwarmplotChart = (props: NivoBarProps) => {
  return (
    <ResponsiveSwarmPlot
      borderWidth={1}
      borderColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
      margin={{
        top: 40,
        right: 40,
        bottom: 40,
        left: 40,
      }}
      groupBy='group'
      identity='id'
      size={10}
      {...props}
    />
  );
};

export default SwarmplotChart;
```

<img width="1472" alt="Screen Shot 2023-04-27 at 11 05 06" src="https://user-images.githubusercontent.com/19939822/234887059-34f57559-404c-4846-9bab-7f7f5695b6c5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey
 - Browser chrome 112
 - Version 112

**Comment by plouc** [comment]
Thank you for taking the time to report this issue. I'm closing this in favor of a more generic issue: https://github.com/plouc/nivo/issues/2310.
