### ISSUE TITLE
Support Microsoft IE11

### ISSUE THREAD

**Issue by benzitohhh** [plouc/nivo#232]
Hi there,

Nivo is amazing, nice one for all the hard work.

But unfortunately it does not currently work with IE11.

Specifically, `curve.js` has a call to str.endsWith, which IE11 does not support.

Please could this fix be added:
https://github.com/plouc/nivo/pull/231

Or perhaps it could be fixed in your build?

Thanks,
Ben

**Comment by benzitohhh** [comment]
#231

**Comment by reanimatter** [comment]
i'd recommend using external polyfills rather than adding them to the library

**Comment by plouc** [comment]
@benzitohhh, I agree with @reanimatter, I've answered on your MR https://github.com/plouc/nivo/pull/231.

**Comment by benzitohhh** [comment]
@plouc @reanimatter ok cool all good - thanks for looking at this
