### ISSUE TITLE
Border radius for each day of calendar graph

### ISSUE THREAD

**Issue by aaryan610** [plouc/nivo#2323]
**Is your feature request related to a problem? Please describe.**
There is no way to set the border radius for each day in the calendar way.

**Describe the solution you'd like**
A prop in the calendar graph component to set the border radius for each day.

**Comment by Dosbodoke** [comment]
No updates for this right? I would like to work on this, I think is a supper important feature

We just need a prop where we can define the `rx` number that will then be passed to the `CalendarDay.tsx` `<rect />` element

**Comment by Dosbodoke** [comment]
As  a temporary solution I defined the `rx` via CSS

 ```
 #calendar-container g rect[x][y][width][height][style] {
    rx: 4;
}
```

The `rect[x][y][width][height][style]` CSS selector aim's to select only the CalendarDay

**Comment by plouc** [comment]
> No updates for this right? I would like to work on this, I think is a supper important feature
> 
> We just need a prop where we can define the `rx` number that will then be passed to the `CalendarDay.tsx` `<rect />` element

I won't have the time to look into this, and there are more pressing issues for now. 
But it's a bit more complicated than just forwarding a property, due to the canvas implementation.
