### ISSUE TITLE
Custom label for responsive pie chart and other charts.

### ISSUE THREAD

**Issue by ma7899** [plouc/nivo#2327]
Add custom elements on labels in pieChart.
I have a dashboard page and the data I want to show the company logo next to the company name inside a box with a border.

If there would be an option for a custom label or inside the data array, in data Json we could pass a JSX element to render that instead of just a string would be great.

I am currently using ResponsivePieChart and I think this feature can be added to the rest of the charts as well.

thanks.

**Comment by plouc** [comment]
Don't forget that nivo also support canvas implementation, I don't think presentational elements should be part of the data, and this could cause a bunch of issues with memoization, typings... So sorry, but that's not something I'm willing to introduce.
