### ISSUE TITLE
Customize Radar gridLabels

### ISSUE THREAD

**Issue by barriber** [plouc/nivo#233]
Currently radar grid generates grid labels according to the grid keys string,
Is there a way to generate more complex labels? Like in the example below

![image](https://user-images.githubusercontent.com/12542724/41968232-74f45ecc-7a0c-11e8-98c6-9bb825b1fe3a.png)

**Comment by plouc** [comment]
@barriber, not for now, could be feasible, but content will have to be svg though.

**Comment by plouc** [comment]
except for interactions (like tooltip) I avoid adding html to be compatible with the http rendering API.

**Comment by plouc** [comment]
Implemented via https://github.com/plouc/nivo/commit/03b3640b6aee3158e88d66868be099f16ba6e8f3

**Comment by plouc** [comment]
Please have a look at the [documentation](http://nivo.rocks/radar) and at the [corresponding example](http://nivo.rocks/storybook/?selectedKind=Radar&selectedStory=custom%20label%20component&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by akvashi24** [comment]
Hey @plouc thanks for this.  I'm having trouble typing the props that are given to this `CustomGridLabelFunction`.  What should the types of the props it receives be?  I'm simply trying to implement onClick on the labels, so I expect this to work.


    const gridLabelGenerator: GridLabelCustomFunction = (props: any[]): JSX.Element => {
        return (
            <svg>
                <text onClick={handleClick}>
                    {props.id}
                </text>
            </svg>
        )
    }

**Comment by kamranayub** [comment]
Just FYI, the docs say your label will be within a `<g>` element with translation set to the proper XY but according to Storybook story and with 0.88.0, you _do_ need to provide the `<g>` element with translation:

```tsx
import { ResponsiveRadar, GridLabelComponent } from '@nivo/radar';

const CustomLabel: GridLabelComponent = ({ id, anchor, x, y }) => {
    return (
        <g transform={`translate(${x}, ${y})`}>
                <text
                    dominant-baseline="central"
                    text-anchor={anchor}
                    style={{
                        fontFamily: 'sans-serif',
                        fontSize: 11,
                        fill: 'rgb(51, 51, 51)',
                        outlineWidth: 0,
                        outlineColor: 'transparent'
                    }}>
                    {id}
                </text>
        </g>
    )
}
```
