### ISSUE TITLE
You may need additional loader error showing in terminal when i did yarn add @nivo/core @nivo/bar in my react app

### ISSUE THREAD

**Issue by Znoy108x** [plouc/nivo#2331]
**Error Message**

./node_modules/@react-spring/web/dist/esm/index.js 113:11
Module parse failed: Unexpected token (113:11)

File was processed with these loaders:

 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js

You may need an additional loader to handle the result of these loaders.
>     this.transforms = I;
>     }
>     _value = null;
>     get() {
>     return this._value || (this._value = this._get());

Please help me resolve this issue !!

**Comment by plouc** [comment]
Hello @Znoy108x.

I don't know what your setup is, please use the provided issue template to properly describe your problem.

Regarding your issue, it's not directly related to nivo, please see https://github.com/pmndrs/react-spring/issues/2104.

**Comment by alexcmetro** [comment]
@Znoy108x Did you find out how to solve this issue?

**Comment by Znoy108x** [comment]
@alexcmetro install 0.74.1 version

**Comment by MuhammadAnas14** [comment]
@Znoy108x I am facing a similar issue Can you tell me which package version are you talking about?

**Comment by ChedvaKatze** [comment]
I am facing same issue too, version 0.83.0.
Does anyone solve the issue?

**Comment by oandrevictor** [comment]
facing the same issue

**Comment by omar-hasan1** [comment]
> @alexcmetro install 0.74.1 version

This worked for me. Thank you!
