### ISSUE TITLE
Attempted import error: 'useAnimatedPath' is not exported from '@nivo/core' (imported as 's')

### ISSUE THREAD

**Issue by neerajrathore** [plouc/nivo#2332]
dependencies 
<img width="246" alt="image" src="https://github.com/plouc/nivo/assets/11667917/1e446b9b-062b-45e4-b61e-2d1e3790c8b4">

Trying to compile react project but failing constantly 

Can anyone provide direction on how to solve this

Thank you

**Comment by plouc** [comment]
You should use the same version for all `@nivo` packages, here `@nivo/sankey` is much more recent, and it depends on `@nivo/core`, which didn't contain this function at that time.

**Comment by plouc** [comment]
This also means that you might need to update the other charts, as the API changed between versions.

**Comment by neerajrathore** [comment]
@plouc thank you for quick response. I will attempt the solution given.
