### ISSUE TITLE
Info about contributing missing

### ISSUE THREAD

**Issue by thalseth** [plouc/nivo#234]
Hi @plouc ! I love this package and would like to contribute if i get the chance. I am not familiar with Rollup or Lerna. 

Is there missing a script to execute in the setup section?
https://github.com/plouc/nivo/blob/master/CONTRIBUTING.md#setup

I tried running `npm i rollup --global`and then  `make init` and that seems to go fine.
But now i want to build a package and watch and cant seem to get it working.
Tried `make package-build-<package>` but i cant add --watch to this script 😢 
Thank you for any help! 
Cheers 🍻

**Comment by plouc** [comment]
Hi @thalseth,
You can use `make package-dev-<package>`.

**Comment by thalseth** [comment]
Awesome @plouc. Thank you 💯

**Comment by plouc** [comment]
@thalseth, is it OK? can I close this issue?

**Comment by thalseth** [comment]
All good @plouc . I just thought you might want to update the contribution file 👍
