### ISSUE TITLE
Select scatters by dragging around them !

### ISSUE THREAD

**Issue by Znoy108x** [plouc/nivo#2341]
![image](https://github.com/plouc/nivo/assets/75539409/080f6d96-5bfa-4c3d-8fb3-1dbfe75bd392)
This is the scatter plot , and i want to select all the points by drawing a rectangle !!

Can anyone tell me how can i do that ??

**Comment by plouc** [comment]
@Znoy108x, this feature is not supported. Maybe it'll when I implement brushing.

**Comment by plouc** [comment]
Also please stop adding double exclamation/question marks everywhere (as I asked in another issue you opened), it really doesn't bring anything.
