### ISSUE TITLE
How to make the naming of the bar chart take 50% of the place and bar chart take the other 50%. 

### ISSUE THREAD

**Issue by RinorJahaj** [plouc/nivo#2343]
The default behavior for Bar chart is name is like 5% of the place then it's the bar chart that takes place, Is it possible to achieve the design as seen in the image:

<img width="354" alt="image" src="https://github.com/plouc/nivo/assets/52374991/e8cdafe0-3d01-4a5a-bb17-584838ddbc1d">

**Comment by plouc** [comment]
@RinorJahaj, I'm not sure which default you're talking about as by default, there's no margin, you'll have to set the margin depending on the width of the container, but there's no builtin mechanism to compute percentages.

**Comment by RinorJahaj** [comment]
> @RinorJahaj, I'm not sure which default you're talking about as by default, there's no margin, you'll have to set the margin depending on the width of the container, but there's no builtin mechanism to compute percentages.

Thanks for the reply!
I'm using ResponsiveBar component for this and seems like I can't achieve the desired design. I also tried with Bar component where I can manually play around with props like width and height, but the width it takes it as a whole row (name + bar chart). What I'd like to achieve is give 50% width to name and the other 50% to the chart (as seen in the image I've attached)

**Comment by plouc** [comment]
Sorry, but I don't really understand what you mean, as I suggested, you could compute the margin by yourself depending on the size of the parent, to achieve a 50/50 ratio.

**Comment by RinorJahaj** [comment]
> Sorry, but I don't really understand what you mean, as I suggested, you could compute the margin by yourself depending on the size of the parent, to achieve a 50/50 ratio.

Sorry, I'll try to explain with images:
1)
<img width="421" alt="image" src="https://github.com/plouc/nivo/assets/52374991/f275a9a6-4e8d-48e2-9106-bd30cbe1c10a">

How can I change the design from 1) to 2)
2)
<img width="368" alt="image" src="https://github.com/plouc/nivo/assets/52374991/b61b5b59-18b1-49d9-a709-2ab8614b4f7c">

**Comment by plouc** [comment]
Still the same solution :) You would define the left margin of your chart so that it's 50% of the available space, something you need to compute by yourself.
