### ISSUE TITLE
Bundle size increase when upgrading to v0.83.0

### ISSUE THREAD

**Issue by vio** [plouc/nivo#2347]
**Describe/explain the bug**
I recently upgraded `@nivo/line` and `@nivo/core` from `0.80.0` to `0.83.0` and noticed a `~80KB`(not gziped) increase in the bundle size. The increase is caused by the inclusion of the entire `lodash` library and a duplicate of `d3-color`

**To Reproduce**

- Test repository PR: https://github.com/vio/test-nivo-upgrade/pull/2
- Changed packages report: https://app.relative-ci.com/projects/H9Yx9ocfbdohuca0SAYQ/jobs/4-Banej4lJCDlX3eM9F7Vc/packages
- Lodash bundled modules report: https://app.relative-ci.com/projects/H9Yx9ocfbdohuca0SAYQ/jobs/4-Banej4lJCDlX3eM9F7Vc/modules?bm=%7B%22search%22%3A%22..%2Fnode_modules%2Flodash%2F%22%2C%22filters%22%3A%7B%22changed%22%3Afalse%7D%7D
- bundlephobia: https://bundlephobia.com/package/@nivo/line@0.83.0

**Expected behavior**

I expect nivo to use individual imports to `lodash` and not include a duplicate of `d3-color`

**Screenshots**

Bundle changed packages report:
<img width="1157" alt="Screenshot 2023-05-25 at 19 08 47" src="https://github.com/plouc/nivo/assets/13300/a7104c71-c044-4466-9363-85b00e7e07d9">

Bundle lodash modules report:
<img width="1339" alt="Screenshot 2023-05-25 at 19 09 09" src="https://github.com/plouc/nivo/assets/13300/4696de32-cc82-4b6e-a34b-2becb6ec9425">

**Additional context**

Project is using latest webpack (`v5.84.0`)

---

Thank you for the amazing work, @plouc! Happy to have a look at a possible fix if needed ;)

**Comment by plouc** [comment]
Thank you for the detailed report @vio, I've addressed the d3 packages issue in https://github.com/plouc/nivo/pull/2337/commits/d9a9c975a9daa129159a764bd882a83371ea7501, for lodash, I removed the lodash plugin (which eliminate unused functions) because I had conflicts with it, and I was thinking it shouldn't be an issue if using tree shaking. I'm also trying to remove it when it can be replaced with es6 alternatives, although some helpers are quite handy.

**Comment by vio** [comment]
Thank you for the quick response, @plouc! 

Unfortunately, lodash index module is not treeshackeable. Also, mixing the import types results in duplicate code, `import { get } from 'lodash'` and `import get from 'lodash/get'` will bundle the same code 2x times.

more info: 
- https://lodash.com/per-method-packages
- https://web.dev/decrease-frontend-size/#optimize-dependencies

--- 

I opened #2349, and based on my local tests, the index module is not bundled anymore. If you want to see the change on https://github.com/vio/test-nivo-upgrade, let me know when you are releasing the next version or just open a new PR based on https://github.com/vio/test-nivo-upgrade/pull/2 to trigger the bundle analysis
