### ISSUE TITLE
d3-color vulnerability fix

### ISSUE THREAD

**Issue by decisionsdevin** [plouc/nivo#2348]
**Is your feature request related to a problem? Please describe.**
The nivo library fails vulnerability audit due to d3-color library <3.1.0 vulnerable to ReDos. Although the nivo/core library itself has been updated to use d3-color: 3.1.0, the d3-interpolate and d3-scale-chromatic libraries are using 2.x versions. The outdated version of these libraries depend on the d3-color 2.x libraries, which is why the audit continues to fail.

**Describe the solution you'd like**
Upgrade d3-interpolate and d3-scale-chromatic libraries

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2023-05-25 144111](https://github.com/plouc/nivo/assets/126513415/1869afde-9052-43ce-b50f-22680acc6baa)

**Comment by plouc** [comment]
I noticed this as well, upgrading `d3-color` wasn't enough, that's something I fixed via https://github.com/plouc/nivo/pull/2337/commits/d9a9c975a9daa129159a764bd882a83371ea7501, and it will be included in the next release (I still need to complete the work on the corresponding PR though 😅).

**Comment by msheahen** [comment]
@plouc was this included in the latest release? I'm unfortunately held back by this task as well since its a high vulnerability dependency.   Any update would be great.  Thanks!

**Comment by pcorpet** [comment]
Apparently this is part of the theming change (#2337) which is not merged yet. As such we're still waiting for a fix to be released.
