### ISSUE TITLE
BoxPlot: Could not find a declaration file

### ISSUE THREAD

**Issue by NicolasNewman** [plouc/nivo#2350]
**Describe/explain the bug**
Upon installing the new `@nivo/boxplot` package and importing it, I get the following error:
```
Could not find a declaration file for module '@nivo/boxplot'. '[redacted]/node_modules/.pnpm/@nivo+boxplot@0.83.0_v2m5e27vhdewzwhryxwfaorcca/node_modules/@nivo/boxplot/dist/nivo-boxplot.cjs.js' implicitly has an 'any' type.
```

Importing `@nivo/bar` from the same project yields the path
```
module "[redacted]/node_modules/.pnpm/@nivo+bar@0.83.0_v2m5e27vhdewzwhryxwfaorcca/node_modules/@nivo/bar/dist/types/index"
```

Looking in the node_modules folder I noticed there is no `@nivo/boxplot/dist/types` folder, but it seems to exist in the repo.

My environment uses pnpm with workspaces enabled.

**To Reproduce**

1. `pnpm create react-app my-app --template cra-template-typescript`
2. `cd my-app`
3. `pnpm i @nivo/bar @nivo/boxplot`
4. `ls node_modules/@nivo/*/dist`
5. `@nivo/bar` will contain a `types` folder while `@nivo/boxplot` won't

**Screenshots**
![image](https://github.com/plouc/nivo/assets/16135852/8f1986f9-0c07-4fcf-b48e-4c8a22871cbb)

**Desktop (please complete the following information):**
 - OS: Ubuntu v22.0.4 in WSL
 - Browser: N/A
 - Version N/A

**Comment by NicolasNewman** [comment]
Would the issue be a result of `@export SKIP_TYPES=TRUE` in the Makefile? It looks like that change was made the same version boxplots were added.

**Comment by plouc** [comment]
No this change is not directly the issue, otherwise no packages would have types, it's an optimization as the types are generated for everything before building. I missed this during review, but the package is not included in https://github.com/plouc/nivo/blob/master/tsconfig.monorepo.json.

**Comment by tkonopka** [comment]
My mistake for not updating the monorepo config and missing this after release. Sorry about that. The solution seems quite simple though. How would you like to proceed? I can submit a fix unless either of you would prefer to do it.

**Comment by plouc** [comment]
@tkonopka, @NicolasNewman [PR](#2351) should be enough.
