### ISSUE TITLE
Wafle graph with icons

### ISSUE THREAD

**Issue by kgrvamsi** [plouc/nivo#236]
do the waffle graphs support for icons with color coding?

**Comment by plouc** [comment]
It's not built-in but you can use `cellShape` property and use a custom component.

**Comment by kgrvamsi** [comment]
@plouc  thanks for the info but i don't see this property here mentioned

http://nivo.rocks/waffle/

**Comment by kgrvamsi** [comment]
is this a right syntax that i can use ?

```
import FaServer from 'react-icons/lib/fa/server'

render(){
return (
<ResponsiveWaffle
        data={/* see data tab */}
        total={100}
        rows={18}
        columns={14}
        margin={{
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        }}
        theme={{
            "tooltip": {
                "container": {
                    "fontSize": "13px"
                }
            },
            "labels": {
                "textColor": "#555"
            }
        }}
        colorBy="id"
        borderColor="inherit:darker(0.3)"
        animate={true}
        motionStiffness={90}
        motionDamping={11}
        cellComponent={<FaServer />}
    />
)
}
```
If i miss anything there can you please share a sample code on how to achieve this?

Thanks for all the help

**Comment by plouc** [comment]
You can have a look at https://github.com/plouc/nivo/blob/master/packages/nivo-waffle/stories/waffle.stories.js#L83 & https://github.com/plouc/nivo/blob/master/packages/nivo-waffle/stories/waffle.stories.js#L114
