### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by nappalm** [plouc/nivo#2360]
**Describe/explain the bug**
I haven't even used <ResponsiveBar/>, I just imported it and it throws the error:

![image](https://github.com/plouc/nivo/assets/35016608/1a69743e-48f7-45f3-b6f5-6c8c7a5202c0)

1:
install nivo:
npm i @nivo/core @nivo/bar
2:
import into a component
import { ResponsiveBar } from '@nivo/bar';

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Last

**Comment by tskk97** [comment]
@nappalm Even I faced the same issue, I tried the following:
```
npm i @react-spring/web@9.4.5
```
And, this resolved for me. But, I'm not sure whether this was the right way.

**Comment by plouc** [comment]
I'm afraid I cannot do much about this, it seems related to `@react-spring`, I'd suggest to enable this feature in your config, you could also force the use of `9.4.5` which doesn't seem to require this feature, but it's a bit more dangerous if you ever want to upgrade nivo and nivo requires an higher version.
