### ISSUE TITLE
Passing custom legend shape

### ISSUE THREAD

**Issue by taugustyn** [plouc/nivo#237]
Seems like `symbolShape` uses a [shape class](https://github.com/plouc/nivo/blob/d3abafdcaf612df8602c961e63e2c1d7a22fb94b/packages/nivo-legends/src/svg/symbols/SymbolSquare.js) but it's not possible to pass a custom one.
Is there any other way to to this? For example:

```
legends={[
  {
    anchor: 'bottom',
    direction: 'row',
    translateY: 56,
    itemWidth: 100,
    itemHeight: 18,
    symbolSize: 18,
    // Would be nice to be able to pass custom shape function 
    symbolShape: ({ x, y, size, fill }) => <rect x={x} y={y} width={size} height={size} rx='5' ry='5' />
  }
]}
```

`PropType` for `symbolShape` in [LegendSvgItem](https://github.com/plouc/nivo/blob/20a30ab8a795d359b6e6b1eeb0a2194780c4cb20/packages/nivo-legends/src/svg/LegendSvgItem.js) supports `PropTypes.func` but then it's not implemented properly, i.e. `const Symbol = symbolByShape[symbolShape]` would trigger an error when function is passed.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/272
