### ISSUE TITLE
On the handling of On Issue 2366

### ISSUE THREAD

**Issue by dataf3l** [plouc/nivo#2370]
@plouc 
on: https://github.com/plouc/nivo/issues/2366

Hey, thank you for closing the issue, that really helps. /s

I think the issue here is usability and usability also involves listening to the users.

Which you clearly have no interest in listening.

In my case, As it happens it turns out that my coworker put the chart definition in a JSON and JSON doesn't support comments so he or she removed the crucial comments (which are probably all over the place).

I could have been a newbie as well, which would have made it even longer.

So I Had to go and read the documentation in order to fix it which of course was a waste of time.

zero default height? what mind creates these thoughts...
not even a console log warning about this behavior.

What I found lackluster and mediocre was the absolute lack of documentation, and basically the lack of simple examples on how to use a tool,

and by simple I don't mean like 1000 lines of json, I mean like 5 or 10.

If I need pie chart I probably don't want to read a 600 line JSON to do that, there is no clear indication of what fields are required and which ones are not, is this supposed to be trial and error? reading the comments shows the complete disregard for the users of the tool.

And the fact that there are no simple examples which are really short, it really prevented us to quickly solve the problem. 

The tool wasted more time it saved.

In this case regarding the way of solving the problem unfortunately.  I think that basically it's unusable in it's current state, and we might move onto a different charting library based on this interaction that I'm having with you and the previous interaction to avoid further traps that may be lying there in the code.

The choice of names, like "IndexBy" and "keys" was also poor in my opinion, but I supposes you guys are now stuck with that, even though there were probably better names for those fields.

You're telling people that need they need to set a height, why not just have a default minimum height?
you know, like something reasonable, like most components do.

Why Not just having width and height parameters which are optional for example, like most libraries?

Your claim that it could expand in definitely shows lack of creativity, I would argue it's just plainly a false statement.

So you lie to your users, but why?

Here is the thing,

I sincerely hope that you guys improve your tools, I sincerely hope that you guys will improve the example code, to have shorter example codes, and to have a tool where they optional parameters are in fact not set and not added to the code.

Because I believe in Open source, as a maintainer, I wish I didn't get criticism like this, but here some truths have to be said.

Sincerely hope guys I love add focus on usability and user focus, and I also sincerely hope that you guys stop closing the issues posted without further investigation as to what are the causes of the problem.

 because this is the only way open source is going to move forward is that people are passionate about software, just like you guys were clearly passionate about software, I suggest transform some of this passion into compassion, and consider that the tool in its current state is unusable due to the lack of usability, the lack of examples, and the extraneous requirements, I can't believe that you guys can write a for loop to calculate the height.

Even you guys feel uninterested in the problem I supposed to ChatGPT can probably write the code that calculates the height, I asked it, it provided some examples, can't say they are perfect, but I see it was possible to solve it. 

the ideal height is in attainable. just like the "ideal width" is also attainable. what are you do here is just setup different default value which is non-zero (this part is important, defaults are important), because whoever put the default as zero height  obviously was not thinking of other users when they put this arcane trap for users to fall into.

who knows what other traps are on this library.

I suppose the issue here is probably the individual person who decided to close my issue without giving a damn, but you guys are probably stuck with that person, so I don't really have any advice on how to even solve that.

anyone's advice on what other chart library would be interesting.

**Comment by littledot** [comment]
Every single example says 
```
// make sure parent container have a defined height when using
// responsive component, otherwise height will be 0 and
// no chart will be rendered.
```
You spent 6hrs and couldn't figure this out? That's a skill issue.
