### ISSUE TITLE
EnableArea goes beyond the x-axis limit

### ISSUE THREAD

**Issue by lfpazmino** [plouc/nivo#2372]
**Steps to reproduce:**

Create ResponsiveLine with property "enableArea" = true, paints the area beyond the x-axis limit

<img width="380" alt="image" src="https://github.com/plouc/nivo/assets/6908976/b66c6fea-1ccd-46a8-a302-5360280d8097">

**Using the following versions:**
    "@nivo/core": "^0.83.0",
    "@nivo/line": "^0.83.0",

**Attaching the full component definition:**
  <ResponsiveLine
    theme={theme}
    data={props.data}
    enableArea={true}
    margin={{ top: 20, right: 110, bottom: 40, left: 40 }}
    xScale={{ type: "point" }}
    yScale={{
      type: "linear",
      min: "auto",
      max: "auto",
      stacked: true,
      reverse: false,
    }}
    axisTop={null}
    axisRight={null}
    axisBottom={{
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "years",
      legendOffset: 36,
      legendPosition: "middle",
    }}
    axisLeft={{
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "",
      legendOffset: -40,
      legendPosition: "middle",
    }}
    pointSize={10}
    pointColor={{ theme: "background" }}
    pointBorderWidth={2}
    pointBorderColor={{ from: "serieColor" }}
    pointLabelYOffset={-12}
    useMesh={true}
    legends={[
      {
        anchor: "bottom-right",
        direction: "column",
        justify: false,
        translateX: 100,
        translateY: 0,
        itemsSpacing: 0,
        itemDirection: "left-to-right",
        itemWidth: 80,
        itemHeight: 20,
        itemOpacity: 0.75,
        symbolSize: 12,
        symbolShape: "circle",
        symbolBorderColor: "rgba(0, 0, 0, .5)",
        effects: [
          {
            on: "hover",
            style: {
              itemBackground: "rgba(0, 0, 0, .03)",
              itemOpacity: 1,
            },
          },
        ],
      },
    ]}
  />

**Comment by plouc** [comment]
You can use `areaBaselineValue` to adjust this, but it's not computed automatically, in your case, it should be the lowest y value.
