### ISSUE TITLE
scatterplot with string x axis

### ISSUE THREAD

**Issue by tflanagan** [plouc/nivo#2378]
**Describe/explain the bug**
Was unable to accept discord invite for some reason, so was unable to screen this, but I think I found a bug or a chance to enhance documentation.

With `<ResponsiveScatterPlot />` an `x` value of a type of `string` fails to render.

It appears this chart only supports dates and numbers, not strings, however the typing suggests that strings are supported. Is `string` in the type to support `2023-06-28` date strings or were arbitrary strings intended to be supported?

**To Reproduce**

```
<ResponsiveScatterPlot
	data={[{
		id: 'a',
		data: [{
			x: 'z',
			y: 3
		}, {
			x: 'x',
			y: 5
		}, {
			x: 'y',
			y: 7
		}]
	}, {
		id: 'b',
		data: [{
			x: 'z',
			y: 8
		}, {
			x: 'x',
			y: 1
		}, {
			x: 'y',
			y: 9
		}]
	}, {
		id: 'c',
		data: [{
			x: 'z',
			y: 2
		}, {
			x: 'x',
			y: 4
		}, {
			x: 'y',
			y: 6
		}]
	}]}
	margin={{ top: 60, right: 140, bottom: 70, left: 90 }}
	xScale={{ type: 'linear', min: 0, max: 'auto' }}
	yScale={{ type: 'linear', min: 0, max: 'auto' }}
	blendMode="multiply"
	axisTop={null}
	axisRight={null}
	axisBottom={{
		tickSize: 5,
		tickPadding: 5,
		tickRotation: 0,
		legend: 'Text Field',
		legendPosition: 'middle',
		legendOffset: 46
	}}
	axisLeft={{
		tickSize: 5,
		tickPadding: 5,
		tickRotation: 0,
		legend: 'Number Field',
		legendPosition: 'middle',
		legendOffset: -60
	}}
	legends={[
		{
			anchor: 'bottom-right',
			direction: 'column',
			justify: false,
			translateX: 130,
			translateY: 0,
			itemWidth: 100,
			itemHeight: 12,
			itemsSpacing: 5,
			itemDirection: 'left-to-right',
			symbolSize: 12,
			symbolShape: 'circle',
			effects: [
				{
					on: 'hover',
					style: {
						itemOpacity: 1
					}
				}
			]
		}
	]}
/>
```

**Expected behavior**

xAxis to properly render `z`, `x`, and `y` instead of interpreting them as numbers and producing `NaN`

Types:

```
export type ScatterPlotValue = number | string | Date;
```

**Screenshots**

![Screenshot 2023-06-28 114312](https://github.com/plouc/nivo/assets/5559820/16841bc0-f5c6-4b8e-acac-e2d99ec50f75)

**Comment by plouc** [comment]
That's because the `xScale` is defined as a `linear` scale, but you provide string values, you should use a `point` scale for your use case, please see https://codesandbox.io/s/nivo-scatterplot-non-linear-x-value-91498pz0wo?file=/src/index.js.
