### ISSUE TITLE
Stacked line chart tooltip showing zero values when they share a point with a non-zero value

### ISSUE THREAD

**Issue by erquhart** [plouc/nivo#2382]
**Describe/explain the bug**
In a stacked line graph, when hovering a point that has both zero (0) values and a non-zero value:
- the zero (0) value point(s) are not really visible to the user, they are hidden behind the non-zero point as they should be
- the non-zero value point is rendered out front, as expected
- the tooltip reflects one of the hidden zero values instead of the visible point

**To Reproduce**

1. Check out sandbox: https://codesandbox.io/s/broken-feather-cs4kck?file=/src/App.tsx
2. Hover the right-most point on the chart
3. Observe non-zero value obscured by zero value

**Expected behavior**
The visible, non-zero value should be the point reflected in the tooltip

**Screenshots**
<img width="509" alt="Screenshot 2023-07-06 at 12 57 45 PM" src="https://github.com/plouc/nivo/assets/2112202/d7e56112-a314-4d73-8035-72ce5664be3b">
Note that the light tan point is hovered, and is the only one visible to the user, but the tooltip shows the non-visible yellow point data, which is zero. When there are a lot of lines, there's no way to tell what that visible value represents.

**Additional context**
This is similar to this issue: https://github.com/plouc/nivo/issues/1051

**Comment by newerton** [comment]
I'm having the same problem with ResponsiveCirclePacking.

The initial values is zero, and that value does not show the bubbles.
