### ISSUE TITLE
RadialBar -- allow axis "enabled" feature in production

### ISSUE THREAD

**Issue by codewizard-dt** [plouc/nivo#2384]
**Is your feature request related to a problem? Please describe.**
When using the RadialBar, the axis config objects have properties to change the tick size, padding, etc, but there is no way to customize the labels

**Describe the solution you'd like**
In the demo there is an "enabled" property that makes the ticks and labels completely disappear.  This should be available in production. 

**Describe alternatives you've considered**
Provide a way to give a custom label that I could force to an empty string, or allow the option to provide values for ticks (like is done in the Bar component) so that I can provide an empty array.

**Additional context**
https://nivo.rocks/radial-bar/
![Screen Shot 2023-07-10 at 12 05 59 PM](https://github.com/plouc/nivo/assets/94571813/b84778f2-460c-44a0-8720-a4259083de5e)

**Comment by plouc** [comment]
It's not a prop per se, but if you look at the generated code, you'll see that it leads to `circularAxisOuter={null}`, so this is already available.
