### ISSUE TITLE
Is there a mouseover/mouseout handler?

### ISSUE THREAD

**Issue by mjsarfatti** [plouc/nivo#239]
Sometimes you have several charts in your page, and you want to highlight a datum on each chart whenever you hover over a single element. This is usually done with a mouseover/mouseout handler, but I can't seem to find anything available. Only an onClick handler.

Is there a suggested way of enhancing the Nivo components maybe? Or is it something that needs to be baked in?

**Comment by plouc** [comment]
Not for now, it's not exposed and only used for tooltips, but it could be feasible to use the existing events.

**Comment by mjsarfatti** [comment]
Is it something you would be interested in?
I have to tackle a project that could make use of Nivo components, but it needs onHover handles. I could fork Nivo, implement it and submit a pull request.

A second thing I'd need is a map/geo component, if it interests you I could develop it as a Nivo component as well.

Let me know :)

**Comment by plouc** [comment]
Yes, for sure :) Contributions are very welcome!

**Comment by lferreira457** [comment]
not in the docs, but after going through the code `onMouseEnter` & `onMouseLeave` seem to work

**Comment by plouc** [comment]
Support was added for scatterplot in `0.51.0`

**Comment by plouc** [comment]
Doing a little bit of issues cleanup, I'm closing this one in favor of https://github.com/plouc/nivo/issues/47

**Comment by plouc** [comment]
@mjsarfatti, regarding charts synchronization, you can now find an [example for the scatterplot](http://nivo.rocks/storybook/?selectedKind=ScatterPlot&selectedStory=synchronizing%20charts&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by mjsarfatti** [comment]
@plouc, awesome. By the way, we finally went online with the project I was working on, and for which I needed some of the extra funcionality. This was all done (with the only exception of the map) with Nivo: http://taxtracker.eu/

**Comment by cazapatamar** [comment]
@mjsarfatti is your code published at any public repository? Looking your website http://taxtracker.eu/, i can identify some functions such as click events i need to implement into my project, which use nivo.

**Comment by mjsarfatti** [comment]
@cazapatamar unfortunately I can't open the repository, but everything you see there was eventually made part of nivo. I believe onClick handlers are now part of every (or almost every) chart type, same for onMouseEnter/onMouseLeave.
