### ISSUE TITLE
please add percent Mark %

### ISSUE THREAD

**Issue by bananana0118** [plouc/nivo#2393]
**Is your feature request related to a problem? Please describe.**

Hi Thanks for this library 
I have some issue...

I want custom my Chart

![image](https://github.com/plouc/nivo/assets/28006318/9939481b-4515-435f-9a3d-2021134932c9)

I want to add % mark 

66.67 => 66.67%

I try to use valueFormat option but 

66.66 => 6700.0%
![image](https://github.com/plouc/nivo/assets/28006318/ef0e61aa-5179-423b-89aa-d21049eb703b)

I want to write the % mark of a number

66.67 "%"

not multiply by100

What should I do?

**Comment by SebasQuirogaUCP** [comment]
Hey there @bananana0118 ,
Recall `valueFormat` can receive either a string or a callback. Try using the callback to parse the values as needed.

`valueFormat: string | (value: number) => string | numberoptional`

**Comment by bananana0118** [comment]
![image](https://github.com/plouc/nivo/assets/28006318/b6bf2a93-0951-4d73-a18b-00870cf3df19)

Yeah!! I did it 
thanks!!

**Comment by bananana0118** [comment]
> Hey there @bananana0118 , Recall `valueFormat` can receive either a string or a callback. Try using the callback to parse the values as needed.
> 
> `valueFormat: string | (value: number) => string | numberoptional`

![image](https://github.com/plouc/nivo/assets/28006318/81d9df0c-f7ce-4c03-bbb8-feed321e091d)

Yeah! I did it!!
thanks!!!
