### ISSUE TITLE
Adjusting width of arc slices based on the values.

### ISSUE THREAD

**Issue by johngeorge1998** [plouc/nivo#2400]
Hi,
It would be great if the Pie charts have the feature for adjusting the arc width based on the values inside it, Please consider this request or inform me if the feature already exists,

Thankyou

**Comment by plouc** [comment]
The arcs already match the values provided to the chart, I'm not sure I understand what you mean.

**Comment by johngeorge1998** [comment]
![Screenshot (12)](https://github.com/plouc/nivo/assets/113915115/fac3ebf3-0400-4309-b0d9-1389ff1776be)

is there anyway I can achieve similar layout for the Pie chart

**Comment by plouc** [comment]
Ah, I see, you meant the radius, no, it's a different chart type, usually called a rose chart, nivo doesn't support this, and I'm not planning to add this to the pie chart.

**Comment by johngeorge1998** [comment]
Ok Thankyou
