### ISSUE TITLE
Pie chart slice stand out when click it

### ISSUE THREAD

**Issue by alienriquebm** [plouc/nivo#2406]
**Is your feature request related to a problem? Please describe.**
Actually we can stand out a slice of the pie chart when we hover it, but I would like to have the same interactivity when we click it.

**Describe the solution you'd like**
Add to the graphs like the pie chart the interactivity of when clicked slice stands out exactly when we do hover on it. Implement a "toogle" interactivity.

**Additional context**
![image](https://github.com/plouc/nivo/assets/5152002/966c21d5-15e2-4fcf-b50a-55a3c105a974)

**Comment by barrymichaeldoyle** [comment]
This is very similar (not exactly the same) to my feature request.

https://github.com/plouc/nivo/issues/2388

It is the same reason why I don't want a single out of the box solution, but some way to specifically indicate that a specific slice is active, which would help a lot with sorting everything out.

**Comment by plouc** [comment]
Hi @alienriquebm,

I'm agree with @barrymichaeldoyle, and I'm currently working on such solution, I also feel it would offer more flexibility.

**Comment by plouc** [comment]
The ability to define the `activeId` has been released in `0.84.0`.
