### ISSUE TITLE
Show tooltip always, not only on hover

### ISSUE THREAD

**Issue by radikris** [plouc/nivo#2407]
I would like that my radarchart would always show the tooltip, I could create a custom tooltip with
```
   sliceTooltip={(data) => {
        return (
          <div className="button-medium visible flex gap-x-4 rounded-full bg-other-white px-12 py-4 ">
            {data.index}
            <span className="text-primary-green-green-300">({data.data[0].value})</span>
          </div>
        );
      }}
```

But it is only showing up on hover (or click or something focus), would be great if we could make these always visible.
My workaround would be too difficult with custom svg element creation and positioning.

Currently: 

<img width="553" alt="image" src="https://github.com/plouc/nivo/assets/55052220/1be40784-92b3-4f57-ab54-9908a5274754">

Expected behaviour:

<img width="585" alt="image" src="https://github.com/plouc/nivo/assets/55052220/46652c3c-9026-4f0d-a403-8bb0c983f262">

**Comment by plouc** [comment]
The tooltip behaves as a tooltip, if you want to add those labels, you can try to add a custom layer.
