### ISSUE TITLE
ScatterPlot: minX, maxX, minY, maxY

### ISSUE THREAD

**Issue by jawj** [plouc/nivo#241]
I'm using nivo in a dashboard I'm putting together, which is going well so far. Thanks!

Using ResponsiveScatterPlot —  I find I can set minX, maxX, etc, but these props don't seem to be respected, and still appear to be set to 0 (min) and auto (max).

Am I doing something wrong here, or is this a problem that could this be fixed in the library?

**Comment by jawj** [comment]
Figured out I can use the `scales` prop to achieve this, but it feels a bit unpolished?

```
scales={[
  { id: 'x', axis: 'x', domain: [0, 100] },
  { id: 'y', axis: 'y', domain: [0, 100] }
]}
```

**Comment by plouc** [comment]
Yep, sorry for the lack of reply, it's not well documented unfortunately :/ is it ok then, can I close this issue?

**Comment by jawj** [comment]
Sure — though I suggest it might be worth accepting minX, maxX etc. in line with the other chart types?

**Comment by plouc** [comment]
`scales` are the best way to deal with scales customization, I've exposed (min|max)(X|Y) on several charts for BC, but it only solve part of the problem, `scales` also allows to customize scale type (linear, categorical, time…) and I'd like to expose them for other charts as there is many issues regarding this feature.

**Comment by plouc** [comment]
I think the behavior can become very unpredictable with overlapping properties.

**Comment by jawj** [comment]
OK, thanks — I'm sure you've thought more about this! I think partly I got confused by the existence of those properties near the top of the ScatterPlotDefaultProps object (lines 69 – 72), which it appears are never used?

**Comment by plouc** [comment]
You're right, it should be removed then :/ I've created a new issue for this https://github.com/plouc/nivo/issues/243, thank you.
