### ISSUE TITLE
Step-wise Chart

### ISSUE THREAD

**Issue by yubarajshrestha** [plouc/nivo#2426]
**Is your feature request related to a problem? Please describe.**
It's not a problem but a feature.

**Describe the solution you'd like**
<img width="822" alt="Screenshot 2023-09-05 at 12 22 47" src="https://github.com/plouc/nivo/assets/7955362/07d7369b-8872-4a78-a890-18e71b26b341">
Let's take an example of above chart it is used in lots of places but doesn't looks like nivo has this one.

**Describe alternatives you've considered**
Everychart in nivo is super nice and super customizable it's really awesome. But I am working on representing the mortality rate of a patient and I needed the step-wise chart for this hence I had to switch to `Chart.js`

**Comment by plouc** [comment]
@yubarajshrestha, it is supported, you can use the line chart with `curve="stepAfter"`, something you can try in the interactive demo as well.
