### ISSUE TITLE
Add options for padding labels in either axis

### ISSUE THREAD

**Issue by mattander** [plouc/nivo#2429]
**Is your feature request related to a problem? Please describe.**
I'm having trouble achieving consistent styling between my bar charts and line charts when it comes to aligning tick labels. 

On the Bar Chart the x-axis value labels are padded in from the edge of the chart, but on the Line Chart they are flush with the edge. The design we've been given has the charts stacked vertically and the unaligned labels don't match the design. 
![image](https://github.com/plouc/nivo/assets/10996915/593aa9de-884c-41c8-9279-cb4fbc1addea)
![image](https://github.com/plouc/nivo/assets/10996915/57f12d41-55b0-4bc8-8e06-34c787fa398f)

**Describe the solution you'd like**
The option to add padding to the x axis labels so they can be consistent between charts. 

**Describe alternatives you've considered**
We've looked through all the available options we can tweak but nothing seems to achieve what we are looking for. 

**Additional context**
Here's what we'd like to see
![image](https://github.com/plouc/nivo/assets/10996915/cfbc369b-239a-440e-a4aa-2099acdc0b2f)

![image](https://github.com/plouc/nivo/assets/10996915/a6c447e1-4a84-4af2-a4e0-228f878edc16)

**Comment by plouc** [comment]
Unfortunately, this is not supported, and could be a bit tricky, the line chart would need extra values for the edges, or could duplicate the first and last one, but then it should be excluded from interactions, clicks, tooltips... And for certain curve options, would alter the shape of the line, which could be misleading IMHO.

Also the bar chart uses a band scale to compute the space between each group, while the line chart uses a point/linear scale, so it doesn't have the same option.

I don't plan to add such feature, but you might be able to achieve something close by playing with the margins/tick padding, please have a look at this example: https://codesandbox.io/s/nivo-line-bar-tick-padding-psfn2w?file=/src/index.js.

**Comment by mattander** [comment]
Thanks for the feedback. We appreciate the response.

**Comment by robin-blanchard** [comment]
Hello, has any solution been found for this ?
