### ISSUE TITLE
custom tooltip doesnt work for nivo/heatmap (v0.83.0) as node information gives back 'undefined'

### ISSUE THREAD

**Issue by inslyde-sd** [plouc/nivo#2430]
Hi, 

I'm using nivo heatmap (Responsive Heatmap, SVG) and want to use a custom tooltip. The tooltip itself is shown correctly when used without accessing any node information. But if I try: 

tooltip={({ node }) => {
  console.log(node);
  return (
    <CustomTooltip
        id={node.id}
        value={node.value}
    />
  );
}}

console.log gives back 'undefined' and id and value are not accessible and throws an error (i.e. "TypeError: Cannot read properties of undefined (reading 'id')") as soon as I hover over the chart (to see the tooltip). 
I suppose somehow the node information is not accessible. This custom tooltip code as shown above works for several other chart types from nivo (i.e. treemap). Hence, I guess there must be some issue with tooltip for the heatmap chart. 

I'd expect the information to be show in the tooltip by accessing it like {node.id} or {node.value}

I'd appreciate any help on this. Workarounds are welcome.

I'm using:
    "@nivo/core": "^0.83.0",
    "@nivo/heatmap": "^0.83.0",
    "react": "^17.0.1",

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 115.0.5790.171

**Comment by plouc** [comment]
The data is available under the `cell` property, please see the [default implementation](https://github.com/plouc/nivo/blob/master/packages/heatmap/src/HeatMapTooltip.tsx).
