### ISSUE TITLE
Tooltips are not working with Yarn3 PnP Berry in Pie, Bar, other charts

### ISSUE THREAD

**Issue by unrealsolver** [plouc/nivo#2435]
**Describe/explain the bug**
Moving cursor over a pie chart crashes the app. Am I missing 

**To Reproduce**
This can not be reproduced in regular `node_modules` repo, I think it's required to use Yarn PnP. Basically, you just need this:
```javascript
        <ResponsivePie
          data={[
            { id: "a", label: "a", value: 10 },
            { id: "b", label: "b", value: 20 },
          ]}
```
and then move cursor over the chart.

**Expected behavior**
To see a tooltip

**Screenshots**
I assume this context should not be undefined, but it is for some reason:
![image](https://github.com/plouc/nivo/assets/1101771/8cd9fcc3-715b-42f9-8173-4610a7697825)
![image](https://github.com/plouc/nivo/assets/1101771/4d45d4ed-5daa-4a4c-a417-0b3b9c208e39)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Firefox
 - Version 118

**Additional context**
package.json:
```
    "@nivo/core": "^0.83.0",
    "@nivo/pie": "^0.83.0",
    "@nivo/tooltip": "^0.83.0",
```
.yarnrc.yml
```
yarnPath: .yarn/releases/yarn-3.6.0.cjs
```

**Comment by plouc** [comment]
Should have been solved by https://github.com/plouc/nivo/pull/2528.
