### ISSUE TITLE
Stream chart parts don't fit inside of the container in v0.83.0 (working correctly in v0.79.1)

### ISSUE THREAD

**Issue by mouhannad-sh** [plouc/nivo#2436]
Hi 👋🏻 

Demonstrated in this codesandbox https://codesandbox.io/s/stream-funnel-forked-vzpx3d
updating `@nivo/stream` to latest (v0.83.0) will make the stream chart parts overflow the container as shown in the before after below:

### Before @ 0.79.1
<img width="1336" alt="image" src="https://github.com/plouc/nivo/assets/18495740/21e73d95-6f63-4353-9a01-9abeb3b19752">

### After @ 0.83.0 (bug)

<img width="1358" alt="image" src="https://github.com/plouc/nivo/assets/18495740/bacc48b6-8df0-4f50-8b1e-7595cb07109f">

**Describe/explain the bug**

**To Reproduce**

 - update `@nivo/stream` to 0.83.0

**Expected behavior**
The chart should look the same as it does in 0.79.1

**Desktop:**
 - OS: MacOS
 - Browser Chrome
 - Version 116

Happy to contribute with some guidance 
Thanks a bunch

**Comment by plouc** [comment]
Hi @mouhannad-sh,

This has been fixed via https://github.com/plouc/nivo/pull/2392, and should not be an issue anymore if you upgrade to `0.83.1`.
