### ISSUE TITLE
@nivo/waffle is missing type declarations

### ISSUE THREAD

**Issue by patbeqo** [plouc/nivo#2437]
**Describe/explain the bug**
The @nivo/waffle package is missing type declarations.

**To Reproduce**
Dist folder does not include type declarations. https://www.npmjs.com/package/@nivo/waffle?activeTab=code

**Expected behavior**
Include a types folder similar to @nivo/bar

**Desktop (please complete the following information):**
- Version 0.83.0

**Comment by plouc** [comment]
Fixed in version `0.83.1`.
