### ISSUE TITLE
Allow `innerRadius` to be applied to individual slices instead of only ALL slices

### ISSUE THREAD

**Issue by barrymichaeldoyle** [plouc/nivo#2439]
**Is your feature request related to a problem? Please describe.**
I want to accomplish a Pie Chart design as follows:

<img width="431" alt="Screenshot 2023-09-29 at 15 15 45" src="https://github.com/plouc/nivo/assets/4674486/ac41eaca-ec03-4b57-9537-45c031990ba7">

But I can't get the innerRadius style to be value based. Currently the `innerRadius` prop only accepts a number that will be applied to all pie slices.

**Describe the solution you'd like**
I would like the `innerRadius` prop to be extended to also accept an array of values that will apply respectively to each data slice so that I can accomplish this design above

**Describe alternatives you've considered**
I haven't been able to figure this out other than just picking a different library.

**Comment by plouc** [comment]
This is more like a rose chart, which is not supported (and not planned) atm, then users would probably want some kind of scale to compute this, decide if it expands/shrinks inward/outward...
