### ISSUE TITLE
How can I set the width of the bars in Bar chart

### ISSUE THREAD

**Issue by niralivasoya** [plouc/nivo#2441]
I want to set the custom width for the bars. I want it like this:

<img width="325" alt="image" src="https://github.com/plouc/nivo/assets/32123446/00f6a6bc-1f90-4bb7-89eb-148ea5364a9a">

This is my current behaviour using `@nivo/bar`.

<img width="513" alt="image" src="https://github.com/plouc/nivo/assets/32123446/bfcbd1f4-eb16-472d-882d-44aa660ddb2f">

any suggestion?

**Comment by niralivasoya** [comment]
@plouc, can you please look into it?

**Comment by plouc** [comment]
@niralivasoya, you cannot set a fixed width for the bars, but you can play with `padding` to achieve what you want.

**Comment by yairEO** [comment]
You can utilize the `barComponent` prop for the `ResponsiveBar` component:

```tsx
<ResponsiveBar
  barComponent={CustomBar}
  ...
```

## `CustomBar.tsx`:

```tsx
import { BarItem, type BarDatum, type BarItemProps, type ComputedDatum} from "@nivo/bar";

const BAR_MAX_WIDTH = 20;

interface CustomBarProps<RawDatum> extends BarItemProps<RawDatum> {
  bar: Omit<ComputedDatum<RawDatum>, "data"> & {
    data: BarDatum;
  };
}

const CustomBar = <RawDatum extends BarDatum>(
  props: CustomBarProps<RawDatum>
) => {
  const {
    bar: { data, ...bar },
    style,
  } = props;

  const w = Math.min(bar.width, BAR_MAX_WIDTH);
  const x = bar.x + bar.width / 2 - w / 2;

  return (
    <BarItem
      {...props}
      bar={{ ...bar, data, x }}
      style={{
        ...style,
        width: w,
        transform: `translate(${x}, ${bar.y})`,
      }}
    />
  );
};

export default CustomBar;
```
