### ISSUE TITLE
Visual bug on website

### ISSUE THREAD

**Issue by chip-davis** [plouc/nivo#2445]
**Describe/explain the bug**
On the page [theming](https://nivo.rocks/guides/theming/) there is a minor visual bug. An excerpt is eclipsing one of the graphs. It has information about "Online", "Combini", and "Supermarket".

**To Reproduce**
Go to https://nivo.rocks/guides/theming/

**Expected behavior**
The graph should be fully visible. 

**Screenshots**
![image](https://github.com/plouc/nivo/assets/62909360/42466c36-1588-4c7c-8254-e4d3cdd76872)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Firefox
 - Version 118.0.2 of Firefox and 117.0.5938.150 of Chrome

The visual bug is also present on mobile (iOS / Safari).

**Comment by LeonKilgoreTrout** [comment]
I guess it supposed to be 270°

**Comment by LeonKilgoreTrout** [comment]
> **Describe/explain the bug** On the page [theming](https://nivo.rocks/guides/theming/) there is a minor visual bug. An excerpt is eclipsing one of the graphs. It has information about "Online", "Combini", and "Supermarket".
> 
> **To Reproduce** Go to https://nivo.rocks/guides/theming/
> 
> **Expected behavior** The graph should be fully visible.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/62909360/274347297-42466c36-1588-4c7c-8254-e4d3cdd76872.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 11
> * Browser Chrome, Firefox
> * Version 118.0.2 of Firefox and 117.0.5938.150 of Chrome
> 
> The visual bug is also present on mobile (iOS / Safari).


I guess it supposed to be 270°

**Comment by plouc** [comment]
Yes, this is normal, it's a [radial bar chart](https://nivo.rocks/radial-bar/), not a pie chart.
