### ISSUE TITLE
continue line over holes in data

### ISSUE THREAD

**Issue by Gim-way** [plouc/nivo#2450]
Is your request to add a feature related to any problem? Please describe it.
I have created a line chart where the x-axis data has holes, but the line should be continuous. We go straight from the last Null data point to the next one.

Describe the solution you would like to receive
A logical parameter that causes the line to continue over the holes or to make a discontinuous line
![изображение](https://github.com/plouc/nivo/assets/96630329/55e6aeef-8658-4df5-a8db-854eadfb6f14)
You have to do it like this
<img width="1920" alt="Group 12(1)" src="https://github.com/plouc/nivo/assets/96630329/cb14daad-4258-49f2-88d1-a88a8fddfca9">
This is the data that comes
{
	"miniChart": [
		{
			"chr": "539066666",
			"phr": "510377600",
			"cAt": 1697500800
		},
		{
			"chr": null,
			"phr": null,
			"cAt": 1697511600
		},
		{
			"chr": "538887499",
			"phr": "509336108",
			"cAt": 1697587200
		}
	]
}

**Comment by plouc** [comment]
While this feature is not supported, you could achieve something a bit similar by populating the null values with the latest defined value, the drawback would be that tooltips would then treat those as non-null values.

**Comment by plouc** [comment]
@Gim-way, you could simply exclude the entries with null values.
