### ISSUE TITLE
tooltip.container submenu fails front of the page

### ISSUE THREAD

**Issue by LeonKilgoreTrout** [plouc/nivo#2451]
**Describe/explain the bug**
tooltip.container submenu fails front of the page

**To Reproduce**
Go to [https://nivo.rocks/guides/theming/](https://nivo.rocks/guides/theming/)
Scroll to the bottom
Click on tooltip.container item
There is blank line only

**Screenshots**
![ex](https://github.com/plouc/nivo/assets/79303699/465dfdc3-6d7f-47bb-b0f1-442af221111e)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome, Firefox, Edge

**Comment by plouc** [comment]
This has been fixed.
