### ISSUE TITLE
Missing boxplot types issue still present in 0.83.0

### ISSUE THREAD

**Issue by CSWITH89** [plouc/nivo#2458]
**Describe/explain the bug**
declaration file missing for boxplots, first highlighted in issue #2350  but no fix has been released.

1. yarn add @nivo/boxplot

**Expected behavior**
declaration file should be present 
types folder should be present

**Comment by plouc** [comment]
This has been released, and typings are now available in `0.83.1`.

**Comment by CSWITH89** [comment]
@plouc Ah my apologies I yarn installed 0.83.1. I was confused as GH shows me 0.83.0 is latest.

**Comment by plouc** [comment]
@CSWITH89, you were right, I published this new release yesterday.
