### ISSUE TITLE
multiple copies of dependencies imported

### ISSUE THREAD

**Issue by taozhou-glean** [plouc/nivo#2463]
not necessary a bug report, but just happen to notice that there are multiple versions of the same dep, like `d3-interpolate` here, are imported on the same 0.83.1 nvio scope, would be nice if we can consolidate all of them across the package scope:

![image](https://github.com/plouc/nivo/assets/121891361/72cdb324-9d17-4829-b400-b4ded14283ea)

**Comment by plouc** [comment]
Hum, thank you for reporting this, it's not intended, I need to check if I can use another version of `d3-scale` using `d3-interpolate@3.0.1`.

**Comment by icco** [comment]
I was seeing something similar with `d3-scale-chromatic` so I created https://github.com/plouc/nivo/pull/2466 but probably needs work or more thought as there are a few packages here that have major version differences.

**Comment by cythrawll** [comment]
I mean this is kinda a bug? cuz my vulnerability scanner is still tripping up on having d3-color 2.0 being brought in by d3-scale-chromatic 2.0 (using regular old npm)

**Comment by plouc** [comment]
Upgraded d3 dependencies, should be solved in `0.85.1`.
