### ISSUE TITLE
extra space in long bar charts

### ISSUE THREAD

**Issue by ph98** [plouc/nivo#2471]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

https://codesandbox.io/s/wispy-glitter-r392l6?file=/src/App.js

1. apply an large array to the data source of the chart.

**Expected behavior**

I expect the margin to be close to zero, but now it will be so high when we apply a large array.

**Screenshots**
<img width="317" alt="image" src="https://github.com/plouc/nivo/assets/6303786/e9792d6d-4a9e-4faa-b13d-bdbcb852dbca">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by plouc** [comment]
Hi @ph98,

This is due to rounding on the index scale (which becomes quite noticeable with large charts), you can fix this by disabling it:

```
indexScale={{
    type: 'band',
    round: false,
}}
```
