### ISSUE TITLE
Its very useful to provide tooltip for axis points also

### ISSUE THREAD

**Issue by chaitanyaleanpitch** [plouc/nivo#2475]
**Is your feature request related to a problem? Please describe.**
If the axis points title is very long we are truncating it, but cant show tooltip on hover of it 

**Describe the solution you'd like**
If we can provide tooltip function for tha points, on hover of it we can show the full name

**Additional context**
Example: Point at x-axis: Basics of python
The text we are showing: Basics o...
Solution on hover of it: () => {
<p> Full Text( Basics of python ) </p>
}

**Comment by plouc** [comment]
Duplicate of https://github.com/plouc/nivo/issues/2476.
