### ISSUE TITLE
MouseEnter and MouseLeave callbacks aren't called in BarCanvas

### ISSUE THREAD

**Issue by sambev** [plouc/nivo#2479]
**Describe/explain the bug**
I'm trying to use the `onMouseEnter` and `onMouseLeave` callbacks in the `BarCanvas` component, but they are almost never called. I can see them being used in the code here: https://github.com/plouc/nivo/blob/master/packages/bar/src/BarCanvas.tsx.

I tried debugging these and I noticed there is a guard for `onMouseEnter` that is `event.type === 'mouseenter'` but the event is always `mousemove`. With `onMouseLeave`, the bar from `const bar = findBarUnderCursor(bars, margin, x, y)` is always `undefined`.

**To Reproduce**
 I have a simple sandbox that shows the behavior here: https://codesandbox.io/p/sandbox/tender-glade-ryy392.

If I move my mouse really fast over lots and lots of bars, i'll occasionally get a callback, but it doesn't seem very predictable.

**Expected behavior**
I would expect the mouseenter/leave callbacks to to be called when the mouse 'enters' or 'leaves' a bar

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 119.0.6045.159 (Official Build) (arm64)

**Comment by plouc** [comment]
That's because for the canvas implementation, these events are only triggered when entering/leaving the main canvas element, that's a limitation of the canvas implementation.

**Comment by plouc** [comment]
That being said, this limitation should be clearly stated in the docs, and I realized that some event handlers are missing on the website.
