### ISSUE TITLE
Would like to set a custom color for each node in ResponsiveCirclePacking

### ISSUE THREAD

**Issue by jagdeepsb** [plouc/nivo#2482]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Working with a react project. I'd like to be able to do something like:
`colors={(node) => node.color}` in the `ResponsiveCirclePacking` component or otherwise specify the color in `data`. 
For example: 
```
const data = {
  id: "nivo",
  children: [
    { id: "a", value: 100, color: "#353745" },
  ],
};
```

**Describe alternatives you've considered**
New to this library. I have reviewed documentation and examples and could not find a solution.
If this functionality exists, would appreciate a point towards the relevant documentation :)

**Additional context**
Great library otherwise!

**Comment by plouc** [comment]
@jagdeepsb, it's feasible, if you have a color defined in the data, you can use the following `colors={node => node.data.color}`, it's not directly accessible via `node.color` because `node` is a computed version of a node, not the data you passed in.
