### ISSUE TITLE
Website crash on grid/axes details opening

### ISSUE THREAD

**Issue by hassan493** [plouc/nivo#2484]
**Describe/explain the bug**
Whenever we click to expand the object details inside grid/axes, the website just basically goes blank
Link: https://nivo.rocks/area-bump/

**To Reproduce**
Just go on the link and try to get details of any object in the GRID & AXES section.

**Expected behavior**
the details of the object should have displayed.

**ERROR MESSAGE**
Error: no value defined for property: truncateTickAt ({
  "key": "truncateTickAt",
  "flavors": [
    "svg"
  ],
  "help": "Top prevent the tick from overlapping truncating it",
  "type": "number",
  "required": false,
  "control": {
    "type": "range",
    "min": 0,
    "max": 100
  },
  "name": "truncateTickAt",
  "group": "Grid & Axes"
}, {
  "path": [
    "axisTop"
  ]
})
    at ControlsGroup.tsx:117:19

**Comment by plouc** [comment]
This has been solved.
