### ISSUE TITLE
bar custom color using data label nivo

### ISSUE THREAD

**Issue by gowsi-03** [plouc/nivo#2489]
Hi,

I Was just wondering if there is a way to set a color to a bar in a ResponsiveBar chart
For example:
import { type BarDatum } from '@nivo/bar'

const chartData: BarDatum[] = [
{
label: 'Jan',
value: 40,
},
{
label: 'Feb',
value: 60,
},
]

export default chartData

import { Meta, StoryObj } from '@storybook/react'
import { BarChart } from '@/components'
import chartData from './chartData'

const meta: Meta<typeof BarChart> = {
  title: 'BarChart',
  component: BarChart,
}

export default meta
type Story = StoryObj<typeof BarChart>
export const Default: Story = {
  name: '[0] default',
  render: (args) => (
    <div className="flex flex-col gap-4">
      <BarChart {...args} data={chartData} />
    </div>
  ),
}

import { type BarDatum, ResponsiveBar } from '@nivo/bar'

export interface Props {
  className?: string
  classNames?: { wrapper?: string }
  data: BarDatum[]
  indexBy: string
  enableLabel: boolean
  isInteractive: boolean
}
const BarChart = ({
  data,
  indexBy = 'label',
  enableLabel = false,
  isInteractive = false,
}: Props) => {
  return (
    <div className="h-96 w-auto">
      <ResponsiveBar
        data={data}
        keys={['value']}
        indexBy={indexBy}
        colors={(d) => d.data.color}
      />
    </div>
  )
}

export default BarChart

So i used indexBy proprty for barchart using this data label. I want color for specify label value if label=jan color shoud red if label=Feb color should green. How i customise color for my data label
![Capture](https://github.com/plouc/nivo/assets/105698064/7d28fa5a-f4c4-4223-a924-a21cdae0589c)

**Comment by plouc** [comment]
@gowsi-03, I'm going to close this issue for now, as it's really difficult to understand without formatting the code, please feel free to edit the issue and comment if you can provide an example and cleanup the description a bit.
