### ISSUE TITLE
Page break when expanding on  tool tip container

### ISSUE THREAD

**Issue by faizkhan12** [plouc/nivo#2491]
Hi,
Whenever I click on the tooltip and expand its container on the theme guide documentation I get an error and it completely breaks the website. Here's the error

Steps to reproduce: 
1. Go to  https://nivo.rocks/guides/theming/ 
2. Navigate to the bottom of the  page at tooltip 
3. Try to expand the tooltip container 
4. Errors are logged in the console and the whole website breaks.

Link - https://nivo.rocks/guides/theming/ 
![Screenshot from 2023-12-22 00-12-44](https://github.com/plouc/nivo/assets/39912483/5603ffdd-f187-4be9-ade1-f188f547f8c6)

**Comment by plouc** [comment]
This has been fixed.
