### ISSUE TITLE
Timeseries

### ISSUE THREAD

**Issue by vpotluri1217** [plouc/nivo#250]
Hi,
  How to create Time series on X-axis. I have  x labels as YYYYMM (201801, 201802, 201803) how to show them as time on bottom Axis as Jan 2018, Feb 2018 for line graph. I didn't find enough documentation on this. Can you please help me.

**Comment by plouc** [comment]
Unfortunately, it's not supported for now, see https://github.com/plouc/nivo/issues/225, I'm closing this as it's a duplicate.
