### ISSUE TITLE
Add Images as Background as option

### ISSUE THREAD

**Issue by nico-limo** [plouc/nivo#2500]
**Is your feature request related to a problem? Please describe.**
I am doing a treechart that works good but is require that use an especific images as background and not the colors that is provided. I tried to update the nodeComponent but if I touch that one, it break all the logics and features from the treeMap. Is a way to add the Images?

**Describe the solution you'd like**
Get the img as background

![image](https://github.com/plouc/nivo/assets/74354611/05e30d6a-4802-4260-9759-759b4444abe2)

**Additional context**
Here is some code I have
```ts
    <ResponsiveTreeMapHtml
      data={{ name: "MEMES", children: memesTop }}
      identity="name"
      value="value"
      leavesOnly={true}
      valueFormat=".02s"
      margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
      labelSkipSize={40}
      tile="binary"
      orientLabel={false}
      borderWidth={1}
      enableParentLabel={false}
      labelTextColor="transparent"
      nodeOpacity={1}
      // nodeComponent={({ animatedProps, node }) => {
      //   const { img } = node.data
      //   const { width, height } = animatedProps
      //   return (
      //     <div
      //       style={{
      //         width: animatedProps.width,
      //         height: animatedProps.height,
      //       }}
      //     >
      //       <Image src={img} width={400} height={400} alt="asd" />
      //     </div>
      //   )
      // }}
      tooltip={({ node }) => {
        const { name, value } = node.data as TokenType

        return (
          <div style={{ color: "#ffffff" }} className="rounded-xl bg-black p-4">
            <Text tag="h6">{name}:</Text>

            <Amount
              textStart="Market Cap:"
              type="price"
              amount={value.toString()}
            />
          </div>
        )
      }}
    />```

**Comment by plouc** [comment]
@nico-limo, I don't really plan to add this feature by default atm, but that's something you can do by overriding the default node component, you need to replicate what's implemented in the default component, please have a look at https://github.com/plouc/nivo/blob/master/packages/treemap/src/TreeMapHtmlNode.tsx. Also, I'd recommend to define your custom components outside your render function.
