### ISSUE TITLE
Error when expanding Axis options on website

### ISSUE THREAD

**Issue by scalabw** [plouc/nivo#2503]
**Describe/explain the bug**
An error appearing on the website when trying to expand any axis options "axisTop" "axisBottom" "axisLeft" "axisRight".
It make the website unusable and you are also not able to see the options for those axis.

**To Reproduce**
You can go to any graph on the website (such as this one: [Line](https://nivo.rocks/line/))
Then click on the option "axisTop" this will turn all the website blank and show an error in the console (as you can see in the screenshot section)

**Screenshots**
<img width="1718" alt="image" src="https://github.com/plouc/nivo/assets/22681512/92a83ac5-9752-493c-9e8f-2bf718ce4af8">
<img width="1715" alt="image" src="https://github.com/plouc/nivo/assets/22681512/dd8b6a13-d72c-4b3b-8172-712c40307ad0">

**Comment by msolano00** [comment]
I can confirm this.

**Comment by msolano00** [comment]
I can confirm this. @plouc

**Comment by scalabw** [comment]
I created a pull request that solve this issue #2504
