### ISSUE TITLE
defaultProps error

### ISSUE THREAD

**Issue by b310L** [plouc/nivo#2508]
I got this error in console :
Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

**Comment by nehalist** [comment]
The PR for this fix has already been merged; https://github.com/plouc/nivo/pull/2452 - unfortunately no new version has been released since.

**Comment by b310L** [comment]
> The PR for this fix has already been merged; #2452 - unfortunately no new version has been released since.

Although this new version is not released, is there a way to not show this error?

**Comment by b310L** [comment]
Even though the new version is not released, is there a way to prevent this error from appearing?

**Comment by plouc** [comment]
Should be fixed in `0.85.0`.
