### ISSUE TITLE
LineChart: any way to add a custom tooltip?

### ISSUE THREAD

**Issue by benzitohhh** [plouc/nivo#251]
Any way to add a custom tooltip for Line chart?

i.e. for Bar chart, we can use

```
      <ResponsiveBar
        tooltip={tooltip}
      />
```

Would be really useful to have something similar for Line.

Thanks!

**Comment by superplussed** [comment]
(Love the library, don't mind my gentle criticism) . But it does seem a bit crazy that it's been added for pie chart and not other chart types.  The good news is we can use the pie chart PR as a template for adding it to other charts:

https://github.com/plouc/nivo/commit/d3734428cee364f4eb67af5c0f4c572b9973dc31

**Comment by plouc** [comment]
Support for line has been merged.
I close this issue in favor of https://github.com/plouc/nivo/issues/192.

**Comment by ilirosmanaj** [comment]
@plouc, is there a demo implementation of tooltip for the responsive line? Trying to implement it, but the function never gets called. I saw similiar problems [in this issue](https://github.com/plouc/nivo/issues/390)

**Comment by mhsnprvr3** [comment]
@benzitohhh https://nivo.rocks/storybook/?path=/story/bar--custom-tooltip

**Comment by shreyakupadhyay** [comment]
A better reference to this. https://nivo.rocks/storybook/?path=/story/line--custom-tooltip

Custom tooltip specifically for LineChart.
