### ISSUE TITLE
Update in Colors package the d3-scale-chromatic dependency to version 3.0.0.

### ISSUE THREAD

**Issue by rictimpmi** [plouc/nivo#2517]
https://github.com/plouc/nivo/blob/bc18832351f6e1bc70ec189ed5efd1fe96e0a654/packages/colors/package.json#L31

In order to prevent vulnerabilities warning on Node v20.9.0

**Comment by plouc** [comment]
It's already `^3.1.0`, https://github.com/plouc/nivo/blob/master/packages/colors/package.json#L29, but it hasn't been published yet.
