### ISSUE TITLE
Providing a function in colorBy in ResponsiveLine throws a bunch of prop types warnings

### ISSUE THREAD

**Issue by Rodre** [plouc/nivo#252]
Im providing a function like this:

`colorBy={d => d.color}`

It works, but I get some prop types warnings

Warning: Failed prop type: The prop `data[0].fill` is marked as required in `BoxLegendSvg`, but its value is `undefined`.

Warning: Failed prop type: The prop `data[0].fill` is marked as required in `LegendSvg`, but its value is `undefined`.

Warning: Failed prop type: The prop `fill` is marked as required in `LegendSvgItem`, but its value is `undefined`.

Warning: Failed prop type: The prop `fill` is marked as required in `SymbolCircle`, but its value is `undefined`.

**Comment by Rodre** [comment]
If I remove the legends property the warnings disappear.

**Comment by jcanady20** [comment]
Thank you for reporting this issue, I just ran into this as well.

**Comment by plouc** [comment]
@Rodre, if you try it on the website, it works as expected, without warning, could you please provide an example (on codesandbox for example)?

**Comment by plouc** [comment]
I close this issue as it's been inactive for a while, feel free to comment/create a new one if you can provide an example.
