### ISSUE TITLE
Theming website - expanding tooltip crashes the web page

### ISSUE THREAD

**Issue by LaurelineP** [plouc/nivo#2520]
## Context: nivo website theming
https://nivo.rocks/guides/theming/
### Issue: 
When reaching out for the tooltip customisation, the web page crashes
### Scenario:
- go to the [theming page of the  website](https://nivo.rocks/guides/theming/)
- scroll down to the bottom to reach the `tooltip` section
- expand the tile `tooltip object optional`
- will reveal another expandable section `tooltip.container`
- click on it
     _➡️ this displays a blank page_
     _➡️ this logs an error in the console_
    
![image](https://github.com/plouc/nivo/assets/32878345/2df0f8de-4771-44c0-bd37-5a6c23ca04c0)

 ### Personal Setup
 - OS: Mac
 - Browser: Chrome
 - Version: 121.0.6167.184
=

**Comment by scalabw** [comment]
I opened a PR to solve that here: https://github.com/plouc/nivo/pull/2521

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/2521 thanks to @scalabw.
