### ISSUE TITLE
 c.scaleOrdinal is not a function

### ISSUE THREAD

**Issue by mrkirchner** [plouc/nivo#2535]
**Describe/explain the bug**
Upgrading from 0.84.0 to 0.85.1 and am getting scaleOrdinal is not a function on a pie component.  We are using nextjs.

**To Reproduce**
I tried adding a codesandbox but couldnt repo it using that and only react and your library so it has to be nextjs related.  

` <Pie
      data={data}
      height={200}
      width={380}
      margin={{
        top: 0,
        right: 20,
        bottom: 0,
        left: -120,
      }}
      key="value"
      colors={{ scheme: "paired" }}
      innerRadius={0.5}
      enableArcLabels={false}
      enableArcLinkLabels={false}
      sortByValue={true}
      legends={[
        {
          anchor: "top-right",
          direction: "column",
          justify: false,
          translateX: 0,
          translateY: 0,
          itemsSpacing: 2,
          itemWidth: 100,
          itemHeight: 18,
          itemTextColor: "#999",
          itemDirection: "left-to-right",
          itemOpacity: 1,
          symbolSize: 12,
          symbolShape: "circle",
          effects: [
            {
              on: "hover",
              style: {
                itemTextColor: "#000",
              },
            },
          ],
        },
      ]}
    />`

**Expected behavior**
To render pie graph without error.

Console

`node_modules/@nivo/core/dist/nivo-core.cjs.js (1:10311) @ scaleOrdinal
 ⨯ TypeError: c.scaleOrdinal is not a function
    at eval (webpack-internal:///./node_modules/@nivo/core/dist/nivo-core.cjs.js:500:37)
    at ./node_modules/@nivo/core/dist/nivo-core.cjs.js (/Users/user/Workspaces/optio/optio/.next/server/vendor-chunks/@nivo.js:70:1)
    at __webpack_require__ (/Users/user/Workspaces/optio/optio/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/@nivo/pie/dist/nivo-pie.cjs.js:2:56)
    at ./node_modules/@nivo/pie/dist/nivo-pie.cjs.js (/Users/user/Workspaces/optio/optio/.next/server/vendor-chunks/@nivo.js:90:1)
    at __webpack_require__ (/Users/user/Workspaces/optio/optio/.next/server/webpack-runtime.js:33:42)
`

**Additional context**

**Comment by plouc** [comment]
Unless it's reproducible, we won't be able to investigate the issue.

**Comment by plouc** [comment]
It also seems possible to setup next.js in codesandbox.

**Comment by mrkirchner** [comment]
I updated a repo (https://github.com/mrkirchner/nivo-85.1) and made a codesandbox 

https://codesandbox.io/p/github/mrkirchner/nivo-85.1/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltmjf9nb00062e668syn7imc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltmjf9nb00022e66rrzfdifd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltmjf9nb00042e66xvbrutmz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltmjf9nb00052e66qg7f9h40%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltmjf9nb00022e66rrzfdifd%2522%253A%257B%2522id%2522%253A%2522cltmjf9nb00022e66rrzfdifd%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltmjf9nb00052e66qg7f9h40%2522%253A%257B%2522id%2522%253A%2522cltmjf9nb00052e66qg7f9h40%2522%252C%2522activeTabId%2522%253A%2522cltmjhrf700k02e66watq1w94%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cltmjhrf700k02e66watq1w94%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltmjf9nb00042e66xvbrutmz%2522%253A%257B%2522id%2522%253A%2522cltmjf9nb00042e66xvbrutmz%2522%252C%2522activeTabId%2522%253A%2522cltmjhom700gw2e664dqts5td%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmjf9nb00032e66z55rwph3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltmjfa75000nddk68o1wembv%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cltmjgbnm00562e66l6vhcus3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltmjhom700gw2e664dqts5td%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

Only changes in Nextjs are located in next.config.mjs where we had added

`  experimental: {
    esmExternals: "loose",
  },
  transpilePackages: ["@nivo"], // https://github.com/plouc/nivo/issues/2310`

**Comment by plouc** [comment]
Thank you @mrkirchner, it's unfortunately related to https://github.com/plouc/nivo/issues/2310, and I don't have a fix for that atm. I'm closing in favor of the other one, but you might want to share your sandbox in the other issue.
