### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by alexaandig** [plouc/nivo#2546]
Can someone please help me with this. While updating the package.

Server Error
Error: require() of ES Module D:\Documents\wp-dl\dev\web\node_modules\d3-interpolate\src\index.js from D:\Documents\wp-dl\dev\web\node_modules\@nivo\core\dist\nivo-core.cjs.js not supported.
Instead change the require of index.js in D:\Documents\wp-dl\dev\web\node_modules\@nivo\core\dist\nivo-core.cjs.js to a dynamic import() which is available in all CommonJS modules.

**Comment by plouc** [comment]
It's a duplicate of https://github.com/plouc/nivo/issues/2310.
