### ISSUE TITLE
Test ids for bars in ResponsiveBar

### ISSUE THREAD

**Issue by jean-maradjx** [plouc/nivo#2547]
Hi! Could someone provide some examples how to add a test id to the bars or a bar graph?
I tried using the layers option but that removes the tooltip and onClick behavior, I'm guessing I would have to pass it again somehow.

```
<ResponsiveBar
          layers={[
            'grid',
            'markers',
            ({ bars }) => (
              <>
                {bars.map((bar) => (
                  <g key={bar.key} transform={`translate(${bar.x},${bar.y})`}>
                    <rect
                      width={bar.width}
                      height={bar.height}
                      fill={bar.color}
                      data-testid={`existing-bar-${bar.data.index}`}
                      rx="4"
                      ry="4"
                      strokeWidth="0"
                      focusable="false"
                    />
                  </g>
                ))}
              </>
            ),
            'axes',
            'legends',
          ]}
          .....
```

**Comment by plouc** [comment]
This is currently not supported, but you could customize the `barComponent`, in order to maintain the existing feature, you might want to check the default implementation: https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.tsx.

**Comment by plouc** [comment]
I'm closing this issue for now as I think the default implementation should be enough to restore these features.
