### ISSUE TITLE
Sankey Diagram Links don't show with Dark Theme

### ISSUE THREAD

**Issue by dperconti** [plouc/nivo#2550]
1. Go to [https://nivo.rocks/sankey/](https://nivo.rocks/sankey/)
2. Click on `dark`
3. See that links do not appear

**Expected behavior**
Links still appear

**Screenshots**

<img width="2056" alt="Screenshot 2024-03-26 at 4 48 04 PM" src="https://github.com/plouc/nivo/assets/1742882/a8c5d9a0-ccce-475f-a678-fef4caf1f2f5">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 123.0.6312.59

**Comment by plouc** [comment]
@dperconti, this is not really a bug, it's just that the links use a `multiply` blend mode by default which doesn't work well on dark backgrounds, it's a playground, not a regular website, so the charts aren't adjusted automatically, it can be easily changed via `linkBlendMode`.
