### ISSUE TITLE
Customizing Area Bump Chart Colors Based on Ending Date in Data Series

### ISSUE THREAD

**Issue by shellyscheng** [plouc/nivo#2557]
Hi, I'm trying to use the area bump chart with custom arrays of colors: ["colorA", "colorB", "colorC", ..., "colorZ"]. How can I assign colors based on the ending date (2006's data in the screenshot below) instead of the starting date (2000's data)?

![Screenshot 2024-04-02 at 3 01 13 PM](https://github.com/plouc/nivo/assets/22440246/4f0a5cf0-a52a-400b-ace4-4e4c749dbb6e)

Version: 0.85.1

**Comment by plouc** [comment]
@shellyscheng, I replied in the discussion you also opened.

There's no builtin support for this, what you could do is to first sort the data by the value for 2006, the colors aren't assigned according to the first values, but according to the order of the input, so this would work.
