### ISSUE TITLE
Line Chart revert yaxis

### ISSUE THREAD

**Issue by Panczo** [plouc/nivo#256]
Hi,

I've been looking for awhile but without any results. Is there a way to change order of y axis?
Currently the numbers on this axis start from 0 from bottom and then go up.
What I'm looking for is that numbers starts from 0 from top on y axis and then go down.

Thanks for any help.

**Comment by plouc** [comment]
Hi @Panczo,
You can play with `(min|max)Y`.

**Comment by plouc** [comment]
You can also test it on the demo website, http://nivo.rocks/line

**Comment by Panczo** [comment]
But even when I playing around with these options numbers on yaxis start from bottom to top 0,10, 20 etc.
Is there a way to revert it? That they will start on top from 0 and then they will move down?

**Comment by plouc** [comment]
<img width="788" alt="capture d ecran 2018-08-08 a 06 31 15" src="https://user-images.githubusercontent.com/501642/43803778-b873c33e-9ad4-11e8-89e4-0f9fc810d1c8.png">

**Comment by plouc** [comment]
not sure I understand :/

**Comment by Panczo** [comment]
![line1](https://user-images.githubusercontent.com/4106478/43804130-3edb1d26-9a9b-11e8-81b8-b5fb7f144aa4.png)

This is what I wanted and thanks to your advise I've achieved :)

**Comment by plouc** [comment]
I'm glad to read it! funny chart, it looks like a subway map :)

**Comment by Panczo** [comment]
Haha true, I have to work on it slightly more.
