### ISSUE TITLE
Add support for hierarchy/dendrograms.

### ISSUE THREAD

**Issue by CinchBlue** [plouc/nivo#2562]
**Is your feature request related to a problem? Please describe.**
I am evaluating UI libraries to use and I have noticed that `nivo` does not support hierarchy diagrams beyond `d3-hierarchy` TreeMap's.

**Describe the solution you'd like**
Add support for dendrograms.

**Describe alternatives you've considered**
See: [@visx/hierarchy](https://airbnb.io/visx/docs/hierarchy). 

**Additional context**
N/A

**Comment by plouc** [comment]
@CinchBlue, I'm currently [working on a `@nivo/dendogram` package](https://github.com/plouc/nivo/pull/2582)
