### ISSUE TITLE
Add Icons as Labels

### ISSUE THREAD

**Issue by sambowenhughes** [plouc/nivo#2563]
**Is your feature request related to a problem? Please describe.**

I would love to be able to add an Icon, parent label, and value inside a tree node. See screenshot:

![CleanShot 2024-04-15 at 10 10 38@2x](https://github.com/plouc/nivo/assets/23152623/4cbf59ea-6ae0-48b3-b71c-491575753b2c)

**Describe the solution you'd like**

More configurations to customize the inner tree node. Adding icons and parent labels. 

**Describe alternatives you've considered**

**Additional context**

**Comment by plouc** [comment]
@sambowenhughes, this component already has a lot of props, it's impossible to cover every needs, and it would make the API and the implementation quite complex.

This is achievable using a custom component though.
