### ISSUE TITLE
BarChart setting enableTotals not working

### ISSUE THREAD

**Issue by tyler-willowtree** [plouc/nivo#2565]
**Describe/explain the bug**
Using either ResponsiveBarChart or BarChart, when setting `enableTotals` nothing happens. IDE shows error `Property enableTotals does not exist on type IntrinsicAttributes & ResponsiveBarSvgProps<BarDatum>`

This is using the most recent version.

**To Reproduce**
Take the example you have on the website or any BarCahrt and add `enableTotals={true}`

**Expected behavior**
The example on your website is working so I expect this functionality to work as intended.

**Screenshots**
![Screenshot 2024-04-16 at 5 43 22 PM](https://github.com/plouc/nivo/assets/54323980/7ffa20ba-5223-46a2-bcb8-43300d17dcff)

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.4.1
 - Browser: All
 - Version: All

**Comment by plouc** [comment]
That's because it hasn't been released yet, but the demo website is deployed continuously.

**Comment by 2hakjoon** [comment]
@plouc 
Could you please provide an estimate for when this feature will be released?

**Comment by tahos81** [comment]
Looking forward to this feature @plouc

**Comment by plouc** [comment]
It's been released in `0.86.0`.

**Comment by mountainash** [comment]
@plouc does `enableTotals` come with an associated formatter like `labels` does? I tried the obvious [eg. `totals={(d) => `$${d.value}`}`] but it doesn't seem to work.

**Comment by plouc** [comment]
@mountainash, no, it's going to use the format defined via `valueFormat`.
