### ISSUE TITLE
Changing Pie legend text color

### ISSUE THREAD

**Issue by PattieC4ke** [plouc/nivo#257]
How do I change the text color in the legend of the nivo/pie chart?

**Comment by PattieC4ke** [comment]
Thank you!

**Comment by Taelkir** [comment]
If anyone finds this via Google like I did and it isn't working for them (I was using a ResponsiveLineChart - not sure if that was my issue), then maybe this will help:
```
legends={[
	{
		"anchor": "top-right",
		"direction": "column",
		"translateY": -25,
		"translateX": 100,
		"itemWidth": 100,
		"itemHeight": 48.2,
		"symbolSize": 12,
		"symbolShape": "circle",
		"itemTextColor": "#eee", // <= this worked for me in the end
	},
]}
```

**Comment by RomainD2** [comment]
I tried both itemTextColor and textColor, and nothing is working to change the legend text color. Only the on: hover text color is working...

**Comment by wyze** [comment]
You can pass it via the theme: `theme={{ legends: { text: { fill: 'tomato' } } }}`

I just put a PR in that converted the package to typescript. Once merged and released, you will be able to use `itemTextColor` again.

**Comment by ewmiller** [comment]
> You can pass it via the theme: `theme={{ legends: { text: { fill: 'tomato' } } }}`
> 
> I just put a PR in that converted the package to typescript. Once merged and released, you will be able to use `itemTextColor` again.

@wyze you're a lifesaver! This is the only solution that worked for me. Appreciate it.

**Comment by thenengah** [comment]
@ewmiller nice! tomato is now by fav html color.

We are using:

```
    "@nivo/bar": "^0.69.0",
    "@nivo/core": "^0.69.0",
    "@nivo/pie": "^0.69.0",
```
And this works:

```
theme={{ legends: { text: { fill: 'tomato' } } }}
```

We cannot upgrade fully yet because of breaking changes, and we have to update to fix security vulns.
