### ISSUE TITLE
Stream stack tooltip does not display original values in stack tooltip

### ISSUE THREAD

**Issue by plouc** [plouc/nivo#26]
Values displayed in stack tooltip are impacted by `stackOffset`, for example the `expand` offset cause values to be displayed as ratio (0~1).

**Comment by bluetidepro** [comment]
Having this same issue, too. Would love to see this get fixed.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/commit/05fbcc9fadf6d540f6788de5cb98072b92cdd103
