### ISSUE TITLE
The arc link labels for ResponsivePie overflow the drawable area.

### ISSUE THREAD

**Issue by tabarra** [plouc/nivo#2600]
**Describe/explain the bug**
The arc link labels for ResponsivePie overflow the drawable area.

**Expected behavior**
The pie should resize to accommodate the arc link labels, or the link labels should reorganize in a way that fit in the area.

**Screenshots**
![image](https://github.com/plouc/nivo/assets/1808295/07ce6a22-95ec-4793-aca9-ef46da428beb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 126

**Additional context**
Using `@nivo/pie` version 0.87

**Comment by plouc** [comment]
@tabarra, I agree this would be ideal to have everything automatically arranged, but it's quite complex to implement and I don't plan to implement this atm. For now, users need to use the margins.

**Comment by tabarra** [comment]
Understandable, thank you.
