### ISSUE TITLE
Add a references/gallery page to the website

### ISSUE THREAD

**Issue by plouc** [plouc/nivo#261]
- **state of js 2017** [website](https://2017.stateofjs.com/) | [repo](https://github.com/StateOfJS/StateOfJS)
- **batbstats** [website](https://batbstats.trevorblades.com/skaters) | [repo](https://github.com/trevorblades/batbstats)
- **spacetime reviews** [website](https://spacetime.graph.zone/) | [repo](https://github.com/johnymontana/spacetime-reviews)

**Comment by Larissagilliane** [comment]
I can help with that

**Comment by Larissagilliane** [comment]
@plouc  do you want a page on the site that has projects that were references to nivo, such as projects that inspired?
