### ISSUE TITLE
Nivo/line, stack line does not match the values in the graph.

### ISSUE THREAD

**Issue by JhsK** [plouc/nivo#2613]
A stack line graph was implemented using nivo/line, and even if the value of the data put in the graph is normally entered, the graph does not fit the numerical value. 

For example, even if I set a value of 2739, the graph seems to be drawn to 27390. The weird thing is that only one of the 3 line graphs seems to be treated strangely. 

I share it so that you can check it in the codesandbox below. 
You can check the graph of the x-axis other, norway in the example graph.

In a shared environment, you have configured it based on the example code of the nivo official document.

codesandbox - [example](https://codesandbox.io/p/devbox/reverent-violet-m833sc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxvfo0xu00073b6pzyu1rz52%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxvfo0xu00023b6p1ys4nrd4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxvfo0xu00043b6p61qn0bk9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxvfo0xu00063b6paxel431r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxvfo0xu00023b6p1ys4nrd4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvfo0xu00013b6pau2gwmdd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxvfo0xu00023b6p1ys4nrd4%2522%252C%2522activeTabId%2522%253A%2522clxvfo0xu00013b6pau2gwmdd%2522%257D%252C%2522clxvfo0xu00063b6paxel431r%2522%253A%257B%2522id%2522%253A%2522clxvfo0xu00063b6paxel431r%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxvfvzvn00k73b6p43eh9qjy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxvfvzvn00k73b6p43eh9qjy%2522%257D%252C%2522clxvfo0xu00043b6p61qn0bk9%2522%253A%257B%2522id%2522%253A%2522clxvfo0xu00043b6p61qn0bk9%2522%252C%2522activeTabId%2522%253A%2522clxvfva2h00g03b6panpcuj5p%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxvfva2h00g03b6panpcuj5p%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by tkonopka** [comment]
Hi @jhsK. Your codesandbox has a `yScale` configured with `stacked: true` and that makes the y axis show cumulative values, so a data value 2739 may well appear drawn much higher, in your case near 27390. Your other lines also follow this behaviour (to see this in the codesandbox, remove the entry labelled "other" - the lines will then not be squished at the bottom and it will become clearer that all the lines are treated consistently). You may want to consider setting `stacked: false` to draw lines on a regular yScale. HTH

**Comment by plouc** [comment]
Thank you for the explanation @tkonopka.

**Comment by JhsK** [comment]
@tkonopka Thank you so much, I didn't understand the stack option and was using it!
