### ISSUE TITLE
@nivo/sankey turn off node legend text and custom nodes

### ISSUE THREAD

**Issue by shellyscheng** [plouc/nivo#2624]
**Is your feature request related to a problem? Please describe.**

Is there a way to hide node labels on the bottom right corner?
<img width="800" alt="Screenshot 2024-07-23 at 10 39 10 PM" src="https://github.com/user-attachments/assets/e31bcbf9-b108-44d4-a2fa-8802cfd1a206">

**Describe the solution you'd like**

I'm working on a chart which I set the `nodeThickness` to be 0, so I don't need the legend box at the bottom right corner. Would appreciate it if there's a way to turn it off. 

Thanks a lot!

**Describe alternatives you've considered**

**Additional context**

**Comment by plouc** [comment]
@shellyscheng, I think you posted before the upload of the screenshot could complete.

**Comment by shellyscheng** [comment]
@plouc opps! I just updated it! I figured it out by giving `legends={[]}`. 

But now I have encountered two different questions for labels: 
1. How can I break labels into two lines? for the label on the top, I envision it be 
```Category 1
         x %
```
2. How do we know the precise position of the node? Or customize node labels to be more complex, such as including images.

for my use case, I'm hoping to add two images at the center of the bottom two nodes
![Screenshot 2024-07-24 at 1 29 10 AM](https://github.com/user-attachments/assets/9d0f4a44-8436-471e-9dbb-3f920e26c6f1)

**Comment by plouc** [comment]
@shellyscheng, line breaks are not supported (SVG limitation), regarding customization, it's doable if you're familiar with SVG, while not exactly the same, you can have a look at this example: https://codesandbox.io/p/sandbox/sankey-custom-b4iyi?file=%2Fsrc%2FApp.js which uses a custom layer for the nodes, it could be a good start, but you'll have to figure out things by yourself as custom layers aren't documented.

**Comment by shellyscheng** [comment]
@plouc, that's super helpful! I have a follow-up question about using Nivo with custom layers. Once I added a custom layer for the nodes, the original labels set within the Nivo config get overwritten (pic 1 is Nivo label settings, pic 2 with CutomNodeLayer). Is there a way to keep both the original labels and my custom elements? Additionally, the custom node layer seems to have a very fixed width restriction, which is not ideal for my labels. 

here's my code:
`const StyledHeadshot = styled(Headshot)`
  width: 100px;
  max-width: 100%;
  position: relative;
  margin: 0 auto;
  display: flex;
  margin-top: 0.5rem;
`

const Label = styled.div`
  color: ${(props) => props.color};
  margin: 0 auto;
  wrap: nowrap;
`

const CustomNode = ({ node }) => {

  return (
    <g transform={`translate(${node.x0}, ${node.y0})`}>
      {node.id === "target 1" || node.id === "target 2" ? (
        <foreignObject width={node.width} height={node.height}>
          <div
            style={{
              width: node.width,
              height: node.height,
              boxSizing: "border-box",
              color: "black",
              textAlign: "left",
              padding: "9px",
              fontSize: "12px",
              backgroundColor: neutrals.white,
            }}
          >
            <StyledHeadshot
              key={node.id}
              $imgSrc={imgUrl}
            />
          </div>
        </foreignObject>
      ) : (
        <foreignObject width={node.width + 100} height={node.height}>
          <Label
            style={{
              width: 21,
              height: 0,
              boxSizing: "border-box",
              backgroundColor: node.color,
              lineHeight: "1.5rem",
              fontSize: "18px",
              fontStretch: "75%",
              fontWeight: "700",
            }}
          >
            {node.id}
          </Label>
        </foreignObject>
      )}
    </g>
  )
}`

![Screenshot 2024-07-26 at 11 47 55 AM](https://github.com/user-attachments/assets/40422f2d-c7af-44ef-9708-b8b31cdd9eb7)

![Screenshot 2024-07-26 at 11 48 10 AM](https://github.com/user-attachments/assets/6944c578-4917-48f8-8f19-69d013352943)

**Comment by plouc** [comment]
@shellyscheng, you can pass the following layers: `'links' | 'nodes' | 'labels' | 'legends'`.
It's not possible to use a custom layer only for certain elements as it replaces all.
As it's SVG, there are no line breaks, you could also use a custom layer for labels if you wish to customize them.

**Comment by shellyscheng** [comment]
Thank you, @plouc. With `customNodeLayer`, how should we enable the node tooltips? The `nodeTooltip` option doesn't work anymore. And I wish it to be the same style as my `linkTooltip `

``` 
nodeTooltip={({ node }) => (
              <CustomTooltipContainer>
                <strong>{node.label}</strong>: {node.nValue}% of total voters
              </CustomTooltipContainer>
            )}
```
