### ISSUE TITLE
isInteractive hover functionality stops working when using `cellComponent` prop for a custom cell

### ISSUE THREAD

**Issue by antpacespothero** [plouc/nivo#2625]
**Describe/explain the bug**
When using the `cellComponent` prop to implement a custom cell component, the isInteractive hover highlighting functionality stops working. 

**To Reproduce**
Add a custom cellComponent:
https://nivo.rocks/storybook/?path=/story/heatmap--custom-cell-component

**Expected behavior**
When specifying a cellComponent, interactivity should still work.

**Comment by plouc** [comment]
@antpacespothero, if you want to preserve the functionality, you'll have to replicate the [default behavior](https://github.com/plouc/nivo/blob/master/packages/heatmap/src/HeatMapCellRect.tsx), as you provide your own implementation, this is expected.
