### ISSUE TITLE
Line API example doesn't work

### ISSUE THREAD

**Issue by xapple** [plouc/nivo#263]
Hi,

I'm looking for a JS charting library to start a new project, so I'm quickly looking though the options available and clicking on examples to decide if yes or no I investigate it further.

When I evaluated yours, the first example I piked here http://nivo.rocks/line/api didn't work and returned 404. This is a pity because it's the kind of thing that will make prospective users jump to the next library very quickly.

The specific error messages was:

    {
      "errors": [
        "\"enableArea\" is not allowed (enableArea)",
        "\"areaOpacity\" is not allowed (areaOpacity)"
      ]
    }

**Comment by xapple** [comment]
I think it's a great little project, thank you for releasing it for free, and I understand how a developer has to prioritize his time, of course.

Maybe at a later stage you will complete the http rendering api and that will be nice. In the meantime, my analysis is simply the following: until it is done you are doing yourself a disservice from a PR point of view from listing it in the examples and thus having a dysfunctional example in your documentation.

My humble advice is to list it there only once it is done.

**Comment by alcmacys** [comment]
The project is awesome and grateful for you spending the time and making it open source for everyone

I'm also facing the issue reported by the OP. I think Nivo has the most comprehensive and easy to use graphing documentation online with the rendering api built in. But as @xapple mentioned, it might be better to mark the page as "under construction" instead of putting it out there when its incomplete, as it would likely causes confusion. 

Thanks again and keep up the awesome work!

**Comment by gavinsharp** [comment]
I found myself in a similar situation. I'm evaluating libraries for generating line charts. Until I found this thread it was not at all obvious that the references to "API" that I found in the docs (e.g. http://nivo.rocks/line/api) were a reference to the HTTP API, as opposed to the library's API (even though I can see now that the main heading says "HTTP API", the link on the left sidebar just says "API" or "Line API", which is confusing). I appreciate that maintaining this package is a big chunk of work, but I can't help but feel that adding a bit of clarity in the docs about what the HTTP API is (and it's state of maintenance) might help avoid people like me getting confused :)

**Comment by plouc** [comment]
@gavinsharp, it's mentioned in both the *about* and *FAQ* pages.

**Comment by gavinsharp** [comment]
> @gavinsharp, it's mentioned in both the _about_ and _FAQ_ pages.

I don't typically look at those other pages when quickly browsing a new library's docs. Probably the single thing you could do to help clarify from my perspective is change the "API" button in the left nav to say "HTTP API" (or be clearer in some other way that it's different).

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/512/commits/a52a9c84fff56a866981b5dbe03219436544d663 (not deployed/published yet), I also updated the documentation to use `http api` instead of `api` which might be confusing otherwise.
