### ISSUE TITLE
Bug: Bars with zero value are not able to render labels

### ISSUE THREAD

**Issue by tigerabrodi** [plouc/nivo#2646]
Please 🫠 , don't close this issue like done with #2172.

It seems like the issue in https://github.com/plouc/nivo/issues/874 is back. I am unable to render a zero above the bar when it's value is 0. The fields with value 0 get excluded completely. I'd assume something like `!{the value}` is done in the source which means if the value is the number 0, the expression `!0` results in true.

What do I expect?

Explicitly check if undefined, otherwise if the value number 0, it should be totally fine to include the field!

Looking in the source code, the function `filterZerosIfLog` in the file `packages/bar/src/compute/stacked.ts` seems suspicious. But I'd need to take a deeper look to properly fix this.

Pinging people who had this issue in the past, and it doesn't seem to be resolved yet, or it's back!

cc @RobertHosking @dooleyb1

**Comment by plouc** [comment]
Labels aren't rendered, as a bar with a value of 0 is not rendered, it cannot be rendered as visually 0 shouldn't take any space, however it's included in the legend, which is what #874 was about.

I don't plan to support rendering labels for 0 values.
