### ISSUE TITLE
React 18 suport

### ISSUE THREAD

**Issue by alinealvesvianna** [plouc/nivo#2650]
I updated my project to:  
``` 
"react": "^18.3.1",
 "react-dom": "^18.3.1",
```
I'm getting the following error when hovering over the ResponsiveLine graph:
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/8ff7f42c-3ba8-45d8-a7f2-b4f1ffdedd92">

When I click on the error in the console to see where it comes from, it points to an error in the tooltip script:
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/2fd1def3-6f4b-415d-923c-710f936dad7b">

I'm using the nivo version:

```
   "@nivo/core": "^0.87.0",
    "@nivo/line": "^0.87.0",
    "@nivo/pie": "^0.87.0",
```

Can you help me, please?

**Comment by plouc** [comment]
Without a reproducible example, such as a codesandbox, I don't think anybody will be able to help.
I'm closing this for now, please feel free to ping me if you create one.

**Comment by plouc** [comment]
This could be similar to https://github.com/plouc/nivo/issues/2630.
