### ISSUE TITLE
Swarmplot is creating inacurate point with low value

### ISSUE THREAD

**Issue by lflangis** [plouc/nivo#2654]
**Describe/explain the bug**

Hi, 

I'm currently using Nivo to display 400 data that goes to 0.00 to 6.029 in some case. I saw that Nivo is having trouble placing data that are near zero, placing them in the negative space. 

![image](https://github.com/user-attachments/assets/47068bf5-c6cc-4373-ae5e-22e62db693ec)

It also seems to have trouble placing data at the correct y value. In those screenshots, 0.01 is placed lower thant 0.0

![image](https://github.com/user-attachments/assets/d4cdcd26-7ef3-4751-a1fb-ebac22d95573)
![image](https://github.com/user-attachments/assets/6c1f6f45-c7fc-49f0-8170-4be8d79ffb99)

This issue is give my trouble to create a custom layer that display a BoxPlot, since the quartile position can be inacurate.
 

**To Reproduce**
1. Go to ['sandbox'](https://codesandbox.io/p/sandbox/xhqxry)
2. See the graph

**Expected behavior**
SwarmPlot should be able to correctly place the point. I expect that 0.0 to be lower that a point with 0.1 value. Those value should be place above the 0 axis.

**Comment by jthib077** [comment]
@plouc thanks for your input! I work with lflangis and we will attempt to play with the force strength. 

We will also perhaps explore a scatterplot but are you aware if it is possible to have categorical variables in your scatterplot? Essentially, we have many Y-axis data but no defined X-axis variable other than the 2 categories (T21 and control) seen in the screenshot above. Something like this:

![image](https://github.com/user-attachments/assets/297e894c-33be-49b8-8955-4640ee747b54)
