### ISSUE TITLE
Waiting on release: v0.87.0 is behind documentation nivo.rocks

### ISSUE THREAD

**Issue by jonasbuechel** [plouc/nivo#2664]
### Issue: Release v0.87.0 does not include Radar's onClick property
Nivo.rocks seems to be ahead of the release. I stumbled into it with the onClick property of the Radar component 
https://nivo.rocks/radar/

The actual Release v0.87.0 does not include the property, but master branch includes https://github.com/plouc/nivo/pull/2601 already.

Would it be possible to have another release as a quickfix? In the future it would be awesome to @next releases or similar.

As a workaround I tried to directly install it via `npm install 'https://gitpkg.vercel.app/plouc/nivo/packages/radar?master` but ended in an error `npm error Unsupported URL Type "workspace:": workspace:*` even if I don't have a workspace defined in package.json or using any packages with a workspace prefix.

**Comment by DaniWyrd** [comment]
We would like to build an interactive radar component. Please release the onClick property 🙏

**Comment by plouc** [comment]
v0.88.0 has been released.
