### ISSUE TITLE
new `readonly` props is a breaking change

### ISSUE THREAD

**Issue by pstephenwille** [plouc/nivo#2672]
**Thanks for using nivo**
This change is now breaking us and i wondered if it should have been **semver'd** as a Major version bump.

https://github.com/plouc/nivo/pull/2494/files

**Comment by plouc** [comment]
@pstephenwille, as not all packages were migrated to TS, I'm still using sub 0 version numbers, which means minor versions might contain some braking changes, that's an approach other libraries used in the past as well, but it's confusing.

I might move to "regular" semver in the future, but I'm closing this issue as there's not much I can do about this specific issue now that it's been released.
