### ISSUE TITLE
Automatic legend positioning

### ISSUE THREAD

**Issue by borisrorsvort** [plouc/nivo#274]
In the case of 
<img width="614" alt="screen shot 2018-08-26 at 00 38 18" src="https://user-images.githubusercontent.com/39081/44623202-09bbde00-a8c9-11e8-9fb0-4253c777573e.png">

Is there a way to automatically position the legend outside the graph? I fail to see when is it a good idea to display the legend on the graph. It there a way to use the component outside the graph component to place it where we want?

I feel some docs would be useful to add about that in the legend guide

**Comment by plouc** [comment]
Hi @borisrorsvort, not automatically as it would rely on the DOM, and will break support for http rendering API.

This part of the doc explain how to position legend:

<img width="826" alt="legend_position" src="https://user-images.githubusercontent.com/501642/44623333-cf246680-a905-11e8-8dbb-d71d0d1276a5.png">

however, it has to be inside the component, the [demo](http://nivo.rocks/line) of this component shows how to place it outside the chart.

**Comment by plouc** [comment]
yes, you'll have to add this height to your global chart height.

**Comment by plouc** [comment]
...and use a bottom margin to prevent the chart from growing.

**Comment by plouc** [comment]
In fact you don't have to translate the legend to place it under the chart, `anchor: 'bottom'` + `margin: { bottom: graphSeriesData.length * 20 }` on the chart itself should be enough.

**Comment by borisrorsvort** [comment]
Its not enough: you need to add the calculated height of the legend to the height, to the graph margin and the translateY of the legend.

Now I’m thinking that if you want responsive multi rows legend, how would you do that?

<img width="573" alt="screen shot 2018-08-26 at 11 09 45" src="https://user-images.githubusercontent.com/39081/44626659-92b23400-a920-11e8-9799-21e99e81a8ee.png">

**Comment by plouc** [comment]
For such a case, maybe it's better to implement legend in plain html outside the chart, CSS grid should make it simple enough.
I'm not going to re-implement a complex layout system for legends, sorry.

**Comment by plouc** [comment]
Maybe I could expose a render function for legend which pass the computed legend data, this way we could use a wrapper component and bind one of its method to render the legend outside the chart component while preserving data consistency.

**Comment by borisrorsvort** [comment]
@plouc Seems legit 👍 Though it seems to me that these legends use cases are quite comon. But got your point and it would awsome to get the legend data and handle the rendering elsewhere

**Comment by luisrudge** [comment]
I'm having this need as well. I'm trying to render 12 legends and it kinda breaks the layout:

![image](https://user-images.githubusercontent.com/941075/45400603-3c810880-b623-11e8-9ab2-6c8dc234d9f9.png)

If the render function is too complex, maybe we can add another prop like `itemsPerRow` where you group the legends automatically based on that prop?

**Comment by plouc** [comment]
@luisrudge, the problem is it must support SVG/Canvas, and should be able to render without DOM (for the http rendering API). I think the best option is to be able to render the legend outside of the chart, using html, as it's easy enough to do this via CSS grids/flexbox for example.

**Comment by luisrudge** [comment]
@plouc yeah.. I agree. It's way more flexible to build this in html

**Comment by SenelithPerera** [comment]
@luisrudge can u be a little more specific about how it becomes flexible ? Cause I'm facing the same issue right now. It's not clear to me about how to handle the legends outside the chart area using html and css. Do you happen to have an example or a code sandbox that you could share ?

**Comment by ymenase** [comment]
Hi, please help. I am using nivo line and want to translate the legend to be lower. I thought increasing translateY would do it but I am finding that none of the legend properties are being applied

**Comment by lezan** [comment]
@plouc Is it now possible to render legend outside chart? I need to able to use multi rows.

Thanks!

**Comment by ericduarte** [comment]
Hello , i want to create responsive legends with CSS Grid, for that i need get informations from chart like, colors etc, there is a way to make it ? i know that in onclick event i can get data from one item, can i get all data in one time ?

**Comment by tuucan** [comment]
Can we somehow display legends for specific labels?
So we can create multiple legends and position them accordingly to create a row or column effect?

**Comment by dkim-thomas** [comment]
@plouc Just wanted to follow up in this thread to see if there was a way to render the legend outside of the chart. Is this possible for the responsive line graphs at the moment?

**Comment by wyze** [comment]
Here is an example using custom layers that I've split the legends onto 2 rows. https://codesandbox.io/s/react-nivo-example-forked-hidxj

Here is another example where the legend is completely outside the chart: https://codesandbox.io/s/nivopie-typescript-4qvmh

**Comment by joelbyrd** [comment]
> Here is an example using custom layers that I've split the legends onto 2 rows. https://codesandbox.io/s/react-nivo-example-forked-hidxj
> 
> Here is another example where the legend is completely outside the chart: https://codesandbox.io/s/nivopie-typescript-4qvmh

Still way too complicated and brittle to have to worry about splitting it like that, still using SVG (BoxLegendSvg). @plouc I'm still voting for that render function where we can output in html and use CSS flexbox if we want. Any Progress on that?
