### ISSUE TITLE
Feature Request: Sankey Diagram

### ISSUE THREAD

**Issue by ckluis** [plouc/nivo#28]
Sankey diagrams are excellent tools that are under utilized, but would be great to have within this very nice solution set.

Example: https://bl.ocks.org/mbostock/ca9a0bb7ba204d12974bca90acc507c0

**Comment by plouc** [comment]
@ckluis, I completely agree, and there's already one :), the demo website has not been updated yet though, but it were added in https://github.com/plouc/nivo/commit/f358d2f9709555833fd9ca550b5c0a2f30c63f3b:

<img width="1680" alt="capture d ecran 2017-08-22 a 11 32 25" src="https://user-images.githubusercontent.com/501642/29546201-d4866c18-872d-11e7-963a-fc4f8756f7ff.png">

I also have to add labels, but should be easy enough.

**Comment by plouc** [comment]
Labels are now supported https://github.com/plouc/nivo/commit/b90de33ad818f86a0ed1a6af24bed831c221834c
