### ISSUE TITLE
Dashed gridY line

### ISSUE THREAD

**Issue by g1un** [plouc/nivo#281]
Hie!
Does it possible to make gridY line dashed?
<img width="195" alt="2018-09-07 11 27 32" src="https://user-images.githubusercontent.com/13907881/45207610-13622000-b291-11e8-9e85-69ceab0a204d.png">

**Comment by plouc** [comment]
Hello,

Yes, you can use the theme for this, you have an available example [here](https://codesandbox.io/s/p3pv1n4n60).

**Comment by g1un** [comment]
Great! Thanks!

**Comment by JessSTX** [comment]
update the link please :'(

**Comment by romancavry** [comment]
You can do this like this

<img width="788" alt="image" src="https://github.com/user-attachments/assets/b6f287d4-5ed7-4431-a5b9-917438c75575">

```
<ResponsiveBar
      theme={{
        grid: { line: { stroke: '#ddd', strokeDasharray: '1 2' } },
      }}
     ...
```
