### ISSUE TITLE
LineGraph y-axis overflow

### ISSUE THREAD

**Issue by elias94** [plouc/nivo#284]
On the LineGraph, y-axis doesn't manage anymore the values overflow.

![image](https://user-images.githubusercontent.com/8095533/45291682-2542fd80-b4f3-11e8-8408-ae11523e5102.png)

**Comment by plouc** [comment]
It's not a bug, it's a feature :) it depends on the min value of the yScale, if you set it to `auto` values will remain in the graph, otherwise it's your responsibility to se the correct min value according to your dataset, the most common case being to start at `0`.

**Comment by elias94** [comment]
If I remember well, the LineGraph didn't work in this way before some recent update.
It's a feature not so useful, because if I want to create a zoomed version of the Graph, now the Chart is going outside the container creating a strange and undesired effect.
Btw, you're doing a great work, thanks!

**Comment by plouc** [comment]
It did, see this example using an older version => https://codesandbox.io/s/l2l55ykr47

**Comment by plouc** [comment]
Not really handy, but you can replace off-values by null, so those points won't be rendered, like in [this example](http://nivo.rocks/storybook/?knob-curve=monotoneX&selectedKind=Line&selectedStory=holes%20in%20data&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by elias94** [comment]
![5238087303823360](https://user-images.githubusercontent.com/8095533/45351122-acf14080-b5b5-11e8-864d-14e2fb7f0545.png)
What about this behaviour?

**Comment by plouc** [comment]
yes, it behaves like this on purpose, see [this example](http://nivo.rocks/storybook/?knob-curve=monotoneX&selectedKind=Line&selectedStory=highlighting%20negative%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs), maybe the areas min value could be configurable, I'll be glad to review a PR if you need this feature.

**Comment by fftristan** [comment]
Hi plouc, how do you set a y-min value for a naive bar? Please see most recent post in https://github.com/plouc/nivo/issues/671

**Comment by usamedin** [comment]
@elias94 i had the same issue and I fix it by removing min and max from yScale and it worked

**Comment by ssbarbee** [comment]
If anyone is still having this issue of the yAxis overflowing when using `enableArea=true`, try adding `areaBaselineValue` and setting the value to the min value of the yAxis. 

Example code:

```const yScale = useMemo(() => {
    const yS = data.reduce((pV, cI) => {
      const validData: number[] = cI.data
        .filter((d) => d.y !== null && d.y !== undefined)
        .map((d) => d.y as number);
      return [...pV, ...validData];
    }, [] as number[]);

    data[0].data.map((d) => d.y);
    const min = Math.min(...yS);
    const max = Math.max(...yS);
    return { min, max };
  }, [data]);

return (
  <ResponsiveLine
     areaBaselineValue={yScale.min}
     enableArea={true}
     yScale={{
          type: 'linear',
          min: 'auto',
          max: 'auto',
          stacked: true,
          reverse: false,
        }}
  />
)
```

Note: this assumes that the points in the yAxis are numbers. `data` above is passed as prop the Component returning the ResponsiveLine.

@plouc perhaps it is worthy if you update the storybook with such example? Thanks for the amazing library!

**Comment by streamside** [comment]
When implemented a use case I encountered the problem outlined in this issue. Posting my solution here in case someone stumbles across this issue. On high level the solution add a custom line layer and uses [clipPath](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath) to prevent the lines to overflow the chart area.

**Line layer preventing overflow**
```
const LineLayer = ({ series, lineGenerator, innerWidth, innerHeight, }) => {
  return (
    <g>
      <clipPath id="chartClipPath">
        <rect x={0} y={0} width={innerWidth} height={innerHeight} />
      </clipPath>
      {series.map(({ id, data, color }) => {
        return (
          <path
            d={lineGenerator(data.map((d) => d.position))}
            fill="none"
            stroke={color}
            clipPath="url(#chartClipPath)"
            key={`line-${id}`}
          />
        );
      })}
    </g>
  );
};
```

**Use custom line layer**
```
import LinesLayer from './LinesLayer';

<ResponsiveLine
  data={...}
  layers={[
    'grid',
    'makers',
    'areas',
    LinesLayer, // applies the custom line layer
    'slices',
    'axes',
    // remove / add layers needed by your use case
  ]}
/>
```

**Comment by WilliamABradley** [comment]
> When implemented a use case I encountered the problem outlined in this issue. Posting my solution here in case someone stumbles across this issue. On high level the solution add a custom line layer and uses [clipPath](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath) to prevent the lines to overflow the chart area.
> 
> **Line layer preventing overflow**
> 
> ```
> const LineLayer = ({ series, lineGenerator, innerWidth, innerHeight, }) => {
>   return (
>     <g>
>       <clipPath id="chartClipPath">
>         <rect x={0} y={0} width={innerWidth} height={innerHeight} />
>       </clipPath>
>       {series.map(({ id, data, color }) => {
>         return (
>           <path
>             d={lineGenerator(data.map((d) => d.position))}
>             fill="none"
>             stroke={color}
>             clipPath="url(#chartClipPath)"
>             key={`line-${id}`}
>           />
>         );
>       })}
>     </g>
>   );
> };
> ```
> 
> **Use custom line layer**
> 
> ```
> import LinesLayer from './LinesLayer';
> 
> <ResponsiveLine
>   data={...}
>   layers={[
>     'grid',
>     'makers',
>     'areas',
>     LinesLayer, // applies the custom line layer
>     'slices',
>     'axes',
>     // remove / add layers needed by your use case
>   ]}
> />
> ```

A more portable version of @streamside's solution is:

```tsx
 const graphId = useId();
  const ClipLayer: Layer = ({ innerWidth, innerHeight }) => {
    return (
      <>
        <clipPath id={`clip-${graphId}`}>
          <rect x={0} y={0} width={innerWidth} height={innerHeight} />
        </clipPath>
        <style>{`#${CSS.escape(graphId)} path { clip-path: url(#clip-${CSS.escape(graphId)}); }`}</style>
      </>
    );
  };

<ResponsiveLine
  data={...}
  layers={[
      "grid",
      "markers",
      "axes",
      "areas",
      "crosshair",
      "lines",
      "points",
      "slices",
      "mesh",
      "legends",
      ClipLayer,
  ]}
/>
```

This way, you can still use the native layers (Keeping animations + clipping the area too)
