### ISSUE TITLE
Independent x-axis and y-axis style control

### ISSUE THREAD

**Issue by lucas-wade** [plouc/nivo#286]
I would like to configure the colour of the x-axis independently from the colour of the y-axis. 
Is this possible?
thanks so much,
Luke

**Comment by plouc** [comment]
not atm unfortunately, but it could be useful.

**Comment by maskott** [comment]
Is this still not possible? I have a use case where I need a much larger font size on the Y axis than the X axis and I can't seem to find a way to control them separately. I only have my `axis: { ticks: { text: { fontSize: 14 }}}` which controls both.
