### ISSUE TITLE
Add a theme option to change the color of the LineSlicesItem's line

### ISSUE THREAD

**Issue by luisrudge** [plouc/nivo#289]
https://github.com/plouc/nivo/blob/master/packages/line/src/LineSlicesItem.js#L36

It's fixed as #000, making it hard to use with dark backgrounds:
![image](https://user-images.githubusercontent.com/941075/45401809-c8496380-b628-11e8-88f6-2815a191e7ed.png)

**Comment by rpearce** [comment]
:100: this would be a great improvement, though passing in any number of styles would probably make it even more flexible (as is done elsewhere)

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/512/commits/bd7a40545229bd9f2e635ef57681df91ba90e1ce, you can customize it using `theme.crosshair.line`, which default to:

```javascript
crosshair: {
    line: {
        stroke: '#000000',
        strokeWidth: 1,
        strokeOpacity: 0.35,
    },
}
```
