### ISSUE TITLE
Can I do pie chart label with 2 lines?

### ISSUE THREAD

**Issue by g1un** [plouc/nivo#290]
Is there an ability to have multiline label? Like this:
<img width="547" alt="2018-09-13 12 35 32" src="https://user-images.githubusercontent.com/13907881/45480718-48b7b380-b752-11e8-84aa-f4ff6e8dfe14.png">

**Comment by Xotl** [comment]
Any news on this? 👀

**Comment by plouc** [comment]
This is not feasible for now, to do so, we would need the ability to provide a custom component for labels or support for layers.

**Comment by plouc** [comment]
@g1un @Xotl even if that's not provided by default by the package, you now have the ability to add extra layers, which allows you to implement custom labels like this.

**Comment by Xotl** [comment]
Thanks, will try it! 😄

**Comment by dafu2020** [comment]
hi @plouc , how can you find out the x,y location of a label to make a new layer?

**Comment by olgakozich** [comment]
> hi @plouc , how can you find out the x,y location of a label to make a new layer? I have three arcLinkLabels, not sure how to get the location of each labels.

@dafu2020 hi, I have the same problem. Did you find solution?

**Comment by plouc** [comment]
Hi @dafu2020, I guess after more than 1 year you probably forgot about this, but nivo uses `computArcLink` internally to compute the positions and links points (https://github.com/plouc/nivo/blob/master/packages/arcs/src/arc_link_labels/compute.ts#L31).

**Comment by archisman11** [comment]
Hi, I was looking for a similar solution. 
Did anyone implement labels on 2 row?

**Comment by acherkashin** [comment]
@plouc is there way in 2024 to make 2 lines labels? 🤔

**Comment by plouc** [comment]
@acherkashin, I sense sarcasm, which is really not welcome here. No, in 2024 SVG text still doesn't support line breaks.

**Comment by acherkashin** [comment]
> I sense sarcasm, which is really not welcome here.
@plouc there was no sarcasm directed at you, I was really curious.

**Comment by plouc** [comment]
If you're curious, you can have a look at [this SO thread](https://stackoverflow.com/questions/16701522/how-to-linebreak-an-svg-text-within-javascript) for example, but basically, this would most likely require a custom text component, extra props...

**Comment by acherkashin** [comment]
@plouc thank you 👍
