### ISSUE TITLE
Dynamic data?

### ISSUE THREAD

**Issue by MarcMagnin** [plouc/nivo#292]
Hi! 

Do you have the capability to update the date with newer data such as for instance in the following example? 
https://www.highcharts.com/stock/demo/dynamic-update

Regard,

**Comment by plouc** [comment]
Something like [this](http://nivo.rocks/storybook/?selectedKind=Line&selectedStory=real%20time%20chart&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)?

**Comment by MarcMagnin** [comment]
Awesome! Where can we find the source/samples of this demo?

**Comment by plouc** [comment]
[here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js)
