### ISSUE TITLE
Synchronized charts or API to draw on other charts

### ISSUE THREAD

**Issue by MarcMagnin** [plouc/nivo#293]
Hi,

Do Nivo has the capability to programmatically render visuals on charts to endup doing things such as in the following example?: https://www.highcharts.com/demo/synchronized-charts

Basically hovering a chart show a vertical line. Other charts can programmatically render that line based on this hovering event. Having an API to programmatically render things would be great!
Also can we show the vertical line without sticking to datapoints?
Many thanks!

**Comment by plouc** [comment]
You could be able to do something similar using mouse events, however it's not ready yet, there's a pending PR on the matter https://github.com/plouc/nivo/pull/280.

**Comment by MarcMagnin** [comment]
ok great! As long as there is a way to do something
