### ISSUE TITLE
@nivo/line doesn't work with time as expected

### ISSUE THREAD

**Issue by di2pro** [plouc/nivo#294]
The problem is that when I'm passing dates to the x-axis and using a day as precision, it will show additional steps on the x-axis by splitting a day on hours. Also, the [example](http://nivo.rocks/storybook/?knob-curve=step&selectedKind=Line&selectedStory=time%20x%20scale&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) doesn't work as expected.

[live preview](https://stackblitz.com/edit/nivo-line-issue)

**Comment by plouc** [comment]
@di2pro, the example data isn't complete in the code preview, the extension used to show component source code cuts properties, the complete code can be found [here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js).

**Comment by plouc** [comment]
The precision acts on the input data, not on the axis ticks, it's used to cut unwanted info from input dates, for example if you use a daily precision, it will set hours/seconds/ms to 0.
It allows to use different interval for input and axis, for example you could use a daily interval for your data, but have a monthly interval for the axis.

**Comment by di2pro** [comment]
@plouc, so, does it mean that I have to use different config to set up a daily interval for the x-axis? Don't see any docs about this option, could you please point me to it?

**Comment by di2pro** [comment]
@plouc, ok, got it. I've updated the preview and it works as expected with data, does it mean that the line chart x-axis interval depends on the number of points you pass in? And if it's less than 7 days, then it'll use additional ticks, right?

**Comment by plouc** [comment]
@di2pro, there's a [guide about axes](http://nivo.rocks/guides/axes), however it only supports count or explicit values for now, the time interval support is a WIP which should be available soon enough, it should be something like `time:day` (to pass to `tickValues`) property which will map to the corresponding d3 function.

**Comment by plouc** [comment]
yes it depends on the data, however, you have the ability to pass custom lower/higher value, but the documentation is missing :/

**Comment by di2pro** [comment]
Ok, thanks a lot, I'm going to close the issue. Am I able to help you with docs?

**Comment by ymenase** [comment]
do the axes support time now? @plouc thanks
