### ISSUE TITLE
Drawing a line over charts

### ISSUE THREAD

**Issue by raphael-leger** [plouc/nivo#296]
Hellow,

I would enjoy being able to draw Regression charts with Nivo, which are basically scatter plots with a straight line. (for instance: x=y)

![Example](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZX8Cpxfzn5RtH17Lh36Es0DP8-hPKfXaVZtNbJ3eVZ5LiJ1cu_Q)

#139 would probably allow this by composing together a line chart and a scatter plot chart.

Though, maybe there could be a lighter solution that would help with any use cases where such trendlines are needed.
Could be a kind of sub-component working pretty much like the 'axes': an attribute you can give to charts that have x and y.

[AmCharts](https://www.amcharts.com/demos/trend-lines/) have such a handy system given some start/end position:
```
"trendLines": [{
        "startX": 1,
        "startY": 1,
        "endX": 20,
        "endY": 20,
        "lineColor": "#CC0000"
    }],
```

**Comment by plouc** [comment]
I'm closing this one on favor of https://github.com/plouc/nivo/issues/139.
I'm not planing to add `trendlines` support to the ScatterPlot API for now, but you should now be able to achieve this using the `layers` property, see [this example](https://codesandbox.io/s/kkqmx1rw17).
