### ISSUE TITLE
Render treemap internal nodes labels

### ISSUE THREAD

**Issue by taschetto** [plouc/nivo#297]
The `<Treemap />` component renders a label for every leaf node, but the user must hover above a small area to show an internal node tooltip . It would be very useful (specially for printing purposes) to have the ability to render a label on every node. Maybe on the top left corner for internal nodes.

Something like this:

![](https://upload.wikimedia.org/wikipedia/commons/c/c5/Gradient_grouped_treemap.jpg)

**Comment by plouc** [comment]
I agree it could be really useful, however d3 layout doesn't support natively, and you also have the option to automatically orient labels depending on the width/height ratio of the cell, I'm afraid it will require a bit of work.

**Comment by plouc** [comment]
Implemented with https://github.com/plouc/nivo/pull/555, we can now use a parent label and adjust its position, it'll be available in the next release.
