### ISSUE TITLE
legend format for pie chart

### ISSUE THREAD

**Issue by abhijit-padhy** [plouc/nivo#298]
Is there any attribute available to **format legend** values?

I am trying to show like _" id + value "_ in legends.

![screenshot from 2018-09-26 14-42-37](https://user-images.githubusercontent.com/28405350/46070087-92fd5380-c19a-11e8-95e9-e76751f4ed92.png)

For sake of testing I tried like adding a string 'hello':
```
legends={[
                        {
                            legendFormat: (d)=>{ d+'hello'}
                        }
                    ]}
```
But the legends are getting overlapped on each other.

**Comment by plouc** [comment]
@abhijit-padhy, can you please provide a screenshot of this overlap, sorry but I don't really understand the problem.

**Comment by abhijit-padhy** [comment]
> @abhijit-padhy, can you please provide a screenshot of this overlap, sorry but I don't really understand the problem.
Below is the code:
 `<ResponsivePie
                    tooltipFormat={(d)=>Number.parseFloat(d*100).toFixed(1)+"%"}
                    legends={[
                        {
                            "anchor": "top-left",
                            "direction": "column",
                            "translateY": 5,
                            "translateX": -30,
                            "itemWidth": 170,
                            "itemHeight": 32,
                            "itemTextColor": "#25334C",//replace with acc to design "#25334C",
                            "symbolSize": 18,
                            "symbolShape": "circle",
                            "effects": [
                                {
                                    "on": "hover",
                                    "style": {
                                        "itemTextColor": "#000"
                                    }
                                }
                            ],
                            legendFormat:(d)=>{console.log("legends ",d);d.value+d.id}
                        },
                        // {
                        //     "legendFormat": (d,v)=>{ console.log(d,v);d+'hello'+v},
                        //     "anchor": "bottom-left",
                        //     "direction": "column",
                        //     "translateY": 5,
                        //     "translateX": -30,
                        //     "itemWidth": 200,
                        //     "itemHeight": 32,
                        //     "itemTextColor": "#25334C",
                        //     "symbolSize": 18,
                        // }
                    ]}
                    // legendFormat={(d)=>{console.log("legends ",d);d.value+d.id}}
                />`
![pie](https://user-images.githubusercontent.com/28405350/46807593-eae5ae00-cd87-11e8-9238-75c1bdda5772.png)

**Comment by plouc** [comment]
@abhijit-padhy, can you please format it? It's completely unreadable :)

**Comment by abhijit-padhy** [comment]
@plouc 
Sorry, 'm unable to format. I am not getting that option here.
So attaching the screen shot.
![legend](https://user-images.githubusercontent.com/28405350/46808087-174dfa00-cd89-11e8-8501-1c49bc304b78.png)

**Comment by Milleo** [comment]
I'm also having problems with the text alignment with the symbols, as I noticed the Y axis of the legend text element is defined by height / 2, but it still not aligned with the symbol, is there some work-around to fix this?

**Comment by fmturati** [comment]
Hello, do you guys have any idea of how to change the legend`s font size?
Thank you!

**Comment by plouc** [comment]
@Milleo, there's already an issue about this, https://github.com/plouc/nivo/issues/164, but didn't had the time to look at it.

@fmturati, you can change the font-size using the theme property, like this:
```
theme={{
    legends: {
        text: {
            fontSize: 14,
        }
    }
}}
```

**Comment by plouc** [comment]
@abhijit-padhy, sorry but there's no such property.
Please note that the way you wrote your function, it won't return anything:

```javascript
// this won't return anything
const legendFormat = (d) => { d.value + d.id }
// if you wish to return the value, you can either add an explicit return
const legendFormat = (d) => { return d.value + d.id }
// or use implicit return by omitting {}
const legendFormat = (d) => d.value + d.id
```

**Comment by annjawn** [comment]
Hey @plouc , thanks for all the work on this great library. Is there a place where I can find some documentation on how to set `theme`? I am trying to set font sizes for things like pie slice labels etc. the solution above worked for legends but wondering what key should be used for pie slice labels etc. any help would be appreciated.

**Comment by jithinbalakrishnan** [comment]
@abhijit-padhy 
How did you customize the legends ? 
The legend should display what is inside label property in data . is that possible ?
"legendFormat" property is not working for me.
can someone please help me on this

**Comment by kaeland** [comment]
@jithinbalakrishnan I've been able to tailor the code snippet located in [this pie chart](https://nivo.rocks/pie/) example to my own use case. Once the `legends` prop is passed to the `<ResponsivePie />` component, this prop can then be configured following the guide located [here](https://nivo.rocks/guides/legends). I hope this helps.

**Comment by c9s** [comment]
same here, the `legendFormat` property is not working in the ResponsivePie chart.

**Comment by AndreiManya** [comment]
> Is there any attribute available to **format legend** values?
> 
> I am trying to show like _" id + value "_ in legends.
> 
You can just create custom legend by mapping data
Example
{data && data.map((item) => (
                                        <React.Fragment key={item.label}>
                                            <Circle background={item.color}></Circle>
                                            <div>
                                                <span>{item.label}</span>
                                                <span>{item.value}</span>
                                            </div>
                                        </React.Fragment>
 ))}
