### ISSUE TITLE
Axis Legend Position - Middle or Center

### ISSUE THREAD

**Issue by benembery** [plouc/nivo#302]
I'm currently ResponsiveBar and legendPosition: 'center' aligns the label off the canvas. However, legendPosition: 'middle' works as expected, but doesn’t pass TypeScript validation. You're documentation says the position should be center to, I was hoping to clarify what is correct.

https://github.com/plouc/nivo/blob/199cb081247346deaab086562ff1598b475267fd/packages/bar/index.d.ts#L115

**Comment by wyze** [comment]
Here is the logic that handles `legendPosition`: 

https://github.com/plouc/nivo/blob/199cb081247346deaab086562ff1598b475267fd/packages/core/src/components/axes/Axis.js#L103-L126

Looks like you get some defaults when `legendPosition` is not one of the 3, so it seems the type could be relaxed a bit to allow you to omit it. Do you get the same results when you don't pass a value for `legendPosition`?

**Comment by plouc** [comment]
The typescript definitions might not be up to date with recent API changes, I must find a way to automate the detection of those BC breaks because it's really painful to maintain as nivo isn't written in TS and now contains many packages, I like it and use it for several projects, but I prefer to not use it for nivo as it makes it more difficult to contribute (React/d3/ts…). If you have any suggestion on how to do so :)

**Comment by plouc** [comment]
also recompose and ts isn't the best match (defaultProps for example).

**Comment by benembery** [comment]
Regardin automation, I'm not so sure, I've not done much distribution of type files. TS is handy in most cases but as you say adds a barrier to entry for contributors and can be really finicky.

I've only been using the BarChart so far but I'm really pleased with the result. Thanks for creating the library.

**Comment by plouc** [comment]
So, I've fixed the definitions, it's `middle` not `center`, I've also switched to `@nivo/axes` instead of `@nivo/core` for several packages.

**Comment by plouc** [comment]
Regarding automation, I've created a sample ts project in `examples` and build it on travis to ensure it matches definitions.
