### ISSUE TITLE
Usage with React 15

### ISSUE THREAD

**Issue by Vivalemuc** [plouc/nivo#303]
Hi,

I use React@15.6.1, can i use @nivo/Bar ? Because i got an error with @nivo/Axes each time ! And i saw that the min version of React is 16.2 !

How can i use @Nivo/Bar with React 15 ?
Thanks

**Comment by plouc** [comment]
Hi,

Sorry but you cannot, as the package.json states, react 16.2 is required, mostly because of `Fragment` usage which is used in several packages and really helps reducing DOM tree.
