### ISSUE TITLE
Negative Radius Error on Chord Diagram when Resizing.

### ISSUE THREAD

**Issue by aalises** [plouc/nivo#304]
I am getting the `path.js:94 Uncaught Error: negative radius: -0.94734375` when I am trying to resize the window so the chord diagram is so small it is not even visible. On the picture we can see the edge case. Resizing even more creates the negative radius issue. 

![Mini Chord](https://i.imgur.com/LnzcDDw.png)

Is there a way to circumvent that, or stop rendering the component when negative paths appear? (So it does not crash).

Thank you!

**Comment by plouc** [comment]
I added guards on most components, must have missed this one :)

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/327, will be available in next release.
