### ISSUE TITLE
Display additional data in Calendar tooltip and formatting.

### ISSUE THREAD

**Issue by matchatype** [plouc/nivo#307]
I see that calendar can display `day`, `value`, `x`, `y` and `size` in the tooltip. Is it possible to display additional properties passed to `data`? I would like to add a value for label, but I was not able to do that.

Additionally, I used _momentjs_ and _numeraljs_ to format tooltip values, but feels like overkill. Is it possible to customize formatting for both tooltips and legends, so instead of 1000000 I can display 1M for example...

**Comment by plouc** [comment]
The ability to add arbitrary data has been implemented via https://github.com/plouc/nivo/pull/489/commits/b02382a7caab8be97778da7746e025312a755f86, you'll find the raw data you passed under the `data` property of each day, available in tooltips/event handlers.
Regarding the use of `momentjs` and `numeraljs`, I agree that it's overkill :) nivo already requires `d3-format` & `d3-time-format`, you could use them without any impact on your bundle size.
