### ISSUE TITLE
Doc mistake bad space charactor '@nivo/heatmap '

### ISSUE THREAD

**Issue by elzup** [plouc/nivo#309]
at http://nivo.rocks/heatmap

```diff
-import { ResponsiveHeatMap } from '@nivo/heatmap '
+import { ResponsiveHeatMap } from '@nivo/heatmap'
```

![heatmap_components___nivo](https://user-images.githubusercontent.com/2284908/46776221-a507f600-cd45-11e8-8b24-87b2cc2ad43e.png)

**Comment by plouc** [comment]
Thank you @elzup, it was also the case for the canvas example, fixed by https://github.com/plouc/nivo/commit/93077734b6faed1beed595bff13fd8a0b16e85f2.
