### ISSUE TITLE
Data order mismatch

### ISSUE THREAD

**Issue by getnashty** [plouc/nivo#310]
I have 3 series of chart data in a responsive line:

<img width="689" alt="screen shot 2018-10-12 at 3 06 26 pm" src="https://user-images.githubusercontent.com/113112/46889480-d3fb9600-ce31-11e8-8719-1088c38ced8a.png">
<img width="685" alt="screen shot 2018-10-12 at 3 06 20 pm" src="https://user-images.githubusercontent.com/113112/46889481-d3fb9600-ce31-11e8-935a-c7a114cb8fa2.png">
<img width="690" alt="screen shot 2018-10-12 at 3 06 15 pm" src="https://user-images.githubusercontent.com/113112/46889482-d3fb9600-ce31-11e8-86fc-9f72e6602475.png">

The strange thing is, its pulling the data in out of order (you can see MIK is coming after dates it came before).

I can't use the time scale - as the data is by the minute, but the series can be a day apart, so with time it just crams the data to either side with nothing in the middle.

I have sorted the data in advance, so each series should still be correctly sorted by time to work with the point scale.

My component:
```
<ResponsiveLine
    margin={{ top: 20, bottom: 0, left: 0, right: 0 }}
    data={data}
    animate
    theme={theme.chart}
    curve="natural"
    xScale={{ type: 'point' }}
    enableGridY={false}
    enableGridX
    colorBy={d => d.color}
    legends={[
        {
            dataFrom: 'keys',
            anchor: 'bottom-left',
            direction: 'column',
            justify: false,
            translateX: 40,
            translateY: -20,
            itemsSpacing: 2,
            itemWidth: 100,
            itemHeight: 20,
            itemDirection: 'left-to-right',
            itemOpacity: 0.85,
            symbolSize: 14,
            symbolShape: 'circle',
            effects: [
                {
                    on: 'hover',
                    style: {
                        itemOpacity: 1
                    }
                }
            ]
        }
    ]}
    yScale={{ type: 'linear', min: 'auto', max: 'auto' }}
    minY="auto"
    maxY="auto"
    colors="spectral"
    enableArea />
```

My data looks like:

`[{"color":"#46A5D0","data":[{"x":"2018-10-11 14:59:00","y":98.07},{"x":"2018-10-11 15:00:00","y":97.96},{"x":"2018-10-11 15:01:00","y":97.83},{"x":"2018-10-11 15:02:00","y":98.1},{"x":"2018-10-11 15:03:00","y":98.135},{"x":"2018-10-11 15:04:00","y":98.39},{"x":"2018-10-11 15:05:00","y":98.44},{"x":"2018-10-11 15:06:00","y":98.31},{"x":"2018-10-11 15:07:00","y":98.32},{"x":"2018-10-11 15:08:00","y":98.09},{"x":"2018-10-11 15:09:00","y":98.15},{"x":"2018-10-11 15:10:00","y":97.955},{"x":"2018-10-11 15:11:00","y":97.79},{"x":"2018-10-11 15:12:00","y":97.85},{"x":"2018-10-11 15:13:00","y":97.68},{"x":"2018-10-11 15:14:00","y":98.11},{"x":"2018-10-11 15:15:00","y":98.19},{"x":"2018-10-11 15:16:00","y":98.31},{"x":"2018-10-11 15:17:00","y":98.52},{"x":"2018-10-11 15:19:00","y":98.71},{"x":"2018-10-11 15:20:00","y":98.64},{"x":"2018-10-11 15:21:00","y":98.68},{"x":"2018-10-11 15:22:00","y":98.76},{"x":"2018-10-11 15:23:00","y":98.83},{"x":"2018-10-11 15:24:00","y":98.66},{"x":"2018-10-11 15:25:00","y":98.84},{"x":"2018-10-11 15:26:00","y":98.665},{"x":"2018-10-11 15:27:00","y":98.63},{"x":"2018-10-11 15:28:00","y":98.55},{"x":"2018-10-11 15:29:00","y":98.51},{"x":"2018-10-11 15:30:00","y":98.45},{"x":"2018-10-11 15:31:00","y":98.45},{"x":"2018-10-11 15:32:00","y":98.45},{"x":"2018-10-11 15:33:00","y":98.75},{"x":"2018-10-11 15:34:00","y":98.61},{"x":"2018-10-11 15:35:00","y":98.525},{"x":"2018-10-11 15:36:00","y":98.16},{"x":"2018-10-11 15:37:00","y":98.125},{"x":"2018-10-11 15:38:00","y":98.19},{"x":"2018-10-11 15:39:00","y":98.44},{"x":"2018-10-11 15:40:00","y":98.25},{"x":"2018-10-11 15:41:00","y":98.17},{"x":"2018-10-11 15:42:00","y":98.21},{"x":"2018-10-11 15:43:00","y":98.225},{"x":"2018-10-11 15:44:00","y":98.14},{"x":"2018-10-11 15:45:00","y":97.95},{"x":"2018-10-11 15:46:00","y":98.185},{"x":"2018-10-11 15:47:00","y":98.01},{"x":"2018-10-11 15:48:00","y":97.88},{"x":"2018-10-11 15:49:00","y":97.78},{"x":"2018-10-11 15:50:00","y":97.71},{"x":"2018-10-11 15:51:00","y":97.89},{"x":"2018-10-11 15:52:00","y":98.07},{"x":"2018-10-11 15:53:00","y":97.89},{"x":"2018-10-11 15:54:00","y":98.03},{"x":"2018-10-11 15:55:00","y":97.86},{"x":"2018-10-11 15:56:00","y":98},{"x":"2018-10-11 15:57:00","y":97.87},{"x":"2018-10-11 15:58:00","y":97.84},{"x":"2018-10-11 15:59:00","y":97.77}],"id":"PRU BEFORE"},{"color":"#664C79","data":[{"x":"2018-10-12 09:30:00","y":99.35},{"x":"2018-10-12 09:31:00","y":98.69},{"x":"2018-10-12 09:32:00","y":99.1},{"x":"2018-10-12 09:33:00","y":99.04},{"x":"2018-10-12 09:34:00","y":98.705},{"x":"2018-10-12 09:35:00","y":98.565},{"x":"2018-10-12 09:36:00","y":98.54},{"x":"2018-10-12 09:37:00","y":98.79},{"x":"2018-10-12 09:39:00","y":99.14},{"x":"2018-10-12 09:40:00","y":99.41},{"x":"2018-10-12 09:41:00","y":99.4},{"x":"2018-10-12 09:42:00","y":99.43},{"x":"2018-10-12 09:44:00","y":98.84},{"x":"2018-10-12 09:46:00","y":98.77},{"x":"2018-10-12 09:47:00","y":98.76},{"x":"2018-10-12 09:50:00","y":98.55},{"x":"2018-10-12 09:55:00","y":99.025},{"x":"2018-10-12 09:56:00","y":99},{"x":"2018-10-12 10:03:00","y":98.66},{"x":"2018-10-12 10:07:00","y":98.19},{"x":"2018-10-12 10:09:00","y":98.115},{"x":"2018-10-12 10:12:00","y":97.91},{"x":"2018-10-12 10:13:00","y":97.795},{"x":"2018-10-12 10:14:00","y":97.53},{"x":"2018-10-12 10:15:00","y":97.38},{"x":"2018-10-12 10:16:00","y":97.41},{"x":"2018-10-12 10:19:00","y":97.32},{"x":"2018-10-12 10:21:00","y":97.51},{"x":"2018-10-12 10:25:00","y":97.25},{"x":"2018-10-12 10:28:00","y":96.97},{"x":"2018-10-12 10:29:00","y":97.08},{"x":"2018-10-12 10:37:00","y":97.54},{"x":"2018-10-12 10:40:00","y":97.82},{"x":"2018-10-12 10:42:00","y":97.71},{"x":"2018-10-12 10:43:00","y":97.75},{"x":"2018-10-12 10:44:00","y":97.58},{"x":"2018-10-12 10:45:00","y":97.5},{"x":"2018-10-12 10:48:00","y":97.27},{"x":"2018-10-12 10:53:00","y":97.42},{"x":"2018-10-12 11:00:00","y":97.5},{"x":"2018-10-12 11:02:00","y":97.63},{"x":"2018-10-12 11:04:00","y":97.58},{"x":"2018-10-12 11:07:00","y":97.52},{"x":"2018-10-12 11:11:00","y":97.66},{"x":"2018-10-12 11:18:00","y":97.49},{"x":"2018-10-12 11:20:00","y":97.28},{"x":"2018-10-12 11:22:00","y":97.28},{"x":"2018-10-12 11:23:00","y":97.29},{"x":"2018-10-12 11:27:00","y":97.18},{"x":"2018-10-12 11:28:00","y":97.1},{"x":"2018-10-12 11:30:00","y":97.07},{"x":"2018-10-12 11:32:00","y":97.125},{"x":"2018-10-12 11:33:00","y":97.09},{"x":"2018-10-12 11:35:00","y":97.045},{"x":"2018-10-12 11:37:00","y":97.05},{"x":"2018-10-12 11:41:00","y":96.92},{"x":"2018-10-12 11:42:00","y":96.86},{"x":"2018-10-12 11:43:00","y":96.72},{"x":"2018-10-12 11:45:00","y":96.68},{"x":"2018-10-12 11:46:00","y":96.61}],"id":"PRU AFTER"},{"color":"#9e0142","data":[{"x":"2018-10-11 14:52:00","y":15.54},{"x":"2018-10-11 14:54:00","y":15.565},{"x":"2018-10-11 14:55:00","y":15.56},{"x":"2018-10-11 14:56:00","y":15.565},{"x":"2018-10-11 14:57:00","y":15.57},{"x":"2018-10-11 14:58:00","y":15.575},{"x":"2018-10-11 14:59:00","y":15.58},{"x":"2018-10-11 15:00:00","y":15.585},{"x":"2018-10-11 15:01:00","y":15.6},{"x":"2018-10-11 15:02:00","y":15.62},{"x":"2018-10-11 15:03:00","y":15.615},{"x":"2018-10-11 15:06:00","y":15.645},{"x":"2018-10-11 15:07:00","y":15.635},{"x":"2018-10-11 15:08:00","y":15.62},{"x":"2018-10-11 15:09:00","y":15.61},{"x":"2018-10-11 15:11:00","y":15.6},{"x":"2018-10-11 15:13:00","y":15.61},{"x":"2018-10-11 15:14:00","y":15.645},{"x":"2018-10-11 15:15:00","y":15.67},{"x":"2018-10-11 15:16:00","y":15.67},{"x":"2018-10-11 15:17:00","y":15.71},{"x":"2018-10-11 15:18:00","y":15.685},{"x":"2018-10-11 15:19:00","y":15.67},{"x":"2018-10-11 15:20:00","y":15.705},{"x":"2018-10-11 15:21:00","y":15.695},{"x":"2018-10-11 15:23:00","y":15.67},{"x":"2018-10-11 15:24:00","y":15.665},{"x":"2018-10-11 15:27:00","y":15.66},{"x":"2018-10-11 15:28:00","y":15.65},{"x":"2018-10-11 15:29:00","y":15.625},{"x":"2018-10-11 15:30:00","y":15.615},{"x":"2018-10-11 15:31:00","y":15.63},{"x":"2018-10-11 15:32:00","y":15.625},{"x":"2018-10-11 15:33:00","y":15.62},{"x":"2018-10-11 15:34:00","y":15.615},{"x":"2018-10-11 15:35:00","y":15.605},{"x":"2018-10-11 15:36:00","y":15.595},{"x":"2018-10-11 15:37:00","y":15.595},{"x":"2018-10-11 15:38:00","y":15.595},{"x":"2018-10-11 15:39:00","y":15.625},{"x":"2018-10-11 15:40:00","y":15.61},{"x":"2018-10-11 15:41:00","y":15.595},{"x":"2018-10-11 15:42:00","y":15.59},{"x":"2018-10-11 15:43:00","y":15.59},{"x":"2018-10-11 15:44:00","y":15.56},{"x":"2018-10-11 15:45:00","y":15.575},{"x":"2018-10-11 15:46:00","y":15.565},{"x":"2018-10-11 15:47:00","y":15.555},{"x":"2018-10-11 15:48:00","y":15.555},{"x":"2018-10-11 15:49:00","y":15.56},{"x":"2018-10-11 15:50:00","y":15.54},{"x":"2018-10-11 15:51:00","y":15.555},{"x":"2018-10-11 15:52:00","y":15.565},{"x":"2018-10-11 15:53:00","y":15.58},{"x":"2018-10-11 15:54:00","y":15.575},{"x":"2018-10-11 15:55:00","y":15.565},{"x":"2018-10-11 15:56:00","y":15.565},{"x":"2018-10-11 15:57:00","y":15.565},{"x":"2018-10-11 15:58:00","y":15.565},{"x":"2018-10-11 15:59:00","y":15.545}],"id":"MIK"}]"`

Any ideas would be highly appreciated!

**Comment by plouc** [comment]
@getnashty, do you think you could provide an example of this on codesandbox?

**Comment by plouc** [comment]
@getnashty, sorry but I'm closing this issue as I don't have a running example, I might re-open it if you can provide one.

**Comment by getnashty** [comment]
Sorry plouc, I stopped using this library due to ^^ and forgot to close, thanks!
