### ISSUE TITLE
Change the color of the grid

### ISSUE THREAD

**Issue by danzawadzki** [plouc/nivo#311]
I really like the library, but either there is no option, or I do not see it. Is it possible to change the color of the grid? Can i pass color by props or even by overwriting some css class?

**Comment by Chrischuck** [comment]
To add, is there a way to change the label colors for the grid tick labels?

**Comment by Chrischuck** [comment]
https://codesandbox.io/s/l264on6pvl

[Other Issue](https://github.com/plouc/nivo/issues/132)

**Comment by plouc** [comment]
You can use the theme for this, I've updated the sandbox according to nivo updates => https://codesandbox.io/s/p3pv1n4n60

**Comment by Chrischuck** [comment]
@plouc Thanks for the help, what would the JSON look like if I wanted to change the text color for the tick mark labels referenced in [this issue](https://github.com/plouc/nivo/issues/132)?  I tried plugging in the axis part into the new code sand box but it didn't work.
