### ISSUE TITLE
Controlling Axis Increments

### ISSUE THREAD

**Issue by mattmuirheadDauntless** [plouc/nivo#313]
Is there a way to control axis increments?

For instance I have a chart that tracks assets, in the chart there are 2 bars, one that has a value of 1 and the other has a value of 2. However the axis displays 0, 0.5, 1, 1.5 and 2. As there is no such thing as 1.5 assets this doesn't work for us. Is there a way to limit the axis to whole numbers only?

**Comment by mattmuirheadDauntless** [comment]
Thanks for the quick reply @plouc - can you point me in the right direction in the documentation? I can't find any examples on how to do this?

**Comment by plouc** [comment]
You can have a look at http://nivo.rocks/guides/axes#ticks, in your case you could use `tickValues: 3` or `tickValues: [0, 1, 2]` for example.

**Comment by plouc** [comment]
And also it depends on the package you use, I've not plugged all components on the new axes package.

**Comment by mattmuirheadDauntless** [comment]
Excellent thanks @plouc

**Comment by plouc** [comment]
I've created a demo, just in case => https://codesandbox.io/s/1zoxoj5q5j

**Comment by brandondurham** [comment]
Is it possible to show y axis grid lines only on those whole numbers and not the fractions? I have a chart with data points that can only ever be whole numbers, and I’d like to make the y axis grid lines adhere to that and not show the lines in between.

**Comment by siddharthVH** [comment]
Can we control axis-bottom too in similar way by using **tickValues** ?

**Comment by ChuckJonas** [comment]
I had a series where the x-axis was the number of seconds since start.

My work around was to do something like this:

```typescript
tickValues: [...Array(Math.ceil(tempData.length / 10)).keys()].map(i => i * 10),
```

It works pretty well for my use case, and I think you could do something pretty similar with a fix number of points distributed across the x range.

Still seems like it should just work the same way that the y-axis does out of the box tho...

**Comment by sarang12** [comment]
Is it possible to have completely unrelated left axis and right axis tickValues? I tried passing an array to right tickValues, but the numbers being very small compared to the left axis, just overlap at x=0.
