### ISSUE TITLE
Setting width & height to flex

### ISSUE THREAD

**Issue by rweller59** [plouc/nivo#318]
Just getting started but charts are working fine so far. 
I'm rendering components with flex grid. Is there a way to have width and height conform to flex controls?

**Comment by plouc** [comment]
What do you mean by "flex grid", is it flex-box or css-grid?

**Comment by rweller59** [comment]
I am using Material-UI Components Library grid layout which uses  CSS Flexible Box module.

**Comment by plouc** [comment]
I'm closing this in favor of https://github.com/plouc/nivo/issues/411
