### ISSUE TITLE
Negative Values on calendar

### ISSUE THREAD

**Issue by vinayaknadar** [plouc/nivo#324]
Hello guys,

I'm trying to display negative values on a calendar, it is displaying as positive value even if you add negative value in the data ,  is there a way to have minY maxY config. 
For example minValue -200  and middleValue  0  maxValue 400

Regards,

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/489/commits/6a9de013d5333d6e5ec717ce17ce5fb8d1e63cef
