### ISSUE TITLE
yScale type in LineChart isn't rendered in the correct order

### ISSUE THREAD

**Issue by iremlopsum** [plouc/nivo#330]
So, I technically want to achieve what `type: 'point'` already does, but if I set the type to point then the order of the y axis doesn't render in the correct order. See '7am', which is -3, but it doesn't actually dip correctly

![image](https://user-images.githubusercontent.com/8178748/47652865-68326080-db87-11e8-8b16-7c506827d202.png)

If I set it to linear it renders all values, but I want to show only the points that are available

**Comment by plouc** [comment]
Can you please provide an example on codesandbox?

**Comment by plouc** [comment]
I'm closing this since I don't have an example to use to investigate, feel free to comment if you can setup one.
