### ISSUE TITLE
tickValues don't affect grid

### ISSUE THREAD

**Issue by rick-software** [plouc/nivo#335]
I like to limit the number of ticks by using tickValues, however, I haven't been able to figure out how to limit the grid lines in the same manner. Is there a way to control the number of grid lines?

**Comment by ciaranschutte** [comment]
@rick-software in the exact same way as tickValues I think. Pass 'gridXValues' prop with an array of values

**Comment by plouc** [comment]
@rick-software yes, axes and grid are independent, you can use `grid(X|Y)Values` to configure the grid

**Comment by rick-software** [comment]
awesome!
