### ISSUE TITLE
Nivo Scatterplot 0.51.0 Syntax Error

### ISSUE THREAD

**Issue by jaydenklam** [plouc/nivo#336]
Hello!

I've recently had an error in Internet Explorer 11 where my application will not render in the window and this error shows up in the console:
![ie-error](https://user-images.githubusercontent.com/16137401/47920296-168c1d80-de88-11e8-8444-15ffb01c4a0b.PNG)

IE seems to be complaining about this snippet of code here (starting at 57415):
![syntax-error](https://user-images.githubusercontent.com/16137401/47920370-41767180-de88-11e8-8b6d-33d83fc68a39.PNG)

This happens when I update only @nivo/scatterplot from 0.50.0 to 0.51.0 (does not occur with any other nivo graphs).  As well, this happens only in Internet Explorer 11 and works fine in every other browser (Chrome, Firefox, Opera, Safari, and Edge).  Any thoughts?

**Comment by plouc** [comment]
Don't know which setup you use, but you could try to include the compilation of this package in your build to output es5.

**Comment by jaydenklam** [comment]
Thanks for the quick reply!  I will play around with this!

**Comment by plouc** [comment]
I think I'll have to figure something for the nivo website too (probably broken on IE). I'll let you know if I find a workaround.
