### ISSUE TITLE
Scatter plot does not handle negative values properly

### ISSUE THREAD

**Issue by plingampally** [plouc/nivo#337]
I've having issues with the x axis, it seems like it always starts at 0, even though I have set the domain to `auto`. As suggested by #249 and #241. (I've also tried setting the domain to specific values such as `[-1, 1]`)

```
<ResponsiveScatterPlot
  scales={[
    { id: 'x', axis: 'x', domain: [-1, 1] },
    { id: 'y', axis: 'y', domain: [-1, 1] }
  ]}
  data={scatter}
  margin={{
      "top": 60,
      "right": 140,
      "bottom": 70,
      "left": 90
  }}
  symbolSize={d => Math.abs(d.z/20)}
/>
```
If x is always -1:
![image](https://user-images.githubusercontent.com/4418607/47945811-02fda880-dec2-11e8-8728-b2af6622a9d5.png)

As you can see the x-axis makes absolutely no sense. 

Another example of x values between -1 and 1:
![image](https://user-images.githubusercontent.com/4418607/47946053-e5c9d980-dec3-11e8-9e62-7a92daeae137.png)

Any tips on how to properly handle negative values? Thanks!

**Comment by plouc** [comment]
Hi @plingampally,

That's because you're using an older version of the package, please upgrade to `@0.51.0`.
I've created a sandbox to show it working => https://codesandbox.io/s/21x1vm5l3p, it shows negative values without problem

**Comment by plingampally** [comment]
Thanks for the quick reply, I was using version `@0.51.0` however it seems that the `xScale` prop works, but the `scales` prop does not.

Thanks!
