### ISSUE TITLE
Re-add missing Sankey from demo site

### ISSUE THREAD

**Issue by rgfoley** [plouc/nivo#34]
The title captures the gist of it. The sankey diagram is not on the demo site. It is linked by the README but leads to a blank page. With that in mind, there may be others.

Thanks for the great project!

**Comment by plouc** [comment]
@rgfoley, I didn't deployed the corresponding demo yet, but it should be the only one because it's a recent addition (yesterday)

**Comment by plouc** [comment]
Some links to the API samples are also broken because it's not deployed in the latest version.

**Comment by plouc** [comment]
demo, storybook & APIs where updated.
