### ISSUE TITLE
borderColor prop missing from BarProps type def

### ISSUE THREAD

**Issue by SandyGifford** [plouc/nivo#344]
## Summary

The TypeScript type def for `BarProps` is missing the `borderColor` property.  Adding `borderColor` to a `Bar` or `ResponsiveBar` raises a typing error, although the compiled JS does correctly add the border color to the graph.

## Example

The following code (error in comments):

    import * as React from "react";
    import * as ReactDOM from "react-dom";
    
    import { Bar } from "@nivo/bar";
    
    const target = document.createElement("div");
    document.body.appendChild(target);
    
    ReactDOM.render(
        <Bar
            keys={["cow", "chicken"]}
            data={[{ id: "A", cow: 5, chicken: 3 }, { id: "B", cow: 1, chicken: 8 },]}
            indexBy="id"
            width={500}
            height={500}
            borderWidth={3}
            borderColor="black" />, // Type Error: "Property 'borderColor' does not exist on type ..."
        target
    );
    
will correctly create the following graph:

![image](https://user-images.githubusercontent.com/5024843/48518017-37fcea00-e836-11e8-8de6-bd6bb208426d.png)

The full error is:

    [ts] Property 'borderColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Bar> & Readonly<{ children?: ReactNode; }> & Readonly<Data & ColorProps<BarDatum> & Partial<{ indexBy: string | IndexByFunc; keys: string[]; ... 29 more ...; markers: CartesianMarkerProps[]; }> & Partial<...> & SvgDefsAndFill<...> & Partial<...> & Dimensions>'.

**Comment by plouc** [comment]
@SandyGifford, can you please use [this issue](https://github.com/plouc/nivo/issues/197) instead? It's easier to track down missing/wrong type defs.
Thank you.
