### ISSUE TITLE
Empty line chart

### ISSUE THREAD

**Issue by Chedvaka** [plouc/nivo#349]
Hi,
I use the responsive line chart and I need to render an empty chart - just grid,
There is any option?

**Comment by TrieBr** [comment]
Wondering the same thing. All of the scales go out of whack when there is no data. It even ignores my `tickValues`

**Comment by plouc** [comment]
You can replace the default `yScale` to maintain axes:

```javascript
const MyLine = <Line yScale={{ type: 'linear', min: 0, max: 100 }} {...otherProps}/>
```
