### ISSUE TITLE
https://nivo.rocks/ cert error

### ISSUE THREAD

**Issue by tristanbes** [plouc/nivo#35]
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

when trying to access the website

**Comment by patrickreck** [comment]
👍

**Comment by plouc** [comment]
just configured Cloudflare… seems it's not OK…

**Comment by tristanbes** [comment]
no it's not, unless there is some propagation delay

**Comment by plouc** [comment]
You should use non-ssl for now, sorry :/

**Comment by tristanbes** [comment]
non https redirects to https. I'm stuck in https version.

**Comment by plouc** [comment]
You should clear your browser cache

**Comment by plouc** [comment]
I should have waited to force redirect

<img width="240" alt="capture d ecran 2017-08-24 a 17 19 08" src="https://user-images.githubusercontent.com/501642/29656812-8b77ed20-88f0-11e7-849d-bef3ea936408.png">

**Comment by calvellido** [comment]
It's working for me now (non secure), it's not redirecting to https.

**Comment by plouc** [comment]
Never had the certificate… closing it as there's no error now, neither https unfortunately :(
