### ISSUE TITLE
Can't change tickColor and tickSize

### ISSUE THREAD

**Issue by bl4ze** [plouc/nivo#352]
TickColor is gray and TickSize is pretty small by default.
They are really hard to see. I can't make them larger.
The demo for ResponsiveStream doesn't show difference as well:
http://nivo.rocks/stream

My code:

> const theme = {
>   axis: {
>     textColor: "#fff",
>     fontSize: "15px",
>     tickColor: "#fff"
>   },
>   grid: {
>     stroke: "#888",
>     strokeWidth: 1
>   }
> };
> 
> <ResponsiveStream
>             data={data}
>             keys={[
>                 "Competitor",
>                 "Competitor2",
>             ]}
>             axisBottom={{
>               "orient": "bottom",
>               "tickSize": 20,
>               "tickPadding": 5,
>               "tickRotation": 0,
>               "legend": "",
>               "legendOffset": 36
>             }}
>             axisLeft={{
>                 "orient": "left",
>                 "tickSize": 20,
>                 "tickPadding": 5,
>                 "tickRotation": 0,
>                 "legend": "",
>                 "legendOffset": -40
>             }}
>             theme={theme}
>             curve= 'linear'
>             enableDots={true}
>             margin={{
>               "top": 50,
>               "right": 110,
>               "bottom": 50,
>               "left": 60
>            }}
>             colors="paired"
>             enableGridY={true}
>             enableGridX={false}
>             offsetType="none"
>             fillOpacity={0.65}
>             borderColor="#000"
>             dotSize={8}
>             dotBorderWidth={2}
>             dotBorderColor="inherit:brighter(0.7)"
>             animate={true}
>             motionStiffness={90}
>             motionDamping={15}
>             legends={[
>                 {
>                     "anchor": "bottom-right",
>                     "direction": "column",
>                     "translateX": 100,
>                     "itemWidth": 80,
>                     "itemHeight": 20,
>                     "itemTextColor": "white",
>                     "symbolSize": 12,
>                     "symbolShape": "circle",
>                     "effects": [
>                         {
>                             "on": "hover",
>                             "style": {
>                                 "itemTextColor": "#000"
>                             }
>                         }
>                     ]
>                 }
>             ]}
>         />

**Comment by plouc** [comment]
@bl4ze the theme structure was updated recently, for reference, you can have a look at https://github.com/plouc/nivo/blob/master/packages/core/src/theming/defaultTheme.js.

This should be something like this:

```javascript
const theme = {
    axis: {
        ticks: {
            line: {
                stroke: '#fff',
            },
            text: {
                fill: '#fff',
                fontSize: 15,
            }
        }
    },
    grid: {
        line: {
            stroke: '#888',
            strokeWidth: 1,
        }
    }
}
```

**Comment by codepharmer** [comment]
Or see here :)
https://nivo.rocks/guides/theming
