### ISSUE TITLE
Migrate Makefile to npm scripts

### ISSUE THREAD

**Issue by DanielRuf** [plouc/nivo#355]
Makefiles can not be used on all platforms. Woukd bd great to migrate it to npm scripts.

**Comment by plouc** [comment]
Hi @DanielRuf,

I'm sorry if that's your case, but I don't plan to change change this for now, make provides auto-completion, dynamic targets, parallelisation, environment variables support, inter-dependent targets, comments/help command…

Moving to a js based solution will require to maintain far more code and this repo is already pretty huge, and it will involve knowledge on various concepts such as CLI apps, processes, streams… while degrading performances (typically for fs operations) and adding more dependencies.

Maybe I'm missing something and they are better options, do not hesitate if you know one.
