### ISSUE TITLE
Problem with http://nivo.rocks

### ISSUE THREAD

**Issue by stefanos82** [plouc/nivo#36]
I have tried to visit the website and got an error (waterfox screenshot):

![selection_001](https://user-images.githubusercontent.com/1777466/29655414-af6e7f32-88b9-11e7-9517-91655c20e277.png)

Also, to double-confirm the issue, I have tested it via curl:

```text
stefanos@debian:~$ curl -vI https://nivo.rocks/
*   Trying 104.18.44.131...
* TCP_NODELAY set
* Connected to nivo.rocks (104.18.44.131) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS header, Unknown (21):
* TLSv1.0 (IN), TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

As you can see, on the ticket title I use `http://nivo.works` whereas in `curl` I use `https` protocol, because the link used in project description it redirects to `https://nivo.rocks`.

**Comment by plouc** [comment]
please use non-ssl version, and clear your browser cache if it always redirect to `https`

**Comment by plouc** [comment]
I should have waited to force redirect

<img width="240" alt="capture d ecran 2017-08-24 a 17 19 08" src="https://user-images.githubusercontent.com/501642/29656784-77f99cf8-88f0-11e7-9de1-64804ff01a94.png">

**Comment by stefanos82** [comment]
Weird..under Chromium (Debian testing 64-bit) goes to website, but with `curl` and waterfox (a firefox fork) it tries to redirect.

**Comment by calvellido** [comment]
It's working for me now (non secure), it's not redirecting to https.

**Comment by stefanos82** [comment]
Perfect! I have checked it with both waterfox and curl and works as expected.

Cheers @calvellido and @plouc 👍
