### ISSUE TITLE
Is there a histogram chart component?

### ISSUE THREAD

**Issue by simongis** [plouc/nivo#360]
Struggling to find a histogram chart.  Can someone point me to a sample?

We want to create a chart component that is half bubble chart, half histogram.
So far, the closest we have found is t[his bubble chart](http://nivo.rocks/storybook/?selectedKind=Bar&selectedStory=custom%20bar%20item&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) that uses an axes similar to a bar chart

This is what we are aiming to re-create using Nivo.  Any histogram samples would get us going in the right direction.

![image](https://user-images.githubusercontent.com/2769383/49137946-d7d37100-f328-11e8-910d-f5de6b6dee5c.png)

**Comment by plouc** [comment]
Appart from the Bar component, there's no such pre-made chart, however you'll probably be able to achieve this using the ScatterPlot component.

**Comment by plouc** [comment]
I've created an example using the ScatterPlot component => https://codesandbox.io/s/komnl0zx25

<img width="403" alt="screenshot 2018-11-29 at 12 30 05" src="https://user-images.githubusercontent.com/501642/49197528-88497f80-f3d2-11e8-88f5-d25768073813.png">

**Comment by simongis** [comment]
Wow! Excellent. Let me report back after the weekend. Big thanks

**Comment by simongis** [comment]
We struggled to get it to work to our requirements. Another dev will report his workings wirh a codepen sample tomorrow.

**Comment by abumuawiyah** [comment]
@plouc 
let me setting up a codepen. 
Actually the chart will be used in the Webmap (Web that have the Map and UI component (chart) interact with the Map). 
Example interaction is when we mouseover the Map, the chart e.g. the bubble highlighted and vice versa (mouseover the bubble, the Map highlighted).

**Comment by simongis** [comment]
@abumuawiyah Can you get a codepen setup for this next week?  Would still like to know if we can get better interaction between an Esri map and a custom histogram component.

**Comment by plouc** [comment]
any update?

**Comment by abumuawiyah** [comment]
Hi @plouc ,
I am sorry for not being responsive as currently moved to another project.
I have commit the code into my github
https://github.com/abumuawiyah/esrimapscatterplot

and can be review in Stackblitz
https://stackblitz.com/github/abumuawiyah/esrimapscatterplot

if you issue review it in Stackblitz,
you can access it here:
http://iluvnivoandesri.surge.sh/

What we need to do with Nivo chart and map is, if we are hovering the map, we would like the plot/bubble highlighted as well. 

I personally like Nivo especially on responsiveness and we plan to use Nivo chart as core chart library.

**Comment by plouc** [comment]
I'm closing this issue as I was able to reproduce the example. @abumuawiyah, the example doesn't seem to work on Stackblitz :/

Feel free to comment if you have other questions.
