### ISSUE TITLE
Support for logarithmic xScale/yScale?

### ISSUE THREAD

**Issue by rob-richards** [plouc/nivo#361]
Hey,

I'm new to Nivo and I apologize if this is already documented somewhere, but I looked and couldn't find anything. I am trying to see if a logarithmic xScale is possible with this library? I saw that in d3 [it is supported](https://github.com/d3/d3-scale#log-scales) and was curious if it is supported here?

**Comment by plouc** [comment]
No it's not, but I need for something I'm currently working on, so it might be available soon.

**Comment by plouc** [comment]
@rob-richards you can use a log scale with [Line](https://nivo.rocks/storybook/?selectedKind=Line&selectedStory=logarithmic%20y%20scale&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) and [ScatterPlot](https://nivo.rocks/storybook/?selectedKind=ScatterPlot&selectedStory=using%20logarithmic%20scales&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) components.

**Comment by Salah856** [comment]
i have a problem in yScale because it it's overflows 
i mean if i have a maximum value in my data set, it overflows beyond this limit
escpecially i have at least two legends 

i tried to make stacked option set to false, 
but it did not change
