### ISSUE TITLE
Cannot set text color in ResponsiveLine

### ISSUE THREAD

**Issue by zes** [plouc/nivo#364]
Hello,

first of all, thank you for Nivo :pray: 

I use `textColor` in `legends` property of a `ResponsiveLine` component but legends stay black. Did I miss an another parameter ?

Thx

```
legends={[
  {
     ...
     textColor: 'white',
     ...
  },
]}
```

**Comment by plouc** [comment]
Hello @zes,

It should work with `itemTextColor` property.

**Comment by minafa96** [comment]
what about point's text color? @plouc
