### ISSUE TITLE
Storybook section of website is empty

### ISSUE THREAD

**Issue by pfreedmanJG** [plouc/nivo#368]
https://nivo.rocks/storybook/

There doesn't seem to be any content in this section. There is a console error:
>Error while trying to use the following icon from the Manifest: https://nivo.rocks/favicon.ico (Resource size is not correct - typo in the Manifest?)

**Comment by plouc** [comment]
I've enabled https, which have enabled service workers, which seems to be the issue, I'm investigating

**Comment by plouc** [comment]
Fixed, you'll probably have to clear the website's cache though

**Comment by pfreedmanJG** [comment]
Great, that's done the trick 👍
