### ISSUE TITLE
Can't handle negative value in ScatterPlot 

### ISSUE THREAD

**Issue by AhyoungRyu** [plouc/nivo#374]
I saw some related issues like #249 and #337 but I think it'll be nicer there is safer workaround to handle this kind of situation. 
In my case, Chrome browser just becomes unresponsive.

 - With ScatterPlot Canvas api 
<img width="908" alt="screen shot 2018-12-07 at 11 45 30 pm" src="https://user-images.githubusercontent.com/10060731/49682407-e83cd600-faf6-11e8-9924-05ccdedcc20a.png">

 - With SVG api 
<img width="866" alt="screen shot 2018-12-07 at 11 46 20 pm" src="https://user-images.githubusercontent.com/10060731/49682408-e8d56c80-faf6-11e8-861c-3b8dba7705e5.png">

**Comment by plouc** [comment]
#249 and #337 are very different from this one as they relate to the scales provided by nivo (x/y), the sizing function is the user's responsibility and not something provided by the API.

**Comment by AhyoungRyu** [comment]
@plouc Yeah right. I found the workaround for my case. Closing this and #375
