### ISSUE TITLE
Axis legend not working for HeatMapCanvas

### ISSUE THREAD

**Issue by ilovepku** [plouc/nivo#376]
Axis legends are not working for HeatMapCanvas, even in the official examples. 
Though it has the value "country" for axisRight, axisBottom and axisLeft in settings, none are actually shown.

While in the SVG version, Axis legends work reasonably well, though their responsiveness seem a bit off, especially for axisTop and axisRight.

**Comment by plouc** [comment]
@ilovepku, the canvas implementation lacks some features that the SVG implementation provides.
When you say:
> Axis legends work reasonably well, though their responsiveness seem a bit off, especially for axisTop and axisRight
What do you mean? can you reproduce a sample example on codesandbox? Also if you're running your app in development mode, the performance is really different as React enable some checks which are disabled in production mode.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/512/commits/d657d0d59770b78ca30706422e5b11c13ff04f38
