### ISSUE TITLE
Text wrap for TreeMap label

### ISSUE THREAD

**Issue by ilovepku** [plouc/nivo#377]
It seems like TreeMap's label property can only render strings as opposed to html entities, and adding "\n" to the strings doesn't break lines either. Is there a way to wrap long label texts inside the tiles?

**Comment by plouc** [comment]
@ilovepku, if you use SVG implementation, it doesn't behave like HTML, there are already similar opened issues, as `TreeMap` also supports HTML implementation, you should use it if you want to use regular HTML.
