### ISSUE TITLE
Treemap events (mouseover, mouseenter and mouseleave)

### ISSUE THREAD

**Issue by abumuawiyah** [plouc/nivo#381]
Hi Nivo team.
I have checked the documentation and I didn't see mouseover, mouseenter & mouseleave events/callbacks. 

Those events is needed for us to showing up popover that have a details about item hovered and links.

**Comment by simongis** [comment]
Some additional context:

On a table component, we have full control over styling and adding extra links [into the popover/Tooltip](https://github.com/bgtdevhub/housekeeping/blob/70e2bb6fb449b7621f06f0240669c9d20744a36d/src/pages/Profile/PopupDetail/PopupDetail.js)

![image](https://user-images.githubusercontent.com/2769383/50040176-a7166a00-0092-11e9-80d7-6cfc702ba9c9.png)

But we have not been able to repeat this [with the Nivo TreeMap component](https://github.com/bgtdevhub/housekeeping/blob/master/src/components/Chart/Treemap/Treemap.js):
![image](https://user-images.githubusercontent.com/2769383/50040181-c614fc00-0092-11e9-89d6-5c24ba4b51e7.png)

**Comment by plouc** [comment]
Implemented via https://github.com/plouc/nivo/pull/555, and will be available in the next release.
