### ISSUE TITLE
Feature Request: Add label to Marker

### ISSUE THREAD

**Issue by danpettay** [plouc/nivo#386]
Hello,
Is there a built-in way to add a static label at a particular (x,y) coordinate? I would like to add a label to a marker I added to a Bar chart. I saw labels were added to the markers in the storybook stories (ex: https://nivo.rocks/storybook/?selectedKind=Bar&selectedStory=with%20marker&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs), but didn't see how it was done.

Love this library, great work!

**Comment by evalineBai** [comment]
I'm also interested in the answer to this. It seems like you can add a custom component as a marker but I'm wondering what the correct prop name is to add to the marker - thanks!

**Comment by danpettay** [comment]
@evalineBai I got around this issue by creating a custom legend for my chart (independent of the nivo legend), and specifying a label for the marker by its color
![image](https://user-images.githubusercontent.com/17413129/51341205-637a9b80-1a56-11e9-8808-7a836e0b0814.png)

**Comment by ryahadley** [comment]
This was in the source code under - [https://github.com/plouc/nivo/blob/master/examples/typescript/src/components/Line.tsx](url)

```
markers={[
    {
        axis: 'x',
        value: 4,
        legend: 'X marker a 4',
        lineStyle: {
            stroke: 'blue',
        },
        textStyle: {
            fill: 'blue',
        },
    },
    {
        axis: 'y',
        value: 4,
        legend: 'Y marker at 4',
        lineStyle: {
            stroke: 'red',
        },
        textStyle: {
            fill: 'red',
        },
    },
]}
