### ISSUE TITLE
Axis props should allow `null` in TypeScript

### ISSUE THREAD

**Issue by pete-otaqui** [plouc/nivo#388]
https://github.com/plouc/nivo/blob/27524f184ff338438291facac1b7ce2e762c8d21/packages/line/index.d.ts#L53

Seems like the type definitions only allow a valid `AxisProps` object, or `undefined`.  They do _not_ allow `null`, which (according to the docs) is the required value to completely disable the axes, since bottom and left are "on" by default, and providing `undefined` does not disable them.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/412
