### ISSUE TITLE
How to customise tooltip values?

### ISSUE THREAD

**Issue by abhijit-padhy** [plouc/nivo#390]
I have lot of answers with tooltip={tooltip} for tooltip formatting. But I am not clear what does {tooltip} means and how should it be written. #@nivo/pie #plouc

Please be more descriptive.

**Comment by MathiasFl** [comment]
Looking at the index.d.ts for @nivo/pie 
tooltip is defined as :

`tooltipFormat: string | ValueFormatter`

and ValueFormatter is defined as:

`export type ValueFormatter = (value: number) => string | number`

So if you want to create a dynamical tooltip that changes based on hovered value it could look like this.

`tooltipFormat={value =>
            Number(value).toLocaleString('en-US', {minimumFractionDigits: 2}) + '$'}`

**Comment by danpettay** [comment]
@MathiasFl's answer has worked on all the chart types I've used thus far (Line, Bar, Pie)

**Comment by plouc** [comment]
@abhijit-padhy, you often see `tooltip={tooltip}` because the storybook and website's examples are not able to display the code for nested components, however you can explore the storybook's source to see how it's implemented, for example https://github.com/plouc/nivo/blob/master/packages/bar/stories/bar.stories.js#L202

**Comment by plouc** [comment]
`tooltip` allows to customise the whole tooltip while `tooltipFormat` only acts on the value.

**Comment by DominicTobias** [comment]
I simply want to format the date in the tooltip so `tooltip` seems overkill but `tooltipFormat` never gets called for `ResponsiveLine` at least :(

**Comment by markdascher** [comment]
Looks like `yFormat` does the trick for line charts.

**Comment by ilirosmanaj** [comment]
@DominicTobias / @markdascher  , did you find any way to use tooltip for ResponsiveLine? yFormat works fine, but I cannot access the whole object using it

**Comment by znoland3** [comment]
This helped me with custom tooltips - https://github.com/plouc/nivo/issues/149#issuecomment-593617357

**Comment by DamiToma** [comment]
My tooltips show the whole object ('x: value, y: value'). I've tried to use options found on examples but nothing worked. I'm not sure what's going on but the function I pass to `tooltipFormat` is never called on a `ResponsiveLine`, just tried to always return 'hi' but I still get object keys and values. What could be wrong? I'm not using tooltip related options if not for the theme, which I assume is not related to labels.
