### ISSUE TITLE
Adding `defaultCurrentNode` prop in HeatMap

### ISSUE THREAD

**Issue by ncknuna** [plouc/nivo#393]
We have a need to call out a specific row/column/cell in a heatmap based on external data (e.g. "this is the particular cell that's in effect based on your current settings"), and I thought that the best way to do that would be to allow providing a `defaultCurrentNode` prop which would get used in the `computeNodes` process here (https://github.com/plouc/nivo/blob/262a8ee96bb870fe388e64d1453248aed94bf445/packages/heatmap/src/computeNodes.js#L58) if `currentNode` is falsy

Would you be open to a PR that adds this? Or is there an alternative you would prefer?

**Comment by plouc** [comment]
Yes, I'm ok with this approach with the current implementation, but I'd like to change the heatmap behaviour as it could be more versatile to have the ability to customise node attributes the way we want (using onMouseEnter/onMouseMove/onMouseLeave + overrides).

**Comment by ncknuna** [comment]
@plouc Could you elaborate a bit more on your desired implementation? If it's not too big of a lift I'd consider taking some of it on

**Comment by plouc** [comment]
The idea is to completely remove the currentNode from the state and let users decide the styles of the nodes from the outside, for example you could have default color/border/size and have the ability to override those properties using an `overrides` property for example which will accept a matcher and properties, the same way patterns and gradients work, then you could use mouse event to define the matcher managing the state by yourself, it will require more customisation but will allow to cover almost every use cases.

**Comment by ncknuna** [comment]
Ah, I see... that does seem like a bigger lift. I'll just submit a PR for the easy fix with the current implementation for now :)
