### ISSUE TITLE
Issue of d3-delaunay module

### ISSUE THREAD

**Issue by SokichiFujita** [plouc/nivo#395]
[`d3-delaunay`](https://github.com/d3/d3-delaunay) which is dependent by `@nivo/scatterplot` and `@nivo/voronoi` is exposed with a lot of current experimental ECMAScript features (e.g. exponential operator) in spite of **production build**.  There are no problem if it's just source code, however it's a [dist file](https://github.com/d3/d3-delaunay/releases/tag/v4.1.5). 

Furthermore, older version ("0.50.0") of the `@nivo/scatterplot` didn't cause the issue because it didn't use `d3-delaunay` as follows. 
https://github.com/plouc/nivo/commit/a17dfedf502a75b969e205620231a5c1fb6a1d67#diff-f2a678a861e8c489821af95d1ddffc41

Thus now upgrading of `@nivo/scatterplot` from v0.50.0 or under breaks a backward compatibility, legacy browser support and so on.  Do you have some idea or plan to avoid the issue?

**Comment by plouc** [comment]
I don't know what to do… I've seen you've filled an issue on the repo, but it seems the author is not willing to ship a compatible package :/
He has to maintain a bunch of repos though, so maybe he's more comfortable with the current setup, I'll see if I can submit a PR which add support for babel (as it's almost the setup I currently use for nivo :)).

**Comment by plouc** [comment]
In fact other d3 packages have also dropped support for older browsers, nivo being tightly coupled to d3, there's not much to do… you could try to add the required polyfills or transform the packages using babel for example.

**Comment by plouc** [comment]
Please be aware that there might be other BC breaks until nivo reach v1.
