### ISSUE TITLE
Tooltip Overflows Browser Window

### ISSUE THREAD

**Issue by tarecord** [plouc/nivo#396]
For graphs that are displayed close to the edge of the window, current tooltip position (#25) can cause tooltips to overflow the window.

![screen shot 2018-12-19 at 10 25 35 am](https://user-images.githubusercontent.com/6947218/50229501-7414f480-0378-11e9-99b6-cbbc40e4a72c.png)

**Comment by plouc** [comment]
I'm closing this in favor of https://github.com/plouc/nivo/issues/580

**Comment by serj-prog** [comment]
The issue still exists and https://github.com/plouc/nivo/issues/580 is still open. Is somebody going to work on it?
