### ISSUE TITLE
[THEMING] PropTypes validation for textSize can also be CSS-valid string

### ISSUE THREAD

**Issue by SanderVerkuil** [plouc/nivo#398]
The PropTypes validation of the fontSize appears to be too simplistic. When having the following theme:

```javascript
const theme = {
  axis: {
    legend: {
      fontSize: '1.2vmin',
    }
  }
}
```

I'm getting the warning that the fontSize should be a number. When inspecting the elements, the fontSize css attribute is correctly set to `1.2vmin` and it appears to be working just fine.

Is there a reason that the fontSize must be a number?

**Comment by plouc** [comment]
It's because of canvas which only support pixels unit.
