### ISSUE TITLE
Gradient for Line component (or Stream)

### ISSUE THREAD

**Issue by Kerumen** [plouc/nivo#40]
Is it possible to fill the area below the line with a gradient?

Example: http://recharts.org/#/en-US/api/AreaChart

**Comment by plouc** [comment]
For now it's not, charts use colors range for the sake of simple use.

**Comment by plouc** [comment]
@Kerumen, "javascript ninja", seriously????

**Comment by Kerumen** [comment]
@plouc ???

**Comment by plouc** [comment]
Even the most skilled devs I know do not call themselves ninjas, perhaps you're some kind of superhuman…

**Comment by plouc** [comment]
BTW, sorry, it's not related to this issue, which should be fixed (also supporting svg patterns).

**Comment by Kerumen** [comment]
![giphy-downsized](https://user-images.githubusercontent.com/5436545/29773173-7e3e974e-8bfc-11e7-81e8-42a88cacd112.gif)

**Comment by plouc** [comment]
Started something for the gradient support => http://nivo.rocks/#/guides/gradients, but it's not available for line chart for now, just on Stream.

**Comment by plouc** [comment]
Area support has been added to line chart https://github.com/plouc/nivo/pull/82

**Comment by dielduarte** [comment]
hey @plouc, any news related to linear gradients in an area?

**Comment by Eric0201** [comment]
with pie chart ? @plouc

**Comment by pnikitinsky** [comment]
up

**Comment by algebrathefish** [comment]
Hi, the gradient on line chart area is not working


    <Line
            data={data}
            width={700}
            height={310}            
            xScale={{ type: 'point' }}
            yScale={{ type: 'linear', stacked: false, min: 0, max: 400 }}
            curve="linear"
            axisTop={null}
            axisRight={null}
            axisBottom={null}
            axisLeft={null}
            enableGridX={false}
            enableGridY={false}
            colors={d => d.color}
            enablePoints={false}           
            enableSlices="x"            
            enableArea={true}
            areaBlendMode="screen"
            areaOpacity={0.16}
            keys={['react', 'vue', 'elm']}
            defs={[{
              id: 'gradientC',
              type: 'linearGradient',
              colors: [
                { offset: 0, color: '#fff' },
                { offset: 100, color: '#000' },
              ],
            },]}
            fill={[
              { match: '*', id: 'gradientC' },
            ]}
            useMesh={true}
    />

This is my code, the gradient is not being rendered whatsoever.

**Comment by tomaswitek** [comment]
There is an [opened PR](https://github.com/plouc/nivo/pull/844) which seems to resolve this issue.
