### ISSUE TITLE
Unable to install forked version of repo as dependency

### ISSUE THREAD

**Issue by ByronBecker** [plouc/nivo#403]
Thanks for the great library! I'm interested in contributing some features, but am running into an issue adding my forked version of the nivo library to my project while a feature I added is in a PR.

From my project, I am installing nivo as such

`npm i <username>/<reponame>#branchname`

The installed module ends up looking significantly different than the npm published version of your library, and therefore I'm not able to import components into my project, receiving 
`Module not found: Error: Can't resolve 'nivo' in ...` errors. 

Are there any build scripts that I need to run and push up to github in order to install the library directly from a personal fork on github (not from a module published to npm)?

**Comment by plouc** [comment]
Yes, you need to build the package using `make package-build-bar` for example, and then link it to your project (e.g. yarn link @nivo/bar).
nivo is no more a single package, the older mono-package is still on npm but is not maintained anymore.
You won't be able to install the package directly from a github repo as the compiled code isn't versioned, hence the *link* usage.

**Comment by plouc** [comment]
I've seen you've just forked the sankey package, but you should fork the whole repo as it contains commands used to compile the code and other things such as testing env/libs, linters…

**Comment by ByronBecker** [comment]
I forked the whole repo at https://github.com/ByronBecker/nivo

What I ended up doing was making the sankey package, then pushing it to a sankey specific repo https://github.com/ByronBecker/-nivo-sankey so that I can pull it into projects easily

**Comment by plouc** [comment]
Oh ok missed the other one :)

**Comment by ByronBecker** [comment]
Thanks for the response and help, Fyi the changes I made are in https://github.com/plouc/nivo/pull/401
