### ISSUE TITLE
Make sure examples work with Typescript.

### ISSUE THREAD

**Issue by burtonator** [plouc/nivo#408]
I don't think the examples on the site work with Typescript.  Getting a lot of type errors and having to comment out things.

I verified that I'm on 0.52.0 

BTW.. Nivo rocks.. very excited about this. Migrating from chartjs and this has all the key charts I need.

**Comment by ByronBecker** [comment]
@burtonator It's in progress... See https://github.com/plouc/nivo/issues/197

**Comment by plouc** [comment]
@burtonator, I'm closing this in favor of https://github.com/plouc/nivo/issues/197, if you can report the error you had, it would be really useful. As the library isn't written in TypeScript, unfortunately definitions aren't always up-to-date. 
Otherwise, contributions are welcome ;)
