### ISSUE TITLE
Setting animate = true results in "laggy" animation

### ISSUE THREAD

**Issue by ByronBecker** [plouc/nivo#409]
I'm currently having issues with the performance of the ResponsiveSankey animation transitions, having set the animate property to true. Sometimes I see delays of 1-1.5 seconds when switching hover between links. When I set animate to false, I see no such performance issues. Since the demo on storybook performs without any issues, it makes me think that the issue is on my side. I've only used this library so far in my development environment (using webpack-dev-server with hot reloading), so I'm not sure if others are having the same issue, and if it has to do more with my webpack setup than the library. 

If anyone has any suggestions/reassurances, let me know.

The following is my webpack config

```
const config = {
    entry: {
        app: SRC_DIR + '/app/index.tsx'
    },
    output: {
        path: DIST_DIR,
        filename: 'bundle.js'
    },
    devtool: 'inline-source-map',
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
        hot: true,
        port: 8080
    },
    mode: 'development',
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          loaders: ['babel-loader'],
        },
        {
            test: /\.css$/,
            loaders: ['style-loader', 'css-loader']
        },
        {
            test: /\.(ts|tsx)$/,
            loader: 'ts-loader'
        }
      ]
    },
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx']
    },
    plugins: [
       new HtmlWebPackPlugin({
           title: 'Dev - React_Nivo_Testing',
           template: './src/index.html',
           filename: './index.html'
       }),
       new webpack.HotModuleReplacementPlugin()
    ] 
  };
```

**Comment by plouc** [comment]
@ByronBecker, it can be laggy if you're using the development version of react, please make sure to use the production version to check performance.
If you still experience performance issues, you could disable custom mix-blend-mode, gradients…

**Comment by ananth-chiselkraft** [comment]
on a real time line graph, animate causes tickLabels to fly from left
