### ISSUE TITLE
IE11 endsWith polyfill

### ISSUE THREAD

**Issue by jwhooper** [plouc/nivo#41]
I tried to look at the demo at http://nivo.rocks/ using IE11

Error on endsWith:

export var closedCurvePropKeys = curvePropKeys.filter(function (c) {
	**return c.endsWith('Closed');**
});

Polyfill, if you care to add, or you could use ES6-shim as there might be more issues:

if (!String.prototype.endsWith)
  String.prototype.endsWith = function(searchStr, Position) {
      // This works much better than >= because
      // it compensates for NaN:
      if (!(Position < this.length))
        Position = this.length;
      else
        Position |= 0; // round position
      return this.substr(Position - searchStr.length,
                         searchStr.length) === searchStr;
  };

IE sucks, but some of us are forced to use it exclusively at work.

Some blabbing about the issue:
https://www.sitepoint.com/community/t/endswith-issue-in-ie11/233838

**Comment by plouc** [comment]
In fact, I thought `create-react-app` included this kind of polyfill

**Comment by plouc** [comment]
Added the polyfill
