### ISSUE TITLE
Conditionally changing the label text color

### ISSUE THREAD

**Issue by lkovesdi** [plouc/nivo#413]
Is there a way to change the color of the text on the bubbles conditionally with props or a function?

**Comment by danpettay** [comment]
Are you referring to the labels found on the axes/data points (known as "Dot Labels" for Line charts)? Or the labels within tooltips? Not sure which chart types you're using but you're currently able to provide custom tooltips for some chart types (Bar, Line), but I'm not sure about all of them.

**Comment by plouc** [comment]
@lkovesdi which component are you using? can you please describe the expected result? and can you please also setup an example of your current implementation on codesandbox?

**Comment by lkovesdi** [comment]
@plouc, Sorry about that but please regard. Our direction has changed since I wrote that and we created something vastly different. I appreciate your response though!

It was the bubble chart. We were trying to send in our own colors on different conditions.
