### ISSUE TITLE
Way to disable LiceSlicesItem vertical line?

### ISSUE THREAD

**Issue by rpearce** [plouc/nivo#414]
Hiya! I'm curious if there will eventually be a way to disable this `LineSlicesItem` code without disabling all interactivity?

https://github.com/plouc/nivo/blob/master/packages/line/src/LineSlicesItem.js#L31-L39

Here's the use-case for it (`enableGridX={false}`):

<img width="978" alt="image" src="https://user-images.githubusercontent.com/592876/50867841-9f3bb280-1411-11e9-810f-e07995199ad0.png">

**Comment by plouc** [comment]
You'll now be able to do this using the theme, it won't be disabled, but you can make it invisible:

```
<Line
    // ...
    theme={{ crosshair: { line: { strokeOpacity: 0  } } }}
/>
```
