### ISSUE TITLE
Line chart is slow with many points

### ISSUE THREAD

**Issue by Thebarda** [plouc/nivo#415]
Hello and thank you for this project !

I have a line chart with 5 lines, each with about 400 points and there is a leak CPU consumption when I'm moving the mouse through the chart to display tooltip. On chromium, it is between 80% and 120%.

I ran the React profiler and here is the result : 
![screenshot from 2019-01-10 10-52-36](https://user-images.githubusercontent.com/12515407/50963463-11250200-14cd-11e9-89cc-39997eef147d.png)

It seems there is a tooltip render each when mouse is moving over the graph (a render per traveled point)

Is there a way to roughly (or slightly) reduce the number of tooltip's render ?

**Comment by johnolos** [comment]
Just an idea. You're able to give a function for tooltip-prop on Line.

Giving something along the lines as `React.memo(() => React.ReactNode)` for this tooltip, do you experience the same performance hit?

**Comment by plouc** [comment]
@johnolos nivo already makes heavy use of memoization (using recompose instead of the new `memo()` helper), but the _problem_ is the x/y props will change, so it doesn't use the cached version.
@Thebarda are you running the production version of React?

**Comment by Thebarda** [comment]
@plouc I ran both debug and production version of React. In production, the slowdown is roughly reduced and almost inexistant.

**Comment by plouc** [comment]
I guess we can close this then?

**Comment by Thebarda** [comment]
Yeah, I will close this. 
But there is a problem of re-rendering on tooltips and It could be fine a way to avoid these UI updates ;)

**Comment by plouc** [comment]
Well, that's not really a problem, that's how it work, when you move through the graph the tooltip updates depending on the mouse position.

**Comment by uttam-thummar** [comment]
Hey, can you please tell me the detailed solution as I am facing the same problem and can't find a suitable solution that works?
