### ISSUE TITLE
help wanted: API Client: `"\"legendPosition\" must be one of [start, center, end]…`

### ISSUE THREAD

**Issue by indvstry** [plouc/nivo#418]
When using the API Client and try to generate bar charts https://nivo.rocks/bar/api the result is a following error:
```
{
  "errors": [
    "\"legendPosition\" must be one of [start, center, end] (axisBottom.legendPosition)",
    "\"legendPosition\" must be one of [start, center, end] (axisLeft.legendPosition)"
  ]
}
```

if we disable the `axisBottom` and `axisLeft`  from the Grid & Axes tab, then the chart is generated without any errors. I see no options to set the position to `[start, center, end]` from the API Client am I missing something?

**Comment by plouc** [comment]
@indvstry the http API isn't up to date with the latest version of nivo packages, that's why it's rejected for now.

**Comment by iarroyo5** [comment]
The types are also incompatible, for example into the `BarProps` "legenPostion" property accepts this type values ` "start" | "center" | "end" | undefined;`

```
 export type Axis = Partial<{
        format: string | LabelFormatter
        legend: string
        legendOffset: number
        legendPosition: 'start' | 'center' | 'end'
        orient: 'top' | 'right' | 'bottom' | 'left'
        tickPadding: number
        tickRotation: number
        tickSize: number
        tickValues: number | string[] | number[]
    }>
```

but when you render it with `center` value it throws and exception saying that `middle` is the correct value to use:

<img width="832" alt="screen shot 2019-01-31 at 16 29 53" src="https://user-images.githubusercontent.com/5355188/52069007-cea79000-2575-11e9-9b7e-14e443ac0e6c.png">

**Comment by plouc** [comment]
I'm closing this in favor of https://github.com/plouc/nivo/issues/263, as both issues are about mismatch between the deployed demo packages versions and the ones used for the website.
