### ISSUE TITLE
Pass datum props to dotSymbol

### ISSUE THREAD

**Issue by drj17** [plouc/nivo#421]
It would be very helpful if we could pass datum info to custom dotSymbol function so that we could return a different symbol based on the data point. Right now, it only receives size, color, etc.

**Comment by jjsub** [comment]
@plouc  I got it, 
All I had to do is to extract it from the args when defining the CustomSymbol function: 

const CustomSymbol = ({ size, color, borderWidth, borderColor, `datum` }) => {}

**Comment by jjsub** [comment]
@plouc I would love to help provide some examples for the docs or to update it in any way that would be helpful.
