### ISSUE TITLE
Responsive Bar not working in React v15.6

### ISSUE THREAD

**Issue by dandro32** [plouc/nivo#422]
Using basic implementation:

```
import { ResponsiveBar } from '@nivo/bar';
<ResponsiveBar data={data} />
```
Got Check the render method of `Axes` error.
![image](https://user-images.githubusercontent.com/32488988/51102271-97e42280-17de-11e9-99a1-5aee1c3d554c.png)

It's a old project using React v.15.6
I would be very gratefull for some tips
Thank you

**Comment by szymonmal** [comment]
Axit uses PureComponent. I would suggest updating react and react-dom packages to newest one and trying again.

**Comment by dandro32** [comment]
Newest react fix this issue, my bad :)
