### ISSUE TITLE
Returning an <svg> as a custom symbol to line causes it to be drawn in the wrong location

### ISSUE THREAD

**Issue by drj17** [plouc/nivo#427]
Maybe this is something that I'm just doing wrong, but when I return an  <svg> to customSymbol in Line it draws it offset from the center, unlike if I return a <g>

Example: 
```
 <svg viewBox="64 64 896 896" className="" data-icon="check-circle" width="24px" height="24px" fill="currentColor" aria-hidden="true"><path d="M699 353h-46.9c-10.2 0-19.9 4.9-25.9 13.3L469 584.3l-71.2-98.8c-6-8.3-15.6-13.3-25.9-13.3H325c-6.5 0-10.3 7.4-6.5 12.7l124.6 172.8a31.8 31.8 0 0 0 51.7 0l210.6-292c3.9-5.3.1-12.7-6.4-12.7z"></path><path d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm0 820c-205.4 0-372-166.6-372-372s166.6-372 372-372 372 166.6 372 372-166.6 372-372 372z"></path></svg>

```
Results in this (the green check circle is a <g> element):
![screen shot 2019-01-16 at 4 38 54 pm](https://user-images.githubusercontent.com/13426126/51280302-52298480-19ad-11e9-8210-99a8cd20141c.png)

Is there a way to manipulate is to center or is this something not supported by nivo?

**Comment by GBarkhatov** [comment]
Hello @drj17 
My custom svg icon if 40x40 px, I just applied

```
x='-20'
y='-20'
```

to main svg element:

https://i.imgur.com/DoIqaxb.png

**Comment by drj17** [comment]
@GBarkhatov Thanks! That does exactly what I need. I don't use svgs very often and I was unaware of that property.
