### ISSUE TITLE
Hide Slice if value is equal 0

### ISSUE THREAD

**Issue by fmturati** [plouc/nivo#431]
Hello, I'm trying to hide the element checking if the value is equal 0 but it's not working very well... It keeps showing or 0 or null. I would like to know if there is another way to do it inside the plugin... Thanks!

**Comment by jithinbalakrishnan** [comment]
@plouc 
I am facing the same issue, if value is 0 , slide is hiding but label is showing 0.
is there any way to hide the label if value is 0 ?
![Screen Shot 2020-03-27 at 12 20 27 PM](https://user-images.githubusercontent.com/29042311/77729808-8e328d80-7025-11ea-8bee-08b5317c6d55.png)
