### ISSUE TITLE
How to wrap legend texts in pie chart?

### ISSUE THREAD

**Issue by abhijit-padhy** [plouc/nivo#433]
My legend texts are bit large which get overflow in mobile view. Is there any way to wrap the texts to new line?

**Comment by plouc** [comment]
Please have a look at https://github.com/plouc/nivo/issues/353

**Comment by mgrip** [comment]
@plouc this is not the same as https://github.com/plouc/nivo/issues/353 - https://github.com/plouc/nivo/issues/353 addresses custom rendering of _tick labels_ for the bar chart. As https://github.com/plouc/nivo/issues/204, https://github.com/plouc/nivo/issues/791, https://github.com/plouc/nivo/issues/616 all point out, there is no way currently to provide a custom renderer for legend items. I'm pretty sure this means that there's no way currently to solve text wrapping for legend items, in any chart type.

If a custom renderer was provided (similar to ticks), the approach outlined in https://github.com/plouc/nivo/issues/353 could then be used

**Comment by nhanpdnguyen** [comment]
After digging the issues, I've found an approach from @wyze https://github.com/plouc/nivo/issues/204#issuecomment-567912924
You will need to create a separate Layer for rendering legend. I'll take a try to see it it works

**Comment by cheeyang** [comment]
I faced this issue too, probably a little late but here's how I got LEGENDS (Not tick labels) to wrap -- I overrode the legends prop to display 2 rows in this case: 

```
const legendProps =
    {
      anchor: 'bottom',
      translateY: 50,
      direction: 'row',
      itemWidth: 100,
      itemHeight: 26,
      itemsSpacing: 60,
      itemOpacity: 0.8,
      symbolShape: 'square',
    };
```

```javascript
<ResponsiveLine
         ... // other props
         data={filteredChartData}
         colors={seriesColors}
         legends={
            filteredChartData && filteredChartData.length <= 6
              ? [
                  {
                    ...legendProps,
                    translateY: 25,
                    symbolSize: 18,
                    itemsSpacing: 60,
                  },
                ]
              : [
                  {
                    ...legendProps,
                    symbolSize: 10,
                    itemsSpacing: 25,
                    translateY: 30,
                    data: filteredChartData
                      .slice(0, Math.floor(filteredChartData.length / 2))
                      .map((cur, index) => ({
                        id: cur.id,
                        label: cur.id,
                        color: seriesColors
                          .slice(0, Math.floor(filteredChartData.length / 2))[index],
                      })),
                  },
                  {
                    ...legendProps,
                    symbolSize: 10,
                    itemsSpacing: 25,
                    translateY: 50,
                    data: filteredChartData
                      .slice(Math.floor(filteredChartData.length / 2))
                      .map((cur, index) => ({
                        id: cur.id,
                        label: cur.id,
                        color: seriesColors.slice(Math.floor(filteredChartData.length / 2))[index],
                      })),
                  },
                ]
          }
/>

**Comment by KarlaLGA** [comment]
> I faced this issue too, probably a little late but here's how I got LEGENDS (Not tick labels) to wrap -- I overrode the legends prop to display 2 rows in this case:
> 
> ```
> const legendProps =
>     {
>       anchor: 'bottom',
>       translateY: 50,
>       direction: 'row',
>       itemWidth: 100,
>       itemHeight: 26,
>       itemsSpacing: 60,
>       itemOpacity: 0.8,
>       symbolShape: 'square',
>     };
> ```
> 
> ```js
> <ResponsiveLine
>          ... // other props
>          data={filteredChartData}
>          colors={seriesColors}
>          legends={
>             filteredChartData && filteredChartData.length <= 6
>               ? [
>                   {
>                     ...legendProps,
>                     translateY: 25,
>                     symbolSize: 18,
>                     itemsSpacing: 60,
>                   },
>                 ]
>               : [
>                   {
>                     ...legendProps,
>                     symbolSize: 10,
>                     itemsSpacing: 25,
>                     translateY: 30,
>                     data: filteredChartData
>                       .slice(0, Math.floor(filteredChartData.length / 2))
>                       .map((cur, index) => ({
>                         id: cur.id,
>                         label: cur.id,
>                         color: seriesColors
>                           .slice(0, Math.floor(filteredChartData.length / 2))[index],
>                       })),
>                   },
>                   {
>                     ...legendProps,
>                     symbolSize: 10,
>                     itemsSpacing: 25,
>                     translateY: 50,
>                     data: filteredChartData
>                       .slice(Math.floor(filteredChartData.length / 2))
>                       .map((cur, index) => ({
>                         id: cur.id,
>                         label: cur.id,
>                         color: seriesColors.slice(Math.floor(filteredChartData.length / 2))[index],
>                       })),
>                   },
>                 ]
>           }
> />
> ```

This was incredibly helpful!! Thank you @cheeyang

**Comment by pedroraimondi** [comment]
If you are seeking one way to fix this issue...I have a straightforward and dumb way to do this...man, just format de data that you use like your keys...I really can't believe that I didn't consider this earlier...

``const ellipsedLabel = (label) => label.length > 25 ? `${label.slice(0, 25)}...` : label; ``

``
const pieChartData = dataContent?.timeByContent?.map(({ _id, label, percent: value }) => ({
id: _id, 
label: ellipsedLabel(label), 
value
})) || []
``

**Comment by thomas4t** [comment]
Based on answers above - I made a general helper which can handle 1-n rows. Keep in mind the more rows you have, Y margins of widget have to increased.

```typescript
import { LegendProps } from '@nivo/legends'

interface NivoWidgetDataEntity {
  id: string | number
  value: number
  label?: string
}

const baseLegendProps: LegendProps = {
  anchor: 'bottom',
  direction: 'row',
  itemWidth: 150,
  itemHeight: 26,
  itemTextColor: '#999',
  symbolShape: 'circle',
}

export const splitLegendData = (data: NivoWidgetDataEntity[], colors: string[], maxRowLength: number): LegendProps[] => {
  const numberOfRows = Math.ceil(data.length / maxRowLength)
  const splitData: LegendProps[] = []

  for (let row = 0; row < numberOfRows; row++) {
    const rowData = data.slice(row * maxRowLength, (row + 1) * maxRowLength)
    const rowColors = colors.slice(row * maxRowLength, (row + 1) * maxRowLength)
    const newRow = {
      ...baseLegendProps,
      symbolSize: 10,
      itemsSpacing: 25,
      translateY: 50 + row * baseLegendProps.itemHeight,
      data: rowData.map((curr, index) => ({
        id: curr.id,
        label: curr.id,
        color: rowColors[index],
      })),
    }
    splitData.push(newRow)
  }

  return splitData
}

```
