### ISSUE TITLE
Total inside donut (pie variation)

### ISSUE THREAD

**Issue by taschetto** [plouc/nivo#434]
Greetings! Congratulations for this wonderful library.

Is it possible to render something inside a donut chart (pie variation)? Something like this:

![https://i.stack.imgur.com/6MdV3.png](https://i.stack.imgur.com/6MdV3.png)

If so, any ideas on how to achive something like this?

Thanks in advance.

**Comment by Eric0201** [comment]
i have same question too

**Comment by plouc** [comment]
Otherwise you can wrap you chart inside a div and add an extra div using an higher z-index on top of the chart, but don't forget to disable events for that div though, using `pointer-events: none;` in order to have the tooltip working.

**Comment by plouc** [comment]
I've created an example of this approach, you can put whatever you want inside the extra div => https://codesandbox.io/s/w27xwy0xlk

**Comment by kaeland** [comment]
@plouc Hi, this is an excellent library. Thank you for all the work you've put into making this! 

Is the layered approach, mentioned above, ready for use with pie charts?

**Comment by thisizkp** [comment]
@kaeland I don't think it supports layers yet - https://github.com/plouc/nivo/blob/master/packages/pie/src/Pie.js#L36

**Comment by wyze** [comment]
@kaeland The Pie chart doesn't support layers yet.

**Comment by kaeland** [comment]
Got it. Thank you all for such fast replies too!

**Comment by thisizkp** [comment]
@plouc @wyze How do we make the total render within the `SVG`? Is it possible now? Or do we have to wait until the layers are implemented?

**Comment by wyze** [comment]
Currently you would need to absolute position a div, or other element, in the middle of the chart. We haven't migrated pie chart to layers yet.

**Comment by climbingcode** [comment]
Is there any timeline available for layers in pie charts release?

**Comment by HerilS** [comment]
Is layers supported for the pie chart yet?

**Comment by wyze** [comment]
It is available in the latest version. Here is a storybook example: https://nivo.rocks/storybook/?path=/story/pie--adding-a-metric-in-the-center-using-a-custom-layer

**Comment by piehouserat** [comment]
is it possible to do the same with the ResponsivePieCanvas component?

**Comment by silvercondor** [comment]
using the storybook example but unable to change the text color

```
const CenteredMetric = ({ dataWithArc, centerX, centerY }) => {
        let total = 0
        dataWithArc.forEach(datum => {
            total += datum.value
        })

        return (
            <text
                x={centerX}
                y={centerY}
                textAnchor="middle"
                dominantBaseline="central"
                style={{
                    color:"#FFFFFF",
                    fontSize: '24px',
                }}
            >
                {total}
            </text>
        )
    }
```

still shows as black color

**Comment by silvercondor** [comment]
> 
> 
> using the storybook example but unable to change the text color
> 
> ```
> const CenteredMetric = ({ dataWithArc, centerX, centerY }) => {
>         let total = 0
>         dataWithArc.forEach(datum => {
>             total += datum.value
>         })
> 
>         return (
>             <text
>                 x={centerX}
>                 y={centerY}
>                 textAnchor="middle"
>                 dominantBaseline="central"
>                 style={{
>                     color:"#FFFFFF",
>                     fontSize: '24px',
>                 }}
>             >
>                 {total}
>             </text>
>         )
>     }
> ```
> 
> still shows as black color but fontsize adjustment works

Answering my own question in case anyone ends up in the same situation as me

The color should be under fill prop.

Final answer 

```
const CenteredMetric = ({ dataWithArc, centerX, centerY }) => {
        let total = 0
        dataWithArc.forEach(datum => {
            total += datum.value
        })

        return (
            <text
                x={centerX}
                y={centerY}
                textAnchor="middle"
                dominantBaseline="central"
                fill='white'
                style={{
                    color:"#FFFFFF",
                    fontSize: '24px',
                }}
            >
                {total}
            </text>
        )
    }
```
