### ISSUE TITLE
Vertical Sankey

### ISSUE THREAD

**Issue by cl-evgenyb-rnd** [plouc/nivo#437]
Is there an easy way to rotate the Sankey diagram 90 degrees?

Something like this:
![image](https://user-images.githubusercontent.com/46893495/51611518-17cd6380-1f28-11e9-8f89-1ce27ec51bb8.png)

**Comment by plouc** [comment]
Not for now, but it could be interesting to have, however your example is more a dendogram (which is a work in progress).

**Comment by gpalrepo** [comment]
Listing here for the convenience of someone else who might have had a similar need:
Nivo now supports vertical layouts for Sankey diagrams. 
**Include a layout prop and pass either "vertical" or "horizontal" into it.**
