### ISSUE TITLE
SVG element in tooltipFormat

### ISSUE THREAD

**Issue by Egorzaa** [plouc/nivo#439]
I'm trying to insert svg element inside tooltip, but it shows [object Object]:
<img width="360" alt="screenshot 2019-01-24 at 14 13 57" src="https://user-images.githubusercontent.com/30752631/51674682-66d7cf00-1fe2-11e9-8f43-63d10f02629a.png">

My code:

<img width="725" alt="screenshot 2019-01-24 at 14 29 15" src="https://user-images.githubusercontent.com/30752631/51675338-75bf8100-1fe4-11e9-82e5-f1fb5906312c.png">

Is it possible to insert somehow such elements inside tooltip?
I will be very appreciate for any hints

**Comment by Tranzystor** [comment]
Just pass your `qwe` function to `Radar` without additional func:

`<Radar {...commonProperties} tooltipFormat={qwe} />`

**Comment by Egorzaa** [comment]
@Tranzystor, I tried to do this and got error: VM28584 checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `tooltipFormat` supplied to `Radar`.

**Comment by Tranzystor** [comment]
@Egorzaa  here is code sandbox example: [click](https://codesandbox.io/s/qv080o1mrj)

there is a `svg` element in `tooltipFormat` as you wish
