### ISSUE TITLE
Wrong radar rendering

### ISSUE THREAD

**Issue by Egorzaa** [plouc/nivo#440]
On my radar some values can be zeroes. In this case radar renders with some distortions(look on the center): 
<img width="508" alt="screenshot 2019-01-24 at 14 23 35" src="https://user-images.githubusercontent.com/30752631/51675089-b9fe5180-1fe3-11e9-8cab-a3642345da6e.png">
Is it possible to fix this problem somehow?
I will be very appreciate for any hints

**Comment by Tranzystor** [comment]
Could you provide code sample with data set?

**Comment by Egorzaa** [comment]
`//data set:

[
    {
        description: "Frontend"
        group: "Expertise"
        id: 1
        name: "Frontend"
        scoreMax: 5
        status: "Open"
        Твой уровень: 0
    },
.....
]

//Radar component:

<ResponsiveRadar {...design} data={newData} gridLabel={gridLabel} tooltipFormat={tooltipFormat} />

//design:

export default {
    keys: ['Твой уровень'],
    indexBy: 'name',
    maxValue: 5,
    margin: {
        top: 120,
        right: 100,
        bottom: 80,
        left: 100,
    },
    curve: 'cardinalClosed',
    borderWidth: 2,
    borderColor: 'inherit',
    gridLevels: 5,
    gridShape: 'circular',
    gridLabelOffset: 70,
    enableDots: true,
    dotSize: 5,
    dotColor: 'inherit',
    dotBorderWidth: 0,
    dotBorderColor: '#ffffff',
    enableDotLabel: false,
    dotLabel: 'value',
    dotLabelYOffset: -12,
    colors: '#fdec4f',
    colorBy: 'key',
    fillOpacity: 0.4,
    animate: true,
    motionStiffness: 90,
    motionDamping: 15,
    isInteractive: true,
    legends: [
        {
            anchor: 'top-left',
            direction: 'column',
            translateX: -50,
            translateY: -120,
            itemWidth: 80,
            itemHeight: 20,
            itemTextColor: '#999',
            symbolSize: 12,
            symbolShape: 'circle',
            effects: [
                {
                    on: 'hover',
                    style: {
                        itemTextColor: '#000',
                    },
                },
            ],
        },
    ],
    theme: {
        grid: {
            stroke: '#eee',
            strokeWidth: 1,
        },
        tooltip: {
            maxWidth: '300px',
            table: {
                width: '240px',
            },
        },
        labels: {
            width: '30px',
            text: { width: '30px' },
        },
        legends: {
            text: { fontSize: 12 },
        },
    },
};
`

**Comment by plouc** [comment]
@Egorzaa, can you please format your code? (you can have a look [at this page](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) on how to do so). It might help to read it, thank you.

**Comment by Tranzystor** [comment]
@Egorzaa  And add whole data set, not only one element.

**Comment by plouc** [comment]
@Egorzaa the distortion is due to the curve you use, which is interpolated, you should use a linear interpolation then.
