### ISSUE TITLE
Label is not appearing on bar chart 

### ISSUE THREAD

**Issue by meganhng** [plouc/nivo#448]
The label doesn't appear on bars with 0 height, but has a value that is greater than 0. I need this value to show on the 0 height, and I was wondering if there is a work around for this issue. 

<img width="523" alt="screen shot 2019-01-25 at 1 52 27 pm" src="https://user-images.githubusercontent.com/35239417/52219112-08281600-286a-11e9-9d05-7d9f2d3e677d.png">

**Comment by plouc** [comment]
I close this in favor of https://github.com/plouc/nivo/issues/165 which is similar.

**Comment by AlexCLeduc** [comment]
Can you please re-open ? It's not really similar to #165 and meganhng has put out a PR that fixes this, you just forgot a special case when values are 0. We've been using her fix in production for months

**Comment by claytongomes** [comment]
the PR #454 fixes the issue.

**Comment by iSantPy** [comment]
> The label doesn't appear on bars with 0 height, but has a value that is greater than 0. I need this value to show on the 0 height, and I was wondering if there is a work around for this issue.
> 
> <img alt="screen shot 2019-01-25 at 1 52 27 pm" width="523" src="https://user-images.githubusercontent.com/35239417/52219112-08281600-286a-11e9-9d05-7d9f2d3e677d.png">

How did you do to put the label on the top of the bar without its height push it out the chart? I know LabelPlacement.Outside put it on top but when bar height is equal to chart plot it takes the label out of it and I can not see it. Thansk in advance!
