### ISSUE TITLE
How to create line chart with different intervals on X axis?

### ISSUE THREAD

**Issue by esomkin** [plouc/nivo#451]
Hi! I need to create `Line chart` with different intervals on X axis, for example

![graph](https://user-images.githubusercontent.com/1814853/52401642-39efe580-2ad3-11e9-8d03-7212c3cf90a6.png)

. Is it possible?

**Comment by mkbren** [comment]
@esomkin the axis objects provide a format() function you can use to build your own interval behavior. you can try passing into your chart properties something like:

`chartProps.axisBottom.format = x => axisBottomFormatFunc(x);`

the format() function exposes the x value being handled, and is called for each x value of your dataset. axisBottomFormatFunc is whatever logic you want to perform, maybe a counter or calculation determining which values you want to display and which you want to suppress. just return null for intervals you want to skip

**Comment by plouc** [comment]
@esomkin, do you mean for the grid?

**Comment by plouc** [comment]
@esomkin, does the reply from @mkbren helped? is this issue still relevant?

**Comment by esomkin** [comment]
@mkbren Thank you very much!  Your answer help me understand, how to exclude some points from axis and graph.

**Comment by esomkin** [comment]
> @esomkin, does the reply from @mkbren helped? is this issue still relevant?

@plouc Hi, issue is not relevant more
