### ISSUE TITLE
Lodash bundled into @nivo/*

### ISSUE THREAD

**Issue by JoviDeCroock** [plouc/nivo#452]
Is it intended for the whole lodash bundle to be included into `@nivo/*`, it bloats the package up to a really big size. Every sub has a dependency on `lodash`, it's hard to come by that all those utilities are used.

Can't we replace this with lodash-es so we can only bundle what's needed.

**Comment by plouc** [comment]
@JoviDeCroock, `lodash` is in the dependencies, however, the imports are scoped, for example, if you have a look at `@nivo/core@0.52.1` `cjs/nivo-core.js`, you'll see that lodash imports are all scoped.

**Comment by JoviDeCroock** [comment]
Hmm, that's strange when I run my bundle analyser it is fully in there. Then it probably gets required somewhere else. Thanks for the reply
