### ISSUE TITLE
Chart applying parent containers transform?

### ISSUE THREAD

**Issue by mkbren** [plouc/nivo#455]
I have a scenario where a Nivo chart's container needs to be scaled down to fit into the available screen real-estate but I'm getting some unexpected behavior when applying scaling transform. To show the scenario, here's an example of a material card (container) with a nivo chart child component:
![image](https://user-images.githubusercontent.com/14078462/52499582-9a912800-2b90-11e9-8ccd-5072d99adfec.png)

here is the card outlined, showing that a portion of it is overflowing behind the controls sheet:
![image](https://user-images.githubusercontent.com/14078462/52499632-b694c980-2b90-11e9-98c9-9d01d0863868.png)

I have some logic that will calculate a scaling ratio and apply it to the card. however, it seems that when the scaling transform is applied, the child chart 'double scales' when the component re-renders:
![image](https://user-images.githubusercontent.com/14078462/52501581-86035e80-2b95-11e9-9733-bcf5e6c76ace.png)

the chart should just remain at a 1:1 scaling ratio because the scaling is applying to the contain, but it appears that the chart applies the same scaling as the parent.

**Comment by plouc** [comment]
@mkbren, sorry but I don't really understand the context, what do you mean by `scaled`? can you please setup a running example on codesandbox?

**Comment by plouc** [comment]
Also, I have no idea of how _Material Card_ is implemented, please make sure the example doesn't use any external library appart from nivo as I won't be able to dig in those :)

**Comment by mkbren** [comment]
> what do you mean by scaled?

when I say scaled, I mean applying the css transform: scale() to the container.

> can you please setup a running example on codesandbox?

tried but wasn't able to isolate the behavior in a simple example. I'll close this out as the defect isn't blocking for me anymore and I can't provide a workable example
