### ISSUE TITLE
Sankey chart label customization

### ISSUE THREAD

**Issue by prahna** [plouc/nivo#456]
Hi all,
I saw in this pull request https://github.com/plouc/nivo/pull/77?_pjax=%23js-repo-pjax-container that this feature has been done in Oct 2017, but it's not in the main branch as of today. I would really want this feature in one of my projects. Is there any way I can get it ? 
Thank you all !

**Comment by plouc** [comment]
@prahna, at that time nivo was a single package which is now deprecated, it is still available in `@nivo/sankey`,  you can pass a function to the `label` property, for example `label={d => `${d.id} 😀`}`.
