### ISSUE TITLE
Circular dependency in sankey

### ISSUE THREAD

**Issue by Rekha-B** [plouc/nivo#459]
I have a circular dependency in sankey due to which graph browser gets hanged . Is there any way to resolve this issue?

**Comment by plouc** [comment]
Sorry, but as stated on the doc, it doesn't support this (because d3-sankey doesn't).

**Comment by Rekha-B** [comment]
oh Thank you so much for the imformation

**Comment by plouc** [comment]
I'm considering the migration to another sankey implementation as the repo doesn't seem to be maintained anymore and there are several interesting forks available, we'll see…

**Comment by Rekha-B** [comment]
sure

**Comment by nklswbr** [comment]
> Rekha-B

Circular dependencies would be a very useful feature. Is there an update on the status of the migration to another implementation?

**Comment by nklswbr** [comment]
> I'm considering the migration to another sankey implementation as the repo doesn't seem to be maintained anymore and there are several interesting forks available, we'll see…

Circular dependencies would be a very useful feature. Is there an update on the status of the migration to another implementation?
