### ISSUE TITLE
RealTimeChart example exists in Storybook but missing across the sources

### ISSUE THREAD

**Issue by rozhok** [plouc/nivo#460]
I've founded RealTimeChart here: https://nivo.rocks/storybook/?knob-curve=step&knob-stacked=true&selectedKind=Line&selectedStory=real%20time%20chart&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

But it's missing in the sources. 

What is the common way to make real-time data with nivo? Setup timer and update component state with new data?

**Comment by plouc** [comment]
It's available here, https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L281 using a timer

**Comment by rozhok** [comment]
Cool, thanks! Wondering why I wasn't able to find it out by classname using GitHub search...

**Comment by pencilcheck** [comment]
@plouc curious if you know where they are now? the link is giving me 404

**Comment by mmorrii** [comment]
more accurate link - https://github.com/plouc/nivo/blob/master/storybook/stories/line/Line.stories.tsx#L332
