### ISSUE TITLE
Custom Legends? or a fix for how legends on row are being displayed

### ISSUE THREAD

**Issue by emildatcu** [plouc/nivo#464]
I want to create a 'likert' scale using the stacked bar chart.
My problem is that you added that .reverse() on the legend items, based on keys/indexes, but only for 'column' display legend. You're not taking into consideration the 'row' display on the legend, so I get this:
![image](https://user-images.githubusercontent.com/42996811/53091324-54d24900-351a-11e9-91a3-219ec813d3b5.png)

Or, if I try to reverse the keys array, I get this, but neither one of them is helping me - and I think that is wrong - aka, bug!
![image](https://user-images.githubusercontent.com/42996811/53091082-b2b26100-3519-11e9-9ada-f6824ceccb4d.png)

I want the items in the legend to be displayed as they appear in the chart, not exactly opposed.

And It would be awesome as well to be able to provide custom labels for the legend... cause I don't want the key to be displayed in the legend... Or as a 'quick fix', add a legendLabel key to the data object.
And a place with working examples on how all these 'custom' features are supposed to be used would be helpful as well... the storybook doesn't work. and I lost half a day searching through github issues, without much luck...

Thanks.

**Comment by plouc** [comment]
@emildatcu can you please setup a running example on codesandbox? Thank you.

**Comment by emildatcu** [comment]
https://nivo.rocks/bar
stacked chart, legend at bottom, row.

the chart will display in the chart -> hot dog, burger, sandwich, kebab, fries, donut
the legend will display -> donut, fries, kebab, sandwich, burger, hot dog

**Comment by emildatcu** [comment]
@plouc ?

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/486/commits/95d1d1d19c2c02a6d8d801abdbddd115c36b580a
