### ISSUE TITLE
Grid render to many vertical lines

### ISSUE THREAD

**Issue by EduardoAC** [plouc/nivo#465]
Problem: The number of horizontal lines render doesn't match the `tickValues` counter.
![screenshot 2019-02-20 at 17 51 07](https://user-images.githubusercontent.com/2104706/53112889-34b18280-3538-11e9-92b2-d3b65647bb39.png)

As well the number of lines increase if I am creating my chart with a custom `min` and `max` values 
![screenshot 2019-02-20 at 17 47 24](https://user-images.githubusercontent.com/2104706/53112805-016ef380-3538-11e9-8404-324cd57116b4.png)

```
...
axisLeft: {
    orient: "left",
   axisLeft: {
    orient: "left",
    **tickValues: 5,**
    legend: "Amount",
    legendOffset: -50,
    format: value => `${Number(Math.floor(value / 1000)).toLocaleString('it-IT', {
        maximumFractionDigits: 0,
    })}K €`,
    legendPosition: "middle"
  },
    legend: "Amount",
    legendOffset: -50,
    format: value => `${Number(Math.floor(value / 1000)).toLocaleString('it-IT', {
        maximumFractionDigits: 0,
    })}K €`,
    legendPosition: "middle"
},
yScale: {
  type: "linear"
  min: 0,
  max: 30000,
}
```

**Comment by plouc** [comment]
axes and grids are two different things, please use `gridYValues`.

**Comment by EduardoAC** [comment]
Ok, I will try thanks

**Comment by yairEO** [comment]
These are horizontal lines... please edit it. I came here from google and got disappointed.
