### ISSUE TITLE
Sankey doesn't draw flows

### ISSUE THREAD

**Issue by jeffeld** [plouc/nivo#466]
Hi,

This is my first time using Nivo and my first foray into Sankey diagrams.

I have a simple data set:

`
{
    "nodes": [
        {
            "id": "Total number of emmployees",
            "color": "hsl(96, 70%, 50%)"
        },
        {
            "id": "Under 100K",
            "color": "hsl(237, 70%, 50%)"
        },
        {
            "id": "100K to 200K",
            "color": "hsl(181, 70%, 50%)"
        },
        {
            "id": "Over 200K",
            "color": "hsl(133, 70%, 50%)"
        }
    ],
    "links": [
        {
            "source": "Total number of emmployees",
            "target": "Under 100K",
            "value": 9990
        },
        {
            "source": "Total number of emmployees",
            "target": "100K to 200K",
            "value": 1456
        },
        {
            "source": "Total number of emmployees",
            "target": "Over 200K",
            "value": 71
        }
    ]
}
`

Nivo draws the nodes to scale (as expected) but doesn't draw the flows:

![image](https://user-images.githubusercontent.com/1257599/53169601-abe92400-35d5-11e9-8ce4-f8db39ef5619.png)

Am I doing something wrong? I copy and pasted the React code from the sample (modified the margin, and dropped the legend).

Many thanks,
Jeff

**Comment by plouc** [comment]
Hi @jeffeld,

Can you please setup an example on codesandbox?

**Comment by jeffeld** [comment]
Ah... I've found the cause. Spaces in the id causes it to "break". As the id is used as the label, this seems to be a bit restrictive.

Is there a way to attach a label separately to a node?

**Comment by plouc** [comment]
It works even with whitespaces, please have a look at https://codesandbox.io/s/km8ovqjj9r

**Comment by plouc** [comment]
Feel free to comment if you still encounter issue with this.

**Comment by jeffeld** [comment]
Thanks for the very fast response and help; much appreciated.

I am still seeing a reproducible problem, and I'm using Typescript (which I forgot to mention). I am only prototyping at the moment, and will dig in further later and comment back here if I encounter further issues.
