### ISSUE TITLE
Sankey orders nodes by link value

### ISSUE THREAD

**Issue by jeffeld** [plouc/nivo#467]
Hi,

Please see this example: [https://codesandbox.io/s/j4pjp8qvky](https://codesandbox.io/s/j4pjp8qvky)

If you look at the output diagram, it's clear that the data has been sorted by link value. My expectation was that the nodes would appear in the order they are in the array (as they have meaning in the context of my business problem).

Is there any way to achieve this behaviour?

Many thanks,
Jeff

**Comment by plouc** [comment]
This is the behaviour of d3-sankey which is used to build the Sankey components, this issue already exists here: https://github.com/plouc/nivo/pull/401.
