### ISSUE TITLE
Some colors theme of stream demo does not work

### ISSUE THREAD

**Issue by lyrixx** [plouc/nivo#471]
Hello,

On this page https://nivo.rocks/stream all colors after "set 3" render like that 
![image](https://user-images.githubusercontent.com/408368/53479788-1d175400-3a7a-11e9-8c72-e2952a774e55.png)

I guess something is wrong, but I don't know what 

Thanks

**Comment by plouc** [comment]
Thank you for reporting this bug! This has been fixed by https://github.com/plouc/nivo/pull/512/commits/7ceb480acbc01564c1d0307da4058f8fcdf3227c (not yet deployed though)
