### ISSUE TITLE
Custom dot size for each dot in Radar Chart..

### ISSUE THREAD

**Issue by pandaa880** [plouc/nivo#472]
I am trying to make a mix of Bubble Chart and Radar Chart. I need to set the size dots in radar chart dynamically. Can anyone point me in a right direction ? Or It is simply can't be done ? Or Do i have to write it from scratch using D3 ?

**Comment by plouc** [comment]
It's not supported on the Radar chart, but if you want to contribute, you could make the chart accept both a number (static) or a function which receive the node data to compute the size:
- https://github.com/plouc/nivo/blob/master/packages/radar/src/Radar.js#L217
- https://github.com/plouc/nivo/blob/master/packages/radar/src/RadarDots.js#L34
- https://github.com/plouc/nivo/blob/master/packages/radar/src/RadarDots.js#L126
