### ISSUE TITLE
How to separate data key from data label?

### ISSUE THREAD

**Issue by kapso** [plouc/nivo#474]
So I have the following json object that I am using for a simple bar chart `keys={['apple']}`

The tooltip and legend display `apple`, but I want a different label, say "Apple's Sold". I guess I can use the `tooltip` property to customize, but there should be a way to separate out the data key from data label in the JSON object, no?

```
[
  {
    date: '14 Sept',
    apple: 254
  },
  {
    date: '15 Sept',
    apple: 352
  }
]
```

**Comment by kapso** [comment]
Or may be `label` property on the component, that lets you map id => label. Thoughts?

**Comment by kapso** [comment]
Curious if there's another forum to ask questions? Or perhaps this project is not actively maintained?

**Comment by plouc** [comment]
@kapso, there's also a discord channel => https://discord.gg/n7Ft74f, the project is still maintained and I use it for several projects, but it's a side project, meaning I work on it on may spare time, and I don't have much now.

Regarding your issue, I'm not fond of automatically using a label property, however, maybe something like `getLabel` which allows to do whatever we want to define the label, but customizing the tooltip should work too.

**Comment by kapso** [comment]
Is there support for `getLabel` ?

**Comment by kapso** [comment]
@plouc curious if this a feature that will be available anytime soon.

Another reason is we use https://www.npmjs.com/package/axios-case-converter to turn json keys to camel case. So being able to decouple id/keys from their `display label` for bar, pie charts etc.  would be nice.

**Comment by plouc** [comment]
@kapso, the `Bar` component accept a function for the `label` property, for your use case you can use `label={d => 'Apples Sold'}`, but you can also have a more complex logic, for example using the lib you mentioned.
