### ISSUE TITLE
datum prop not passed to DotsItem in RadarDots

### ISSUE THREAD

**Issue by brunovegreville** [plouc/nivo#479]
Versions affected :
- `@nivo/core` : 0.52.1
- `@nivo/radar` : 0.52.1

Hey,

After the merge of this PR : #424  , `DotsItem` requires a `datum` props, which is correctly passed by `LineDots` (from `@nivo/line`). However `RadarDots` (from `@nivo/radar`) does not pass the datum props to `DotsItem`, which raises an error.

Thank you,

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/512/commits/d2cc1d60d8516543658019e46bc2058a73cd1d72, but not published yet.
