### ISSUE TITLE
Axis Property support for Bullet Chart

### ISSUE THREAD

**Issue by nloehlein** [plouc/nivo#481]
Similar to other charts, it would be useful to define custom axis tickvalues, size, padding, rotation in bullet charts

**Comment by nloehlein** [comment]
One other thing that would be helpful is the format function.

**Comment by syedali90** [comment]
any update on this ?

**Comment by pietervanwijk** [comment]
Would love to use this too :)

**Comment by wyze** [comment]
This is definitely something we should support! PRs are welcome.

**Comment by assadtony** [comment]
bump

**Comment by usamedin** [comment]
bump

**Comment by jdeanquin-dg** [comment]
bump

**Comment by Ovoda** [comment]
bump

**Comment by ivan-sparq** [comment]
bump
