### ISSUE TITLE
isInteractive prop warning in Treemap chart

### ISSUE THREAD

**Issue by stephanoshadjipetrou** [plouc/nivo#499]
Hi @plouc thanks for such an awesome library!

After upgrading to v0.55.0 the Treemap chart produces a warning message in console (see attachment). I've went a bit through the source code and noticed that the Container component in TreeMapHtml doesn't receive `isInteractive` prop which is set as required in the component's propTypes. Idk if that's what causing the warning thought. As it's not an error, not blocking anything atm but wanted to point it out so you're aware of it :)

![Screenshot 2019-03-29 at 5 26 27 PM](https://user-images.githubusercontent.com/11508354/55244196-601b4180-5249-11e9-9460-8d727cc211b5.png)

**Comment by plouc** [comment]
I moved the default value in the function args `({ children, theme, isInteractive = true })` and forgot to remove the requirements, it has been fixed.

**Comment by plouc** [comment]
And thank you for reporting :)

**Comment by stephanoshadjipetrou** [comment]
No problem :)
