### ISSUE TITLE
BarItem invalid prop error (data.value of type string)

### ISSUE THREAD

**Issue by JakeSidSmith** [plouc/nivo#500]
I'm receiving a prop type error that I wasn't expecting when using Nivo's `ResponsiveBar` component:

```
Warning: Failed prop type: Invalid prop `data.value` of type `string` supplied to `BarItem`, expected `number`.
```

We are using the following data format for all of our charts, and it works fine for line charts (and is echoed by the line chart types / propTypes), but causes an error when used with bars.

```json
[
  {"index": "2019-01-01", "value": "123"}
  {"index": "2019-02-01", "value": "456"}
  {"index": "2019-03-01", "value": "789"}
]
```

This surprised me because we weren't receiving any type errors (we are using TypeScript), but after looking into the source I saw that the data was typed as an array of objects: https://github.com/plouc/nivo/blob/16ae9d5c455bad7349598d95aa746d018c2454b6/packages/bar/index.d.ts#L16

Which does match the propTypes for this component, however its child; `BarItem`, requires explicitly number values: https://github.com/plouc/nivo/blob/16ae9d5c455bad7349598d95aa746d018c2454b6/packages/bar/src/BarItem.js#L88

I'm unsure what the best solution for this is. Possibly a mixture of the following:

* Update the bar data type to only accept objects containing numbers, although I imagine it is necessary to pass strings for some data keys, so this doesn't really resolve the issue.
* Update the bar data type to only accept objects containing strings or numbers (doesn't fix this issues, but is more accurate).
* Cast the values when the bars are being calculated e.g. https://github.com/plouc/nivo/blob/16ae9d5c455bad7349598d95aa746d018c2454b6/packages/bar/src/compute/grouped.js#L98
* Loosen the `BarItem` propTypes to allow string values.

If someone could let me know the correct course of action I'd be happy to open a pull request.

**Comment by ByronBecker** [comment]
@JakeSidSmith The value needs to be a number so that each bar can be rendered correctly. I'd recommend adding a transformation step to cast your values from string -> number and inserting that transformed data as the `data` prop

**Comment by plouc** [comment]
@JakeSidSmith, the bar chart isn't as flexible as the line chart, values must be numbers.
