### ISSUE TITLE
Nivo API calls don't work, Heroku service seems down

### ISSUE THREAD

**Issue by Bondifrench** [plouc/nivo#501]
### Thanks for using nivo
Great library!

# Are you reporting a bug/error? Yes

Please include a test case that demonstrates the issue you're reporting.

All API calls that I have tried: for example Line HTTP API at https://nivo.rocks/line/api
don't return a chart.

It seems your Heroky service is down as when I open the developer tools, I can see in the console:
OPTIONS https://nivo-api.herokuapp.com/charts/line 503 (Service Unavailable)

Same when using the Bar HTTP API, the dev tools would show the following error:
APIClient.js:68 OPTIONS https://nivo-api.herokuapp.com/charts/bar 503 (Service Unavailable)

**Comment by plouc** [comment]
The API uses a free plan, I ran out of free hours, that's why.

**Comment by plouc** [comment]
It should be up soon, at the beginning of April.

**Comment by stayhungry07212** [comment]
@plouc, still down yet?
Any plan fixing the http api version issue?
