### ISSUE TITLE
ResponsiveLine from package 'nivo' ignores yScale

### ISSUE THREAD

**Issue by Dymnarisk** [plouc/nivo#502]
This library is absolutely boss. Thank you so much for developing this.
I have an issue that I'm not sure is intended, it looks like a bug.
A ResponsiveLine imported from package 'nivo' behaves differently from a ResponsiveLine imported from package '@nivo/line', wherein it ignores [at least] the yScale prop.
The '@nivo/line' package renders the min and max correctly, where the 'nivo' version ignores it.

https://codesandbox.io/s/0xql4x2zyw

**Comment by plouc** [comment]
Thank you!
In fact, it's not a bug, `nivo` was the first package I published to npm, it's now deprecated and shouldn't be used, you now must use scoped packages `@nivo/<thing>`.
