### ISSUE TITLE
Chromatic colors don't  work

### ISSUE THREAD

**Issue by MiceXx** [plouc/nivo#503]
### Chromatic colors don't  work
Chromatic colors don't seem to work. Tried in an existing app, then tried again in another empty app, same result. Everything shows up as black.

Below is what happens when I use the default props along with: colors="greens", colorBy="id"
![image](https://user-images.githubusercontent.com/26972453/55353328-06a55380-5491-11e9-8d05-5d1e3425610a.png)

**Comment by plouc** [comment]
I have no idea which version of the package you're using, also as asked in the issue template, please provide a running example on codesandbox.

Here is a screenshot of the website's demo, and it works:

<img width="627" alt="Capture d’écran 2019-04-04 à 21 58 59" src="https://user-images.githubusercontent.com/501642/55557612-3076a880-5725-11e9-9474-c5d33adf850c.png">
