### ISSUE TITLE
Limiting number of legend possible?

### ISSUE THREAD

**Issue by ken31ee** [plouc/nivo#505]
Is it possible to limit the number of legends displayed as the legend render outside the chart.
![Screenshot 2019-04-04 at 11 01 57 AM](https://user-images.githubusercontent.com/7078643/55526862-350d7380-56c9-11e9-8c8a-77f9a0956e4e.png)
As you can see, Keyword A, B, C is outside the chart.
I can't find any related feature in the document.

**Comment by plouc** [comment]
Sorry but there's no such feature, also it seems pretty arbitrary to limit the number of legends.
I don't know, what are your current setup/requirements, but maybe you could consider rendering the legend outside of the chart in plain html to have full control?
