### ISSUE TITLE
ResponsivePie not rendering anything.

### ISSUE THREAD

**Issue by andeersg** [plouc/nivo#51]
I try to output a Pie chart, but the responsive pie chart only outputs an empty div:
```
<div style="width: 100%; height: 100%;"></div>
```
My settings look like this (and I use the sample data from website):
```
const settings = {
      width: 300,
      height: 300,
      margin: { top: 10, right: 10, bottom: 10, left: 10 },
      innerRadius: 0.9,
      cornerRadius: 3,
      padAngle: 1,
      enableSlicesLabels: false,
      enableRadialLabels: false,
      isInteractive: false,
    };
```
It does not work if I remove width/height either. Am I doing something wrong?

**Comment by plouc** [comment]
Can you provide the component's React code please?

**Comment by plouc** [comment]
And what's the size of the wrapping div in your browser inspector?

**Comment by plouc** [comment]
I don't see any data in your settings

**Comment by plouc** [comment]
Sorry, you're using the sample data, missed that :/

**Comment by andeersg** [comment]
Yeah, sorry my implementation looks like this:
```
<ResponsivePie
          {...settings}
          data={testData} // Data from nivo.rocks site.
        />
``` 
It's placed inside a grid with this properties:
```
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr;
    grid-gap: 30px 30px;
```
and the div itself has a min height of 200px.

**Comment by plouc** [comment]
@andeersg what's the computed size of the div in whatever browser dev tools you use ?

**Comment by plouc** [comment]
The wrapper I mean

**Comment by andeersg** [comment]
It has a computed size of width: 600px and height: 200px;

**Comment by plouc** [comment]
really weird then… quite hard to debug without having the proper code though

**Comment by plouc** [comment]
I mean something I can try to run

**Comment by andeersg** [comment]
I can try to experiment with some different heights for the wrapper, if that does not work I will try to reproduce it somewhere you can look at it.

Really cool project btw!

**Comment by plouc** [comment]
Thank you

**Comment by plouc** [comment]
@andeersg, I think I've found the problem, see https://www.webpackbin.com/bins/-KtLnILuaFhwgfJnIkYC

**Comment by plouc** [comment]
You cannot use `min-height` as responsive components use available space to render, but `min-height` relies on content dimension, so…

**Comment by plouc** [comment]
If you want a fixed size component, you should use `Pie`, otherwise, you'll have to set an explicit height on the wrapper

**Comment by plouc** [comment]
Or perhaps find a way to get an usable height, using 100% height for all parents of the grid, because default `align-items` value is `stretch`, but need to have a parent with a defined height to be correctly used

**Comment by plouc** [comment]
I close this issue as it's more a CSS issue in the end.
