### ISSUE TITLE
Stacked Line Charts add y values for same x values

### ISSUE THREAD

**Issue by sanghaiadarsh** [plouc/nivo#510]
when we create stacked line charts they add the y values of items on x axis and thus keep placing the id's one over the other. 

ex: id: A, data:{x:, y:} ; id:B, data:{x:, y:}

so it stacks B on top of A and adds B.y to A.y. 

Is there a way to avoid this?

I want to stack A and B but not add y values rather use the lines to compare A and B. So A might be above B according to values.

**Comment by plouc** [comment]
you can disable stacking in the y scale config:
```
yScale={{
    type: 'linear',
    stacked: false,
    min: 'auto',
    max: 'auto'
}}
```
`stacked` means the values are added, maybe you're looking for another kind of chart like the [stream](https://nivo.rocks/stream/).
