### ISSUE TITLE
geomap(s) not rendering anything

### ISSUE THREAD

**Issue by gcloeval** [plouc/nivo#514]
# Are you reporting a bug/error?
I am reporting a bug - I am unable to get any of the map components to show any data.
I just used source code directly from the example including the data, but none of the maps show anything, just a grid. 
Do I need to import/configure anything else? I tried svg and canvas example but no luck

Here is the codesandbox - please let me know if you have some advice:
https://codesandbox.io/s/v86kz3850l

Thanks for the great lib!!!!!!

**Comment by plouc** [comment]
@gcloeval, sorry, I didn't included the required geojson in the website, I'll try to fork your sandbox with a proper setup.

**Comment by plouc** [comment]
Sorry for the delay, please have a look at https://codesandbox.io/s/xlow398ymo, the missing piece was the feature file `world_countries.json`.

**Comment by ayepRahman** [comment]
Hi Plouc, can you update the doc please with the feature included in the examples
