### ISSUE TITLE
Sankey tooltips render but are blank

### ISSUE THREAD

**Issue by oliviabrandel36** [plouc/nivo#517]
Whether attempting to implement custom tooltips or the default, I only seem to get blank boxes when I hover over the Sankey diagram. This occurred in CodeSandbox and running on localhost. The tooltip box seems to change length if the tooltip content gets longer but I haven't been able to get it to display the text. I'm using the sample data and code from https://nivo.rocks/sankey so I don't know where the issue could be arising from. Thanks in advance! 

 CodeSandbox link:
https://codesandbox.io/embed/v89qwzw9yy

Image of issue:
<img width="608" alt="tooltip test" src="https://user-images.githubusercontent.com/47863554/56220446-76d9da80-6036-11e9-8626-cabf2943dd09.PNG">

**Comment by plouc** [comment]
@oliviabrandel36, you've put the chart inside `<header className="App-header">` and `.App-header` class has `color: white;`, if you remove this, you'll see the tooltip content, it's here but has the same color as the background.

**Comment by oliviabrandel36** [comment]
> @oliviabrandel36, you've put the chart inside `<header className="App-header">` and `.App-header` class has `color: white;`, if you remove this, you'll see the tooltip content, it's here but has the same color as the background.

Thank you so much! I had a feeling it was a simple problem. I appreciate that you took the time to reply.
