### ISSUE TITLE
Warning: Failed prop type: Invalid prop `colors` supplied to `Line`.

### ISSUE THREAD

**Issue by ConnorTCM** [plouc/nivo#519]
With `react` 16.8.1, `react-dom` 16.8.1 and `@nivo/line` 0.56.0.

Providing a single hex code string to the `colors` property results in PropTypes error:

```
Warning: Failed prop type: Invalid prop `colors` supplied to `Line`.
    in Line (created by pure(Line))
    in pure(Line) (created by withPropsOnChange(pure(Line)))
    in withPropsOnChange(pure(Line)) (created by withPropsOnChange(withPropsOnChange(pure(Line))))
    in withPropsOnChange(withPropsOnChange(pure(Line))) (created by withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Line)))))
    in withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Line)))) (created by withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Line))))))
    in withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Line))))) (created by withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Line)))))))
    in 
```
etc. etc. etc.

Example here https://codesandbox.io/s/p5y6l4wym

**Comment by plouc** [comment]
Because it's not a valid color, even if it passes, if you want to use a single color, you should use `colors={() => 'red'}` plain color is supported for inherited colors such as borders/links…

**Comment by plouc** [comment]
Here is the logic behind it => https://github.com/plouc/nivo/blob/master/packages/colors/src/ordinalColorScale.js

**Comment by plouc** [comment]
In fact it should be supported as it's the fallback

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/commit/b8d3abb4bd86398193b988cc30dd98feaf365be4

**Comment by ymenase** [comment]
Kind of related:
Failed prop type: Invalid prop `yScale` supplied to `Line`

Why would I get this? It seems that yscale is a fine property.

**Comment by RabeeAbuBaker** [comment]
> Kind of related:
> Failed prop type: Invalid prop `yScale` supplied to `Line`
> 
> Why would I get this? It seems that yscale is a fine property.

Make sure that you provide the full property.
e.g.
` 
yScale={{
				type: 'linear',
				min: 'auto',
				max: 'auto',
				stacked: false,
				reverse: false,
			}}
`
