### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./BubbleProps

### ISSUE THREAD

**Issue by mario589736** [plouc/nivo#52]
After Updating to nivo@^0.26.2:
ERROR in ./~/nivo/lib/components/charts/bubble/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./BubbleProps in */node_modules/nivo/lib/components/charts/bubble
 @ ./~/nivo/lib/components/charts/bubble/index.js 41:19-43

**Comment by plouc** [comment]
Weird, because I fixed that => https://github.com/plouc/nivo/commit/37067061cf1d4353da4fed3dd60dabb61a449cf7

**Comment by plouc** [comment]
Hum… the es version is ok, but not the commonjs one

**Comment by plouc** [comment]
@mario589736 should be fixed in `0.26.3`
