### ISSUE TITLE
Warning: Failed prop type: The prop `datum` is marked as required in `DotsItem`, but its value is `undefined`.

### ISSUE THREAD

**Issue by mcharalambous** [plouc/nivo#521]
I am trying to view the Radar Chart from the website project on github tag v0.55.0, when radar chart is loaded i get the following warning: 

Warning: Failed prop type: The prop `datum` is marked as required in `DotsItem`, but its value is `undefined`. 

Any solutions ?

**Comment by plouc** [comment]
Yes, you should upgrade to `0.56.0`
