### ISSUE TITLE
Warning: Failed prop type: Invalid prop `colors` supplied to `<<anonymous>>`.

### ISSUE THREAD

**Issue by mcharalambous** [plouc/nivo#522]
Website project tag v0.56.0 on Radar Chart get this warning on Rendering. 
Warning: Failed prop type: Invalid prop `colors` supplied to `<<anonymous>>`.

Any solutions?

**Comment by plouc** [comment]
I don't have this warning, can you please show what's the generated code in the dedicated tab and take a screenshot of this warning?

**Comment by plouc** [comment]
Also, I have no idea of which commands you're running, how you installed the project, browser… some context would be useful
