### ISSUE TITLE
Adaptive resize height and width responsive

### ISSUE THREAD

**Issue by stahlmanDesign** [plouc/nivo#523]
Nivo charts have always automatically resized when the width changes, but not the height. Now, the examples on the website resize vertically and horizontally when you resize the page.

I have wrapped some charts in react-measure, but it is cumbersome and it looks like there might be a better way to do it like the example. What is the best way to do this?

![resize-adapt-horiz-and-vertical](https://user-images.githubusercontent.com/972804/56436320-641b0c00-62a9-11e9-8174-fa5ca3fd9242.gif)

**Comment by plouc** [comment]
Responsive components are already wrapper in react-measure, use `ResponsiveLine` for example instead of `Line`

**Comment by plouc** [comment]
Also it was already the case before, it's just that now the website use a percentage instead of a fixed value.

**Comment by plouc** [comment]
You just need to have a parent container with a defined size.

**Comment by codepharmer** [comment]
@plouc How can the graph be responsive if it has a defined size?

**Comment by plouc** [comment]
@codepharmer, a defined size can be in `%` or inside a grid using `fr` units, a flexbox... even if responsive, the behavior has to be determined, as you would do for a responsive website.

**Comment by AntoineFachez** [comment]
Hi Plouc,

thanks for all the work! 
as some of us I am stuck with the responsive width as well. I got control of the height, perfect. But the width sticks with its latest min. The line chart does not shrink.
I consoled your line chart at nivo.rocks and reproduced the structure, I gotElementById and forced the container, the svg and a wrapping div to "100%" or some "Xvw" all together, seperate… any given combination I would come up with. I tried npm autoSizer.

the only value that got any "accaptable" result was a fixed value not based on percentage or viewport width.

Can you point me to the right direction how you did that on your page? I cant figure it out.

Very, very much appreciated :)
Antoine.

**Comment by lockhaicttv** [comment]
@AntoineFachez 

I am facing this problem as well. I recognized when I inspected the chart from Nivo website, that the position is absolute, and changing it from my code will fix the problem, I hope it can help you solve this one

**Comment by lockhaicttv** [comment]
import { BarDatum, ResponsiveBar } from '@nivo/bar'
import { ResponsiveBarSvgProps } from '@nivo/bar/dist/types/ResponsiveBar'
import { DEFAULT_CHART_COLOR_SCHEMA } from '@app/components/Chart/constants/chart.constants'
import EmptyData from '@app/components/EmptyData'
import { useTheme } from 'next-themes'
import { ChartWrapper } from '@app/components/Chart/styles/chart.styles'

interface Props extends ResponsiveBarSvgProps<BarDatum> {}
const Bar: React.FC<Props> = ({ ...props }) => {
  const { theme } = useTheme()

  return (
    <ChartWrapper className='flex justify-center content-center items-center h-full w-full chart-wrapper'>
      {!props.data.length ? (
        <EmptyData />
      ) : (
        <ResponsiveBar
          {...{
            padding: 0.2,
            labelSkipWidth: 16,
            labelSkipHeight: 16,
            axisLeft: {
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: '',
              legendPosition: 'middle',
              legendOffset: 1,
              truncateTickAt: 0
            },
            axisBottom: {
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: '',
              legendPosition: 'middle',
              legendOffset: 1,
              truncateTickAt: 0
            }
          }}
          borderColor={{
            from: 'color',
            modifiers: [['darker', 1.6]]
          }}
          margin={{ top: 10, right: 0, bottom: 25, left: 40 }}
          padding={1 / props.data.length}
          valueScale={{ type: 'linear' }}
          indexScale={{ type: 'band', round: true }}
          labelSkipWidth={12}
          labelSkipHeight={12}
          barAriaLabel={(e) => e.id + ': ' + e.formattedValue + ' in country: ' + e.indexValue}
          colors={DEFAULT_CHART_COLOR_SCHEMA}
          theme={{
            axis: {
              ticks: {
                text: {
                  color: theme === 'dark' ? '#FFF' : '#000',
                  fill: theme === 'dark' ? '#FFF' : '#000'
                }
              }
            },
            tooltip: {
              container: {
                color: '#000'
              }
            },
            ...props.theme
          }}
          {...props}
        />
      )}
    </ChartWrapper>
  )
}

export default Bar

import styled from 'styled-components'

export const ChartWrapper = styled.div`
  > div {
    > div {
      position: absolute !important;
    }
  }
`
My example
