### ISSUE TITLE
Button to copy code/data in clipboard on all the examples

### ISSUE THREAD

**Issue by jonattfin** [plouc/nivo#525]
I think that a copy button on the code/data would be useful for rapid taking that code/data & putting it in your own editor, etc. See attached picture.
![Screenshot_2019-04-21 Bar-1](https://user-images.githubusercontent.com/3768739/56473632-a6de0f00-6476-11e9-8e6e-5108f8f764ec.png)

**Comment by plouc** [comment]
You're right, in fact it's already on my todo ;)

**Comment by Larissagilliane** [comment]
I can help and work on that issue
