### ISSUE TITLE
Knowing when a graph has been drawn/rendered

### ISSUE THREAD

**Issue by SuttJ** [plouc/nivo#527]
Thank you for this library and the demos/documentation - it's fantastic.

I notice that in the Bar Graph component for example, `this.draw()` is called in `componentDidMount`. Is there anyway to know when `this.draw()` has been completed? Any callback available?

I'm in a situation where I'm waiting for multiple Nivo graph components to render before I print the page. With the current React setup, I'm able to know when these components mount and render but _not_ when their graphs are actually drawn and shown - so I end up printing blank base nivo components with no graphs.

**Comment by plouc** [comment]
There is no such hook, depending on the chart you use, you might be able to achieve this by adding an extra layer on top of all other layers, this way, it will be called after all other layers.

**Comment by plouc** [comment]
Which components are you using?

**Comment by SuttJ** [comment]
ResponsiveBarGraph, specifically

**Comment by plouc** [comment]
You mean `ResponsiveBar`? Because it doesn't have a `draw` method.

**Comment by SuttJ** [comment]
Sorry, yes ResponsiveBar. I'm not too familiar with the inner workings of this library I just noticed that `this.draw()` is called in `componentDidMount` of BarCanvas and figured that was the process of drawing the bar graph.

**Comment by plouc** [comment]
The canvas implementation internals are really different from the SVG implementation because everything's rendered inside a single component.

**Comment by plouc** [comment]
Please have a look at this example => https://codesandbox.io/s/won5y6k70w

**Comment by plouc** [comment]
However I doubt it will address your issue as you'll need to render the charts to have the callback called, and you want to want for this callback to draw :/

**Comment by plouc** [comment]
If you could provide an example of your current app, maybe I could help, but I don't really understand why the components are _blank_.

**Comment by plouc** [comment]
@SuttJ any update on this?

**Comment by plouc** [comment]
I'm closing this due to lack of reply, feel free to comment if you can provide a running example.

**Comment by alexnm2566** [comment]
Hello, first of all thanks for this great library! I need to mutate Treemap HTML DOM after it renders so I can style the tiles as I want (ex. set border-radius). But there's no callback when it has rendered. Can you help me? Maybe there's some method to do it

**Comment by DaveCole** [comment]
Chiming in with a fix for @ghost or anyone else running into a similar issue (I'm using html2canvas to download an image of the chart in this case and was getting blank images due to a state change that caused a re-render) - wrap your call to whatever downloads/prints your chart in a setTimeout() call - even a minimal delay value like 10ms seems to allow the chart to re-render before attempting to capture the image.
