### ISSUE TITLE
Pie Chart not rendering

### ISSUE THREAD

**Issue by vagnervst** [plouc/nivo#53]
Hello, Plouc!

I am trying to use your Nivo package to create a Mozaik widget but I can't get the Pie Chart to work.

I hosted the code at Webpackbin (which is the same code presented at http://nivo.rocks/#/pie/) so that you can see exactly what I am refering to: https://www.webpackbin.com/bins/-Kts4ISztFmDaec8MYZX

It shows the data but not the chart.
What could it be? Thanks!

**Comment by plouc** [comment]
Hello, `width` & `height` :)

**Comment by plouc** [comment]
Or you can use the responsive alternative `ResponsivePie` which will use available space

**Comment by plouc** [comment]
https://www.webpackbin.com/bins/-KtsAjv-1MbbkUWCV4so

**Comment by vagnervst** [comment]
Thanks! =)
