### ISSUE TITLE
colorBy not available in ResponsivePie

### ISSUE THREAD

**Issue by nbouliol** [plouc/nivo#530]
First of all, thanks for the lib 😄 

`colorBy` is not available in `ResponsivePie`

You can find find an example [here](https://codesandbox.io/s/kxmw7vrnk5)

But i saw it was available in [your sandbox](https://codesandbox.io/s/w27xwy0xlk) with version *0.52.1* 

Maybe the `PieSvgProps` type is missing the `ColorProps<PieDatum>` interface

**Comment by plouc** [comment]
Hi @nbouliol, 

Thank you :)

I've changed the api for colors, `colorBy` is now only available if you want to select the property used to pick a color from a color scale (like `depth` or `id` for a TreeMap), custom color function can now be directly passed to colors, so you can use `colors={d => d.color}`.

However there's a bug on the Pie component regarding color inheritance, the patterns won't behave correctly, for now you can specify the color directly in the pattern to bypass this issue.

**Comment by plouc** [comment]
The TypeScript definition matches the new api, using `OrdinalColorsInstruction`.

**Comment by nbouliol** [comment]
OK thank you !

I will test it on monday.

I'll update you

**Comment by nbouliol** [comment]
Hi,

Yes it's working well using `colors={d => d.color}` 

Thank you :)

**Comment by plouc** [comment]
👍

**Comment by talarico43** [comment]
@plouc just a quick follow question to this issue.. 

So does this mean we cannot pass a color scale to `colors` anymore? In other words, is the only option a custom color function?

**Comment by talarico43** [comment]
@plouc nvm i figured it out. for anyone else coming into this issue looking for a way to specify a color scale/set you now just need to pass an object `{ scheme: 'nivo' }`

**Comment by dafu2020** [comment]
Hi @plouc, I was trying to use  `colors={d => d.color}` to customize pie components color but it did not work with ResponsivePie. I also tried `colors={{ datum: 'data.color' }}`.
