### ISSUE TITLE
Adjustable Choropleth Color Domain

### ISSUE THREAD

**Issue by tg970** [plouc/nivo#534]
Hi Plouc, great stuff here in the Nivo library; just started using the charts and they're looking amazing so far!

The Choropleth is a great feature and we're hoping to use it more. It looks like the domain for the color scaling is defaulted to [0, 1000000]. I see the color prop can take a function so assuming this is where we could adjust the domain.  

How does the function to customize the color prop need to be constructed? 

Also wondering how hard would be be add a domain prop that would pass a two element array into the domain function of guessQuantizeColorScale. That way we could use the off the shelf color scales and also control the domain? 

Thanks for all that you're doing!

**Comment by tg970** [comment]
Created PR #540 to add functionality

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/540 thanks to @tg970
