### ISSUE TITLE
Grouped and stacked bar charts

### ISSUE THREAD

**Issue by JelleBlaauw** [plouc/nivo#535]
Is it possible to combine grouped and stacked behavior in bar charts, like below image?
![image](https://user-images.githubusercontent.com/20815406/57447974-9c828a00-7258-11e9-9b3c-adbec160e3a4.png)
If not, I would like to request this feature.

Thanks!

**Comment by plouc** [comment]
No it's not.

**Comment by JelleBlaauw** [comment]
Alright. Are you planning on implementing this? And if not, could you give me some pointers on how I could get started with implementing it?

**Comment by plouc** [comment]
I'm not planning to implement this as there's already support for stacked/grouped/reversed, I'm afraid the component will become very bloated, and some combinations will probably not play well together.

I was thinking of splitting the Bar chart component into several ones, like `Bar`, `GroupedBar`, `StackedBar`… so maybe another `GroupedStackedBar`.

Also the `@nivo/bar` package hasn't been migrated to the latest architecture, using hooks for more flexibility, so first it'll need to be updated.

So the steps would be:
- migrate to new architecture
- provide several components
- add this new component

Unfortunately It's not trivial, and requires quite a bit of work :)

**Comment by plouc** [comment]
For now, what you could do is using the existing `Bar` component in `grouped` mode and use a custom bar item which handle the stacking.

**Comment by JelleBlaauw** [comment]
Alright, seems like a plan. Thanks a lot!

**Comment by jackgilbertx** [comment]
@JelleBlaauw were you ever able to implement this?????I would really appreciate if you would share your code/method for achieving this feature.  Please respond in another comment if so.  
Thanks!

**Comment by JelleBlaauw** [comment]
@jackgilbertx No, unfortunately not. I had to focus on another project and switched to react-vis instead.

**Comment by pawel-kowalczyk7** [comment]
@plouc Are you going to implement this feature in close future? 'in grouped mode and use a custom bar item which handle the stacking.' So is this possible to set chart as grouped and have stacking bars?

**Comment by timramone** [comment]
It's so sad you doesn't support this use case =(

Cusom bar component seems like a hack because the position of the legend inside the component and the tooltip would be broken. All of these features should support stacked groups to work correctly.

**Comment by john-curry871** [comment]
This would be a seriously valuable enhancement.  One of those requirements that seems to come up again and again

**Comment by rmonnier9** [comment]
Hi everyone !

First of all, thanks all contributors for this pretty cool open source project :)
I've tried many other libraries and I ultimately picked this one. Fast, beautiful and great api.

I'm seriously considering coding group and bar chart, because I need it as well.

@plouc Are you already working on it? Or would you have any advice (architecture) before I start doing it ?

**Comment by rmonnier9** [comment]
It seems that it essentially needs to add a file in this folder:
https://github.com/plouc/nivo/tree/master/packages/bar/src/compute

**Comment by dooleyb1** [comment]
Would love to see this functionality, anyone have a workaround / implementation?

**Comment by monzilnepali** [comment]
I did implement grouped bar chart with a custom stacked bar. Let me know if this works for you as well.
https://codesandbox.io/s/proud-fast-g14zp

**Comment by monzilnepali** [comment]
Here is another example of a grouped bar chart with a custom stacked bar and tooltip functionality
https://codesandbox.io/s/affectionate-sammet-zcnbf?file=/src/App.js

**Comment by Vaidik1308** [comment]
> Here is another example of a grouped bar chart with a custom stacked bar and tooltip functionality
> https://codesandbox.io/s/affectionate-sammet-zcnbf?file=/src/App.js


It is not working with typescript
