### ISSUE TITLE
Font-size should be of type string, not number

### ISSUE THREAD

**Issue by JelleBlaauw** [plouc/nivo#536]
When I pass `fontSize: "0.875rem"` to the `axis.ticks` property in theme, I get the following warning:

> Warning: Failed prop type: Invalid prop `theme.axis.ticks.text.fontSize` of type `string` supplied to `Axes`, expected `number`.

However, font-size should really be of type `string`. A `number` has no unit (`px`/`em`/`rem`/etc.) 
information; the assumption it should be `px` is faulty.

**Comment by plouc** [comment]
No it shouldn't, as canvas doesn't support those units.

**Comment by plouc** [comment]
This value might be used for deriving props too, which isn't possible with others.

**Comment by JelleBlaauw** [comment]
But shouldn't the warning only appear when using canvas, then? Because I use svg. Also, for non-svg solutions, perhaps it would be an idea to support both `number` and `string` variants, where the `string` variant would be converted to the `px` version.

**Comment by plouc** [comment]
I'll have to check first that nothing relies on this value, but it should works.

**Comment by JelleBlaauw** [comment]
Sounds good, thanks!
