### ISSUE TITLE
TypeError: scale.domain is not a function

### ISSUE THREAD

**Issue by longhungn** [plouc/nivo#537]
# Are you reporting a bug/error?

When I tried copying the storybook example for a Line chart with a time axis, I encountered this error: TypeError: scale.domain is not a function

Codesandbox example: https://codesandbox.io/s/03yxm4n1np

I took a quick look through the code and it looked like this line here is the problem:

https://github.com/plouc/nivo/blob/747b36908447afad4d4c4fe570bf9e189e163b15/packages/scales/src/timeScale.js#L45

It seems to be working fine when changed to:
```javascript
const scale = useUTC ? scaleUtc() : scaleTime()
```

**Comment by plouc** [comment]
Thank you for reporting, I don't know how I could miss that…

**Comment by plouc** [comment]
This has been fixed, please upgrade to `@nivo/line@0.57.1`.
