### ISSUE TITLE
CHANGELOG.md is not getting updated on new releases

### ISSUE THREAD

**Issue by drac** [plouc/nivo#544]
[CHANGELOG.md](https://github.com/plouc/nivo/blob/master/CHANGELOG.md) has not being updated since 6 months now.

It would be nice to have CHANGELOG.md back and working so we can easily check the changes on new releases.

**Comment by plouc** [comment]
You're right, done.

**Comment by OzzieOrca** [comment]
Seems out of date again... `0.57.2` is the last one mentioned but https://yarnpkg.com/en/package/@nivo/bar is at `0.59.2`. Also CHANGELOG.md is so big Github can't render it... 
![Screen Shot 2019-08-01 at 2 20 09 PM](https://user-images.githubusercontent.com/756501/62328271-822b0780-b467-11e9-86f7-dfd7b59edcc4.png)
