### ISSUE TITLE
Duplicate tick values when using 8 total days or less

### ISSUE THREAD

**Issue by charle692** [plouc/nivo#548]
**Describe/explain the bug**
First off I want to say thank you for this amazing library.
While trying to use the `ResponsiveLine` component, I found that if your dataset contains 8 consecutive days or less, the x-axis will create duplicate ticks. 

**To Reproduce**
I have created a [codesandbox](https://codesandbox.io/embed/z2xk4m0k0x) with a working and non-working example.

**Expected behavior**
I expect there to be no duplicate `date ticks` no matter the number of consecutive days within your dataset.

**Screenshots**
![image](https://user-images.githubusercontent.com/5891054/57733348-4f921f80-766d-11e9-80f6-4a6507c71cc9.png)

If there's anything additionally that I can do to help please let me know.

**Comment by plouc** [comment]
Hi @charle692, 

Thank you :)

Starting with latest release, you can now specify a time interval, like this:

```javascript
const axisBottom ={
    format: '%b %d',
    tickValues: 'every day'
}
```

**Comment by charle692** [comment]
Hi @plouc Thanks for your help. That does sort of fix the issue. But my dataset can also grow to a large number of days. In that case having a tick for every day would quickly run out of usable space.

I'm fine with closing this for now as there are 2 potential work arounds.

1. Having a minimum of 9 days of data allows the axis to automatically scale as expected.
2. Dynamically setting the `tickValues: 'every day'` to something else when the dataset is larger.

Thank you again.

**Comment by plouc** [comment]
You can use several days if you want like `every 3 days` or switch to weeks, months…

**Comment by charle692** [comment]
Yup, saw the other possible values from your amazing Storybook. I believe that is what I will do. Thanks for the suggestion.

**Comment by jithinbalakrishnan** [comment]
Hi @plouc ,
tickValues: 'every day' worked for me but the y axis grid lines are not getting removed .

![Screen Shot 2020-05-13 at 1 47 17 PM](https://user-images.githubusercontent.com/29042311/81789275-5de57680-9521-11ea-9cfb-cbb2b026048c.png)

after every x axis tick values  there is an extra line. How to remove that ?
