### ISSUE TITLE
Scatter Plot symbol size according to their value

### ISSUE THREAD

**Issue by cruze17** [plouc/nivo#551]
is there any way we could derive the symbol size as per their value.
e.g data ={ x ='2',y='5',value='6'}
![Capture](https://user-images.githubusercontent.com/27903834/57871076-8d5e8780-77d6-11e9-9ee7-a44aff983598.PNG)

**Comment by plouc** [comment]
Maybe we could use the same approach as for the [Swarmplot component](https://nivo.rocks/swarmplot/)

**Comment by cruze17** [comment]
Hi Plouc,
i tried the same pattern that you have used for Different size.
so i added 3rd dimension in data and set it to symbol size eg:

{ 
   "x"=5,
   "y"=6,
    size=4
}

scatterplotCharts{ symbolSize={d => d.size} }

**Comment by plouc** [comment]
@cruze17, it has to be implemented in this component first.
