### ISSUE TITLE
Customize Radar dotLabel

### ISSUE THREAD

**Issue by danzawadzki** [plouc/nivo#558]
Hey 👋! 
I'm building a chart based on the radar chart component. 
<img width="354" alt="Screenshot 2019-05-20 at 11 53 21" src="https://user-images.githubusercontent.com/23190254/58012973-ed666e00-7af5-11e9-83f8-bddd25e861e0.png">
However, I have a problem with styling labels for dots. Is it possible to change the color of these labels?

It would be great to pass basic styling this way:
`dotLabelColor: {
	from: 'color',
	modifiers: [['opacity', 0.9]]
},`

or at least:
`dotLabelColor: 'rgba(255,255,255,.9)'`

It would be nice to be able also to change the font size, etc. Is it possible to do it now, even somehow around? I need to fix it, and slowly I'm getting short of ideas.

**Comment by wyze** [comment]
@danzawadzki You can control the dot labels via the theme. Like so:

```jsx
<Radar
  // ...
  theme={{
    dots: {
      text: {
        fill: 'rgba(255,255,255,.9)'
      }
    }
  }}
/>
```

There is also `fontFamily` and `fontSize` properties on the `text` field as well.

**Comment by plouc** [comment]
@danzawadzki, you can change the style of the dot label using the theme, please have a look at [this example](https://codesandbox.io/s/nivoradar-m1dvs)

**Comment by ashu565** [comment]
Can we make label point in radar chart custom ?
