### ISSUE TITLE
Additional callback needed for layers api

### ISSUE THREAD

**Issue by clairesunstudio** [plouc/nivo#559]
**Is your feature request related to a problem? Please describe.**
This is what I need to achieve with the chord diagram: I'm using layers to customize ribbons/arcs/legends

![chord](https://user-images.githubusercontent.com/5789411/58103457-02540780-7bb1-11e9-9cc2-489357f02e47.gif)

**Describe the solution you'd like**
Currently, layer context contains the following:
```
        center,
        radius,
        arcs,
        arcGenerator,
        ribbons,
        ribbonGenerator,
```
In order to use layer context to build custom layers, e.g. customize ribbons and arcs to tie to external controls, and customize legends to control ribbons/arcs, I had to also add the other props into the callback (layerContext) and export ChordRibbons and ChordArcs :
```
        ribbonProps: {
          borderWidth: ribbonBorderWidth,
          getBorderColor: getRibbonBorderColor,
          getOpacity: getRibbonOpacity,
          blendMode: ribbonBlendMode,
          setCurrent: setCurrentRibbon,
          isInteractive: isInteractive,
          onMouseEnter: onRibbonMouseEnter,
          onMouseMove: onRibbonMouseMove,
          onMouseLeave: onRibbonMouseLeave,
          onClick: onRibbonClick,
          tooltip: ribbonTooltip
        },
        arcProps: {
          borderWidth: arcBorderWidth,
          getBorderColor: getArcBorderColor,
          getOpacity: getArcOpacity,
          setCurrent: setCurrentArc,
          isInteractive: isInteractive,
          onMouseEnter: onArcMouseEnter,
          onMouseMove: onArcMouseMove,
          onMouseLeave: onArcMouseLeave,
          onClick: onArcClick,
          tooltip: arcTooltip
        }
```

```
export { default as ChordRibbons } from './ChordRibbons'
export { default as ChordArcs } from './ChordArcs'
```

so that I can construct my own arcs like such:
```
        // arcs
        ({center, arcs, arcGenerator, arcProps}) => {
          // const currentArc = activeTown && getObjByValue(arcs, activeTown, 'id');
          return(
            <g key="arcs" transform={`translate(${center[0]}, ${center[1]})`}>
              <ChordArcs
                arcs={arcs}
                arcGenerator={arcGenerator}
                {...arcProps}
              />
            </g>
          );
        },
```

Is this the right way to use the layers API and can you expose these to allow full customization?

**Comment by plouc** [comment]
Yes, this is the right way to use it 👍 
Exposing internal components makes sense.
I could expose more props too, I didn't exposed all props to avoid unnecessary re-rendering, waiting to see how people would use it.
However as I understand your use case, you want to be able to mask some links depending on the selection, I could allow to pass a function to the opacity property, this way, you could be able to set the opacity to 0 for inactive links, I already used this approach on other components, and it could work for the arcs too.

**Comment by helt** [comment]
@plouc Would you mind to point to the components, where you applied this approach?

@clairesunstudio @plouc Will this work with typescript, too?
