### ISSUE TITLE
Update lodash

### ISSUE THREAD

**Issue by danriti** [plouc/nivo#561]
hey @plouc, thanks for such an awesome library! we just started using this library and it's been a pleasure to work with. however, it appears to be using a slightly older version of `lodash` that has two security vulnerabilities associated with it:

- https://app.snyk.io/vuln/SNYK-JS-LODASH-73638
- https://app.snyk.io/vuln/SNYK-JS-LODASH-73639

Thus, the recommended remediation is to upgrade `lodash` to version `4.17.11` or higher.

**Comment by plouc** [comment]
@danriti, do you use the latest releases? because [that's already the case](https://github.com/plouc/nivo/blob/master/packages/core/package.json#L27)

**Comment by danriti** [comment]
@plouc i am not using the latest version (will update, thanks!), but I was thrown off because the `package.json` in the root directory is using a different version then the rest in `packages/*/package.json`:

https://github.com/plouc/nivo/blob/master/package.json#L48

is that expected?

**Comment by plouc** [comment]
No, it's not :) but this file isn't published, so it should not be an issue for users of nivo packages.

**Comment by danriti** [comment]
@plouc gotcha! ok cool, thanks for the heads up, closing this 👍
