### ISSUE TITLE
Line custom tool-tip disappear after upgrade from 0.53.0 to 0.58.0

### ISSUE THREAD

**Issue by Chedvaka** [plouc/nivo#562]
hey @plouc ,
thanks for the amazing library,
I just upgrade my line version from 0.53.0 to 0.58.0,
and my custom tool-tip and the dot border disappear,

I use chrome and I also checked on FF,

here my component and my tool-tip code:

 `    const toolTip = (event, icons, texts, colors, tooltipPadding) => {
        debbuger;
        if (event) {
            const data = event.data;
            return (
                <div style={{ fontSize: '13px', paddingTop: '10px', paddingRight: tooltipPadding, paddingLeft: '5px' }}>
                    <div style={{ fontWeight: 'bold', marginBottom: '10px' }}>{event.id}</div>
                    {data.map(({ data }, i) =>
                        <div key={i} style={{ alignItems: 'center', display: 'flex', flexDirection: 'row', lineHeight: '10px', marginBottom: '10px' }}>
                            {icons.length ? <img src={icons[i]} style={{ marginRight: '10px' }} /> :
                                colors.length ? <div style={{ height: '8px', width: '8px', backgroundColor: colors[i], marginRight: '5px', borderRadius: '10px' }} />
                                    : null}
                            <div>{data.y}<span style={{ fontWeight: '400' }}> {texts[i]}</span></div>
                        </div>
                    )}
                </div>
            );
        }
    };

    const isChrome = navigator.userAgent.indexOf('Chrome') != -1;
    const isEdge = navigator.userAgent.indexOf('Edge') >= 0;
    const tickPadding = isEdge || !isChrome ? 20 : 5;

    return (
        <ResponsiveLine
            colors={areaColors}
            height={height}
            data={data}
            margin={{
                'top': 50,
                'right': paddingRight,
                'bottom': 50,
                'left': 50
            }}
            axisLeft={{
                tickValues: tickValuesLeft
            }}
            axisBottom={{
                tickValues: tickValuesBottom,
                tickPadding: tickPadding
            }}
            animate={true}
            stacked={true}
            yScale={{ type: 'linear', stacked: true }}
            enableArea
            dotSize={8}
            lineWidth={4}
            enableGridX={false}
            enableGridY={true}
            tooltip={(e) => toolTip(e, icons, texts, colors, tooltipPadding)}
            gridXValues={!notEnoughData ? tickValuesLeft : undefined}
            gridYValues={!notEnoughData ? tickValuesLeft : undefined}
            isInteractive={!notEnoughData}
            dotBorderWidth={1}
            dotBorderColor='#ffffff'
            areaOpacity={1} 
        />);
};`

Thanks.

**Comment by plouc** [comment]
@Chedvaka, can you please reproduce this on codesandbox? Thank you.

**Comment by plouc** [comment]
The `@nivo/line` package changed lately, did you had a look at the documentation? (for example `dots` properties are now `points`)

**Comment by Chedvaka** [comment]
@plouc I look for documentation of the changes, and I didn't find,
where I can see that?

thanks

**Comment by plouc** [comment]
<img width="799" alt="Capture d’écran 2019-05-23 à 21 32 55" src="https://user-images.githubusercontent.com/501642/58253000-5e31b280-7da2-11e9-853f-1551f8903fec.png">

**Comment by plouc** [comment]
If you don't have this section, try to clear your cache, the service worker might be the problem.

**Comment by plouc** [comment]
If you want the previous behavior for the tooltip, you'll have to use `enableSlices="x"` and `sliceTooltip={MyCustomTooltip}`

**Comment by Chedvaka** [comment]
@plouc thanks for the quick replay,
that was the problem,
and now it works well.

thanks a lot.
