### ISSUE TITLE
Allow X and Y axis lines for bar chart

### ISSUE THREAD

**Issue by akob** [plouc/nivo#564]
There is the ability to hide grid axis on bar chart, but I want to keep axis X and Y lines. Is it possible to do it in some way like on image above?
![bar-chart](https://user-images.githubusercontent.com/8971441/58361400-2b1d1b00-7e97-11e9-8291-feee27a3ba84.png)

**Comment by akob** [comment]
Any updates?

**Comment by plouc** [comment]
You can use the theme property, for example you can use something like this:

```javascript
const theme = {
    axis: {
        domain: {
            line: {
                stroke: 'blue',
                strokeWidth: 2,
            }
        }
    }
}
```
