### ISSUE TITLE
There are not ability to hide axis tiks on bar chart

### ISSUE THREAD

**Issue by akob** [plouc/nivo#565]
I'm trying to hide tiks on Y axis. According to example it's working when axisLeft={null}, but typescript does not allow apply null to partial type, only undefined. But with undefined it does not work. Need to fix typings to allow null

**Comment by plouc** [comment]
Can you please provide more context, packages you're using, what you use to build your app (it seems you're using TypeScript), I cannot deal with such issues, having to guess everything… Thank you.
Also there is an issue template, please read it.

**Comment by akob** [comment]
I use "@nivo/bar": "0.58.0" and typescript and have next error
TypeScript error in C:/Users/Anton/Job/mvp/ui/src/application/content/home/salesTrend/SalesTrend.tsx(34,21):
Type 'null' is not assignable to type 'Partial<{ format: string | LabelFormatter; legend: string; legendOffset: number; legendPositio
n: "end" | "start" | "middle"; orient: "bottom" | "left" | "right" | "top"; tickPadding: number; tickRotation: number; tickSize: numb
er; tickValues: number | ... 1 more ... | number[]; }> | undefined'.  TS2322

    32 |                         legendOffset: 32,
    33 |                     }}
  > 34 |                     axisLeft={null}
       |                     ^
    35 |                     labelSkipWidth={12}
    36 |                     labelSkipHeight={12}
    37 |                     labelTextColor="white"

Because of indext.d.ts contains next line of code axisLeft: Axis. It means that axis cannot be nullable

**Comment by akob** [comment]
Any updates?

**Comment by Rezaraki** [comment]
don't write 
`axisLeft={null}`
instead write 
`axisLeft=null`

type check accepts null but not a null inside an object
