### ISSUE TITLE
nivo/geo 0.58 throws undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by gcloeval** [plouc/nivo#566]
Hi I am reporting a bug when upgrading to @nivo/geo version 0.58 from 0.56
Working version:
https://codesandbox.io/s/xlow398ymo

Failing version:
https://codesandbox.io/s/nivogeo-demo-hfgxl

Only change is to bump dependecy to 0.58
TypeError
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Function.scale.domain
https://hfgxl.codesandbox.io/node_modules/d3-scale/dist/d3-scale.js:732:41
    at eval (https://hfgxl.codesandbox.io/node_modules/
nivo/geo/dist/nivo-geo.cjs.js:109:49
mountMemo
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:13459:19
Object.useMemo
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:13668:16
Object.useMemo
https://hfgxl.codesandbox.io/node_modules/react/cjs/react.development.js:1492:21
    at useChoropleth (https://hfgxl.codesandbox.io/node_modules/
nivo/geo/dist/nivo-geo.cjs.js:108:26
    at eval (https://hfgxl.codesandbox.io/node_modules/
nivo/geo/dist/nivo-geo.cjs.js:624:24
renderWithHooks
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12938:18
mountIndeterminateComponent
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:15020:13
beginWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:15625:16
performUnitOfWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:19312:12
workLoop
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:19352:24
renderRoot
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:19435:7
performWorkOnRoot
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20342:7
performWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20254:7
performSyncWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20228:3
requestWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20097:5
scheduleWork
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:19911:5
scheduleRootUpdate
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20572:3
updateContainerAtExpirationTime
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20600:10
updateContainer
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20657:10
ReactRoot.render
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20953:3
eval
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:21090:14
unbatchedUpdates
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:20459:10
legacyRenderSubtreeIntoContainer
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:21086:5
Object.render
https://hfgxl.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:21155:12
evaluate
/src/index.js:95:9
  92 | );
  93 | 
  94 | const rootElement = document.getElementById("root");
> 95 | ReactDOM.render(<App />, rootElement);
     |         ^
  96 | 
View compiled
▶ 10 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.

**Comment by plouc** [comment]
@gcloeval, that's because the previous release used a fixed domain for the choropleth (the range used to determine colors), which was very undesirable, now you have to pass an explicit domain.
For your example, you can add `domain={[0, 1000000]}` to the choropleth.
