### ISSUE TITLE
Bug: Stacked Line Charts overlaps into X-axis labels in area-mode

### ISSUE THREAD

**Issue by Schinkenkoenig** [plouc/nivo#567]
**Describe/explain the bug**
Component: Line Chart
Conditions: 
- enableArea=true
- Stacked (at least two lines)
- the first line has a minimum value of y > 0.

Result: The area overlaps into the x-axis labels 

**To Reproduce**
Showcase in the following Code-Sandbox: https://codesandbox.io/s/pedantic-ishizaka-57ibx

The sandbox displays two variants of the same line chart which differs only in the areaBaselineValue.
BaselineValue (first Chart): the minimum value of the first line dataset (66)
BaselineValue (second Chart): the default 0

Steps:
- Create line chart with {stacked: true, enableArea: true, baselineValue: default)
- Input data with at least two lines
- All values for the first line are above 0
- Display the X-Axis labels

**Expected behavior**
I would expect the line chart to behave like the first one in the sandbox.
This means the baselineValue will default to the minimum of the first line chart when it is configured to be stacked.

**Screenshots**
![image](https://user-images.githubusercontent.com/12746890/58410905-70963f80-8073-11e9-8853-fc2c58478a08.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Comment by plouc** [comment]
If the minimum value doesn't start at `0`, you have to override the `areaBaselineValue` property

**Comment by codepunkt** [comment]
I've ran into the same problem recently - and while @Schinkenkoenig's "fix" might be a possible way to work around this - shouldn't or couldn't the library itself guard against something like this?

Potentially by re-using parts of @Schinkenkoenig's fix?

**Comment by Slither8** [comment]
Hey @plouc ! Thank you for this great library! The performance is really really great!!
However, I experience a similar problem but with the line chart. As you can see in the image below, I dynamically set min and max on the x-axis (time-based, varies according to user selection) which causes the line and the x-axis to overlap. Is there any fix for this which I just couldn't find yet? If not, could you give me a hint on how and where to implement an option to enable/disable this behavior? Of course I'd be willing to share the code/create a PR if it fits your needs as well.
![image](https://user-images.githubusercontent.com/6223247/62307640-3d619980-b484-11e9-958c-9dddcdb25bdf.png)

Thank you in advance!!

P.S. Setting min/max for the x-axis is not part of the documentation but works - except for the overlap - really well!

**Comment by iamchathu** [comment]
https://codesandbox.io/s/reverent-sky-tgijy?file=/src/App.js I also having same issue for the default data set in the example. What should I do to fix this?
