### ISSUE TITLE
sliceTooltip - how to map slice.id to x-axis value?

### ISSUE THREAD

**Issue by rbtbar** [plouc/nivo#569]
How can I map the slice.id to the value on x-axis?

I'm trying to display a corresponding date/time value from the X-Axis in the sliceTooltip in the responsive line chart. As far I can see there is a slice.id property which seems to have a value stored in pixels. 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/6705643/58488615-f5fc1b80-8169-11e9-949f-f7476c385725.png">

**Comment by plouc** [comment]
I'm sorry, I don't really understand what you're trying to achieve, can you share your current props/data and ideally a screenshot of what you're expecting? Thank you

**Comment by wyze** [comment]
The `data` property on the point should have what you are looking for. Something like this:

```ts
<ResponsiveLine
  // ...
  sliceTooltip={({ slice }) => (
    <div>
      {slice.points.map((point) => (
        <div>X Value: {point.data.x /* or `point.data.xFormatted` */}</div>
      ))}
    </div>
  ))}
/>
```
