### ISSUE TITLE
Monthly Line Chart values off by one

### ISSUE THREAD

**Issue by annaloukianova** [plouc/nivo#577]
**Describe/explain the bug**
When given monthly data on a line chart, the x-axis is off-by-one by apparently rounding the month down. Messing with the `xScale` precision makes this problem worse.

**To Reproduce**
https://codesandbox.io/s/nivoline-off-values-z5hm9
If you look at the data, it goes from "2018-08" to "2019-05". However, the axes and the data points when you hover over them are "mislabeled" so that `{ x: "2018-08", y: 16 }` becomes `{ x: "2018-07", y: 16 }`

**Expected behavior**
Data points to be labeled as they are given in the data array, with the correct month in the x-axis. 

**Screenshots**
![Screen Shot 2019-06-03 at 9 32 54 AM](https://user-images.githubusercontent.com/38470773/58818328-9aef7c00-85e2-11e9-8286-6e3198499022.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Chrome
 - Version 0.58.1, react 16.8.1

**Additional context**
In the discord channel, it seemed like this might be a timezone issue... I am in MST(+7)

**Comment by wyze** [comment]
If you add `useUTC: false` to your xScale, it appears to fix it. I'm not sure what is going on around all the UTC/non-UTC stuff.

**Comment by annaloukianova** [comment]
Thanks!
