### ISSUE TITLE
[Storybook] Bar Custom Axis Ticks doesn't work

### ISSUE THREAD

**Issue by rylek90** [plouc/nivo#579]
**Describe/explain the bug**
Hey, I've just noticed that one of your storybook stories throws an exception.

**To Reproduce**
1. Go to Storybook
2. Expand `Bar`
3. Click on `custom axis ticks`

See url: https://nivo.rocks/storybook/?path=/story/bar--custom-axis-ticks

**Expected behavior**
No error 🤷‍♂ 

**Screenshots**
![image](https://user-images.githubusercontent.com/10184544/58965448-ea83a280-87b0-11e9-8db4-3236e90d31d5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version (74.0.3729.169 (Official Build) (64-bit))

**Comment by EduardoAC** [comment]
Still happening

**Comment by jberube** [comment]
Updating to `0.59.0` broke my app, since I use `tick.theme` in a similar fashion.

**Comment by jberube** [comment]
Looks related to https://github.com/plouc/nivo/issues/600
