### ISSUE TITLE
Specific color for specific bar

### ISSUE THREAD

**Issue by shubham2809** [plouc/nivo#581]
Hi,

Was just wondering if there is a way to set a color to a bar in a ResponsiveBar chart
For example:
my keys for bar chart is `keys={['2017', '2018', '2019']}` 

So when I render data just of the key 2017 or 2018 or 2019, I want those bar color to be associated with a single color, as 2019 bar will always show green in color.

**Comment by plouc** [comment]
you can use a custom function for the `colors` property, for example:

```javascript
const colors = { '2017': 'red', '2018': 'red', '2019': 'green' }
const getColor = bar => colors[bar.id]

const MyBar = () => <Bar colors={getColor} {...otherProps} />
```

**Comment by leandrotk** [comment]
Dependency version: `"@nivo/bar": "0.59.2"`

I tried this code, but I always get my bars with black color.

```javascript
import { theme } from 'path/to/theme/style';

const isCurrentMonth = ({ index }) => index === 7;

const getColor = bar =>
  isCurrentMonth(bar)
    ? [theme.palette.primary.light, theme.palette.secondary.light]
    : [theme.palette.primary.main, theme.palette.secondary.main];

const MyBar = () => <Bar colors={getColor} {...otherProps} />
```

Am I missing something here?

**Comment by leandrotk** [comment]
Dependency version: `"@nivo/bar": "0.59.2"`

I tried this code, but I always get my bars with black color.

```javascript
import { theme } from 'path/to/theme/style';

const isCurrentMonth = ({ index }) => index === 7;

const getColor = bar =>
  isCurrentMonth(bar)
    ? [theme.palette.primary.light, theme.palette.secondary.light]
    : [theme.palette.primary.main, theme.palette.secondary.main];

const MyBar = () => <Bar colors={getColor} {...otherProps} />
```

Am I missing something here, @plouc?

**Comment by wyze** [comment]
@leandrotk Your code looks to be returning an array, when it should be returning a single value (the color).

**Comment by leandrotk** [comment]
I missed some information here. The bars have two different types of data, this is why the function returns an array. The `keys` prop looks like this:

```javascript
const MyBar = () => <Bar {...otherProps} colors={getColor} keys={['earnings', 'bonus']} />
```

This way the bars got both black.

But when I just add the array of colors manually, I got it all right (one bar is blue and the other is green). This code runs ok:

```javascript
const MyBar = () =>
  <Bar
    {...otherProps}
    colors={[theme.palette.primary.main, theme.palette.secondary.main]}
    keys={['earnings', 'bonus']}
  />
```

**Comment by wyze** [comment]
Here is a working example: https://codesandbox.io/s/upbeat-williams-zq7wg

The function will be executed per bar item, so it should only ever return a single value.

For debugging, you could do something like `<Bar colors={(bar) => console.log(bar) || getColor(bar)} />` so you can see the data structure coming into the function.

**Comment by leandrotk** [comment]
Got it, @wyze. That makes sense to me now. Thanks!

**Comment by fillippeyton** [comment]
In case anyone wants to use a `color` property in the `data` itself (like the docs), here's what I'm doing:

```
const data = [
  {
    id: 'views',
    color: '#00f,
    data: [
      {...},
    ],
  },
  {
    id: 'engagements',
    color: "#f00",
    data: [
      {...},
    ],
  },
];

// render
<ResponsiveLine data={data} colors={d => d.color} />
```

**Comment by yehee** [comment]
> In case anyone wants to use a `color` property in the `data` itself (like the docs), here's what I'm doing:
> 
> ```
> const data = [
>   {
>     id: 'views',
>     color: '#00f,
>     data: [
>       {...},
>     ],
>   },
>   {
>     id: 'engagements',
>     color: "#f00",
>     data: [
>       {...},
>     ],
>   },
> ];
> 
> // render
> <ResponsiveLine data={data} colors={d => d.color} />
> ```

Spent hours to get it working, thank you!

**Comment by JP-sDEV** [comment]
> In case anyone wants to use a `color` property in the `data` itself (like the docs), here's what I'm doing:
> 
> ```
> const data = [
>   {
>     id: 'views',
>     color: '#00f,
>     data: [
>       {...},
>     ],
>   },
>   {
>     id: 'engagements',
>     color: "#f00",
>     data: [
>       {...},
>     ],
>   },
> ];
> 
> // render
> <ResponsiveLine data={data} colors={d => d.color} />
> ```

does this also work for the Bar component?

**Comment by wyze** [comment]
@JP-sDEV Yes it does, that is what the initial issue was for. You can see my https://github.com/plouc/nivo/issues/581#issuecomment-630302205 for an example.

**Comment by amalviya13** [comment]
Does this work as well with the ResponsivePie component? I've tried putting the color value in my data as both hsl and hex, but neither seems to give the proper output. Below are the two ways I have tried. Is there something I have to add?

```
data = [
    {
        "color": "#0000fe",
        "id": "blue",
        "label": "blue",
        "value": 1
    },
    {
        "color": "#fe00fe",
        "id": "fuchsia",
        "label": "fuchsia",
        "value": 2
    }
]
```
```
data = [
    {
        "color": "hsl(240, 100%, 50%)",
        "id": "blue",
        "label": "blue",
        "value": 1
    },
    {
        "color": "hsl(300, 100%, 50%)",
        "id": "fuchsia",
        "label": "fuchsia",
        "value": 2
    }
]
```

**Comment by wyze** [comment]
@amalviya13 This should work on the latest version (v0.64): https://nivo.rocks/storybook/?path=/story/pie--using-colors-from-data

**Comment by amalviya13** [comment]
Does Nivo have anything that can be used like a traditional histogram? I'm aware of the Bar graphs, but I was hoping for a traditional histogram

**Comment by johnaco** [comment]
Hello folks, 
kind of new with front end dev, but can anyone give me a hint as to why my bar colors are all black with this?  I've been at this for a while trying different things.  Thanks for the help.

import React from "react";
import { render } from "react-dom";
import { ResponsiveBar } from "@nivo/bar";

import data from './data/ee_types_count'

const styles = {
    fontFamily: "sans-serif",
    textAlign: "center"
};

 const data1 = [
    { "ee.code": "FCC", "eed.descr": "Financial Company Code (Financial Consollidation)", "color": "#FF9933",  "nrCodes": 161 },
    { "ee.code": "GCC", "eed.descr": "Global Company Code (Global, Cross-System, Company Code)'", "color": "#CCFF00", "nrCodes": 28 },
    { "ee.code": "OC", "eed.descr": "Operating Concern (Profitability Analysis)","color": "#FF99CC",  "nrCodes": 15 },
    { "ee.code": "CCA", "eed.descr": "Credit Control Area","color": "#336699",  "nrCodes": 42 }
]; 
const data2 = [
    { "ee.code": "FCC", "eed.descr": "Financial Company Code (Financial Consollidation)", "color": "red",  "nrCodes": 161 },
    { "ee.code": "GCC", "eed.descr": "Global Company Code (Global, Cross-System, Company Code)'", "color": "blue", "nrCodes": 28 },
    { "ee.code": "OC", "eed.descr": "Operating Concern (Profitability Analysis)","color": "green",  "nrCodes": 15 },
    { "ee.code": "CCA", "eed.descr": "Credit Control Area","color": "yellow",  "nrCodes": 42 }
]; 
//const getColor ;
const App = () => (
    <div style={styles}>
        <h1>EBM - Organizational Units</h1>
        <div style={{ height: "400px" }}>
            <ResponsiveBar
                data={data1}
                keys={["nrCodes"]}
                indexBy="ee.code"
                valueScale={{ type: 'symlog' }}
                //colors="eed.color"
                //colors={["eed.color"]}
                //colors="#FF99CC" //ok but static
                //colors={() => data[`${id}.eed.color`]}
                //colors={() => data[`${ResponsiveBar.id}.eed.color`]}
                //colors={{datum: 'data1.color' }}
                colors={d => data1.color}
            />
        </div>
    </div>
);

render(<App />, document.getElementById("root"));

**Comment by johnaco** [comment]
Hello folks,
kind of new with front end dev, but can anyone give me a hint as to why my bar colors are all black with this? I've been at this for a while trying different things. Thanks for the help.

`import React from "react";
import { render } from "react-dom";
import { ResponsiveBar } from "@nivo/bar";

import data from './data/ee_types_count'

const styles = {
    fontFamily: "sans-serif",
    textAlign: "center"
};

 const data1 = [
    { "ee.code": "FCC", "eed.descr": "Financial Company Code (Financial Consollidation)", "color": "#FF9933",  "nrCodes": 161 },
    { "ee.code": "GCC", "eed.descr": "Global Company Code (Global, Cross-System, Company Code)'", "color": "#CCFF00", "nrCodes": 28 },
    { "ee.code": "OC", "eed.descr": "Operating Concern (Profitability Analysis)","color": "#FF99CC",  "nrCodes": 15 },
    { "ee.code": "CCA", "eed.descr": "Credit Control Area","color": "#336699",  "nrCodes": 42 }
]; 
const data2 = [
    { "ee.code": "FCC", "eed.descr": "Financial Company Code (Financial Consollidation)", "color": "red",  "nrCodes": 161 },
    { "ee.code": "GCC", "eed.descr": "Global Company Code (Global, Cross-System, Company Code)'", "color": "blue", "nrCodes": 28 },
    { "ee.code": "OC", "eed.descr": "Operating Concern (Profitability Analysis)","color": "green",  "nrCodes": 15 },
    { "ee.code": "CCA", "eed.descr": "Credit Control Area","color": "yellow",  "nrCodes": 42 }
]; 
//const getColor ;
const App = () => (
    <div style={styles}>
        <div style={{ height: "400px" }}>
            <ResponsiveBar
                data={data1}
                keys={["nrCodes"]}
                indexBy="ee.code"
                valueScale={{ type: 'symlog' }}
                //colors="eed.color"
                //colors={["eed.color"]}
                //colors="#FF99CC" //ok but static
                //colors={() => data[`${id}.eed.color`]}
                //colors={() => data[`${ResponsiveBar.id}.eed.color`]}
                //colors={{datum: 'data1.color' }}
                colors={d => data1.color}
            />
        </div>
    </div>
);

render(<App />, document.getElementById("root")); `

**Comment by gpalrepo** [comment]
Could someone show how this works for Responsive Heatmap?

**Comment by anderskleve** [comment]
I have a follow up question on this. It's super handy that you can keep the color definitions inline with the data, but what if an item is missing a color value? Would it be possible to then fallback to a predefined color scheme, such as "nivo"?

**Comment by 0tii** [comment]
> const data = [
>   {
>     id: "Yes",
>     Yes: 63.89,
>     color: "#3A82D4" // Only this color gets used in the legend
>   },
>   {
>     id: "No",
>     No: 36.11,
>     color: "#43B5E3"
>   }
> ];
> 
> const keys = ["No", "Yes"];
> 
> <Bar data={data} keys={keys} colors={({ data }) => data.color} />
> ```


Your solution is typescript friendly, the previous one did not work for me because typescript got angry about it. But in general - how is this not properly documented by nivo? Such an essential demand.
