### ISSUE TITLE
["@nivo/calendar": "^0.58.0"] ResponsiveCalendarCanvas is not defined in index.d.ts?

### ISSUE THREAD

**Issue by github0013** [plouc/nivo#585]
**Describe/explain the bug**
https://codesandbox.io/s/eloquent-sara-ngq03?fontsize=14

https://github.com/plouc/nivo/blob/v0.58.0/packages/calendar/index.d.ts#L75
missing `ResponsiveCalendarCanvas`?

**To Reproduce**

```tsx
import { ResponsiveCalendarCanvas } from "@nivo/calendar"

```

**Expected behavior**
Not to show the error.

**Screenshots**
![](https://user-images.githubusercontent.com/809378/59142605-cff13980-89fb-11e9-9a0f-88c3d202d072.png)

**Comment by plouc** [comment]
Yes, the canvas implementation definition is missing, I've added it to [this issue](https://github.com/plouc/nivo/issues/197) about missing chart types
