### ISSUE TITLE
ParallelCoordinates have invisible axis lines

### ISSUE THREAD

**Issue by janKir** [plouc/nivo#586]
**Describe/explain the bug**
In a fresh `create-react-app` project, the `ParallelCoordinates` doesn't display the axis lines. The ticks and numbers also seem not to be styled as in the docs: [https://nivo.rocks/parallel-coordinates/](https://nivo.rocks/parallel-coordinates/).

**To Reproduce**
I couldn't find a sandbox for parallel coordinates but here is a minimal repository: [https://github.com/janKir/nivo-parallel-coordinates-axes-bug](https://github.com/janKir/nivo-parallel-coordinates-axes-bug)

1. `create-react-app`
2. install `@nivo/parallel-coordinates`
3. create a simple component with the coordinates
4. start project and see how the component looks like

**Expected behavior**
Axis lines are drawn and the rest of the axis is properly styled.

**Screenshots**
![ParallelCoordinates](https://user-images.githubusercontent.com/9143877/59208416-58f9a380-8ba9-11e9-9e6e-2b63cb2e8bcb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64bit
 - Browser Firefox, Chrome
 - Version @nivo/parallel-coordinates@0.59.0

**Additional context**
```json
"dependencies": {
    "@nivo/parallel-coordinates": "^0.59.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
}
```

**Comment by plouc** [comment]
@janKir, it's not a bug, the website just use a different theme, that's all, you can pass a theme object to the component, please have a look at [the default theme](https://github.com/plouc/nivo/blob/master/packages/core/src/theming/defaultTheme.js) for available keys.

**Comment by janKir** [comment]
Okay, thanks for your reply! This is absolutely confusing, why doesn't the component just take the same theme settings as the website by default? The fact that there is no documentation on theming wasn't very helpful either. I even tried to specify theming options but didn't succeed without docs.

Is there a way to get the theming options the website uses on this component?

**Comment by plouc** [comment]
Well, the website uses a theme which suits the website. you can have a look at the code of the website which is also available in this repository.
