### ISSUE TITLE
Add theme styles to chip inside tooltip component.

### ISSUE THREAD

**Issue by Et3rnal1** [plouc/nivo#588]
**Is your feature request related to a problem? Please describe.**
Currently, the chip on tooltip can shrink if tooltip text is large enough and there is maxWidth limit on tooltip container, like this: http://prntscr.com/o0chvp.

**Describe the solution you'd like**
It would easily be fixed by adding a section of theme to chip component, thus allowing for custom css to be added to chip component. Currently all chip properties are hardcoded inside of tooltip component.

Thanks in advance!

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/589
