### ISSUE TITLE
Rendered ResponsiveLine not smoothed 

### ISSUE THREAD

**Issue by christian-nils** [plouc/nivo#594]
Hello!

I would like to plot a simple curve (with 1000 pts). When I do so, the curve is not smooth, (https://codesandbox.io/embed/nivo-aliasing-etho9)

What am I doing wrong? Is there too many points (or not enough...)?

Thank you in advance

**Comment by plouc** [comment]
Did you tried all the available options on the [demo](https://nivo.rocks/line)?

<img width="568" alt="Capture d’écran 2019-06-12 à 17 29 42" src="https://user-images.githubusercontent.com/501642/59335570-ccc9b680-8d37-11e9-864f-a4c7e785c52e.png">

**Comment by plouc** [comment]
I think you have too many points to have a smooth curve though.

**Comment by christian-nils** [comment]
Merci pour ton aide!

I have tried all the different values for the _curve_ option without success.

You must be right, I will try to resample the data.

//CN
