### ISSUE TITLE
Pie Canvas tooltip doesn't work

### ISSUE THREAD

**Issue by amihalopoulos** [plouc/nivo#597]
Seem like tooltipFormat & tooltip both get ignored by ResponsivePieCanvas. Looks like the same issue happens on your website example

https://nivo.rocks/pie/canvas/

scroll down to your custom tooltip example. That doesn't work

**Comment by wyze** [comment]
Seems to be working for me. Even put it up in a CodeSandbox, https://codesandbox.io/s/admiring-mountain-5is6m. Are you having issues with it? If so you should post a CodeSandbox showing your issue.

**Comment by amihalopoulos** [comment]
I'm still unable to change the value on the tooltip in your CodeSandbox

**Comment by wyze** [comment]
Please provide the code you are trying that is not working so we can help you further.

**Comment by plouc** [comment]
@wyze, as I understand this issue, it's about custom tooltip for PieCanvas, which is not implemented yet.

@amihalopoulos, there's already an issue regarding custom tooltip status, https://github.com/plouc/nivo/issues/192, I've added it to the todo list.
