### ISSUE TITLE
color for specific column Bar or return color of colorBy="index"

### ISSUE THREAD

**Issue by jeisonng** [plouc/nivo#598]
I need to change the color of a specific column of the bar chart but I did not find any method for this.

```javascript
getRandomColor() {
	var letters = '23456789ABD';
	var color = '#';
	for (var i = 0; i < 6; i++) {
		color += letters[Math.floor(Math.random() * 11)];
	}
	console.log("color: ", color)
	return color;
}

_.each(chartao, chart => {
	const color = this.getRandomColor()
	const data = {
		id: chart[0] != undefined ? chart[0] : "indefinido",
		label: chart[0] != undefined ? chart[0] : "indefinido",
		valor: _.size(chart),
		color
	};
	colorId.push(color)
	dataChart.push(data);
});


<Bar
	data={value}
	keys={["valor"]}
	indexBy="id"
	colors={colorId}
	axisLeft={{
		tickSize: 5,
		tickPadding: 5,
		tickRotation: 0,
		legend: "Valores",
		legendPosition: "middle",
		legendOffset: -40,
	}}
	width={350}
	height={300}
	padding={0.5}
	borderWidth={0}
	margin={{
		top: 30,
		right: 0,
		bottom: 50,
		left: 50,
	}}
	enableRadialLabels={false}
	enableLabel={false}
	enableGridY={true}
	slicesLabelsTextColor="#ffffff"`
/>
```

**Comment by wyze** [comment]
Have you tried https://nivo.rocks/storybook/?path=/story/bar--using-custom-color ? Sorry, it is hard to read the code you posted as all the formatting was lost. You could post in a CodeSandbox and we can fix it from there.

**Comment by plouc** [comment]
@jeisonng, I've formatted your code, but please try to do it when you submit an issue, it was barely readable. You're asking people to help you and spend some time doing so, so you should at least take some time to make sure the issue is clear enough and the code readable.
Also, there's an issue template, you should stick to it. 
Thank you

**Comment by plouc** [comment]
@jeisonng, You'll find a working demo [here](https://codesandbox.io/s/bar-custom-color-8ggev)
