### ISSUE TITLE
Feature - Start Bar Graph from non 0 value

### ISSUE THREAD

**Issue by martin-kieliszek** [plouc/nivo#599]
**Is your feature request related to a problem? Please describe.**

Start bar graphs from a non 0 value. eg. -60.

Bar graphs will then climb from your floor/ceiling towards their value.

Eg. [http://www.msarmento.com.br/images/pre_eq_sample1.png](http://www.msarmento.com.br/images/pre_eq_sample1.png)

Problem I am facing is that I have personally not found a way to represent the above graph using BarChart. If you have a recommendation - please let me know I'd be grateful

**Describe the solution you'd like**
Introduce a "startFrom" or "beginAt" property for Bar Charts / other charts that you think could benefit from it

**Describe alternatives you've considered**
I considered and failed to find a hack where I thought I could add yAxisTickValues that would map a label of "-60" to an actual integer value of 0. So in otherwords, the BarChart would still start bars growing from integer 0, but the label could show it as being "-60" and give the illusion that the startFrom value is non 0

**Additional context**

Please reference the above link to see the motivation for starting at a non zero values.

**Comment by wyze** [comment]
You need to get a little creative, check this out: https://codesandbox.io/s/focused-burnell-lt8xr

**Comment by plouc** [comment]
I think the component needs another property, something like baseYValue

**Comment by vincentaudebert** [comment]
Any update on this idea? It would be great indeed.

**Comment by plouc** [comment]
@vincentaudebert no progress on this, but contributions are welcome ;)

**Comment by AndiDog** [comment]
I'm using `valueScale: { clamp = true, ... }` for this. It's not perfect because both top and bottom edge of a bar may be cut off and normally I only want the bottom edge to start at a non-zero value. But this does the job.
