### ISSUE TITLE
Warning: Failed prop type: The prop `theme.markers.textColor` is marked as required in `CartesianMarkersItem`, but its value is `undefined`.

### ISSUE THREAD

**Issue by malzaeem** [plouc/nivo#600]
**Description:** 
When using ResponsiveBar I get this Error (Warning: Failed prop type: The prop `theme.markers.textColor` is marked as required in `CartesianMarkersItem`, but its value is `undefined`.). Beside of this error the chart works perfectly.
I tried to add textColor to the marker, but no luck.

**To Reproduce**
I have included a codesandbox https://codesandbox.io/s/mystifying-bhabha-s7te6?fontsize=14 with my code. 
Also, the nivo/bar version I'm using is "@nivo/bar": "^0.58.0", 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.90

**Comment by wyze** [comment]
In the CodeSandbox provided, you need to include a `height` on the div for the `ResponsiveBar` component to render. After I added that, it worked fine. I'm not seeing the PropType error you posted above though.

**Comment by malzaeem** [comment]
Thanks @wyze I just updated the height and now it's visible. Also, I don't see the error on codesandbox, but on my local setup I see the error and when I remove the markers object from <ResponsiveBar /> I don't get the error.

**Comment by plouc** [comment]
@malzaeem, you have `@nivo/bar@0.59.0`, that's probably why it works there and not locally, you should upgrade the package.

**Comment by malzaeem** [comment]
@plouc, just updated @nivo/bar to 0.59.2 and still getting the same Warning: Failed prop type: The prop `theme.markers.textColor` is marked as required in `CartesianMarkersItem`, but its value is `undefined`.
