### ISSUE TITLE
Expose legendRotation for Axes

### ISSUE THREAD

**Issue by foreverhomesg** [plouc/nivo#602]
**Is your feature request related to a problem? Please describe.**
Change the rotation of axes' legend

**Describe the solution you'd like**
can specify legendRotation

**Describe alternatives you've considered**
I have checked the code located here [Code](https://github.com/plouc/nivo/blob/master/packages/axes/src/components/Axis.js#L70) We can consider exposing legendRotation similar to legendOffset

**Comment by jge58** [comment]
Hi, is it possible to implement this feature now please ?
It's frustrating not to be able to make vertical text symmetrical.
The 2 requests have been closed https://github.com/plouc/nivo/issues/2363 without changes.

Thank you

**Comment by plouc** [comment]
Hi @jge58, unfortunately, it's not possible.
That being said, contributions are welcome.
