### ISSUE TITLE
clarification for SSR - using SVG vs rendering API

### ISSUE THREAD

**Issue by gcloeval** [plouc/nivo#611]
Hi,
Just wondering if you could provide some clarification on what / when would you use the dedicated SSR rendering API.

We are experimenting with next.js and rendering a simple pie, i.e.:

```
<Pie
      data={data}
      width={300}
      height={300}
..
```

So this seems to be all working as expected - blazing fast too!!!! The first ever response from server shows pure html containing the svg,i.e:

`<svg xmlns="http://www.w3.org/2000/svg" role="img" width="300" height="300"><rect width="300" height="300" fill="transparent"></rect><g transform="translate....`

In addition, once on the client after hydration, we get proper click events so we can click on a pie slice.

So amazing!!!!, thanks a lot.

So really the only quesiton is when would you use the rendering API? What are the benefits of it? Just want to make sure we are not misunderstanding / missing something?

**Comment by gcloeval** [comment]
As a small follow up - and perhaps this is what the render API is there for - once we rendered the SVG on the server, the SVG will keep the height/width that it was requested, i.e. 300px by 300px

Is there an approach / best practice how to then enable/inject some sort of responsivnes to the chart, so it adopts to screen size.
The following doesn't prevent the size of the size of the SVG
```
<div style={{ maxWidth: '200px' }}>
            <Pie />
          </div>
```
Let us know if you have some recommendations on possible approaches to achieve both SSR and responsivness.
Cheers thanks again.

**Comment by gcloeval** [comment]
I have added a super simple sandbox with nextjs rendering a pie - any idea how to force the pie to fit to say %50 or %75 of the screen?
https://codesandbox.io/s/hello-world-uitgv

**Comment by plouc** [comment]
The HTTP API can be used to generate charts to be embedded in other contexts (static charts), it wasn't made for SSR, for this you can use regular components.

**Comment by plouc** [comment]
Using responsive components on server side won't work though, unfortunately I don't have a solution for this, rendering with a fixed size and then resizing will trigger transitions if `animate` is true, which isn't desirable IMO.

**Comment by plouc** [comment]
Maybe you could switch the components depending on the context, using a fixed size for SSR and then replacing it by the responsive alternative, but I'm not sure there will be real benefit from doing so.

**Comment by gcloeval** [comment]
Yeah after some more research, its a common issue in any SSR of any component....
There is a few libraries that investigate user agent string on the server - so I can potentially detect device i.e. mobile/tablet/desktop at least and use that to best guess approximate size:

https://deviceatlas.com/blog/javascript-server-side-rendering-device-detection

But I think it might just overcomplicate things and make them inconsistent. We will render at server at 300px and put a custom "maximize" button next to a chart, then on click we will replace with a responsive version.

Thanks for the help.
