### ISSUE TITLE
Missing props in LineProps, Typescript definition file

### ISSUE THREAD

**Issue by kahshiu** [plouc/nivo#615]
@nivo/line/index.d.ts, typescript definition file is missing onClick, onMouseMove, other event callback handlers in LineProps. Please add those in, as documented in 

![image](https://user-images.githubusercontent.com/1201413/60564991-59462280-9d94-11e9-9ff2-0660ae3bb85e.png)

Right now, Im getting error from typescript complaining error due to missing handlers
![image](https://user-images.githubusercontent.com/1201413/60564951-33208280-9d94-11e9-908f-49cb9a6c8a55.png)

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/641, will be available in the next release
