### ISSUE TITLE
Line chart enableSlices x tooltip out of viewport bounds

### ISSUE THREAD

**Issue by stephanoshadjipetrou** [plouc/nivo#617]
Hi @plouc thanks again for this amazing library!

In line chart [example](https://nivo.rocks/line) with enableSlices equal to 'x' you can see in the screeshot the crosshair tooltip is getting out of viewport bounds when you hover the far most right x point. Is there a way to show the tooltip at the left side of the crosshair (in this case)?

<img width="861" alt="line" src="https://user-images.githubusercontent.com/11508354/60593951-84d50700-9dac-11e9-8bbb-b789ced12c1b.png">

**Comment by plouc** [comment]
Hi @stephanoshadjipetrou, not for now, there's already an opened issue about this https://github.com/plouc/nivo/issues/580, I think I'll restore the old behavior which displayed the tooltip on the right for the first half of the chart or on the left for the second one.

**Comment by vintg** [comment]
> Hi @stephanoshadjipetrou, not for now, there's already an opened issue about this #580, I think I'll restore the old behavior which displayed the tooltip on the right for the first half of the chart or on the left for the second one.

does anyone know which older version has this? there doesn't seem to be any new updates on this for over 4 months, so we'll probably need to revert back to an older version
