### ISSUE TITLE
LabelFormat Paragraph

### ISSUE THREAD

**Issue by marcx28** [plouc/nivo#618]
Is it possible to make an paragraph between 2019/7and 01.07- 13.07? Sadly \n does not work.

`export default [
    {
        "date": "2019/7<paragraph here> 01.07 - 13.07",
        "Type A": 5,
        "Type AColor": "hsl(110, 70%, 50%)",
        "TypeB": 12,
        "TypeBColor": "hsl(54, 70%, 50%)"
    }`
![image](https://user-images.githubusercontent.com/35005352/60598533-23f9fe80-9dad-11e9-9d7c-29140a5690a4.png)

**Comment by plouc** [comment]
@marcx28, please have a look at [this issue](https://github.com/plouc/nivo/issues/353) which suggest potential solutions.
