### ISSUE TITLE
Feature request: Ability to render custom sliceLabel

### ISSUE THREAD

**Issue by andresgutgon** [plouc/nivo#62]
Hi, thanks for this amaizing project. I just started using it and I was wondering if it would be possible to add ability to change `sliceLabel` look & feel by passing a custom renderer.

What I want to accomplish is rounded labels like this:
![image](https://user-images.githubusercontent.com/49499/30776179-367b299e-a0a2-11e7-8609-c956cb15261c.png)

If I'm not wrong that's not possible with a `<text .../>{label}</text>` node. And I don't see I way of overwrite it in code https://github.com/plouc/nivo/blob/8db9a1366fc53a8d0eb9dbd53bec5573e2c04ac0/src/components/charts/pie/PieRadialLabels.js#L101

Maybe I'm missing something. 

I would like to contribute and do a PR to allow this behaviour. What do you think?

Thanks again for your work

**Comment by plouc** [comment]
@andresgutgon, you're right, it's not feasible in SVG. In fact, the first pie implementation had this feature, but I removed it as it's not really standard and can cause issue depending on the chart / font size. 

I like the idea to have the ability to define a custom component, your PR will be really welcome :)
