### ISSUE TITLE
core-js dependency toooo old

### ISSUE THREAD

**Issue by Akiyamka** [plouc/nivo#621]
@nivo/pie > recompose > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

**Comment by plouc** [comment]
nivo uses the latest version of `recompose`, there's nothing I can do about this, if you want to fix this you could probably [force the resolution of this module](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)

**Comment by Akiyamka** [comment]
@plouc recompose [officially dead](https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018)

**Comment by plouc** [comment]
Yes, that's why I'm migrating to hooks, but given the amount of code and the number of packages, it takes time…
