### ISSUE TITLE
Spaces in Sankey node ids break colors

### ISSUE THREAD

**Issue by OzzieOrca** [plouc/nivo#623]
**Describe/explain the bug**
Using spaces as node ids in Sankey diagrams breaks custom link gradients.

**To Reproduce**
https://codesandbox.io/s/inspiring-sammet-g7txn

I copied the code out or https://nivo.rocks/storybook/?path=/story/sankey--with-custom-node-link-coloring, made it render, and then just added the lines with the comment `// Breaks colors` that maps all ids to have ` Test` appended to the end.

1. Edit https://nivo.rocks/storybook/?path=/story/sankey--with-custom-node-link-coloring to use a space in a node id.
2. Custom colors disappear and you're left with grey links.

**Expected behavior**
Custom colors should continue to render even when using

**Screenshots**
With space in id:
![Screen Shot 2019-07-08 at 10 09 26 PM](https://user-images.githubusercontent.com/756501/60860964-826c1600-a1cd-11e9-9898-c02187820bb2.png)
Without space in id:
![Screen Shot 2019-07-08 at 10 09 56 PM](https://user-images.githubusercontent.com/756501/60860965-8304ac80-a1cd-11e9-9943-3b94d2de8d27.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 75.0.3770.100

**Additional context**
https://github.com/plouc/nivo/issues/466 seems like it could have been related.

**Comment by julimi** [comment]
Met same issue but I think @wyze has already solved it, thanks! Looking forward to the next version release! By the way, in my opinion, it will be better to display label via nodes.label instead of nodes.id.

**Comment by itschrislow** [comment]
Spaces still break colors **but only on mobile**

![IMG_5906](https://github.com/plouc/nivo/assets/21194612/a5c9f142-7313-4bf3-a810-b87e3cf9267b)
