### ISSUE TITLE
@nivo/bar crashes on IE11

### ISSUE THREAD

**Issue by thomasthiebaud** [plouc/nivo#624]
**Describe/explain the bug**

`@nivo/bar` does not seems to work on IE11

![Screenshot 2019-07-09 at 08 47 25](https://user-images.githubusercontent.com/3715715/60865448-5b8dfe00-a226-11e9-981e-5b43bdf8e80f.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser IE11
 - Version `"@nivo/bar": "^0.59.1"`

**Comment by plouc** [comment]
Sorry @thomasthiebaud, but this is due to the latest d3 modules which target modern browsers (`d3-scale` here) not nivo, if you want to support older ones, you'll have to transform those modules.

**Comment by thomasthiebaud** [comment]
@plouc yes, but that having d3-scale^3.0.0 as a dependency, you make @nivo/bar incompatible with IE 11

**Comment by plouc** [comment]
@thomasthiebaud, [that's already the case](https://github.com/plouc/nivo/blob/master/packages/scales/package.json#L18)

**Comment by thomasthiebaud** [comment]
Ok ;) When I'll have to transpile something or get rid of IE11. Thanks for the insights
