### ISSUE TITLE
heatmap: add color scale legend

### ISSUE THREAD

**Issue by mgilbir** [plouc/nivo#625]
**Is your feature request related to a problem? Please describe.**
When you hide the labels in the cells, you lose all sense of scale for the meaning of the colors. 

**Describe the solution you'd like**
I would like a gradient legend that maps the colors to values in the heatmap.

**Additional context**
There are examples of what I'm thinking in these blocks (color scale legend under the chart):
http://bl.ocks.org/tjdecke/5558084
http://bl.ocks.org/ianyfchang/8119685

**Comment by michellehabu** [comment]
@plouc We're also interested in having this feature. Are you working on it? Is there an ETA for when it'll be available?

**Comment by bujesse** [comment]
Also looking for this feature!

**Comment by AnitaMariaThomas** [comment]
Hi @plouc, Is there any chance that we can use @nivo/legends in @nivo/heatmap ? If so, can you give an example ?
Thanks in advance

**Comment by Luiz-Fellipe** [comment]
bump
