### ISSUE TITLE
Y Axis in Responsive Line incorrect.

### ISSUE THREAD

**Issue by pratikguru** [plouc/nivo#627]
I've been using ResponsiveLine and noticed a peculiar issue. The Y axis range on the left does not coincide with the values on the values on the graph. 

![image](https://user-images.githubusercontent.com/23006473/60906169-8a1ad180-a244-11e9-9331-af594bdb8b22.png)

As you can see on the image the example also has the same issue. The value on Y is 104 but the scale is at a higher range. Anyone else had this issue?

**Comment by wyze** [comment]
This happens if you set `yScale={{ stacked: true }}`, which looks to be the case in the above image as none of the lines cross.

**Comment by pratikguru** [comment]
But the highest point/count on the Y-axis does not cross 300, but the max range is 1000. Isn't the max count and min count on the Y axis supposed to be aligned to the points on the line?

**Comment by pratikguru** [comment]
@wyze thanks for the reply. My bad. Since the stacking was set to true, the range on the Y Axis and the graph lines do not align. But i got it to work by setting it to false.

**Comment by cazroam** [comment]
@wyze you know, if you wanted to make your code cleaner, it also works if you just take out `stacked: true` all together (no need to set it to false) :)
