### ISSUE TITLE
Customize Mesh Hover Label

### ISSUE THREAD

**Issue by karenqinn** [plouc/nivo#628]
Hi Everyone,

I would like to customize the label that pops up on line graphs with mesh enabled. Currently, I was able to customize the spliceTooltip to display the type of label I want, but I want to be able to do that without splices, and with mesh on. 

Thank you!

**Comment by karenqinn** [comment]
Follow up: Would it be possible to add `tooltip` to the LineProps types? Similar to this? 

`sliceTooltip?: (data: LineSliceData) => React.ReactNode;`

**Comment by wyze** [comment]
There is a `tooltip` property already, just missing the typings which are being added in https://github.com/plouc/nivo/pull/568.

**Comment by karenqinn** [comment]
Thank you @wyze !! 👍

**Comment by plouc** [comment]
@karenqinn, the PR has been merged, it'll be available in the next release.
