### ISSUE TITLE
Using an icon as pie chart label.

### ISSUE THREAD

**Issue by Creaa** [plouc/nivo#629]
Hi,
Like I wrote in a topic, is it possible? 
I am trying to use icon from material ui library. 
But I can print it only in a tooltip, labels are empty. 

Thanks.

**Comment by plouc** [comment]
The custom pie tooltip must be implemented, which is not yet the case. I'm closing this in favor of https://github.com/plouc/nivo/issues/597

**Comment by Creaa** [comment]
Uhmm, sorry but I cannot find an answer for my question. I am NOT talking about tooltip. 
Tooltip is fine, I can custom it. But I mean that, what if I'd like to use some icons (img, svg, or library) to represent some data as a LABEL (and display it in a legend). It is possible?

**Comment by plouc** [comment]
Oh, sorry I missed that

**Comment by plouc** [comment]
It's not feasible for legends, I'll have to check for labels

**Comment by plouc** [comment]
https://github.com/plouc/nivo/pull/1204 is adding support for custom layers, which is gonna add the ability to add an extra layer with icons.
