### ISSUE TITLE
Possible to set border right (etc) on bar

### ISSUE THREAD

**Issue by tomyates** [plouc/nivo#632]
Is it possible to set a border-right or border-top value on bar?

Trying to achieve this:

![Screen Shot 2019-07-11 at 16 59 13](https://user-images.githubusercontent.com/785769/61074653-188f7e80-a410-11e9-8ec4-1c862ea0a4f7.png)

I've tried a number of things including adding a border, and considered doing something hacky such as placing another bar of a darker colour behind the bar to give appearance of a border right.

Any pointers in the right direction would be appreciated.
Great library by the way @plouc !

**Comment by plouc** [comment]
Unfortunately neither SVG nor canvas support border-(top|right|bottom|left), however you can achieve this by overriding the bar component or adding an extra layer, the layer solution is probably the easier.
I've created an example [here](https://codesandbox.io/s/bar-border-right-jqvp5)

**Comment by plouc** [comment]
You could also have a loook at [a more sophisticated example](https://nivo.rocks/storybook/?path=/story/bar-race-chart--demo)

**Comment by tomyates** [comment]
> You could also have a look at [a more sophisticated example](https://nivo.rocks/storybook/?path=/story/bar-race-chart--demo)

Thanks @plouc, that's a great, great help.

**Comment by littke** [comment]
![image](https://user-images.githubusercontent.com/227383/92431022-44f57680-f14b-11ea-9f97-30dea891b596.png)

@plouc Is it just me or do neither of the linked examples have border radius on the actual bars? 

(Big Sur b7, latest Chrome)

**Comment by sfiorotti** [comment]
Update link ~> https://nivo.rocks/storybook/?path=/story/bar--race-chart

**Comment by EsranurGalipKayahan** [comment]
Hi! I would like to add border to selected subgraphs? Is there any possible way to do that?
