### ISSUE TITLE
Support for other d3 geo projectiontypes

### ISSUE THREAD

**Issue by rccoe** [plouc/nivo#633]
**Is your feature request related to a problem? Please describe.**
I would like to use other projection types included in d3-geo, like albersUsa, for example

**Describe the solution you'd like**
Please add these to the possible projectionTypes for GeoMap and/or Chloropleth

**Describe alternatives you've considered**
I've considered setting a zoom, but that is not ideal

**Comment by FoxxMD** [comment]
why was this closed? I need to use albersUsa but it is not possible given `projectionById` is hardcoded

**Comment by jschraub** [comment]
This is the only feature holding me back from using Nivo for my Geos/Maps. Please re-open and add more support for other projections.
