### ISSUE TITLE
SwarmPlotCanvas axis direction

### ISSUE THREAD

**Issue by zepplock** [plouc/nivo#638]
**Is your feature request related to a problem? Please describe.**
Currently SwarmPlotCanvas linearly scales and plots values from mix to max. It would be great if the order could be reversed.

**Describe the solution you'd like**
An option in valueScale field, something like {..., "direction": 1 } or {..., "direction": -1 }

**Describe alternatives you've considered**
I could not find (in docs or source code) how to reverse the order for scaled axis

**Comment by zepplock** [comment]
@plouc is this a valid issue? Is there a quick/dirty walk around?

**Comment by plouc** [comment]
@zepplock, yes it is, I've just merged a PR which solve this, you'll be able to add `{ …, reverse: true }`, it'll be available in the next release :)

**Comment by zepplock** [comment]
Thanks!
