### ISSUE TITLE
Custom Symbol Hover Effects

### ISSUE THREAD

**Issue by karenqinn** [plouc/nivo#643]
Hi! 

I was wondering if there was any feature available that would provide effects on hover for custom point symbols. I used a `pointSymbol` using a svg and I would love to have it expand and add text on mouse over
 
Thanks!
Karen

**Comment by ginnyedelstein** [comment]
This would be very helpful for me as well!

**Comment by Boeing787** [comment]
Also seconding this, would be very helpful

**Comment by renderlife** [comment]
Yes a very necessary feature

**Comment by jmahabal** [comment]
I got around this by using hooks and `onMouseMove`. In pseudocode,

```
[id, setId] = useState()
<ResponsiveLine
    ...
    pointSymbol={data => {
        if (data.datum.id === id) { 
            return <circle r=10 />
        } else {
            return <circle r=5 />
        }
    }}
    onMouseMove={d => if (id !== d.data.id) { setId(d.data.id) }}
    onMouseLeave={d => setId()}
    ...
/>
```

I'd love to know if there's a better / more performant way! I haven't gotten css transitions to work with this due to re-renders, however. It'd be great to figure that out too!

**Comment by wyze** [comment]
You can try a ref instead to avoid the re-renders, but not sure how you would use that with css transitions.
