### ISSUE TITLE
XScale time precision: week

### ISSUE THREAD

**Issue by xhuthetribe** [plouc/nivo#645]
Hello,

First, thank you for your awesome work !

I'm working on a time scale line chart, I'd like to have a precision of week but this does not seem possible using `precision: week` in the xScale definition. Is there any alternative ?

Thanks !

**Comment by plouc** [comment]
`precision` defines the unit from which the date should be cut-off, so `week` isn't a valid unit, however if your goal is to have the x axis' ticks to show weekly intervals, you can use `xScale={{ ..., tickValues: 'every week' }}`.

**Comment by xhuthetribe** [comment]
> `precision` defines the unit from which the date should be cut-off, so `week` isn't a valid unit, however if your goal is to have the x axis' ticks to show weekly intervals, you can use `xScale={{ ..., tickValues: 'every week' }}`.

Thank for this, that solves my issue.
