### ISSUE TITLE
Left padding between the y-axis and first data point on Line Chart

### ISSUE THREAD

**Issue by davidhan527** [plouc/nivo#646]
![image](https://user-images.githubusercontent.com/4370987/61546290-40d23b00-aa17-11e9-8eb9-ff38936e28a2.png)

Is there a way to add space between the axis and the first data point so that the data point labels don't conflict with the y-axis label? I tried to find it in the docs but didn't see anything.

Thanks for the help and for your work on this awesome library!

**Comment by wyze** [comment]
You should be able to change the `axisLeft.tickPadding` value.

**Comment by davidhan527** [comment]
That worked. Thanks for the help!
