### ISSUE TITLE
🎨 Stacked Line Chart add areaColor prop  

### ISSUE THREAD

**Issue by ulysset** [plouc/nivo#647]
Thank you very much for this amazing library.

My problem is that I can't make a stacked line chart with an area colour a bit brighter than the actual line. For example http://recharts.org/en-US/examples/StackedAreaChart
With the yScale stacked set to true, the enableArea set to true the areaOpacity set to 0.7, for example, the areas colours at the bottom become way too dark. Similarly, areaBlendMode don't seem ta work for that use case.

Possible solution: a prop that would let you choose the colour of the area:
```JSX
<ResponsiveLine 
  yScale={{
    stacked: true
  }}
  enableArea={true}
  areaColor={{ from: 'color', modifiers: [ [ 'brighter', '1.6' ] ] }}
/>
```
The areaColor prop would work **exactly** the same way as the "borderColor" prop in the [bar chart API](https://nivo.rocks/bar/)

Let me know if this is possible!

**Comment by JosNun** [comment]
@ulysset With the exception of the workaround in #652, have you found any good workarounds?

**Comment by ulysset** [comment]
Hi, I've used another library because I needed that type of graph, but would still recommend using Nivo :)
