### ISSUE TITLE
Feature request: Table 

### ISSUE THREAD

**Issue by thucnc** [plouc/nivo#65]
Some time I have a small json array and want to show it as a simple table. It would be nice if nivo can provide this feature, so that I can use your api in all my use cases to generate image. Thanks

**Comment by plouc** [comment]
Hi @thucnc,

Thank you for the suggestion, I keep focus on charts only, data tables can be tricky to implement, sorting, filtering, responsiveness, and there are some pretty good modules for that purpose.
