### ISSUE TITLE
Documentation for <ResponsiveNetwork/> on the site is inaccurate.

### ISSUE THREAD

**Issue by xanderjakeq** [plouc/nivo#654]
On the [site](https://nivo.rocks/network/) it says that the component needs a `data` prop in the form of: 
```
{
"nodes" : [{}],
"links": [{}]
}
```
But is expecting separate `nodes` and `links` props.

**Comment by Larissagilliane** [comment]
I can fix that right now

**Comment by Larissagilliane** [comment]
@xanderjakeq  can you explain with more details how the data should be shown, please ?

**Comment by xanderjakeq** [comment]
This is the example given.
![image](https://user-images.githubusercontent.com/13279523/72455842-88047300-3791-11ea-8f14-b098cf648b9a.png)

It shows that the `ResponsiveNetwork` component accepts a `data` prop. 

However, the [source code](https://github.com/plouc/nivo/blob/master/packages/network/src/Network.js) for the `Network` component doesn't and expects a separate `nodes` and `links` props on lines 25 and 26.

Would suggest changing the example maybe?

**Comment by jdelpierre** [comment]
Thanks @xanderjakeq xanderjakeq
Yes, there is an inconsistency between the documentation and the code.
This is what the code states

![image](https://user-images.githubusercontent.com/12846806/75874009-3bdcc300-5e11-11ea-8500-bbeedac7a8b7.png)

**Comment by jlangner-hubble** [comment]
This is def still an issue in the documentation. Has anyone submitted a PR for this?

**Comment by umarsayyad** [comment]
Still getting the same error when defining the data prop, same error "TypeError: Cannot read property 'nodes' of undefined"

`	nodes={data.nodes}
	links={data.links}`
