### ISSUE TITLE
className of tooltips

### ISSUE THREAD

**Issue by john-martinez-729** [plouc/nivo#658]
I'm interested in styling the tooltips of the Pie/Bubble/Choropleth charts. What is the className (if any) of the tooltip containers, or how can I go about adding them?

**Comment by Taelkir** [comment]
This is how I've styled my Choropleth tooltip - this prop is provided to my <ResponsiveChoropleth /> component. You could add a className in to the element returned by the function and make changes as needed. Not sure about Pie and Bubble.
```
							tooltip={e => {
								return (
									<div
										style={{
											background: "white",
											padding: "9px 12px",
											border: "1px solid #ccc",
											borderRadius: "25px",
											display: "flex",
											alignItems: "center",
											justifyContent: "center",
											flexDirection: "column",
											color: "black",
										}}
									>
										{e.feature.properties.name}:{" "}
										{e.feature.value
											? e.feature.value.toLocaleString()
											: "No data"}
									</div>
								);
							}}
```

**Comment by john-martinez-729** [comment]
This works for Choropleth, however Pie charts and Bubble charts have an outer div that contains the tooltips. It would be nice if there were consistency in tooltips between charts, or if the out divs were removed.

**Comment by john-martinez-729** [comment]
Specifically, this is the div I'm having trouble with. My tooltip is listed with the class "bubble-chart-tooltip". This div does not appear on the Choropleth custom tooltip.
![div image](https://user-images.githubusercontent.com/52676492/62546295-38f50200-b831-11e9-879d-d90aedb24f0e.png)

The code for my tooltip: 

```
    renderTooltip = e => {
        return (
            <div className='bubble-chart-tooltip' id={e.id}>
                {e.id}:{" "}
                {e.value
                    ? e.value.toLocaleString()
                    : "No data"}
            </div>
        );
    } // end of renderTooltip(e)
```

**Comment by shivika** [comment]
Was this resolved? I'm also looking for a way to add a class to the outer most tooltip container, the one above the one john-martinez-729 is pointing at.

**Comment by RobertB4** [comment]
I'm having the same problem with bar charts. Would be nice if the additional divs could be removed.

**Comment by litari** [comment]
Pretty annoying, but I managed to solve it by adding the following to my custom theme:
`<Bar
      theme={{
        tooltip: {
          container: {
            padding: 0,
          },
        },
      }} ..... />`
