### ISSUE TITLE
Question: Data points support

### ISSUE THREAD

**Issue by ChandlerMBing** [plouc/nivo#661]
Hi, I've been playing around with Nivo a bit but once I entered 10'000 data points into my "one-line" line chart, it just died completely, it actually slowed down noticeably with as little as 1000 data points. My client might have 100'000 data points or even more with multiple lines on it, is there something I can do to improve performance for large datasets?

**Comment by wyze** [comment]
You can use the canvas implementation. https://nivo.rocks/line/canvas/

**Comment by ChandlerMBing** [comment]
Yeah, I thought I was but didn't realize that code samples don't change between svg and canvas versions. Thanks for the help, it's much better now :)
