### ISSUE TITLE
Error in Stream component

### ISSUE THREAD

**Issue by b0gok** [plouc/nivo#67]
Hello!

I have an error when trying to use params from your example for `Stream` component.

```js
Uncaught TypeError: Array.prototype.slice called on null or undefined
```

Here is example https://www.webpackbin.com/bins/-Kw1kMTwLtEqBY5sZvn5

**Comment by plouc** [comment]
@b0gok the keys to use are missing, I've updated the example: https://www.webpackbin.com/bins/-Kw5sL2zoW45GvIBSRiP

**Comment by tibotiber** [comment]
@plouc I think this is not reflected in the docs currently. Am I missing something?
