### ISSUE TITLE
Question about having different "curves" per series in one LineChart

### ISSUE THREAD

**Issue by ralmo** [plouc/nivo#672]
Hello, 

I'm looking for the correct way to use different `curve` styles per series within one line chart. 

Usecase: I need to have series consisting of setpoints to be displayed as "steps". The corresponding actual values need to be displayed as normal lines, though.

However, I haven't been able to find related information in documentation or storybook.

Could you point me into the right direction, please? Thank you!

**Comment by WBialekMerixStudio** [comment]
I also have this problem. Is there any way to achieve that?

**Comment by ShanonJackson** [comment]
I also have this problem. Ideally you could curve each line differently on a case-by-case basis; Our usecase is we have 1 line trending real-time that we don't want to "hint" at a trend for I.E it uses curveStepAfter, and we want another line that trends linearly IE we do want to 'hint' that there is some kind of trend between points.
