### ISSUE TITLE
@nivo/bump: Check the render method of `Bump`.

### ISSUE THREAD

**Issue by andrebm** [plouc/nivo#673]
Hello,
 I have a issue using the example provided by Nivo Documentation:
  https://nivo.rocks/bump/

Error:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Bump`.

example:
https://codesandbox.io/s/nivoline-chart-bottom-tick-values-tyy6r?fontsize=14

**Comment by wyze** [comment]
This appears to be fixed on the latest version: https://codesandbox.io/s/nivoline-chart-bottom-tick-values-forked-jfdu2?file=/src/index.js
