### ISSUE TITLE
Scatterplot TimeScale min/max not working when using non-native dates

### ISSUE THREAD

**Issue by rgiese** [plouc/nivo#675]
I'd expect the scatter plot's timescale to honor the `min`/`max` parameters when I'm using a non-`native` date format. It looks like it's just a typo in the code:

```
    let minValue = min
    if (min === 'auto') {
        minValue = values.min
    } else if (format !== 'native') {
        minValue = normalize(values.min)
    }
```

I suspect that should be:

```
    let minValue = min
    if (min === 'auto') {
        minValue = values.min
    } else if (format !== 'native') {
        minValue = normalize(min) // <---
    }
```

Same for `max`.

Also, while we're at it, the properties `min`, `max`, and `useUTC` are missing from the TypeScript definition for this.

**Comment by chandru89new** [comment]
Running into this same issue when trying to set a min value for a time-based ScatterPlot. @rgiese did you find any workaround for this?

**Comment by rgiese** [comment]
@chandru89new I did not, I just left it unset since that was close enough for what I was trying to do. If it matters more to you, I suspect this should be an easy PR to get through.
