### ISSUE TITLE
Accessing legends data from custom icons

### ISSUE THREAD

**Issue by andresmechali** [plouc/nivo#679]
**Is your feature request related to a problem? Please describe.**
I want to be able to toggle data for a bar chart by clicking on the legend text. For this, my approach is to add an onClick function to the legends object, as well as a symbolShape. The onClick part works fine, as I have access to the ID of the element I am clicking. However, I would like to render a filled icon when selected, and an empty icon when not. Unfortunately, the props used for the symbolShape component do not include this ID. It only includes x, y, size, fill, borderWidth and borderColor.

**Describe the solution you'd like**
I would like to be able to access more data from the symbolShape object. Particularly, the ID or the text label.

**Comment by i2xzy** [comment]
I agree with the need for this update. Currently, I've been able to circumvent this by mapping the fill colour to the icon I want
Example:
```js
const icons = {
  '#1877F2': IconFacebook,
  '#EF0176': IconInstagram,
  '#1ED760': IconSpotify,
  '#1DA1F2': IconTwitter,
  '#FF0000': IconYoutube,
  '#FF7700': IconSoundcloud,
};

const CustomSymbolShape = ({ x, y, size, fill }) => {
  const SVG = icons[fill];
  return (
    <g x={x} y={y}
>
      <circle fill={fill} cx={size / 2} cy={size / 2} r={size / 2} />
      <SVG color="#fff" width={16} height={16} x={4} y={4} />
    </g>
  );
};
```
![Screenshot 2019-09-11 at 13 45 30](https://user-images.githubusercontent.com/11375079/64698258-75ec8e00-d49a-11e9-9f4f-4323f303625e.png)

**Comment by andresmechali** [comment]
I sent a one-liner pull request to add the ID to the symbolShape function (https://github.com/plouc/nivo/pull/687).
I would appreciate if anyone could review it.

**Comment by plouc** [comment]
The id property has been added in https://github.com/plouc/nivo/pull/687, thanks to @andresmechali.
