### ISSUE TITLE
Missing tooltip in ResponsiveHeatMap Typescript definition

### ISSUE THREAD

**Issue by Fgerthoffert** [plouc/nivo#682]
**Describe/explain the bug**
Hi, when using ResponsiveHeatMap with typescript, I'm getting the following error:
```
Property 'tooltip' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ResponsiveHeatMap> & Readonly<HeatMapSvgProps> & Readonly<{ children?: ReactNode; }>
```

It seems the tooltip definition is missing from https://github.com/plouc/nivo/blob/master/packages/heatmap/index.d.ts

**To Reproduce**

Code Sandbox is available here: https://codesandbox.io/s/naughty-lederberg-tgmxr?fontsize=14

**Expected behavior**
No Typescript error

**Screenshots**
<img width="1355" alt="Capture d’écran, le 2019-09-08 à 19 49 10" src="https://user-images.githubusercontent.com/5667028/64496329-d8167a80-d271-11e9-87a8-b2b1b2f8f76e.png">

Thanks for these great dataviz components :)

Relates to: #197

**Comment by lawrencecrane** [comment]
Run into this problem today, seems that `HeatMapCommonProps` in `nivo/packages/heatmap/index.d.ts` is missing prop: `tooltip: (node: NodeData) => React.ReactNode`?
