### ISSUE TITLE
setting xScale type to linear breaks the UI

### ISSUE THREAD

**Issue by Julio-Assis** [plouc/nivo#686]
**Describe/explain the bug**
On the demo link of the framework https://nivo.rocks/line/ by changing the xScale property type to linear an error is thrown and this error breaks the UI.

**To Reproduce**

1. Go to 'https://nivo.rocks/line/'
2. Click on 'xScale'
3. On the type tab that appears, select linear 
4. See error on console "No Delaunay triangulation exists for this input"

**Expected behavior**
I think in the case of the demo, probably it doesn't make a lot of sense to set the xScale to linear given the type of the labels on the xAxis which are categories. In this case I would expect the UI to doesn't display this option or at least fail gracefully when such an invalid option is provided.  

**Screenshots**

![Screenshot from 2019-09-17 13-21-42](https://user-images.githubusercontent.com/20711458/65037496-23a1e600-d94e-11e9-8a9b-80b9961157d0.png)

![Screenshot from 2019-09-17 13-14-19](https://user-images.githubusercontent.com/20711458/65037034-1e906700-d94d-11e9-9f1e-790eda741217.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser firefox

**Comment by plouc** [comment]
The scale type was read-only before, it's a regression with the dynamic settings system. Thank you for reporting the issue.
