### ISSUE TITLE
Bug: Tooltip does not update for SwarmPlot

### ISSUE THREAD

**Issue by schlesingermatthias** [plouc/nivo#688]
Hi, 

if a dynamic tooltip is passed to the SwarmPlot component, the tooltip is not updated. It does work for other components (e.g. Bar)

See the following demo on codesandbox: https://codesandbox.io/s/nivo-basic-demo-mcf9u

When the "Toggle Tooltip" Button is clicked, the bar chart displays "2nd Tooltip" but the SwarmPlot keeps displaying the tooltip that was initially passed to the component (saying "Tooltip") so the component did not update.

Thank you. Let me know if I can help fixing the bug.

**Comment by nclar015** [comment]
I am having this same issue in regards to rendering a custom tooltip. I use various other charts such as the bar charts and it works just fine. 

For the swarmplot chart specifically I am not able to access the data object to be passed to the tooltip. (i.e. ({data}) => (data.id)) This will result in data is undefined.

**Comment by TheTaz25** [comment]
Hi there,

I had the same issues @schlesingermatthias and @nclar015 and found some workarounds (as long as there are no updates regarding this issue):

1. On the matter of the tooltips not updating:
The Swarmplot itself seems to be wrapped inside a `useMemo` hook which blocks updates on the chart. Wrap your swarmplot in another `useMemo` hook to force rerending like so: 
```
return (
  {useMemo(() => {
    <Swarmplot
      data={data}
      groups={groups}
      {...props}
    />
  }, [data, groups]);
);
```
Just make sure that all your dependencies affecting the plot are passed in the dependecy-array of useMemo.

2. On the matter of the custom-tooltip-data:
The data passed to the custom tooltip function wraps the data inside a node element:
`({ node }) => (node.data.id));` should do the trick.  

Even though I am quite late, I hope I could help you or others encountering those problems :)
