### ISSUE TITLE
Feature: Swiping Line Chart (ECG Signal)

### ISSUE THREAD

**Issue by juancols** [plouc/nivo#692]
I've been playing with the [real time line](https://nivo.rocks/storybook/?path=/story/line--real-time-chart) recipe for plotting a random ECG signal and this is what I got:
![ECG (nivo)](https://user-images.githubusercontent.com/7674043/65608988-56338a80-dfaf-11e9-8290-8e5cc1b178ec.gif)

I was wondering if there is a way for fixing the X-axis and plotting the values from left to right in a loop. Ideally something like this:

![ECG goal](https://user-images.githubusercontent.com/7674043/65609127-909d2780-dfaf-11e9-938e-26274a080611.gif)

I'm loving this library by the way! ❤

**Comment by jaymendez** [comment]
@juancols  Did they update this on 2020?
