### ISSUE TITLE
Grouped bar plots where results display overlapped

### ISSUE THREAD

**Issue by jdelos** [plouc/nivo#694]
I cannot make in a grouped bar plot, the grouped bars share the same area. I want to present a bar plot where results look like being stacked, however, the given values are absolute. 

**Describe the solution you'd like**
Enable a grouped plot where the clustered bars are overlapped with each other.

**Describe alternatives you've considered**
The current workaround is to use a bar stack plot and recompute all values to it's stacked correspondence. This solution is not optimal because the hoovering then does not give the right data.

**Comment by theDanielJLewis** [comment]
Nearly 3 years later, was there any solution to this?

Here's an example of what I'm trying work with:

```js
const data = [
  { label: 'plants': trees: 10, oaks: 5}
]
```

In this data example, all oaks are trees, but not all trees are oaks. So I want the oaks portion of the chart to be in front and overlap the trees portion, taking up half the space, while the trees portion stretches across the whole thing.

I've done this in the past with Chart.js, but I'd like to move my charts to Nivo with my new project.

**Comment by plouc** [comment]
@theDanielJLewis, there's no support for this, what nivo expects is more like:

```
const data = [
  { label: 'tress': other_trees: 5, oaks: 5}
]
```

I understand that's not what you're looking for, but that's how it can be done, there's no support for sub-categories within a group.

**Comment by theDanielJLewis** [comment]
@plouc, and you're saying that if I format the data like that, "stacked" would then layer the values over each other instead of essentially adding the values onto the ends?

**Comment by plouc** [comment]
@theDanielJLewis, no 😅, what I mean is that such way of expressing the values would be compliant with the way the chart works. Each group only has a virtual value, the sum of all data points belonging to it.

**Comment by theDanielJLewis** [comment]
So making an overlapping chart like this is not possible with Nivo (at least right now)?

<img width="653" alt="image" src="https://github.com/plouc/nivo/assets/154936/e14f05b9-1d6f-4cdb-a8a4-2333eafd2f74">

Note that in this chart, there are always more ratings than reviews, so the ratings bar is layered behind the reviews bar and then extends farther.

**Comment by plouc** [comment]
No, it is not possible, if you change the data format, having reviews: 392 and ratings: 44, the tooltip would not show what you want, although the tooltip could probably be customized to achieve that.

**Comment by theDanielJLewis** [comment]
Okay. Thanks for the answers then!
