### ISSUE TITLE
Question: is it possible to render less hoverable points than data points?

### ISSUE THREAD

**Issue by matthewtgilbride** [plouc/nivo#696]
**Is your feature request related to a problem? Please describe.**
I would like to render a line chart with a higher density of data than hoverable points on the line.  For instance, a line with hourly data over the last 7 days, but with only a single, hoverable "point" per day.  

If I only provide one data point per day, trends throughout the day are lost.  If I provide hourly data, I get hoverable points that are too close together and impossible to discern from one another.

**Describe the solution you'd like**
Some prop in the spirit of the "tickValues" prop we have for axes, where we can specify a number of hoverable points, or a function to determine whether or not to render the point.

Is this already possible somehow?

**Describe alternatives you've considered**
The only alternative I've considered is rendering multiple series.  One would would have daily data, an invisible line, and visible points.  Meanwhile, the other would have hourly data, no points, and a visible line.  This feels a bit awkward to me...especially if we want to render multiple lines...

**Additional context**
More of a question than a feature request.  Thanks for a great library!

**Comment by plouc** [comment]
@matthewtgilbride, it's not supported out of the box, however you can probably do this using a custom layer, points are implemented in a [layer](https://github.com/plouc/nivo/blob/master/packages/line/src/Line.js#L216), so you can disable the original one and replace it with a custom implementation, you can see an example of this [here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L891). This might require a bit of work but you can for example try to filter the points in your custom layer component and reuse the `Points` component to render them.
