### ISSUE TITLE
How to export BarCanvas or other chart to base64 image?

### ISSUE THREAD

**Issue by arwanfiles** [plouc/nivo#698]
Hi, can I generate image and convert it to base64 from nivo chart?

I want to using it for viewing a chart on pdf document.

Regards.

**Comment by plouc** [comment]
This is not part of nivo, but you have several way to do so, you can for example use `react-dom/server` to generate an SVG file, or you can use puppeteer to generate the image (that's [what I do for the READMEs](https://github.com/plouc/nivo/blob/master/scripts/capture.js)), you might also find some library that are able to do this purely on the client side.
