### ISSUE TITLE
No exported ResponsiveCalendarCanvas 

### ISSUE THREAD

**Issue by SourceCipher** [plouc/nivo#699]
**Describe/explain the bug**
Cant import ResponsiveCalendarCanvas as shown in https://nivo.rocks/calendar/canvas/ 

**To Reproduce**
Try importing ResponsiveCalendarCanvas  and you will get  `Module '"@nivo/calendar"' has no exported member 'CalendarCanvas'.`

I have checked the nivo-calendar.cjs.js and it seems like they are exporting them all. I can import only `ResponsiveCalendar` or `Calendar`.

**Comment by SourceCipher** [comment]
Ok found what was the issue. Refer to this pull request #700

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/700
