### ISSUE TITLE
Choropleth features prop not documented

### ISSUE THREAD

**Issue by brownieboy** [plouc/nivo#702]
**Is your feature request related to a problem? Please describe.**
In the [main documentation for the Choropleth map ](https://nivo.rocks/choropleth/) the `features` prop does not appear to be documented.  This is odd, since it appears to be crucial to having the map actually display any countries.

**Describe the solution you'd like**
Document the `features` prop.  There is a mention of it (kind of) in the introductory paragraphs about the Choropleth, i.e. "you must pass an array of features which determine the geometries to render on the map".  But it doesn't say that you use the `features` prop for this, and `features` is _not_ in the list of props that are documented in the list below that.

Also, the sample code under the **code** tab on documentation page is misleading. It shows the `features` prop being passed an empty array, which is not going to display anything, as I understand it.  When I checked the _actual_ code in the Dev Tools, I saw a the Choropleth component _is_ being passed data from a countries config json file, and not an empty array.

**Describe alternatives you've considered**
I found a working example here https://codesandbox.io/s/nivogeo-demo-mkl9u, which shows the `features` prop being passed the countries data.

**Additional Context**
Some examples of the Geo maps on [the Nivo Storybook](https://nivo.rocks/storybook) would be nice to have too.  There are none there that I could find.

**Comment by harrisonxia** [comment]
Thanks for pointing this point. Just ran into this issue.

**Comment by plouc** [comment]
I've updated the documentation, the feature file is not included in the generated code, but I've added a warning and a link to the feature file used for the example.
