### ISSUE TITLE
Draw a bar chart with single bar average markers?

### ISSUE THREAD

**Issue by tomeraz** [plouc/nivo#705]
Hi,
Is there a way to use Nivo bar chart to draw single bar average markers as shown in this image?
![IMG_20191015_063943](https://user-images.githubusercontent.com/7067145/66798563-15c48e00-ef17-11e9-907f-378470599bf6.jpg)

**Comment by plouc** [comment]
There's no native support for this, but you can achieve this by using an extra layer, Bar doesn't have an example of it but you can have a look at this: https://nivo.rocks/storybook/?path=/story/line--custom-layers to have an idea on how to do so.
