### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by amickael** [plouc/nivo#723]
Is Nivo still being maintained? The last commit was about 4 months ago and it doesn’t look like new issues are being worked on.

**Comment by plouc** [comment]
Hi @amickael, unfortunately I didn't had much time to spare on the project lately for personal reasons. But yes, it is still maintained :) will try to have a look at the PRs/issues over the weekend.

**Comment by amickael** [comment]
Thank you @plouc, this library is very useful and happy to hear it's still being looked after.
