### ISSUE TITLE
onMouseEnter/Leave functions are not exported within TypeScript-Type definitions

### ISSUE THREAD

**Issue by kumarunster** [plouc/nivo#724]
in current Bar/Pie versions 
  "@nivo/bar": "^0.59.2",
  "@nivo/pie": "^0.59.1",

TypeScript property definitions for onMouseEnter/Leave are missing, hence instantiating nivo charts with onMouseEnter/Leave functions is not possible or not intuitive.

my current workaround is

```typescript

const chartProps: BarSvgProps = {
    //init with regular props
}

 //expand properties with mouse enter/leave handler
 Object.assign(chartProps, {
    onMouseEnter: (data: BarExtendedDatum, event: React.MouseEvent<HTMLCanvasElement>) => {
        event.currentTarget.style.cursor = 'pointer'
        event.currentTarget.style.strokeWidth = '2'
        event.currentTarget.style.opacity = '0.8'
    },
    onMouseLeave: (data: BarExtendedDatum, event: React.MouseEvent<HTMLCanvasElement>) => {
        event.currentTarget.style.cursor = 'auto'
        event.currentTarget.style.strokeWidth = '' + borderWidth
        event.currentTarget.style.opacity = '1'
    }
})

return new ResponsiveBar(chartProps)

```

More context:
this functions were added with https://github.com/plouc/nivo/issues/295 and PR https://github.com/plouc/nivo/pull/280

do you want PR for this issue?

**Comment by kumarunster** [comment]
any comment on this?

**Comment by kumarunster** [comment]
bump

**Comment by wyze** [comment]
> do you want PR for this issue?

Definitely send a PR to add these!
