### ISSUE TITLE
@nivo/sankey - React Hooks / React Router

### ISSUE THREAD

**Issue by awatson1978** [plouc/nivo#726]
**Describe/explain the bug**
Hello.  Receiving the following error regarding React Hooks.  
`Invariant Violation: Hooks can only be called inside the body of a function component.`

![Screen Shot 2019-10-23 at 2 35 57 PM](https://user-images.githubusercontent.com/675910/67427930-b9124480-f5a2-11e9-89c6-6a33e42899a7.png)

**To Reproduce**
Just using the provided example from the documentation.  Using it within a Meteor.js build pipeline for Node/Javascript, and with React 16.8.4.  

```jsx
const MyResponsiveSankey = ({data}) => (
  <ResponsiveSankey
    data={data}
    margin={{ top: 40, right: 40, bottom: 40, left: 40 }}
    align="justify"
    colors={{ scheme: 'category10' }}
    nodeOpacity={1}
    nodeThickness={18}
    nodeInnerPadding={3}
    nodeSpacing={24}
    nodeBorderWidth={0}
    nodeBorderColor={{ from: 'color', modifiers: [ [ 'darker', 0.8 ] ] }}
    linkOpacity={0.5}
    linkHoverOthersOpacity={0.1}
    enableLinkGradient={true}
    labelPosition="outside"
    labelOrientation="vertical"
    labelPadding={16}
    labelTextColor={{ from: 'color', modifiers: [ [ 'darker', 1 ] ] }}    
  />
)


let sankeyData = {
  "nodes": [
    {
      "id": "John",
      "color": "hsl(102, 70%, 50%)"
    },
    {
      "id": "Raoul",
      "color": "hsl(58, 70%, 50%)"
    }
   ...etc
}
export class WorkflowPage extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div id='indexPage'>
        <FullPageCanvas>
          <GlassCard height='auto' >
            <CardTitle 
              title="Workflow Analysis"
              titleStyle={{fontSize: '240%'}}
              subtitleStyle={{fontSize: '180%'}}
              />
            <CardText style={{fontSize: '180%', height: '400px'}}>
              <MyResponsiveSankey data={sankeyData} style={{fontSize: '180%', height: '400px'}} />                
            </CardText>
          </GlassCard>
        </FullPageCanvas>
      </div>
    );
  }
}

```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest

**Comment by awatson1978** [comment]
Update:  More debugging, and this is clearly related to using React Router v4.  Apparently React Router is introducing a class based container somewhere along the render tree, which is throwing the Hook error.  

Does anybody have a code sample of using Nivo with React Router?

**Comment by plouc** [comment]
@awatson1978, can you please reproduce this issue on codesandbox? I was able to use nivo in several contexts, and before moving to gatsby, [the nivo website was using React router](https://github.com/plouc/nivo/commit/7ed59e94d6248e761dfcd2ba167b28fab9699ddb#diff-07f3a4647460e74f9514d8def137963aL47). I'm not sure it's an issue with nivo.

**Comment by Branislavjvc** [comment]
https://github.com/gaearon/react-hot-loader/issues/1088

Related, figured it might shine some light on the topic if you're using react-hot-loader.

**Comment by awatson1978** [comment]
Hi.  Problem was on my side.  Had to do an entire rebuild of my application.  Blah.  Thanks for the help.
