### ISSUE TITLE
Add ability to set color explicitly for a key in radar chart.

### ISSUE THREAD

**Issue by nurbek-ab** [plouc/nivo#727]
**Is your feature request related to a problem? Please describe.**
If keys prop changes dynamically the chart may asign another color to the same key as it just pulls colors one by one from colors prop.

**Describe the solution you'd like**
I'd like to be able to specify a color explicitly in data. So each key has it's own assigned color that doesn't change when keys prop changes.

**Comment by plouc** [comment]
You can use a function for the `colors` property that will return the color associated to a specific key.

**Comment by richAtreides** [comment]
Can you provide an actual example I'm not sure what you mean?

**Comment by garrrikkotua** [comment]
Hi, can you please provide the example for the function? It is not clear, how to use it. Thanks.

**Comment by wyze** [comment]
Here you go @richAtreides and @garrrikkotua : https://codesandbox.io/s/patient-butterfly-dq53o

**Comment by nurbek-ab** [comment]
> Here you go @richAtreides and @garrrikkotua : https://codesandbox.io/s/patient-butterfly-dq53o

Thanks, it works for me. Though in my case I had to take 'id' property for key value, not 'key' property. So my function looks like this:
```
colors={({ id }) => {
  return colorsByKey[id]
}}
```
