### ISSUE TITLE
BorderColor does not exist on BarSvgProps -> Bar Chart Example

### ISSUE THREAD

**Issue by chawk** [plouc/nivo#730]
Property 'borderColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ResponsiveBar> & Readonly<BarSvgProps> & Readonly<{ children?: ReactNode; }>'.

**Comment by plouc** [comment]
This has been fixed by https://github.com/plouc/nivo/pull/704 and will be available in the next release.
