### ISSUE TITLE
Can't use Line with Typescript

### ISSUE THREAD

**Issue by lucypoly** [plouc/nivo#736]
![image](https://user-images.githubusercontent.com/17836316/67849093-9508b300-fb0e-11e9-9227-42477241fb4b.png)

`data` type is ok!

**Comment by wyze** [comment]
Can you post a CodeSandbox with a reproduction? Hard to go off just a screenshot.

**Comment by ByronBecker** [comment]
I can say firsthand the @nivo/line package has excellent typings (just used them) - the typescript error you are receiving is returned when the object you are passing is not actually typed as an array

**Comment by lucypoly** [comment]
Thank you for the answer!

пт, 1 нояб. 2019 г., 02:34 ByronBecker <notifications@github.com>:
