### ISSUE TITLE
Option for custom data accessors

### ISSUE THREAD

**Issue by silverwind** [plouc/nivo#739]
**Is your feature request related to a problem? Please describe.**
nivo currently expects `data` to be in a certain format, for example `{x, y}` for line charts. Sometimes, data is not directly available in that format and one would need to perform expensive transformations that could be avoided when nivo could be told about how it should access the data.

**Describe the solution you'd like**
A new option `dataAccessors` taking key/value pairs. For example for data in format `{time, value}`:

```` js
dataAccessors: {
  x: "time",
  y: "value",
}
````

**Describe alternatives you've considered**
The only other option is to transform data which can be a expensive operation that I'd like to avoid.

**Comment by ABhat00** [comment]
bump

**Comment by michaelg9** [comment]
this feature would be useful for me as well; I'm dealing with long data and rendering overhead is already a bit high, so I'm trying to avoid data conversion if possible

**Comment by matobiely** [comment]
@wyze can you please take a look on this? It is closed, but i think this could by very helpful. Thanks

**Comment by wyze** [comment]
Yeah we can probably do something similar to like we have in other charts.

**Comment by wyze** [comment]
Can someone post a small data sample of their input that they would like to use an API like this for?

**Comment by matobiely** [comment]
`[{
id:'Quote', data: [{timeSerie: '2021-01-12', value:22},{timeSerie: '2021-01-13', value:24},{timeSerie: '2021-01-14', value:25}]
}]`

@wyze you mean something like this?

**Comment by wyze** [comment]
Yes, exactly. Thank you.

**Comment by matobiely** [comment]
bump

**Comment by MA-MacDonald** [comment]
It would be very helpful to be able to specify a dataKey so I don't have to reformat all my data to {x,y} before charting.

Something similar to how [recharts](https://recharts.org/en-US/examples/SimpleLineChart) does it.

**Comment by eddielee394** [comment]
bump

**Comment by sergeyloysha** [comment]
dump

**Comment by ImLunaHey** [comment]
can this please be re-opened?
