### ISSUE TITLE
Y axis labels overlap with one another when the area of the chart container reduces

### ISSUE THREAD

**Issue by SenelithPerera** [plouc/nivo#742]
![Screenshot from 2019-11-08 09-48-09](https://user-images.githubusercontent.com/47237886/68449406-f4507c80-020c-11ea-8011-edb070d08fe6.png)

The Y axis labels gets overlapped with each other when the chart container's area gets small.
Is there a way to set a padding bottom for these labels or shouldn't the chart be able to reduce font-size and adjust the labels according to it's parent container ? Or have i missed something from the docs ?

**Comment by plouc** [comment]
@SenelithPerera, it's not part of the lib, but you can easily wrap the component with a responsive container and adjust the chart props accordingly.
