### ISSUE TITLE
How to format legend labels within a Calendar?

### ISSUE THREAD

**Issue by taschetto** [plouc/nivo#744]
Hi! I've searched the docs, storybook and this repo to find a way to do it but I was not successful.

I need to format legend labels within a Calendar. Currently, my raw values range from 0 to ~70,000.

![image](https://user-images.githubusercontent.com/5279182/68676095-fcbff480-0537-11ea-953d-caaeec45eda5.png)

I'd like to format these values as follows:

![image](https://user-images.githubusercontent.com/5279182/68676205-401a6300-0538-11ea-9dc2-8206ea00f783.png)

Is there anyway to do it?

I've tried to pass a function inside the legend object, but it didn't work:

```javascript
    // ...
    legends: [
      {
        // ...
        legendFormat: ({ value }) => myFormatter(value),
        // ...
      },
    ],
```

Thanks! :-)

**Comment by oscargws** [comment]
Bump, any information on this? Trying to achieve the same thing

**Comment by rovaniemi** [comment]
I also needed this feature, but the library does not support it yet. However, this feature can be used with a little workaround, but **we should do a PR** if we want to use it the proper way.

#### Workaround

**@nivo/calendar** uses colorScale function when it does create legends. 

```js
const legendData = colorScale.ticks(legend.itemCount).map(value => ({
  id: value,
  label: value,
  color: colorScale(value),
}))
```

We can pass new colorScale function on **@nivo/calendar** props
```js
import { scaleQuantize } from 'd3-scale'

const computeDomain = (data, minSpec, maxSpec) => {
  const allValues = data.map(d => d.value)
  const minValue = minSpec === 'auto' ? Math.min(...allValues) : minSpec
  const maxValue = maxSpec === 'auto' ? Math.max(...allValues) : maxSpec
  return [minValue, maxValue]
}

const createColorScale = (data, minValue, maxValue, colors) => {
  const domain = computeDomain(data, minValue, maxValue)
  const defaultColorScale = scaleQuantize()
      .domain(domain)
      .range(colors)
  const colorScale = value => {
      const number = prettyIntegerToNumber(value) // Formatted number back to number
      return defaultColorScale(number)
  }
  colorScale.ticks = count => {
     return defaultColorScale.ticks(count).map(e => prettyInteger(e)) // Format number
  }
  return colorScale
}
```

**Comment by Genarito** [comment]
Another workaround is to make your custom Legend as proposed [here](https://github.com/plouc/nivo/issues/791#issuecomment-587051981).

There's a [PR](https://github.com/plouc/nivo/pull/919) which fixes this issue (I hope). But it's still not reviewed
