### ISSUE TITLE
Website: Markdown description of the 'labelFormat' property is broken on the Bar page.

### ISSUE THREAD

**Issue by Addono** [plouc/nivo#747]
**Describe/explain the bug**
Markdown description of the 'labelFormat' property is broken on the [Bar](https://nivo.rocks/bar) page.

**To Reproduce**
1. Go to '[https://nivo.rocks/bar](https://nivo.rocks/bar)'
2. Scroll down to 'labelFormat'
3. Expand 'labelFormat'

**Expected behavior**
Same working markdown on the [Bubble](https://nivo.rocks/bubble) page.
![working](https://user-images.githubusercontent.com/15435678/68752531-25192300-060c-11ea-9ca6-3df2a4c72305.png)

**Screenshots**
Broken markdown on the [Bar](https://nivo.rocks/bar) page.
![broken](https://user-images.githubusercontent.com/15435678/68752556-319d7b80-060c-11ea-88d9-70e37e7d0089.png)

**Comment by plouc** [comment]
Fixed by https://github.com/Addono/nivo/commit/2b674212e73c8ee16937a99b42218ebb00a457eb
