### ISSUE TITLE
Misaligned ticks for week-based time scale

### ISSUE THREAD

**Issue by schlesingermatthias** [plouc/nivo#749]
Hi, 

I'm trying to plot weeks in a year to a line chart (see [this codesandbox](https://codesandbox.io/s/vigorous-herschel-4k3nd))
My input data point looks like: 
```
[
  {
     x: "2019-W33",
     y: 618940
  },...
]
```

The xAxis: 
```
xScale={{
  type: "time",
  format: "%Y-W%V"
}}
axisBottom={{
  format: "%Y-W%V",
  tickValues: "every week"
}}
```

But the axis ticks are not aligned with the line's points and the grid columns are not equally spaced. I'm filling this as a bug but please let me know if I'm doing something wrong...

Thank you

**Comment by meltingice** [comment]
I have this same issue but with daily ticks. I have a feeling it affects any chart with a time-based x-axis.

**Comment by wyze** [comment]
I set `useUTC: false` on the `xScale` property.

**Comment by meltingice** [comment]
@wyze you are a lifesaver, thank you! I had no idea that option even existed.

**Comment by swiharta** [comment]
Please note that `useUTC: false` seems to address a different issue and does not seem to apply to the issue of the original poster. 

I have the same issue as the original poster with misaligned ticks on a week-based time scale. For some reason, the ticks that are automatically generated get offset by a seemingly random (to me) amount of days relative to the dates in the actual data.

Please see the following example:
![offset data points and ticks](https://user-images.githubusercontent.com/323712/80920917-dc336300-8d40-11ea-9d87-16cb03a1e9de.png)
https://codesandbox.io/s/pedantic-tereshkova-69oig?file=/src/index.js

This can be "fixed" by a manual process, by explicitly providing the tickValues as an array from the data set. Also note that you have to do the same for gridXValues, or else the grid lines remain misaligned:
![aligned data points and ticks](https://user-images.githubusercontent.com/323712/80920906-ce7ddd80-8d40-11ea-8b94-ae123a07338d.png)
https://codesandbox.io/s/ecstatic-drake-nfvgz?file=/src/index.js

This also occurs when you have tickValues set to multiple months, for example 3 months. Where my data has the months already grouped into 3 month chunks, that gets ignored and different months are used for the ticks.  For example:
![image](https://user-images.githubusercontent.com/323712/80920896-c45bdf00-8d40-11ea-89f1-f31e1e083894.png)
https://codesandbox.io/s/zealous-mahavira-1reo8?file=/src/index.js

It would be great if the tick marks would reflect the data points that are being passed in, as in my "fixed" demo above.

**Comment by swiharta** [comment]
If it helps anyone, I currently addressed my issue with a function that produces the tick values explicitly. In my case, `point.x` values are Date objects, which are specific to a given time interval. See a CodeSandbox above for an example. `start` and `end` are the min and max dates included in the chart data, `intervalType` is 'week', 'month, 'day, or 'year', and `intervalNum` is the number of intervals (ex. 3 months) per data point.

``` js
getIntervalTicks = (data, maxTicks=12) => {
  if (!(data && data.length)) {
    console.log('not able to explicitly generate ticks')
      return 8 // fallback to automatically generated ticks of this number
  }
  const {start, end, intervalNum, intervalType} = this.state
  const intervalCount = Math.floor(moment(end).diff(start, intervalType) / intervalNum)
  return data[0].data.reduce((accum, point, index) => {
      const divisor = Math.ceil(intervalCount / maxTicks)
      if (index % divisor === 0)
          accum.push(point.x)
      return accum
  }, [])
}
```
Then I call this function from the chart parameters as below:
``` js
axisBottom: {
  // blah, blah, blah...
  tickValues: this.getIntervalTicks(data),
},
gridXValues: this.getIntervalTicks(data),
```
This results in limiting the number of ticks to the `maxTicks` value. So if you have `maxTicks=12`, and 12 months of data you get 12 ticks, but if you have 13 data points, you'll drop your number of ticks down to 6, then with 14 data points, it goes to 7 ticks, etc...

**Comment by DeoluA** [comment]
This comment from @swiharta helped a lot. The only change I made was letting `start` and `end` be data-dependent, viz:
```
const start = data[0].data[0].x;
const end = data[0].data[(data[0].data.length - 1)].x;
```
Maybe examples like these can be included in the documentation somewhere for newbies? (and if it already is, maybe the location can be more prominent?)

> If it helps anyone, I currently addressed my issue with a function that produces the tick values explicitly. In my case, `point.x` values are Date objects, which are specific to a given time interval. See a CodeSandbox above for an example. `start` and `end` are the min and max dates included in the chart data, `intervalType` is 'week', 'month, 'day, or 'year', and `intervalNum` is the number of intervals (ex. 3 months) per data point.
> 
> ```js
> getIntervalTicks = (data, maxTicks=12) => {
>   if (!(data && data.length)) {
>     console.log('not able to explicitly generate ticks')
>       return 8 // fallback to automatically generated ticks of this number
>   }
>   const {start, end, intervalNum, intervalType} = this.state
>   const intervalCount = Math.floor(moment(end).diff(start, intervalType) / intervalNum)
>   return data[0].data.reduce((accum, point, index) => {
>       const divisor = Math.ceil(intervalCount / maxTicks)
>       if (index % divisor === 0)
>           accum.push(point.x)
>       return accum
>   }, [])
> }
> ```
> 
> Then I call this function from the chart parameters as below:
> 
> ```js
> axisBottom: {
>   // blah, blah, blah...
>   tickValues: this.getIntervalTicks(data),
> },
> gridXValues: this.getIntervalTicks(data),
> ```
> 
> This results in limiting the number of ticks to the `maxTicks` value. So if you have `maxTicks=12`, and 12 months of data you get 12 ticks, but if you have 13 data points, you'll drop your number of ticks down to 6, then with 14 data points, it goes to 7 ticks, etc...
