### ISSUE TITLE
Multi-colored line chart

### ISSUE THREAD

**Issue by ui-ninja** [plouc/nivo#750]
First, thanks for making this amazing chart library.

I had question in mind that does @nivo/line supports multi-color in single line.

something like 
![multi-colored-line-chart](https://user-images.githubusercontent.com/12812377/68783669-a3d98480-063b-11ea-8cac-703b508de2b7.png)

**Comment by DavidTawil** [comment]
any update on this?
@ui-ninja did you manage to figure it out?

**Comment by nilscam** [comment]
I'm interested to know as well if you found a solution.

**Comment by MTxx87** [comment]
I am also interested in this. 
Anybody figured this out?

**Comment by 3nt3** [comment]
@MTxx87 you can generate multiple series like in [this example](https://nivo.rocks/storybook/?path=/story/line--highlighting-negative-values)
