### ISSUE TITLE
Scatterplot and Bar behave differently with custom tooltips

### ISSUE THREAD

**Issue by mjsarfatti** [plouc/nivo#754]
**Describe/explain the bug**
`Scatterplot` and `Bar` behave differently with custom tooltips. While `Bar` wraps whatever the custom tooltip function returns in a themed `<BasicTooltip>`, `Scatterplot` does not. It seems to me that `Scatterplot` has changed behavior recently.

**To Reproduce**
[![Edit scatterplot vs. bar custom tooltip](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nivoscatterplot-extra-layer-7u6qg?fontsize=14&hidenavigation=1&theme=dark)

_Please see a stripped down example in the CodeSandbox above_

**Expected behavior**
The behavior for custom tooltips should be consistent in all components.

**Screenshots**

**Desktop (please complete the following information):**
_This is not device dependent_

**Smartphone (please complete the following information):**
_This is not device dependent_

**Comment by plouc** [comment]
Some packages evolved more quickly that others, it's a way to ship improvements asap, but at the cost of consistency between components.

**Comment by plouc** [comment]
Closing this in favor of https://github.com/plouc/nivo/issues/745
