### ISSUE TITLE
Change the radar labels colors

### ISSUE THREAD

**Issue by halberio** [plouc/nivo#755]
Is there any option for labels color in radar chart?
Thank you.

**Comment by halberio** [comment]
I used the gridLabel function to replace labels with SVG but the its not centered ! any help?

**Comment by plouc** [comment]
@halberio I don't really understand what you're trying to achieve, could you provide a running example of what you got and maybe a quick mockup?

**Comment by halberio** [comment]
Hello, 
We are a digital agency, we do Web/Mobile UX/UI design and development, 
We do social media content creation 
We are trying to get clients with a different mind set, 
We do things differently with a great look and feel and performance
Please feel free to contact our CEO if you need us : 
hamdi@halber.io <mailto:hamdi@halber.io> 


Bests

**Comment by plouc** [comment]
I’m closing this due to lack of feedback, please free to comment if you can provide more context
