### ISSUE TITLE
onMouseEnter and onMouseLeave don't work on @nivo/line

### ISSUE THREAD

**Issue by mjsarfatti** [plouc/nivo#756]
**Describe/explain the bug**
`onMouseEnter` and `onMouseLeave` don't work on @nivo/line.
`onMouseEnter` is fired only once as the mouse enters the chart, while `onMouseLeave` is never fired.

**To Reproduce**
Please see the CodeSandbox (events are logged in the console):

[![Edit @nivo / line mouseenter not working](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nivo-scatterplot-vs-bar-custom-tooltip-2nlbc?fontsize=14&hidenavigation=1&theme=dark)

**Steps to reproduce the behavior:**
1. Create a Line or ResponsiveLine chart
2. Assign a function to the `onMouseEnter` and/or `onMouseLeave` properties
3. Move the mouse over the chart, and from line to line, from point to point
4. `onMouseEnter` is fired only once as the mouse enters the chart, while `onMouseLeave` is never fired

**Expected behavior**
`onMouseEnter` is fired every time the cursor moves to a new point; `onMouseLeave` is fired every time the cursor leaves a point

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Firefox
 - Version 70

**Smartphone (please complete the following information):**
 _not checked_

**Comment by wyze** [comment]
This is resolved in the latest version.
