### ISSUE TITLE
Dark mode not working for AreaBump and ScatterPlot 

### ISSUE THREAD

**Issue by vianneyguesdon** [plouc/nivo#757]
On the website, we can't see the data when dark mode is on for AreaBump and ScatterPlot charts.

**To Reproduce**
You just need to activate the dark mode on the website.

1. Go to https://nivo.rocks/area-bump/
2. Click on the "dark mode" toggle
3. Error : can't see anything on the chart

![Capture d’écran de 2019-11-20 10-05-22](https://user-images.githubusercontent.com/47182193/69224871-92cdcd80-0b7d-11ea-9dc5-066ada1109a8.png)

I would expect the colors to change like for the other charts

I'm using Google Chrome v78.0.3904.97 (Build officiel) (64 bits)

**Comment by plouc** [comment]
This is because of the blend mode, the default demo is cooler with those, but need to be changed when switching to dark mode.
