### ISSUE TITLE
Nivo bar is missing renderTick type in latest release

### ISSUE THREAD

**Issue by dylancom** [plouc/nivo#775]
When installing @nivo/bar@0.59.2 the renderTick type is missing (and therefore I can't use the renderTick prop in TypeScript). I see it was added in a commit: https://github.com/plouc/nivo/commit/61fc20786b92eb1c96ba1c543f43aa91c57591c7#diff-54a2d592b2e950c23cc6e348a7ff1925 but there hasn't been a new version for a while.

**Comment by w4-alibek** [comment]
Is this issue resolved?

**Comment by dylancompanjen** [comment]
@w4-alibek this issue is still there. The last @nivo/bar tag dates from 4 months ago.

**Comment by codler** [comment]
This can be closed, It works in 0.61.1
