### ISSUE TITLE
Axis fontSize and textColor are not working for Bar v.0.59.2

### ISSUE THREAD

**Issue by igorbuts** [plouc/nivo#776]
Thank you for creating Nivo. It's really a powerful tool.

**Issue description:**
For `ResponsiveBar` v.0.59.2  Axis `fontSize` and `textColor` can not be set through theme object. It was working in previous versions. 

**To Reproduce:**
`v.0.59.2 - not working`: https://codesandbox.io/s/nivo-bar-axis-issue-0592-e3n53
`v.0.33.0 - was working`: https://codesandbox.io/s/nivo-bar-axis-label-size-v033-lr1r6

Same code provided in two sandboxes. Just different @nivo/bar versions.

P.S maybe it also regards some other style properties  - I didn't check.

**Comment by wyze** [comment]
Yes, the theme properties have chanced in between those versions. Here is an updated example working with the latest version: https://codesandbox.io/s/nivo-bar-axis-issue-0592-fkiqs

**Comment by igorbuts** [comment]
@wyze it is working, thanks
