### ISSUE TITLE
How to make nested donut chart?

### ISSUE THREAD

**Issue by mattoni** [plouc/nivo#777]
Forgive me if I missed this somewhere, but I didn't see anything in docs or on storybook.

I'm trying to accomplish something similar to the following:

![image](https://user-images.githubusercontent.com/5110855/69457322-aade5200-0d21-11ea-9e78-1ef51ec4c610.png)

Is there a way to achieve this in Nivo?

**Comment by wyze** [comment]
I don't think this is currently possible as a pie chart. Might be possible with a Sunburst, but not too sure on that.

**Comment by mattoni** [comment]
What I ended up doing to get around this was manually layering them using position:absolute and made the second chart just smaller. Sunburst isn't the kind of data I want, since the two circles are basically separate values.

**Comment by plouc** [comment]
@mattoni unless you're confortable with nivo internals to build your own chart (using the `usePie` hook), that's the best option, I agree it feel hackish though.
@wyze Sunburst is suited for hierarchical data, bot not for this use case if I understood it well.
