### ISSUE TITLE
Pie chart Placeholder when empty data

### ISSUE THREAD

**Issue by gponsu** [plouc/nivo#779]
I'm using a `ResponsivePie` component, it's amazing, but I don't know if it's possible to render an empty placeholder when the data value is still zero. Right now, the graph simply does not appear for this case.

Thank you very much!

**Comment by plouc** [comment]
Sorry but you cannot do this with the Pie component, if you want something to appear on the chart, it must have an associated value that can be displayed on the chart.

**Comment by jaeminche** [comment]
I gave the value a true like this: [{ id: null, label: '', value: true }], and it worked, it's showing an empty chart with some light-colored background.
