### ISSUE TITLE
How can i set grid Y step size?

### ISSUE THREAD

**Issue by Jav3k** [plouc/nivo#780]
Hello. I can't find information on how to set a grid Y step.
On screenshot below step has been automatically calculated to 0.2. I want to see integer numbers only (0, 1, 2, 3; or 0, 5, 10). I tried to use gridYValues and tickValues of axisLeft, but i can't know exactly my yValues every time. 

![image](https://user-images.githubusercontent.com/33694362/69701677-451e0b80-110f-11ea-86d6-401b4a6db9f9.png)

**Comment by plouc** [comment]
You can set `gridYValues` on the chart itself, not on the axis.

**Comment by strahius** [comment]
@plouc is there no other option? What if the values can reach to the thousands?
