### ISSUE TITLE
`x` property is undefined for ticks in @nivo/stream chart

### ISSUE THREAD

**Issue by ogroppo** [plouc/nivo#781]
When using `tickValues` option (e.g. tickValues = ['a', 'b', 'c']) in `Stream` or `ResponsiveStream` > `axisBottom` all the labels get rendered on the left because `x` is is undefined so the transform attribute is `translate(undefined, y)`.

Also in the `renderTick` function the argument is missing `x` property. e.g.
```
{
 format: undefined,
 lineX: 0,
 lineY: 5,
 opacity: 1,
 rotate: 0,
 ...
 value: 'a'
 x: undefined,
 y: 0,
}
```

Thank you.

**Comment by plouc** [comment]
Can you please reproduce this on codesandbox so we can see the data/configuration used?

**Comment by ogroppo** [comment]
There you go bud: https://codesandbox.io/embed/react-example-m1zry?fontsize=14&hidenavigation=1&theme=dark

**Comment by plouc** [comment]
Oh, forgot that the stream chart only supports numbers actually :/

**Comment by plouc** [comment]
I'd like to change the structure of the data to match the line component so it's easier to customize the scale type used on x axis.

**Comment by ogroppo** [comment]
That would be great! Especially if dates are involved string support is 100% needed.

**Comment by janvdvegt** [comment]
We would really like this as well, we want to use this component to show latency distribution over time

**Comment by nylki** [comment]
> I'd like to change the structure of the data to match the line component so it's easier to customize the scale type used on x axis.
@plouc That would be super useful! At the moment there is a grey area for stacked charts between `Line` and `Stream`. Either use a `Line` to have support for time-series. Or use `Stream` if you want pattern or non-overlapping transparent areas.
