### ISSUE TITLE
Responsive maps are not responsive

### ISSUE THREAD

**Issue by strahius** [plouc/nivo#783]
**Describe/explain the bug**
The map components (geo) do not seem to be responsive, even though they imply they are, in their name. This applies to all,  `ResponsiveGeoMap`, `ResponsiveGeoMapCanvas`, `ResponsiveChoropleth` and `ResponsiveChoroplethCanvas`.

There is a `projectionScale` property that scales the map, but the component is not automatically responsive.

**To Reproduce**
1. Go to https://nivo.rocks/choropleth/
2. Resize your browser
3. Notice that the map does not actually resize

**Expected behavior**
Map should scale when the container's size updates.

**Comment by plouc** [comment]
The container is responsive, but the way you want to scale the maps when it's resized is your responsibility though.

**Comment by ohelixa** [comment]
@plouc Would you suggest how to implement this? Changing `projectionScale` with a `useResize` or something?

**Comment by LuzanF** [comment]
@plouc I'm also facing this problem, is there any solution for this? the geo map disappears when resizing the browser

**Comment by plouc** [comment]
You could make `projectionScale`, `projectionTranslation` and `projectionRotation` depend on window size for example.

**Comment by LuzanF** [comment]
@plouc I'm trying to add sliders that will give the user the ability to select the projectionScale and the projectionTranslation, I'm not able to wrap <ResponsiveChoropleth> with any thing (the chart disappears...) do you have any suggestion on how to add sliders like in the documentation? thanks

**Comment by plouc** [comment]
@LuzanF the chart disappearing sounds like a bug, do you think you could reproduce this in codesandbox for example? 

The doc use [a config](https://github.com/plouc/nivo/blob/master/website/src/data/components/geo/props.js#L81) with some [custom controls](https://github.com/plouc/nivo/blob/master/website/src/components/controls/RangeControl.js#L18), but I think this would be way too complicated for most case, you could use a state and native range controls for example.

**Comment by LuzanF** [comment]
@plouc  I found interesting d3 method: projection.fitextent, the question is how can I use it with Nivo
