### ISSUE TITLE
Update documentation, Main README

### ISSUE THREAD

**Issue by ziyadmutawy** [plouc/nivo#786]
**Is your feature request related to a problem? Please describe.**

After creating a simple react-create-app with the following react versions: 

`    "react": "^16.12.0",
    "react-app-polyfill": "^1.0.4",
    "react-dev-utils": "^9.1.0",
    "react-dom": "^16.12.0",
`
I ejected and installed `@nivo/radar`

I ran across an error `cannot read property 'legends' of undefined` when using the example on the page: https://nivo.rocks/radar/

I then was able to track it down to the lack of having typescript installed (which my react-create-app didnt come with)

I looked around and didnt see it posted anywhere obvious that there is a dependency on typescript on the readme or website `nivo.rocks`. 

**Describe the solution you'd like**

Update the readme `https://github.com/plouc/nivo/blob/master/README.md` to state which peer dependencies we need. 

**Describe alternatives you've considered**

**Additional context**

**Comment by plouc** [comment]
typescript is not a direct dependency of the package, I think it's a dependency of CRA
