### ISSUE TITLE
Why are tooltips/legends ordered opposite to input data?

### ISSUE THREAD

**Issue by markdascher** [plouc/nivo#787]
I haven't been using Nivo long, so forgive my ignorance if the answer should be obvious.

The Nivo [Line](https://nivo.rocks/line/) docs use input data that looks like this:

```json
[
  { "id": "japan",   "data": [] },
  { "id": "france",  "data": [] },
  { "id": "us",      "data": [] },
  { "id": "germany", "data": [] },
  { "id": "norway",  "data": [] }
]
```

However, the legend on the right (and the tooltip, when setting `enableSlices` to `x`) reverses the input order, listing norway first.

Digging in, I found the useSlices hook currently includes a [slicePoints.reverse()](https://github.com/plouc/nivo/blob/master/packages/line/src/hooks.js#L103) when building the array of points for each slice. I'm guessing that has something to do with it.

That `.reverse()` must have a purpose, but I can't figure out what it is. Does it make more sense for other chart types? It's not hard to reverse the input to get the desired legend/tooltip order, but just felt odd.

**Comment by sattuchin** [comment]
This feature would be very useful. Please prioritize when possible. Thank you! For now, I've addressed it with a reverse()

**Comment by bjarkehs** [comment]
I just experienced this as well. It seems rather counter intuitive.

**Comment by tskk97** [comment]
^bump
