### ISSUE TITLE
Heatmap - attribute `cellShape` kills `tooltip`

### ISSUE THREAD

**Issue by ogroppo** [plouc/nivo#788]
When using the `cellShape` attribute for custom cell, the tooltip is not triggered anymore, also the custom `tooltip` attribute seems not to be read.

Example can be found in storybook docs:
https://nivo.rocks/storybook/?path=/story/heatmap--custom-cell-component

**Comment by plouc** [comment]
yes, that’s the behavior when you override the shape as it’s the interactive element of the chart, this way you have full control over it, you can restore this by using the handlers it receives, see [one of the default shape](https://github.com/plouc/nivo/blob/master/packages/heatmap/src/HeatMapCellRect.js) for example.
