### ISSUE TITLE
Issues with @nivo/treemap example

### ISSUE THREAD

**Issue by littlecastrum** [plouc/nivo#789]
This code which is a reproduction of the webpage example is not rendering the treemap and no error is being displayed. I don't really know what is missing. I'm passing the example root from the webpage

```javascript
import React, { Component } from 'react';
import { ResponsiveTreeMap } from '@nivo/treemap'
import { useTheme } from '@nivo/core'
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import { withStyles } from '@material-ui/core/styles';
import style from './style';

function TreeMap({ classes, root }) {
  return (
    <Grid container className={classes.root}>
      <ResponsiveTreeMap
        root={data}
        identity="name"
        value="loc"
        innerPadding={3}
        outerPadding={3}
        margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
        label="loc"
        labelFormat=".0s"
        labelSkipSize={12}
        labelTextColor={{ from: 'color', modifiers: [ [ 'darker', 1.2 ] ] }}
        colors={{ scheme: 'nivo' }}
        borderColor={{ from: 'color', modifiers: [ [ 'darker', 0.3 ] ] }}
        animate={true}
        motionStiffness={90}
        motionDamping={11}
      />
    </Grid>
  );
}
export default withStyles(style)(TreeMap);
```

**Comment by littlecastrum** [comment]
Apparently the structure is not supposed to be passed with the first part of the json object in the example

**Comment by totaland** [comment]
can you explain this a bit more? what is the correct data struc to use? do you have link to download this?

**Comment by wyze** [comment]
@totaland The website shows the data with a top level `root` key in the JSON, but what should be passed should be the value of the `root` key.

**Comment by codler** [comment]
Do you have an example in codesandbox?

**Comment by picoLizard** [comment]
> Do you have an example in codesandbox?

In the website examples, the 'data' object passed simply includes a 'root' key to start with:

```
{
  "root": {
    "name": "nivo",
    "color": "hsl(188, 70%, 50%)",
    "children": [
      {
        "name": "viz",
        "color": "hsl(17, 70%, 50%)",
        "children": [
```

instead, the data object should just launch straight into the first parent, without the need for the 'root' key, so the website example should read:

```
{
    "name": "nivo",
    "color": "hsl(188, 70%, 50%)",
    "children": [
      {
        "name": "viz",
        "color": "hsl(17, 70%, 50%)",
        "children": [

```
this is the same data object as the 'Bubble' - so if you look at that example, it is correct.

**Comment by davvit** [comment]
Thank you for this info. 
You can also just do this so you can copy the sample data on the demo site and use it.

```
  return <ResponsiveTreeMapHtml
        data={testData.root}    <----
        identity="name"
        value="loc"
```

**Comment by NicolasNewman** [comment]
Could we potentially look at getting this fixed on the website? I just spent a substantial amount of time trying to figure out what was wrong before coming across this
