### ISSUE TITLE
Treemap example from web site does not render and no error message

### ISSUE THREAD

**Issue by smelehy** [plouc/nivo#790]
Trying to simply copy the TreeMap example from the web site and make it work.  The container div has a height specification and root is copied exactly from the site.  It won't render and no error message. I'm out of ideas to try.  I tried the same thing with the Line graph - same exact result.  

I installed @nivo/treemap with npm install --save @npm/treemap.  
Using webpack with babel-loader to transpile

`import { ResponsiveTreeMap } from '@nivo/treemap';
`
`class MyTreeMap extends Component {
  render() {
    return(
      <div class="row border border-dark" id="thisIsIt" style={{height: "800px"}}>
          <ResponsiveTreeMap
              root={root}
              identity="name"
              value="loc"
              innerPadding={3}
              outerPadding={3}
              margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
              label="loc"
              labelFormat=".0s"
              labelSkipSize={12}
              labelTextColor={{ from: 'color', modifiers: [ [ 'darker', 1.2 ] ] }}
              colors={{ scheme: 'nivo' }}
              borderColor={{ from: 'color', modifiers: [ [ 'darker', 0.3 ] ] }}
              animate={true}
              motionStiffness={90}
              motionDamping={11}
          />
      </div>
    )
  }
}

       ReactDOM.render(
          <MyTreeMap/>,
        document.getElementById('root')
       )
`

**Comment by smelehy** [comment]
Just tried the same thing with this example from CodeSandbox https://codesandbox.io/embed/react-example-m1zry?fontsize=14&hidenavigation=1&theme=dark  with exact same result.  No render and no console errors.  I tried refreshing the chrome cache - no luck.

**Comment by smelehy** [comment]
an empty div with style of width: 100% and height: 100% is all that is rendered in all cases.
![Screenshot_1](https://user-images.githubusercontent.com/46900688/70581798-4a4a7400-1b6d-11ea-8141-991a8bc324f1.png)

**Comment by smelehy** [comment]
This was fixed by adding the following line to the main .js module file:   
`import ReactDOM from "react-dom";
`

**Comment by littlecastrum** [comment]
@smelehy I'm having the same issue with `@nivo/treemap`. Was the issue you have related to just importing the `ReactDom` variable in the main render file?

**Comment by smelehy** [comment]
Yes.  Adding that one line fixed it.
