### ISSUE TITLE
X:date points are one day behind the actual date listed.

### ISSUE THREAD

**Issue by NguyenBrian12** [plouc/nivo#793]
I have dummyData that has dates such as 2019-12-01, but when plotted, it plots as 2019-11-30... please help.
const MyResponsiveLine = ({ data }) => (
    <ResponsiveLine
        data={data}
        areaOpacity={1}
        margin={{ top: 20, right: 100, bottom: 20, left: 20 }}
        xScale={{
          type: 'time',
          format: '%Y-%m-%d',
          precision: 'day'
        }}
        xFormat="time:%Y-%m-%d"
        enableGridX={true}
        enableGridY={true}
        yScale={{ type: 'linear', stacked: false}}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          format: '%b %d',
          tickValues: 'every 2 days',
     
        }}
        axisLeft={null}
        colors={{ scheme: 'nivo' }}
        pointSize={10}
        enablePointLabel={true}
        pointColor={{ theme: 'background' }}
        pointBorderWidth={1}
        pointBorderColor={{ from: 'serieColor' }}
        pointLabel="y"
        useMesh={true}
        legends={[
            {
                anchor: 'bottom-right',
                direction: 'column',
                justify: false,
                translateX: 100,
                translateY: 0,
                itemsSpacing: 0,
                itemDirection: 'left-to-right',
                itemWidth: 80,
                itemHeight: 20,
                itemOpacity: 0.75,
                symbolSize: 12,
                symbolShape: 'circle',
                symbolBorderColor: 'rgba(0, 0, 0, .5)',
                effects: [
                    {
                        on: 'hover',
                        style: {
                            itemBackground: 'rgba(0, 0, 0, .03)',
                            itemOpacity: 1
                        }
                    }
                ]
            }
        ]}
    />
)

**Comment by JaredJRoss** [comment]
I was having this issue with doing every month and setting useUTC: false in the xScale solved this issue
