### ISSUE TITLE
Hide legends texts

### ISSUE THREAD

**Issue by santanapaulo** [plouc/nivo#796]
Hi there!!! I'd like to know if there is any way to hide the legend text on Pie Chart.

![image](https://user-images.githubusercontent.com/15819810/70806295-bdd0c900-1d99-11ea-9704-1cbc94d86abc.png)

According to the image, I want to hide the rounded texts.

PS: thanks for creating this amazing lib!

**Comment by plouc** [comment]
The point of legends is to provide legends ;) but you can fake it by setting `itemTextColor` to transparent
