### ISSUE TITLE
Selecting colors of treemap nodes from a string array

### ISSUE THREAD

**Issue by littlecastrum** [plouc/nivo#799]
I would like to be able to select colors of the nodes in my treemap from a list of rgb colors passed to the treemap. You can already provide the array for the pallette but I don't have control over which colors are assigned where

This is the Component with the colors array that I'm using
```
        <ResponsiveTreeMap
            root={data}
            identity="name"
            value="loc"
            innerPadding={3}
            outerPadding={3}
            margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
            label="loc"
            labelFormat=".0s"
            labelSkipSize={12}
            labelTextColor={{ from: 'color', modifiers: [ [ 'darker', 1.2 ] ] }}
            colors={['#416FA8','#7193BE','#A0B7D3', '#679436','#8DAF69','#B3C99A']}
            borderColor={{ from: 'color', modifiers: [ [ 'darker', 0.3 ] ] }}
            animate={true}
            motionStiffness={90}
            motionDamping={11}
        />
```

**Comment by shivamragnar** [comment]
Any update on this?

**Comment by plouc** [comment]
@littlecastrum, this will work, however, you'll have to define how to color the nodes depending on one of their property (e.g. `id`) if you want full control over colors, you can pass a function to `colors`, it will receive a node and should return a valid color.
