### ISSUE TITLE
Allow series to have different lengths

### ISSUE THREAD

**Issue by lapidus** [plouc/nivo#80]
What implications would it have to remove this check?
https://github.com/plouc/nivo/blob/9728dd85662c9c26c3193b7db5bea5eaf61377ec/src/lib/charts/line/index.js#L20-L28

Often Line Chart series have different time-spans. Both x-axis and y-axis should ideally calculate extent of all series independent of length.

**Comment by plouc** [comment]
@lapidus, this chart does not handle missing data for now https://github.com/plouc/nivo/issues/61, but once it's fixed maybe it will be easier to support this.

**Comment by lapidus** [comment]
Thank you @plouc. I am trying to replace scalePoint with scaleLinear to support more versatile data to Line Chart as well as incl. above support for missing values. I'll submit a PR if I'm successful ...

**Comment by selfishl0v3** [comment]
Any news on this? Usually when I have two series with different lengths I have to fill with null or 0 values.

**Comment by plouc** [comment]
Available via #275
