### ISSUE TITLE
Tooltip not showing ID

### ISSUE THREAD

**Issue by ymenase** [plouc/nivo#801]
Hi, I don't know where to put this question. I have a nivo line project and I have the hovering tool tip but it doesn't show any data or fields, only the rectangle and my corresponding line colors. I looked through the storybook as well and I am not sure how to edit this. I thought it would be something like "pointlabel" but my changes have no effect. Please help. Thanks.

**Comment by plouc** [comment]
You can have a look at the documentation, it shows how to use it:

<img width="966" alt="Capture d’écran 2020-01-14 à 20 04 35" src="https://user-images.githubusercontent.com/501642/72339150-23053a80-3709-11ea-8b18-b15eeae1c00a.png">

**Comment by ymenase** [comment]
I did... It turned out there was a setting in the css that was turning the
text white. Thank you

**Comment by ODINAKACHUKWU** [comment]
Thanks @ymenase for this. It helped me resolve the same issue in my project!
