### ISSUE TITLE
Pie label is required in PropTypes and used instead of id for tooltip, but isn't required in TS typings and docs

### ISSUE THREAD

**Issue by le0nik** [plouc/nivo#808]
Not required in TS typings: https://github.com/plouc/nivo/blob/f5798d0d76263c3fbd4a2f1b96ff29b8a2119710/packages/pie/index.d.ts#L7-L11
Required in PropTypes  https://github.com/plouc/nivo/blob/f5798d0d76263c3fbd4a2f1b96ff29b8a2119710/packages/pie/src/PieSlice.js#L77
And used instead of `id` for tooltip https://github.com/plouc/nivo/blob/f5798d0d76263c3fbd4a2f1b96ff29b8a2119710/packages/pie/src/PieSlice.js#L38

Which definition should be updated? Seems to me, that `label` should not be required and `id` should be used for tooltip

**Comment by plouc** [comment]
It’s because TS cover external/public API while PropTypes covers mostly internal API (after running higher order components and hooks).

**Comment by le0nik** [comment]
As a user of "external" API if I don't specify labels I always see PropTypes error in development that label is required, even if I don't use tooltips. Also there is no way of knowing at compile time that not passing label would break tooltips(because all id's would be `undefined`).

**Comment by plouc** [comment]
Yes, there’s a bug in the logic injecting the label then

**Comment by plouc** [comment]
Sorry didn’t touched this component for a while, id is required in both prop types and typings, so yes if you don’t pass this required property used internally to compute the label, you’ll have this warning

**Comment by cerber717** [comment]
@le0nik  @plouc  would you like me to add the `id instead of the label in tooltip` as-well as the fallback to the `id` in https://github.com/plouc/nivo/pull/797 ?
