### ISSUE TITLE
Allow for a "max width" on Bar Chart bars

### ISSUE THREAD

**Issue by effekt** [plouc/nivo#809]
**Is your feature request related to a problem? Please describe.**
As a user I would like to have fixed-width bar chart bars that don't expand / shrink when the data changes (amount of bars, etc).

**Describe the solution you'd like**
Be able to specify a maximum width for the bars, regardless of number of bars shown.

**Describe alternatives you've considered**
Modifying the package for a one-off use case, however this may be something useful for many.

**Additional context**
Ex: I want to have a maximum bar width of 18, I expect to see:

![Screen Shot 2019-12-27 at 1 30 42 PM](https://user-images.githubusercontent.com/11183340/71528334-52185100-28ad-11ea-86bd-33b1c837494a.png)

What I actually see:

![Screen Shot 2019-12-27 at 1 31 54 PM](https://user-images.githubusercontent.com/11183340/71528341-593f5f00-28ad-11ea-819e-4ef7ce5f0a2c.png)

**Comment by plouc** [comment]
The problem with this kind of option, is that they do not play well with the various modes the chart supports, stacked/grouped, vertical/horizontal, some people also asked for max height, min height, that's not something I consider adding for now, you can achieve this result by using a custom bar element thought.
