### ISSUE TITLE
Horizontal Bar chart - show data labels outside of the bar

### ISSUE THREAD

**Issue by rksbala** [plouc/nivo#812]
Is there any way to display the data labels at the end/outside of the bar. Please refer attached screenshot. 
**Current result:** Data label shown in middle of the bar (highlighted in red)
**Expected result:** At the end of the bar

![barchart](https://user-images.githubusercontent.com/6780344/71578237-4e8b0100-2b1d-11ea-91b9-da5f1599405d.png)

**Comment by amihalopoulos** [comment]
Anyone have a solution for this out yet?

**Comment by wyze** [comment]
Anyone have any thoughts what this might look like for stacked graphs when there is more than 1 item in the bar?

**Comment by amihalopoulos** [comment]
I think a sum would work & make sense

**Comment by Deliaz** [comment]
There is a way to achieve that using a custom `layouts`
https://codesandbox.io/s/nivo-bar-labels-outside-zndse?file=/src/index.js
