### ISSUE TITLE
BoxLegendSvg does not respect theme.legend.text.fill

### ISSUE THREAD

**Issue by CharlieMartell** [plouc/nivo#814]
**Describe/explain the bug**
Other legend types respect `theme.legend.text.fill` property but [BoxLegendSvg](https://github.com/plouc/nivo/blob/master/packages/legends/src/svg/BoxLegendSvg.js) only accepts 
itemTextColor. This means bar charts on svg don't work with dark mode theming 

**To Reproduce**
This is pretty easy to reproduce as it is broken on the example site: https://nivo.rocks/bar/, just change to dark mode. 
**Expected behavior**

**Screenshots**
<img width="151" alt="Screen Shot 2020-01-02 at 10 12 49 AM" src="https://user-images.githubusercontent.com/5011042/71683823-7611e180-2d48-11ea-8fc3-15306fef889e.png">

**Comment by wyze** [comment]
I'd consider this a bug. Note, that the LegendSvgItem does use the theme https://github.com/plouc/nivo/blob/793bebc8a972607820227ee87da1d3221caff9fc/packages/legends/src/svg/LegendSvgItem.js#L140-L145 but it doesn't overwrite the `fill` property.
