### ISSUE TITLE
Support for Cropping large values in Bar Chart

### ISSUE THREAD

**Issue by rajarameshvarma** [plouc/nivo#816]
I have many bar charts with outliers that have really large values compared to other items in the bar chart. 
![image](https://user-images.githubusercontent.com/7087542/71837270-d798bf80-306a-11ea-9b37-0a6c1f84f33a.png)

I would like to crop the long bars, so that the chart takes less space. Something like this: (ignore the orientation)

![image](https://user-images.githubusercontent.com/7087542/71837392-2a727700-306b-11ea-978d-3753cec388e5.png)

Not sure if this is already supported. If so, please point me to the documentation.

**Comment by plouc** [comment]
Sorry. this is not supported and is not something I plan to support.
