### ISSUE TITLE
Zooming in and out changes line chart size

### ISSUE THREAD

**Issue by john-martinez-729** [plouc/nivo#818]
This is hard to describe, so hopefully I'll do an ok job at it. Basically when I zoom in or out the dimensions of the chart change until I refresh the page. This leads to the rest of the page shifting to accommodate the larger chart. 

Here is a video link that shows what I mean: https://drive.google.com/file/d/1OGarMiFvS6m9HmXOlWICWVNThu7qGEA8/view

Here is my JS regarding the linegraph:

![code1](https://user-images.githubusercontent.com/52676492/71931265-642aa700-316b-11ea-9074-7fe210f1ef4c.png)
![code2](https://user-images.githubusercontent.com/52676492/71931273-67be2e00-316b-11ea-8df9-dc78eb5ab4fe.png)

and here is the CSS:

![code3](https://user-images.githubusercontent.com/52676492/71931284-6e4ca580-316b-11ea-87e2-df9bde779a8d.png)

**Comment by tg970** [comment]
It looks like in your css you have the height of the wrapper div at '60vh' - this means that no matter what the zoom is - the hight of the div is going to be 60% of the hight of the viewing window. Haven't tested this but confident this might solve your issue.

**Comment by john-martinez-729** [comment]
> It looks like in your css you have the height of the wrapper div at '60vh' - this means that no matter what the zoom is - the hight of the div is going to be 60% of the hight of the viewing window. Haven't tested this but confident this might solve your issue.

Thanks for the reply. I tried changing the wrapper div to a set height and I'm still having the same issues.
