### ISSUE TITLE
Adjust Pie chart sliceLabel position

### ISSUE THREAD

**Issue by georgefairbairn** [plouc/nivo#819]
**Problem**
I'd like to be able to position the labels on the pie chart closer to the outside edge of the pie (i.e. closer to the circumference)

**Describe the solution you'd like**
Perhaps a solution could be to change a value in the `theme` or it could be an additional prop passed to the component like `slicesLabelRadiusMultiplier={1.5}`

**Describe alternatives you've considered**
To my knowledge, no alternative exists - but I'd welcome any suggestions

**Comment by georgefairbairn** [comment]
@plouc - does this functionality already exist?

**Comment by tg970** [comment]
@georgefairbairn - Yes, checkout the 'RADIAL LABELS' section of the documentation, there are several adjustments for the labels. [https://nivo.rocks/pie/ ](https://nivo.rocks/pie/ )

**Comment by georgefairbairn** [comment]
@tg970 Thanks, but I'm not sure that answers my question here

I'm trying to adjust the position of the **Slices Labels**. I'd like to adjust them by moving them closer to the perimeter of the pie chart (as the linked image suggests)

Is this possible?

[Pie Chart Image Link](https://ibb.co/hfBfz0fl)

**Comment by georgefairbairn** [comment]
@plouc @tg970 - is it possible to get an answer to this?

**Comment by WhiteAbeLincoln** [comment]
I also need a solution for this. I have slice labels that end up being very long, and the current position in the center of the slice causes labels to overlap

**Comment by plouc** [comment]
This is gonna be implemented in https://github.com/plouc/nivo/pull/1204, via the `sliceLabelsRadiusOffset` property.
