### ISSUE TITLE
BarChart: Tooltip doesn't work with custom bar elements

### ISSUE THREAD

**Issue by azhuravlevlivegeniccom** [plouc/nivo#823]
**Describe/explain the bug**
When using custom bar elements on BarChart there are no tooltips.

**To Reproduce**
https://nivo.rocks/storybook/?path=/story/bar--custom-bar-item

1. Go to https://nivo.rocks/storybook/?path=/story/bar--custom-bar-item
2. Hover on any bar element on chart 
3. See that there is no any tooltip

**Expected behavior**
Tooltip is visible

If there is any workaround, tell me please.

**Comment by plouc** [comment]
@azhuravlevlivegeniccom, bars are the element catching interactions, there's no magical solution here, you can have a look at the default bar element implementation to see how it's made.

**Comment by DWboutin** [comment]
Good docs on that can be a solution

**Comment by obeka** [comment]
> @azhuravlevlivegeniccom, bars are the element catching interactions, there's no magical solution here, you can have a look at the default bar element implementation to see how it's made.

I can say this is the worst explanation to a question in this library.

**Comment by plouc** [comment]
I admit that the original answer wasn't very useful as is, that being said, I think it's the best way to replicate the default behavior, if the internal API changes, the codesandbox won't work anymore, it also doesn't support all the features of the default implementation.

The default implementation is defined in https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.tsx, the `useTooltip` hook can be used to control the tooltip, but you might want to use the same approach as the default implementation if you plan to have a custom tooltip or still support extra handlers, depending on your requirements.
