### ISSUE TITLE
Is there a way to format values on Bullet chart?

### ISSUE THREAD

**Issue by ogroppo** [plouc/nivo#827]
Just a question really :)

**Comment by sergiocc96** [comment]
Any response? And is posible disable tooltips?

**Comment by wyze** [comment]
@ogroppo Looks like there isn't, but definitely should support it.

@sergiocc96 You should be able to set `isInteractive={false}` and it will disable the tooltip.

**Comment by wyze** [comment]
Looks like this functionality was requested in #481 so I will close this and you can track issue!
