### ISSUE TITLE
Choropleth Legend prop is missing 

### ISSUE THREAD

**Issue by priyanshu966106** [plouc/nivo#828]
Legend prop  type is missing in Choropleth thus the builds are failing please add the types.

**Comment by vrunda-thacker** [comment]
I am also facing a similar issue as stated above, Legend prop is not being recognized on ResponsiveChoropleth.
This is a blocking issue, kindly add the missing types

**Comment by priyanshu966106** [comment]
Till then you can use `ts-ignore` @vrunda-thacker

**Comment by MainOlma** [comment]
I'm not sure if it is a good solution, but it works for me:
`import {ResponsiveChoropleth, ChoroplethProps} from '@nivo/geo'`
...
`const choroplethProps: ChoroplethProps & { legends: any } = {
        data: mapData,
        features: features,
...}`
...
`<ResponsiveChoropleth {...choroplethProps}/>`

**Comment by las3r** [comment]
This issue is not yet fixed in the latest version as of 17-01-2021. It should be trivial to add this to the typings right?
