### ISSUE TITLE
line: Area fill is going below the x axis when there is no plotted value that meets the lowest point on the y axis

### ISSUE THREAD

**Issue by cdwyer-cognito** [plouc/nivo#829]
**Describe/explain the bug**
![image](https://user-images.githubusercontent.com/18459691/72523659-2f4bdd80-3858-11ea-99a5-8a64b3af7a7a.png)

This is on the latest chrome browser
Not having a plot of 0 in the data set for the y axis causes the markers to shift and not scale, Int he example the 0 now would render below the x axis which has caused the fill to draw down to that point rather than stopping at the x axis. 

render code
```
import React from 'react';
import { ResponsiveLine } from '@nivo/line';
 // ...a react function that returns...

    <ResponsiveLine
      {...chartProps}
      data={data}
      curve={smooth ? 'natural' : 'linear'}
      lineWidth={3}
      enableArea={area}
      areaOpacity={0.5}
      data-testid="lineChart-ResponsiveLine"
    />
```
Data structure being passed
```
const chartProps = 
{"top":10,"right":40,"bottom":70,"left":40},"labelTextColor":"#000000","borderWidth":0,"enableDots":true,"enableDotLabel":true,"dotSize":8,"dotColor":"#000000","dotBorderWidth":0,"theme":{"labels":{"text":{"fontSize":9}},"legends":{"text":{"fontSize":9}},"axis":{"legend":{"text":{"fontSize":10,"fill":"#000000"}},"ticks":{"line":{"fill":"#CCC"},"text":{"fontSize":8,"fill":"#000000"}}},"grid":{"line":{"stroke":"#80808040","strokeWidth":0.5}}},"enableGridX":true,"enableGridY":true,"labelSkipWidth":10,"yScale":{"type":"linear","min":"auto","max":"auto"},"markers":[{"axis":"y","value":0,"lineStyle":{"stroke":"#80808040","strokeWidth":2}}],"axisBottom":{"orient":"bottom","tickRotation":-25,"tickSize":5,"tickPadding":10,"legend":"Date/Time - Hour of Day","legendOffset":65,"legendPosition":"middle"},"axisLeft":{"orient":"left","tickSize":5,"tickPadding":10,"tickRotation":0},"legends":[],"colors":{"scheme":"paired"},"animate":false,"isInteractive":true,"motionStiffness":90,"motionDamping":15};

const data = [{"id":"Date/Time - Hour of Day","data":[{"x":"0","y":100,"origClassName":"0"},{"x":"1","y":100,"origClassName":"1"},{"x":"2","y":100,"origClassName":"2"},{"x":"3","y":100,"origClassName":"3"},{"x":"4","y":100,"origClassName":"4"},{"x":"5","y":100,"origClassName":"5"},{"x":"6","y":81.76,"origClassName":"6"},{"x":"7","y":80.95,"origClassName":"7"},{"x":"8","y":85.72,"origClassName":"8"},{"x":"9","y":89.5,"origClassName":"9"},{"x":"10","y":89.92,"origClassName":"10"},{"x":"11","y":90.36,"origClassName":"11"},{"x":"12","y":84.23,"origClassName":"12"},{"x":"13","y":75.53,"origClassName":"13"},{"x":"14","y":80.12,"origClassName":"14"},{"x":"15","y":78.2,"origClassName":"15"},{"x":"16","y":74.68,"origClassName":"16"},{"x":"17","y":80.47,"origClassName":"17"},{"x":"18","y":65.95,"origClassName":"18"},{"x":"19","y":49,"origClassName":"19"},{"x":"20","y":47.47,"origClassName":"20"},{"x":"21","y":36.84,"origClassName":"21"},{"x":"22","y":28.78,"origClassName":"22"},{"x":"23","y":20,"origClassName":"23"}]}];
```

**Comment by mwood23** [comment]
Can confirm, looks like it's happening on the docs site too.

<img width="1548" alt="2020-02-27_14-27-42" src="https://user-images.githubusercontent.com/13633613/75479354-66d89a00-596d-11ea-8fd5-ece67f172d64.png">

**Comment by carloscastelano** [comment]
@cdwyer-cognito, did you find any solution to fix it?

**Comment by cdwyer-cognito** [comment]
@carloscastelano  The work around I applied was to have 0 as a fixed minimum value, It unfortunately provides a lot of dead space but it did work.

**Comment by fubhy** [comment]
This is not a bug, you need to set the `areaBaselineValue` prop to the right value (e.g. 20 in the example you showed) in The typescript definition for this prop is currently incorrectly named due to a typo. Here's a fix: https://github.com/plouc/nivo/pull/961

**Comment by wyze** [comment]
I'm going to agree that I don't think this is a bug. The axes and line is generated correctly based on the yScale and your data. Once you enable area, it will set its baseline value to 0 by default, so if your data doesn't reach zero, like in the case above, you need to set the `areaBaselineValue` accordingly.

Thanks for the typedef fix @fubhy!

**Comment by thehappycoder** [comment]
The problem isn't with area, actually. With enableArea=false and xScale.min=209, the graph is still going over x scale labels. https://nivo.rocks/line/.

Changing `areaBaselineValue` doesn't seem to be helping. It doesn't do anything to the graph even when area is enabled.

**Comment by kbzowski** [comment]
I believe the problem is still present in "@nivo/line": "0.73.0"

**Comment by korablin** [comment]
This is still the issue!

**Comment by hardcoregor** [comment]
For me it's problem too 
![image](https://user-images.githubusercontent.com/107989895/212797429-f73108e1-062b-4e05-ba6b-9a57cbb21701.png)

**Comment by jimmyhogerty** [comment]
Adding areaBaselineValue, and setting that value to my custom yMin fixed it for me.

**Comment by plouc** [comment]
As suggested, setting `areaBaselineValue` is the proper way to deal with this atm.

**Comment by ricardo-sendible** [comment]
You can solve that with the clamp property:
```
        yScale={{
          type: 'linear',
          min: 'auto',
          max: 'auto',
          clamp: true,
         ......
        }}
```

With this, you can even remove the areaBaselineValue prop from the component.
