### ISSUE TITLE
feature request: multiple nivo bar charts in one widget for mozaik

### ISSUE THREAD

**Issue by knackjax** [plouc/nivo#83]
might be my lack of understanding but it seems like charts are filling the entire div when I try to put it in mozaik. I noticed responsivewrapper code adds div width 100% and height 100%, is there a way to change this property? I would like to put three bar charts together in one widget.

thanks! we love your mozaik and nivo projects!

**Comment by plouc** [comment]
@knackjax, you can wrap it inside other divs, for example using a parent flexbox with 3 child divs having 33.3% width.

**Comment by knackjax** [comment]
@plouc thanks for the response but it doesn't seem to work. I get a blank div

https://www.webpackbin.com/bins/-KyIZNDisQjTeGdcceL2

**Comment by knackjax** [comment]
looks like I have to specify a concrete height, its inconvenient but I can live with that. Preferably I rather be able a height as a percentage.

**Comment by plouc** [comment]
Can you provide a running example with the updated approach? It should work, maybe I can help if you create a new bin on webpackbin.

**Comment by knackjax** [comment]
Updated example here, sorry I overwrote my original example but to replicate you just set height to a percentage and it will disappear.
https://www.webpackbin.com/bins/-KylBOM-OLUpXZ8zOhY-

Thanks!

**Comment by plouc** [comment]
To be able to use percents, you must have something to refer to, but in your case, `<html/>`, `<body/>` and `<div id="root"/>` do not have any height defined, it's just a matter of adding this css rule `html, body, #root { height: 100%; }` => https://www.webpackbin.com/bins/-KylDtsmpHvHY7J0BT5Z

**Comment by knackjax** [comment]
thanks this tidbit helps, I actually use your other project mozaik (v2) in conjunction with nivo. I modified the theme to have root with height 100% and it solved my issues.  Thanks again!
