### ISSUE TITLE
Reverse order of legend

### ISSUE THREAD

**Issue by manner** [plouc/nivo#839]
When using the vertical stacked bar chart I would like to be able to reverse the order of the legend.
In this bar chart example, each bar has values from `A` to `E` in ascending order, but the legend shows descending order.

[Code Sandbox here](https://codesandbox.io/s/nivo-legend-order-ln9tn)
![image](https://user-images.githubusercontent.com/3809419/72981142-63854800-3ddc-11ea-8471-72088909b934.png)

**Describe the solution you'd like**
To have a boolean property on the legend e.g. `reverseLegend`, which reverses the order of the legend.

**Comment by manner** [comment]
While creating a PR to add this feature, I realized this seems to be a bug with this specific configuration. Here is the link to the PR which fixes the order in this configuration #842

**Comment by dooleyb1** [comment]
+1 on this. Would love if the PR could be merged.

**Comment by serj-prog** [comment]
Same issue exists in line bar. Is there any updates on it?

**Comment by owenallenaz** [comment]
I'm having the same problem... perhaps if we could manually specify the order on the legend by using the `id` of the various data sets. So like legendOrder : [id1, id3, id2, id5]. If we change the order of the our data array it can mess with the axes otherwise I would say the legend should just match the data array.

**Comment by ballerdev01** [comment]
Echoing what @serj-prog said. Would be nice if this direction prop existed across multiple formats, especially line. Any plans to add this @plouc ?

**Comment by seanmaisch** [comment]
Echoing what @serj-prog said. Would be nice if this direction prop existed across multiple formats, especially line. Any plans to add this @plouc ?

**Comment by zakariaenosis** [comment]
The issue still exists for the line charts.

**Comment by DaliborKovar** [comment]
bump
