### ISSUE TITLE
feature request: differentiate between value and resize animation

### ISSUE THREAD

**Issue by codepunkt** [plouc/nivo#84]
I've noticed that animations occur on several occasions. It might not be an exhaustive list, but they at least occur when:

- resizing the container a responsive widget is rendered into
- updating data

I would love it if would be able to have animation happen on data update **only**.
I would love to have this:

![data-anim](https://user-images.githubusercontent.com/603683/32605987-d0d61b86-c553-11e7-80af-424798e8d8d4.gif)

But **definitely** not this:

![size-anim](https://user-images.githubusercontent.com/603683/32606252-e755c50e-c554-11e7-8770-bf04f4b31f4e.gif)

Is there any way to achieve this and differentiate between those two?
If it might be possible: What do you think about adding this via one or more additional params?

**Comment by codepunkt** [comment]
What does work is setting `animate` to false and only setting it to `true` before updating data - after which it's set back to `false`.

```javascript
handleDataUpdate = data => {
  // hard to say for spring-based react-motion stuff, set to 1sec as approximation
  const animationDuration = 1000

  this.setState({ animate: true })
  setTimeout(() => {
    this.setState({ data })
    setTimeout(() => {
      this.setState({ animate: false })
    }, animationDuration)
  }, 0)
}
```

That's rather hacky though and does not seem performant at all.
Any other ideas?

**Comment by plouc** [comment]
@codepunkt, react-motion using spring-based animation and not offering options to stop animation, it's not possible to do that, in your case maybe you could set `animate` to `false` in edit mode.
