### ISSUE TITLE
Bars sizes are rounded and don't take the whole chart area

### ISSUE THREAD

**Issue by constgen** [plouc/nivo#840]
Bars lines in `Bar` chart do not cover all area of a chart (SVG element). Their sizes are rounded. That's why we can see gaps on the left and right. This screenshot shows this issue comparing Histograms with Timeline

**Screenshots**
![image](https://user-images.githubusercontent.com/673144/72987183-89b5e280-3df2-11ea-8fb6-3dc67434c226.png)

To reproduce this you can use for example `width=200` and 92 child items

**Expected behavior**
Bars should take all space from left to right. The dimensions are integers `<g transform="translate(8, 20)">`. But float numbers are expected

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 0.61.1

**Comment by constgen** [comment]
The proposed PR fixes the issue. Now Histograms look correct 
![image](https://user-images.githubusercontent.com/673144/72988346-bec33480-3df4-11ea-9ffe-2d0e46acb1c0.png)

Demensions look as expected `<g transform="translate(2.150537634408602, 14)">`

**Comment by mwinkels-onegini** [comment]
👍 
maybe make this an option

**Comment by constgen** [comment]
Maybe not. Because coordinates on all other charts are float numbers

**Comment by constgen** [comment]
bump

**Comment by wyze** [comment]
@constgen Can you provide a CodeSandbox demonstrating above, or close to it, so I can check it out against your proposed PR please?

**Comment by constgen** [comment]
I will try

**Comment by wyze** [comment]
Here is one that represents the issue: https://codesandbox.io/s/busy-violet-s19us

**Comment by constgen** [comment]
My example https://codesandbox.io/s/nivo-bar-chart-ki9h7

**Comment by wyze** [comment]
This was added in #1282. You can use `indexScale={{ type: 'band', round: false }}`. This will be available in the next version.
