### ISSUE TITLE
Treemap tile coloring

### ISSUE THREAD

**Issue by sciamp** [plouc/nivo#845]
**Is your feature request related to a problem? Please describe.**
While building a treemap I noticed this difference in tile coloring with the treemap I was previously using.

In the current implementation that different colors correspond to a different depth in the data tree, this is awesome when dealing with a data tree with indefinite depth, but I couldn't find a wat to represent data with one level only of depth setting a different color for every group at the same level (i.e. a different color for every leaf) aside from manipulating my data:

[Here is a sandbox to try to be as clear as possible :)](https://codesandbox.io/s/dry-rgb-rke0v?fontsize=14&hidenavigation=1&theme=dark)

so basically instead of setting up the treemap with my `originalData`:
```js
const originalData = {
  name: "my data",
  children: [
    {
      name: "group 1",
      children: [
        {
          name: "el 1 group 1 (should be red)",
          value: 100
        },
        {
          name: "el 2 group 1 (should be red)",
          value: 200
        }
      ]
    },
    {
      name: "group 2",
      children: [
        {
          name: "el 1 group 2 (should be blue)",
          value: 90
        },
        {
          name: "el 2 group 2 (should be blue)",
          value: 220
        }
      ]
    }
  ]
};
```
which results in this:
![image](https://user-images.githubusercontent.com/234184/73075061-5ee39100-3ebb-11ea-87ba-e44639879e53.png)

I changed my data to `manipulatedData`:
```js
const manipulatedData = {
  name: "my data",
  children: [
    {
      name: "group 1",
      children: [
        {
          name: "el 1 group 1 (should be red)",
          value: 100
        },
        {
          name: "el 2 group 1 (should be red)",
          value: 200
        }
      ]
    },
    {
      children: [
        {
          name: "group 2",
          children: [
            {
              name: "el 1 group 2 (should be blue)",
              value: 90
            },
            {
              name: "el 2 group 2 (should be blue)",
              value: 220
            }
          ]
        }
      ]
    }
  ]
};
```
that yields the result I expected
![image](https://user-images.githubusercontent.com/234184/73075154-981c0100-3ebb-11ea-88f0-ffa8de33a3a1.png)

**Describe the solution you'd like**
I would love some sort of option to switch to this tile coloring behavior without having to mess around with my data.

**Describe alternatives you've considered**
The alternative is the one shown in the codesandbox: I can add an `n` level extra nesting for the `n+1`-th leaf

I'm super willing to help and very happy to provide a PR for this, I just wish to know:
* if this makes any sense to you
* where I should work to add such a feature.

Thank you :)

**Comment by sravani1906** [comment]
I am facing same issue. I am having data which doesn't have different depths and is flat. Please let me know if there is any solution where I don't have to manipulate the data
