### ISSUE TITLE
Enable area only data

### ISSUE THREAD

**Issue by thallesrv** [plouc/nivo#847]
How can I enable / disable data only area? 

I want one of the graph lines to not have the area

**Comment by kagansari** [comment]
Any solution?

**Comment by kagansari** [comment]
I found a hacky solution but it works if you are using svg. Assign a custom color to the line and hide the area with css

```js
const Container = styled.div`
  path[fill="#123456"] { fill-opacity: 0 !important; }
`
```
```js
<Container>
  <Line
    colors={{ datum: 'color' }}
    data={[
      {
        id: 1,
        color: '#123456',
        data
      }
    ]}
  />
</Container>
```

**Comment by RealAdamSinger** [comment]
I am also looking for a solution to this. This library is great but lacks mixing different rendering into a single chart

**Comment by RealAdamSinger** [comment]
Yup, I found a less hacky way.

```Javascript
const Areas = ({
  series, areaGenerator, xScale, yScale,
}) => series.map(({ id, data, color }) => (
  <path
    key={id}
    d={areaGenerator(
      data.map(d => ({
        x: xScale(d.data.x),
        y: yScale(d.data.y),
      })),
    )}
    fill={color}
    fillOpacity={0.25}
  />
));
```
and then in your chart add the layers prop
```Javascript
        layers={['grid', 'markers', 'axes', Areas, 'crosshair', 'lines', 'points', 'slices', 'mesh', 'legends']}
```
You can return different `fill: "none"` based on the index of your data

**Comment by harrypfry** [comment]
@RealAdamSinger thanks that's ideal. Do you have a link for documentation on these layer functions? I've been unable to find any.

**Comment by wyze** [comment]
@harrypfry Sorry, we currently don't have any documentation around custom layers. Would need to look through examples and source code currently.
