### ISSUE TITLE
How to change color or fomat of only one axes-Label exclusively. 

### ISSUE THREAD

**Issue by sanidhyatandon** [plouc/nivo#848]
![image](https://user-images.githubusercontent.com/12902267/73161295-3a80f200-4111-11ea-8420-3603caa1cbfd.png)
Hey,
As you see in this image I just want to make the Left-Axes grid labels bold, and I am not finding any solution to do that. I tried using theme prop but that applies on top-grid labels as well. Please, someone, help me as I am blocked here.

------Thank You--------

**Comment by sanidhyatandon** [comment]
@plouc Can you Please help me with this ??

**Comment by sanidhyatandon** [comment]
@plouc Also can you also help me with how to align the labels to right end in horizontal bars as in the image above.

**Comment by mia-pelino** [comment]
I'm also looking for a way to do this on the axisBottom text, only I would also like to know if there is a way to only make one of the values bold. Any help is appreciated 😸

**Comment by mia-pelino** [comment]
@sanidhyatandon I'm sure you're not still stuck since this is 3 months later, but I was able to align my vertical bar labels flush with the top using this: 

labelFormat={d => <tspan y={ 0 }>{ d }</tspan>}

maybe try the same thing but replace y with x?

**Comment by wyze** [comment]
We might be able to extend the theme or axis* props to support this a little better, but in the short term you can use a custom renderTick method.

Here is an example where I provided custom renderTick with the bold styling (1) and then also a custom bar component to move the labels to the right (2).

https://codesandbox.io/s/jovial-shockley-c6lbt
