### ISSUE TITLE
ResponsivePieCanvas does not show when rendering.

### ISSUE THREAD

**Issue by alexandru-tomescu** [plouc/nivo#850]
**Describe/explain the bug**
ResponsivePieCanvas does not show when rendering. When hovering, it is showing values. For now i'm using ResponsivePie, this one is working but ResponsivePieCanvas is better because i can generate PDF files on browser and see the charts.

I'm using also ResponsiveBarCanvas in the same mode and it is working as it should (in PDF files also)

**To Reproduce**

```
<ResponsivePieCanvas data={data} {...props} />
```
where `data` is 
```
const data = [
	{
		id: 'aaaa',
		label: 'aaaa',
		value: 84,
		color: 'hsl(146, 70%, 50%)'
	},
	{
		id: 'bbbb',
		label: 'bbbb',
		value: 16,
		color: 'hsl(153, 70%, 50%)'
	}
];
```
and `props` is an empty object

**Expected behavior**
Render the ResponsivePieCanvas as ResponsivePie it is rendered. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by Vatsov** [comment]
The frequent problem occurs because the responsive pie chart initially the value will be zero. 
To overcome this need to define a specific height in the parent component. 

```
<div style={{height:400}}>
    <ResponsivePieChart />
</div>
```
