### ISSUE TITLE
[feature request] enable customize radar dot label position

### ISSUE THREAD

**Issue by sibelius** [plouc/nivo#851]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/2005841/73370867-a4c1a000-4293-11ea-9e24-11f0efe4e5d3.png)

The image above shows that radar chart dot label are overlapping when values is too close

**Describe the solution you'd like**
Right now we can only customize dotLabelYOffset, but this is not enough to fix dot label overlapping issues.
I think the solution would be to provide different dotlabel x/y offsets per `keys`

**Describe alternatives you've considered**
I've only tried to fix label offset

**Additional context**
screenshot above

Here is my current fix for this on this file https://github.com/plouc/nivo/blob/master/packages/radar/src/RadarDots.js#L55

```jsx
const points = data.reduce((acc, datum, i) => {
        const index = getIndex(datum)
        keys.forEach((key, j) => {
            const pointData = {
                index,
                key,
                value: datum[key],
                color: colorByKey[key],
                labelYOffset: labelYOffset * (j+1), 
            }
            acc.push({
                key: `${key}.${index}`,
                label: enableLabel ? getLabel(pointData) : null,
                style: {
                    fill: fillColor(pointData),
                    stroke: strokeColor(pointData),
                    ...positionFromAngle(angleStep * i - Math.PI / 2, radiusScale(datum[key])),
                },
                data: pointData,
            })
        })

        return acc
    }, [])
```

I've generated a different labelYOffset for dot based on `keys` index

the result is like this:

![image](https://user-images.githubusercontent.com/2005841/73371396-67a9dd80-4294-11ea-91e1-9bf05be01de2.png)

**Comment by ashu565** [comment]
Can we Label radar according in custom way ? Like we define ranges for each category ?
