### ISSUE TITLE
any way to keep the crosshair on the chart onMouseLeave? 

### ISSUE THREAD

**Issue by seinnaidess** [plouc/nivo#858]
Hi, I am using the `<Line />` and have slices enabled, I would like the crosshair to remain visible on the chart (at whatever datapoint was the last point of interaction) after interactivity has stopped. Is this possible?

**Comment by zaven-h** [comment]
@plouc  I want to make it so too. Is this possible?

**Comment by wyze** [comment]
You can do it with a custom layer that replaces the current `'crosshair'` layer.

You would want to build a wrapper component that renders this:


```jsx
<Crosshair
  key="crosshair"
  width={innerWidth}
  height={innerHeight}
  x={currentSlice.x}
  y={currentSlice.y}
  type={enableSlices} /* would be `x` or `y` depending on your slice */
/>
```

Then the wrapper component, use some method, maybe a ref, to keep track of `currentSlice` and when the prop comes in null (from nivo), then render the currentSlice value you have been keeping track of.
