### ISSUE TITLE
y-axis - auto scale with holes in data

### ISSUE THREAD

**Issue by axlider** [plouc/nivo#859]
Hi,

I use "yScale={{ type: 'linear', stacked: false, min: 'auto', max: 'auto' }}" to auto scale y axis.
Unfortunately when I combine this with "holes in data",  auto-scaling does not work anymore and the hole y-axis appears.
Unfortunately the null values on y axis are responsible for this.
Shouldn't only '0' values influence auto-scaling and not null values?

I think the problem is line 126 in 'packages/scales/src/compute.js':
` min = Math.min(...all)`  
because `Math.min([null])` resolves to '0'.

I think 'all' should be filtered before calculating y.
Someting like:

```
const validAll = all.filter(val =>  val !== null);
min = Math.min(validAll);

```
Thanks a lot!

**Comment by jhonabreul** [comment]
Hey! Has anybody check this out? Please, I have the same issue

**Comment by renato** [comment]
I'm facing the same issue, I used a similar workaround as the OP but I believe "auto" should account for null values.
