### ISSUE TITLE
Nivo/Line X-Axis Issues with time.

### ISSUE THREAD

**Issue by pratikguru** [plouc/nivo#865]
I have been having this issue with Nivo for quite a while, and wanted to clear it out. 
I have a data-set with this format.
`data = [
 id : "ID: 1",
 data : [
  { x : moment( date ).format("YYYY-mm-DD:HH:MM:ss" , y : int }
 ]
]`

The format for the line chart is this 

```
`<ResponsiveLine
            data={data}
            margin={{ top: 50, right: 110, bottom: 90, left: 60 }}
            xScale={{
              type: "time",
              format: "%Y-%m-%d %H:%M:%S",
              precision: "millisecond"
            }}
            xFormat="time:%Y-%m-%d %H:%M:%S"
            yScale={{
              type: "linear",
              min: "auto",
              max: "auto",
              stacked: false,
              reverse: false
            }}
            curve="cardinal"
            axisTop={null}
            enableGridX={false}
            axisRight={null}
            axisBottom={{
              format: "%b %d",
              tickValues: "every 2 seconds",
              legend: "time scale",
              legendOffset: -12,
              orient: "bottom",
              tickValues: 15,
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 45,
              legend: this.props.legend,
              legendOffset: 36,
              legendPosition: "middle"
            }}
            axisLeft={{
              orient: "left",
              tickSize: 5,
              tickPadding: 5,
              tickRotation: 0,
              legend: "count",
              legendOffset: -40,
              legendPosition: "middle"
            }}
            colors={{ scheme: "nivo" }}
            pointSize={5}
            pointColor={{ theme: "background" }}
            pointBorderWidth={1}
            pointBorderColor={{ from: "serieColor" }}
            pointLabel="y"
            pointLabelYOffset={-12}
            useMesh={true}
            legends={[
              {
                fill: "white",
                anchor: "top",
                direction: "row",
                justify: false,
                translateX: 0,
                translateY: -40,
                itemsSpacing: 0,
                itemDirection: "left-to-right",
                itemWidth: 200,
                itemTextColor: "#cccccc",
                itemHeight: 20,
                itemOpacity: 0.75,
                symbolSize: 12,
                symbolShape: "circle",
                symbolBorderColor: "rgba(0, 0, 0, .5)",
                effects: [
                  {
                    on: "hover",
                    style: {
                      itemBackground: "rgba(0, 0, 0, .03)",
                      itemOpacity: 1
                    }
                  }
                ]
              }
            ]}
            theme={{
              fontFamily: "Montserrat",
              textColor: "white",
              text: {
                fill: "white"
              },
              axis: {
                ticks: {
                  line: {
                    stroke: "green"
                  },
                  text: {
                    fill: "white"
                  }
                },
                legend: {
                  text: {
                    fill: "white"
                  }
                }
              },
              crosshair: {
                line: {
                  stroke: "white",
                  strokeWidth: 0.3,
                  strokeOpacity: 0.75,
                  strokeDasharray: "6 6"
                }
              },
              grid: {
                line: {
                  stroke: "white",
                  strokeWidth: 0.5
                }
              }
            }}
            animate={true}
            motionStiffness={215}
            motionDamping={20}
          />`
```

I get an error saying 

`TypeError: null is not an object (evaluating 'v.getTime')`

```
'max = Math.max.apply(Math, _toConsumableArray(all));
  292 | } else if (scaleSpec.type === 'time') {
  293 |   all = uniqBy(all, function (v) {
 294 |     return v.getTime();
      | ^  295 |   });
  296 |   all = all.slice(0).sort(function (a, b) {
  297 |     return b - a;'
```

I've been cracking my head for a while and can't seem to figure out what the problem is.. I think the error is very small maybe with the formats to be set, could anyone please point out what could be the problem?

I want the intervals to be somewhere like every 15 minutes.

**Comment by wyze** [comment]
If you wouldn't mind throwing this together in a CodeSandbox, I can take a look.

**Comment by pratikguru** [comment]
Hey,

Here is the sandbox link.

https://codesandbox.io/s/heuristic-payne-6lsp6?fontsize=14&hidenavigation=1&theme=dark

**Comment by wyze** [comment]
I think the data coming in is formatted incorrectly and not able to be parsed as a date. I replaced the `T` with a space and removed the `+00:00` and then the chart rendered the data.

**Comment by pratikguru** [comment]
Thanks! That should help render it. 

Could you please write down how the interval can be set? and how the format on the X-Axis can be changed? I tried to play around with the config but it ends up with the same error.

**Comment by man-person** [comment]
i get the same error. 
The hours and the minutes are required in the format, so removing them as suggested in the answer above is not an option for me.

**Comment by sniko10** [comment]
This issue is still reproducing after all those years.

**Comment by plouc** [comment]
@sniko, what issue exactly? the original issue was due to a formatting problem.

**Comment by plouc** [comment]
Just to clarify, the fix wasn't to remove the hours and minutes, but the TZ offset, (note the `+`).

**Comment by sniko10** [comment]
In my case i just found out that I use xScale in Line charts I also have to provide extra information for **axisBottom** in order to fully work. 

The Storybooks examples are great if you are prepared to fully explore the power of the charts.

Also, can we write this information in Line Charts Demo ? That we need to provide extra information for **AxisBottom** in order for line charts to fully work without errors ?

**Comment by plouc** [comment]
@sniko10, it depends on the scale used, it's not necessarily true for linear or ordinal scales, but it could be interesting to mention in storybook, where the config is more specific, but the storybook demos already include the required config for the x axis.
