### ISSUE TITLE
Typings Error

### ISSUE THREAD

**Issue by volkerchartier** [plouc/nivo#866]
**Thanks for using nivo**
Super Lib!! Thanks for it!

**Describe/explain the bug**
In TypeScript <Bar> + </RepsonsiveBar> both missing "onMouseEnter" + "onMouseLeave" in Typing index.d.ts. adding the following solves problem.
 
`
    export type BarSvgProps = Data &
        BarProps &
        MotionProps &
        SvgDefsAndFill<BarDatum> &
        Partial<{
            layers: Layer[]
            onClick: (datum: BarExtendedDatum, event: React.MouseEvent<SVGRectElement>) => void
            onMouseLeave: (datum: BarExtendedDatum, event: React.MouseEvent<SVGRectElement>) => void
onMouseEnter: (datum: BarExtendedDatum, event: React.MouseEvent<SVGRectElement>) => void
        }>
`
**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

use  Lib in a TS project like CRA `npx create-react-app my-app --template typescript`

**Expected behavior**
No Typescript Error

**Comment by wyze** [comment]
This should be resolved in the latest version.
