### ISSUE TITLE
How to update the "keys" font-size in the image as a highlighted items?

### ISSUE THREAD

**Issue by nitinreddy3** [plouc/nivo#869]
![keys_update](https://user-images.githubusercontent.com/5886208/74215237-69c56080-4cc6-11ea-92e5-f905bed7c380.PNG)

How can I update the font-size of the keys highlighted in yellow color in the above image?
Any suggestions will be really helpful!

**Comment by wyze** [comment]
It is on the `theme` prop.

```
{
  legend: {
    text: {
      fontSize: 16
    }
  }
}
```

**Comment by plouc** [comment]
Thank you @wyze
