### ISSUE TITLE
feature request: legend for charts (bar, line, etc)

### ISSUE THREAD

**Issue by knackjax** [plouc/nivo#87]
Support for a legend on the stacked bar charts or any others if needed (i.e. http://bl.ocks.org/ZJONSSON/3918369).  For us this would help in our non-interactive dashboard.

**Comment by dtelad11** [comment]
I will second that -- legends will be welcome.

Going through the code, I see that we can define a legend for the axes -- but I believe the current legend implementation is actually for an axis label.

**Comment by plouc** [comment]
@dtelad11, you're right, the name is misleading

**Comment by plouc** [comment]
@knackjax, @dtelad11, I've created `@nivo/legends`, it's already implemented on few charts, you can follow the ongoing work [here](https://github.com/plouc/nivo/pull/98).

I've also added a new [guide](http://nivo.rocks/#/guides/legends) about legends usage (still a WIP though).

**Comment by dtelad11** [comment]
This is fantastic. Thank you.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/98

**Comment by knackjax** [comment]
@plouc thanks for adding this in so quickly! I'm using it now... I found a minor bug #112.
