### ISSUE TITLE
LineChart: Show/Hide point based on data

### ISSUE THREAD

**Issue by joshkay** [plouc/nivo#870]
Is it currently possible to hide certain points on the line chart based on the dataset?  I can't seem to find an option for this.

**Comment by wyze** [comment]
I think this is what you are looking for? https://nivo.rocks/storybook/?path=/story/line--holes-in-data

**Comment by joshkay** [comment]
Not exactly. I want to be able to hide the actual dot on the graph for certain data points, but still draw the line.

**Comment by wyze** [comment]
Ah okay, you will need to use a custom layer instead of the `points` layer.

**Comment by joshkay** [comment]
Okay, I was worried about having to do that. Thanks for the help.

**Comment by captainheart** [comment]
> I think this is what you are looking for? https://nivo.rocks/storybook/?path=/story/line--holes-in-data

Hi @wyze  is it possible to have an option to link segments smoothly?
I have a dataset with holes and I want to display like this.
Thanks in advance!!!

![image](https://user-images.githubusercontent.com/42261423/86548192-2d7bf080-bf44-11ea-9f9f-3554a050bcac.png)

**Comment by michaeldever** [comment]
I would love to be able to disable points based on a line id or something along those lines.

I have lines with holes in the data, and I have backfilled the data (it's not perfect, as the curve of the line between two points that are very close together is nonexistant, but that's another issue for another day.

However, in the image below, highlighted red, there is a gap between the two lines as there is a space being allowed for a non-existant point.

![Screenshot 2020-08-29 at 09 48 48](https://user-images.githubusercontent.com/120821/91633022-f45c7b80-e9dc-11ea-97ba-95ddd7fd9a77.png)

**Comment by JannVazTor** [comment]
> > I think this is what you are looking for? https://nivo.rocks/storybook/?path=/story/line--holes-in-data
> 
> Hi @wyze is it possible to have an option to link segments smoothly?
> I have a dataset with holes and I want to display like this.
> Thanks in advance!!!
> 
> ![image](https://user-images.githubusercontent.com/42261423/86548192-2d7bf080-bf44-11ea-9f9f-3554a050bcac.png)

I'm also facing this, I've searching without luck, anyone manage to solve it?

**Comment by aamir-mns** [comment]
Why is this issue closed? It's a much needed feature
