### ISSUE TITLE
Responsive line plotting the data incorrectly

### ISSUE THREAD

**Issue by gowsreeni** [plouc/nivo#872]
I have added the code and working example in the below link.
https://codesandbox.io/s/tender-varahamihira-6b2qv

I am trying to split the y axis based on percentage. The first data series plots correctly. But the second data series is plotted incorrectly.

**Comment by gowsreeni** [comment]
Hey @plouc Thank you for the wonderful library.

**Comment by wyze** [comment]
Is it because you have the yScale stacked? I'm not sure what you mean by split the y-axis based on percent.

**Comment by gowsreeni** [comment]
@wyze If I have to plot the data based on percentage, between 0 to 100% and increment it with every 25% how am I supposed to do it? Instead of explicitly giving it in the tickvalues of axis.
Also do we have any option to change the way how a tooltip is being rendered ?

**Comment by wyze** [comment]
Whats wrong with specifying tickValues? You have to do that if you don't want them populated by the scale automatically. Also see this storybook for custom tooltip: https://nivo.rocks/storybook/?path=/story/line--custom-tooltip

**Comment by gowsreeni** [comment]
The reason is when giving specific tickValues the Yaxis line(vertical line) disappears. Not sure why. And thanks for the custom tool tip. Had a look at it earlier but not sure how to customize values.

**Comment by wyze** [comment]
Are you sure that isn't because `enableGridX={false}`? If it isn't I'm sorry, not sure I am following.

**Comment by gowsreeni** [comment]
@wyze Sorry for the late reply. Didnt get time to see the post. So my question is consider a responsive line chart, or in the storybook as well. The axisleft will have a visible line with tick values like 10%,20% or 30%. But when I try to run with tickvalues or without tickvalues defined I dont get that line connecting all the values in Y -Axis. 

2) Also If I need some space at the top for some nice look how should I do it ?

**Comment by gowsreeni** [comment]
@wyze I have tried enabling and disabling enableGridx property. The thing is if I enable it I am getting all square boxes in my chart area. Wherein I need only the Y-Axis line and X-Axis line alone.At the bottom and the side one where we have our tickvalues. Just one line for both the axis. Can we do that ?
