### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by tothandras** [plouc/nivo#873]
I'm evaluating charting libraries and it seems like there was no new commit since last year. Is nivo being deprecated?

**Comment by sibelius** [comment]
no 

check this https://github.com/plouc/nivo/pull/821

**Comment by jamesdh** [comment]
@tothandras if you look at the commit history, you can see @plouc tends to work on this in batches. Every few weeks you'll see a bunch of activity all on one or two days. It's just how he seems to work. Unfortunately it also means he's not the most responsive.

**Comment by sibelius** [comment]
he answers on discord

**Comment by plouc** [comment]
@tothandras nivo is a « side project », not backed by any company, it means I can work on it only during my spare time, if you’re looking for a professional support and a committed roadmap, you might want to consider paid solutions. That being said, I think this lib has some benefits over other solutions, and is open to contributions. So to answer your question: no it’s not deprecated :) In the end it depends on your requirements, if you need a lot of charts not available in Nivo and you cannot afford contributing to the project, this is probably not a good fit.

**Comment by tothandras** [comment]
Thanks for your answer! I was just interested in the current state and obviously, I am happy to contribute.
