### ISSUE TITLE
[ResponsiveBar] - Show Entries in Legend for 0 Value Data Points

### ISSUE THREAD

**Issue by dooleyb1** [plouc/nivo#874]
**Is your feature request related to a problem? Please describe.**
I'm currently rendering a `<ResponsiveBar>` element that does not contain stacked values across the range and is similar. However, for entries in the bar chart that take the value 0 there is no entry in the legend corresponding to this option.

**Describe the solution you'd like**
I think it'd be nice if there was an option to display a legend for 0 values with a color that that they would take in the case that they did have a non-zero value.

**Describe alternatives you've considered**
Read around the docs and previous issues but couldn't find anything that matched what I was looking for.

**Additional context**
<img width="1463" alt="Screenshot 2020-02-14 at 17 30 32" src="https://user-images.githubusercontent.com/23729427/74553936-41e92d80-4f50-11ea-9edd-17f42dd40054.png">

**Comment by wyze** [comment]
This has been fixed in the latest version. https://codesandbox.io/s/nivo-basic-demo-forked-7z0x6?file=/src/index.js
