### ISSUE TITLE
Unable to format the line graph how I need

### ISSUE THREAD

**Issue by standayweb** [plouc/nivo#875]
**Is your feature request related to a problem? Please describe.**
I am unable to format the line graph how I want.

**Describe the solution you'd like**
I would like:
- a way to align the ticks text to the left on the x axis
- a way to hide the first tick on the x axis
- a way to make the line on each axis not dotted
- a way to stop the text on the top tick on the y axis being cropped.
- a way to remove the space on right hand side of the chart

**Describe alternatives you've considered**
I have spent a day or so looking through the docs trying different solutions and I am unable to achieve the desired formatting.

**Additional context**
Here is a screenshot of what I have achieved so far, and a screenshot of the mockup I am trying to achieve. Ignore the tooltip, I haven't tried to implement that yet.
<img width="720" alt="Image 2020-02-18 at 12 19 06 pm" src="https://user-images.githubusercontent.com/8285082/74735890-7f4c0480-5249-11ea-88b5-f7852fdd6d36.png">
<img width="675" alt="Image 2020-02-18 at 12 20 22 pm" src="https://user-images.githubusercontent.com/8285082/74735907-88d56c80-5249-11ea-9bbc-0aaba06a7f06.png">

**Comment by wyze** [comment]
If you want to throw it together in a CodeSandbox we can take a look. Most of what you are asking sounds possible.

**Comment by standayweb** [comment]
Ok thanks, will do @wyze

**Comment by standayweb** [comment]
Managed to fix the cropping issue on the top tick by setting the overflow visible on the chart SVG, which was being set to overflow hidden by some a global style. The other issues are still in the code sandbox @wyze 
https://codesandbox.io/s/polished-paper-z675i?fontsize=14&hidenavigation=1&theme=dark

**Comment by wyze** [comment]
@standayweb Here you go, I commented on each change: https://codesandbox.io/s/zen-breeze-njkci

> a way to make the line on each axis not dotted

I think this was referring to each value? If not then I'm not sure.

**Comment by standayweb** [comment]
@wyze I mean the grid lines, in the mockup all the grid lines are dotted lines, except the one at the bottom, and the one at the left

**Comment by standayweb** [comment]
Also, there is still a space at the right-hand side of the chart making it not line up with the legend, I could compensate with padding adjustments, etc though so doesn't matter too much.

I also get this error in typescript with the useTheme, have just used @ts-ignore on that:
`Module '"@nivo/core"' has no exported member 'useTheme'.`

Anyway thanks for the help, I would never have worked out the AxisTick component especially, much appreciated!

**Comment by wyze** [comment]
Oh, you explicitly set the `strokeDashArray` in the grid theme, just remove that.

I've updated the sandbox to fix the margin and dashed lines.

... Yeah, hopefully with the current TypeScript migration we won't have issues about things not being exported.

**Comment by standayweb** [comment]
Thanks, the spacing fix worked, I created an image to show what I am trying to achieve with the dotted lines since I was finding it hard to explain it with text. I want to red lines to be solid and the blue lines to be dotted. Not sure if this is possible?
<img width="563" alt="Image 2020-02-19 at 1 44 56 pm" src="https://user-images.githubusercontent.com/8285082/74840205-7c6f1380-531e-11ea-8f0e-fb016dd00afc.png">

**Comment by wyze** [comment]
Ah okay, you might have to overwrite that with CSS.

**Comment by standayweb** [comment]
I'll give that a try thanks

**Comment by standayweb** [comment]
Was able to achieve it with this
```
line:first-of-type {
  stroke-dasharray: none;
}
```
