### ISSUE TITLE
Adding date formatting library to documentation

### ISSUE THREAD

**Issue by krezchikov42** [plouc/nivo#877]
So recently I was trying to create a time series chart, but I was very confused on how to use the xScale format or the xFormat. The example in the story books had `xFormat="time:%Y-%m-%d"` so I could tell there was some date formatting library being used, but I wasn't sure which one.

After digging into the code I found out it was the https://github.com/d3/d3-time-format. I think somewhere in the docs putting a reference saying that your using that library to format dates might make things easier for future users.

**Comment by plouc** [comment]
Right, I've added it to the doc (https://github.com/plouc/nivo/pull/899)

**Comment by joostdecock** [comment]
Were these changes ever deployed? Because I just spent 20 minutes googling this exact same question, and I don't see it on the website:

![Screenshot_2020-04-30 Line](https://user-images.githubusercontent.com/1708494/80738318-1d472f80-8b15-11ea-9bcd-ad155ff6a42e.png)

**Comment by plouc** [comment]
@joostdecock not yet, I'll try to release a minor version along with a website update asap.
