### ISSUE TITLE
nivo/core should be a peer dependency

### ISSUE THREAD

**Issue by arcanis** [plouc/nivo#879]
**Describe/explain the bug**
The component packages are currently depending on `nivo/core` through regular dependencies. I don't believe this is what you want, because it means that due to how package managers work, each component may have its own instance of the core (for example if the top-level project depends on a different core version that the components).

To make it worse, this triggers an infinite recursion in Yarn 2 due to the way peer dependencies are resolved (more details here: https://github.com/yarnpkg/berry/issues/901).

**How to fix**
All packages should reference `nivo/core` through a peer dependency. As a first step, if that can't be done for all packages, please at least do it for `nivo/tooltip` - it's listed as a dependency of `nivo/core`, so the regular dependency loop between `tooltip` and `core` is what's causing Yarn to go haywire.

**Comment by wyze** [comment]
With the latest version we removed the circular dependencies between core and tooltip. I was able to start a fresh Next project and add a bar chart without issue.

We can look into moving `core` to peer dependencies in the rest of the packages as well.
