### ISSUE TITLE
feature request: sunburst labels similar to pie

### ISSUE THREAD

**Issue by knackjax** [plouc/nivo#88]
labels for slides and radials similar to pie

**Comment by taschetto** [comment]
+1

**Comment by maithuvenkatesh** [comment]
+1

**Comment by KasraTabrizi** [comment]
+1

**Comment by andriuss** [comment]
+1

**Comment by ptitpioul** [comment]
bump

**Comment by Nathaniel-Fernandes** [comment]
bump

**Comment by plouc** [comment]
Arc labels have been implemented, there's no plan to support the radial labels, supporting them in a sunburst would be pretty complicated and I guess we won't get good results. Pie and Sunburst are now using the exact same components/props for arc labels (previously called slice labels).

This is gonna be available in the next release (no ETA yet, sorry).
