### ISSUE TITLE
Existing component suited to creating Funnel Charts?

### ISSUE THREAD

**Issue by ericsoco** [plouc/nivo#881]
**Is your feature request related to a problem? Please describe.**
A standard form for visualizing a single value that changes (often shrinks) as it progresses through multiple steps is a [Funnel Chart](https://infogram.com/examples/charts/funnel-chart). This is especially useful in BI contexts.

**Describe the solution you'd like**
Support for [Funnel Charts](https://infogram.com/examples/charts/funnel-chart)

**Describe alternatives you've considered**
Didn't see any chart forms currently supported by Nivo that would lend themselves to this. Some other charting libs offer Funnel Charts, though not all.

**Additional context**
@plouc mentioned on Discord that there are no plans to add support for Funnel Charts right now but that PRs are welcome. Filing this feature request just so others can find it and know the status.

**Comment by plouc** [comment]
@ericsoco it's been implemented in https://github.com/plouc/nivo/pull/1001 and will be available in the next release

**Comment by ericsoco** [comment]
\o/
unexpected late birthday gift 🎁🎁🎁
Thanks Raphael!

**Comment by plouc** [comment]
Happy birthday then 🎂 

I've created a small demo using it combined with other chart types:

![funnel-small-multiples-demo](https://user-images.githubusercontent.com/501642/84958702-e4046680-b138-11ea-9fcd-7d547a267963.gif)

I will add it to the stories when I have more time.

**Comment by PriyaJainDev** [comment]
@plouc Hello. Is there any way we can use this chart in our code officially soon?

**Comment by onionhammer** [comment]
Any update on this? This looks like exactly what we need!

**Comment by rickvian** [comment]
looking forward for the release!

**Comment by cor1** [comment]
@plouc any idea on the release date for the next release that includes this? Love the library btw

**Comment by paulgodfrey** [comment]
@plouc looks awesome :) any update on when this might make it into a RC?

**Comment by arielmeneses** [comment]
@plouc thanks for this just a question in your demo you have these headers for each separator but I cannot find the way to do that, is there a easy way to do it?

**Comment by hmaurer** [comment]
@arielmeneses they were implemented outside of the funnel chart, c.f. https://github.com/plouc/nivo/blob/master/packages/funnel/stories/clustering.stories.js (with css grid)
