### ISSUE TITLE
Line Graph with Time X-Axis -- Skipping Times

### ISSUE THREAD

**Issue by NickBeukema** [plouc/nivo#885]
I'm using the line graph to represent stock information, and over the weekends there are no data points (Due to stock market closing on Friday evening, and opening Monday morning). Curious if there's a way to utilize the time axis feature in Nivo while skipping weekends, or just any days that there's missing data for?

I end up with long lines connecting the data over the weekends.

I'm also wanting to display a point for each hour, so I can't just bucket in the points to their individual days either.

Let me know if this makes sense, and if it's possible with this framework. Thanks!

**Comment by JonHannah** [comment]
There's an example of leaving holes in data in the story book [here](https://nivo.rocks/storybook/?path=/story/line--holes-in-data).

I achieved the same effect with a time x-axis by adding null entries at the start and end of data periods, e.g. (by day rather than hour for illustration):

```
data={[
  {
    id: 'Share price',
    data: [
      { x: '2020-03-12', y: 100 },
      { x: '2020-03-13', y: 101 },
      { x: '2020-03-13', y: null },
      { x: '2020-03-16', y: null },
      { x: '2020-03-16', y: 98 },
    ],
  },
```

**Comment by DipakDA** [comment]
I have a similar problem statement.

Do we have any solution for this?

**Comment by nikhil-ravi** [comment]
Is there a solution to this yet? I would like to do the same, if a time index does not exist in the dataset, I would like to skip it in the axis (Mo, Tu, We, Th, Fr, Mo,...). 

@NickBeukema @DipakDA, what did you folk end up doing?

**Comment by plouc** [comment]
So, yes, the solution is to [insert null values](https://nivo.rocks/storybook/?path=/story/line--holes-in-data).

@AChangXD, what do you mean by "a blank area"?

**Comment by plouc** [comment]
@AChangXD, I see, I thought it was just about having holes, yes, it'll be an issue for time scale, if you use another type of scale, you could probably fake a non-linear time.

**Comment by plouc** [comment]
Hum, right, this might be difficult then, especially if you have unpredictable holes.

**Comment by plouc** [comment]
You could use a linear scale, as it'll preserve an order, assigning a number to each data point, but then you'll have to override tooltips and axes to get the time value displayed...
