### ISSUE TITLE
Point label text color

### ISSUE THREAD

**Issue by janvarsa** [plouc/nivo#888]
Is it possible to change the point label text color? For example, if I have a chart with a black background, I would want the point label text to be white.

**Comment by plouc** [comment]
@janvarsa, yes, this is what happens when you go to http://localhost:8000/line/ and switch to dark mode. you can pass a theme using the following structure:

```
theme={{
    dots: {
        text: {
            fill: '#ffffff',
        },
    },
}}
```

**Comment by ukuhnhardt** [comment]
What is 
```
theme: {
  labels: {
    text: {
	fill: token("color.text")
    }
  },
}
```
for then?

**Comment by plouc** [comment]
@ukuhnhardt, it affects labels, which depends on the chart type, for example the value of the bars in a bar chart.
