### ISSUE TITLE
Warning: Failed prop type: The prop `width` is marked as required in `withPropsOnChange(defaultProps(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Bar)))))))))`, but its value is `undefined`.

### ISSUE THREAD

**Issue by sw-yx** [plouc/nivo#89]
Trying to do a basic bar chart and i get this scary looking error:

Warning: Failed prop type: The prop `width` is marked as required in `withPropsOnChange(defaultProps(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Bar)))))))))`, but its value is `undefined`.

my code is at: <https://glitch.com/edit/#!/nivo-test?path=client/index.js>

```
import React from "react";
import axios from "axios";
import { Bar } from "nivo";

export default class App extends React.Component {
  constructor() {
    super();
    this.state = { data: [] };
  }
  componentDidMount() {
    const apiarray = Array(10)
      .fill(0)
      .map(i =>
        axios
          .get("https://swapi.co/api/species/?format=json&page=" + (i + 1))
          .then(x => x.data.results)
      );
    console.log("apiarray", apiarray);
    Promise.all(apiarray).then(resultarr => {
      const x = [].concat.apply([], resultarr);
      const parseddata = x
        .filter(x => x.average_lifespan != "unknown")
        .map(({ name, average_lifespan }) => ({
          name,
          average_lifespan: Number(average_lifespan)
        }));
      console.log("flattened results", parseddata);
      this.setState({ data: parseddata });
    });
  }
  render() {
    return (
      <div>
        {JSON.stringify(this.state.data)}
        {this.state.data.length && (
          <Bar
            data={this.state.data}
            keys={["average_lifespan"]}
            indexBy="name"
          />
        )}
      </div>
    );
  }
}
```

what am i doing wrong?

**Comment by plouc** [comment]
You're using `Bar` instead of `ResponsiveBar`, so the dimensions have to be defined.

**Comment by sw-yx** [comment]
ok, where do i define them? the docs for `Bar` say that only the `data` prop is required. i think that is outdated now?

**Comment by plouc** [comment]
Humm, you're right, I've updated the property documentation system, it seems some props are missing :/

BTW, you define them as top level props `width={600} height={450}`

**Comment by sw-yx** [comment]
I added width and height props and now they work! thank you.

```

          <Bar
            width={100}
            height={100}
            data={this.state.data}
            keys={["average_lifespan"]}
            indexBy="name"
          />
```

![image](https://user-images.githubusercontent.com/6764957/33003221-50b7c21a-cd87-11e7-8328-66366a700e0f.png)

**Comment by plouc** [comment]
YW, you actually spotted a bug on the demo website, thank you :)

**Comment by plouc** [comment]
https://github.com/plouc/nivo-website/blob/master/src/components/charts/bar/props.js#L45, it's there but not displayed

**Comment by sw-yx** [comment]
ya i think i looked for it in the docs and couldnt find it so i panicked.

in general i think the docs need beginner examples before the super fancy here-are-all-the-options demos. i'm sure you'll get there :)

**Comment by plouc** [comment]
That was the purpose of the [storybook](http://nivo.rocks/storybook/) but I have to find some kind of plugin to show the corresponding code

**Comment by sw-yx** [comment]
strange that someone hasn't made it yet. closest i can find is https://github.com/storybooks/storybook/tree/master/addons/info (i dont really know storybook yet)
