### ISSUE TITLE
Show tooltip programmatically

### ISSUE THREAD

**Issue by felipeinfantino** [plouc/nivo#890]
Hello, is it possible to show/hide tooltip programmatically in a line component?

Use case: 
I have a table and below a line graph. I want to show the tooltip in the graph when the mouse is on the table. 

If there is a way to trigger the rendering with the id would be awesome. Thanks and great job with this library.

**Comment by litewarp** [comment]
So I kind of implemented something similar to what you are asking for by extrapolating from the [Synchronized Plot Example for the ScatterPlot graph](https://nivo.rocks/storybook/?path=/story/scatterplot--synchronizing-charts)

In short, you need to essentially construct a second list with each item using the same id that it would have on a graph nodes. In the scatterplot this is in the form of "category.2." Once you can sync the ids, you can then send the onMouseMove and onMouseLeave callbacks to the second list and it should give you the ability to change the plotPoint render on the chart.  In the storybook example, the size of the plotPoint changes when hovering on one of the charts. I haven't tried this, but at least the scatterplot exposes the renderNode prop, so you can vary the node presentation based on the callback per the example. 

Hope this helps!
