### ISSUE TITLE
@nivo/scatterplot doesn't pass theme to custom tooltip

### ISSUE THREAD

**Issue by CharlieMartell** [plouc/nivo#892]
**Describe/explain the bug**
In other Visualization types (ie: bar) passing a custom tooltip as a functional component receives theme as a prop, Scatterplot only passes node. 

Here are the props it receives: 
```
{
  "node": {
    "index": 54,
    "id": "count.54",
    "x": 1054,
    "y": 0,
    "data": {
      "x": 1991,
      "y": 18,
      "id": "count.54",
      "serieId": "count",
      "formattedX": 1991,
      "formattedY": "18"
    },
    "size": 9,
    "style": {
      "color": "#1f77b4"
    }
  }
}
```

**To Reproduce**
https://codesandbox.io/s/nivo-scatterplot-bug-demo-wyvve

1. Hover over a point and see what props the tooltip gets

**Expected behavior**
Tooltip should receive the theme in the props, like other visualization types so the tooltip can be customized

**Comment by plouc** [comment]
@CharlieMartell, that's because the theme is now available in a dedicated context, you can use the following code to retrieve it:

```
import { useTheme } from '@nivo/core'

// inside your custom tooltip component
const theme = useTheme()
```
