### ISSUE TITLE
Treemap - Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by pomber** [plouc/nivo#894]
Hi!

I'm unable to use Treemap in interactive mode. When the user hovers the chart it disappears with this error:

```
nivo-tooltip.esm.js:160 Uncaught TypeError: Cannot read property 'tooltip' of undefined
    at nivo-tooltip.esm.js:160
```

The error comes from this line in BasicTooltip:
https://github.com/plouc/nivo/blob/cf0fd6bdaacd36edfacbb951a036de19ce374aae/packages/tooltip/src/components/BasicTooltip.js#L27

I have this error in a NextJS project, so maybe it's related to SSR because I couldn't reproduce it with a normal CRA CodeSandbox.

A minimal nextjs project to reproduce the issue:
```json
// package.json
{
  "dependencies": {
    "@nivo/treemap": "0.61.0",
    "@nivo/stream": "0.61.0",
    "next": "^9.3.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```

```jsx
// pages/index.js
import React from "react";
import { TreeMap } from "@nivo/treemap";

export default function HomePage() {
  return (
    <TreeMap
      width={400}
      height={400}
      root={{
        id: "x",
        children: [
          { id: "a", value: 2 },
          { id: "b", value: 3 },
          { id: "c", value: 5 },
          { id: "d", value: 8 }
        ]
      }}
    />
  );
}
```

**Note that the package json also has a dependency for `@nivo/stream`.** The strange thing is that TreeMap works fine until I add another `@nivo` dependency. After I add another dependency it fails, even if I don't import the new dep.

I tried different combinations of versions but couldn't make it work, any idea what could be the problem?

**EDIT** 
If I go back to version 0.59 it works
```json
    "@nivo/treemap": "0.59.0",
    "@nivo/stream": "0.59.0",
```

**Comment by epicfaace** [comment]
Try wrapping your code in a `ThemeProvider` with theme equal to `{}` as mentioned here (https://github.com/plouc/nivo/issues/308#issuecomment-542261857) -- this solved a similar problem for me.
