### ISSUE TITLE
Is there a way to limit a marker size on x axis in a Responsive Bar Char?

### ISSUE THREAD

**Issue by RayanXY** [plouc/nivo#895]
I would to put the marker as limit for my application (a feedback for the user) but the marker takes the whole chart, is there a way to set where to begin and end as the exemple bellow?
![Exemple](https://user-images.githubusercontent.com/28001304/76761819-da9ce400-676e-11ea-9be0-120c81f1e478.png)

**Comment by plouc** [comment]
@RayanXY, short answer, you cannot :/ However you can use an extra layer to achieve the same result, using the `layers` property and adding an extra component.
