### ISSUE TITLE
prop for rendering responsive wrapper even if height and width are 0

### ISSUE THREAD

**Issue by jshawl** [plouc/nivo#897]
**Is your feature request related to a problem? Please describe.**

I'm wanting to write a functional test that requests some data from an API and then asserts some amount of bars are present.

Currently, my tests show `<div style='height: 100%; width: 100%'></div>` instead of `<div>...some svg that I can query on here</div>`

I've narrowed it down to this line: https://github.com/plouc/nivo/blob/cf0fd6bdaacd36edfacbb951a036de19ce374aae/packages/core/src/components/ResponsiveWrapper.js#L28

**Describe the solution you'd like**

I would love to be able to pass a prop to a `ResponsiveWrapper`, like:

```
<ResponsiveLine alwaysRender={true} {...props} />
```

and then inside of `ResponsiveWrapper`:

```
(shouldRender || this.props.alwaysRender) && {this.props.children}
```

**Describe alternatives you've considered**
I considered just writing my own responsive wrapper that basically copies your implementation, but omits the `shouldRender &&` and just  always renders the children.

**Additional context**

I'm interested in sending in a PR for this but wanted to see if you're interested in this before I do that :) thanks!

**Comment by jhbalestrin** [comment]
+1 for this, i'm on the same issue here.

**Comment by ErikGMatos** [comment]
+1 for this, i'm on the same issue here

**Comment by ErikGMatos** [comment]
here I am also in the same problem .... did anyone get any alternative for this?

**Comment by russmatney** [comment]
I was able to work around this with [this SO post](https://stackoverflow.com/questions/66657968/resizeobserver-api-testing-jest) and the (linked from there) [useMeasure tests](https://github.com/streamich/react-use/blob/master/tests/useMeasure.test.ts#L42):

```ts
describe(SomeBarChartComponent.name, () => {
  // set up a listener so we can force the width/height
  // this is required to get the chart to render in its ResponsiveWrapper
  let listener: ((rect: any) => void) | undefined = undefined;
  (window as any).ResizeObserver = class ResizeObserver {
    constructor(ls: any) {
      listener = ls;
    }
    observe() {}
    disconnect() {}
  };

  describe("passed some data", () => {
    it("renders something", async () => {
      render(<SomeBarChartComponent data={inputData} />);

      act(() => {
        listener!([
          {
            contentRect: {
              x: 1,
              y: 2,
              width: 200,
              height: 200,
              top: 100,
              bottom: 0,
              left: 100,
              right: 0,
            },
          },
        ]);
      });

      await screen.findByText(/some-text-in-the-chart/i);
    });
  });
});

```

**Comment by ErikGMatos** [comment]
Do I just need the ResizeObservable module?

**Comment by ErikGMatos** [comment]
> I was able to work around this with [this SO post](https://stackoverflow.com/questions/66657968/resizeobserver-api-testing-jest) and the (linked from there) [useMeasure tests](https://github.com/streamich/react-use/blob/master/tests/useMeasure.test.ts#L42):
> 
> ```ts
> describe(SomeBarChartComponent.name, () => {
>   // set up a listener so we can force the width/height
>   // this is required to get the chart to render in its ResponsiveWrapper
>   let listener: ((rect: any) => void) | undefined = undefined;
>   (window as any).ResizeObserver = class ResizeObserver {
>     constructor(ls: any) {
>       listener = ls;
>     }
>     observe() {}
>     disconnect() {}
>   };
> 
>   describe("passed some data", () => {
>     it("renders something", async () => {
>       render(<SomeBarChartComponent data={inputData} />);
> 
>       act(() => {
>         listener!([
>           {
>             contentRect: {
>               x: 1,
>               y: 2,
>               width: 200,
>               height: 200,
>               top: 100,
>               bottom: 0,
>               left: 100,
>               right: 0,
>             },
>           },
>         ]);
>       });
> 
>       await screen.findByText(/some-text-in-the-chart/i);
>     });
>   });
> });
> 
> ```

Do I just need the ResizeObservable module? Then I can test my graph, right?

**Comment by russmatney** [comment]
Somewhat related, you may want to disable the animations, like nivo's own test suite: 
``` ts
import { Globals } from "@react-spring/web";

beforeAll(() => {
  Globals.assign({ skipAnimation: true });
});

afterAll(() => {
  Globals.assign({ skipAnimation: false });
});
```

**Comment by ErikGMatos** [comment]
thank you very much,  I will try this and then come back here to tell if work me.

**Comment by ErikGMatos** [comment]
I'm came back, now to tell that for me worked like a charm. I going to leave here the example of my code.
Thank you @russmatney for help me.

https://gist.github.com/ErikGMatos/20192d0ee2815a14e8516c16002c6422

https://user-images.githubusercontent.com/29432413/174338237-848d4003-5b37-4cf0-aef4-2b9a645b0e0e.mov
