### ISSUE TITLE
CartesianMarkerProps legend position

### ISSUE THREAD

**Issue by Arminkhodaei** [plouc/nivo#898]
Hi,

First of all, Thanks for all of the efforts. Nice job!
My question is about `CartesianMarkers` props, and hopefully, it's not duplicated. Is there any reason for not exposing legend position props (like `legendPosition` or `legendOffsetY`) in the related propTypes and the typescript implementation?
Even they have been used in the below storybook:

https://nivo.rocks/storybook/?path=/story/bar--diverging-stacked

Best,

**Comment by DarkEye123** [comment]
I have same question, this just seems like missing impl. Typescript makes problem from that

**Comment by Arminkhodaei** [comment]
I can add the types If they are just missing and the owners agree on that. However, I already solved my problem in another way. I'm not still sure if it's been intentional or not.

**Comment by Arminkhodaei** [comment]
I don't know if this issue is already solved or not. Anyway, I solved my problem in a different way, and since we haven't had any answer on the thread I will close the issue. Of course, feel free to reopen it if you encountered the same problem.
