### ISSUE TITLE
Legends prop is missing in @nivo/geo package type definitions

### ISSUE THREAD

**Issue by elias-garcia** [plouc/nivo#905]
Hi! I've just found that `legends` prop is missing in the `@nivo/geo` package type definitions. You can check it out in the type definitions file for the module [here](https://github.com/plouc/nivo/blob/master/packages/geo/index.d.ts#L98).

I can help making a PR if needed, thanks!

**Comment by teddybee** [comment]
I have run into this with the Cholorepth package as well.

**Comment by wyze** [comment]
@elias-garcia Sorry for the late response, but PR would be most appreciated!
