### ISSUE TITLE
[Canvas components] allow to get the canvas 

### ISSUE THREAD

**Issue by oorestisime** [plouc/nivo#906]
**Is your feature request related to a problem? Please describe.**
The problem is to export graphs into png 

**Describe the solution you'd like**
A neat way to export canvas is to use `toDataURL` web api of canvas. To do this I need to be able to access the canvas. The solutions i am seeing are:

* allow users to use ref and forward it to canvas. 
* if this is not possible because of how refs are used internally then provide a function getCanvas that gives back the current canvas ref
* worst solution, allow user to add an id tag that will be then able to query using `document.getElementById`

**Describe alternatives you've considered**
Haven't considered but open to suggestions

**Additional context**
I am willing to do the changes myself via a PR, just interested in knowing what an acceptable solution is to you so i don't do this in vein :)

And if you arrived here, thanks for maintaining this awesome library

**Comment by Gwillison415** [comment]
+1  My Outfit is considering this library based on criteria like export/download features. There is a [related response](https://github.com/plouc/nivo/issues/698#issuecomment-559076455) that speaks to this also

**Comment by plouc** [comment]
@oorestisime, thank you for willing to contribute, and sorry for the late reply, I guess [`forwardRef`](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components) could work to get the canvas.

**Comment by oorestisime** [comment]
Awesome thanks! i ll have some time later this week to work on this!

**Comment by aselawijesinghe** [comment]
@oorestisime were you able to work on this idea? It seems to be a much needed functionality for me as well.

**Comment by oorestisime** [comment]
Unfortunately no, covid happened lol. i plan to get to it but can't commit to when. But feel free to do this if you need it asap

**Comment by shadiramadan** [comment]
@aselawijesinghe @oorestisime Did either of you get to this?

**Comment by oorestisime** [comment]
Nope sorry still couldn't make time for this. go ahead :)

**Comment by wjes** [comment]
+1 I'm also in the need for this functionality to insert the image into a PDF, sadly I'm too new to React to implement the solution

**Comment by bobylito** [comment]
Hi everybody,

I'm working with the Orbit team (@phacks and @dzello) on this topic. Thanks to the earlier discussion, I have something working already for the Line chart (see https://github.com/orbit-love/nivo/commit/8bd3a7e92f9c9ac91f7623054bdc3757af796651)

I'd like your feedback on the solution:
 - am I doing something too much with the refs? 😅
 - do you think there is a way to generalize the solution to all the charts? (I'm OK with custom code everywhere too)

Right now we don't need charts beyond the lines and bars, does it make sense to provide this feature to all canvas based components? Would a PR with only the lines and bars be accepted?

Thanks for your time :)

**Comment by wyze** [comment]
> Right now we don't need charts beyond the lines and bars, does it make sense to provide this feature to all canvas based components?

Yes, we would want it to be consistent.

> Would a PR with only the lines and bars be accepted?

Yes.

If the solution you linked to works, we can open a separate umbrella issue to update the rest of the canvas components throughout the library with the same functionality.
