### ISSUE TITLE
Property 'colorBy' does not exist on type 'IntrinsicAttributes & BarChartProps & { children?: ReactNode; }

### ISSUE THREAD

**Issue by mahatosourav91** [plouc/nivo#909]
`colorBy` prop is missing on the bar types definition (https://github.com/plouc/nivo/blob/98a4f4394479c0d61c0f7c8ee7a52ce0b380b5f9/packages/bar/index.d.ts)

**Expected behavior**
`colorBy` props should be available.

**Comment by helt** [comment]
is addressed by https://github.com/plouc/nivo/pull/904

**Comment by wyze** [comment]
This is deprecated, see here: https://github.com/plouc/nivo/pull/904#issuecomment-626407337
