### ISSUE TITLE
'key' issue in Line graph with null values in data

### ISSUE THREAD

**Issue by andreas-groos** [plouc/nivo#91]
Commit #81 was intended to enable linecharts with missing data points (nulls). It works but there are certain conditions that create duplicate keys which leads to a lot of these errors:
![image](https://user-images.githubusercontent.com/19787368/33236912-1095339e-d218-11e7-8f09-dd50ef9a5f46.png)
Because of the flattening of children the line between dots is not being drawn even though it should.
![image](https://user-images.githubusercontent.com/19787368/33236920-510db6da-d218-11e7-9bf8-767c48100e47.png)
If animate={true} there is a 'runaway' error condition and  errors go into the thousands within seconds, with animate={false} errors only occur on prop change.
Again, it only happens if multiple lines are drawn i.e. 
`
[  { id: 19, 
    data: [{x: .....,
               y: .....},
             .....],
   {id: 30.
    data: [....]}
]
`
I'm fairly certain I'm passing the correct props and I believe that passing null as certain y's leads to the duplicate key issue.

**Comment by andreas-groos** [comment]
In this situation I manually added ResponsiveLine from the latest github package:
`import { ResponsiveLine } from '../nivo-github/components/charts/line;`
If I switch to the npm version it complains about the null values being passed and renders them as 0 but the 'flatten children' error doesn't occur
.

**Comment by plouc** [comment]
Hi @andreas-groos, thank you for the feedback, however I don't think it's an issue as it's just not supported for now :), maybe it could be more useful if you comment the ongoing PR => https://github.com/plouc/nivo/pull/81.

**Comment by plouc** [comment]
Sorry… forgot it has been merged, will try to have a look at this when I find some time :)

**Comment by andreas-groos** [comment]
Thanks, I can see that it is an edge case, I'll keep following and see what
comes out of it. Thanks!

**Comment by ahtohbi4** [comment]
@andreas-groos, could you write an example of the data which causes the warnings? I tried to reproduce it in a storybook, but I couldn't.

**Comment by andreas-groos** [comment]
@ahtohbi4  Sorry for the delay, I only saw this now. This is the data props and I get the errors plus only the 'dots' get rendered, not the lines in between:
![image](https://user-images.githubusercontent.com/19787368/33447889-615377b0-d5b9-11e7-94a2-09d392ef89d2.png)
`[
  {
    "id": "15",
    "data": [
      {
        "x": "01-01-00",
        "y": null
      },
      {
        "x": "01-02-00",
        "y": null
      },
      {
        "x": "01-03-00",
        "y": null
      },
      {
        "x": "01-04-00",
        "y": null
      },
      {
        "x": "01-05-00",
        "y": null
      },
      {
        "x": "01-06-00",
        "y": null
      },
      {
        "x": "01-07-00",
        "y": null
      },
      {
        "x": "01-08-00",
        "y": null
      },
      {
        "x": "01-09-00",
        "y": null
      },
      {
        "x": "10-10-00",
        "y": 13
      },
      {
        "x": "01-11-00",
        "y": null
      },
      {
        "x": "01-12-00",
        "y": null
      },
      {
        "x": "13-01-01",
        "y": 3.3
      },
      {
        "x": "14-02-01",
        "y": null
      },
      {
        "x": "10-03-01",
        "y": 6.53
      },
      {
        "x": "07-04-01",
        "y": 8.4
      },
      {
        "x": "05-05-01",
        "y": 12.8
      },
      {
        "x": "09-06-01",
        "y": 21.12
      },
      {
        "x": "14-07-01",
        "y": 21.4
      },
      {
        "x": "11-08-01",
        "y": 22.37
      },
      {
        "x": "08-09-01",
        "y": 18.23
      },
      {
        "x": "06-10-01",
        "y": 14.73
      },
      {
        "x": "03-11-01",
        "y": 8.97
      },
      {
        "x": "08-12-01",
        "y": 4.8
      },
      {
        "x": "12-01-02",
        "y": 5.3
      },
      {
        "x": "09-02-02",
        "y": 3.3
      },
      {
        "x": "09-03-02",
        "y": 5.2
      },
      {
        "x": "13-04-02",
        "y": 11.2
      },
      {
        "x": "11-05-02",
        "y": 10.6
      },
      {
        "x": "08-06-02",
        "y": 17.97
      },
      {
        "x": "13-07-02",
        "y": 23.5
      },
      {
        "x": "10-08-02",
        "y": 23.13
      },
      {
        "x": "07-09-02",
        "y": 16
      },
      {
        "x": "05-10-02",
        "y": 12.2
      },
      {
        "x": "02-11-02",
        "y": 5.1
      },
      {
        "x": "07-12-02",
        "y": 3.13
      },
      {
        "x": "04-01-03",
        "y": 5.83
      },
      {
        "x": "01-02-03",
        "y": 7.3
      },
      {
        "x": "01-03-03",
        "y": 6.2
      },
      {
        "x": "05-04-03",
        "y": 4.57
      },
      {
        "x": "03-05-03",
        "y": 8.17
      },
      {
        "x": "07-06-03",
        "y": 13.6
      },
      {
        "x": "12-07-03",
        "y": 21.9
      },
      {
        "x": "09-08-03",
        "y": 20.1
      },
      {
        "x": "06-09-03",
        "y": 20.5
      },
      {
        "x": "04-10-03",
        "y": 15.6
      },
      {
        "x": "08-11-03",
        "y": 8.63
      },
      {
        "x": "06-12-03",
        "y": 7.73
      },
      {
        "x": "03-01-04",
        "y": 4
      },
      {
        "x": "06-02-04",
        "y": 5.2
      },
      {
        "x": "06-03-04",
        "y": 7.7
      },
      {
        "x": "03-04-04",
        "y": 9.47
      },
      {
        "x": "01-05-04",
        "y": 13.47
      },
      {
        "x": "16-06-04",
        "y": 22.5
      },
      {
        "x": "10-07-04",
        "y": 21.37
      },
      {
        "x": "07-08-04",
        "y": 20.4
      },
      {
        "x": "11-09-04",
        "y": 18.2
      },
      {
        "x": "09-10-04",
        "y": 15.17
      },
      {
        "x": "06-11-04",
        "y": 6.6
      },
      {
        "x": "11-12-04",
        "y": 5.83
      },
      {
        "x": "15-01-05",
        "y": 5.2
      },
      {
        "x": "12-02-05",
        "y": 6.4
      },
      {
        "x": "12-03-05",
        "y": 11.43
      },
      {
        "x": "09-04-05",
        "y": 7.6
      },
      {
        "x": "07-05-05",
        "y": 10.7
      },
      {
        "x": "11-06-05",
        "y": 13.4
      },
      {
        "x": "09-07-05",
        "y": 21.97
      },
      {
        "x": "06-08-05",
        "y": 26.17
      },
      {
        "x": "10-09-05",
        "y": 18.27
      },
      {
        "x": "08-10-05",
        "y": 13.53
      },
      {
        "x": "06-11-05",
        "y": 11.47
      },
      {
        "x": "03-12-05",
        "y": 6.27
      },
      {
        "x": "07-01-06",
        "y": 7.87
      },
      {
        "x": "04-02-06",
        "y": 7.53
      },
      {
        "x": "04-03-06",
        "y": 5.27
      },
      {
        "x": "08-04-06",
        "y": 7.87
      },
      {
        "x": "13-05-06",
        "y": 11.3
      },
      {
        "x": "10-06-06",
        "y": 17.57
      },
      {
        "x": "08-07-06",
        "y": 21.87
      },
      {
        "x": "05-08-06",
        "y": 22.93
      },
      {
        "x": "09-09-06",
        "y": 19.1
      },
      {
        "x": "07-10-06",
        "y": 12.53
      },
      {
        "x": "04-11-06",
        "y": 10.03
      },
      {
        "x": "02-12-06",
        "y": 2.27
      },
      {
        "x": "06-01-07",
        "y": 2.57
      },
      {
        "x": "03-02-07",
        "y": 3.4
      },
      {
        "x": "03-03-07",
        "y": 6.27
      },
      {
        "x": "07-04-07",
        "y": 13.4
      },
      {
        "x": "05-05-07",
        "y": 12.23
      },
      {
        "x": "09-06-07",
        "y": 18.83
      },
      {
        "x": "07-07-07",
        "y": 26.1
      },
      {
        "x": "04-08-07",
        "y": 23.57
      },
      {
        "x": "08-09-07",
        "y": 19.97
      },
      {
        "x": "13-10-07",
        "y": 12.9
      },
      {
        "x": "03-11-07",
        "y": 9
      },
      {
        "x": "01-12-07",
        "y": 4.1
      },
      {
        "x": "05-01-08",
        "y": 7.7
      },
      {
        "x": "09-02-08",
        "y": 4.13
      },
      {
        "x": "01-03-08",
        "y": 6.87
      },
      {
        "x": "05-04-08",
        "y": 9.33
      },
      {
        "x": "03-05-08",
        "y": 10.5
      },
      {
        "x": "07-06-08",
        "y": 18.17
      },
      {
        "x": "12-07-08",
        "y": 25.1
      },
      {
        "x": "02-08-08",
        "y": 23.27
      },
      {
        "x": "06-09-08",
        "y": 20.5
      },
      {
        "x": "04-10-08",
        "y": 16.8
      },
      {
        "x": "01-11-08",
        "y": 12.23
      },
      {
        "x": "01-12-08",
        "y": null
      },
      {
        "x": "01-01-09",
        "y": null
      },
      {
        "x": "07-02-09",
        "y": 6.8
      },
      {
        "x": "09-03-09",
        "y": 6.7
      },
      {
        "x": "04-04-09",
        "y": 10.03
      },
      {
        "x": "01-05-09",
        "y": 11.33
      },
      {
        "x": "12-06-09",
        "y": 18.37
      },
      {
        "x": "13-07-09",
        "y": 23.8
      },
      {
        "x": "01-08-09",
        "y": 23.3
      },
      {
        "x": "12-09-09",
        "y": 20.4
      },
      {
        "x": "03-10-09",
        "y": 13.87
      },
      {
        "x": "11-11-09",
        "y": 10.2
      },
      {
        "x": "01-12-09",
        "y": null
      },
      {
        "x": "01-01-10",
        "y": null
      },
      {
        "x": "01-02-10",
        "y": null
      },
      {
        "x": "06-03-10",
        "y": 7.5
      },
      {
        "x": "10-04-10",
        "y": 10.5
      },
      {
        "x": "08-05-10",
        "y": 10
      },
      {
        "x": "05-06-10",
        "y": 10.4
      },
      {
        "x": "10-07-10",
        "y": 21.1
      },
      {
        "x": "07-08-10",
        "y": 20.43
      },
      {
        "x": "11-09-10",
        "y": 16.6
      },
      {
        "x": "01-10-10",
        "y": 19.6
      },
      {
        "x": "06-11-10",
        "y": 11.27
      },
      {
        "x": "01-12-10",
        "y": null
      },
      {
        "x": "01-01-11",
        "y": null
      },
      {
        "x": "01-02-11",
        "y": null
      },
      {
        "x": "12-03-11",
        "y": 6.73
      },
      {
        "x": "09-04-11",
        "y": 5.6
      },
      {
        "x": "14-05-11",
        "y": 10.1
      },
      {
        "x": "11-06-11",
        "y": 9.8
      },
      {
        "x": "09-07-11",
        "y": 13.67
      },
      {
        "x": "13-08-11",
        "y": 20.07
      },
      {
        "x": "10-09-11",
        "y": 18.87
      },
      {
        "x": "15-10-11",
        "y": 14.87
      },
      {
        "x": "12-11-11",
        "y": 8.1
      },
      {
        "x": "01-12-11",
        "y": null
      },
      {
        "x": "01-01-12",
        "y": null
      },
      {
        "x": "01-02-12",
        "y": null
      },
      {
        "x": "10-03-12",
        "y": 7.7
      },
      {
        "x": "14-04-12",
        "y": 7.97
      },
      {
        "x": "05-05-12",
        "y": 9.5
      },
      {
        "x": "09-06-12",
        "y": 17.67
      },
      {
        "x": "14-07-12",
        "y": 23.17
      },
      {
        "x": "11-08-12",
        "y": 22.9
      },
      {
        "x": "08-09-12",
        "y": 20.77
      },
      {
        "x": "13-10-12",
        "y": 14.33
      },
      {
        "x": "09-11-12",
        "y": 8.3
      },
      {
        "x": "01-12-12",
        "y": null
      },
      {
        "x": "01-01-13",
        "y": null
      },
      {
        "x": "01-02-13",
        "y": null
      },
      {
        "x": "09-03-13",
        "y": 7.63
      },
      {
        "x": "13-04-13",
        "y": 13.73
      },
      {
        "x": "11-05-13",
        "y": 18.53
      },
      {
        "x": "08-06-13",
        "y": 26.43
      },
      {
        "x": "13-07-13",
        "y": 22.83
      },
      {
        "x": "10-08-13",
        "y": 22.47
      },
      {
        "x": "07-09-13",
        "y": 22.43
      },
      {
        "x": "12-10-13",
        "y": 11.87
      },
      {
        "x": "09-11-13",
        "y": 8.77
      },
      {
        "x": "01-12-13",
        "y": null
      },
      {
        "x": "01-01-14",
        "y": null
      },
      {
        "x": "01-02-14",
        "y": null
      },
      {
        "x": "07-03-14",
        "y": 9.7
      },
      {
        "x": "19-04-14",
        "y": 16.77
      },
      {
        "x": "09-05-14",
        "y": 15.1
      },
      {
        "x": "14-06-14",
        "y": 20
      },
      {
        "x": "12-07-14",
        "y": 24.17
      },
      {
        "x": "09-08-14",
        "y": 23.77
      },
      {
        "x": "13-09-14",
        "y": 19.4
      },
      {
        "x": "11-10-14",
        "y": 14.6
      },
      {
        "x": "15-11-14",
        "y": 10.13
      },
      {
        "x": "01-12-14",
        "y": null
      },
      {
        "x": "01-01-15",
        "y": null
      },
      {
        "x": "01-02-15",
        "y": null
      },
      {
        "x": "14-03-15",
        "y": 11.87
      },
      {
        "x": "11-04-15",
        "y": 14.77
      },
      {
        "x": "09-05-15",
        "y": 17.4
      },
      {
        "x": "13-06-15",
        "y": 23.63
      },
      {
        "x": "11-07-15",
        "y": 20.73
      },
      {
        "x": "08-08-15",
        "y": 21.93
      },
      {
        "x": "12-09-15",
        "y": 19.6
      },
      {
        "x": "10-10-15",
        "y": 16.3
      },
      {
        "x": "14-11-15",
        "y": 5.4
      },
      {
        "x": "01-12-15",
        "y": null
      },
      {
        "x": "01-01-16",
        "y": null
      },
      {
        "x": "01-02-16",
        "y": null
      },
      {
        "x": "12-03-16",
        "y": 7.03
      },
      {
        "x": "09-04-16",
        "y": 9.2
      },
      {
        "x": "14-05-16",
        "y": 11.43
      },
      {
        "x": "11-06-16",
        "y": 18.2
      },
      {
        "x": "09-07-16",
        "y": 22.33
      },
      {
        "x": "13-08-16",
        "y": 21.3
      },
      {
        "x": "10-09-16",
        "y": 19.2
      },
      {
        "x": "08-10-16",
        "y": 13.33
      },
      {
        "x": "12-11-16",
        "y": 10.33
      },
      {
        "x": "01-12-16",
        "y": null
      },
      {
        "x": "01-01-17",
        "y": null
      },
      {
        "x": "01-02-17",
        "y": null
      },
      {
        "x": "11-03-17",
        "y": 8.67
      },
      {
        "x": "10-04-17",
        "y": 7.4
      },
      {
        "x": "13-05-17",
        "y": 8.5
      },
      {
        "x": "10-06-17",
        "y": 10.57
      },
      {
        "x": "08-07-17",
        "y": 22.17
      },
      {
        "x": "12-08-17",
        "y": 22.37
      },
      {
        "x": "09-09-17",
        "y": 20.73
      },
      {
        "x": "01-10-17",
        "y": null
      },
      {
        "x": "01-11-17",
        "y": null
      },
      {
        "x": "01-12-17",
        "y": null
      }
    ]
  },
  {
    "id": "30",
    "data": [
      {
        "x": "01-01-00",
        "y": null
      },
      {
        "x": "01-02-00",
        "y": null
      },
      {
        "x": "01-03-00",
        "y": null
      },
      {
        "x": "01-04-00",
        "y": null
      },
      {
        "x": "01-05-00",
        "y": null
      },
      {
        "x": "01-06-00",
        "y": null
      },
      {
        "x": "01-07-00",
        "y": null
      },
      {
        "x": "01-08-00",
        "y": null
      },
      {
        "x": "01-09-00",
        "y": null
      },
      {
        "x": "01-10-00",
        "y": null
      },
      {
        "x": "01-11-00",
        "y": null
      },
      {
        "x": "01-12-00",
        "y": null
      },
      {
        "x": "01-01-01",
        "y": null
      },
      {
        "x": "01-02-01",
        "y": null
      },
      {
        "x": "01-03-01",
        "y": null
      },
      {
        "x": "01-04-01",
        "y": null
      },
      {
        "x": "01-05-01",
        "y": null
      },
      {
        "x": "01-06-01",
        "y": null
      },
      {
        "x": "01-07-01",
        "y": null
      },
      {
        "x": "01-08-01",
        "y": null
      },
      {
        "x": "01-09-01",
        "y": null
      },
      {
        "x": "01-10-01",
        "y": null
      },
      {
        "x": "01-11-01",
        "y": null
      },
      {
        "x": "01-12-01",
        "y": null
      },
      {
        "x": "01-01-02",
        "y": null
      },
      {
        "x": "01-02-02",
        "y": null
      },
      {
        "x": "01-03-02",
        "y": null
      },
      {
        "x": "01-04-02",
        "y": null
      },
      {
        "x": "01-05-02",
        "y": null
      },
      {
        "x": "01-06-02",
        "y": null
      },
      {
        "x": "01-07-02",
        "y": null
      },
      {
        "x": "01-08-02",
        "y": null
      },
      {
        "x": "01-09-02",
        "y": null
      },
      {
        "x": "01-10-02",
        "y": null
      },
      {
        "x": "01-11-02",
        "y": null
      },
      {
        "x": "01-12-02",
        "y": null
      },
      {
        "x": "01-01-03",
        "y": null
      },
      {
        "x": "07-02-03",
        "y": 5.17
      },
      {
        "x": "01-03-03",
        "y": null
      },
      {
        "x": "05-04-03",
        "y": null
      },
      {
        "x": "03-05-03",
        "y": 8.97
      },
      {
        "x": "07-06-03",
        "y": 14.1
      },
      {
        "x": "11-07-03",
        "y": 20.7
      },
      {
        "x": "09-08-03",
        "y": 20.1
      },
      {
        "x": "06-09-03",
        "y": 19.9
      },
      {
        "x": "04-10-03",
        "y": 15.8
      },
      {
        "x": "08-11-03",
        "y": 7.9
      },
      {
        "x": "06-12-03",
        "y": 8.2
      },
      {
        "x": "09-01-04",
        "y": 6.87
      },
      {
        "x": "07-02-04",
        "y": 5.17
      },
      {
        "x": "06-03-04",
        "y": 8.13
      },
      {
        "x": "03-04-04",
        "y": 9.1
      },
      {
        "x": "01-05-04",
        "y": 12.8
      },
      {
        "x": "12-06-04",
        "y": 18.2
      },
      {
        "x": "10-07-04",
        "y": 22.17
      },
      {
        "x": "07-08-04",
        "y": 19.87
      },
      {
        "x": "13-09-04",
        "y": 19.07
      },
      {
        "x": "09-10-04",
        "y": 14.8
      },
      {
        "x": "06-11-04",
        "y": 6.3
      },
      {
        "x": "11-12-04",
        "y": 5.6
      },
      {
        "x": "15-01-05",
        "y": 5.2
      },
      {
        "x": "12-02-05",
        "y": 6.37
      },
      {
        "x": "12-03-05",
        "y": 9.6
      },
      {
        "x": "09-04-05",
        "y": 6.4
      },
      {
        "x": "07-05-05",
        "y": 9.6
      },
      {
        "x": "11-06-05",
        "y": 13.27
      },
      {
        "x": "09-07-05",
        "y": 20.9
      },
      {
        "x": "06-08-05",
        "y": 22
      },
      {
        "x": "10-09-05",
        "y": 17.9
      },
      {
        "x": "08-10-05",
        "y": 11.9
      },
      {
        "x": "05-11-05",
        "y": 9.7
      },
      {
        "x": "03-12-05",
        "y": 5.93
      },
      {
        "x": "07-01-06",
        "y": 7.93
      },
      {
        "x": "04-02-06",
        "y": 7.17
      },
      {
        "x": "08-03-06",
        "y": 6.83
      },
      {
        "x": "08-04-06",
        "y": 7.13
      },
      {
        "x": "13-05-06",
        "y": 9.53
      },
      {
        "x": "10-06-06",
        "y": 13.67
      },
      {
        "x": "08-07-06",
        "y": 21
      },
      {
        "x": "05-08-06",
        "y": 21.13
      },
      {
        "x": "09-09-06",
        "y": 18.73
      },
      {
        "x": "07-10-06",
        "y": 11.87
      },
      {
        "x": "04-11-06",
        "y": 10
      },
      {
        "x": "02-12-06",
        "y": 2.47
      },
      {
        "x": "06-01-07",
        "y": 2.63
      },
      {
        "x": "03-02-07",
        "y": 2.7
      },
      {
        "x": "03-03-07",
        "y": 5.4
      },
      {
        "x": "07-04-07",
        "y": 12.9
      },
      {
        "x": "05-05-07",
        "y": 9.9
      },
      {
        "x": "09-06-07",
        "y": 18.15
      },
      {
        "x": "07-07-07",
        "y": 24.27
      },
      {
        "x": "04-08-07",
        "y": 22.33
      },
      {
        "x": "08-09-07",
        "y": 19.47
      },
      {
        "x": "13-10-07",
        "y": 11.83
      },
      {
        "x": "03-11-07",
        "y": 8.87
      },
      {
        "x": "01-12-07",
        "y": 3.3
      },
      {
        "x": "05-01-08",
        "y": 5.07
      },
      {
        "x": "09-02-08",
        "y": 3.5
      },
      {
        "x": "01-03-08",
        "y": 7.9
      },
      {
        "x": "05-04-08",
        "y": 9.43
      },
      {
        "x": "03-05-08",
        "y": 11.17
      },
      {
        "x": "01-06-08",
        "y": null
      },
      {
        "x": "01-07-08",
        "y": null
      },
      {
        "x": "01-08-08",
        "y": null
      },
      {
        "x": "06-09-08",
        "y": 19.53
      },
      {
        "x": "01-10-08",
        "y": null
      },
      {
        "x": "01-11-08",
        "y": 12.33
      },
      {
        "x": "01-12-08",
        "y": null
      },
      {
        "x": "01-01-09",
        "y": null
      },
      {
        "x": "01-02-09",
        "y": null
      },
      {
        "x": "01-03-09",
        "y": null
      },
      {
        "x": "01-04-09",
        "y": null
      },
      {
        "x": "10-05-09",
        "y": 10.17
      },
      {
        "x": "01-06-09",
        "y": null
      },
      {
        "x": "14-07-09",
        "y": 25.2
      },
      {
        "x": "01-08-09",
        "y": null
      },
      {
        "x": "12-09-09",
        "y": 20.1
      },
      {
        "x": "01-10-09",
        "y": null
      },
      {
        "x": "07-11-09",
        "y": 11.3
      },
      {
        "x": "01-12-09",
        "y": null
      },
      {
        "x": "01-01-10",
        "y": null
      },
      {
        "x": "01-02-10",
        "y": null
      },
      {
        "x": "01-03-10",
        "y": null
      },
      {
        "x": "01-04-10",
        "y": null
      },
      {
        "x": "08-05-10",
        "y": 10.13
      },
      {
        "x": "01-06-10",
        "y": null
      },
      {
        "x": "10-07-10",
        "y": 20.53
      },
      {
        "x": "01-08-10",
        "y": null
      },
      {
        "x": "11-09-10",
        "y": 16.63
      },
      {
        "x": "01-10-10",
        "y": null
      },
      {
        "x": "06-11-10",
        "y": 10.5
      },
      {
        "x": "01-12-10",
        "y": null
      },
      {
        "x": "01-01-11",
        "y": null
      },
      {
        "x": "01-02-11",
        "y": null
      },
      {
        "x": "01-03-11",
        "y": null
      },
      {
        "x": "01-04-11",
        "y": null
      },
      {
        "x": "12-05-11",
        "y": 9.33
      },
      {
        "x": "01-06-11",
        "y": null
      },
      {
        "x": "09-07-11",
        "y": 15.57
      },
      {
        "x": "01-08-11",
        "y": null
      },
      {
        "x": "10-09-11",
        "y": 18.9
      },
      {
        "x": "01-10-11",
        "y": null
      },
      {
        "x": "12-11-11",
        "y": 7.7
      },
      {
        "x": "01-12-11",
        "y": null
      },
      {
        "x": "01-01-12",
        "y": null
      },
      {
        "x": "01-02-12",
        "y": null
      },
      {
        "x": "01-03-12",
        "y": null
      },
      {
        "x": "01-04-12",
        "y": null
      },
      {
        "x": "05-05-12",
        "y": 8.63
      },
      {
        "x": "01-06-12",
        "y": null
      },
      {
        "x": "14-07-12",
        "y": 22.53
      },
      {
        "x": "01-08-12",
        "y": null
      },
      {
        "x": "08-09-12",
        "y": 19.83
      },
      {
        "x": "13-10-12",
        "y": 13
      },
      {
        "x": "10-11-12",
        "y": 7.73
      },
      {
        "x": "01-12-12",
        "y": null
      },
      {
        "x": "01-01-13",
        "y": null
      },
      {
        "x": "01-02-13",
        "y": null
      },
      {
        "x": "09-03-13",
        "y": 7.6
      },
      {
        "x": "01-04-13",
        "y": null
      },
      {
        "x": "11-05-13",
        "y": 18.57
      },
      {
        "x": "08-06-13",
        "y": 23.47
      },
      {
        "x": "13-07-13",
        "y": 21.8
      },
      {
        "x": "10-08-13",
        "y": 20.43
      },
      {
        "x": "07-09-13",
        "y": 20
      },
      {
        "x": "12-10-13",
        "y": 11.53
      },
      {
        "x": "09-11-13",
        "y": 7.7
      },
      {
        "x": "01-12-13",
        "y": null
      },
      {
        "x": "01-01-14",
        "y": null
      },
      {
        "x": "01-02-14",
        "y": null
      },
      {
        "x": "08-03-14",
        "y": 7.83
      },
      {
        "x": "19-04-14",
        "y": 14.47
      },
      {
        "x": "10-05-14",
        "y": 14.33
      },
      {
        "x": "14-06-14",
        "y": 19.93
      },
      {
        "x": "12-07-14",
        "y": 23
      },
      {
        "x": "08-08-14",
        "y": 24.87
      },
      {
        "x": "13-09-14",
        "y": 18.97
      },
      {
        "x": "11-10-14",
        "y": 14.67
      },
      {
        "x": "15-11-14",
        "y": 9.63
      },
      {
        "x": "01-12-14",
        "y": null
      },
      {
        "x": "01-01-15",
        "y": null
      },
      {
        "x": "01-02-15",
        "y": null
      },
      {
        "x": "14-03-15",
        "y": 11.87
      },
      {
        "x": "11-04-15",
        "y": 10.6
      },
      {
        "x": "09-05-15",
        "y": 15.8
      },
      {
        "x": "13-06-15",
        "y": 22.5
      },
      {
        "x": "11-07-15",
        "y": 20.2
      },
      {
        "x": "08-08-15",
        "y": 21.2
      },
      {
        "x": "12-09-15",
        "y": 19.8
      },
      {
        "x": "09-10-15",
        "y": 15.6
      },
      {
        "x": "14-11-15",
        "y": 5.5
      },
      {
        "x": "01-12-15",
        "y": null
      },
      {
        "x": "01-01-16",
        "y": null
      },
      {
        "x": "01-02-16",
        "y": null
      },
      {
        "x": "12-03-16",
        "y": 6.53
      },
      {
        "x": "09-04-16",
        "y": 8.8
      },
      {
        "x": "14-05-16",
        "y": 10.97
      },
      {
        "x": "11-06-16",
        "y": 17.1
      },
      {
        "x": "09-07-16",
        "y": 21.2
      },
      {
        "x": "13-08-16",
        "y": 20.9
      },
      {
        "x": "10-09-16",
        "y": 18.43
      },
      {
        "x": "08-10-16",
        "y": 11.9
      },
      {
        "x": "12-11-16",
        "y": 10.5
      },
      {
        "x": "01-12-16",
        "y": null
      },
      {
        "x": "01-01-17",
        "y": null
      },
      {
        "x": "01-02-17",
        "y": null
      },
      {
        "x": "11-03-17",
        "y": 7.57
      },
      {
        "x": "08-04-17",
        "y": 7.3
      },
      {
        "x": "13-05-17",
        "y": 7.3
      },
      {
        "x": "12-06-17",
        "y": 9.4
      },
      {
        "x": "08-07-17",
        "y": 21.47
      },
      {
        "x": "12-08-17",
        "y": 22
      },
      {
        "x": "09-09-17",
        "y": 20.63
      },
      {
        "x": "01-10-17",
        "y": null
      },
      {
        "x": "01-11-17",
        "y": null
      },
      {
        "x": "01-12-17",
        "y": null
      }
    ]
  }
]`

**Comment by andreas-groos** [comment]
I can get rid of the 'flatten children' error by changing Line 55 in LineDots.js to generate a unique key. But the missing line between two consecutive datapoints I can't track down.
![image](https://user-images.githubusercontent.com/19787368/33466490-3aaf77fe-d603-11e7-9dbb-1db11223b874.png)

**Comment by ahtohbi4** [comment]
I have found a difference of `x` values in your data. For example item with value `{ x: "10-10-00", y: <any value> }` exist in the first collection, but was missed in the second one.

How I understand the ideology of the library, dataset for each `Line` should have the same length and should consist of the identical sets of `x` values.

Wrong (your case):

```json
[
  {
    "id": "15",
    "data": [
      { "x": "01-01-00", "y": 5 },
      { "x": "03-01-00", "y": 3 },
      { "x": "04-01-00", "y": null }
    ]
  },
  {
    "id": "30",
    "data": [
      { "x": "01-01-00", "y": 7 },
      { "x": "02-01-00", "y": 12 },
      { "x": "04-01-00", "y": 2 }
    ]
  }
]
```

Correct:

```json
[
  {
    "id": "15",
    "data": [
      { "x": "01-01-00", "y": 5 },
      { "x": "02-01-00", "y": null },
      { "x": "03-01-00", "y": 3 },
      { "x": "04-01-00", "y": null }
    ]
  },
  {
    "id": "30",
    "data": [
      { "x": "01-01-00", "y": 7 },
      { "x": "02-01-00", "y": 12 },
      { "x": "03-01-00", "y": null },
      { "x": "04-01-00", "y": 2 }
    ]
  }
]
```

So, you should fill missed values of `x` in each dataset with `{ "x": <missed value>, "y": null }`.

@plouc, correct me, please.

**Comment by andreas-groos** [comment]
Thanks for paying attention @ahtohbi4 , I'll try it in my case (though it'll take me a bit till I get to it) and report back if that is indeed the issue.

**Comment by plouc** [comment]
@ahtohbi4, you're right 👍, thank you!
