### ISSUE TITLE
Time Scale Line Chart dates off by one

### ISSUE THREAD

**Issue by jcampos8782** [plouc/nivo#911]
Points entered into a line chart using time as the x-axis are being modified and are changing the date to be off by one. For example, a point of "2020-03-22" would be displayed on 3/21, not 3/22. 

**To Reproduce**
This issue is live on the story page:
https://nivo.rocks/storybook/?path=/story/line--time-scale

Notice that the first point in the data set is for 1/1 but the graph is displaying it on 12/31. 

**Expected behavior**
Date is accurate based on provided format

**Screenshots**
![Screen Shot 2020-04-05 at 12 11 27 PM](https://user-images.githubusercontent.com/3411401/78507738-afd2f980-7736-11ea-97d6-785bf4376101.png)

**Comment by mathur7** [comment]
I am experiencing the same issue too.

**Comment by freakyzoidberg** [comment]
Hello, 

I ran into this too, as far as I understand this is due to timezone handling.

By default, the date is interpreted as UTC and displayed in the TZ of your system.

If your input date is already in the local of the system you can configure the **xScale** to not use UTC 

```
    xScale={{
      type: 'time',
      format: '%Y-%m-%d',
      precision: 'day',
      useUTC: false
    }}
```

**Comment by jcampos8782** [comment]
Fantastic. Did not see the useUTC option. Closing the issue. Cheers!
