### ISSUE TITLE
Can not get xScale with time stamp working

### ISSUE THREAD

**Issue by bkriczky** [plouc/nivo#912]
Hello, I am trying to create a graph which uses timestamp that need to be converted to dates. I have been looking around and no answers seems to solve my problem. This is what I have so far

import React from 'react'
import { ResponsiveLine } from '@nivo/line'
import data from '../../api/deviceMock'
import * as time from 'd3-time'
import { timeFormat } from 'd3-time-format'

const DeviceUsage = () => (
   <ResponsiveLine
      data={data}
      margin={{ top: 50, right: 110, bottom: 100, left: 60 }}
      yScale={{ type: 'linear', min: 'auto', max: 'auto', stacked: true, reverse: false }}
      curve="catmullRom"
      axisTop={null}
      axisRight={null}
      xScale={{ "type": "time"}}
      axisBottom={{
         orient: 'bottom',
         tickValues: 'every day',
         tickSize: 3,
         tickPadding: 5,
         tickRotation: 0,
         legend: 'Date',
         legendOffset: 36,
         legendPosition: 'middle',
         format: "%Y-%m-%d"
      }}

And then my data is set up like this

[
  {
    "id": "japan",
    "color": "hsl(309, 70%, 50%)",
    "data": [
      {
        "x": "1999-12-31T16:00:00.000Z",
        "y": 223
      },
      {
        "x": "2000-01-31T16:00:00.000Z",
        "y": 268
      },
      {
        "x": "2000-02-29T16:00:00.000Z",
        "y": 85
      }
    ]
  },
  {
    "id": "france",
    "color": "hsl(257, 70%, 50%)",
    "data": [
      {
        "x": "J1999-12-31T16:00:00.000Z",
        "y": 27
      },
      {
        "x": "2000-01-31T16:00:00.000Z",
        "y": 129
      },
      {
        "x": "Mar",
        "y": "2000-02-29T16:00:00.000Z"
      }
    ]
  },
  {
    "id": "us",
    "color": "hsl(321, 70%, 50%)",
    "data": [
      {
        "x": "1999-12-31T16:00:00.000Z",
        "y": 223
      },
      {
        "x": "2000-01-31T16:00:00.000Z",
        "y": 268
      },
      {
        "x": "2000-02-29T16:00:00.000Z",
        "y": 238
      }
    ]
  },
  {
    "id": "germany",
    "color": "hsl(99, 70%, 50%)",
    "data": [
      {
        "x": "1999-12-31T16:00:00.000Z",
        "y": 223
      },
      {
        "x": "2000-01-31T16:00:00.000Z",
        "y": 268
      },
      {
        "x": "2000-02-29T16:00:00.000Z",
        "y": 238
      }
    ]
  },
  {
    "id": "norway",
    "color": "hsl(135, 70%, 50%)",
    "data": [
      {
        "x": "1999-12-31T16:00:00.000Z",
        "y": 223
      },
      {
        "x": "2000-01-31T16:00:00.000Z",
        "y": 268
      }
    ]
  }
]

I am not really sure what is going wrong here. Any help would be appreciated.
Thanks,

**Comment by mckelveygreg** [comment]
I found this in the source that helped point me in the right direction: 
 that the time scale uses  I ended up setting 2 different specific formatting strings

**Comment by mckelveygreg** [comment]
I found this in the source that helped point me in the right direction:
https://github.com/plouc/nivo/blob/98a4f4394479c0d61c0f7c8ee7a52ce0b380b5f9/website/src/data/components/line/props.js#L72
I ended up setting 2 different specific formatting strings using the [d3-format](https://github.com/d3/d3-format) as a guide
```
    xScale={{
        type: "time",
        // Format must match how the date comes in :facepalm:
        // example "2020-02-20 17:17:51Z"
        format: "%Y-%m-%d %H:%M:%SZ",
        precision: "hour"
    }}
```
and 
axisBottom={{
                            format: "%_m/%-d/%y",
                            tickValues: 7,
                            legend: xLegend,
                            legendPosition: "middle",
                            legendOffset: 34
                        }}
```
I hope that helps!

**Comment by bkriczky** [comment]
Ah ok thank you!

**Comment by bkriczky** [comment]
Hm.. your example used the same format as my date right? using format: 
"%Y-%m-%d %H:%M:%SZ"   for 
2000-01-31T16:00:00.000Z  dosnt seem to work still. Does the T matter?

**Comment by mckelveygreg** [comment]
It is exact to a fault... That is why the `Z` is in there. You also have milliseconds it looks like? So you'll need something for that, too

**Comment by bkriczky** [comment]
Ok awesome thanks again!

**Comment by bkriczky** [comment]
So like this?     format: "%Y-%m-%d %H:%M:%SmsZ"
