### ISSUE TITLE
Missing docs for prop `colorScale`

### ISSUE THREAD

**Issue by gurre** [plouc/nivo#92]
I've been looking around how I should use the `colorScale`-prop for the calendar. Guess I'll read the source code.

**Comment by gurre** [comment]
Seems there are some implementation left to do.

**Comment by plouc** [comment]
@gurre, I've updated the `Calendar` component & its documentation, see http://nivo.rocks/#/calendar

**Comment by gurre** [comment]
Wow you rock! Keep it up your project is really awesome!
