### ISSUE TITLE
Click option to mute all the unselected items in Pie chart

### ISSUE THREAD

**Issue by razorrahul123** [plouc/nivo#920]
Is there an option to change the opacity of all the not selected items in responsive pie nivo.

*I would like to create a pie chart in which the selected value is highlighted and all the other will have a muted color tone.
This is needed to created a filter functionality based on the area of pie selected.
If its possible then can you also tell me how to implement it.
Thanks

**Comment by plouc** [comment]
@razorrahul123 unfortunately it's not possible using built-in features, you could achieve this y using `onMouseEnter|Leave` events and updating the colors accordingly.

**Comment by luizamendes** [comment]
@plouc Hey! Is there an example somewhere on how to achieve this using the events and updating the colors accordingly, as you suggested? I am trying to do the same thing that was asked, but I am not getting the hang of it. Thanks

**Comment by olgakozich** [comment]
@plouc Faced this. Any updates?

**Comment by zeyadetman** [comment]
I did something like this as a workaround:

```jsx
const [activeItem, setActiveItem] = useState({});
const [fillItems, setFillItems] = useState([]);

useEffect(() => {
   if (activeItem && (activeItem as any)?.id) {
      setFillItems(
        data.map((item) => ({
          match: { id: item.id },
          id: item.id === (activeItem as any)?.id ? "lines" : "opacity",
        }))
      );
    } else {
      setFillItems([]);
    }
  }, [activeItem]);
  
  ...
  
  <ResponsivePie
      data={genres}
      ...
      onClick={(item) => {
        if ((activeItem as any)?.id === item.id) {
          setActiveItem(null);
        } else {
          setActiveItem(item);
        }
      }}
      defs={[
        {
          id: "opacity",
          type: "patternLines",
          background: "#a1a1a1",
          color: "rgba(255, 255, 255, 0.3)",
          size: 3,
          padding: 1,
          stagger: true,
        },
        {
          id: "lines",
          type: "patternLines",
          background: "inherit",
          color: "rgba(255, 255, 255, 0.3)",
          rotation: -45,
          lineWidth: 6,
          spacing: 10,
        },
      ]}
      fill={fillItems}
    />
```

Full code example Here: https://github.com/zeyadetman/Notes/blob/main/src/components/Chart.tsx
