### ISSUE TITLE
Drag select option for Scatter graph

### ISSUE THREAD

**Issue by ShawnAmplify** [plouc/nivo#921]
Need a way to select multiple data points to display in another way. Or act as a zoom function to define the limits of the graph. This would be great to give the graph some more interactivity. 

Add OnClickDown and OnClickUp events to the component to allow the drag select to work

Something similar to https://simonwep.github.io/selection/

**Comment by plouc** [comment]
@ShawnAmplify I don't plan to implement this feature for now, what you could do is add an extra layer, capture selection boundaries and filter out the nodes based on it, not the most efficient way to do it I agree, but this could work (the nodes are passed down to custom layers).

**Comment by ShawnAmplify** [comment]
Thanks for responding, I have one other questions. Is it possible to bring onMouseUp and onMouseDown in the props similar to how the onClick and the other mouse events are happening?

Thanks for the help!

**Comment by ohad-definity** [comment]
Hi, do you have any simple example reference for that?
