### ISSUE TITLE
Add option to place label at top/right of bar for vertical/horizontal Bar component

### ISSUE THREAD

**Issue by bencohen2** [plouc/nivo#923]
**Is your feature request related to a problem? Please describe.**
#146 describes a workaround for placing labels at the top of vertical bars in the `Bar` component. As far as I know, no solution has been provided for placing labels at the right of the `Bar` component when it is rendered horizontally. This is the functionality I need.

**Describe the solution you'd like**
Would it be possible for this to be added as a prop? Something like `labelPlacement` which could be an enum between `start`, `middle`, and `end`?

**Comment by meglio** [comment]
I would use this setting too instead of a workaround. Example where I would use it:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/282177/80914314-02312580-8d8a-11ea-80b2-78a1caf3eadf.png">

**Comment by mia-pelino** [comment]
@bencohen2 the following code works for placing labels to the right of a vertical bar:

`labelFormat={d => <tspan y={ 0 }>{ d }</tspan>}`

in my case I needed more of a margin between the bar and the label, so I replaced `y={ 0 }` with `y={ -12 }`
