### ISSUE TITLE
HOWTO: Percentage values in Pie?

### ISSUE THREAD

**Issue by rgetValue** [plouc/nivo#924]
Hello.

How to add percentage symbol to data values in Pie?

![image](https://user-images.githubusercontent.com/5750897/79380452-278bfa00-7f69-11ea-9542-92cade7364e2.png)

btw, this answer doesn't work -> https://github.com/plouc/nivo/issues/468#issuecomment-469522846
:((

**Comment by rgetValue** [comment]
btw, this answer doesn't work -> https://github.com/plouc/nivo/issues/468#issuecomment-469522846
:((

**Comment by baapham** [comment]
Seems like #468 is for bar charts.

Try adding a prop to your pie component `sliceLabel={(item) => `${item.value}%}`

**Comment by rgetValue** [comment]
@baapham Yeyyy, thank you!!!

**Comment by mariano-aguero** [comment]
This works for me...
```
    valueFormat={function (e) {
      return e + '%'
    }}
```

**Comment by dimileeh** [comment]
For [Pie chart](https://nivo.rocks/pie/) it's:
```arcLabel={(item) => `${item.value}%`}```

**Comment by lhguerra** [comment]
In all of those answers I'll have to calculate the percentage myself. Can't I get that value from nivo somehow? It already has to calculate it in order to plot the chart
