### ISSUE TITLE
ResponsiveBar: large space between axis y and the first bar

### ISSUE THREAD

**Issue by barnapisti1994** [plouc/nivo#929]
**Describe/explain the bug**
In case of using large datasets with ResponsiveBar the distance between axis y and the first bar is too large for some widths.

**To Reproduce**
I created a demo on Code Sandbox. As you resize the display area the distance between axis y and the first bar changes and it becomes too large for some sizes. 
https://codesandbox.io/s/nivo-bar-tick-formatting-demo-j1zf9?file=/index.js

**Expected behavior**
The distance between axis y and the first bar doesn't become unproportionally large when resizing.

**Screenshots**
![Képernyőkép erről: 2020-04-20 11-45-08](https://user-images.githubusercontent.com/32958948/79738388-f874e000-82fc-11ea-9615-7f9cafd5009a.png)

**Comment by drodmun** [comment]
Same problem here, the bigger the data, the proportionally bigger the distance

**Comment by AlphaSpectrum** [comment]
I also observed that all of the bars will compress into one single spot right in the middle of the graph at around 406 bar elements

**Comment by mateusscm** [comment]
Anyone find a solution?

**Comment by barnapisti1994** [comment]
I ran through the related code a few weeks ago when I created this issue. I think it is caused by the calculations made by the d3 library but I'm not 100% sure.

**Comment by immanuelfodor** [comment]
Same issue here, it doesn't look good, and I couldn't find any solution apart from making excuses to complaining customers that it needs a fix from Nivo 😞

**Comment by ldd** [comment]
Question for people affected by this: have you considered using a Line graph?

From The example you provided:

![line](https://user-images.githubusercontent.com/1187476/83364309-6980cc00-a36e-11ea-90b7-c23705abcdf0.png)

source (forked codesandbox code from your example): https://codesandbox.io/s/nivo-bar-tick-formatting-demo-jso1b?file=/index.js

I mention this because I remembered having had exactly the same issue in a couple of other libraries until it hit me: once you have a lot of data points, it makes more sense to just use a line graph to display your values. I think that's how I solved some graph issues [here](https://github.com/ldd/mal-anime-graph)

**Comment by drodmun** [comment]
@barnapisti1994 add the label:":bar_chart: bar"  so appear as an open issue for that and let's hope it gets fixed soon

**Comment by immanuelfodor** [comment]
@drodmun I think only contributors can add labels to issues.

**Comment by abourtnik** [comment]
Any news for this issue ?

**Comment by immanuelfodor** [comment]
No progress here 😢

**Comment by wyze** [comment]
I think this is related to #840. If so there is a PR in the works to get this solved.

**Comment by wyze** [comment]
Looks to be fixed by #1282 and will be available in the next version. See here: https://codesandbox.io/s/nivo-forked-y50jx

**Comment by nightwolf-041** [comment]
> Looks to be fixed by #1282 and will be available in the next version. See here: https://codesandbox.io/s/nivo-forked-y50jx

it's not :/

**Comment by wyze** [comment]
@nightwolf-041 Please provide a new sandbox link with your code as the original issue here with the sandbox is not experiencing the issue.

**Comment by SamuelBrander** [comment]
A fix that worked in my case is to add "indexScale={{ type: "band", round: false }}" to the props of the chart. 

The default for a Nivo Bar Chart seems to be "indexScale={{ type: "band", round: true }}". Based on the source code of nivo, particularly [https://github.com/plouc/nivo/blob/master/packages/scales/src/bandScale.ts](https://github.com/plouc/nivo/blob/master/packages/scales/src/bandScale.ts), Nivo uses the D3 [scale band](https://observablehq.com/@d3/d3-scaleband). If round is set to true, all the measurements in the chart are rounded down from floats to integers:

"[band.round](https://github.com/d3/d3-scale/blob/master/README.md#band_round) — and the shorthand notation [band.rangeRound](https://github.com/d3/d3-scale/blob/master/README.md#band_rangeRound) — give the results as integer values, using Math.floor() to avoid overflowing the range. This will usually leave some unused space, that must be allocated to the left and right padding (even if those have been set to 0). Align them with band.align."

It seems that in the case of hundreds of data points, and a slim enough display (say, 1080 pixels of screen width for 300 data points) this unused space grows quite large. Feel free to correct me in case my assumptions are wrong, but the fix works on my end.

**Comment by raktim-sg** [comment]
The above solution by @SamuelBrander  resolved the issue for me.

**Comment by SteveAtKlover** [comment]
worked for me too. thanks :)
