### ISSUE TITLE
Custom symbolShapes for legend 

### ISSUE THREAD

**Issue by subanandhini** [plouc/nivo#930]
I am using a Bar chart with line and area as a layer. I want to differentiate the line chart and bar chart the only option I have is to differentiate based on colors, but what I exactly want is for line chart. I have to indicate with '@material-ui/icons/LinearScale'; and for other it should be square or circle  
![Composedcharts](https://user-images.githubusercontent.com/34816663/79766365-82489b80-8345-11ea-9f10-1b574f8ef44b.png)
in the above chart, I have to display the line  with Linearscale Icon and bar and area with color filled square

**Comment by wyze** [comment]
The `legends` prop supports an array, so you can have 2 legends, one for the square/circle, and one containing your custom symbol.
