### ISSUE TITLE
Support d3-scale nice

### ISSUE THREAD

**Issue by CharlieMartell** [plouc/nivo#931]
**Is your feature request related to a problem? Please describe.**
Currently if the domain of a continuous scale is say [1050, 1500] the scale will return tickvalues/gridvalues that do not include the full domain. If you use https://github.com/d3/d3-scale#continuous_nice it will include the full domain in the tickvalues

**Describe the solution you'd like**
Allow us to pass a prop in the yScaleSpec, xScaleSpec to include full domain in the ticks computed. 

**Describe alternatives you've considered**
I manually computed tickValues and gridValues for a chart after creating a "nice" domain. But then the axis labels get messed up because the axis labels are being plotted to a scale computed by nivo which doesn't use the "nice" domain so it will put labels inside the chart. 

**Additional context**

**Comment by wyze** [comment]
I think this would be great and shouldn't be difficult to add if anyone wants to attempt a PR!
