### ISSUE TITLE
Is possible to change the point color of line chart depending of value?

### ISSUE THREAD

**Issue by sergiocc96** [plouc/nivo#932]
Hello, 
i need **change the point color of Line chart depending of the value**. For example if the tick have a propierty **changecolor : 1** i need the color of this point be blue and is **changecolor: 0** red. And with this i will have a **line chart with 1 line but diferents pointcolor in the same line**. 
Is possible do that? 
Thankyou!

**Comment by WhoAteDaCake** [comment]
Can't you just use
```
pointColor={(n: Point) => {
    return n.color;
}}
```

**Comment by sergiocc96** [comment]
No, with this i get all data and i only need the data of the current position. 
I need change the pointcolor in any tick, i need the pointColor of the chart at the tick 1 be red and the tick 2 be blue,  i have a data like this:  

 
```
data = [
  object {
     changecolor :  1,
      x : 10,
      y: 20
} ,
 object {
     changecolor : 0,
      x : 5,
      y: 2
} 
...
]
```

Thanks !

**Comment by MattJakeman** [comment]
I have a similar problem. I would like to be able to change individual point colours on a line, based on the data value of that point. Is there any way to accomplish this?

**Comment by sergiocc96** [comment]
Try this, works for me


```
pointSymbol={e => {

                let colorPunto = ''
                let colorBorde = ''

                switch (e.datum.name) {
                    case '1':
                        colorPunto = e.datum.valueI? 'rgba(6,1,85,0.58)' : 'white'
                        colorBorde = 'rgb(6,1,85)'

                        break;
                    case '2':
                        colorPunto = e.datum.valueI? 'rgba(107,167,156,0.85)' : 'white'
                        colorBorde = 'rgba(42,146,77,1)'
                        break;

           
                }

                return (
                    <circle cx="0" cy="0" r="5" stroke={colorBorde} strokeWidth="2" fill={colorPunto} />
                );

            }}
```

**Comment by MattJakeman** [comment]
Fantastic, thanks for the help.
