### ISSUE TITLE
BarCanvas: hardcoded legend symbol size and text color

### ISSUE THREAD

**Issue by barnapisti1994** [plouc/nivo#933]
**Is your feature request related to a problem? Please describe.**
I tried to set a dark color and decrease symbol size for BarCanvas legends but changing the configuration didn't affect the chart. I found the cause in the repository, the symbol size and the color are hardcoded in the source code of BarCanvas:
![Képernyőkép erről: 2020-04-24 11-22-18](https://user-images.githubusercontent.com/32958948/80196623-f329d500-861d-11ea-99fa-555465a74a6e.png)

**Describe the solution you'd like**
The symbol size and text color of the legends of BarCanvas can be configured.

**Comment by immanuelfodor** [comment]
bump

**Comment by noobvim** [comment]
bump
