### ISSUE TITLE
Custom ticks overlap when updating the scale

### ISSUE THREAD

**Issue by catalinberta** [plouc/nivo#934]
**Thanks for using nivo**
Thank YOU! It's awesome!

**Describe/explain the bug**
When using custom ticks/labels for the axis -> updating the scale updates them through some transition animation that makes the old and new values overlap. This does not happen when using the default ticks.

**To Reproduce**
No custom ticks (works as expected) https://codesandbox.io/s/nivoline-update-y-scale-with-no-custom-ticks-qiitd
WITH custom sticks (ticks overlap when get updated): https://codesandbox.io/s/nivoline-update-y-scale-with-custom-ticks-7cjkl

Click the increase and decrease buttons to update the Y scale 

**Expected behavior**
With custom ticks, when the scale gets updated, the old ticks should immediately fade out in order not to overlap with the new ones

**Additional context**
This might be a simple fix/error on my end, I apologize if that's the case, thanks in advance for your help!

**Comment by catalinberta** [comment]
On further debugging, I notice that native ticks are SVG and added with the <g> element, while custom ticks are added with <foreignObject>.
I notice that the custom <g> ticks are faded out via an inline opacity transitioned to 0, I'm guessing that this is not applied to custom ticks that use <foreignObject>?

**Comment by CaveSeal** [comment]
I had a similar problem, and discovered that I needed to add opacity to the `<g>` element.

```
const customLeftAxisTick = tick => {
  return (
    <foreignObject
      width={60}
      height={30}
      opacity={tick.opacity}
      transform={`translate(${tick.x - 60},${tick.y - 20})`}
    >
      <div className="customLeftAxisTick">
        <span>{tick.value}</span>
        <svg
          width={90}
          height={1}
          style={{ transform: "translate(-10px,-10px)" }}
        >
          <g>
            <line
              stroke="#edf1f4"
              strokeWidth="1"
              opacity="1"
              x1="0"
              x2="90"
              y1="0"
              y2="0"
            />
          </g>
        </svg>
      </div>
    </foreignObject>
  );
}
```
