### ISSUE TITLE
custom cellShape not supported with HeatMapCanvas

### ISSUE THREAD

**Issue by babsonmatt** [plouc/nivo#936]
**Describe/explain the bug**
Not sure if intended, but custom cellShapes are not supported by HeatMapCanvas.  The code looks like it checks for 'rect' otherwise defaults to 'circle', so passing in a custom shape results in a circle.

**To Reproduce**
https://nivo.rocks/heatmap/

Toggle cellShape to custom, you'll see the triangular shapes in the heat map.
Switch to canvas and repeat and you'll see the cells are circular.

**Expected behavior**
Custom cell shapes to work in HeatMapCanvas

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 81

Thanks!

**Comment by Dfred** [comment]
bump.
