### ISSUE TITLE
Skipping tick values in ResponsiveLine

### ISSUE THREAD

**Issue by ymenase** [plouc/nivo#938]
Hi, I have read through the existing issues and the docs. I am unable to skip ticks with responsiveline. I am using timescale but I tried with point as well. Right now, I have a chart with day/time increments, and I have a label at every tick. I want the labels to skip ticks, so if ticks 0-4 are 8AM, 9AM, 10AM, 11AM, 12PM, I would want 
0  blank
1 9AM
2 blank
3 11AM
4 blank

I havre dug through the source code as well and I am at a loss. The closest I have is writing a custom function:
```  static labelArray() {
        const tickValues = [0, 1, 2, 3, 4];
        for (let i = 0; i < tickValues.length; i += 2) {
            tickValues.push(tickValues[i]);
        }
        return tickValues;
    }
```

and in axisBottom, 
```
  axisBottom={{
                        orient: 'bottom',
                        tickSize: 0,
                        tickPadding: 10,
                        tickRotation: 0,
                        tickValues: Chart.labelArray(),
                        renderTick: CustomTick,
                        legendOffset: 100,
                        translateX: 25,
                        legendPosition: 'start',
                    }}
```
```
               xScale={{
                        type: 'time',
                        format: '%m/%d/%Y %H:%M:%S %p',
                        precision: 'second',
                    }}
                    xFormat="time:%Y-%m-%d"
```
I should mention that this:
        const tickValues = [0, 1, 2, 3, 4];

is mostly a placeholder. I want that to represent the dynamic values OF those indices but not sure how to write it. This is NOT an array of numbers. Thanks

**Comment by iepur1lla** [comment]
I had a similar problem with tick values for days, what helped me is the option "every x days". Nivo axes, [docs](https://nivo.rocks/guides/axes) are based on [d3 scale](https://github.com/d3/d3-scale). 

I would suggest to check your input data and set then "every X hours" based on your data dynamically.

**Comment by ayushbisht2001** [comment]
bump
