### ISSUE TITLE
Feature request: scatter plot component

### ISSUE THREAD

**Issue by demartsc** [plouc/nivo#94]
Hi Raphael, great work on the library so far, would be great to see a scatter plot component added to the repo as well.

**Comment by plouc** [comment]
I've created `@nivo/scatterplot` package, which offers 2 implementations:
* svg => http://nivo.rocks/#/scatterplot/
* canvas => http://nivo.rocks/#/scatterplot/canvas

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/107
