### ISSUE TITLE
Graph breaks if data is not organized in data array (min->max)

### ISSUE THREAD

**Issue by hannespettersson** [plouc/nivo#946]
**Describe/explain the bug**
Graph breaks when you input multiple arrays of data to the graph in the "wrong" order.

I investigated it and Nivo seems to require the data to be organized so that x-axis data is less in the data array data[0] than in data[1].

If it is more in data[0] than data[1] then it will break and data is not correct in x-axis anymore.

**To Reproduce**
I created a sandbox that to show you the bug:
https://codesandbox.io/s/nivo-rocks-bug-6y08c

There are three example graphs:
-First the bug (problematic dataset)
-Second: Workaround (workingdataset)
-Third: Working example with problematic dataset turned around ;)

**Expected behavior**
It should not matter what is the order where the data is placed in the data array.

**Screenshots**
![image](https://user-images.githubusercontent.com/15250006/81200804-23358880-8fcd-11ea-9ff5-20eba30c5eda.png)

**Desktop (please complete the following information):**
Chrome and safari latest

**Comment by plouc** [comment]
It behaves this way because by default the chart uses a point scale, if you want to use dates, you should use a time scale, otherwise order matters.

**Comment by hannespettersson** [comment]
Thanks :) I needed to dig some information because the documentation did not mention "time" at alla in "https://nivo.rocks/line/"
There is only "point" and "line".

But then i found issue 289 and the demo attached. Lot of "try-and-error" but eventually all working fine. 

https://github.com/plouc/nivo/issues/283
and the demo: https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L101

I updated my codesandbox to to show how i fixed it.

**Comment by wyze** [comment]
Glad you got it resolved. There are definitely more examples in storybook than in the documentation!
