### ISSUE TITLE
ES5 Compliant version

### ISSUE THREAD

**Issue by agarwal00s** [plouc/nivo#947]
Is there an es5 compliant distribution for @nive/pie and @nivo/line?
I am facing this error while building the application:
Failed to minify the bundle. Error: index.6d841c69.js from UglifyJs
We are using Uglifyjs to minify, which supports till es5 and not es6.

**Comment by plouc** [comment]
Sorry, but this is actually an issue with d3 packages, not nivo, the author decided to no longer ship es5 compliant packages, if you really need es5 compliant bundle, you'll have to process those packages, otherwise you can use terser for minification, which is more flexible.
