### ISSUE TITLE
hide the bar in grouped bar chart if data is null or 0 

### ISSUE THREAD

**Issue by ashutoshsoptai** [plouc/nivo#950]
**hide or remove the bar in grouped bar chart if data is null or 0 **
var data=[
        {
            "key1": 40,
            "key2": 35,
            "key3": 0,
            "time": "30 Jun 19"
        },
        {
            "key1": 35,
            "key2": 35,
            "key3": 0,
            "time": "31 Jul 19"
        },
        {
            "key1": 40,
            "key2": 35,
            "key3": 0,
            "time": "31 Aug 19"
        },
        {
            "key1": 28,
            "key2": 0,
            "key3": 35,
            "time": "30 Sept 19"
        },
        {
            "key1": 40,
            "key2": 0,
            "key3": 35,
            "time": "31 Oct 19"
        },
        {
            "key1": 40,
            "key2": 0,
            "key3": 35,
            "time": "30 Nov 19"
        },
        {
            "key1": 40,
            "key2": 0,
            "key3": 35,
            "time": "31 Dec 19"
        }
    ]
`<ResponsiveBar
                                        data={data}
                                        keys={['key1','key2','key3']}
                                        indexBy="time"
![Screenshot 2020-05-08 13 11 06](https://user-images.githubusercontent.com/62087918/81490261-a0554c00-92b2-11ea-838c-6faa46c2b85e.png)

                                        margin={{ top: 50, right: 50, bottom: 80, left: 50 }}
                                        padding={0.5}
                                        innerPadding={6}
                                        groupMode="grouped"
                                        theme={{
                                            axis: {
                                                ticks: {
                                                    line: {
                                                        stroke: '',
                                                    },
                                                    text: {
                                                        fill: '#A9B0BB',
                                                    },
                                                },
                                            },
                                            grid: {
                                                line: {
                                                    stroke: '#ECECEC',
                                                    strokeWidth: 1,
                                                    strokeDasharray: '6',
                                                },
                                            },
                                        }}
                                        axisLeft={{
                                            tickPadding: 15,
                                            tickValues: 5,
                                        }}
                                        enableLabel={false}
                                        colors={['#2166AC', '#B2182B', '#F4A582']}
                                    />`

**Comment by CRGavrila** [comment]
just remove all keys with zero and null value from object. you can use something like lodash

**Comment by ashutoshsoptai** [comment]
> just remove all keys with zero and null value from object. you can use something like lodash

I tried it stills the same
