### ISSUE TITLE
coloring diverging stacked bar chart

### ISSUE THREAD

**Issue by m-jakob93** [plouc/nivo#952]
When only one data value != 0 is given in the data array for the stacked diverging bar, only the first color is chosen. The array of keys then does not always match the array of colors.

In the sandbox I reproduced the problem:

The keys are: ["pos", "neg"]
The colors are: ["green", "red"]
If the data looks like this [{pos: 1, neg: -1}] all is well, but if the data is [{pos: 0, neg: -1}], the "neg" is colored with the first color value.

[Codesandbox](https://codesandbox.io/s/fast-snow-cpnsj?file=/src/App.js)

OS: macOS Catalina 10.15.4
Browser: Chrome Version 81.0.4044.129

**Comment by diegosps** [comment]
I believe this is the same bug as #986 and #1031 

Maybe close them as duplicate?

Looking the code, a simple fix is to remove all `if (barWidth > 0)` and `if (barHeight > 0)` from `grouped.js` and `stacked.js`

I tested it locally and it worked. Both the colors and legend items.

However, i didn't go further the code to see if this has any impact.

**Comment by IgorStetsiuk** [comment]
Hey, guys! Do you have any updates on this? I've encountered the same issue as @m-jakob93 described, what could I possibly do except changing the source code of the lib? 

For now, I came up with the idea of checking, `data` and then to adjust `colors` and `keys` properties for that `datums` (data points) with that exact colors that I need to display.

I'll post updates here and my case and solution, ones its ready

**Comment by wyze** [comment]
This is fixed in the latest version: https://codesandbox.io/s/wispy-feather-9fnwe
