### ISSUE TITLE
Showing tooltip for onMouseEnter on custom bar items

### ISSUE THREAD

**Issue by lucaorio** [plouc/nivo#956]
Sorry for opening an issue here, but I couldn't find a specific example on Storybook.

I am currently using `ResponsiveBar` with a simple, `svg`-based custom bar component. Is it possible to show/hide a custom tooltip on mouseenter/leave?

**Comment by Eric0201** [comment]
@plouc can you help me same issue

**Comment by wyze** [comment]
The BarItem does receive all the props needed for this, here is a snippet of how it is handled in the default BarItem component:

```ts
function BarItem({ showTooltip, hideTooltip, onMouseEnter, onMouseLeave, tooltip }) {
    const handleTooltip = e => showTooltip(tooltip, e)
    const handleMouseEnter = e => {
        onMouseEnter(data, e)
        showTooltip(tooltip, e)
    }
    const handleMouseLeave = e => {
        onMouseLeave(data, e)
        hideTooltip(e)
    }

    return (
        <rect
            onMouseEnter={handleMouseEnter}
            onMouseMove={handleTooltip}
            onMouseLeave={handleMouseLeave}
        />
    )
}
```

**Comment by aruldd** [comment]
While implementing the snippet, the tooltip parameter comes as undefined, so the tooltip is not being shown. Are we supposed to create the tooltip element ourselves?

Thank you for your help.

**Comment by Eric0201** [comment]
> While implementing the snippet, the tooltip parameter comes as undefined, so the tooltip is not being shown. Are we supposed to create the tooltip element ourselves?
> 
> Thank you for your help.

I created a custom tooltip and passed data into it, it work

**Comment by wyze** [comment]
@aruldd Are you passing some tooltip prop to your bar graph? The custom bar component receives the same props as the default bar component, so the tooltip should work either way.

**Comment by aruldd** [comment]
> @aruldd Are you passing some tooltip prop to your bar graph? The custom bar component receives the same props as the default bar component, so the tooltip should work either way.

No. If I just remove the `barComponent` prop it rendersbthe Default tool tip properly.

I have temporarily fixed it by creating a `BasicTooltip` same as the default `BarItem` component.
