### ISSUE TITLE
Component props documentation

### ISSUE THREAD

**Issue by rafaelmarques7** [plouc/nivo#958]
**Is your feature request related to a problem? Please describe.**

This  request is related to documentation of components.

**Describe the solution you'd like**

I would like some documentation regarding the props of these components, particularly regarding the `data` props.
For example, in the case on the `Sunburst` component, although the documentation page https://nivo.rocks/sunburst/ does include a `data` tab that has an example of data, this gives us little information on how to compose the data object ourselves.

**Describe alternatives you've considered**

**Additional context**

**Comment by wyze** [comment]
I'm not sure I follow 100%. The tab with example data is showing you the shape you need to have your data in when you pass it to the chart. How you get it into that shape, that is up to you.

**Comment by rafaelmarques7** [comment]
@wyze sorry, I should have been more clear.
I do understand that the `data` that shows the shape of the data.
But looking at that data specifically, I can see that there is a field called `loc` (for example `"loc": 186635`) that apparently is required in order to build this correctly.
However, I have no idea what this `loc` field represents, and what value I should use there.
The `186635` value for gives me very little information.

**Comment by wyze** [comment]
Looks like it is the `value` prop (`value="loc"`) in the documentation:

![image](https://user-images.githubusercontent.com/186971/82219460-ecbc0f80-98e2-11ea-8646-12413f7c18e8.png)

**Comment by ldd** [comment]
To complement what @rafaelmarques7 said, I found that there was a little bit of friction in how to use this library.

It was easy to figure out that `indexBy` and `keys` are how I was supposed to access my data in `@nivo/radar`, but I think it doesn't hurt anyone if you mention it somewhere in the documentation. 

Simplest solution I thought of:
- add a comment at the top of the data tab, something like
// take a look at `indexBy` and `keys` to see how your data is being used

Then again, I love what you did with nivo and it took me less than a minute to find out what to do.

**Comment by wyze** [comment]
PRs are welcome. :)

We probably need to put together some getting started guide or minimum config required per chart.

**Comment by ldd** [comment]
ok! I can give a shot at a documentation-only PR.

But first let's discuss the possibilities:
 - [ ] add comments to the storybook's data section
 - [ ] add a generic getting started guide
- [ ] add a `data` guide in the same menu as the other guides (axis, color, etc). 

Now that I think about it, the 3rd option seems interesting, what do you think?

**Comment by wyze** [comment]
Oh yeah, option 3 sounds good! I think it would still need sectioned by chart type, so don't feel like you have to add them all in a single PR.

**Comment by plouc** [comment]
@ldd, I don't think we can create a generic data guide, depending on the chart you use, the shape of the data can be really different, e.g. line VS sankey VS network VS map, I'm afraid it would cause confusion to try to make it generic for all charts.
Adding a comment to the data section sounds good (when the data item in the prop list isn't enough), but I guess you're referring to the website, not storybook?
A getting started guide is a must 👍
