### ISSUE TITLE
Invalid minified file for production (CDN)

### ISSUE THREAD

**Issue by ylacaute** [plouc/nivo#959]
I am trying to use Nivo with a CDN link in a simple static HTML page (no tools, just an HTML edited with a basic text editor).

**To Reproduce**
Just include the minified file (pie chart) in script tag : it produces an error in the console.
[The detailed problem have been exposed on stackoverflow.](https://stackoverflow.com/questions/61821010/use-nivo-graph-lib-in-a-single-html-page-react).

**Expected behavior**
We should be able to include the CDN file in a static html file and use the library to create a chart.
Included file : https://cdn.jsdelivr.net/npm/@nivo/pie@0.61.1/dist/nivo-pie.cjs.min.js

**Desktop**
 - OS: Debian
 - Browser: chromium/chrome
 - Version: 81

You did a very good job with that library, probably the best one for React ! I already used it in a classic project, everything works as expected, but here it is a special need : just a static page, build without any tools.

**Comment by wyze** [comment]
You would want to use the UMD or ESM bundle for that. Granted I tried both and couldn't get either of them to work, even trying several different CDNs and building the bundle from source to try and get around errors.

**Comment by plouc** [comment]
@ylacaute, as @wyze mentioned, you should use the [UMD build](https://cdn.jsdelivr.net/npm/@nivo/pie@0.61.1/dist/nivo-pie.umd.min.js), however, you'll need a bunch of extra dependencies, including D3 packages which are using modern JS features.

**Comment by ylacaute** [comment]
@plouc thank you, indeed it is better but now I have some new errors I don't undertand :
```js
Uncaught TypeError: o is not a function
    at nivo-pie.umd.js:194
```
Which is this line :
```js
 var PieLayout$1 = setDisplayName('PieLayout')(enhance(PieLayout));
```
So I think I had to add more dependencies, like Recompose but then have a new error : 
```js
Recompose.min.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
```

Also, I don't undertand why you speak about D3, it Nivo based on D3 ? Why we don't see the dependency in package.json ?


Here is my test file which even not include the PIE code yet :
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Batch stats</title>
    <script crossorigin src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/recompose/0.25.0/Recompose.min.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js"></script>    
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min.js"></script>
    <script crossorigin src="https://unpkg.com/react@16.7.0/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16.7.0/umd/react-dom.production.min.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.7.2/prop-types.min.js"></script>
    <script crossorigin src="https://cdn.jsdelivr.net/npm/@nivo/bar@0.61.1/dist/nivo-bar.umd.min.js"></script>    
    <script crossorigin src="https://cdn.jsdelivr.net/npm/@nivo/pie@0.61.1/dist/nivo-pie.umd.min.js"></script>
</head>
<body>
<div id="root"></div>
<script type="text/babel">
    function Page(props) {
        return (
            <div>
                <h1>Hello World</h1>
                <div>How to add a PIEChart ?</div>
            </div>
        );
    }
    ReactDOM.render(<Page version="v3"/>, document.getElementById('root'));
</script>
</body>
</html>


```
