### ISSUE TITLE
"Error: <path> attribute d: Expected number"  AND Warning: Failed prop type: The prop `y` is marked as required in `DotsItem`, but its value is `undefined`.

### ISSUE THREAD

**Issue by nigellima** [plouc/nivo#960]
**Describe/explain the bug**
Example Line Chart from documentation is triggering some warnings and errors on console. It's rendering correctly, though.

**To Reproduce**
Component from documentation page used in React + Typescript application

1. Go to https://nivo.rocks/line/
2. Copy generated code 
3. Use it on a React Typescript application

**Expected behavior**
No warnings or error logs

**Screenshots**
<img width="747" alt="image" src="https://user-images.githubusercontent.com/14295280/82174330-a9dc4680-98a6-11ea-9bb0-f9383dfc23c8.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome and Firefox
 - Version: "@nivo/line": "^0.61.1",

**Comment by wyze** [comment]
Here is a CodeSandbox with the generated code + data: https://codesandbox.io/s/quizzical-bassi-h99py

I don't see any errors. It sounds like there may be some issue with the data you are providing to the chart. Would you mind updating the sandbox with the data you are using to reproduce the error?

**Comment by nigellima** [comment]
Hi @wyze it was indeed an error with my DATA array. I had duplicate keys for x parameter in some items

**Comment by wyze** [comment]
Glad you got it resolved @nigellima! Going to close this out as there is nothing actionable here.

**Comment by iljinjung** [comment]
However, the same error occurs for y as well.
y is the value of the data, not the key...
