### ISSUE TITLE
How to change scale of axisLeft?

### ISSUE THREAD

**Issue by nigellima** [plouc/nivo#965]
Is it possible to change the scale of the numbers in the axisLeft in the line chart (or any other series type)?

For example, I have these values in the axisLeft. How would I display them in K scale? like: 0k, 0.5k and 1k. Displaying only these 3 values there, instead of all hundred  steps.

<img width="103" alt="image" src="https://user-images.githubusercontent.com/14295280/82493379-3c0a6780-9abe-11ea-96d3-3ffc90390eaf.png">

**Comment by wyze** [comment]
You could try the following:

```ts
<Line
  axisLeft={{ format: value => `${value / 1000}k`, tickValues: [0, 500, 1000] }}
/>
```

**Comment by nigellima** [comment]
Hi @wyze Thanks for your response.

I was able to set like you suggested. Thanks. However, the last tick (the 1000) is not being displayed in the chart. DO you know why?

Also, for some reason my chart is displaying the line wiht smaller values above the line with greater values, even though I've set the yScale line this:

```
yScale={{
        type: 'linear', min: 0, max: 1000, stacked: true, reverse: false,
      }}
```
Thanks in advance

**Comment by wyze** [comment]
> I was able to set like you suggested. Thanks. However, the last tick (the 1000) is not being displayed in the chart. DO you know why?

Might need something like `margin={{ top: 30 }}`.

> Also, for some reason my chart is displaying the line wiht smaller values above the line with greater values

Would be easier to debug if you could throw together a quick CodeSandbox.

**Comment by nigellima** [comment]
Hi @wyze Sorry for the delay.
That worked perfectly. Thank you very much

**Comment by wyze** [comment]
No worries, glad we got it resolved!
