### ISSUE TITLE
Sankey with fixed colors causes errors

### ISSUE THREAD

**Issue by mvdobrinin** [plouc/nivo#970]
### Issue
An error is printed to the Chrome developer tools console when using a sankey diagram with pinned node colors rather than using a D3 color scheme. The actual rendering appears to work even though warnings are printed.

```
index.js:1 Warning: Failed prop type: The prop `links[0].color` is marked as required in `SankeyLinks`, but its value is `undefined`.
    in SankeyLinks (created by pure(SankeyLinks))
    in pure(SankeyLinks) (created by Container)
    in g (created by SvgWrapper)
    in svg (created by SvgWrapper)
    in SvgWrapper (created by Container)
    in div (created by Container)
    in MotionConfigProvider (created by Container)
    in Container (created by Sankey)
    in Sankey (created by pure(Sankey))
    in pure(Sankey) (created by withPropsOnChange(pure(Sankey)))
    in withPropsOnChange(pure(Sankey)) (created by withPropsOnChange(withPropsOnChange(pure(Sankey))))
    in withPropsOnChange(withPropsOnChange(pure(Sankey))) (created by withPropsOnChange(withPropsOnChange(withPropsOnChange(pure(Sankey)))))
```

### To Reproduce
I've set up a code sandbox that reproduces the issue here - https://codesandbox.io/s/purple-https-0z71s?file=/src/index.js. Check the Console tab to see the errors.

### Versions
* Sankey - 0.61.2
* React - 16.13.1

**Comment by wyze** [comment]
There are a couple things here, but first off, the warning is correct in that the links are getting the `color` prop set to undefined.

The `colors` function you provide will be used for both nodes and links.

In the sandbox, in order to fix that, you can add the same `nodeColor` prop to the map of links data and refresh, the error will go away. 

Next, the whole graph will still be red (from your example), because of `enableLinkGradient` prop. If you remove it, or set it to false, you will see the color you set on `nodeColor` for the links. I believe the gradient won't work well with custom colors, would need to dig in further.

Lastly, it does look like you might have been looking at the storybook for this, so we should leave this ticket open to get that updated to showcase this better.

**Comment by mvdobrinin** [comment]
> I believe the gradient won't work well with custom colors, would need to dig in further.

@wyze Actually it works right now already. It just happens to produce the warnings above.

It seems like setting `nodeColor` on links and `enableLinkGradient` aim to achieve opposite goals. For me, I want my links to be colored with a gradient between the nodes and the nodes to have a pinned hardcoded color rather than a D3 palette. 

It looks to me that when a gradient is enabled on the links, the library shouldn't expect `nodeColor` on the links. Would you agree?

**Comment by mvdobrinin** [comment]
I tested some more and it looks like when `enableLinkGradient` is set, you need `nodeColor` set on links to prevent the warnings - but the value is not actually used. So to make the error go away, just add a black nodeColor on the links.

```
const sankey = {
  nodes: [
    {
      id: 'A',
      nodeColor: '#4884b8',
    },
    {
      id: 'B',
      nodeColor: '#d57f46',
    },
    {
      id: 'C',
      nodeColor: '#d57f46',
    },
    {
      id: 'D',
      nodeColor: '#57aa4a',
    },
    {
      id: 'E',
      nodeColor: '#d24a3e',
    },
    {
      id: 'F',
      nodeColor: '#9c76c2',
    },
  ],
  links: [
    {
      source: 'F',
      target: 'C',
      value: 5,
      nodeColor: '#000000',
    },
    {
      source: 'F',
      target: 'B',
      value: 5,
      nodeColor: '#000000',
    },
    {
      source: 'F',
      target: 'A',
      value: 5,
      nodeColor: '#000000',
    },
    {
      source: 'A',
      target: 'D',
      value: 5,
      nodeColor: '#000000',
    },
    {
      source: 'A',
      target: 'E',
      value: 5,
      nodeColor: '#000000',
    }
  ]
};
```

**Comment by mvdobrinin** [comment]
Bump.
________________________________

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/1748
