### ISSUE TITLE
Is it possible to enableSlices for both x and y?

### ISSUE THREAD

**Issue by nigellima** [plouc/nivo#972]
Hi,

According to the [example](https://nivo.rocks/line/) and also the type definition (`(JSX attribute) enableSlices?: false | "x" | "y" | undefined`) for the enableSlices attribute, I can only enable one at a time. Would it be possible, somehow, to add the horizontal dashed line on the hover (making a cross) but having the same behaviour as enableSlices="x"? (like the tooltip showing all the current multiple line values)

Like this, but also having the horizontal line while hovering

<img width="857" alt="image" src="https://user-images.githubusercontent.com/14295280/83072902-eb5ab780-a045-11ea-9ffe-25e6f61f6dd7.png">

**Comment by wyze** [comment]
Do you need `enableSlices="x"`? You can `enableSlices={false} crosshairType="cross"`. If you need enableSlices=x then you need to do a custom layer and implement it yourself like this: https://github.com/plouc/nivo/blob/c5d5d86f3cb04820a7de5629b38842d6100fa4ef/packages/line/src/Line.js#L260-L267

**Comment by nigellima** [comment]
Hi @wyze 
Thank you very much for your quick response!

Indeed, I the `crosshairType`renders it the way I want. But, I think I need the `enableSlices="x"` because this way my custom tooltip is able to render all the points in the current slice at once through the `sliceTooltip` function.

I tried to implement my custom and I was able to render a static cross and have the `enableSlices="x"` at the same time. However, in the parameters that the custom layer provides me there is no parameter similar to `currentSlice` or `slice` (like we have in the `sliceTooltip` function). Looking at the documentation, the `SlicesItem` component is the one that sets it, but would there be a proper way of finding the current slide from within the Custom Layer function?

This is my custom layer so far:

```
const CrosshairLayer = (params) => {
  const {
    slices, innerHeight, innerWidth,
  } = params;

  return (
      <Crosshair
        key="crosshair"
        width={innerWidth}
        height={innerHeight}
        x={50} // current slice?
        y={50} // current slice?
        type="cross"
      />
  );
};
```

And this is the `params` objects in the function scope:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/14295280/83110707-dc055980-a099-11ea-93e6-54fae857d85b.png">

Thanks in advance for your help

**Comment by wyze** [comment]
It looks like the work we need was added in #656, so the next release will have the custom layer receive the currentPoint/currentSlice props.

**Comment by nigellima** [comment]
Oh nice @wyze I've seen the currentSlice would be exposed to custom layers. Do you have an estimate of when it would be released?

**Comment by wyze** [comment]
Unfortunately I don't, but I hope soon. I only have access to merge PRs, not cut releases yet.

**Comment by nigellima** [comment]
@wyze  I see! So, in the meantime would be possible a workaround solution?

**Comment by plouc** [comment]
@nigellima it has been released in `v0.62.0`

**Comment by nigellima** [comment]
@wyze @plouc I've managed to achieve the results by customizing the single point tooltip (adding all values as it was enableSlices="x"). Thanks for your support

**Comment by plouc** [comment]
@nigellima I’m glad you found a way to achieve what you wanted! I’m gonna close this then.
