### ISSUE TITLE
Is it possible to reverse the order of items in "legend" and "slices"?

### ISSUE THREAD

**Issue by MarcoAlvarez** [plouc/nivo#973]
I am trying to reverse the order of items in the "legend" and "slices" for a ResponsiveLine.  The default ordering is in increasing order, and I would like to see items in decreasing order.  After multiple tries I couldn't figure it out.

**Comment by wyze** [comment]
If the scale is linear type you can try setting the `reverse: true` property of the yScale/xScale property. If that doesn't work it would be helpful to provide a codesandbox or some code so we can look at it further.

**Comment by MarcoAlvarez** [comment]
Thank you for your response.  I was hoping to find a way to reverse the order of the items that appear inside the legend box.  I actually reversed the order of my items inside the JSON (data) file and it worked well.

**Comment by wyze** [comment]
Glad you got it working!
