### ISSUE TITLE
Changing the grid label colors on @nivo/radar

### ISSUE THREAD

**Issue by yodashiv** [plouc/nivo#974]
I'm trying to change the grid label value colors on the nivo radar visualization but can't find a way to do so. The documentation has a small blurb on using the grid label function and passing it in as a prop to the component, but this doesn't seem to be working well for me. The text is being cut off and formatted incorrectly. As you can see below, there is a label of 'strong' with a value of 56, but you can see neither the label 'strong' nor the value of 56 on the perimeter of the radar
since they are too similar to the background. I want to make both of those text values white. Anyone have thoughts? 

![Screen Shot 2020-05-28 at 5 40 48 PM](https://user-images.githubusercontent.com/32081685/83208406-6dacaf80-a10a-11ea-9e0a-69876c3f59ed.png)

The documentation appears to have been able to change the text colors to a light grey, but they don't mention how.

![Screen Shot 2020-05-28 at 5 43 42 PM](https://user-images.githubusercontent.com/32081685/83208543-d2680a00-a10a-11ea-8349-f1f1a6e7d237.png)

**Comment by wyze** [comment]
Looks like you can set the `theme` prop like so:

```jsx
<Radar theme={{ axis: { ticks: { text: { color: '#fff' } } } }} />
```
