### ISSUE TITLE
Enable slice tooltip for holes in data on mouse-hover

### ISSUE THREAD

**Issue by cheeyang** [plouc/nivo#975]
Hi, first of all, thank you for this amazing library.
Recently, I've come across the need to show "Unavailable" on the slice tooltip for holes in data.
As holes in data can only be shown with `null` values, it also means that the tooltip will not render null values over a `null` point. 

I've tried using the `sliceTooltip` prop in the `<Line/>` component, but it only allows me to customize the tooltip without the ability to control how it should render over a null x axis value.

Is there a way to do this with nivo?

Something like this : 
![image](https://user-images.githubusercontent.com/29735224/83221113-815a2380-a1a7-11ea-8bea-3c7f6462b632.png)

Thank you!

**Comment by wyze** [comment]
I'm not 100%, but might need a custom layer to do this. There was a PR merged recently that passed the currentSlice/currentPoint to custom layer, so we need a release before even trying that out.

**Comment by cheeyang** [comment]
> I'm not 100%, but might need a custom layer to do this. There was a PR merged recently that passed the currentSlice/currentPoint to custom layer, so we need a release before even trying that out.

@wyze Oh that's great news! Eagerly anticipating it then. Thank you!

**Comment by wyze** [comment]
I'll try and revisit a solution this week since we just cut a release for 0.62 which contains the data we need.

**Comment by cheeyang** [comment]
> I'll try and revisit a solution this week since we just cut a release for 0.62 which contains the data we need.

Hey @wyze, sure thing. Thank you! Any updates on this?

**Comment by cheeyang** [comment]
Hi guys, I've raised a pull request to handle this particular issue, please let me know your suggestions/feedback in order to get it merged asap :) 

I tried custom layers but it seems like it doesn't solve the issue because the slices are drawn differently when there are null values involved (screenshots included in the PR)

https://github.com/plouc/nivo/issues/975

**Comment by cheeyang** [comment]
bump

**Comment by cheeyang** [comment]
Bump
