### ISSUE TITLE
[Bar Chart] get width for maxValue in BarComponent

### ISSUE THREAD

**Issue by mamilov** [plouc/nivo#976]
**Is your feature request related to a problem? Please describe.**
For my project, I'm using the bar chart with a custom bar component. This component draws the bar as well as adds a background to show the full width of the bar (e.g. maxValue=100). I'm currently not able to draw the full width because the width property of BarItemProps is the width of the bar for the value, not the full width

**Describe the solution you'd like**
I would like to have a separate property that has the width of the chart for the maxValue.

**Describe alternatives you've considered**
I tried calculating the total width using the width and the value, but the full width always differs because the width value is rounded, which means that multiple charts would slightly differ in their length depending on the value.

**Additional context**
If anyone has an easier solution for this problem, I would be happy to hear it.

**Comment by wyze** [comment]
Hi @mamilov, would you mind putting a CodeSandbox together to help easier visualize what is happening?

**Comment by mamilov** [comment]
Hi @wyze, done: [CodeSandbox](https://codesandbox.io/s/black-architecture-cmhfl?file=/src/App.tsx)
I noticed that it is visible when the value shown is below 10. I believe there is some kind of rounding happening for the width value which causes this.

**Comment by wyze** [comment]
Oh I think I follow. Instead of a custom bar component, you should use a custom layer and replace the `bars` layer. There you will receive much more props than a custom bar component and should be able to solve your issue.

**Comment by mamilov** [comment]
Yes, that was it! It's working now as expected. Thanks!
