### ISSUE TITLE
@nivo/line - Cannot read property 'map' of undefined`

### ISSUE THREAD

**Issue by jj0b** [plouc/nivo#977]
**Describe/explain the bug**

With a brand new create-react-app, when I use the @nivo/line sample code from https://nivo.rocks/line/ and run the app I get this error:

`TypeError: Cannot read property 'map' of undefined`

**To Reproduce**

1. Create new create-react-app
2. npm install @nivo/line
3. Add component with sample code from https://nivo.rocks/line/ and add to App.js
4. Make sure the containing div has a height set
5. npm start

I created a demo on codesandbox where you can view the complete error:

https://codesandbox.io/live/z63g2

This is the first time I've used codesandbox, so please let me know if you have any issues accessing the sample code.

**Expected behavior**
I expected to see the graph displayed without errors.

**Desktop**
 - OS: Mac OS 10.15.4
 - Browser Chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by wyze** [comment]
In your example, you would want to change the `{MyResponsiveLine(data)}` to `{MyResponsiveLine({ data })}`.

**Comment by jj0b** [comment]
> In your example, you would want to change the `{MyResponsiveLine(data)}` to `{MyResponsiveLine({ data })}`.

Doh! Developer error. Thank you. I'll close this.
