### ISSUE TITLE
Can not disable points on stacked area graph

### ISSUE THREAD

**Issue by Amp1lfy** [plouc/nivo#980]
Hello,

I have been trying forever with no progress on disabling line points. This what my stacked area graph comes out as.

![Screen Shot 2020-06-04 at 6 03 07 PM](https://user-images.githubusercontent.com/64943430/83815507-592e6100-a68e-11ea-875b-6d7358252a99.png)

Here is the code im using, I have tried every option I can think of to disable the points.

```jsx
<ResponsiveLine
        data={data}
        enablePoints={false}
        margin={{ top: 50, right: 110, bottom: 120, left: 60 }}
        yScale={{
          type: "linear",
          stacked: true,
        }}
        curve="linear"
        xScale={{
          type: "time",
          format: "%Y-%m-%dT%H:%M:%S.%LZ",
        }}
        axisBottom={{
          orient: "bottom",
          format: "%m",
          tickValues: 5,
          tickSize: 5,
          tickPadding: 0,
          tickRotation: 0,
          legend: "Date",
          legendOffset: 66,
          legendPosition: "center",
        }}
        axisLeft={{
          orient: "left",
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Devices and Platform",
          legendOffset: -40,
          legendPosition: "center",
        }}
        enableArea={true}
        areaOpacity={1}
        useMesh={false}
        legends={[
          {
            anchor: "bottom-right",
            direction: "column",
            justify: false,
            translateX: 100,
            translateY: 0,
            itemsSpacing: 0,
            itemDirection: "left-to-right",
            itemWidth: 80,
            itemHeight: 20,
            itemOpacity: 0.75,
            symbolSize: 12,
            symbolShape: "circle",
            symbolBorderColor: "rgba(0, 0, 0, .5)",
            // effects: [
            //   {
            //     on: "hover",
            //     style: {
            //       itemBackground: "rgba(0, 0, 0, .03)",
            //       itemOpacity: 1,
            //     },
            //   },
            // ],
          },
        ]}
      />
```

Any advice would be appreciated. Thanks

**Comment by wyze** [comment]
What version of nivo are you using?

I put together a CodeSandbox (https://codesandbox.io/s/optimistic-ritchie-4udpw) using the code you provided above, minus time specific props. You can see that there are no points on my sandbox.

Can you provide a sandbox where you are experiencing the issue? Or maybe a little bit of the data you are using.

**Comment by Amp1lfy** [comment]
I believe nivo/line 0.62.0, also here is some sample data maybe you could try with the ResponsiveLine component I sent? 

[
        {
            "id": "A12E",
            "color": "hsl(95, 70%, 50%)",
            "data": [
                {
                    "x": "2020-06-04T20:05:09.000Z",
                    "y": "1"
                },
                {
                    "x": "2020-06-04T20:10:09.000Z",
                    "y": "3"
                },
                {
                    "x": "2020-06-04T20:15:09.000Z",
                    "y": "1"
                },
                {
                    "x": "2020-06-04T20:20:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:25:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T20:30:09.000Z",
                    "y": "6"
                },
                {
                    "x": "2020-06-04T20:35:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:40:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:45:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T20:50:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:55:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T21:00:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T21:05:09.000Z",
                    "y": "5"
                }
            ]
        },
        {
            "id": "Android Mobile",
            "color": "hsl(145, 70%, 50%)",
            "data": [
                {
                    "x": "2020-06-04T20:05:09.000Z",
                    "y": "3"
                },
                {
                    "x": "2020-06-04T20:10:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:15:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:20:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:25:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T20:30:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:35:09.000Z",
                    "y": "4"
                },
                {
                    "x": "2020-06-04T20:40:09.000Z",
                    "y": "6"
                },
                {
                    "x": "2020-06-04T20:45:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:50:09.000Z",
                    "y": "8"
                },
                {
                    "x": "2020-06-04T20:55:09.000Z",
                    "y": "1"
                },
                {
                    "x": "2020-06-04T21:00:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T21:05:09.000Z",
                    "y": "2"
                }
            ]
        },
        {
            "id": "ATV",
            "color": "hsl(195, 70%, 50%)",
            "data": [
                {
                    "x": "2020-06-04T20:05:09.000Z",
                    "y": "6"
                },
                {
                    "x": "2020-06-04T20:10:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:15:09.000Z",
                    "y": "8"
                },
                {
                    "x": "2020-06-04T20:20:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:25:09.000Z",
                    "y": "8"
                },
                {
                    "x": "2020-06-04T20:30:09.000Z",
                    "y": "7"
                },
                {
                    "x": "2020-06-04T20:35:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T20:40:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:45:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T20:50:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T20:55:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T21:00:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T21:05:09.000Z",
                    "y": "5"
                }
            ]
        },
        {
            "id": "Fire TV",
            "color": "hsl(245, 70%, 50%)",
            "data": [
                {
                    "x": "2020-06-04T20:05:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:10:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T20:15:09.000Z",
                    "y": "1"
                },
                {
                    "x": "2020-06-04T20:20:09.000Z",
                    "y": "4"
                },
                {
                    "x": "2020-06-04T20:25:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:30:09.000Z",
                    "y": "4"
                },
                {
                    "x": "2020-06-04T20:35:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:40:09.000Z",
                    "y": "1"
                },
                {
                    "x": "2020-06-04T20:45:09.000Z",
                    "y": "0"
                },
                {
                    "x": "2020-06-04T20:50:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T20:55:09.000Z",
                    "y": "2"
                },
                {
                    "x": "2020-06-04T21:00:09.000Z",
                    "y": "5"
                },
                {
                    "x": "2020-06-04T21:05:09.000Z",
                    "y": "10"
                }
            ]
        }
    ]

**Comment by wyze** [comment]
Updated my sandbox with the data you provided and it still removes the points. What is the size of your data you are passing to the chart?

**Comment by Amp1lfy** [comment]
It would be a lot bigger than the sample I sent, thousands probably, would that be too much?

**Comment by Amp1lfy** [comment]
Actually I still get dots with that small sample set

![Screen Shot 2020-06-04 at 7 13 19 PM](https://user-images.githubusercontent.com/64943430/83819314-86cbd800-a697-11ea-861c-c9e9eac9445e.png)

**Comment by plouc** [comment]
I don't think the dataset size would affect this behaviour, in worth case it would become really slow or 💥 , @Amp1lfy do you think you could reproduce this issue on codesandbox?

**Comment by Amp1lfy** [comment]
I can try yes, maybe I have some conflicting versions or something.

**Comment by plouc** [comment]
@Amp1lfy, are you importing the chart using `import { ResponsiveLine } from '@nivo/line'`?

**Comment by Amp1lfy** [comment]
Yes

**Comment by plouc** [comment]
Also all `@nivo` packages versions must be aligned, the chart uses underlying features from other packages.

**Comment by Amp1lfy** [comment]
Ok I think that maybe is the problem

**Comment by plouc** [comment]
The documentation is not mentioning it anywhere, it can be confusing 😅

**Comment by Amp1lfy** [comment]
Ok that was the problem, mixed versions, thanks so much

**Comment by plouc** [comment]
I'm glad you found a solution to your issue!
