### ISSUE TITLE
[Calendar Chart] Values inside calendar cell

### ISSUE THREAD

**Issue by ascotto** [plouc/nivo#981]
Hello, is there a way to add values inside of the day cell in the calendar graph?

I would like to recreate something like the image below with Nivo Calendar:
![image](https://user-images.githubusercontent.com/2669250/83853251-5165cf80-a715-11ea-8fc0-e4f8158c489d.png)

Thank you.

**Comment by wyze** [comment]
Currently not supported but seems like a good addition to add if you want to submit a PR.
