### ISSUE TITLE
Customize active line point

### ISSUE THREAD

**Issue by csaba-pusztai** [plouc/nivo#982]
**Is your feature request related to a problem? Please describe.**
I have been trying to figure out how to customise the active point in a line chart. I was looking at similar examples (e.g. synced scatter plot) but the line chart package seems to be structured differently. I tried to create a custom function to pass to to `pointSymbol`, but `isActive/isInactive` is not available there (as far as I understand). I also thought of piggybacking on the custom  callback function passed to `tooltip` but not sure hot to access/modify the respective component from there. I also tried via pure CSS (:hover), but had to realise that the overlaid mesh would not make it possible.

**Describe the solution you'd like**
I would like to be able to customise the active point symbol in a line chart (for which the tooltip is showing, slices disabled) by specifying styling attributes (or even a custom function to render the symbol).

**Describe alternatives you've considered**
(see above).

**Additional context**

**Comment by wyze** [comment]
The `points` layer doesn't receive the currentPoint/currentSlice, so one way would be to disable that layer and replace it with your own custom layer to render the points.

Other than that, we would need to decide on an elegant way to allow the Points layer to accept an `active` style and apply that to `DotsItem`.

**Comment by marcelojrfarias** [comment]
Waiting for news about this issue.. :|

**Comment by van-for-days** [comment]
bump

**Comment by p-abasian** [comment]
bump
