### ISSUE TITLE
Values not rendered in bar chart will affect selected colors, legend and maybe other properties

### ISSUE THREAD

**Issue by diegosps** [plouc/nivo#986]
**Describe/explain the bug**
When the height of the chart is not exaggerated, the component will skip the first color from scheme if the key value is so small that cant be rendered.

**To Reproduce**
Both charts with same data and same color scheme. The only difference is the height.
It seems the first color of the set is skiped in the first chart because it is unable to render it. resulting in different set of colors for both charts.

https://codesandbox.io/s/vigilant-lake-ml67g

**Expected behavior**
It shouldn't matter if the first key is small or not, the component should respect the correct order from selected scheme.

Thanks!

**Edit**
After seeing #1031,  I made another example to include the legend component:
https://codesandbox.io/s/adoring-snowflake-2ojr2

Apparently, It happens when the data value is equal to 0 too.

**Comment by diegosps** [comment]
This one has a [simple fix](https://github.com/plouc/nivo/issues/952#issuecomment-655105135). But I'm not sure about side effects.
Will submit a PR when the calendar one gets closed (I guess I need to refork it to keep commit history clean).

**Comment by wyze** [comment]
This appears to be fix with my latest pending PR, you can see a CodeSandbox with that version and your code here: https://codesandbox.io/s/nivo-forked-sivhw?file=/src/App.js
