### ISSUE TITLE
X axis values are overlapping on time scale based line chart

### ISSUE THREAD

**Issue by jithinbalakrishnan** [plouc/nivo#988]
X axis values are overlapping on time scale based line chart when i use tickValues: "every 5 days" or "every {x} days". 
![Screen Shot 2020-06-09 at 9 18 10 AM](https://user-images.githubusercontent.com/29042311/84104367-1f18e280-aa33-11ea-8092-11906ee5821e.png)
Here is the code 
https://codesandbox.io/s/late-violet-97gbt?file=/src/App.js
Actual use-case API is returning the data, here i used a loop create same data for reproducing the bug.
Is there any way to solve this issue ?

**Comment by ronandowlingcullen** [comment]
Having the same issue, any info would be much appreciated 👍

**Comment by annaudod** [comment]
We have the same problem and it looks like a broken for users. For the long-term graphs, there are always shows the first and last day of the month, which overlap each other.
![image](https://user-images.githubusercontent.com/55787241/84884645-ae10a500-b09a-11ea-94a0-508ae45f7a1a.png)

**Comment by fillippeyton** [comment]
I believe this is the same issue I'm having in #1101. Looks like it has to do with dates going over the month boundary. Using a string like `"every 5 days"` for the `tickValues` seems to cause this.

**Comment by fillippeyton** [comment]
bump

**Comment by nnieves22** [comment]
bump
