### ISSUE TITLE
Line graph : Y axis are inaccurate 

### ISSUE THREAD

**Issue by 32teeths** [plouc/nivo#989]
**Describe/explain the bug**
The line graph has bugs . The lines does not connect and y axis values are not accurate . The issue is present even in the demo of line graph . The values does not match and is inaccurate . 

**Expected behavior**
The expected . 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 83.0.4103.61

**Comment by plouc** [comment]
Please define inaccurate and not connected, possibly with screenshots because I have no idea what you’re referring to, afaik the demo isn’t broken. Are you aware that the line chart has a stacked mode, enabled on the demo? I’m not sure but maybe that’s what you talking about

**Comment by 32teeths** [comment]
@plouc  Thank you for quick response .Stacked one's are what we need .  For eg , y(plane) for japan being 244 is aligned correct to y axis . But y(place) for us is 18 and lies above japan and the value is not inclined to y axis .

**Comment by plouc** [comment]
@32teeths could you please share a screenshot of what you're describing? the demo data is random, so it's hard to check. As values are stacked having a lower value above a higher one isn't necessarily a clue, as you need to consider this value + all the values for the lines below.

I think things are working as expected:

<img width="605" alt="Capture d’écran 2020-06-11 à 19 21 58" src="https://user-images.githubusercontent.com/501642/84374430-f0f4f780-ac18-11ea-8328-404cc486fe88.png">

<img width="605" alt="Capture d’écran 2020-06-11 à 19 22 12" src="https://user-images.githubusercontent.com/501642/84374410-ec304380-ac18-11ea-8865-641c161d1990.png">

**Comment by 32teeths** [comment]
In the below case for norway y(helicopter)=56 but in the graph its aligned to somewhere around 740.

<img width="694" alt="Screenshot 2020-06-11 at 20 15 21" src="https://user-images.githubusercontent.com/1265466/84400954-526c9480-ac20-11ea-8455-24a473c89f87.png">

While in the below graph for germany , y(helicopter)=120 lies below 56 and is aligned to 660 . 
<img width="718" alt="Screenshot 2020-06-11 at 20 15 27" src="https://user-images.githubusercontent.com/1265466/84400968-57c9df00-ac20-11ea-894c-af4877003f96.png">

**Comment by plouc** [comment]
Yes, that’s the expected behavior, and that’s also why I’ve been asking about stacked, just turn this option off. The position of each dot is based. On it’s value plus the sum of all the values below. It’s clear on my screenshots where you can see all values.
