### ISSUE TITLE
Added yarn.lock to .gitignore

### ISSUE THREAD

**Issue by kaadash** [plouc/nivo#99]
I see that yarn.lock has been moved to .gitignore. I think that it should be still in repo (https://github.com/yarnpkg/yarn/issues/1583 ). I've created PR (https://github.com/plouc/nivo/pull/100). I will be really happy and proud of being contributor of such great library. Really good job!

**Comment by plouc** [comment]
@kaadash, you're right, it offers more consistent behavior.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/100.
