### ISSUE TITLE
Setting color scheme results in all-black pie-chart

### ISSUE THREAD

**Issue by LinusGeffarth** [plouc/nivo#990]
I managed to get this pie chart to work:

<img src="https://i.stack.imgur.com/gahlV.png" height="200">

For this, I used this slightly modified code from the example:

```js
<ResponsivePie
  data={data}
  margin={config.margins}
  padding={0.3}
  colors="nivo"
  borderColor="inherit:darker(1.6)"
  animate
  motionStiffness={90}
  motionDamping={15}
  legends={config.legends}
  sortByValue
  innerRadius={0}
  padAngle={0}
  cornerRadius={0}
  borderWidth={0}
  radialLabelsSkipAngle={10}
  radialLabelsTextXOffset={6}
  radialLabelsTextColor="#333333"
  radialLabelsLinkOffset={0}
  radialLabelsLinkDiagonalLength={16}
  radialLabelsLinkHorizontalLength={24}
  radialLabelsLinkStrokeWidth={1}
  radialLabelsLinkColor="#CCCCCC"
  slicesLabelsSkipAngle={10}
  slicesLabelsTextColor="#333333"
/>
```

Now, I wanted the colors to be a grayscale, so I changed the `colors` prop to "greys", as shown in the docs:

    colors={{ scheme: 'greys' }}

This results in:

<img src="https://i.stack.imgur.com/WUOpy.png" height="200">

I also tried:

    colors="greys"

Using `"greens"` also results in the same.

If you want to try it out:  
[![Open in CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-waterfall-befew?fontsize=14&hidenavigation=1&theme=dark)

Am I doing it wrong or is this a bug?

**Comment by lorgan3** [comment]
Try installing `@nivo/bar`, just `nivo` is an old version of the library

https://codesandbox.io/s/nivo-chart-coloring-g696n

**Comment by wyze** [comment]
Hi Linus. You should change your import from `nivo` to `@nivo/pie`. Then change the `colors` prop from `greys` to `{ scheme: 'greys' }`.

Here is my sandbox with the above changes: https://codesandbox.io/s/nivo-chart-coloring-budyc
