### ISSUE TITLE
Is there any way to hover and show point in line chart?

### ISSUE THREAD

**Issue by vuanhnguyeen** [plouc/nivo#993]
**Is your feature request related to a problem? Please describe.**
First of all, thank you to everyone who created the nivo chart, it's so great. I come from Vietnam. I use line chart nivo and custom like this. 
![image](https://user-images.githubusercontent.com/43888185/84583133-82ce5180-ae1f-11ea-8133-869825749636.png)

**Describe the solution you'd like**
I want to hover in line chart and show tooltip, show point in this line. and point line will hidden when move mouse leave.
**Describe alternatives you've considered**
I use `onMouseEnter={(point, event) => console.log('mouse: ', point, event)}` to log position points but it don't work with `enableSlices="x"`.  And I can't make auto show, hidden it. I read the storybook and I have no way to implement it.

**Additional context**
Regardless of any advice. Please let me know. I would like to thank everyone.

**Comment by wyze** [comment]
This is not the exact thing you requested, but I did this for someone else a couple days ago and sounds like it is exactly what you need. https://codesandbox.io/s/nivoline-custom-slices-layer-851lp

**Comment by plouc** [comment]
@vuanhnguyeen, when slices are enabled, invisible rects are used to capture interactions, so you cannot get the current point using the event handler anymore.

**Comment by vuanhnguyeen** [comment]
@plouc @wyze Thank everyone very much ^^

**Comment by Rohit1508** [comment]
@vuanhnguyeen I am trying to do something like that, as we have seen in the google stock chart, when we hover then only point are visible on line.
are u able to make it like this?

**Comment by ayushkul** [comment]
@Rohit1508 Were you able to find this?

**Comment by gregypooh** [comment]
@Rohit1508 @ayushkul did you figure it out?

**Comment by nikeshhm** [comment]
@Rohit1508 @ayushkul @gregypooh 
Here is the example it may help. If you are looking for this 
<img width="488" alt="Screenshot 2021-09-14 at 11 56 55 AM" src="https://user-images.githubusercontent.com/18121432/133206408-413c0673-2f39-4649-a4a9-5e3374a2ec8f.png">

https://codesandbox.io/s/bq8lb?file=/src/LineChart.js

**Comment by Maverick17user** [comment]
> @Rohit1508 @ayushkul @gregypooh Here is the example it may help. If you are looking for this <img alt="Screenshot 2021-09-14 at 11 56 55 AM" width="488" src="https://user-images.githubusercontent.com/18121432/133206408-413c0673-2f39-4649-a4a9-5e3374a2ec8f.png">
> 
> https://codesandbox.io/s/bq8lb?file=/src/LineChart.js

This example doesn't work =/

**Comment by jdavidferreira** [comment]
See: https://github.com/plouc/nivo/discussions/1602
