### ISSUE TITLE
Nivo Responsive Horizontal Bar - Numeric values are not showing in x-axis

### ISSUE THREAD

**Issue by sarthaksaxena01** [plouc/nivo#994]
I managed to get this horizontal bar chart to work:

<img width="273" alt="barIssue" src="https://user-images.githubusercontent.com/15171503/84627599-cf3f8d00-af04-11ea-8dc5-e2fa53dd0a1a.png">

I'm creating a Horizontal Bar chart using @Nivo Responsive bar, in the documentation(_https://nivo.rocks/bar_), it's written that **indexBy**(string or function, id by default) is a unique key used to index the data and have noticed that this value is showing always on x-axis ticks. But I need to show the values(**numbers** that can be unique/duplicate) in the y-axis ticks, not the keys as shown in the image attached.

If you want to try it out, Codesandbox link:
https://codesandbox.io/s/nivobar-axis-legend-text-color-443-3l129?file=/src/index.js

For this, I am using "@nivo/bar": "^0.52.0" and this is the code:
```
import React from "react";
import { render } from "react-dom";
import { ResponsiveBar } from "@nivo/bar";

let data = [
  {
    id: "One Plus",
    label: "Apple",
    value: 350
  },
  {
    id: "Samsung",
    label: "Samsung",
    value: 280
  },
  {
    id: "Nokia  C",
    label: "Nokia",
    value: 240
  }
];

data = data.sort((a, b) => a.value - b.value);

const theme = {
  labels: { text: { fontSize: 11 } },
  axis: {
    ticks: { text: { fontSize: 11, fill: "grey" } }
  }
};

const App = () => (
  <div
    style={{ width: "90%", height: "15em", float: "left", overflowY: "auto" }}
  >
    <ResponsiveBar
      height={150}
      layout="horizontal"
      margin={{
        top: 5,
        right: 5,
        bottom: 5,
        left: 35
      }}
      data={data}
      indexBy={_index => _index.value + ""}
      keys={["value"]}
      colors={["#cce4f2"]}
      colorBy="indexValue"
      groupMode="grouped"
      enableGridX={false}
      enableGridY={false}
      borderRadius={1}
      label={_label => _label.data.id}
      padding={0.2}
      labelFormat={d => <tspan x={40}>{d}</tspan>}
      axisLeft={{
        tickSize: 0,
        tickPadding: 5,
        tickRotation: 0
      }}
      axisBottom={null}
      labelTextColor="black"
      motionStiffness={170}
      motionDamping={26}
      theme={theme}
    />
  </div>
);

render(<App />, document.getElementById("root"));

```
As you can notice above, I have used indexBy as indexBy={_index => _index.value + ""} to convert the value from number to string.

**To Reproduce**
It failed when the values will be duplicate, as the keys are duplicate.
For eg, when data like:
```
const topBarData = [{
    id: 'One Plus', label: 'Apple', value: 350,
  },
  {
    id: 'Samsung', label: 'Samsung', value: 280,
  },
  {
    id: 'Nokia  C', label: 'Nokia', value: 280,
  }];
```
On duplicate values, it gives error as: **Encountered two children with the same key, `value.280`**
<img width="461" alt="barDuplicate" src="https://user-images.githubusercontent.com/15171503/84630635-dc12af80-af09-11ea-8aee-a22a97d25a53.png">

Am I doing it wrong or is this a bug?

**Comment by plouc** [comment]
@sarthaksaxena01 the y axis corresponding tick is the id as you're using a categorical scale, the value is bound to x axis in your case, axes are meant to be used with their corresponding data, I think what your trying to achieve here is a bit different. I think that given you need, you probably handle this by creating an extra layer or using a custom bar element.
