### ISSUE TITLE
Have x-axis wait for data to draw?

### ISSUE THREAD

**Issue by Amp1lfy** [plouc/nivo#998]
Hello,

I am wondering if this is possible. Right now I have a stacked area graph that is re-drawing from a button click. I have it set up to show time-frames such as: 1 Day, 1 Week, 1 Month. Say I am looking at 1 Week, when I click my button to change the graph to show 1 Month, the x-axis begins to draw the x-axis I have set up for the month view before that actual graph changes from the week data to the month data. Is there a way to make the x-axis wait until the new data is shown in the graph. Right now the x-axis starts transforming early. Sorry if this is difficult to explain but any feedback would be appreciated.

Thanks

**Comment by plouc** [comment]
Hello @Amp1lfy,

I think you could change the config of the x-axis only once the data has been fetched, nivo doesn't provide any built-in mechanisms to handle data fetching/loading states.

**Comment by Amp1lfy** [comment]
Ok thank you ill see what I can do

**Comment by plouc** [comment]
I'm gonna close this as it's outside the scope of the lib to handle async data fetching, I think you can achieve what you want by adjusting the chart props depending on the loading state.
Please do not hesitate if you have any questions regarding this approach.
